import { defineKnowledgeOpenQuestions } from '../../../schema';

export const frigilianaClimateSeasonOpenQuestions = defineKnowledgeOpenQuestions([
  { id: 'frigiliana.climate.question-local-monthly-series', subject: 'frigiliana', topic: 'climate-seasons', question: 'Which explicit ERA5-Land cells, reference period, variables, aggregation rules and uncertainty boundary can support comparable Frigiliana and Nerja monthly series?', priority: 'high', reason: 'ERA5-Land is now selected as the reproducible comparison candidate, but Málaga Airport remains the only extracted official normal and the current public Frigiliana and Nerja values are identical.', preferredEvidence: 'Reproducible Copernicus CDS extraction for declared Frigiliana and Nerja cells with request, raw output, variables, units, conversions, reference period and validation against suitable AEMET stations.', status: 'researching', createdAt: '2026-08-28' },
  { id: 'frigiliana.climate.question-nerja-difference', subject: 'frigiliana', topic: 'climate-seasons', question: 'Which measured evidence can distinguish Frigiliana from Nerja without applying a generic elevation lapse rate?', priority: 'high', reason: 'Elevation, terrain and maritime influence justify caution but not an exact temperature difference.', preferredEvidence: 'Comparable station or raster series for both declared locations and periods.', status: 'open', createdAt: '2026-08-28' },
  { id: 'frigiliana.climate.question-local-wind-normal', subject: 'frigiliana', topic: 'climate-seasons', question: 'Is there a methodologically suitable local wind-normal dataset for the village and relevant exposed routes?', priority: 'medium', reason: 'Current wind forecasts and coastal stations cannot be converted into a village climate normal.', preferredEvidence: 'AEMET station metadata or a documented competent raster product with local limitations.', status: 'open', createdAt: '2026-08-28' },
  { id: 'frigiliana.climate.question-external-reference-points', subject: 'frigiliana', topic: 'climate-seasons', question: 'Which official reference stations elsewhere in Andalusia, Spain and northern Europe can put the coastal summer maximum in context for a guest deciding when to travel?', priority: 'high', reason: 'The published monthly table gives a July daily maximum of about 27 °C, which means nothing to a reader without a comparison. Every existing climate question compares Frigiliana with Nerja; none looks outward. A sourced comparison would also be the honest counterpart to the neighbouring Torrox "best climate in Europe" claim, which the evidence pool already records as a 2008 commissioned comparison of 22 Mediterranean coastal locations.', preferredEvidence: 'AEMET climate normals for two or three inland Andalusian stations such as Seville and Córdoba, taken from the same provider and the same reference period as the existing Málaga Airport extraction, plus one comparable northern European normal from an equivalent official service. Same period, same variables, same definitions, or the comparison is not publishable.', status: 'resolved', createdAt: '2026-08-30' },
  { id: 'frigiliana.climate.question-home-capital-references', subject: 'frigiliana', topic: 'climate-seasons', question: 'What are the official monthly climate normals for Berlin, London, Madrid and Stockholm on the same 1981-2010 reference period already used for Sevilla, Cordoba, Malaga and Schiphol?', priority: 'high', reason: 'The 2026-08-30 run settled the period and extracted two of six references. London Heathrow is complete from the Met Office; Stockholm is covered for the summer months at city level from SMHI. Berlin, Madrid and the three Spanish stations were confirmed to have the right 1991-2020 product but their values sit in download payloads, XLSX files and API responses the run could not read. The German, Spanish and Dutch editions therefore still have no home anchor, and the Andalusian comparison on the pages still rests on superseded 1981-2010 values.', preferredEvidence: 'Original payloads rather than rendered web pages. For the Spanish stations the AEMET OpenData endpoint /api/valores/climatologicos/normales/estacion/{idema} for 5783, 5402, 6155A and 3195 - never the classic station pages, which still show 1981-2010. For Berlin the DWD CDC mean_91-20 files for station 403 Berlin-Dahlem(FU), with the parameter definition confirmed so the mean of daily maxima is not confused with the monthly mean temperature. For Schiphol the KNMI 1991-2020 station climate table. For Stockholm the SMHI normal files, to bind the city figure to a station and extend it beyond summer.', status: 'open', createdAt: '2026-08-30' },
] as const);
