import { defineKnowledgeOpenQuestions } from '../../../schema';

export const frigilianaClimateSeasonOpenQuestions = defineKnowledgeOpenQuestions([
  { id: 'frigiliana.climate.question-local-monthly-series', subject: 'frigiliana', topic: 'climate-seasons', question: 'Which explicit ERA5-Land cells, reference period, variables, aggregation rules and uncertainty boundary can support comparable Frigiliana and Nerja monthly series?', priority: 'high', reason: 'ERA5-Land is now selected as the reproducible comparison candidate, but Málaga Airport remains the only extracted official normal and the current public Frigiliana and Nerja values are identical.', preferredEvidence: 'Reproducible Copernicus CDS extraction for declared Frigiliana and Nerja cells with request, raw output, variables, units, conversions, reference period and validation against suitable AEMET stations.', status: 'researching', createdAt: '2026-08-28' },
  { id: 'frigiliana.climate.question-nerja-difference', subject: 'frigiliana', topic: 'climate-seasons', question: 'Which measured evidence can distinguish Frigiliana from Nerja without applying a generic elevation lapse rate?', priority: 'high', reason: 'Elevation, terrain and maritime influence justify caution but not an exact temperature difference.', preferredEvidence: 'Comparable station or raster series for both declared locations and periods.', status: 'open', createdAt: '2026-08-28' },
  { id: 'frigiliana.climate.question-local-wind-normal', subject: 'frigiliana', topic: 'climate-seasons', question: 'Is there a methodologically suitable local wind-normal dataset for the village and relevant exposed routes?', priority: 'medium', reason: 'Current wind forecasts and coastal stations cannot be converted into a village climate normal.', preferredEvidence: 'AEMET station metadata or a documented competent raster product with local limitations.', status: 'open', createdAt: '2026-08-28' },
  { id: 'frigiliana.climate.question-external-reference-points', subject: 'frigiliana', topic: 'climate-seasons', question: 'Which official reference stations elsewhere in Andalusia, Spain and northern Europe can put the coastal summer maximum in context for a guest deciding when to travel?', priority: 'high', reason: 'The published monthly table gives a July daily maximum of about 27 °C, which means nothing to a reader without a comparison. Every existing climate question compares Frigiliana with Nerja; none looks outward. A sourced comparison would also be the honest counterpart to the neighbouring Torrox "best climate in Europe" claim, which the evidence pool already records as a 2008 commissioned comparison of 22 Mediterranean coastal locations.', preferredEvidence: 'AEMET climate normals for two or three inland Andalusian stations such as Seville and Córdoba, taken from the same provider and the same reference period as the existing Málaga Airport extraction, plus one comparable northern European normal from an equivalent official service. Same period, same variables, same definitions, or the comparison is not publishable.', status: 'resolved', createdAt: '2026-08-30' },
  { id: 'frigiliana.climate.question-home-capital-references', subject: 'frigiliana', topic: 'climate-seasons', question: 'What are the official monthly climate normals for Berlin, London, Madrid and Stockholm on the same 1981-2010 reference period already used for Sevilla, Cordoba, Malaga and Schiphol?', priority: 'high', reason: 'The weather pages now put the July figure on a scale using Andalusian stations, and the Dutch edition can also name Schiphol. The other four editions have no home reference, so a German, British, Spanish or Swedish reader still has nothing familiar to measure the number against. Each locale should see its own capital rather than a shared foreign one.', preferredEvidence: 'Official station normals published by the national services themselves for the 1981-2010 period, giving mean daily maximum, monthly precipitation and where available sunshine hours: DWD for Berlin, the Met Office for London, AEMET for Madrid and SMHI for Stockholm. DWD does publish 1981-2010 long-term means, so the shared period is attainable. If any service publishes only 1991-2020, say so rather than mixing periods silently, and never compute normals from daily data.', status: 'open', createdAt: '2026-08-30' },
] as const);
