import { defineKnowledgeOpenQuestions } from '../../../schema';

export const frigilianaHikingOpenQuestions = defineKnowledgeOpenQuestions([
  { id: 'frigiliana.hiking.question-live-route-status', subject: 'frigiliana', topic: 'hiking-weather-return', question: 'What authority and live-check method establish current access, closures and exceptional conditions for each of the four routes?', priority: 'high', reason: 'Published route profiles do not establish day-specific safety or openness.', preferredEvidence: 'Current municipal, protected-area or GR authority notices plus AEMET warnings on the intended date.', status: 'open', createdAt: '2026-08-28' },
  { id: 'frigiliana.hiking.question-amara-start-return', subject: 'casa-amara', topic: 'hiking-weather-return', question: 'What exact first-party route connects each apartment, the official start and the return/recovery context?', priority: 'high', reason: 'Casa AMARA must not be described as an official trailhead and map plausibility cannot replace a host walkthrough.', preferredEvidence: 'Dated operator walk with unit, endpoint, time, steps, gradient, daylight and return notes.', status: 'open', createdAt: '2026-08-28' },
  { id: 'frigiliana.hiking.question-gr249-return-transport', subject: 'frigiliana', topic: 'hiking-weather-return', question: 'Which current, pre-bookable return options make the linear GR 249 Frigiliana–Cómpeta stage usable for AMARA guests?', priority: 'high', reason: 'A long linear stage needs a planned return and cannot rely on an assumed same-day bus.', preferredEvidence: 'Current transport operator or taxi evidence and a dated host test.', status: 'open', createdAt: '2026-08-28' },
  { id: 'frigiliana.hiking.question-post-route-food', subject: 'frigiliana', topic: 'hiking-weather-return', question: 'Which personally tested food choices genuinely fit the finish time and position of each route?', priority: 'medium', reason: 'A restaurant link becomes useful only when the restaurant owner contains the relevant timing, location and operating evidence.', preferredEvidence: 'Direct restaurant operation evidence plus dated AMARA route-and-meal notes.', status: 'open', createdAt: '2026-08-28' },
  { id: 'frigiliana.hiking.question-candidate-route-identities', subject: 'frigiliana', topic: 'hiking-weather-return', question: 'What verified tracks and endpoints define the proposed short El Fuerte viewpoint route and Lízar/Acequia loop, and is any proposed Acebuchal loop distinct from the official 13-kilometre out-and-back route?', priority: 'high', reason: 'The supplemental research did not find official definitions for the short El Fuerte or Lízar/Acequia variants, while the municipal Acebuchal route explicitly returns over the outward line.', preferredEvidence: 'Dated first-party GPX walkthroughs reconciled with current municipal or protected-area route information.', status: 'open', createdAt: '2026-08-28' },
] as const);
