import { defineKnowledgeOpenQuestions } from '../../../schema';

export const frigilianaSupermarketsOpenQuestions = defineKnowledgeOpenQuestions([
  { id: 'frigiliana.shopping-current-everyday-network', subject: 'frigiliana', topic: 'supermarkets-everyday-shopping', question: 'Which current shops and areas form a durable everyday grocery network for visitors?', priority: 'high', reason: 'Existing public copy is not a source-verified, dated shopping model.', preferredEvidence: 'Official operator listings, municipal sources and a dated field check.', status: 'researching', createdAt: '2026-08-22' },
  { id: 'frigiliana.shopping-host-route', subject: 'frigiliana', topic: 'supermarkets-everyday-shopping', question: 'What shopping route do we genuinely recommend from Casa AMARA with and without a car?', priority: 'high', reason: 'Host guidance requires first-party evidence and must not be inferred from a map.', preferredEvidence: 'Dated host walkthrough with transport mode, terrain and practical trade-offs.', status: 'open', createdAt: '2026-08-22' },
  { id: 'frigiliana.shopping-market-current-operation', subject: 'frigiliana', topic: 'supermarkets-everyday-shopping', question: 'What are the current authority, exact location, hours, cancellation logic and vendor mix of the Thursday market?', priority: 'high', reason: 'The current municipal site supports Thursday and provides stall-application forms, but does not publish the operating details; current third-party listings disagree on the location and cannot authorize public claims.', preferredEvidence: 'Dated written confirmation or a current notice from the Ayuntamiento or responsible market authority, followed by a dated field check.', status: 'researching', createdAt: '2026-08-28' },
  { id: 'frigiliana.shopping-nerja-arrival-network', subject: 'frigiliana', topic: 'supermarkets-everyday-shopping', question: 'Which larger Nerja shops genuinely help with arrival supplies for Casa AMARA, and under which car or non-car scenario?', priority: 'medium', reason: 'The new run did not verify a bounded arrival-shopping set strongly enough for host guidance.', preferredEvidence: 'Retailer-operated store records plus dated operator route and parking checks.', status: 'open', createdAt: '2026-08-28' },
  { id: 'frigiliana.shopping-recipe-kitchen-matrix', subject: 'casa-amara', topic: 'supermarkets-everyday-shopping', question: 'Which candidate regional preparations can Farah, Lounis, Zaid and Maha each support with their verified kitchen equipment?', priority: 'high', reason: 'A generic kitchen claim would collapse property differences and could make recipe guidance unusable.', preferredEvidence: 'Dated property-by-property inventory and operator preparation check.', status: 'open', createdAt: '2026-08-28' },
  { id: 'frigiliana.shopping-seasonal-ingredient-availability', subject: 'frigiliana', topic: 'supermarkets-everyday-shopping', question: 'Which regional ingredients are realistically available by season, from which shop or market, and with what verified provenance?', priority: 'medium', reason: 'Regional production, local sale and current shelf stock are separate claims.', preferredEvidence: 'Producer or DOP evidence, current direct retailer evidence and seasonal field checks.', status: 'open', createdAt: '2026-08-28' },
] as const);
