import { defineKnowledgePageManifest } from '../../schema';

export const frigilianaExperienceKnowledge = defineKnowledgePageManifest({
  id: 'page-frigiliana-experience',
  destination: 'frigiliana',
  topic: 'experience-hub',
  createdAt: '2026-08-28T18:00:00+02:00',
  updatedAt: '2026-08-28T18:00:00+02:00',
  status: 'needs-review',
  driveFolder: {
    id: '1FxPa56b3GnZt8XwUUcx5qEnlscUbjvA6',
    url: 'https://drive.google.com/drive/folders/1FxPa56b3GnZt8XwUUcx5qEnlscUbjvA6',
    path: 'AMARA – Research Vault/10_LOCATIONS/nerja/experiences/beaches/2026-08-28__092356__nerja-frigiliana-beaches-connections__research-001',
  },
  publicContentPath: 'src/content/experienceHubContent.ts',
  researchRunIds: [
    '2026-08-24__121344__frigiliana-semantic-corpus-recovery__research-001',
    '2026-08-24__121345__frigiliana-three-cultures-evidence__research-001',
    '2026-08-24__121346__frigiliana-streetscape-overnight-atmosphere__research-001',
    '2026-08-24__121347__frigiliana-agriculture-lived-landscape__research-001',
    '2026-08-28__092355__frigiliana-climate-seasons-decisions__research-001',
    '2026-08-28__092356__nerja-frigiliana-beaches-connections__research-001',
    '2026-08-28__092357__frigiliana-hiking-weather-return__research-001',
    '2026-08-28__092358__frigiliana-nerja-restaurants-evenings__research-001',
    '2026-08-28__092359__frigiliana-shopping-local-food-cooking__research-001',
  ],
  coverage: [
    {
      authoringArea: 'direct-answer-and-day-choice',
      purpose: 'Answer how guests can shape shared holiday days from Frigiliana through one variable, curated menu rather than a fixed itinerary.',
      factIds: [
        'frigiliana.geography.sierra.protected-area-context',
        'frigiliana.atmosphere.evening-quiet.observation',
        'frigiliana.climate.regional-proxy.seasonal-contrast',
      ],
      status: 'partial',
      notes: 'These facts support destination range and conditional choice, not the current repeated catalogue, generic wellness, nightlife or an all-purpose “best things” claim.',
    },
    {
      authoringArea: 'single-curated-selection-surface',
      purpose: 'Present each approved day form once and route to the canonical spoke that owns the full answer.',
      factIds: [
        'frigiliana.hiking.cruz-pinto.route-profile',
        'nerja.beaches.burriana.profile-and-listed-services',
        'frigiliana.restaurants.the-garden.position-and-format',
        'frigiliana.shopping.mercadillo.thursday-reference',
        'frigiliana.heritage.historic-ensemble.bic',
      ],
      status: 'partial',
      notes: 'Hiking, beaches, restaurants and Old Town have usable premises. Market remains evidence-light; festivals, day trips and wellness lack sufficient current coverage. The present editorial, moods and catalog repetition must be consolidated during authoring.',
    },
    {
      authoringArea: 'hiking-day-form',
      purpose: 'Offer hiking as a choice by commitment and conditions while leaving route comparison and safety with the Hiking owner.',
      factIds: [
        'frigiliana.hiking.cruz-pinto.route-profile',
        'frigiliana.hiking.cahorros.route-profile-and-riverbed',
        'frigiliana.hiking.el-fuerte.route-profile',
        'frigiliana.hiking.gr249-stage6.route-profile',
      ],
      status: 'partial',
      notes: 'The hub may distinguish four commitments but must not reproduce route detail or imply live openness.',
    },
    {
      authoringArea: 'coast-day-form',
      purpose: 'Offer coast days as choices by access, setting and rhythm from a Frigiliana base.',
      factIds: [
        'nerja.beaches.burriana.profile-and-listed-services',
        'nerja.beaches.playazo.profile-and-listed-services',
        'nerja.beaches.maro.profile-and-seasonal-access',
        'nerja.beaches.calahonda.stair-access',
        'nerja.beaches.cantarrijan.location-and-seasonal-access',
      ],
      status: 'partial',
      notes: 'The hub may show that different coast-day forms exist. Beach selection, current sea state, parking and quietness remain with the Beaches owner.',
    },
    {
      authoringArea: 'food-and-evening-day-form',
      purpose: 'Offer a meal or evening by location and occasion without duplicating the restaurant catalogue.',
      factIds: [
        'frigiliana.restaurants.the-garden.position-and-format',
        'frigiliana.restaurants.la-taperia.position-and-cuisine',
        'frigiliana.restaurants.gloria-bendita.position-and-concept',
        'nerja.restaurants.oliva.position-terrace-and-service-2026',
        'nerja.restaurants.restaurant34.sea-terrace-and-service-2026',
        'nerja.evenings.cochrans.amara-sunset-visit-2025',
        'nerja.evenings.cochrans.amara-playa-walk-2025',
      ],
      status: 'partial',
      notes: 'Cochran’s supplies one genuine AMARA sundowner continuation from central Nerja and a bounded AMARA Playa walk. Exact restaurant pairings, tables and dishes remain unverified.',
    },
    {
      authoringArea: 'old-town-day-form',
      purpose: 'Offer an attentive old-town walk while keeping the complete history and visible-route narrative with the Old Town owner.',
      factIds: [
        'frigiliana.heritage.historic-ensemble.bic',
        'frigiliana.heritage.streets.adarves-algorfas',
        'frigiliana.heritage.san-antonio.baroque',
        'frigiliana.heritage.ingenio.origin-and-adaptation',
      ],
      status: 'partial',
      notes: 'Durable heritage context exists; a verified visible walk and ceramic-panel provenance remain open.',
    },
    {
      authoringArea: 'market-day-form',
      purpose: 'Treat the weekly market as a Thursday outing rather than as supermarket information.',
      factIds: ['frigiliana.shopping.mercadillo.thursday-reference'],
      status: 'gap',
      notes: 'Only a Thursday reference is partially verified. Current location, hours, cancellation logic, vendor mix and a tested onward old-town sequence remain open.',
    },
    {
      authoringArea: 'festival-day-form',
      purpose: 'Offer an event only when its current dates and operational consequences are verified.',
      factIds: [
        'frigiliana.culture.three-cultures-festival.first-edition-2006',
        'frigiliana.culture.three-cultures-festival.current-purpose',
      ],
      status: 'gap',
      notes: 'Historical identity and current stated purpose do not authorize dates, programme, crowd, access or stay consequences for a future edition.',
    },
    {
      authoringArea: 'day-trips',
      purpose: 'Offer regional excursions only after realistic journey, ticket and return evidence is normalized.',
      factIds: [],
      status: 'gap',
      notes: 'No evaluated Frigiliana day-trip fact set currently authorizes the public catalogue or travel-time comparisons.',
    },
    {
      authoringArea: 'wellness',
      purpose: 'Offer rest or treatment choices only when the provider, place, booking boundary and property permission are verified.',
      factIds: [],
      status: 'gap',
      notes: 'Current mobile-treatment and provider claims have no evaluated owner. Private terrace rest belongs to the bounded AMARA return lens, not a generic wellness-provider claim.',
    },
    {
      authoringArea: 'nightlife',
      purpose: 'Prevent an unsupported Nerja nightlife narrative from becoming part of the Frigiliana Experience Hub.',
      factIds: [],
      status: 'excluded',
      notes: 'Remove or withhold the current nightlife story until a separately approved owner and evidence set exist.',
    },
    {
      authoringArea: 'village-versus-coast-stay-choice',
      purpose: 'Keep the accommodation-base decision with Location rather than repeating it inside Experience.',
      factIds: [],
      status: 'excluded',
      notes: 'The current `places` section belongs to the Location Hub job. Experience may reference the base only when it changes a specific day choice.',
    },
    {
      authoringArea: 'romantic-hideaway-return-lens',
      purpose: 'Complete selected day forms with truthful private shared-time consequences at Casa AMARA.',
      factIds: [
        'casa-amara.location.calle-chorruelo-calle-real',
        'casa-amara.terraces.shared-amenities',
        'casa-amara.terraces.sunset-observation',
      ],
      status: 'partial',
      notes: 'Lounis, Zaid and Maha support a bounded terrace/shower/hammock return scene. Farah and exact day-to-property routes require separate evidence; the hub must not turn this into a full inventory pitch.',
    },
    {
      authoringArea: 'natural-transitions',
      purpose: 'Create the next guest question inside the relevant day form before routing to Weather, Hiking, Beaches, Restaurants, Old Town or a property owner.',
      factIds: [
        'frigiliana.climate.regional-proxy.seasonal-contrast',
        'frigiliana.heritage.historic-ensemble.bic',
        'nerja.restaurants.ayo.burriana-daytime-service-2026',
        'nerja.evenings.cochrans.amara-sunset-visit-2025',
        'nerja.evenings.cochrans.amara-playa-walk-2025',
        'casa-amara.terraces.shared-amenities',
      ],
      status: 'partial',
      notes: 'Weather-to-activity, Burriana-to-AYO and a central-Nerja-to-Cochran’s sundowner from AMARA Playa now have bounded premises. Hiking-to-food and a named restaurant-to-sundowner pair remain open.',
    },
    {
      authoringArea: 'closing-and-conversion',
      purpose: 'Route to Romantic Hideaways only after useful destination curation has established the desired shared-time rhythm.',
      factIds: [
        'casa-amara.portfolio.four-stays-three-apartments-one-suite',
        'casa-amara.location.calle-chorruelo-calle-real',
        'casa-amara.terraces.shared-amenities',
      ],
      status: 'partial',
      notes: 'The conversion boundary is supported at portfolio level. Exact unit fit and availability remain with Romantic Hideaways, property pages and the booking boundary.',
    },
  ],
});
