import { defineKnowledgeFacts } from '../../../schema';

export const nerjaWhereToStayFacts = defineKnowledgeFacts([
  { id: 'nerja.stay.models.practical-not-administrative', subject: 'nerja', topic: 'where-to-stay-areas', statement: 'The useful Nerja accommodation models are practical combinations of beaches, streets, landmarks and urbanisations rather than one verified set of equal administrative neighbourhoods.', status: 'partially-verified', sourceIds: ['nerja-carabeo-official-2026', 'nerja-burriana-official-2026', 'nerja-planning-map-2026'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'Public copy must call them areas or location models, not official district boundaries.' },
  { id: 'nerja.stay.carabeo.stepped-access', subject: 'nerja', topic: 'where-to-stay-areas', statement: 'Official visitor information describes stepped access to Playa del Carabeo.', status: 'verified', sourceIds: ['nerja-carabeo-official-2026'], checkedAt: '2026-08-21', reviewAfter: '2027-08-21', volatility: 'low', claimBoundary: 'This does not describe every route from the wider Carabeo or Parador area.' },
  { id: 'nerja.stay.carabeillo.stepped-access', subject: 'nerja', topic: 'where-to-stay-areas', statement: 'Official visitor information describes stepped access to Playa del Carabeíllo.', status: 'verified', sourceIds: ['nerja-carabeillo-official-2026'], checkedAt: '2026-08-21', reviewAfter: '2027-08-21', volatility: 'low', claimBoundary: 'A beach-access fact, not a universal accommodation-accessibility claim.' },
  { id: 'nerja.stay.burriana.infrastructure', subject: 'nerja', topic: 'where-to-stay-areas', statement: 'Burriana has official beach-service, access, transport and municipal-parking infrastructure.', status: 'verified', sourceIds: ['nerja-burriana-official-2026', 'nerja-municipal-parking-rule-2021'], checkedAt: '2026-08-21', reviewAfter: '2027-08-21', volatility: 'medium', claimBoundary: 'This does not make the route from every Burriana accommodation to central Nerja flat or accessible.' },
  { id: 'nerja.stay.outer-clusters.separate', subject: 'nerja', topic: 'where-to-stay-areas', statement: 'Capistrana/San Juan de Capistrana and Punta Lara are separate spatial anchors and should not be presented as one homogeneous outer-hills area.', status: 'partially-verified', sourceIds: ['nerja-planning-map-2026'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'Exact tourism-area polygons and address-level mobility still require mapping.' },
  { id: 'nerja.stay.amara-playa.routes', subject: 'nerja', topic: 'where-to-stay-areas', statement: 'Existing AMARA Playa distance, quietness and access statements are operator-authored property claims.', status: 'first-party-observation', sourceIds: ['amara-nerja-location-baseline-2026'], checkedAt: '2026-08-21', volatility: 'medium', claimBoundary: 'They must remain property-specific and need a documented entrance, route and accessibility evidence pack for precise measurements.' }
] as const);
