import { defineKnowledgeFacts } from '../../../schema';

export const nerjaWinterStaysFacts = defineKnowledgeFacts([
  { id: 'nerja.winter.cueva-open-pattern-2026', subject: 'nerja', topic: 'winter-stays', statement: 'The Cueva de Nerja publishes a 2026 opening pattern covering the full year with specified closure dates.', status: 'verified', sourceIds: ['nerja-winter-cueva-hours-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'high', claimBoundary: 'Use as a concrete 2026 all-weather anchor, not as proof that all Nerja attractions are open year-round; guests must check current hours.' },
  { id: 'nerja.winter.museum-open-pattern-2026', subject: 'nerja', topic: 'winter-stays', statement: 'Museo de Nerja publishes 2026 hours from Tuesday to Sunday throughout the year, with Monday also open from June through September.', status: 'verified', sourceIds: ['nerja-winter-museum-hours-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'high', claimBoundary: 'Schedule is specific to 2026 and must be rechecked; it does not establish wider town opening patterns.' },
  { id: 'nerja.winter.museum-year-round-programme', subject: 'nerja', topic: 'winter-stays', statement: 'Museo de Nerja describes a programme of cultural activities throughout the year.', status: 'verified', sourceIds: ['nerja-winter-museum-hours-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'high', claimBoundary: 'Specific events and dates remain dynamic and cannot be promised without a current programme.' },
  { id: 'nerja.winter.maro-shuttle-summer-2025', subject: 'nerja', topic: 'winter-stays', statement: 'The referenced municipal Maro beach shuttle operated as a summer service from 14 June to 15 September 2025.', status: 'verified', sourceIds: ['nerja-winter-maro-shuttle-2025'], checkedAt: '2026-08-21', reviewAfter: '2027-05-21', volatility: 'high', claimBoundary: 'Historical 2025 operating dates; do not infer later schedules or total winter transport availability.' },
  { id: 'nerja.winter.lifeguard-summer-2026', subject: 'nerja', topic: 'winter-stays', statement: 'Nerja’s referenced 2026 municipal beach surveillance and lifeguard operation is described as a summer service.', status: 'verified', sourceIds: ['nerja-winter-lifeguard-2026'], checkedAt: '2026-08-21', reviewAfter: '2027-05-21', volatility: 'high', claimBoundary: 'This does not by itself define winter bathing safety; current sea, beach and official safety information is required.' },
  { id: 'nerja.winter.dedicated-page-absent', subject: 'nerja', topic: 'winter-stays', statement: 'At research intake on 21 August 2026, AMARA had no dedicated Nerja winter-stays content owner.', status: 'superseded', sourceIds: ['amara-nerja-winter-baseline-2026'], checkedAt: '2026-08-21', volatility: 'high', claimBoundary: 'Historical repository-state fact superseded later the same day by the new public content owner; it never established external demand.' }
] as const);
