import { defineKnowledgeFacts } from '../../schema';

export const winterTravelMarketFacts = defineKnowledgeFacts([
  { id: 'market.winter.etc.travel-intent-2025', subject: 'european-winter-travel', topic: 'winter-stays', statement: 'In the ETC autumn 2025 / winter 2026 survey, 73% of respondents planned to travel between October 2025 and March 2026.', status: 'verified', sourceIds: ['winter-etc-travel-intent-2025'], checkedAt: '2026-08-21', reviewAfter: '2027-02-21', volatility: 'medium', claimBoundary: 'Surveyed travel intention in ten European source markets, not completed bookings and not demand specifically for Spain or AMARA.' },
  { id: 'market.winter.etc.cross-border-intent-2025', subject: 'european-winter-travel', topic: 'winter-stays', statement: 'In the same ETC survey horizon, 63% of respondents intended to travel outside their home country.', status: 'verified', sourceIds: ['winter-etc-travel-intent-2025'], checkedAt: '2026-08-21', reviewAfter: '2027-02-21', volatility: 'medium', claimBoundary: 'Cross-border intention does not identify Spain, Andalusia or an accommodation type.' },
  { id: 'market.winter.etc.one-holiday-2025', subject: 'european-winter-travel', topic: 'winter-stays', statement: 'ETC reported that 45% of respondents expected to take only one holiday between October 2025 and March 2026.', status: 'verified', sourceIds: ['winter-etc-travel-intent-2025'], checkedAt: '2026-08-21', reviewAfter: '2027-02-21', volatility: 'medium', claimBoundary: 'This describes planned holiday count, not the duration or destination of that holiday.' },
  { id: 'market.winter.etc.month-shift-2025', subject: 'european-winter-travel', topic: 'winter-stays', statement: 'ETC reported that 28% of travellers from eight major European source markets planned to shift travel to different months over the following two years.', status: 'verified', sourceIds: ['winter-etc-season-shift-2025'], checkedAt: '2026-08-21', reviewAfter: '2027-02-21', volatility: 'medium', claimBoundary: 'Future stated intention; it does not prove that the shift will be to winter or to Spain.' },
  { id: 'market.winter.etc.shift-motives-2025', subject: 'european-winter-travel', topic: 'winter-stays', statement: 'In the ETC month-shift finding, avoiding crowds was the primary stated motive, with saving money and escaping extreme heat also important.', status: 'verified', sourceIds: ['winter-etc-season-shift-2025'], checkedAt: '2026-08-21', reviewAfter: '2027-02-21', volatility: 'medium', claimBoundary: 'Aggregate motives cannot be assigned to every winter guest or converted into health, temperature or price promises.' },
  { id: 'market.winter.spain.germany-spend-indicator-2025', subject: 'german-winter-travel-to-spain', topic: 'winter-stays', statement: 'Turespaña’s 2025/26 winter outlook reported a 4.3% increase in German international tourism spending in Spain.', status: 'verified', sourceIds: ['winter-tourspain-outlook-2025'], checkedAt: '2026-08-21', reviewAfter: '2027-02-21', volatility: 'high', claimBoundary: 'Retain the exact Turespaña reporting context; this is not a destination-level booking forecast for Andalusia or AMARA.' },
  { id: 'market.winter.spain.netherlands-spend-indicator-2025', subject: 'dutch-winter-travel-to-spain', topic: 'winter-stays', statement: 'Turespaña’s 2025/26 winter outlook reported 10.3% growth in Dutch tourism spending in Spain.', status: 'verified', sourceIds: ['winter-tourspain-outlook-2025'], checkedAt: '2026-08-21', reviewAfter: '2027-02-21', volatility: 'high', claimBoundary: 'A national spend indicator does not quantify winter stays in Nerja, Frigiliana or Tarifa.' },
  { id: 'market.winter.spain.sweden-preference-2025', subject: 'swedish-winter-travel-to-spain', topic: 'winter-stays', statement: 'Turespaña’s 2025/26 winter outlook reported Spain leading Swedish consideration at 39.3% and travel intention at 16.1%.', status: 'verified', sourceIds: ['winter-tourspain-outlook-2025'], checkedAt: '2026-08-21', reviewAfter: '2027-02-21', volatility: 'high', claimBoundary: 'Preference indicators are not bookings and do not establish destination, accommodation or duration choice.' },
  { id: 'seo.winter.nerja-rentals-monthly-intent', subject: 'winter-stays-search-intent', topic: 'winter-stays', statement: 'The English “winter rentals Nerja” result set inspected in this run included offers framed around monthly winter rental.', status: 'partially-verified', sourceIds: ['winter-nerja-rentals-serp-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'high', claimBoundary: 'Qualitative SERP observation only; no search volume or total-market share follows.' },
  { id: 'seo.winter.nerja-overwinteren-multiweek-intent', subject: 'winter-stays-search-intent', topic: 'winter-stays', statement: 'A Dutch result for “overwinteren Nerja” marketed a multi-week packaged stay.', status: 'partially-verified', sourceIds: ['winter-nerja-overwinteren-serp-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'high', claimBoundary: 'One commercial result illustrates expectation risk; it does not quantify Dutch demand.' },
  { id: 'market.winter.torrox.claim-origin', subject: 'torrox', topic: 'winter-stays', statement: 'A 2008 EFE report attributed Torrox’s “best climate in Europe” claim to a Meteogroup study sponsored by Grupo El Fuerte.', status: 'verified', sourceIds: ['torrox-winter-climate-claim-2008'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'Historical account of a commissioned comparison, not a current official or peer-reviewed Europe-wide ranking.' },
  { id: 'market.winter.torrox.claim-scope', subject: 'torrox', topic: 'winter-stays', statement: 'The reported 2008 comparison covered Torrox and 21 other Mediterranean coastal locations over the preceding seven years.', status: 'verified', sourceIds: ['torrox-winter-climate-claim-2008'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'The sample and period do not establish a universal European superlative and cannot be transferred to Nerja or Frigiliana.' }
] as const);
