import { defineKnowledgeSources } from '../../schema';

export const frigilianaDayTripsSources = defineKnowledgeSources([
  {
    id: 'caminito-del-rey-official-2026',
    title: 'Caminito del Rey — official visitor site',
    publisher: 'Caminito del Rey / Diputación de Málaga',
    sourceType: 'official',
    url: 'https://www.caminitodelrey.info/en',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'Official booking and information: one-way linear route, ~3–4 h including access paths, helmet provided and mandatory, minimum age 8 with ID check, no changes or refunds, not recommended for vertigo.',
    limitations: 'FAQ is thin on the exact sell-out lead time and the precise shuttle frequency by direction.',
    reuse: 'link-and-cite',
  },
  {
    id: 'caminito-del-rey-parking-shuttle-2026',
    title: 'Caminito del Rey — parking & shuttle bus (CRV)',
    publisher: 'Caminito del Rey / Diputación de Málaga',
    sourceType: 'official',
    url: 'https://www.caminitodelrey.info/en/your-visit/parking-shuttle-bus-crv',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'Shuttle bus links the two ends, €2.50 per person, cash only, not included in the ticket, ~15–20 min; reservable parking at the CRV (Puerto de las Atalayas) on the north side, €2/day.',
    limitations: 'The micro-geography of the CRV versus the north control point and the El Chorro end is easy to confuse; verify against the official map.',
    reuse: 'link-and-cite',
  },
  {
    id: 'diputacion-malaga-ardales-embalses-2026',
    title: 'Embalses de Ardales / Mirador de los Tres Embalses',
    publisher: 'Diputación de Málaga / Caminito del Rey',
    sourceType: 'official',
    url: 'https://www.caminitodelrey.info/en/discover-the-surroundings',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'The Guadalhorce reservoirs beside the north end of the Caminito: the Mirador de los Tres Embalses, turquoise water, pine woods and swimming spots (Playa del Pantano) — the natural Plan B when the walkway is sold out.',
    limitations: 'Facilities and swimming access are seasonal.',
    reuse: 'link-and-cite',
  },
  {
    id: 'alhambra-patronato-visit-2026',
    title: 'Visit the Alhambra — official tickets and rules',
    publisher: 'Patronato de la Alhambra y Generalife',
    sourceType: 'official',
    url: 'https://www.alhambra-patronato.es/en/visit',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'Official channel for tickets; the Nasrid Palaces carry a fixed printed time slot that cannot be changed, ID is required at entry, and slots sell out weeks to months ahead; a "Gardens, Generalife and Alcazaba" ticket exists without the Nasrid Palaces.',
    limitations: 'Day-to-day availability of each ticket category is not fixed and must be checked live.',
    reuse: 'link-and-cite',
  },
  {
    id: 'alhambra-de-granada-itinerarios-2026',
    title: 'Alhambra itineraries and walking times',
    publisher: 'alhambradegranada.org',
    sourceType: 'secondary',
    url: 'https://www.alhambradegranada.org/en/info/visitthealhambra.asp',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'Walking distances inside the complex: roughly 10–17 minutes on foot from the entrance pavilion to the Nasrid Palaces, full circuit ~3.5 km / ~3 hours.',
    limitations: 'A well-known information site, not the Patronato itself.',
    reuse: 'link-and-cite',
  },
  {
    id: 'visita-malaga-official-2026',
    title: 'Málaga official visitor information',
    publisher: 'Ayuntamiento de Málaga (visita.malaga.eu)',
    sourceType: 'official',
    url: 'https://visita.malaga.eu/',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'Municipal tourism portal: monuments and museums, opening regime and closing days (Carmen Thyssen closed Mondays, Centre Pompidou closed Tuesdays), the Alcazaba and its access.',
    limitations: 'Individual venue hours change seasonally and by public holiday.',
    reuse: 'link-and-cite',
  },
  {
    id: 'museo-picasso-malaga-official-2026',
    title: 'Museo Picasso Málaga — visit',
    publisher: 'Museo Picasso Málaga',
    sourceType: 'official',
    url: 'https://www.museopicassomalaga.org/en/plan-your-visit',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'Timed-entry booking; the museum is open daily (including Mondays), so it does not share the common Monday closure.',
    limitations: 'Seasonal hours vary; last entry is shortly before closing.',
    reuse: 'link-and-cite',
  },
  {
    id: 'malaga-catedral-cubiertas-2026',
    title: 'Málaga Cathedral — rooftop visit (Cubiertas)',
    publisher: 'Catedral de Málaga (malagacatedral.com)',
    sourceType: 'official',
    url: 'https://malagacatedral.com/',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'The rooftop tour ("La Manquita", 200+ steps, ~50 m) and its current status; the tour was suspended for roof works as of September 2026.',
    limitations: 'The suspension is temporary; availability must be checked at the time of travel.',
    reuse: 'link-and-cite',
  },
  {
    id: 'malaga-alcazaba-lift-press-2025',
    title: 'El nuevo ascensor para subir a la Alcazaba de Málaga',
    publisher: 'El Español (press)',
    sourceType: 'secondary',
    url: 'https://www.elespanol.com/malaga/',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'The new lift (in service since May 2025) on Calle Guillén Sotelo behind the town hall reaches the Alcazaba interior (Casa Palacio), replacing the earlier free public lift; it now requires an Alcazaba ticket.',
    limitations: 'Secondary press report; the ticket requirement is reported, and the Alcazaba is free on Sundays from 14:00 per the municipal regime.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-ronda-official-2026',
    title: 'Ronda official visitor information',
    publisher: 'Turismo de Ronda',
    sourceType: 'official',
    url: 'https://info.turismoderonda.es/',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'Official tourism: the Puente Nuevo over the ~120 m Tajo gorge, the old and new town, the Plaza de Toros and the Alameda del Tajo.',
    limitations: 'Access and pricing for the gorge viewpoints change; the 2024 paid-access change to the former free mirador is not always reflected.',
    reuse: 'link-and-cite',
  },
  {
    id: 'wikipedia-plaza-toros-ronda-2026',
    title: 'Plaza de toros de Ronda',
    publisher: 'Wikipedia',
    sourceType: 'secondary',
    url: 'https://en.wikipedia.org/wiki/Plaza_de_toros_de_Ronda',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'Bullring built 1779–1785; described as one of the oldest and the first built entirely of stone — the nuanced framing behind the disputed "oldest bullring" claim.',
    limitations: 'Tertiary encyclopaedia; "oldest" is contested (Seville’s Maestranza was begun earlier), so use the "one of the oldest / first all-stone" framing.',
    reuse: 'link-and-cite',
  },
  {
    id: 'ronda-wine-serrania-dop-2026',
    title: 'Serranía de Ronda wine (DOP Sierras de Málaga)',
    publisher: 'spain.info / Rutas del Vino',
    sourceType: 'secondary',
    url: 'https://www.spain.info/en/region/ronda/',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'Ronda is wine country as the Serranía de Ronda subzone of the DOP Sierras de Málaga; there is no separate "D.O. Ronda".',
    limitations: 'General tourism/wine-route source.',
    reuse: 'link-and-cite',
  },
  {
    id: 'rome2rio-drive-times-2026',
    title: 'Drive-time estimates from Frigiliana',
    publisher: 'Rome2Rio / ViaMichelin',
    sourceType: 'discovery-tool',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'Route-planner drive estimates from Frigiliana: Málaga ~55 min (~60 km), Granada ~1 h 5–1 h 15 (~99 km), Caminito ~1 h 30–40, Ronda ~2 h 15; Ronda→Setenil ~20–30 min.',
    limitations: 'Planner values without traffic or parking search; real door-to-door times run longer.',
    reuse: 'internal-only',
  },
  {
    id: 'wikipedia-caminito-del-rey-2026',
    title: 'Caminito del Rey',
    publisher: 'Wikipedia',
    sourceType: 'secondary',
    url: 'https://en.wikipedia.org/wiki/Caminito_del_Rey',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'History: built as an access walkway for the hydroelectric works in the Gaitanes gorge (1901–1905), named after King Alfonso XIII who crossed it in 1921 to inaugurate the Conde del Guadalhorce dam; it fell into a dangerous state and reopened after a full restoration in 2015.',
    limitations: 'Tertiary encyclopaedia; dates are well established but presented as summary history.',
    reuse: 'link-and-cite',
  },
  {
    id: 'wikipedia-puente-nuevo-ronda-2026',
    title: 'Puente Nuevo (Ronda)',
    publisher: 'Wikipedia',
    sourceType: 'secondary',
    url: 'https://en.wikipedia.org/wiki/Puente_Nuevo_(Ronda)',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      'The Puente Nuevo over the El Tajo gorge: begun 1759, completed 1793 after decades of work, spanning a drop of well over a hundred metres between the old and new town.',
    limitations: 'Tertiary encyclopaedia; the gorge depth is commonly given around 100–120 m.',
    reuse: 'link-and-cite',
  },
  {
    id: 'amara-day-trips-web-synthesis-2026',
    title: 'Amara web synthesis — Frigiliana day trips (Málaga, Granada, Caminito del Rey, Ronda)',
    publisher: 'AMARA Research Vault (web synthesis)',
    sourceType: 'discovery-tool',
    accessedAt: '2026-09-12',
    language: 'de',
    scope:
      'Commissioned 2026-09-12 synthesis consolidating the official and secondary sources above, with a claim audit that corrected the Málaga Alcazaba lift (now ticketed, not free), the cathedral rooftop status (suspended), the Granada entrance-to-Nasrid walking time (~15 min, not ~30), the Caminito shuttle terms and the Ronda "oldest bullring" framing.',
    limitations:
      'A synthesis of official and secondary web sources; individual claims inherit the confidence of their underlying source and are not new primary evidence.',
    reuse: 'internal-only',
  },
] as const);

export type FrigilianaDayTripsSourceId = (typeof frigilianaDayTripsSources)[number]['id'];
