import { defineKnowledgeSources } from '../../schema';

export const frigilianaFestivalsSources = defineKnowledgeSources([
  {
    id: 'frigiliana-turismo-fiestas',
    title: 'Fiestas y tradiciones',
    publisher: 'Oficina de Turismo / Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/fiestas-y-tradiciones.html',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Best basis for the core calendar and relative scale of the representative festivals.',
    limitations: 'Evergreen/promotional page, not a live calendar; individual texts can reflect an older state.',
    reuse: 'link-and-cite'
  },
  {
    id: 'frigiliana-turismo-san-sebastian',
    title: 'San Sebastián',
    publisher: 'Oficina de Turismo / Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/san-sebastian.html',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Official tradition page for the 20 January feast and the historic move of the big feria to June.',
    limitations: 'Not sufficient for the given year programme.',
    reuse: 'link-and-cite'
  },
  {
    id: 'frigiliana-turismo-carnaval',
    title: 'Carnaval',
    publisher: 'Oficina de Turismo / Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/carnaval.html',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Strong for the experience form, route type and night effect.',
    limitations: 'Concrete route/date can change each year; date is movable relative to Lent.',
    reuse: 'link-and-cite'
  },
  {
    id: 'frigiliana-turismo-semana-santa',
    title: 'Semana Santa',
    publisher: 'Oficina de Turismo / Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/s-santa.html',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Extensive primary description of the traditional sequence including the nocturnal Soledad.',
    limitations: 'Some historic/evaluative phrasing is promotional; year dates are movable.',
    reuse: 'link-and-cite'
  },
  {
    id: 'frigiliana-turismo-cruces',
    title: 'Cruces de Mayo / Día de la Cruz',
    publisher: 'Oficina de Turismo / Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/dia-de-la-cruz.html',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Good for the experience and the late verbena.',
    limitations: 'Evergreen page with no reliable future-year programme.',
    reuse: 'link-and-cite'
  },
  {
    id: 'frigiliana-turismo-miel',
    title: 'Día de la Miel de Caña',
    publisher: 'Oficina de Turismo / Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/dia-de-la-miel.html',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Valuable because it explicitly states there is no fixed day.',
    limitations: 'Statements on factory opening, tastings etc. are format, not an upcoming guarantee.',
    reuse: 'link-and-cite'
  },
  {
    id: 'frigiliana-turismo-feria',
    title: 'Feria de San Antonio',
    publisher: 'Oficina de Turismo / Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/feria.html',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Excellent primary source for the actual noise/night character of the feria.',
    limitations: 'The static "five days" description is not reliable year to year.',
    reuse: 'link-and-cite'
  },
  {
    id: 'frigiliana-turismo-3culturas',
    title: 'Festival 3 Culturas (tourism overview)',
    publisher: 'Oficina de Turismo / Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/festival-3-culturas.html',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Evidences origin 2006, typical formats, late August and scale.',
    limitations: 'Visitor numbers read as non-audited tourism self-reporting.',
    reuse: 'link-and-cite'
  },
  {
    id: 'festival-3culturas-site',
    title: 'Festival Frigiliana 3 Culturas — main site',
    publisher: 'Festival / Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana3culturas.com/',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Most current official festival hub.',
    limitations: 'Programmes and year dates are highly volatile.',
    reuse: 'link-and-cite'
  },
  {
    id: 'festival-3culturas-conoce',
    title: 'Conoce el Festival 3 Culturas',
    publisher: 'Festival Frigiliana 3 Culturas / Ayuntamiento',
    sourceType: 'official',
    url: 'https://frigiliana3culturas.com/festival-3-culturas/conoce-el-festival-3-culturas-frigiliana/',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Very valuable for visitor reality: crowds, street operation, night programme, market, PA, venues.',
    limitations: 'Parts such as tapa price and piromusical position can be outdated.',
    reuse: 'link-and-cite'
  },
  {
    id: 'festival-3culturas-ediciones',
    title: 'Ediciones anteriores (3 Culturas editions archive)',
    publisher: 'Festival Frigiliana 3 Culturas / Ayuntamiento',
    sourceType: 'official',
    url: 'https://frigiliana3culturas.com/festival-3-culturas/ediciones-anteriores/',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Evidences long-running recurrence and the 2020/21 pandemic interruption.',
    limitations: 'The archive itself does not appear complete/evenly maintained on all points.',
    reuse: 'link-and-cite'
  },
  {
    id: 'festival-3culturas-parking-2026',
    title: 'Servicio de parking y lanzadera (2026)',
    publisher: 'Festival Frigiliana 3 Culturas / Ayuntamiento',
    sourceType: 'official',
    url: 'https://frigiliana3culturas.com/informacion-de-interes/servicio-de-parking-y-lanzadera/',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Very strong for 2026 planning reality (park-and-ride and evening shuttle).',
    limitations: 'Times, stops and parking areas must not be carried over to later years.',
    reuse: 'link-and-cite'
  },
  {
    id: 'festival-3culturas-espacios',
    title: 'Espacios de actividades y conciertos',
    publisher: 'Festival Frigiliana 3 Culturas / Ayuntamiento',
    sourceType: 'official',
    url: 'https://frigiliana3culturas.com/informacion-de-interes/espacios-de-actividades-y-conciertos/',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Evidences the spatial spread across the town.',
    limitations: 'Specific stage allocation remains year-dependent.',
    reuse: 'link-and-cite'
  },
  {
    id: 'festival-3culturas-press-2025',
    title: 'Nota de prensa — sábado 30 de agosto de 2025',
    publisher: 'Festival / Departamento de Comunicación, Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana3culturas.com/nota-de-prensa-sabado-30-de-agosto-de-2025/',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Strong reality check against generic festival copy: daytime operation, parades, market, night concerts/DJ until late.',
    limitations: 'The 2025 edition only.',
    reuse: 'link-and-cite'
  },
  {
    id: 'festival-3culturas-announce-2026',
    title: 'Frigiliana celebrará una nueva edición… 27–30 agosto 2026',
    publisher: 'Ayuntamiento / Festival 3 Culturas',
    sourceType: 'official',
    url: 'https://frigiliana3culturas.com/frigiliana-celebrara-una-nueva-edicion-del-festival-3-culturas-del-27-al-30-de-agosto-de-2026/',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Evidences current institutional continuation and the late-August window.',
    limitations: 'The edition number "XIV" it gives conflicts with other sources and is not adopted.',
    reuse: 'link-and-cite'
  },
  {
    id: 'frigiliana-ayuntamiento-site',
    title: 'Ayuntamiento de Frigiliana — current website',
    publisher: 'Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana.es/',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Primary place for municipal notices.',
    limitations: 'On the check day the event module showed no upcoming events, so no full year calendar is derivable.',
    reuse: 'link-and-cite'
  },
  {
    id: 'frigiliana-ayuntamiento-candelarias-2019',
    title: 'El 7 de septiembre Frigiliana celebrará la fiesta de las Candelarias',
    publisher: 'Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana.es/el-7-de-septiembre-frigiliana-celebrara-la-fiesta-de-las-candelarias/',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Municipal notice from 2019; evidences a revival/event that year.',
    limitations: 'Does not prove annual continuity to 2026.',
    reuse: 'link-and-cite'
  },
  {
    id: 'frigiliana-ayuntamiento-candelarias-hoguera',
    title: 'Una gran hoguera recuerda el día de las Candelarias',
    publisher: 'Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana.es/una-gran-hoguera-recuerda-el-dia-de-las-candelarias/',
    accessedAt: '2026-09-10',
    language: 'es',
    scope: 'Key counter-evidence against a blanket annual Candelarias festival: calls the original celebration extinct due to the fire ban, with a later commemorative form possible.',
    limitations: 'A commemorative form is not proof of annual continuity.',
    reuse: 'link-and-cite'
  },
  {
    id: 'axarquiaplus-regional-press',
    title: 'AxarquíaPlus regional press / social corroboration (Carnaval 2026, Feria 2026, Candelarias 2022)',
    publisher: 'AxarquíaPlus',
    sourceType: 'secondary',
    url: 'https://www.axarquiaplus.es/',
    accessedAt: '2026-09-10',
    scope: 'Regional press/social used only for year-specific corroboration (e.g. 21 Feb 2026 carnival parade, 11–14 June 2026 feria, a 2022 Candelarias event).',
    limitations: 'Corroboration only; not a basis for evergreen dates or annual continuity.',
    reuse: 'link-and-cite'
  },
  {
    id: 'turismo-frigiliana-social',
    title: 'Turismo Frigiliana social communication (San Sebastián 2026, Día de la Miel XI)',
    publisher: 'Turismo Frigiliana',
    sourceType: 'secondary',
    url: 'https://www.facebook.com/TurismoFrigiliana/',
    accessedAt: '2026-09-10',
    scope: 'Official social channel used for year examples: an extended San Sebastián 2026 programme and the XI Día de la Miel announced for 2 May.',
    limitations: 'Year example, not a new date rule; the Miel announcement is contradicted by a "CANCELADO" post, so it is not proof of execution.',
    reuse: 'link-and-cite'
  },
  {
    id: 'cadena-ser-3culturas-2025',
    title: 'Festival 3 Culturas 2025 — preview',
    publisher: 'Cadena SER',
    sourceType: 'secondary',
    url: 'https://cadenaser.com/',
    accessedAt: '2026-09-10',
    scope: 'Secondary source for cross-checking the 2025 programme, in particular the piromusical as a closing act.',
    limitations: 'No substitute for the organiser source.',
    reuse: 'link-and-cite'
  }
] as const);

export type FrigilianaFestivalsSourceId = (typeof frigilianaFestivalsSources)[number]['id'];
