import { defineKnowledgeSources } from '../../schema';

export const frigilianaOldTownMonumentsSources = defineKnowledgeSources([
  {
    id: 'amara-old-town-monuments-operator-brief-2026',
    title: 'AMARA operator brief — Frigiliana old-town monuments (Fuente Vieja, Castillo de Lizar, Reales Pósitos, Ermita de Ecce Homo, Callejón del Peñón)',
    publisher: 'AMARA (operator: Robert Sebastian Böhmer)',
    sourceType: 'operator-provided',
    accessedAt: '2026-09-11',
    language: 'de',
    scope:
      'Operator-supplied brief with first datings and attributions for five further old-town sights, used as the authoring baseline before the 2026-09-12 web synthesis.',
    limitations:
      'A first-party operator brief, not an independent scholarly source; superseded on specific points by the researched municipal/heritage sources below (Ermita procession day, Fuente Vieja fabric, Castillo razing chain, Callejón view claim).',
    reuse: 'internal-only',
  },
  {
    id: 'boja-decreto-183-2014-frigiliana-conjunto-historico',
    title: 'Decreto 183/2014, de 23 de diciembre, por el que se inscribe en el CGPHA como BIC, tipología Conjunto Histórico, el sector delimitado de la Villa de Frigiliana',
    publisher: 'Junta de Andalucía — BOJA nº 23, 04/02/2015',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/boja/2015/23/26',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'The authoritative legal act: BIC / Conjunto Histórico inscription of the delimited old-town sector; the instrucciones particulares (white façade "deberá ser blanco", curved ceramic roof tile "teja cerámica curva", original design/material/dimensions for historic woodwork and grilles), the Torreón de la calle Real, and the adarves as mixed public-private spaces.',
    limitations:
      'Dated 23 December 2014; legally effective on BOJA publication 4 February 2015. The decree does not name minor lane names such as "Callejón del Peñón".',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-siglo-xvi-xix',
    title: 'Del siglo XVI al XIX (historia de Frigiliana)',
    publisher: 'Ayuntamiento de Frigiliana — Turismo',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/del-neolitico-a-nuestros-dias/del-siglo-xvi-al-xix.html',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'Municipal history: the Fuente Vieja built c.1640 by Don Íñigo Manrique de Lara (fifth Señor of Frigiliana and first Count of the villa), its original name "Fuente Nueva", and the counts’ palace (El Ingenio) built with material from the Arab castle.',
    limitations: 'Municipal self-presentation; concise, without architectural detail or the number of spouts.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-monumentos',
    title: 'Monumentos',
    publisher: 'Ayuntamiento de Frigiliana — Turismo',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/monumentos.html',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'Municipal monument overview: Los Reales Pósitos (1767, brick arcades, cellars, now housing) and the Ermita de Ecce Homo with its Miércoles Santo (Holy Wednesday) procession to the church of San Antonio.',
    limitations: 'A short overview page; no per-monument depth.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-barribarto',
    title: 'El Barribarto',
    publisher: 'Ayuntamiento de Frigiliana — Turismo',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/el-barribarto.html',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'The Barribarto upper quarter: the name as a deformation of "Barrio Alto", its adarves, and the local "tajo del peñón" mirador.',
    limitations: 'Promotional tourism copy; not a legal or scholarly source.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-el-fuerte',
    title: 'El Fuerte',
    publisher: 'Ayuntamiento de Frigiliana — Turismo',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/el-fuerte.html',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'El Fuerte as the ~963 m summit and 1569 battle site, reached from the Plaza del Ingenio past Pozo and Molino de Lízar — establishing that El Fuerte is distinct from the lower Castillo de Lizar over the town core.',
    limitations: 'Promotional/route copy.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-info-fuentes',
    title: 'Las Fuentes de Frigiliana — La Fuente Vieja',
    publisher: 'El Patrimonio de Frigiliana (frigiliana.info)',
    sourceType: 'secondary',
    url: 'https://www.frigiliana.info/fuentes-de-frigiliana.php?tema=3.3.4',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'Architectural description of the Fuente Vieja: two storeys separated by an entablature, pilasters, a semicircular pediment with pinnacles, pomegranate motifs, three spouts (two diamond-framed, one square) and the counts’ (casa De Lara) coat of arms in the central field of the upper storey.',
    limitations: 'A local heritage compendium; descriptive, no restoration history.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-info-reales-positos',
    title: 'Los Reales Pósitos',
    publisher: 'El Patrimonio de Frigiliana (frigiliana.info)',
    sourceType: 'secondary',
    url: 'https://www.frigiliana.info/reales-positos.php?tema=3.3.3',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'The Reales Pósitos: built 1767 by the Counts of Frigiliana to hold, store, distribute and sell the grain of their lands; original three-nave ground floor with round arches, of which only the façade arcades and the cellar vaults survive; the institution documented from 1749 and probably established around 1640; today private housing.',
    limitations: 'Secondary local-history source; no official catalogue sheet, no exact street number.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-info-ermita-ecce-homo',
    title: 'Ermita del Ecce Homo',
    publisher: 'El Patrimonio de Frigiliana (frigiliana.info)',
    sourceType: 'secondary',
    url: 'https://www.frigiliana.info/ermita-del-ecce-homo.php?tema=3.2.2',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'The Ermita de Ecce Homo: first built in the 18th century and heavily remodelled; a front portico over a round arch, a small altar in the cabecera; the carried figure neo-Baroque of the later 20th century; the Miércoles Santo procession.',
    limitations: 'Secondary local-history source.',
    reuse: 'link-and-cite',
  },
  {
    id: 'diputacion-malaga-ermita-ecce-homo',
    title: 'Ermita del Ecce Homo o Capilla del Santo Cristo (Patrimonio)',
    publisher: 'Diputación de Málaga',
    sourceType: 'official',
    url: 'https://www.malaga.es/en/laprovincia/patrimonio/lis_cd-5275/ermita-del-ecce-homo-o-capilla-del-santo-cristo',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'Provincial heritage sheet for the Ermita: single nave, front atrium over a round arch, epistle side against the hillside, the Miércoles Santo procession to San Antonio, and the 20th-century image.',
    limitations: 'Direct fetch returned HTTP 403; content confirmed via identically mirrored provincial/Axarquía catalogue text.',
    reuse: 'link-and-cite',
  },
  {
    id: 'diputacion-malaga-fuente-vieja',
    title: 'Fuente Vieja (Patrimonio)',
    publisher: 'Diputación de Málaga',
    sourceType: 'official',
    url: 'https://www.malaga.es/en/laprovincia/patrimonio/lis_cd-5391/fuente-vieja',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'Provincial heritage sheet confirming the Fuente Vieja’s c.1640 build, its builder and its original name "Fuente Nueva".',
    limitations: 'Direct fetch returned HTTP 403; confirmed via search snippet only.',
    reuse: 'link-and-cite',
  },
  {
    id: 'conocetusfuentes-fuente-vieja-3209',
    title: 'La Fuente Vieja (ficha 3209)',
    publisher: 'Conoce tus Fuentes (Universidad de Granada / Junta de Andalucía)',
    sourceType: 'secondary',
    url: 'https://www.conocetusfuentes.com/ficha_detalle.php?id_fuente=3209',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'Andalusian fountain inventory sheet: builder and title, water from the Sierra Almijara, a 1990s restoration (coat of arms, wall decoration and pomegranate branches reconstructed), current good state, and the Plaza de la Fuente Vieja location off Calle Chorruelo.',
    limitations: 'The 1990s restoration is attested only here; treat as single-source.',
    reuse: 'link-and-cite',
  },
  {
    id: 'lpmbe-frigiliana-castillo-arabe',
    title: 'Restos del Castillo Árabe · Frigiliana',
    publisher: 'Los Pueblos más Bonitos de España',
    sourceType: 'secondary',
    url: 'https://lospueblosmasbonitosdeespana.org/pueblos/frigiliana/pois/restos-del-castillo-arabe',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'The castle on the crown of the cerro de Lízar, ~4,000 m², with two dating hypotheses (9th c. / Almoravid ~11th c.); razed after 1569 on the order of Don Luis de Requesens with Philip II’s approval; only limited remains.',
    limitations: 'A curated village-association POI entry, not an archaeological report.',
    reuse: 'link-and-cite',
  },
  {
    id: 'lpmbe-frigiliana-reales-positos',
    title: 'Reales Pósitos · Frigiliana',
    publisher: 'Los Pueblos más Bonitos de España',
    sourceType: 'secondary',
    url: 'https://lospueblosmasbonitosdeespana.org/pueblos/frigiliana/pois/reales-positos',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'The Reales Pósitos POI: 1767, the pósito institution (1749/1640), surviving arcades and cellars, now private.',
    limitations: 'A short POI entry.',
    reuse: 'link-and-cite',
  },
  {
    id: 'wikipedia-es-castillo-frigiliana',
    title: 'Castillo de Frigiliana',
    publisher: 'Wikipedia (ES)',
    sourceType: 'secondary',
    url: 'https://es.wikipedia.org/wiki/Castillo_de_Frigiliana',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'The 9th–11th-century Arab castle, its 1569 razing under Requesens, the reuse of its cut stone for the Manrique de Lara palace (El Ingenio), the ~4,000 m² area and BIC status since 25 June 1985 (RI-51-0011278).',
    limitations: 'Tertiary encyclopaedia; names the hill "cerro de la Sabina" where other sources say "cerro de Lízar", so the hill name is left open.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-axarquia-ermita-ecce-homo',
    title: 'Ecce Homo Hermitage',
    publisher: 'Turismo Axarquía Costa del Sol (Mancomunidad)',
    sourceType: 'official',
    url: 'https://turismoaxarquiacostadelsol.com/en/what-to-do/ecce-homo-hermitage/',
    accessedAt: '2026-09-12',
    language: 'en',
    scope:
      '18th-century single-nave chapel, front atrium over a round arch, built against the hillside; the Miércoles Santo procession to San Antonio; the 20th-century image.',
    limitations: 'Comarcal tourism copy; does not explain the "de la Caña" name.',
    reuse: 'link-and-cite',
  },
  {
    id: 'andalucia-org-frigiliana-miradores',
    title: 'Frigiliana y sus 3 culturas — miradores',
    publisher: 'Junta de Andalucía (andalucia.org)',
    sourceType: 'secondary',
    url: 'https://www.andalucia.org/es/frigiliana',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'Names Frigiliana viewpoints: a mirador at the upper end of the Callejón del Peñón with a panorama over the village, mountains and sea; the Mirador de Santo Cristo (Calle Santo Cristo, highest quarter) and the Plaza/Mirador de las Tres Culturas.',
    limitations: 'Regional-portal blog tone, not a legal or scholarly source; "Callejón del Peñón" appears as a common lane name, not an official monument name.',
    reuse: 'link-and-cite',
  },
  {
    id: 'ecce-homo-iconografia-cana-cetro',
    title: 'Iconografía del Ecce Homo — la caña como cetro de escarnio',
    publisher: 'Dialnet (Universidad de La Rioja) / Enciclopedia (Universidad de Sevilla)',
    sourceType: 'secondary',
    url: 'https://dialnet.unirioja.es/descarga/articulo/2992136.pdf',
    accessedAt: '2026-09-12',
    language: 'es',
    scope:
      'Academic iconography of the Ecce Homo: the reed (caña) placed in Christ’s hand as a mock sceptre, with the crown of thorns and purple robe — the meaning behind "Santo Cristo de la Caña".',
    limitations: 'Explains the iconographic name generically, not the specific local usage in Frigiliana; establishes that the name is not connected to sugar cane.',
    reuse: 'link-and-cite',
  },
  {
    id: 'amara-old-town-monuments-web-synthesis-2026',
    title: 'Amara web synthesis — Frigiliana old-town monuments (Fuente Vieja, Castillo de Lizar, Reales Pósitos, Ermita de Ecce Homo, Callejón del Peñón)',
    publisher: 'AMARA Research Vault (web synthesis)',
    sourceType: 'discovery-tool',
    accessedAt: '2026-09-12',
    language: 'de',
    scope:
      'Commissioned 2026-09-12 synthesis consolidating the municipal, provincial and heritage sources above, with a claim audit that corrected the Ermita procession day (Miércoles Santo, not Good Friday), the "de la Caña" meaning (reed sceptre, not sugar cane), the Fuente Vieja fabric (stone façade, not brick arch) and the Callejón del Peñón / El Fuerte overclaim.',
    limitations:
      'A synthesis of official and secondary web sources; individual claims inherit the confidence of their underlying source and are not new primary evidence.',
    reuse: 'internal-only',
  },
] as const);

export type FrigilianaOldTownMonumentsSourceId = (typeof frigilianaOldTownMonumentsSources)[number]['id'];
