import { defineKnowledgeSources } from '../../schema';

/**
 * Sources of the 2026-09-13 Barribarto place-entity run
 * (2026-09-13__150901__frigiliana-barribarto-entity__research-001).
 * Official municipal, provincial and heritage records carry the load-bearing
 * claims; OSM, Wikidata and the EU-DEM lookup are geometry aids only.
 */
export const frigilianaBarribartoSources = defineKnowledgeSources([
  {
    id: 'boja-decreto-183-2014-barribarto',
    title: 'Decreto 183/2014, de 23 de diciembre — Conjunto Histórico de Frigiliana (BIC)',
    publisher: 'Junta de Andalucía — BOJA nº 23, 04/02/2015',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/boja/2015/23/26',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Heritage decree describing the three areas of the ensemble (Barribarto, Barribajo, Ensanche), the hillside layout on contour lines, the adarves as mixed public/private spaces entered openly or through an algorfa, the Castillo de Lizar outside the boundary but inside the entorno, and the boundary polygon by cadastral block and parcel.',
    limitations:
      'Describes areas and typologies, not individual streets; the annexed plan is image-only and the delimitation text was read from the PDF extraction.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-el-barribarto-es-2026',
    title: 'El Barribarto',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/el-barribarto.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Municipal tourism page stating that the name derives from “Barrio Alto” and describing the municipal Barribarto walk from the end of Calle Almona via Calle El Garral and El Zacatín to the mirador de Lízar and the tajo del Peñón.',
    limitations: 'Undated promotional page; no length, duration or map; not a philological source for the name.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-the-barribarto-en-2026',
    title: 'The Barribarto',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/en/the-barribarto.html',
    accessedAt: '2026-09-13',
    language: 'en',
    scope:
      'English municipal page naming the “Mirador del Tajo del Peñón” and “Mirador El Lizar”, describing Calle Amargura as the quarter’s main street, mules carrying materials, and stating that the whitewashing is kept by habit with no bye-law enforcing it.',
    limitations: 'Undated; casualty figures for 1569 are uncited; the whitewash statement contradicts the reading of the BIC conservation conditions and is recorded as an open question.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-las-calles-2026',
    title: 'Las calles de Frigiliana',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/las-calles.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Municipal page on the streets: Calle Real as the main artery and the only street passable by vehicles, from which the lanes to the Barribarto branch; “Zacatín” explained as the name for plazas or streets where clothing was sold; the Callejón del Peñón leading to the peña with views over the village and the Nerja coast.',
    limitations: 'Undated descriptive page; the Arabic root of zacatín is not given.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-casco-antiguo-2026',
    title: 'Casco histórico',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/casco-antiguo.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Municipal page naming eleven adarves of the old town: Zacatín, Túnel, Señor, Huerta, Amargura, Peñón, Batanero, Torreón, Cura Soto, Corralón and Inquisidor.',
    limitations: 'Undated; no map and no statement of which lanes are adarves in the decree’s sense (entered through an algorfa).',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-ruta-apero-porton-2026',
    title: 'Desde El Apero hasta El Portón',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/desde-el-apero-hasta-el-porton.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'First municipal itinerary: Plaza del Ingenio (bus drop-off; car park of the Plaza de las Tres Culturas about 50 m away), Cuesta del Apero, Casa del Apero, El Ingenio, Las Maquinillas, Calle Real, Reales Pósitos, Calle Hernando el Darra.',
    limitations: 'No length, duration or difficulty; distances are the site’s approximations.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-ruta-hacia-el-torreon-2026',
    title: 'Hacia El Torreón',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/hacia-el-torreon.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Second municipal itinerary: Jardines del Portón, Callejón del Estanco, Calle Alta into the Barribarto, optional mirador del Peñón, bajada de La Huerta, Callejón del Señor as a small typical adarve, la plazuela and El Torreón (mid-18th-century pósito site, judged unlikely to be Arab, of the 18th-century coastal-watch type).',
    limitations: 'Undated; its sentence placing “el actual ayuntamiento” at the plazuela conflicts with the official seat address.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-ruta-iglesia-santo-cristo-2026',
    title: 'Desde la iglesia al Santo Cristo',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/desde-la-iglesia-al-santo-cristo.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Third municipal itinerary: Zacatín, church, Callejón del Inquisidor, Fuente Vieja, then “la bajada de calle Real, que a partir de la plaza de la Iglesia toma el nombre de calle Chorruelo”, the sculpture “Tres Culturas, dos escultores, un Dios” at the end of Chorruelo, the Ermita del Ecce Homo about 300 m further and the Calle Almona steps as the alternative route into the Barribarto.',
    limitations: 'Distance to the Ermita is the site’s approximation; undated.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-ruta-paneles-2026',
    title: 'La ruta de los paneles',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/la-ruta-de-los-paneles.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Index of the twelve ceramic panels in route order with their titles.',
    limitations: 'No per-panel locations on the index page; no length or duration.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-oficina-turismo-2026',
    title: 'Oficina de turismo',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/oficina-turismo.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Tourist-office page offering an image-only PDF street map; no official audio guide or app is listed.',
    limitations: 'Opening hours not on the page.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-es-frigiliana-tours-listing-2026',
    title: 'Frigiliana Tours (directorio municipal)',
    publisher: 'Ayuntamiento de Frigiliana (frigiliana.es)',
    sourceType: 'official',
    url: 'https://frigiliana.es/places/frigiliana-tours/',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Municipal directory listing of a private guided-walk operator starting at the tourist office (about 1.5 h, ES/EN).',
    limitations: 'Read through a reader proxy (direct fetch blocked); prices and schedule are volatile and not normalized.',
    reuse: 'internal-only',
  },
  {
    id: 'frigiliana-es-parking-subterraneo-2015',
    title: 'El parking subterráneo abrirá sus puertas hasta finales de agosto',
    publisher: 'Ayuntamiento de Frigiliana (frigiliana.es)',
    sourceType: 'official',
    url: 'https://frigiliana.es/el-parking-subterraneo-abrira-sus-puertas-hasta-finales-de-agosto/',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: '2015 municipal notice on the underground car park beneath the Plaza de las Tres Culturas (about 500 vehicles).',
    limitations: 'Read through a reader proxy; a 2015 notice, not current operating information.',
    reuse: 'link-and-cite',
  },
  {
    id: 'festival-3-culturas-conoce-2026',
    title: 'Conoce el Festival 3 Culturas',
    publisher: 'Ayuntamiento de Frigiliana (frigiliana3culturas.com)',
    sourceType: 'official',
    url: 'https://frigiliana3culturas.com/festival-3-culturas/conoce-el-festival-3-culturas-frigiliana/',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Festival site: first edition 2006, Ayuntamiento-organised; the market runs from the Plaza de las Tres Culturas to the Plaza del Ingenio via Calle San Sebastián and Plaza Doña Amparo Guerrero; the Plaza de las Tres Culturas is the main stage.',
    limitations: 'Promotional; the venue list is not dated to a specific edition.',
    reuse: 'link-and-cite',
  },
  {
    id: 'festival-3-culturas-espacios-2026',
    title: 'Espacios de actividades y conciertos',
    publisher: 'Ayuntamiento de Frigiliana (frigiliana3culturas.com)',
    sourceType: 'official',
    url: 'https://frigiliana3culturas.com/informacion-de-interes/espacios-de-actividades-y-conciertos/',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Festival venue list including Calle Chorrera, the church (Calle Real 100), the Patio del Ayuntamiento (Cuesta del Apero 10), a “Photocall | Mirador – Calle Santo Cristo” and the Sala de Exposiciones (Calle Real 80).',
    limitations: 'Edition year of the list unclear.',
    reuse: 'link-and-cite',
  },
  {
    id: 'diputacion-malaga-culturama-plaza-tres-culturas',
    title: 'Plaza de las Tres Culturas (Culturama)',
    publisher: 'Diputación de Málaga',
    sourceType: 'official',
    url: 'https://www.malaga.es/culturama/espacios/lis_cd-12678/plaza-de-las-tres-culturas',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Provincial venue record: municipal plaza with shops over the underground car park, opposite El Ingenio; uses include the Festival de las Tres Culturas, a flamenco festival and the mercadillo.',
    limitations: 'Read through a reader proxy; gives no inauguration year or area.',
    reuse: 'link-and-cite',
  },
  {
    id: 'diputacion-malaga-mirador-urbano-penon',
    title: 'Mirador urbano del Peñón',
    publisher: 'Diputación de Málaga',
    sourceType: 'official',
    url: 'https://www.malaga.es/es/laprovincia/informacionyocio/lis_cd-5908/mirador-urbano-penon',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Provincial record of an urban mirador in the Callejón del Peñón, which climbs to the Peñón de la Sabina below the castle, with views of the village, the Nerja coast, the Higuerón valley and the Sierras of Tejeda and Almijara.',
    limitations: 'No coordinates; read through a reader proxy.',
    reuse: 'link-and-cite',
  },
  {
    id: 'ign-cartociudad-frigiliana-2026',
    title: 'CartoCiudad geocoder — calles de Frigiliana',
    publisher: 'Instituto Geográfico Nacional / CNIG',
    sourceType: 'official',
    url: 'https://www.cartociudad.es/geocoder/api/geocoder/find',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Official street ids and line geometry for Calle Amargura, El Zacatín, El Garral, Santo Cristo, Callejón del Peñón, del Señor, del Inquisidor, del Arriero, del Estanco, Plaza de las Tres Culturas and Calle Rosarico la Joaquín; Calle Chorruelo 5 resolved to cadastral reference 9925509VF2792N.',
    limitations: 'Calle Alta was not returned; the service is intermittent; geometry is centreline, not footprint.',
    reuse: 'link-and-cite',
  },
  {
    id: 'osm-frigiliana-old-town-2026',
    title: 'OpenStreetMap — Frigiliana old-town ways, nodes and viewpoints (Overpass / Nominatim / API 0.6)',
    publisher: 'OpenStreetMap contributors (ODbL)',
    sourceType: 'secondary',
    url: 'https://www.openstreetmap.org/#map=18/36.7928/-3.8975',
    accessedAt: '2026-09-13',
    language: 'en',
    scope:
      'Contributor geometry and tags: stepped lanes with step counts (Zacatín 32, La Chorrera 13, Hernando el Darra 29, La Huerta 82, Alta 21, Arriero 20, Santo Cristo 12, Estanco 8), Calle Real and Chorruelo as one-way living streets, unnamed viewpoint nodes, the Ermita and Reales Pósitos address nodes, the Fuente Vieja node.',
    limitations: 'Community data; names differ from official ones (e.g. “Peñón de la Sabina” for the Callejón del Peñón); step counts and positions are contributor entries to be confirmed on site. Attribution required (© OpenStreetMap contributors).',
    reuse: 'link-and-cite',
  },
  {
    id: 'wikidata-frigiliana-items-2026',
    title: 'Wikidata — items located in Frigiliana (SPARQL P131) and heritage items',
    publisher: 'Wikidata',
    sourceType: 'secondary',
    url: 'https://query.wikidata.org/',
    accessedAt: '2026-09-13',
    language: 'en',
    scope:
      'QIDs and coordinates: Frigiliana municipality Q944137, centro histórico Q97633690 (heritage code 01290530037, IAPH i24352), Castillo de Frigiliana Q67330309 (RI-51-0011278), Iglesia de San Antonio de Padua Q98504857, El Ingenio Q6058379 / Q97633247, Fuente Vieja Q126054962, Plaza de la Iglesia Q110063124, Plaza de la Fuente Vieja Q110063117, Calle Real Q110656460, Ayuntamiento Q126817250, Fuente de las Tres Culturas Q126068393, Fuente del Barrio Alto Q126068392, Fuente Hernando Darra Q126073348, Calle Alta Q110656451, Calle El Zacatín Q110656496, Calle Santo Cristo Q110656479, Calle Almona Q110656444, La Chorrera Q110656523.',
    limitations: 'No item for the Barribarto, the Reales Pósitos, the Ermita or any mirador; duplicate Ingenio items; several coordinates are OSM or ficha imports; an unexplained 1976 qualifier on Q97633690.',
    reuse: 'link-and-cite',
  },
  {
    id: 'conocetusfuentes-fuente-barrio-alto-9240',
    title: 'Fuente del Barrio Alto (ficha 9240)',
    publisher: 'Conoce tus Fuentes (Universidad de Granada / Junta de Andalucía)',
    sourceType: 'secondary',
    url: 'https://www.conocetusfuentes.com/ficha_detalle.php?id_fuente=9240',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Fountain inventory record: wall fountain “en un rincón del Barrio Alto”, ETRS89 UTM 30 X 419926.254 Y 4072274.029, altitude 328 m, dry at the 2014 visit.',
    limitations: 'Volunteer inventory ficha; status observed in 2014.',
    reuse: 'link-and-cite',
  },
  {
    id: 'conocetusfuentes-fuente-tres-culturas-9241',
    title: 'Fuente de las Tres Culturas (ficha 9241)',
    publisher: 'Conoce tus Fuentes (Universidad de Granada / Junta de Andalucía)',
    sourceType: 'secondary',
    url: 'https://www.conocetusfuentes.com/ficha_detalle.php?id_fuente=9241',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Fountain inventory record: small marble fountain with three spouts between the Callejón del Inquisidor and the Callejón de las Ánimas near the church square, ETRS89 UTM X 419815.155 Y 4072340.422, altitude 305 m (2014).',
    limitations: 'Volunteer inventory ficha.',
    reuse: 'link-and-cite',
  },
  {
    id: 'conocetusfuentes-fuente-hernando-darra-13383',
    title: 'Fuente Hernando Darra (ficha 13383)',
    publisher: 'Conoce tus Fuentes (Universidad de Granada / Junta de Andalucía)',
    sourceType: 'secondary',
    url: 'https://www.conocetusfuentes.com/ficha_detalle.php?id_fuente=13383',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Fountain inventory record at the junction of Calle Hernando el Darra and Calle Real, altitude 319 m.',
    limitations: 'Volunteer inventory ficha.',
    reuse: 'link-and-cite',
  },
  {
    id: 'opentopodata-eudem25m-2026',
    title: 'EU-DEM 25 m elevation lookup (opentopodata.org)',
    publisher: 'opentopodata.org (Copernicus EU-DEM v1.1)',
    sourceType: 'secondary',
    url: 'https://api.opentopodata.org/v1/eudem25m',
    accessedAt: '2026-09-13',
    language: 'en',
    scope: 'Approximate terrain heights for old-town points (Casa AMARA ≈307 m, Callejón del Peñón ≈336 m, Calle Santo Cristo ≈346 m, La Chorrera ≈351 m, Castillo ≈394 m, Plaza de las Tres Culturas ≈289–295 m).',
    limitations: '25 m grid, ±10–15 m on this slope; usable for ordering and rough height differences, never for step, gradient or accessibility claims.',
    reuse: 'internal-only',
  },
  {
    id: 'lpmbe-frigiliana-miradores-adarves',
    title: 'Miradores y Adarves · Frigiliana',
    publisher: 'Los Pueblos más Bonitos de España',
    sourceType: 'secondary',
    url: 'https://lospueblosmasbonitosdeespana.org/pueblos/frigiliana/experiencias/miradores-y-adarves',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Six-stop association itinerary: Adarve Callejón del Peñón, Mirador Callejón del Peñón, Mirador C/ Santo Cristo, Adarve Callejón del Arriero (“zona más alta del barrio morisco”), Casa del Apero mirador, Adarve Callejón del Inquisidor.',
    limitations: 'Promotional association page; no coordinates.',
    reuse: 'link-and-cite',
  },
  {
    id: 'axarquiaplus-mirador-santo-cristo-2022',
    title: 'Frigiliana cuenta con un nuevo mirador panorámico y un sendero peatonal en la zona del Santo Cristo',
    publisher: 'AxarquíaPlus',
    sourceType: 'secondary',
    url: 'https://www.axarquiaplus.es/frigiliana-cuenta-con-un-nuevo-mirador-panoramico-y-un-sendero-peatonal-en-la-zona-del-santo-cristo/',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Regional press report (2022-09-07) on a new panoramic mirador and pedestrian path “en la zona alta del Santo Cristo” funded with 31,758.43 € by the Consejería de Turismo (2021).',
    limitations: 'Read through a reader proxy; does not locate the mirador precisely.',
    reuse: 'link-and-cite',
  },
] as const);

export type FrigilianaBarribartoSourceId = (typeof frigilianaBarribartoSources)[number]['id'];
