import { defineKnowledgeSources } from '../../schema';

/**
 * Sources of the 2026-09-13 Calle Real & Barribajo run
 * (2026-09-13__150902__frigiliana-calle-real-barribajo__research-001).
 * The decree text, the Catastro and the BOE carry the load-bearing claims;
 * municipal tourism pages carry the route and street statements; OSM,
 * Wikidata and the EU-DEM lookup are geometry aids.
 */
export const frigilianaCalleRealSources = defineKnowledgeSources([
  {
    id: 'boja-decreto-183-2014-calle-real',
    title: 'Decreto 183/2014, de 23 de diciembre — Conjunto Histórico de Frigiliana (BIC), texto íntegro',
    publisher: 'Junta de Andalucía — BOJA nº 23, 04/02/2015 (HTML) and Junta PDF',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/boja/2015/23/26',
    locator:
      'PDF: https://www.juntadeandalucia.es/sites/default/files/2020-03/Decreto%20Conjunto%20Hist%C3%B3rico%20Frigiliana.pdf (text extracted with pdftotext; Anexo I Descripción, Anexo IV Delimitación del Bien, Anexo VI.4 Instrucciones particulares)',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Full decree text: the Barribajo along Calle Real (wealthier, generally three storeys, larger plots, special care of aesthetics), the Ensanche as the eastern productive area holding most shops, the hitos including “el Torreón de la calle Real” and the former Guardia Civil barracks as buildings of special interest subject to municipal pre-emption, the 1640 villa title with independence from Vélez-Málaga and the establishment of the Ayuntamiento, the modern part south of the Ingenio on the ridge of the Higuerón ravine, and the parcel-by-parcel boundary of the Bien (block 99255 parcels 1–73 listed for the Bien; the western boundary running along the rear of parcels 47…13 and 9 and crossing the Plaza de la Fuente).',
    limitations:
      'The PDF column layout garbles the parcel tables; block 99255 parcels 56–64 appear both in the Bien list and in the entorno list (internal overlap). The annexed plan is image-only.',
    reuse: 'link-and-cite',
  },
  {
    id: 'catastro-dnploc-chorruelo-5-real-109-2026',
    title: 'Consulta_DNPLOC — Calle Chorruelo 5 and Calle Real 109, Frigiliana',
    publisher: 'Dirección General del Catastro (Sede Electrónica, OVC web service)',
    sourceType: 'official',
    url: 'https://ovc.catastro.meh.es/OVCServWeb/OVCWcfCallejero/COVCCallejero.svc/json/Consulta_DNPLOC?Provincia=MALAGA&Municipio=FRIGILIANA&Sigla=CL&Calle=CHORRUELO&Numero=5',
    accessedAt: '2026-09-13',
    language: 'es',
    scope:
      'Cadastral references: Calle Chorruelo 5 = 9925509VF2792N (block 99255, parcel 09; plot 176 m², two dwellings of 91 m² plus a 15 m² annex); Calle Real 109 = 9925541VF2792N (block 99255, parcel 41; three dwelling floors plus storage).',
    limitations: 'Coordinate and WFS endpoints refused connections during the run; block/parcel read from the standard reference structure (first five digits block, next two parcel).',
    reuse: 'link-and-cite',
  },
  {
    id: 'boe-orden-1979-premios-embellecimiento-pueblos',
    title: 'Orden de 15 de febrero de 1979 — Premios Nacionales de Turismo de Embellecimiento y Mejora de los Pueblos Españoles',
    publisher: 'Boletín Oficial del Estado',
    sourceType: 'official',
    url: 'https://www.boe.es/eli/es/o/1979/02/15/(4)',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Regulation of the state prize: jury chaired by the Secretario de Estado de Turismo, first prize 1,000,000 pesetas, resolved by the Secretaría de Estado de Turismo.',
    limitations: 'Framework only; the resolution naming Frigiliana as 1982 first-prize winner was not located.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-conoce-frigiliana-2026',
    title: 'Conoce Frigiliana',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://turismofrigiliana.es/es/conoce-frigiliana.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Municipal statement: “El primer premio de embellecimiento de los pueblos de España, obtenido en 1982”.',
    limitations: 'Municipal self-description; the awarding resolution is not cited.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-las-calles-calle-real-2026',
    title: 'Las calles de Frigiliana',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/las-calles.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Calle Real as “la arteria principal del casco histórico, única transitable por vehículos”, from which the lanes to the Barribarto depart.',
    limitations: 'Undated; “única” is the site’s wording, not a traffic regulation.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-ruta-iglesia-santo-cristo-calle-real-2026',
    title: 'Desde la iglesia al Santo Cristo',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/desde-la-iglesia-al-santo-cristo.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: '“La bajada de calle Real, que a partir de la plaza de la Iglesia toma el nombre de calle Chorruelo”; the sculpture “Tres Culturas, dos escultores, un Dios” at the end of Chorruelo; the Ermita del Ecce Homo about 300 m further; the Calle Almona steps as the alternative way up.',
    limitations: 'The 300 m is the site’s approximation; undated.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-ruta-hacia-el-torreon-calle-real-2026',
    title: 'Hacia El Torreón',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/hacia-el-torreon.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'El Torreón as the mid-18th-century pósito site now attached to a house, judged “poco o nada probable” to be Arab and rather an 18th-century coastal-watch type; a vessel found inside with symbols of the three religions as origin of the “Villa de las 3 Culturas” slogan; “la plazuela” on Calle Real with the Torreón entrance opposite “el actual ayuntamiento”.',
    limitations: 'Undated route text; the town-hall sentence conflicts with the official seat address.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-ruta-apero-porton-calle-real-2026',
    title: 'Desde El Apero hasta El Portón',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/desde-el-apero-hasta-el-porton.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'The bus drops visitors at the Plaza del Ingenio; the most convenient car park is that of the Plaza de las 3 Culturas “que nos dejará a 50 metros”; the Reales Pósitos on Calle Real.',
    limitations: 'Distances are the site’s approximations; undated.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-ayer-y-hoy-2026',
    title: 'Frigiliana ayer y hoy',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/frigiliana-ayer-y-hoy.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: '“En otros tiempos Calle Chorruelo era la última calle del pueblo”; telephone and lighting cables buried along Calle Real and Chorruelo; a photo caption placing the Casa Consistorial on the plazuela with the Torreón entrance opposite.',
    limitations: 'Undated captions.',
    reuse: 'link-and-cite',
  },
  {
    id: 'turismo-frigiliana-monumentos-calle-real-2026',
    title: 'Monumentos',
    publisher: 'Ayuntamiento de Frigiliana — Turismo (turismofrigiliana.es)',
    sourceType: 'official',
    url: 'https://turismofrigiliana.es/es/monumentos.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Monument list: El Torreón, Reales Pósitos (“antiguo silo construido en 1767”), Fuente Vieja in a travesía of Calle Chorruelo.',
    limitations: 'Brief entries without addresses.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-es-telefonos-direcciones-2026',
    title: 'Teléfonos y direcciones — Ayuntamiento de Frigiliana',
    publisher: 'Ayuntamiento de Frigiliana (frigiliana.es)',
    sourceType: 'official',
    url: 'https://www.frigiliana.es/movil/ayuntamiento/telefonos-y-direcciones.html',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Official contact address of the Ayuntamiento: Calle Cuesta del Apero 10, 29788 Frigiliana.',
    limitations: 'Read through a reader proxy (direct fetch blocked).',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-es-torreon-109-listing-2026',
    title: 'Torreón 109 (directorio municipal)',
    publisher: 'Ayuntamiento de Frigiliana (frigiliana.es)',
    sourceType: 'official',
    url: 'https://frigiliana.es/places/torreon-109/',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Municipal business directory: hotel at Calle Real 109 “inaugurado en julio de 2017 manteniendo la estructura … de la vivienda original”.',
    limitations: 'Business listing on the municipal site, not a heritage record; the hotel’s own historical claims (1886 reform, mosque, casino, dungeon) are unverified.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-es-fiestas-y-tradiciones-2026',
    title: 'Fiestas y tradiciones',
    publisher: 'Ayuntamiento de Frigiliana (frigiliana.es)',
    sourceType: 'official',
    url: 'https://frigiliana.es/fiestas-y-tradiciones/',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'The folk-dance show moved from the Plaza del Ingenio to the Plaza de las Tres Culturas because of crowd size; the coros rocieros meet there in August; the Día de la Miel de Caña centres on the Plaza del Ingenio.',
    limitations: 'Read through a reader proxy; undated page.',
    reuse: 'link-and-cite',
  },
  {
    id: 'conocetusfuentes-fuente-vieja-3209-utm',
    title: 'La Fuente Vieja (ficha 3209) — coordenadas ETRS89 UTM',
    publisher: 'Conoce tus Fuentes (Universidad de Granada / Junta de Andalucía)',
    sourceType: 'secondary',
    url: 'https://www.conocetusfuentes.com/ficha_detalle.php?id_fuente=3209',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Ficha (F. D. Puertas Ravira, 31-03-2010): built 1640 by Íñigo Manrique de Lara, first called Fuente Nueva, “en la plaza del mismo nombre, en una travesía de la calle Chorruelo”; ETRS89 UTM 30 X 419762.835 Y 4072417.131, altitude 315 m.',
    limitations: 'The UTM pair converts to 36.794175, -3.899355, about 90 m north of the OSM fountain node and of the ficha’s own textual location; the coordinate is treated as conflicting.',
    reuse: 'link-and-cite',
  },
  {
    id: 'wikipedia-es-frigiliana-2026',
    title: 'Frigiliana',
    publisher: 'Wikipedia (ES)',
    sourceType: 'secondary',
    url: 'https://es.wikipedia.org/wiki/Frigiliana',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Señorío of the Manrique de Lara from 1508; villa title by real cédula of Felipe IV on 24 May 1640 with 160 vecinos; the Casa Consistorial on its present site since at least 1844; population peak 3,197 in 1887.',
    limitations: 'Tertiary; used only where the decree is silent.',
    reuse: 'link-and-cite',
  },
  {
    id: 'osm-calle-real-chorruelo-2026',
    title: 'OpenStreetMap — Calle Real (way 112876460) and Calle Chorruelo (way 112951430), address and POI nodes',
    publisher: 'OpenStreetMap contributors (ODbL)',
    sourceType: 'secondary',
    url: 'https://www.openstreetmap.org/way/112876460',
    accessedAt: '2026-09-13',
    language: 'en',
    scope:
      'Calle Real as highway=living_street, oneway=yes, surface=sett, running from the Ingenio side (node 714800092) to the Plaza de la Iglesia (node 1281971604), main way 355 m and about 0.5 km with its further segments; Calle Chorruelo as one-way living street of 114 m starting beyond the Plaza de la Iglesia; address nodes Reales Pósitos = Calle Real 1 (36.7914771, -3.8956076) and Casa Rural Miller’s = Calle Real 74; the Ermita del Ecce Homo at Calle Rosario la Joaquín 31 (36.7953972, -3.9006033); stepped lanes off Calle Real with contributor step counts; bus stops on Calle San Sebastián and Avenida Carlos Cano; the paid underground car park under the Plaza de las Tres Culturas.',
    limitations: 'Contributor data; lengths are polyline lengths, not surveyed; tags such as access=private are not legal findings. Attribution required (© OpenStreetMap contributors).',
    reuse: 'link-and-cite',
  },
  {
    id: 'wikidata-calle-real-items-2026',
    title: 'Wikidata — Frigiliana street, plaza and building items',
    publisher: 'Wikidata',
    sourceType: 'secondary',
    url: 'https://www.wikidata.org/wiki/Q110656460',
    accessedAt: '2026-09-13',
    language: 'en',
    scope: 'Calle Real Q110656460; Plaza de la Iglesia Q110063124; Iglesia de San Antonio de Padua Q98504857; Ayuntamiento Q126817250 (Cuesta del Apero 10, coordinate imported from OSM); Fuente Vieja Q126054962; Plaza de la Fuente Vieja Q110063117; Fuente de las Tres Culturas Q126068393; Museo Arqueológico Q6033136; El Ingenio Q6058379.',
    limitations: 'No item for El Torreón, the Plaza del Ingenio or the Plaza de las Tres Culturas; coordinates partly imported.',
    reuse: 'link-and-cite',
  },
  {
    id: 'opentopodata-eudem25m-calle-real-2026',
    title: 'EU-DEM 25 m elevation lookup — lower old-town points',
    publisher: 'opentopodata.org (Copernicus EU-DEM v1.1)',
    sourceType: 'secondary',
    url: 'https://api.opentopodata.org/v1/eudem25m',
    accessedAt: '2026-09-13',
    language: 'en',
    scope: 'Approximate heights: Casa AMARA ≈307 m, Plaza de la Iglesia ≈310 m, Calle Real Ingenio-side end ≈323 m, Cuesta del Apero junction ≈299 m, Ayuntamiento/Casa del Apero ≈297 m, Plaza de las Tres Culturas ≈295 m, Ermita (OSM position) ≈306 m.',
    limitations: '25 m grid, ±5–10 m on this slope; ordering only, never step or gradient claims.',
    reuse: 'internal-only',
  },
  {
    id: 'lpmbe-frigiliana-casa-del-apero-poi-2026',
    title: 'Casa del Apero (POI 126) · Frigiliana',
    publisher: 'Los Pueblos más Bonitos de España',
    sourceType: 'secondary',
    url: 'https://lospueblosmasbonitosdeespana.org/pueblos/frigiliana/pois/126',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Association POI stating that the Casa del Apero, restored in the 1990s, houses the municipal seat, the library and the tourist office.',
    limitations: 'Promotional association listing; its church dates on other POIs are unreliable.',
    reuse: 'link-and-cite',
  },
  {
    id: 'ayuntamiento-es-directory-frigiliana-2026',
    title: 'Ayuntamiento de Frigiliana (directorio)',
    publisher: 'ayuntamiento.es (commercial directory)',
    sourceType: 'discovery-tool',
    url: 'https://www.ayuntamiento.es/frigiliana/',
    accessedAt: '2026-09-13',
    language: 'es',
    scope: 'Directory entry giving Calle Real 80 as the registered address of the Ayuntamiento.',
    limitations: 'Not an official source; used only to record the address conflict.',
    reuse: 'internal-only',
  },
] as const);

export type FrigilianaCalleRealSourceId = (typeof frigilianaCalleRealSources)[number]['id'];
