import { defineKnowledgeSources } from '../../schema';

export const frigilianaShoppingSources = defineKnowledgeSources([
  {
    id: 'eroski-city-frigiliana-store-2026',
    title: 'EROSKI/city Frigiliana',
    publisher: 'EROSKI',
    sourceType: 'official',
    url: 'https://www.eroski.es/localizador-de-tiendas/supermercado/malaga/frigiliana/eroskicity-frigiliana/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Retailer-operated store identity and street address for the EROSKI/city branch in Frigiliana.',
    limitations: 'Hours, holiday operation, inventory, payment, delivery and parking remain volatile.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-municipality-silvia-2026',
    title: 'Supermarket Silvia',
    publisher: 'Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana.es/places/supermarket-silvia/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Municipal business entry with the shop address and described grocery range.',
    limitations: 'The entry does not establish that every described product is in stock; hours require a current direct check.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-municipality-garcia-berroa-2026',
    title: 'Supermercado García Berroa',
    publisher: 'Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana.es/places/supermercado-garcia-berroa/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Municipal business entry with the shop address and described grocery and local-product range.',
    limitations: 'Current operation, stock and all service details need retailer or field confirmation.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-municipality-el-lagar-2026',
    title: 'Tienda Bodega El Lagar',
    publisher: 'Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana.es/places/tienda-bodega-el-lagar/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Municipal business entry with the shop address and examples of regional products sold there.',
    limitations: 'Product availability and opening hours are volatile; sale in Frigiliana does not prove Frigiliana provenance.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-municipality-mercadillo-thursday-2026',
    title: 'Café Bar El Ingenio',
    publisher: 'Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana.es/places/cafe-bar-el-ingenio/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Current municipal business text identifying Thursday as the town market day.',
    limitations: 'An incidental reference does not verify current market hours, exact location, authority or vendor mix.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-market-permits-2019',
    title: 'Acta de la Junta de Gobierno Local — 23 de abril de 2019',
    publisher: 'Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana.es/wp-content/uploads/2018/01/ACTA_JGL_23_DE_ABRIL_DE_2019.pdf',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Historical municipal permit evidence for mixed non-food market stalls at Plaza de las Tres Culturas.',
    limitations: 'A 2019 permit record cannot establish the current location, schedule or vendor mix.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-tourism-general-food-2026',
    title: 'Información general — gastronomía y El Ingenio',
    publisher: 'Turismo de Frigiliana',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/informacion-general.html',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Municipal tourism account of traditional dishes and the current identity of El Ingenio as a cane-honey producer.',
    limitations: 'Tourism framing is not an operational factory audit and does not verify raw-material origin or public access.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-tourism-gastronomy-2026',
    title: 'Gastronomía de Frigiliana',
    publisher: 'Turismo de Frigiliana',
    sourceType: 'official',
    url: 'https://www.turismofrigiliana.es/es/gastronomia.html',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Municipal tourism overview of traditional Frigiliana and Axarquía foods and dishes.',
    limitations: 'It does not prove current restaurant availability, shop stock, recipe authorship or suitability for an AMARA kitchen.',
    reuse: 'link-and-cite',
  },
] as const);

export type FrigilianaShoppingSourceId = (typeof frigilianaShoppingSources)[number]['id'];
