import { defineKnowledgeSources } from '../../schema';

export const healthEmergencySources = defineKnowledgeSources([
  {
    id: 'sas-centro-salud-nerja-2026',
    title: 'Centro de salud Nerja',
    publisher: 'Servicio Andaluz de Salud',
    sourceType: 'official',
    url: 'https://www.sspa.juntadeandalucia.es/servicioandaluzdesalud/el-sas/servicios-y-centros/informacion-por-centros/24887',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Current official directory entry for the address, contact numbers, urgent-care number and published opening schedule of Centro de Salud Nerja.',
    limitations: 'Opening schedules and service availability are volatile. A directory opening time does not guarantee that every service is available throughout that period.',
    reuse: 'link-and-cite',
  },
  {
    id: 'junta-andalucia-urgent-emergency-routing-2026',
    title: 'Atención a la ciudadanía — Emergencias Sanitarias',
    publisher: 'Servicio Andaluz de Salud / Junta de Andalucía',
    sourceType: 'official',
    url: 'https://www.sspa.juntadeandalucia.es/servicioandaluzdesalud/emergencias061/ciudadania/atencion-a-la-ciudadania',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Official distinction between life-threatening medical emergencies, non-life-threatening urgent care, 112 and Salud Responde, including the Málaga urgent-care number.',
    limitations: 'This is routing information, not medical advice. Travellers must follow the instructions given by the emergency or healthcare service.',
    reuse: 'link-and-cite',
  },
  {
    id: 'junta-andalucia-emergency-061-2026',
    title: 'Teléfono de Emergencias Sanitarias — 061',
    publisher: 'Junta de Andalucía',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/servicios/sede/tramites/procedimientos/detalle/7082.html',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Official remit and continuous availability of the Andalusian 061 medical-emergency service.',
    limitations: '061 is for medical emergencies; 112 remains the general emergency number.',
    reuse: 'link-and-cite',
  },
  {
    id: 'redaccion-medica-centro-salud-nerja',
    title: 'Centro Salud Nerja',
    publisher: 'Redacción Médica',
    sourceType: 'secondary',
    url: 'https://www.redaccionmedica.com/recursos-salud/centros-de-salud-espana/centro-salud-nerja',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Operator-supplied secondary directory used as a lead for Centro de Salud Nerja contact and opening information.',
    limitations: 'Secondary directory data conflicts with the current official SAS schedule and must not override it.',
    reuse: 'link-and-cite',
  },
  {
    id: 'sentinella-nerja-medical-centre',
    title: 'Nerja Medical Centre',
    publisher: 'The Sentinella',
    sourceType: 'secondary',
    url: 'https://thesentinella.com/listing/nerja-medical-centre',
    accessedAt: '2026-08-24',
    language: 'en',
    scope: 'Operator-supplied local directory lead for Centro de Salud Nerja opening and contact information.',
    limitations: 'Secondary listing; opening times and telephone numbers require confirmation against current official sources.',
    reuse: 'link-and-cite',
  },
  {
    id: 'yelp-centro-salud-nerja',
    title: 'Centro de Salud de Nerja',
    publisher: 'Yelp',
    sourceType: 'secondary',
    url: 'https://m.yelp.com/biz/centro-de-salud-de-nerja-nerja',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Operator-supplied discovery lead for a legacy direct telephone number.',
    limitations: 'The supplied +34 952 523 131 number is not present in the current official SAS entry and is not suitable for publication without primary-source confirmation.',
    reuse: 'link-and-cite',
  },
  {
    id: 'amara-operator-nerja-health-note-2026-08-24',
    title: 'Centro de Salud Nerja operator intake note',
    publisher: 'AMARA operator',
    sourceType: 'operator-provided',
    locator: 'Operator work order received 2026-08-24 with proposed hours, address, telephone numbers and three secondary links.',
    observedAt: '2026-08-24',
    language: 'de',
    scope: 'Preserves the operator-supplied claim set and requested publication scope for knowledge, public Daily Life pages and Guest Guide.',
    limitations: 'The note is an intake record, not independent verification. Active public claims use the newer official sources above.',
    reuse: 'internal-only',
  },
] as const);

export type HealthEmergencySourceId = (typeof healthEmergencySources)[number]['id'];
