import { defineKnowledgeSources } from '../../schema';

export const nerjaCaveSources = defineKnowledgeSources([
  {
    id: 'nerja-cave-bic-2006',
    title: 'Decreto 194/2006: Cueva de Nerja as Bien de Interés Cultural, Zona Arqueológica',
    publisher: 'Junta de Andalucía — BOJA',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/boja/2006/228/45',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Legal protection, archaeological significance, geology, openings and protection rationale.',
    limitations: 'Legal-scientific designation; current visitor access, prices and opening arrangements are outside its stable scope.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-cave-discovery-official',
    title: 'Descubrimiento de la Cueva de Nerja',
    publisher: 'Fundación Cueva de Nerja',
    sourceType: 'official',
    url: 'https://cuevadenerja.es/la-cueva/descubrimiento-de-la-cueva-de-nerja/',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Institutional account of the 12 January 1959 discovery by five local boys.',
    limitations: 'Foundation narrative; detailed oral-history variants should remain attributed when relevant.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-cave-geology-official',
    title: 'Geología de la Cueva de Nerja',
    publisher: 'Fundación Cueva de Nerja',
    sourceType: 'official',
    url: 'https://cuevadenerja.es/la-cueva/valores-de-la-cueva/geologia/',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Institutional geological explanation of the karst cave and its marble host rock.',
    limitations: 'Scientific summary rather than a complete technical monograph.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-cave-values-official',
    title: 'Valores de la Cueva de Nerja',
    publisher: 'Fundación Cueva de Nerja',
    sourceType: 'official',
    url: 'https://cuevadenerja.es/la-cueva/valores-de-la-cueva/',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Institutional overview of geological, archaeological and cultural values.',
    limitations: 'Some promotional superlatives are self-description and must remain attributed.',
    reuse: 'link-and-cite',
  },
  {
    id: 'ahp-malaga-nerja-cave-2019',
    title: 'La Cueva de Nerja: descubrimiento, apertura y protección',
    publisher: 'Archivo Histórico Provincial de Málaga — Junta de Andalucía',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/cultura/archivos_html/sites/default/contenidos/archivos/ahpmalaga/documentos/DocMes201901_cuevaNerja.pdf',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Archival synthesis of discovery, public opening on 12 June 1960 and later protection.',
    limitations: 'High-level archival document; not a live visitor-information source.',
    reuse: 'link-and-cite',
  },
] as const);

export type NerjaCaveSourceId = (typeof nerjaCaveSources)[number]['id'];
