import { defineKnowledgeSources } from '../../schema';

export const nerjaIdentityHistorySources = defineKnowledgeSources([
  {
    id: 'nerja-archaeological-charter-2024',
    title: 'Carta Arqueológica Municipal de Nerja (Málaga)',
    publisher: 'Junta de Andalucía — Anuario Arqueológico de Andalucía',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/cultura/tabula/bitstream/20.500.11947/37202/1/AAA_2024_512_mu%C3%B1oz_navarro_cartaarqueologicanerja_malaga.pdf',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Municipality-wide archaeological inventory, settlement chronology and material heritage synthesis.',
    limitations: 'A technical inventory is not a visitor guide; individual sites may not be publicly accessible or visibly legible.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-tourism-history-2026',
    title: 'Reseña histórica',
    publisher: 'Turismo de Nerja',
    sourceType: 'official',
    url: 'https://visita.nerja.es/descubre/resena-historica',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Official municipal tourism synthesis from Andalusi settlement through sugar production and tourism.',
    limitations: 'Institutional place narrative; fine chronology and origin stories require independent or archival confirmation.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-municipal-heritage-app',
    title: 'Nerja — Historia y patrimonio',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://nerja.es/File/iphone-app/inicio.html?google=es',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Municipal historical notes on sugar mills, Maro, the Balcón and local heritage points.',
    limitations: 'Legacy presentation with limited citations; municipal traditions are attributed rather than treated as archival proof.',
    reuse: 'link-and-cite',
  },
  {
    id: 'rtve-verano-azul-2014',
    title: 'Verano Azul, una serie inolvidable',
    publisher: 'RTVE',
    sourceType: 'official',
    url: 'https://www.rtve.es/play/noticias/20140627/verano-azul-serie-inolvidable/463244.shtml',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Broadcaster record of production dates, episode count, first broadcast and Nerja filming context.',
    limitations: 'Supports the television-production history, not quantified long-term tourism impact.',
    reuse: 'link-and-cite',
  },
  {
    id: 'rtve-verano-azul-filming-2011',
    title: 'Cómo rodamos Verano Azul',
    publisher: 'RTVE',
    sourceType: 'official',
    url: 'https://www.rtve.es/play/noticias/20111010/como-rodamos-verano-azul/465995.shtml',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Broadcaster retrospective placing the start of filming at Burriana on 21 August 1979.',
    limitations: 'A production retrospective; not evidence that every scene or cultural association belongs to Burriana.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-balcon-official-2026',
    title: 'Balcón de Europa',
    publisher: 'Turismo de Nerja',
    sourceType: 'official',
    url: 'https://visita.nerja.es/planifica/balcon-de-europa-p107096',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Official location and visitor description of the public viewpoint over the former coastal fortress site.',
    limitations: 'The page repeats municipal place narrative and does not resolve the origin date of the name.',
    reuse: 'link-and-cite',
  },
  {
    id: 'capilla-balcon-name-2016',
    title: 'El monumento al rey Alfonso XII en el Balcón de Europa',
    publisher: 'Francisco Capilla Luque',
    sourceType: 'secondary',
    url: 'https://franciscocapillaluque.blogspot.com/2016/09/el-monumento-al-rey-alfonso-xii-en-el.html',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Local historical argument citing evidence that the name Balcón de Europa predates the 1885 royal visit.',
    limitations: 'Secondary presentation of archival evidence; the referenced dated record must be inspected directly before resolution.',
    reuse: 'link-and-cite',
  },
] as const);

export type NerjaIdentityHistorySourceId = (typeof nerjaIdentityHistorySources)[number]['id'];
