import { defineKnowledgeSources } from '../../schema';

export const nerjaBeachSources = defineKnowledgeSources([
  {
    id: 'nerja-tourism-burriana-2026',
    title: 'Playa de Burriana',
    publisher: 'Turismo de Nerja',
    sourceType: 'official',
    url: 'https://visitanerja.es/atracciones/playa-de-burriana/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Official dimensions, urban character, occupancy category, access and listed facilities for Burriana.',
    limitations: 'Facilities are operational claims rather than permanent guarantees; crowding varies within a season and day.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-tourism-playazo-2026',
    title: 'Playa El Playazo',
    publisher: 'Turismo de Nerja',
    sourceType: 'official',
    url: 'https://visitanerja.es/atracciones/playa-el-playazo/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Official dimensions, semi-urban character, occupancy category, transport and listed facilities for El Playazo.',
    limitations: 'Facilities and public transport are operational and must be checked for the intended stay date.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-tourism-maro-beach-2026',
    title: 'Playa de Maro',
    publisher: 'Turismo de Nerja',
    sourceType: 'official',
    url: 'https://visitanerja.es/atracciones/playa-de-maro/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Official dimensions, isolated setting, summer demand, seasonal access and listed services for Playa de Maro.',
    limitations: 'The page does not freeze shuttle dates, price, hours or service availability for future seasons.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-municipality-maro-shuttle-2026',
    title: 'Entra en servicio el autobús lanzadera de la playa de Maro',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://www.nerja.es/entra-en-servicio-el-autobus-lanzadera-de-la-playa-de-maro/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Dated 2026 Maro beach shuttle operating period, daily hours and return fare.',
    limitations: 'A 2026 operational notice must not be reused as an undated promise for later seasons.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-municipality-beach-accessibility-2026',
    title: 'El Ayuntamiento refuerza la accesibilidad de las playas',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://www.nerja.es/el-ayuntamiento-refuerza-la-accesibilidad-de-las-playas-con-nuevas-zonas-para-persona-con-movilidad-reducida/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Dated 2026 municipal account of reduced-mobility beach points at Burriana, Torrecilla and El Playazo.',
    limitations: 'A designated point and equipment do not establish an independently accessible end-to-end journey or suitable sea conditions.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-municipality-blue-flags-2026',
    title: 'Nerja y Maro renuevan sus cuatro Banderas Azules',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://www.nerja.es/nerja-y-maro-renuevan-sus-cuatro-banderas-azules/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Dated 2026 award record for Burriana, Torrecilla, Maro and the Playazo-Chucho certification scope.',
    limitations: 'Annual certification is volatile; Playazo-Chucho is an award label and must not silently redefine beach entities.',
    reuse: 'link-and-cite',
  },
  {
    id: 'junta-cantarrijan-visitor-page-2026',
    title: 'Cantarriján',
    publisher: 'Ventana del Visitante — Junta de Andalucía',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/medioambiente/portal/web/ventanadelvisitante/detalle-buscador-mapa/-/asset_publisher/Jlbxh2qB3NwR/content/cantarrij%C3%A1n/255035',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Municipality, protected-area approach, N-340 information point and normal seasonal motor-access restriction for Cantarriján.',
    limitations: 'The page describes a normal seasonal regime; the current-year notice and timetable remain necessary for trip planning.',
    reuse: 'link-and-cite',
  },
  {
    id: 'junta-cantarrijan-shuttle-notice-2026',
    title: 'Servicio de lanzadera a las playas El Cañuelo y Cantarriján',
    publisher: 'Ventana del Visitante — Junta de Andalucía',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/medioambiente/portal/web/ventanadelvisitante/avisos-detalle/-/asset_publisher/9BhyJCdf7sUa/content/servicio-de-lanzadera-a-la-playas-el-ca%C3%B1uelo-y-cantarrijan/',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Dated notice confirming the 15 June 2026 start of the restricted-access shuttle period.',
    limitations: 'The notice is a dated operational snapshot and does not itself provide the complete end date or timetable.',
    reuse: 'link-and-cite',
  },
  {
    id: 'junta-cantarrijan-timetable-2026',
    title: 'Horario 2026 — acceso a Cantarriján',
    publisher: 'Junta de Andalucía — Medio Ambiente',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/medioambiente/portal/documents/20151/10fcb639-d2ef-d412-643d-bac47f614bbe',
    accessedAt: '2026-08-28',
    language: 'es',
    scope: 'Official 2026 calendar and 10:00–21:00 operating window for controlled access to Cantarriján.',
    limitations: 'A dated timetable can change through later notices and must not become a permanent annual claim.',
    reuse: 'link-and-cite',
  },
] as const);

export type NerjaBeachSourceId = (typeof nerjaBeachSources)[number]['id'];
