import { defineKnowledgeSources } from '../../schema';

export const nerjaNatureCoastSources = defineKnowledgeSources([
  {
    id: 'junta-maro-cerro-gordo-overview',
    title: 'Paraje Natural Acantilados de Maro-Cerro Gordo',
    publisher: 'Junta de Andalucía — Medio Ambiente',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/medioambiente/portal/areas-tematicas/espacios-protegidos/legislacion-autonomica-nacional/parajes-naturales/paraje-natural-acantilados-maro-cerro-gordo',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Protected-area extent, land/marine split, municipalities, landscape and designation history.',
    limitations: 'The page rounds total area and gives a cliff-height metric that conflicts with another official page.',
    reuse: 'link-and-cite',
  },
  {
    id: 'junta-maro-cerro-gordo-zec',
    title: 'Acantilados de Maro-Cerro Gordo (ES6170002)',
    publisher: 'Junta de Andalucía — Medio Ambiente',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/medioambiente/portal/landing-page-%C3%ADndice/-/asset_publisher/zX2ouZa4r1Rf/content/acantilados-de-maro-cerro-gordo/20151',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'EU site code, habitats, protection categories, biodiversity and access character.',
    limitations: 'Exact operational access restrictions and services are seasonal and must be checked live.',
    reuse: 'link-and-cite',
  },
  {
    id: 'boja-maro-cerro-gordo-2015',
    title: 'Decreto 6/2015: ZEC Acantilados de Maro-Cerro Gordo',
    publisher: 'Junta de Andalucía — BOJA',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/boja/2015/52/8',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Legal conservation status and ecological significance of the maritime-terrestrial strip.',
    limitations: 'Legal framework; not current visitor logistics.',
    reuse: 'link-and-cite',
  },
  {
    id: 'visitor-window-maro-cerro-gordo',
    title: 'Acantilados de Maro-Cerro Gordo',
    publisher: 'Ventana del Visitante — Junta de Andalucía',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/medioambiente/portal/web/ventanadelvisitante/detalle-buscador-mapa/-/asset_publisher/Jlbxh2qB3NwR/content/acantilados-de-maro-cerro-gordo-1/255035',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Landscape relationship among cliffs, coves, beaches and cultivated terraces.',
    limitations: 'Visitor conditions and route status may change seasonally.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-tourism-beaches-2026',
    title: 'Playas de Nerja',
    publisher: 'Turismo de Nerja',
    sourceType: 'official',
    url: 'https://visita.nerja.es/descubre/playas',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Official municipal beach inventory and spatial discovery entry point.',
    limitations: 'Facilities, flags, awards and services are volatile and require date-specific verification.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-tourism-el-salon-2026',
    title: 'Playa El Salón',
    publisher: 'Turismo de Nerja',
    sourceType: 'official',
    url: 'https://visita.nerja.es/descubre/playas/playa-el-salon-p107119',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Official position and access description for El Salón beside the Balcón de Europa.',
    limitations: 'Current accessibility and facility details require live checking.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-tourism-calahonda-2026',
    title: 'Playa de Calahonda',
    publisher: 'Turismo de Nerja',
    sourceType: 'official',
    url: 'https://visita.nerja.es/descubre/playas/playa-de-calahonda-p107106',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Official position and character description for Calahonda beside the Balcón de Europa.',
    limitations: 'Current accessibility and facility details require live checking.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-beach-pa-system-2025',
    title: 'Todas las playas de Nerja dotadas con megafonía',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://www.nerja.es/todas-las-playas-de-nerja-dotadas-con-megafonia/',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Dated 2025 municipal list of eight beaches served by the public-address system.',
    limitations: 'Operational snapshot only; it does not define a permanent beach count or future services.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-coastal-path-2022',
    title: 'La Senda Litoral de Nerja avanza con el nuevo tramo entre Caletilla y El Salón',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://www.nerja.es/la-senda-litoral-de-nerja-avanza-con-el-nuevo-tramo-entre-las-playas-caletilla-y-el-salon/',
    accessedAt: '2026-08-24',
    language: 'es',
    scope: 'Dated evidence that the coastal path had separate completed and planned sections in 2022.',
    limitations: 'Construction status is highly volatile and cannot establish the route condition in 2026.',
    reuse: 'link-and-cite',
  },
] as const);

export type NerjaNatureCoastSourceId = (typeof nerjaNatureCoastSources)[number]['id'];
