import { defineKnowledgeSources } from '../../schema';

export const parkingAccessibilitySources = defineKnowledgeSources([
  {
    id: 'frigiliana-parking-traffic-ordinance-2011',
    title: 'Entrada en vigor de la Ordenanza de regulación del tráfico en el casco antiguo',
    publisher: 'Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana.es/entrada-en-vigor-de-la-ordenanza-de-regulacion-del-trafico-en-el-casco-antiguo/',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'Historical municipal description of the 2011 traffic rules for Frigiliana’s historic centre.',
    limitations: 'The page is historical and does not establish the current 2026 legal or enforcement status.',
    reuse: 'link-and-cite',
  },
  {
    id: 'frigiliana-parking-repeal-consultation-2018',
    title: 'Memoria de derogación Ordenanza Tráfico casco antiguo',
    publisher: 'Ayuntamiento de Frigiliana',
    sourceType: 'official',
    url: 'https://frigiliana.es/memoria-de-derogacion-ordenanza-trafico-casco-antiguo/',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'Municipal public consultation preceding a proposed repeal of the historic-centre traffic ordinance.',
    limitations: 'The consultation proves a repeal process was initiated; it does not prove the final legal outcome.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-parking-anteproject-2025',
    title: 'Luz verde al Anteproyecto del nuevo aparcamiento con 847 plazas',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://www.nerja.es/luz-verde-al-anteproyecto-del-nuevo-aparcamiento-con-847-plazas/',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'Names existing municipal car parks and describes the planned Avenida de Pescia parking project.',
    limitations: 'The 847 spaces belong to an anteproject, not a completed or available facility.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-parking-balcon-guidance-2026',
    title: 'El Ayuntamiento completará el guiado de plazas libres del aparcamiento Balcón de Europa',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://www.nerja.es/el-ayuntamiento-completara-el-guiado-de-plazas-libres-del-aparcamiento-balcon-de-europa/',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'Contract award and planned third-floor extension of the Balcón de Europa free-space guidance system.',
    limitations: 'The publication does not confirm final completion or current public live-data access.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-parking-verano-azul-marking-2026',
    title: 'El Ayuntamiento sigue mejorando los aparcamientos municipales con la pintura integral del Verano Azul',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://www.nerja.es/el-ayuntamiento-sigue-mejorando-los-aparcamientos-municipales-con-la-pintura-integral-del-verano-azul/',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'Current municipal maintenance and re-marking of the Verano Azul car park.',
    limitations: 'Does not establish tariffs, capacity, access hours or live availability.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-parking-burriana-smart-2026',
    title: 'El aparcamiento municipal de Burriana contará con un sistema inteligente de guiado de plazas libres',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://www.nerja.es/el-aparcamiento-municipal-de-burriana-contara-con-un-sistema-inteligente-de-guiado-de-plazas-libres/',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'Contract award for smart management and real-time free-space guidance at Burriana.',
    limitations: 'The award and planned functionality are verified; live public operation at the research date is not.',
    reuse: 'link-and-cite',
  },
  {
    id: 'nerja-parking-burriana-loading-2026',
    title: 'El Ayuntamiento reorganiza la carga y descarga en la Playa de Burriana',
    publisher: 'Ayuntamiento de Nerja',
    sourceType: 'official',
    url: 'https://www.nerja.es/el-ayuntamiento-reorganiza-la-carga-y-descarga-en-la-playa-de-burriana/',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'Dated operating windows for new loading zones in the Burriana area.',
    limitations: 'Highly volatile operational detail; suitable for a current Burriana guide, not a permanent Nerja-wide rule.',
    reuse: 'link-and-cite',
  },
  {
    id: 'tarifa-parking-meters-tender-2026',
    title: 'Licitación de parquímetros y servicios asociados para aparcamientos municipales',
    publisher: 'Ayuntamiento de Tarifa / URTASA',
    sourceType: 'official',
    url: 'https://www.aytotarifa.com/notice-category/perfil-del-contratante/',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'May 2026 tender for parking meters, maintenance, connectivity and a management platform.',
    limitations: 'A tender proves an active technology change, not the final operating zones, tariff or completed rollout.',
    reuse: 'link-and-cite',
  },
  {
    id: 'tarifa-parking-retiro-authorisations-2026',
    title: 'Autorizaciones anuales para plazas en el aparcamiento municipal Paseo del Retiro',
    publisher: 'Ayuntamiento de Tarifa',
    sourceType: 'official',
    url: 'https://www.aytotarifa.com/notices/listado-de-aprobacion-de-listado-definitivo-de-personas-admitidas-en-el-proceso-de-concesion-de-autorizaciones-anuales-para-el-uso-de-plazas-de-estacionamiento-de-vehiculos-en-el-aparcamiento-municipa/',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'Municipal 2026 process for annual parking authorisations at Paseo del Retiro.',
    limitations: 'Does not by itself define all visitor availability or operating conditions at the facility.',
    reuse: 'link-and-cite',
  },
  {
    id: 'tarifa-beach-use-plan-2024-2027',
    title: 'Plan de Explotación de Playas 2024–2027',
    publisher: 'Ayuntamiento de Tarifa',
    sourceType: 'official',
    url: 'https://www.aytotarifa.com/notices/plan-de-explotacion-de-playas-2024-2027/',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'Official spatial and operating framework for Tarifa’s distinct beach areas.',
    limitations: 'Does not support a single permanent parking rule or tariff for every beach.',
    reuse: 'link-and-cite',
  },
  {
    id: 'andalusia-pmr-parking-card-2026',
    title: 'Solicitar la tarjeta de aparcamiento para personas con movilidad reducida',
    publisher: 'Junta de Andalucía',
    sourceType: 'official',
    url: 'https://www.juntadeandalucia.es/temas/familias-igualdad/discapacidad/ayudas-beneficios/tarjeta-aparcamiento.html',
    accessedAt: '2026-08-21',
    language: 'es',
    scope: 'Official rights, conditions and limitations for the Andalusian reduced-mobility parking card.',
    limitations: 'Legal parking rights do not establish a step-free or otherwise suitable route from a bay to a destination.',
    reuse: 'link-and-cite',
  },
  {
    id: 'amara-parking-operator-note-2026-08',
    title: 'Parking and accessibility operator experience note',
    publisher: 'AMARA operator',
    sourceType: 'first-party-observation',
    locator: 'Drive artifact 1uU9HIK-l7ZFAAZ3bYSD4KkJrVdn6Dqnz.',
    observedAt: '2026-08-21',
    language: 'de',
    scope: 'Operator experience concerning visitor rhythms in Frigiliana, parking-zone impressions in Nerja and peak-season pressure plus private garage parking in Tarifa.',
    limitations: 'Personal experience, not occupancy measurement, legal advice, tariff evidence or a parking-availability guarantee.',
    reuse: 'internal-only',
  },
  {
    id: 'amara-playa-parking-baseline-2026-08',
    title: 'AMARA Playa parking and access baseline',
    publisher: 'AMARA',
    sourceType: 'internal-editorial-baseline',
    locator: 'Current public property content and amenities data for AMARA Playa.',
    observedAt: '2026-08-21',
    scope: 'Current AMARA-authored claims concerning street parking and stair access.',
    limitations: 'Requires explicit property-owner confirmation before a negative private-parking claim or exact arrival instruction is published.',
    reuse: 'internal-only',
  },
  {
    id: 'amara-tarifa-garage-baseline-2026-08',
    title: 'AMARA Tarifa private garage baseline',
    publisher: 'AMARA',
    sourceType: 'operator-provided',
    locator: 'Current AMARA guest documentation and operator note for Family & Surf.',
    observedAt: '2026-08-21',
    scope: 'Private underground parking-space claim for the AMARA Tarifa property.',
    limitations: 'Current assignment, access method, dimensions and inclusion terms require a dated property confirmation.',
    reuse: 'internal-only',
  },
] as const);

export type ParkingAccessibilitySourceId = (typeof parkingAccessibilitySources)[number]['id'];
