import { defineKnowledgeSources } from '../../schema';

export const tarifaNatureWildlifeSources = defineKnowledgeSources([
  { id: 'junta-estrecho-park-2026', title: 'Parque Natural del Estrecho', publisher: 'Junta de Andalucía — Portal Ambiental', sourceType: 'official', url: 'https://www.juntadeandalucia.es/medioambiente/portal/areas-tematicas/espacios-protegidos/legislacion-autonomica-nacional/parques-naturales/parque-natural-del-estrecho', accessedAt: '2026-08-24', language: 'es', scope: 'Legal history, Natura 2000 status and protected-area context.', limitations: 'Broad protected-area overview; individual trail and facility status is volatile.', reuse: 'link-and-cite' },
  { id: 'junta-estrecho-declaration-2003', title: 'Decreto 57/2003 declaring Parque Natural del Estrecho', publisher: 'Junta de Andalucía — BOJA', sourceType: 'official', url: 'https://www.juntadeandalucia.es/boja/2003/54/4', accessedAt: '2026-08-24', language: 'es', scope: 'Foundational official evidence for ecological importance and intercontinental bird migration.', limitations: 'Protected-area declaration; not a current species-sighting forecast.', reuse: 'link-and-cite' },
  { id: 'migres-programme-2026', title: 'Programa Migres', publisher: 'Fundación Migres', sourceType: 'secondary', url: 'https://www.fundacionmigres.org/programa-migres/', accessedAt: '2026-08-24', language: 'es', scope: 'Long-term standardised monitoring of bird migration through the Strait.', limitations: 'Programme description does not guarantee visitor sightings on a particular date.', reuse: 'link-and-cite' },
  { id: 'tarifa-tourism-birds-2026', title: 'Avistamiento de aves', publisher: 'Turismo de Tarifa', sourceType: 'official', url: 'https://turismodetarifa.com/que-hacer/aves/', accessedAt: '2026-08-24', language: 'es', scope: 'Municipal visitor orientation for land and seabird watching.', limitations: 'Commercial directory entries and event information are volatile.', reuse: 'link-and-cite' },
  { id: 'tarifa-tourism-cetaceans-2026', title: 'Avistamiento de cetáceos', publisher: 'Turismo de Tarifa', sourceType: 'official', url: 'https://turismodetarifa.com/que-hacer/cetaceos/', accessedAt: '2026-08-24', language: 'es', scope: 'Municipal evidence that cetacean-watching excursions operate from Tarifa.', limitations: 'Duration, providers, season and species likelihood require live checking; sightings are never guaranteed.', reuse: 'link-and-cite' },
  { id: 'boe-cetacean-protection-2007', title: 'Real Decreto 1727/2007 on cetacean protection', publisher: 'Boletín Oficial del Estado', sourceType: 'official', url: 'https://www.boe.es/buscar/doc.php?id=BOE-A-2008-516', accessedAt: '2026-08-24', language: 'es', scope: 'National legal protection and behavioural framework for cetacean observation.', limitations: 'The law does not identify or endorse individual tour operators.', reuse: 'link-and-cite' },
  { id: 'tarifa-tourism-trails-2026', title: 'Parques naturales y rutas de senderismo', publisher: 'Turismo de Tarifa', sourceType: 'official', url: 'https://turismodetarifa.com/que-hacer/parques-naturales-senderismo/', accessedAt: '2026-08-24', language: 'es', scope: 'Municipal overview of viewpoints, trails and active-nature options.', limitations: 'Route conditions, permissions, duration and provider operation require current confirmation.', reuse: 'link-and-cite' },
] as const);

export type TarifaNatureWildlifeSourceId = (typeof tarifaNatureWildlifeSources)[number]['id'];
