import { defineKnowledgeSources } from '../../schema';

export const tarifaDayTripSources = defineKnowledgeSources([
  { id: 'apba-tarifa-tangier-route-2026', title: 'Tarifa–Tangier City passenger route context', publisher: 'Autoridad Portuaria de la Bahía de Algeciras', sourceType: 'official', url: 'https://www.apba.es/informacion-pasajero', accessedAt: '2026-08-24', language: 'es', scope: 'Official passenger-port information entry point for Tarifa.', limitations: 'Departures, operators and disruption status are live data and must be rechecked.', reuse: 'link-and-cite' },
  { id: 'balearia-tarifa-tangier-2026', title: 'Ferry from Tarifa to Tangier Ville', publisher: 'Baleària', sourceType: 'secondary', url: 'https://www.balearia.com/en/routes-timetables/ferry-tarifa-tanger-ville', accessedAt: '2026-08-24', language: 'en', scope: 'Current operator evidence of a direct fast-ferry service and indicative one-hour crossing.', limitations: 'Commercial schedule and duration are weather- and operation-dependent, not guarantees.', reuse: 'link-and-cite' },
  { id: 'spain-morocco-travel-advice-2026', title: 'Recomendaciones de viaje — Marruecos', publisher: 'Ministerio de Asuntos Exteriores, Unión Europea y Cooperación', sourceType: 'official', url: 'https://www.exteriores.gob.es/es/ServiciosAlCiudadano/Paginas/Detalle-recomendaciones-de-viaje.aspx?trc=Marruecos', accessedAt: '2026-08-24', language: 'es', scope: 'Current Spanish government travel, document, visa, safety, insurance, law and health guidance for Morocco.', limitations: 'Nationality-specific and highly volatile; every traveller must check current official guidance.', reuse: 'link-and-cite' },
  { id: 'visit-gibraltar-access-2026', title: 'How to get here', publisher: 'Gibraltar Tourist Board', sourceType: 'official', url: 'https://www.visitgibraltar.gi/get-here', accessedAt: '2026-08-24', language: 'en', scope: 'Official current access and travel-document orientation for Gibraltar.', limitations: 'Border and visa arrangements are high-volatility and traveller-specific.', reuse: 'link-and-cite' },
  { id: 'visit-gibraltar-reserve-2026', title: 'Gibraltar Upper Rock Nature Reserve', publisher: 'Gibraltar Tourist Board', sourceType: 'official', url: 'https://www.visitgibraltar.gi/see-and-do/gibraltar-nature-reserve-upper-rock', accessedAt: '2026-08-24', language: 'en', scope: 'Official visitor overview for the principal Upper Rock attraction cluster.', limitations: 'Admission prices, closures and included sites change and must be checked live.', reuse: 'link-and-cite' },
  { id: 'vejer-tourism-official-2026', title: 'Turismo Vejer', publisher: 'Ayuntamiento de Vejer de la Frontera', sourceType: 'official', url: 'https://turismovejer.es/en/home/', accessedAt: '2026-08-24', language: 'en', scope: 'Official description of Vejer’s hill-town setting and Arab-Andalusian heritage.', limitations: 'Does not establish travel time from an AMARA property.', reuse: 'link-and-cite' },
  { id: 'cadiz-tourism-official-2026', title: 'Cádiz', publisher: 'Turismo de Andalucía', sourceType: 'official', url: 'https://en.andalucia.org/places-to-visit/cadiz/cadiz/', accessedAt: '2026-08-24', language: 'en', scope: 'Official regional visitor entry point for Cádiz city and its heritage attractions.', limitations: 'Attractions, hours and journey planning require current checks.', reuse: 'link-and-cite' },
] as const);

export type TarifaDayTripSourceId = (typeof tarifaDayTripSources)[number]['id'];
