import { defineKnowledgeSources } from '../../schema';

export const tarifaBeachesWindSources = defineKnowledgeSources([
  { id: 'tarifa-tourism-beaches-2026', title: 'Playas de Tarifa', publisher: 'Turismo de Tarifa', sourceType: 'official', url: 'https://turismodetarifa.com/playas/', accessedAt: '2026-08-24', language: 'es', scope: 'Municipal descriptions of Playa Chica, Los Lances, Valdevaqueros, Punta Paloma, Bolonia and other beaches.', limitations: 'Suitability, facilities, access and use can change by season and conditions.', reuse: 'link-and-cite' },
  { id: 'tarifa-tourism-watersports-schools-2026', title: 'Escuelas de Wind, Kite, Surf and SUP', publisher: 'Turismo de Tarifa', sourceType: 'official', url: 'https://turismodetarifa.com/escuelas-wind-kite-surf-sup/', accessedAt: '2026-08-24', language: 'es', scope: 'Municipal directory evidencing a developed tuition market at Los Lances and Valdevaqueros.', limitations: 'Provider listings, contact details and operating status require live checking and are not endorsements.', reuse: 'link-and-cite' },
  { id: 'junta-estrecho-visitor-2026', title: 'Parque Natural del Estrecho', publisher: 'Junta de Andalucía — Ventana del Visitante', sourceType: 'official', url: 'https://www.juntadeandalucia.es/medioambiente/portal/web/ventanadelvisitante/detalle-buscador-mapa/-/asset_publisher/Jlbxh2qB3NwR/content/del-estrecho/255035', accessedAt: '2026-08-24', language: 'es', scope: 'Protected coastal landscape and official visitor overview including Los Lances and Bolonia.', limitations: 'Does not replace current beach-safety, weather, zoning or access notices.', reuse: 'link-and-cite' },
  { id: 'junta-lances-plan-2024', title: 'Decreto 130/2024: plans for protected coastal spaces', publisher: 'Junta de Andalucía — BOJA', sourceType: 'official', url: 'https://www.juntadeandalucia.es/boja/2024/146/3', accessedAt: '2026-08-24', language: 'es', scope: 'Current planning and protection framework for Playa de Los Lances and Parque Natural del Estrecho.', limitations: 'Legal planning text is not a live map of recreational zones.', reuse: 'link-and-cite' },
  { id: 'aemet-tarifa-forecast-2026', title: 'Tarifa — seven-day forecast', publisher: 'AEMET', sourceType: 'official', url: 'https://www.aemet.es/es/eltiempo/prediccion/municipios/tarifa-id11035', accessedAt: '2026-08-24', language: 'es', scope: 'Authoritative live municipal forecast and wind data entry point.', limitations: 'Forecast values expire rapidly and must never be stored as durable destination facts.', reuse: 'link-and-cite' },
] as const);

export type TarifaBeachesWindSourceId = (typeof tarifaBeachesWindSources)[number]['id'];
