import { defineKnowledgeSources } from '../../schema';

export const tarifaBoloniaBaeloSources = defineKnowledgeSources([
  { id: 'baelo-official-museum-2026', title: 'Conjunto Arqueológico de Baelo Claudia', publisher: 'Museos de Andalucía — Junta de Andalucía', sourceType: 'official', url: 'https://www.museosdeandalucia.es/web/conjuntoarqueologicobaeloclaudia', accessedAt: '2026-08-24', language: 'es', scope: 'Official identity of Baelo Claudia as a maritime Roman city and visitor site.', limitations: 'Opening, admission, reservation and event data are volatile.', reuse: 'link-and-cite' },
  { id: 'baelo-agenda-2026', title: 'Conjunto Arqueológico de Baelo Claudia', publisher: 'Agenda Cultural de Andalucía — Junta de Andalucía', sourceType: 'official', url: 'https://www.juntadeandalucia.es/cultura/agendaculturaldeandalucia/evento/conjunto-arqueologico-de-baelo-claudia', accessedAt: '2026-08-24', language: 'es', scope: 'Current official visitor-contact and seasonal-opening entry point.', limitations: 'Displayed schedules and event years change; cite only as a live-check destination.', reuse: 'link-and-cite' },
  { id: 'baelo-education-monuments-2021', title: 'International Day for Monuments and Sites programme', publisher: 'Junta de Andalucía', sourceType: 'official', url: 'https://www.juntadeandalucia.es/export/drupaljda/Dossier_DIMS_160421.pdf', accessedAt: '2026-08-24', language: 'es', scope: 'Official description of visible urban elements: forum, theatre, basilica, factories, temples and baths.', limitations: 'An event document; its schedule is obsolete and only the heritage description is reused.', reuse: 'link-and-cite' },
  { id: 'bolonia-dune-official-2026', title: 'Monumento Natural Duna de Bolonia', publisher: 'Junta de Andalucía — Portal Ambiental', sourceType: 'official', url: 'https://www.juntadeandalucia.es/medioambiente/portal/areas-tematicas/espacios-protegidos/legislacion-autonomica-nacional/monumentos-naturales/monumento-natural-duna-bolonia', accessedAt: '2026-08-24', language: 'es', scope: 'Official status, area and physical description of the active dune.', limitations: 'Does not by itself establish today’s permitted paths, parking or safe climbing conditions.', reuse: 'link-and-cite' },
  { id: 'tarifa-tourism-baelo-2026', title: 'Ruinas romanas de Baelo Claudia', publisher: 'Turismo de Tarifa', sourceType: 'official', url: 'https://turismodetarifa.com/que-visitar/ruinas-baelo-claudia/', accessedAt: '2026-08-24', language: 'es', scope: 'Municipal visitor orientation, historic port and salting context, and road approach.', limitations: 'Road, parking and access instructions require current confirmation.', reuse: 'link-and-cite' },
] as const);

export type TarifaBoloniaBaeloSourceId = (typeof tarifaBoloniaBaeloSources)[number]['id'];
