import { defineKnowledgeSources } from '../../schema';

export const tarifaIdentityHistorySources = defineKnowledgeSources([
  { id: 'tarifa-tourism-old-town-2026', title: 'Casco Antiguo de Tarifa', publisher: 'Turismo de Tarifa', sourceType: 'official', url: 'https://turismodetarifa.com/que-visitar/casco-antiguo/', accessedAt: '2026-08-24', language: 'es', scope: 'Street pattern, named routes, plazas, civic buildings and Miramar orientation.', limitations: 'Visitor description rather than a complete architectural survey; access and business details are volatile.', reuse: 'link-and-cite' },
  { id: 'tarifa-tourism-walls-route-2026', title: 'Ruta de las Murallas', publisher: 'Turismo de Tarifa', sourceType: 'official', url: 'https://turismodetarifa.com/ruta-de-las-murallas/', accessedAt: '2026-08-24', language: 'es', scope: 'Official interpretation of castle construction, later fortifications and the surviving wall circuit.', limitations: 'Does not establish current opening hours or accessibility of every element.', reuse: 'link-and-cite' },
  { id: 'tarifa-tourism-puerta-jerez-2026', title: 'Puerta de Jerez', publisher: 'Turismo de Tarifa', sourceType: 'official', url: 'https://turismodetarifa.com/que-visitar/puerta-jerez/', accessedAt: '2026-08-24', language: 'es', scope: 'Architecture, restoration and role of Puerta de Jerez as an old-town entrance.', limitations: 'Some historical interpretation is not accompanied by archival citations.', reuse: 'link-and-cite' },
  { id: 'tarifa-tourism-plazas-route-2026', title: 'Ruta de las Plazas', publisher: 'Turismo de Tarifa', sourceType: 'official', url: 'https://turismodetarifa.com/ruta-de-las-plazas/', accessedAt: '2026-08-24', language: 'es', scope: 'Municipal walking route through plazas, Miramar and the street fabric.', limitations: 'Includes interpretive and promotional language; current conditions must be checked.', reuse: 'link-and-cite' },
  { id: 'junta-tarifa-bic-record-2023', title: 'Provincial Heritage Commission act 02/2023', publisher: 'Junta de Andalucía', sourceType: 'official', url: 'https://www.juntadeandalucia.es/sites/default/files/2023-04/ACTA%2002_2023%20DE%2008_03_23_%20Transparencia%28F%29.pdf', accessedAt: '2026-08-24', language: 'es', scope: 'Official record of the protected historic ensemble, urban wall and castle heritage context.', limitations: 'Administrative act, not a visitor guide; cited decree date must be presented as recorded in the document.', reuse: 'link-and-cite' },
] as const);

export type TarifaIdentityHistorySourceId = (typeof tarifaIdentityHistorySources)[number]['id'];
