import { defineKnowledgeRecommendations } from '../../schema';

export const tarifaActivitiesRecommendations = defineKnowledgeRecommendations([
  {
    id: 'tarifa.activities.swim-en-el-mar',
    destination: 'tarifa',
    topic: 'activities',
    place: { name: 'Swim en el Mar', kind: 'provider', website: 'https://www.swimenelmar.com', phone: '+34610984300' },
    summary: 'Swim en el Mar: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.activities.aventura-ecuestre',
    destination: 'tarifa',
    topic: 'activities',
    place: { name: 'Aventura Ecuestre', kind: 'provider', website: 'https://www.aventuraecuestre.com/our-shop/?lang=en' },
    summary: 'Aventura Ecuestre: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.activities.hurricane-hipica',
    destination: 'tarifa',
    topic: 'activities',
    place: { name: 'Hurricane Hípica Tarifa', kind: 'provider', website: 'https://www.tarifahip.com/en/' },
    summary: 'Hurricane Hípica Tarifa: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.activities.south-adventures',
    destination: 'tarifa',
    topic: 'activities',
    place: { name: 'South Adventures', kind: 'provider', website: 'https://www.thesouthadventures.com/' },
    summary: 'South Adventures: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.activities.explore-and-fishing-tarifa',
    destination: 'tarifa',
    topic: 'activities',
    place: { name: 'Explore and Fishing Tarifa', kind: 'provider', website: 'https://www.exploreandfishingtarifa.com' },
    summary: 'Explore and Fishing Tarifa: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.activities.toms-catch',
    destination: 'tarifa',
    topic: 'activities',
    place: { name: 'Tom’s Catch', kind: 'provider', website: 'https://www.tomscatch.com/fishing-in-tarifa/explorer-191', phone: '+34651377316' },
    summary: 'Tom’s Catch: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  }
]);
