import { defineKnowledgeRecommendations } from '../../schema';

export const tarifaEssentialsRecommendations = defineKnowledgeRecommendations([
  {
    id: 'tarifa.essentials.pastelito',
    destination: 'tarifa',
    topic: 'essentials',
    place: { name: 'Pastelito', kind: 'shop', address: 'C. Los Barrios 4', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pastelito+C.+Los+Barrios+4+11380+Tarifa' },
    summary: 'Pastelito: listed in the AMARA guide as a shop used by guests; identity and link only.',
    access: [{ from: 'amara-family-surf', distanceMetres: 350, walkMinutes: 4 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.essentials.pasteleria-la-tarifena',
    destination: 'tarifa',
    topic: 'essentials',
    place: { name: 'Pastelería La Tarifeña', kind: 'shop', address: 'C. Cigüeña Negra 98', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pasteler%C3%ADa+La+Tarife%C3%B1a+Cig%C3%BCe%C3%B1a+Negra+98+11380+Tarifa' },
    summary: 'Pastelería La Tarifeña: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.essentials.pasteleria-bernal',
    destination: 'tarifa',
    topic: 'essentials',
    place: { name: 'Pastelería Bernal', kind: 'shop', address: 'C. Sancho IV el Bravo 3', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pasteler%C3%ADa+Bernal+C.+Sancho+IV+el+Bravo+3+11380+Tarifa' },
    summary: 'Pastelería Bernal: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.essentials.mercadona',
    destination: 'tarifa',
    topic: 'essentials',
    place: { name: 'Mercadona', kind: 'shop', address: 'C. Batalla del Salado', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mercadona+C.+Batalla+del+Salado+11380+Tarifa' },
    summary: 'Mercadona: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.essentials.lidl',
    destination: 'tarifa',
    topic: 'essentials',
    place: { name: 'Lidl', kind: 'shop', address: 'C. Coronel Francisco Valdés 27', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lidl+C.+Coronel+Francisco+Vald%C3%A9s+27+11380+Tarifa' },
    summary: 'Lidl: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.essentials.dia',
    destination: 'tarifa',
    topic: 'essentials',
    place: { name: 'DIA', kind: 'shop', address: 'C. San Sebastián 30', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=DIA+C.+San+Sebasti%C3%A1n+30+11380+Tarifa' },
    summary: 'DIA: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.essentials.supeco',
    destination: 'tarifa',
    topic: 'essentials',
    place: { name: 'Supeco', kind: 'shop', address: 'Calle San José 67', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Supeco+Calle+San+Jos%C3%A9+67+11380+Tarifa' },
    summary: 'Supeco: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.essentials.mercado-publico',
    destination: 'tarifa',
    topic: 'essentials',
    place: { name: 'Mercado Público de Tarifa', kind: 'shop', address: 'C. Colón 5', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mercado+P%C3%BAblico+de+Tarifa+C.+Col%C3%B3n+5+11380+Tarifa' },
    summary: 'Mercado Público de Tarifa: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.essentials.centro-de-salud-tarifa',
    destination: 'tarifa',
    topic: 'essentials',
    place: { name: 'Centro de Salud Tarifa', kind: 'service', address: 'Calle Antonio Maura, s/n, 11380 Tarifa', mapsUrl: 'https://share.google/kThtXHL43CfcwzfDC', phone: '+34956012007' },
    summary: 'For non-emergency medical care, the nearest 24-hour public health centre is: Centro de Salud Tarifa Calle Antonio Maura, s/n 11380 Tarifa Tel. +34 956 01 20 07 Open 24 hours.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  }
]);
