import { defineKnowledgeRecommendations } from '../../schema';

export const tarifaFoodDrinkRecommendations = defineKnowledgeRecommendations([
  {
    id: 'tarifa.food-drink.el-chiringuito',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'El Chiringuito', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Chiringuito+Tarifa' },
    summary: 'El Chiringuito: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.balneario-beach-club',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Balneario Beach Club Tarifa', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Balneario+Beach+Club+Tarifa' },
    summary: 'Balneario Beach Club Tarifa: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.waikiki',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Waikiki', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Waikiki+Tarifa' },
    summary: 'Waikiki: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.demente',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'DEMENTE', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=DEMENTE+Tarifa' },
    summary: 'DEMENTE: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.carbones13',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'CARBONES13', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=CARBONES13+Tarifa' },
    summary: 'CARBONES13: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.aqua',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'AQUA', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=AQUA+Tarifa' },
    summary: 'AQUA: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.waves',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'WAVES', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=WAVES+Tarifa' },
    summary: 'WAVES: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.tumbao',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'TUMBAO', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=TUMBAO+Tarifa' },
    summary: 'TUMBAO: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.gioelia-cremeria',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Gioelia Cremeria', kind: 'shop', address: 'Guzmán el Bueno 12', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=GIOELIA+CREMERIA+Guzm%C3%A1n+el+Bueno+12+Tarifa' },
    summary: 'Gioelia Cremeria: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.fragola-helados',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Fragola Helados-Café', kind: 'shop', address: 'Sancho IV el Bravo 24', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Fragola+Helados+Sancho+IV+el+Bravo+24+Tarifa' },
    summary: 'Fragola Helados-Café: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.surla',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'SURLA', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=SURLA+Tarifa' },
    summary: 'This surfer haven serves superfood-packed breakfasts, perfect for health-conscious travellers looking for high-quality fuel.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.powerhouse',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'POWERHOUSE', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=POWERHOUSE+Tarifa' },
    summary: 'Beside the road to Valdevaqueros, Powerhouse offers hearty breakfasts for kitesurfing and action-packed days.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.cafe-azul',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'CAFÉ AZUL', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=CAF%C3%89+AZUL+Tarifa' },
    summary: 'A Tarifa institution for decades and a classic place for a relaxed breakfast by Puerta de Jerez.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.helenas-kitchen',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'HELENA’S KITCHEN', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=HELENA%E2%80%99S+KITCHEN+Tarifa' },
    summary: 'This cooking school is in the same building as your apartment and also serves excellent breakfasts.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.marisqueria-del-puerto',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Marisquería del Puerto', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Marisquer%C3%ADa+del+Puerto+Tarifa' },
    summary: 'Fresh seafood dishes with outdoor seating overlooking the harbour.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.el-campero',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'El Campero', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Campero+Tarifa' },
    summary: 'Renowned for its tuna specialities and also offers gluten-free options.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.varadero',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Varadero', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Varadero+Tarifa' },
    summary: 'Seafood delicacies in a beachfront setting.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.el-vegetariano-de-tarifa',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'El Vegetariano de Tarifa', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Vegetariano+de+Tarifa' },
    summary: 'A cosy restaurant serving vegetarian and vegan dishes with outdoor seating.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.raices',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Raices', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Raices+Tarifa' },
    summary: 'Creative vegetarian and vegan options made with locally sourced ingredients.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.raw-cakes-tarifa',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Raw Cakes Tarifa', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Raw+Cakes+Tarifa' },
    summary: 'Delicious plant-based desserts in a relaxed setting.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.el-lola',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'El Lola', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Lola+Tarifa' },
    summary: 'Authentic local cuisine in a charming setting with a terrace.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.el-varadero',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'El Varadero', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Varadero+Tarifa' },
    summary: 'Traditional dishes with fresh ingredients and views of the coastline.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.otero',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Otero', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Otero+Tarifa' },
    summary: 'Local specialities and classic Spanish dishes in a warm atmosphere.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.asador-la-burla',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Asador La Burla', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Asador+La+Burla+Tarifa' },
    summary: 'Grilled meat dishes in beautiful surroundings.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.el-rancho',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'El Rancho', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Rancho+Tarifa' },
    summary: 'Known for steaks and barbecue specialities.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.la-torre',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'La Torre', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Torre+Tarifa' },
    summary: 'Meat dishes made with local ingredients and accompanied by stunning views.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.la-lola',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'La Lola', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Lola+Tarifa' },
    summary: 'An authentic Andalusian tapas experience.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.bar-el-frances',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Bar El Francés', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bar+El+Franc%C3%A9s+Tarifa' },
    summary: 'A popular tapas spot with outdoor seating.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.meson-el-patio',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Mesón el Patio', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mes%C3%B3n+el+Patio+Tarifa' },
    summary: 'Traditional Spanish tapas in a cosy atmosphere.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.bar-el-pupilo',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Bar El Pupilo', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bar+El+Pupilo+Tarifa' },
    summary: 'Classic and creative tapas in a lively setting.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.pueblo-nomada',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Pueblo Nómada', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pueblo+N%C3%B3mada+Tarifa' },
    summary: 'Delicious pizza with wonderful ocean views near the apartment.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.la-dolce-vita',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'La Dolce Vita', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Dolce+Vita+Tarifa' },
    summary: 'Authentic Italian pizza, including gluten-free options.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.la-ruota',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'La Ruota', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Ruota+Tarifa' },
    summary: 'Pizza made with fresh ingredients, with vegetarian and gluten-free choices.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.mandragora',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Mandragora', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mandragora+Tarifa' },
    summary: 'Delicious Moroccan cuisine with outdoor seating.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.tajinaste',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Tajinaste', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tajinaste+Tarifa' },
    summary: 'Authentic Moroccan dishes with a modern twist.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.lia-me',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'LIA.me', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=LIA.me+Tarifa' },
    summary: 'For us, the best Italian restaurant in Tarifa.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.osteria-del-sole',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'OSTERIA DEL SOLE', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=OSTERIA+DEL+SOLE+Tarifa' },
    summary: 'Italian cuisine in one of the loveliest chiringuitos, with ocean views.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.silos-19',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Silos 19', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Silos+19+Tarifa' },
    summary: 'Modern Andalusian cuisine in an elegant atmosphere.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.food-drink.boccabuena-plaza',
    destination: 'tarifa',
    topic: 'food-drink',
    place: { name: 'Boccabuena Plaza', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Boccabuena+Plaza+Tarifa' },
    summary: 'Set on a car-free plaza in the heart of the old town, making it a relaxed choice for families with young children.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  }
]);
