import { defineKnowledgeRecommendations } from '../../schema';

export const tarifaNightlifeRecommendations = defineKnowledgeRecommendations([
  {
    id: 'tarifa.nightlife.la-onda',
    destination: 'tarifa',
    topic: 'nightlife',
    place: { name: 'La Onda', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Onda+Tarifa' },
    summary: 'La Onda: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.nightlife.surf-bar',
    destination: 'tarifa',
    topic: 'nightlife',
    place: { name: 'Surf Bar', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Surf+Bar+Tarifa' },
    summary: 'Surf Bar: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.nightlife.taco-way',
    destination: 'tarifa',
    topic: 'nightlife',
    place: { name: 'Taco Way', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Taco+Way+Tarifa' },
    summary: 'Taco Way: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.nightlife.venice-cocktail-bar',
    destination: 'tarifa',
    topic: 'nightlife',
    place: { name: 'Venice Cocktail Bar', kind: 'bar', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Venice+Cocktail+Bar+Tarifa' },
    summary: 'Venice Cocktail Bar: listed in the AMARA guide as a bar used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.nightlife.la-ruina',
    destination: 'tarifa',
    topic: 'nightlife',
    place: { name: 'La Ruina', kind: 'venue', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Ruina+Tarifa' },
    summary: 'La Ruina: listed in the AMARA guide as a venue used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.nightlife.mombassa',
    destination: 'tarifa',
    topic: 'nightlife',
    place: { name: 'Mombassa', kind: 'venue', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mombassa+Tarifa' },
    summary: 'Mombassa: listed in the AMARA guide as a venue used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'tarifa.nightlife.cafe-del-mar',
    destination: 'tarifa',
    topic: 'nightlife',
    place: { name: 'Café del Mar', kind: 'venue', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Caf%C3%A9+del+Mar+Tarifa' },
    summary: 'Café del Mar: listed in the AMARA guide as a venue used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  }
]);
