import { defineKnowledgeFacts } from '../../../schema';
import type { TarifaBeachesWindSourceId } from '../../../sources/locations/tarifaBeachesWindSources';
import type { TarifaGeographySourceId } from '../../../sources/locations/tarifaGeographySources';

type FactInput = Parameters<typeof defineKnowledgeFacts>[0][number] & { sourceIds: readonly (TarifaBeachesWindSourceId | TarifaGeographySourceId)[] };

const facts = [
  { id: 'tarifa.beaches.coast.two-sided-orientation', subject: 'tarifa', topic: 'beaches-wind-watersports', statement: 'At the causeway to Isla de Tarifa, Playa Chica lies on the Mediterranean/Strait side while the long Los Lances–Valdevaqueros coast extends westward on the Atlantic side.', status: 'verified', sourceIds: ['tarifa-tourism-isla-de-las-palomas-2026', 'tarifa-tourism-beaches-2026'], checkedAt: '2026-08-24', reviewAfter: '2029-08-24', volatility: 'low', claimBoundary: 'This is geographic orientation, not a promise of conditions or suitability.' },
  { id: 'tarifa.beaches.playa-chica.compact-town-beach', subject: 'tarifa', topic: 'beaches-wind-watersports', statement: 'Playa Chica is the compact town beach beside the island causeway on Tarifa’s eastern side.', status: 'verified', sourceIds: ['tarifa-tourism-isla-de-las-palomas-2026', 'tarifa-tourism-beaches-2026'], checkedAt: '2026-08-24', reviewAfter: '2029-08-24', volatility: 'low', claimBoundary: 'The beach may feel more protected in some wind situations, but it is not universally sheltered or safe.' },
  { id: 'tarifa.beaches.los-lances.protected-and-recreational', subject: 'tarifa', topic: 'beaches-wind-watersports', statement: 'Los Lances is both a major recreational beach landscape and part of a protected natural area with important bird habitat.', status: 'verified', sourceIds: ['junta-estrecho-visitor-2026', 'junta-lances-plan-2024', 'tarifa-tourism-beaches-2026'], checkedAt: '2026-08-24', reviewAfter: '2029-08-24', volatility: 'low', claimBoundary: 'Recreation must be reconciled with current protected-zone rules and seasonal wildlife measures.' },
  { id: 'tarifa.beaches.lances-north.watersports-cluster', subject: 'tarifa', topic: 'beaches-wind-watersports', statement: 'Municipal tourism information identifies the northern Los Lances sector as a principal concentration of wind- and kitesurf activity and schools.', status: 'verified', sourceIds: ['tarifa-tourism-beaches-2026', 'tarifa-tourism-watersports-schools-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-08-24', volatility: 'medium', claimBoundary: 'School operation, exact launch zones and suitability require live confirmation.' },
  { id: 'tarifa.watersports.tuition-market', subject: 'tarifa', topic: 'beaches-wind-watersports', statement: 'Tarifa has a developed market for instruction in kitesurfing, windsurfing, surfing and stand-up paddling.', status: 'verified', sourceIds: ['tarifa-tourism-watersports-schools-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-08-24', volatility: 'medium', claimBoundary: 'Directory inclusion is not an AMARA endorsement; licensing, insurance and availability must be checked.' },
  { id: 'tarifa.beaches.valdevaqueros-punta-paloma.western-system', subject: 'tarifa', topic: 'beaches-wind-watersports', statement: 'Valdevaqueros and Punta Paloma form a connected western beach-and-dune landscape beyond Los Lances.', status: 'verified', sourceIds: ['tarifa-tourism-beaches-2026'], checkedAt: '2026-08-24', reviewAfter: '2029-08-24', volatility: 'low', claimBoundary: 'Road, parking and dune-related access can change and are not guaranteed.' },
  { id: 'tarifa.wind.live-forecast-required', subject: 'tarifa', topic: 'beaches-wind-watersports', statement: 'Beach and watersport decisions in Tarifa require a current wind and marine forecast rather than a fixed destination rule.', status: 'verified', sourceIds: ['aemet-tarifa-forecast-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-08-24', volatility: 'high', claimBoundary: 'No stored fact should prescribe a beach solely from the words Levante or Poniente.' },
  { id: 'tarifa.watersports.no-universal-beginner-beach', subject: 'tarifa', topic: 'beaches-wind-watersports', statement: 'The evidence does not support naming one Tarifa beach as universally safe or suitable for beginners independent of wind, tide, zoning, crowding and instruction.', status: 'verified', sourceIds: ['aemet-tarifa-forecast-2026', 'junta-lances-plan-2024', 'tarifa-tourism-watersports-schools-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-08-24', volatility: 'high', claimBoundary: 'Beginner recommendations must be condition-specific and preferably instructor-led.' },
] as const satisfies readonly FactInput[];

export const tarifaBeachesWindWatersportsFacts = defineKnowledgeFacts(facts);
export type TarifaBeachesWindWatersportsFactId = (typeof tarifaBeachesWindWatersportsFacts)[number]['id'];
