import { defineKnowledgeFacts } from '../../../schema';
import type { TarifaBoloniaBaeloSourceId } from '../../../sources/locations/tarifaBoloniaBaeloSources';
import type { TarifaBeachesWindSourceId } from '../../../sources/locations/tarifaBeachesWindSources';

type FactInput = Parameters<typeof defineKnowledgeFacts>[0][number] & { sourceIds: readonly (TarifaBoloniaBaeloSourceId | TarifaBeachesWindSourceId)[] };

const facts = [
  { id: 'tarifa.baelo.maritime-roman-city', subject: 'tarifa', topic: 'bolonia-baelo-western-coast', statement: 'Baelo Claudia is an excavated Roman maritime city beside the Ensenada de Bolonia and is administered as an official archaeological ensemble.', status: 'verified', sourceIds: ['baelo-official-museum-2026', 'tarifa-tourism-baelo-2026'], checkedAt: '2026-08-24', reviewAfter: '2030-08-24', volatility: 'low', claimBoundary: 'The archaeological ensemble is not the whole modern settlement or beach of Bolonia.' },
  { id: 'tarifa.baelo.urban-elements-visible', subject: 'tarifa', topic: 'bolonia-baelo-western-coast', statement: 'The visitable archaeological landscape includes the forum, theatre, basilica, temples, baths and fish-processing factories, making multiple functions of a Roman city legible in one site.', status: 'verified', sourceIds: ['baelo-education-monuments-2021', 'baelo-official-museum-2026'], checkedAt: '2026-08-24', reviewAfter: '2030-08-24', volatility: 'low', claimBoundary: 'Individual areas may close for conservation or works.' },
  { id: 'tarifa.baelo.fish-salting-garum-economy', subject: 'tarifa', topic: 'bolonia-baelo-western-coast', statement: 'Fish salting and sauce production formed a visible industrial component of Baelo Claudia’s coastal economy.', status: 'verified', sourceIds: ['baelo-education-monuments-2021', 'tarifa-tourism-baelo-2026'], checkedAt: '2026-08-24', reviewAfter: '2030-08-24', volatility: 'low', claimBoundary: 'This ancient industry must not be presented as an unbroken modern restaurant tradition.' },
  { id: 'tarifa.baelo.tangier-link.ancient-port', subject: 'tarifa', topic: 'bolonia-baelo-western-coast', statement: 'Ancient written tradition identifies Baelo as a Strait-facing port connected with Tingis, present-day Tangier.', status: 'partially-verified', sourceIds: ['tarifa-tourism-baelo-2026'], checkedAt: '2026-08-24', reviewAfter: '2030-08-24', volatility: 'low', claimBoundary: 'This historical connection is not evidence for a modern ferry route from Bolonia.' },
  { id: 'tarifa.bolonia.dune.active-protected-monument', subject: 'tarifa', topic: 'bolonia-baelo-western-coast', statement: 'The Duna de Bolonia is a protected active dune declared a natural monument in 2001.', status: 'verified', sourceIds: ['bolonia-dune-official-2026'], checkedAt: '2026-08-24', reviewAfter: '2030-08-24', volatility: 'low', claimBoundary: 'Protected status requires visitors to follow current paths and conservation instructions.' },
  { id: 'tarifa.bolonia.dune.official-dimensions', subject: 'tarifa', topic: 'bolonia-baelo-western-coast', statement: 'The Junta describes the Duna de Bolonia as more than 30 metres high and records the natural monument as 13.17 hectares.', status: 'verified', sourceIds: ['bolonia-dune-official-2026'], checkedAt: '2026-08-24', reviewAfter: '2030-08-24', volatility: 'low', claimBoundary: 'These are protected-feature measurements, not a walking-distance or climb-time estimate.' },
  { id: 'tarifa.bolonia.archaeology-nature-combination', subject: 'tarifa', topic: 'bolonia-baelo-western-coast', statement: 'Baelo Claudia, Bolonia beach and the protected dune occupy the same bay landscape, allowing archaeology, coast and geomorphology to be understood together.', status: 'verified', sourceIds: ['baelo-official-museum-2026', 'bolonia-dune-official-2026', 'tarifa-tourism-beaches-2026'], checkedAt: '2026-08-24', reviewAfter: '2029-08-24', volatility: 'low', claimBoundary: 'A combined visit still depends on current opening, weather, access and visitor capacity.' },
  { id: 'tarifa.bolonia.access.live-check-required', subject: 'tarifa', topic: 'bolonia-baelo-western-coast', statement: 'Opening hours, admission rules, guided visits, events, road access and parking for a Bolonia–Baelo outing require a current pre-departure check.', status: 'verified', sourceIds: ['baelo-agenda-2026', 'tarifa-tourism-baelo-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-02-24', volatility: 'high', claimBoundary: 'No stored schedule or parking promise should be treated as evergreen.' },
] as const satisfies readonly FactInput[];

export const tarifaBoloniaBaeloWesternCoastFacts = defineKnowledgeFacts(facts);
export type TarifaBoloniaBaeloWesternCoastFactId = (typeof tarifaBoloniaBaeloWesternCoastFacts)[number]['id'];
