import { defineKnowledgeFacts } from '../../../schema';
import type { TarifaDayTripSourceId } from '../../../sources/locations/tarifaDayTripSources';

type FactInput = Parameters<typeof defineKnowledgeFacts>[0][number] & { sourceIds: readonly TarifaDayTripSourceId[] };

const facts = [
  { id: 'tarifa.daytrip.tangier.direct-ferry', subject: 'tarifa', topic: 'day-trips-cross-border', statement: 'Tarifa has a direct passenger-ferry connection with Tangier Ville across the Strait.', status: 'verified', sourceIds: ['apba-tarifa-tangier-route-2026', 'balearia-tarifa-tangier-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-02-24', volatility: 'high', claimBoundary: 'Operation, operator, frequency and disruption status must be checked for the travel date.' },
  { id: 'tarifa.daytrip.tangier.indicative-crossing-one-hour', subject: 'tarifa', topic: 'day-trips-cross-border', statement: 'The current operator describes the Tarifa–Tangier Ville sea crossing as approximately one hour.', status: 'partially-verified', sourceIds: ['balearia-tarifa-tangier-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-02-24', volatility: 'high', claimBoundary: 'This excludes check-in, border formalities, waiting and weather or operational delay.' },
  { id: 'tarifa.daytrip.tangier.cross-border-not-domestic', subject: 'tarifa', topic: 'day-trips-cross-border', statement: 'A Tangier excursion is an international border crossing into Morocco, not a simple extension of a Spanish domestic day trip.', status: 'verified', sourceIds: ['spain-morocco-travel-advice-2026', 'apba-tarifa-tangier-route-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-02-24', volatility: 'high', claimBoundary: 'Document, visa and entry rules depend on nationality and current law.' },
  { id: 'tarifa.daytrip.morocco.spanish-dni-insufficient-2026', subject: 'tarifa', topic: 'day-trips-cross-border', statement: 'As of the current Spanish government guidance, a Spanish DNI alone is not sufficient for entry into Morocco; Spanish citizens require a valid passport and do not need a tourist visa for an ordinary short visit.', status: 'verified', sourceIds: ['spain-morocco-travel-advice-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-02-24', volatility: 'high', claimBoundary: 'This applies to Spanish citizens under current guidance; every traveller must verify rules for their nationality and circumstances.' },
  { id: 'tarifa.daytrip.morocco.insurance-current-advice', subject: 'tarifa', topic: 'day-trips-cross-border', statement: 'Current Spanish government advice recommends reliable travel insurance including medical assistance and repatriation for Morocco.', status: 'verified', sourceIds: ['spain-morocco-travel-advice-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-02-24', volatility: 'high', claimBoundary: 'This is travel guidance, not a statement that one policy is sufficient for every traveller.' },
  { id: 'tarifa.daytrip.gibraltar.documents-live-check', subject: 'tarifa', topic: 'day-trips-cross-border', statement: 'Gibraltar is reachable by road from Spain, but travellers should carry valid travel documents and confirm current visa and border arrangements.', status: 'verified', sourceIds: ['visit-gibraltar-access-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-02-24', volatility: 'high', claimBoundary: 'Requirements differ by nationality and can change; no frictionless-crossing promise is durable.' },
  { id: 'tarifa.daytrip.gibraltar.upper-rock', subject: 'tarifa', topic: 'day-trips-cross-border', statement: 'Gibraltar’s Upper Rock Nature Reserve forms a principal cluster of natural and historic visitor attractions.', status: 'verified', sourceIds: ['visit-gibraltar-reserve-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-02-24', volatility: 'medium', claimBoundary: 'Current admission, site closures and transport inside the reserve must be checked.' },
  { id: 'tarifa.daytrip.vejer.hill-town-heritage', subject: 'tarifa', topic: 'day-trips-cross-border', statement: 'Vejer de la Frontera offers a contrasting elevated white-town experience with Arab-Andalusian heritage and a walkable historic fabric.', status: 'verified', sourceIds: ['vejer-tourism-official-2026'], checkedAt: '2026-08-24', reviewAfter: '2029-08-24', volatility: 'low', claimBoundary: 'This does not establish a guaranteed journey time or parking outcome from Tarifa.' },
  { id: 'tarifa.daytrip.cadiz.city-heritage-option', subject: 'tarifa', topic: 'day-trips-cross-border', statement: 'Cádiz provides a larger historic-city day-trip option with a distinct old-town and maritime heritage offer.', status: 'verified', sourceIds: ['cadiz-tourism-official-2026'], checkedAt: '2026-08-24', reviewAfter: '2029-08-24', volatility: 'low', claimBoundary: 'Suitability as a day trip depends on live transport or driving conditions and the guest’s intended itinerary.' },
] as const satisfies readonly FactInput[];

export const tarifaDayTripsCrossBorderFacts = defineKnowledgeFacts(facts);
export type TarifaDayTripsCrossBorderFactId = (typeof tarifaDayTripsCrossBorderFacts)[number]['id'];
