import { defineKnowledgeFacts } from '../../../schema';
import type { TarifaFoodAtmosphereSourceId } from '../../../sources/locations/tarifaFoodAtmosphereSources';
import type { TarifaIdentityHistorySourceId } from '../../../sources/locations/tarifaIdentityHistorySources';
import type { TarifaBoloniaBaeloSourceId } from '../../../sources/locations/tarifaBoloniaBaeloSources';

type FactInput = Parameters<typeof defineKnowledgeFacts>[0][number] & { sourceIds: readonly (TarifaFoodAtmosphereSourceId | TarifaIdentityHistorySourceId | TarifaBoloniaBaeloSourceId)[] };

const facts = [
  { id: 'tarifa.food.almadraba.regional-tradition', subject: 'tarifa', topic: 'food-evenings-lived-atmosphere', statement: 'Tarifa is one of the Cádiz-coast towns associated by official regional tourism sources with the traditional spring almadraba bluefin-tuna fishery.', status: 'verified', sourceIds: ['andalucia-almadraba-route-2026', 'andalucia-tuna-tradition-2026'], checkedAt: '2026-08-24', reviewAfter: '2028-08-24', volatility: 'medium', claimBoundary: 'This does not prove that tuna served by any given business is local, seasonal or almadraba-caught.' },
  { id: 'tarifa.food.tuna-events.seasonal', subject: 'tarifa', topic: 'food-evenings-lived-atmosphere', statement: 'Tarifa has participated in seasonal tuna-focused gastronomic events linked to the spring almadraba cycle.', status: 'verified', sourceIds: ['andalucia-tuna-tradition-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-03-01', volatility: 'high', claimBoundary: 'The event name, dates, format and participating venues must be checked for the current year.' },
  { id: 'tarifa.food.baelo.ancient-salting-context', subject: 'tarifa', topic: 'food-evenings-lived-atmosphere', statement: 'Baelo Claudia provides material evidence that fish salting and sauce production were economically important on this coast in the Roman period.', status: 'verified', sourceIds: ['baelo-education-monuments-2021'], checkedAt: '2026-08-24', reviewAfter: '2030-08-24', volatility: 'low', claimBoundary: 'Ancient garum production is historical context, not proof of direct recipe or business continuity today.' },
  { id: 'tarifa.evenings.old-town.plaza-network', subject: 'tarifa', topic: 'food-evenings-lived-atmosphere', statement: 'Tarifa’s historic centre contains a linked sequence of small plazas and narrow streets that supports walking between civic, cultural and hospitality uses.', status: 'verified', sourceIds: ['tarifa-tourism-old-town-2026', 'tarifa-tourism-plazas-route-2026'], checkedAt: '2026-08-24', reviewAfter: '2028-08-24', volatility: 'medium', claimBoundary: 'The physical network does not establish a uniform evening mood, noise level or opening pattern.' },
  { id: 'tarifa.evenings.old-town.mixed-uses', subject: 'tarifa', topic: 'food-evenings-lived-atmosphere', statement: 'Municipal interpretation identifies traditional businesses, restaurants, cultural spaces and public squares within the old-town walking environment.', status: 'verified', sourceIds: ['tarifa-tourism-old-town-2026', 'tarifa-tourism-plazas-route-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-08-24', volatility: 'medium', claimBoundary: 'Individual venues and uses can change and are not endorsed.' },
  { id: 'tarifa.atmosphere.subjective-claims-unverified', subject: 'tarifa', topic: 'food-evenings-lived-atmosphere', statement: 'The current evidence does not verify universal claims that Tarifa evenings are quiet, lively, bohemian, family-oriented or party-focused.', status: 'verified', sourceIds: ['tarifa-tourism-events-2026', 'tarifa-tourism-old-town-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-08-24', volatility: 'medium', claimBoundary: 'Such claims require dated first-hand observation by season, weekday, hour and micro-location.' },
  { id: 'tarifa.food.venue-selection.live-check', subject: 'tarifa', topic: 'food-evenings-lived-atmosphere', statement: 'Restaurant recommendations in Tarifa require live checks of opening, menu, dietary suitability, reservation policy and product provenance.', status: 'verified', sourceIds: ['tarifa-tourism-events-2026', 'andalucia-almadraba-route-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-02-24', volatility: 'high', claimBoundary: 'No venue should enter durable knowledge as an evergreen recommendation without a dated review process.' },
] as const satisfies readonly FactInput[];

export const tarifaFoodEveningsLivedAtmosphereFacts = defineKnowledgeFacts(facts);
export type TarifaFoodEveningsLivedAtmosphereFactId = (typeof tarifaFoodEveningsLivedAtmosphereFacts)[number]['id'];
