import { defineKnowledgeFacts } from '../../../schema';
import type { TarifaIdentityHistorySourceId } from '../../../sources/locations/tarifaIdentityHistorySources';
import type { TarifaGeographySourceId } from '../../../sources/locations/tarifaGeographySources';

type FactInput = Parameters<typeof defineKnowledgeFacts>[0][number] & { sourceIds: readonly (TarifaIdentityHistorySourceId | TarifaGeographySourceId)[] };

const facts = [
  { id: 'tarifa.identity.heritage.historic-ensemble-bic', subject: 'tarifa', topic: 'identity-history-old-town', statement: 'Tarifa’s historic centre is protected as a Bien de Interés Cultural historic ensemble, and its urban wall and Castillo de Guzmán el Bueno are separately protected monuments.', status: 'verified', sourceIds: ['junta-tarifa-bic-record-2023'], checkedAt: '2026-08-24', reviewAfter: '2031-08-24', volatility: 'low', claimBoundary: 'Protected status does not mean that every building or interior is publicly accessible.' },
  { id: 'tarifa.history.castle.caliphal-construction-960', subject: 'tarifa', topic: 'identity-history-old-town', statement: 'Official local interpretation dates the construction of Tarifa’s castle by the Umayyad caliph Abd al-Rahman III to 960 CE.', status: 'verified', sourceIds: ['tarifa-tourism-history-2026', 'tarifa-tourism-walls-route-2026'], checkedAt: '2026-08-24', reviewAfter: '2031-08-24', volatility: 'low', claimBoundary: 'Later Almohad and Christian interventions substantially modified the fortress.' },
  { id: 'tarifa.history.castle.strait-control', subject: 'tarifa', topic: 'identity-history-old-town', statement: 'The castle was established as a strategic stronghold for control of the Strait and was reinforced and adapted by later powers.', status: 'verified', sourceIds: ['tarifa-tourism-walls-route-2026', 'tarifa-tourism-history-2026'], checkedAt: '2026-08-24', reviewAfter: '2031-08-24', volatility: 'low', claimBoundary: 'This is a strategic function across periods, not evidence for one unchanged building state.' },
  { id: 'tarifa.history.conquest.1292', subject: 'tarifa', topic: 'identity-history-old-town', statement: 'Sancho IV’s forces took Tarifa in 1292 during the medieval struggle for control of the Strait.', status: 'verified', sourceIds: ['tarifa-tourism-history-2026', 'tarifa-tourism-puerta-jerez-2026'], checkedAt: '2026-08-24', reviewAfter: '2031-08-24', volatility: 'low', claimBoundary: 'This political milestone must not be presented as the origin of settlement in Tarifa.' },
  { id: 'tarifa.heritage.puerta-jerez.old-town-gateway', subject: 'tarifa', topic: 'identity-history-old-town', statement: 'Puerta de Jerez survives as a principal historic entrance to the walled old town, with a sequence of pointed and horseshoe arches between former flanking towers.', status: 'verified', sourceIds: ['tarifa-tourism-puerta-jerez-2026'], checkedAt: '2026-08-24', reviewAfter: '2031-08-24', volatility: 'low', claimBoundary: 'The fact describes the structure, not current vehicle or pedestrian routing.' },
  { id: 'tarifa.old-town.street-pattern.wind-response', subject: 'tarifa', topic: 'identity-history-old-town', statement: 'Municipal interpretation describes Tarifa’s narrow, frequently turning old-town streets as an inherited urban form that reduces the direct effect of wind inside the historic centre.', status: 'partially-verified', sourceIds: ['tarifa-tourism-old-town-2026', 'tarifa-tourism-plazas-route-2026'], checkedAt: '2026-08-24', reviewAfter: '2030-08-24', volatility: 'low', claimBoundary: 'This does not mean every street or plaza is sheltered under every wind direction and speed.' },
  { id: 'tarifa.old-town.calzada.former-watercourse', subject: 'tarifa', topic: 'identity-history-old-town', statement: 'Calle Sancho IV el Bravo, locally called La Calzada, follows a former stream course that was diverted and covered at the end of the nineteenth century.', status: 'verified', sourceIds: ['tarifa-tourism-old-town-2026', 'tarifa-tourism-plazas-route-2026'], checkedAt: '2026-08-24', reviewAfter: '2031-08-24', volatility: 'low', claimBoundary: 'This explains the street form; it is not a claim about present flood risk.' },
  { id: 'tarifa.heritage.san-mateo.early-sixteenth-century', subject: 'tarifa', topic: 'identity-history-old-town', statement: 'The municipal tourism record dates the construction of the Iglesia Mayor de San Mateo to the beginning of the sixteenth century.', status: 'verified', sourceIds: ['tarifa-tourism-old-town-2026'], checkedAt: '2026-08-24', reviewAfter: '2031-08-24', volatility: 'low', claimBoundary: 'Visitor access and service times require current confirmation.' },
  { id: 'tarifa.old-town.miramar.strait-viewpoint', subject: 'tarifa', topic: 'identity-history-old-town', statement: 'Plaza de Miramar is an established public viewpoint from the elevated southern edge of the historic centre towards the Strait and the African coast in suitable visibility.', status: 'verified', sourceIds: ['tarifa-tourism-old-town-2026', 'tarifa-tourism-plazas-route-2026'], checkedAt: '2026-08-24', reviewAfter: '2029-08-24', volatility: 'low', claimBoundary: 'Views of named African landmarks depend on weather and visibility and are not guaranteed.' },
] as const satisfies readonly FactInput[];

export const tarifaIdentityHistoryOldTownFacts = defineKnowledgeFacts(facts);
export type TarifaIdentityHistoryOldTownFactId = (typeof tarifaIdentityHistoryOldTownFacts)[number]['id'];
