import { defineKnowledgeFacts } from '../../../schema';
import type { TarifaNatureWildlifeSourceId } from '../../../sources/locations/tarifaNatureWildlifeSources';

type FactInput = Parameters<typeof defineKnowledgeFacts>[0][number] & { sourceIds: readonly TarifaNatureWildlifeSourceId[] };

const facts = [
  { id: 'tarifa.nature.estrecho.maritime-terrestrial-park', subject: 'tarifa', topic: 'strait-nature-wildlife', statement: 'Parque Natural del Estrecho is a protected maritime-terrestrial landscape spanning coastal and marine environments around the Strait.', status: 'verified', sourceIds: ['junta-estrecho-park-2026', 'junta-estrecho-declaration-2003'], checkedAt: '2026-08-24', reviewAfter: '2030-08-24', volatility: 'low', claimBoundary: 'The park extends beyond Tarifa town and not every sector has the same access or visitor facilities.' },
  { id: 'tarifa.nature.estrecho.bird-migration-corridor', subject: 'tarifa', topic: 'strait-nature-wildlife', statement: 'The Strait of Gibraltar is one of the most important intercontinental passage points for birds moving between European breeding areas and African wintering areas.', status: 'verified', sourceIds: ['junta-estrecho-declaration-2003', 'migres-programme-2026'], checkedAt: '2026-08-24', reviewAfter: '2030-08-24', volatility: 'low', claimBoundary: 'Importance of the corridor does not guarantee sightings of any species on a particular visit.' },
  { id: 'tarifa.nature.migres.long-term-monitoring', subject: 'tarifa', topic: 'strait-nature-wildlife', statement: 'Fundación Migres operates a long-term bird-migration monitoring programme in the Strait using standardised observation protocols.', status: 'verified', sourceIds: ['migres-programme-2026'], checkedAt: '2026-08-24', reviewAfter: '2028-08-24', volatility: 'medium', claimBoundary: 'Programme operation is not equivalent to open public access at every monitoring site.' },
  { id: 'tarifa.nature.birding.land-and-sea', subject: 'tarifa', topic: 'strait-nature-wildlife', statement: 'Tarifa supports both land-based observation of migrating birds and marine-bird observation from the coast or authorised excursions.', status: 'verified', sourceIds: ['tarifa-tourism-birds-2026', 'tarifa-tourism-cetaceans-2026'], checkedAt: '2026-08-24', reviewAfter: '2028-08-24', volatility: 'medium', claimBoundary: 'Site, season and weather determine what can be observed.' },
  { id: 'tarifa.nature.cetacean-excursions.from-port', subject: 'tarifa', topic: 'strait-nature-wildlife', statement: 'Commercial cetacean-watching excursions depart from Tarifa into the Strait.', status: 'verified', sourceIds: ['tarifa-tourism-cetaceans-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-08-24', volatility: 'medium', claimBoundary: 'Provider, duration, season and sailing status require live confirmation.' },
  { id: 'tarifa.nature.cetaceans.no-sighting-guarantee', subject: 'tarifa', topic: 'strait-nature-wildlife', statement: 'No specific whale, dolphin or orca sighting should be promised for a Tarifa excursion.', status: 'verified', sourceIds: ['tarifa-tourism-cetaceans-2026', 'boe-cetacean-protection-2007'], checkedAt: '2026-08-24', reviewAfter: '2027-08-24', volatility: 'medium', claimBoundary: 'Species presence and detectability vary; responsible operators cannot control wildlife.' },
  { id: 'tarifa.nature.cetaceans.protected-observation', subject: 'tarifa', topic: 'strait-nature-wildlife', statement: 'Cetacean observation in Spanish waters is subject to national protection rules governing approach and behaviour around the animals.', status: 'verified', sourceIds: ['boe-cetacean-protection-2007'], checkedAt: '2026-08-24', reviewAfter: '2029-08-24', volatility: 'low', claimBoundary: 'The legal framework does not certify individual operators; current authorisation should be checked.' },
  { id: 'tarifa.nature.trails.coast-and-viewpoints', subject: 'tarifa', topic: 'strait-nature-wildlife', statement: 'Official local visitor information identifies coastal paths and viewpoints as ways to experience the protected Strait landscape on land.', status: 'verified', sourceIds: ['tarifa-tourism-trails-2026'], checkedAt: '2026-08-24', reviewAfter: '2027-08-24', volatility: 'medium', claimBoundary: 'Trail condition, fire restrictions, weather, duration and accessibility require current confirmation.' },
] as const satisfies readonly FactInput[];

export const tarifaStraitNatureWildlifeFacts = defineKnowledgeFacts(facts);
export type TarifaStraitNatureWildlifeFactId = (typeof tarifaStraitNatureWildlifeFacts)[number]['id'];
