import { defineKnowledgeFacts } from '../../../schema';

export const tarifaWhereToStayFacts = defineKnowledgeFacts([
  { id: 'tarifa.stay.la-marina.planning-name', subject: 'tarifa', topic: 'where-to-stay-areas', statement: 'La Marina I appears in official Tarifa planning documentation.', status: 'verified', sourceIds: ['tarifa-la-marina-plan-2026'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'The planning name does not define every contemporary tourism use of “La Marina”.' },
  { id: 'tarifa.stay.los-lances.corridor', subject: 'tarifa', topic: 'where-to-stay-areas', statement: 'Los Lances is a long Atlantic beach and protected coastal context rather than one homogeneous urban neighbourhood.', status: 'verified', sourceIds: ['tarifa-los-lances-official-2026'], checkedAt: '2026-08-21', reviewAfter: '2027-08-21', volatility: 'low', claimBoundary: 'Every accommodation must be located by its actual urban or rural setting and access point.' },
  { id: 'tarifa.stay.historic-access.historical-rule', subject: 'tarifa', topic: 'where-to-stay-areas', statement: 'Tarifa has used controlled vehicle access for the historic centre.', status: 'partially-verified', sourceIds: ['tarifa-historic-access-2021'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'high', claimBoundary: 'The 2021 notice does not prove the complete current 2026 schedule, exemptions or enforcement rules.' },
  { id: 'tarifa.stay.amara.garage-supermarket', subject: 'tarifa', topic: 'where-to-stay-areas', statement: 'AMARA’s canonical property authoring states that Family & Surf has a private underground parking space and a supermarket directly opposite.', status: 'first-party-observation', sourceIds: ['amara-tarifa-location-baseline-2026'], checkedAt: '2026-08-21', volatility: 'medium', claimBoundary: 'These are operator-owned property facts, not general La Marina characteristics; retain them only as explicit AMARA statements.' },
  { id: 'tarifa.stay.amara.walking-time', subject: 'tarifa', topic: 'where-to-stay-areas', statement: 'AMARA’s current authoring gives an approximate 10–15-minute walk to the Old Town.', status: 'unverified', sourceIds: ['amara-tarifa-location-baseline-2026'], checkedAt: '2026-08-21', volatility: 'medium', claimBoundary: 'Start, destination, route and measurement method are undocumented; do not publish the number on the area guide until measured.' },
  { id: 'tarifa.stay.wind.property-specific', subject: 'tarifa', topic: 'where-to-stay-areas', statement: 'Wind exposure or shelter at an accommodation depends on exact orientation and building context and cannot be inferred from an area label alone.', status: 'partially-verified', sourceIds: ['tarifa-los-lances-official-2026'], checkedAt: '2026-08-21', reviewAfter: '2027-08-21', volatility: 'medium', claimBoundary: 'Do not promise wind protection or exposure for an area or AMARA property without site-specific evidence.' }
] as const);
