import { defineKnowledgeFacts } from '../../../schema';

export const tarifaWinterStaysFacts = defineKnowledgeFacts([
  { id: 'tarifa.winter.aemet-station-normal-source', subject: 'tarifa', topic: 'winter-stays', statement: 'AEMET publishes monthly climate normals for Tarifa station 6001 for the 1981–2010 normal period.', status: 'verified', sourceIds: ['tarifa-winter-aemet-normals-1981-2010'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'Detailed climate values and replacement by a newer common baseline belong to Climate & Seasons; normals are not a forecast.' },
  { id: 'tarifa.winter.levante-poniente-context', subject: 'tarifa', topic: 'winter-stays', statement: 'Official Junta information identifies Levante and Poniente as defining wind regimes in the Estrecho context.', status: 'verified', sourceIds: ['tarifa-winter-junta-wind-2026'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'No seasonal frequency, duration, exact strength, local shelter or day-specific condition follows from this qualitative source.' },
  { id: 'tarifa.winter.christmas-programme-2025-26', subject: 'tarifa', topic: 'winter-stays', statement: 'Tarifa’s official tourism channel published a municipal Christmas programme spanning late November 2025 to 5 January 2026.', status: 'verified', sourceIds: ['tarifa-winter-christmas-2025-26'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'high', claimBoundary: 'Historical example only; no later programme or individual event is guaranteed.' },
  { id: 'tarifa.winter.host-quieter-rhythm-baseline', subject: 'tarifa', topic: 'winter-stays', statement: 'AMARA’s current Tarifa authoring records Robert’s experience of winter as calmer and more familiar than the highly transient summer rhythm.', status: 'first-party-observation', sourceIds: ['amara-tarifa-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2027-02-21', volatility: 'medium', claimBoundary: 'Personal host experience, not a promise of quietness, social contact, business openings or the same guest experience.' },
  { id: 'tarifa.winter.amara-heating-baseline', subject: 'tarifa', topic: 'winter-stays', statement: 'AMARA’s current Tarifa authoring states that AMARA Family & Surf has heating and hot-and-cold air conditioning.', status: 'first-party-observation', sourceIds: ['amara-tarifa-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'medium', claimBoundary: 'Confirm equipment, rooms served and operation in a dated property evidence pack.' },
  { id: 'tarifa.winter.amara-fireplace-baseline', subject: 'tarifa', topic: 'winter-stays', statement: 'AMARA’s current Tarifa authoring states that AMARA Family & Surf has a wood-burning fireplace.', status: 'first-party-observation', sourceIds: ['amara-tarifa-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'medium', claimBoundary: 'Fuel, availability, operation and safety instructions require current operator confirmation.' },
  { id: 'tarifa.winter.amara-kitchen-laundry-baseline', subject: 'tarifa', topic: 'winter-stays', statement: 'AMARA’s current Tarifa authoring states that AMARA Family & Surf has a full kitchen and washing machine.', status: 'first-party-observation', sourceIds: ['amara-tarifa-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'medium', claimBoundary: 'An inventory should define the actual equipment and current availability before the winter page is revised.' },
  { id: 'tarifa.winter.amara-wifi-baseline', subject: 'tarifa', topic: 'winter-stays', statement: 'AMARA’s current Tarifa authoring states that AMARA Family & Surf has Wi-Fi.', status: 'first-party-observation', sourceIds: ['amara-tarifa-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'high', claimBoundary: 'No speed, uptime, workstation or workation suitability claim follows without a dated measurement and equipment check.' },
  { id: 'tarifa.winter.amara-garage-baseline', subject: 'tarifa', topic: 'winter-stays', statement: 'AMARA’s current Tarifa authoring states that AMARA Family & Surf includes a reserved underground parking space.', status: 'first-party-observation', sourceIds: ['amara-tarifa-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'medium', claimBoundary: 'Confirm vehicle-size, access and availability details; the space does not imply parking elsewhere.' },
  { id: 'tarifa.winter.amara-supermarket-baseline', subject: 'tarifa', topic: 'winter-stays', statement: 'AMARA’s current Tarifa authoring states that normal grocery shopping is directly opposite the property.', status: 'first-party-observation', sourceIds: ['amara-tarifa-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'high', claimBoundary: 'Business identity, opening, route and exact wording require a current dated check.' },
  { id: 'tarifa.winter.amara-old-town-walk-baseline', subject: 'tarifa', topic: 'winter-stays', statement: 'AMARA’s current Tarifa authoring describes the Old Town as approximately 10–15 minutes away on foot.', status: 'first-party-observation', sourceIds: ['amara-tarifa-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'medium', claimBoundary: 'Start, destination, route, mode and measurement date are undocumented; do not publish as a verified duration until reproduced.' }
] as const);
