import { defineKnowledgeRecommendations } from '../../schema';

export const nerjaAdventureRecommendations = defineKnowledgeRecommendations([
  {
    id: 'nerja.adventure.educare-aventura',
    destination: 'nerja',
    topic: 'adventure',
    place: { name: 'Educare Aventura', kind: 'provider', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Educare+Aventura+Nerja' },
    summary: 'Educare Aventura: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.adventure.local-experiences',
    destination: 'nerja',
    topic: 'adventure',
    place: { name: 'Local Experiences', kind: 'provider', website: 'https://localexperiences.es/en/' },
    summary: 'Local Experiences: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.adventure.filoclimb',
    destination: 'nerja',
    topic: 'adventure',
    place: { name: 'Filoclimb', kind: 'provider', website: 'https://filoclimb.com/' },
    summary: 'Filoclimb: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.adventure.tirolina-de-comares',
    destination: 'nerja',
    topic: 'adventure',
    place: { name: 'Tirolina de Comares', kind: 'provider', website: 'https://www.turismointeriordemalaga.com/actividades/tirolina-de-comares/?lang=en' },
    summary: 'Tirolina de Comares: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.adventure.via-ferrata-zafarraya',
    destination: 'nerja',
    topic: 'adventure',
    place: { name: 'Vía Ferrata Zafarraya', kind: 'provider', website: 'https://viaferratajohnhogbin.com/' },
    summary: 'Vía Ferrata Zafarraya: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.adventure.life-adventure',
    destination: 'nerja',
    topic: 'adventure',
    place: { name: 'Life Adventure', kind: 'provider', website: 'https://lifeadventure.eu/' },
    summary: 'Life Adventure: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.adventure.cyclenerja',
    destination: 'nerja',
    topic: 'adventure',
    place: { name: 'Cyclenerja', kind: 'provider', website: 'https://cyclenerja.com/' },
    summary: 'Cyclenerja: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.adventure.jet-ski-tours-nerja',
    destination: 'nerja',
    topic: 'adventure',
    place: { name: 'Jet Ski Tours Nerja', kind: 'provider', address: 'Calle Antonio Ferrandis Chanquete 25, esc. B, 29780 Nerja', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Jet+Ski+Tours+Nerja' },
    summary: 'Guided jet ski tours along the Nerja coast; the operator named this provider from its Google listing (boat rental category, 4.3 from 17 reviews on 2026-09-06).',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'operator-review',
    checkedAt: '2026-09-06',
    reviewAfter: '2027-03-06',
    volatility: 'medium',
    claimBoundary: 'Identity, address and map link come from the Google listing the operator supplied; opening times, prices and availability need a live check.',
    notes: 'The listing showed opening from 10:00 on the day it was checked.'
  }
]);
