import { defineKnowledgeRecommendations } from '../../schema';

export const nerjaBreakfastRecommendations = defineKnowledgeRecommendations([
  {
    id: 'nerja.breakfast.panaderia-salvador',
    destination: 'nerja',
    topic: 'breakfast',
    place: { name: 'Panaderia Salvador', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Panaderia+Salvador+Nerja' },
    summary: 'This is the easiest pick when you want something simple, quick and good value. Perfect for taking fresh pastries or bread back home and having breakfast on your own terrace after a short morning walk.',
    access: [{ from: 'amara-playa', distanceMetres: 400 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.breakfast.good-stuff-cafe',
    destination: 'nerja',
    topic: 'breakfast',
    place: { name: 'Good Stuff Café', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Good+Stuff+Cafe+Nerja' },
    summary: 'A lovely option when you feel like a more modern breakfast with good coffee, fresh ingredients and a slightly more curated atmosphere. Especially nice if you want something healthier or more international before heading into town for the day.',
    access: [{ from: 'amara-playa', distanceMetres: 850 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.breakfast.kafune-specialty-coffee',
    destination: 'nerja',
    topic: 'breakfast',
    place: { name: 'Kafunè Specialty Coffee', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kafune+Specialty+Coffee+Calle+San+Miguel+36+Nerja' },
    summary: 'For anyone who takes their coffee seriously. Properly made espresso and filter, and a good stop if you want a real flat white before the beach rather than a hotel pot.',
    access: [{ from: 'amara-playa', distanceMetres: 800 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.breakfast.las-cuatro-esquinas',
    destination: 'nerja',
    topic: 'breakfast',
    place: { name: 'Las Cuatro Esquinas', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Las+Cuatro+Esquinas+Nerja' },
    summary: 'If you want to try a more classic local breakfast, this is the place for it. Lovely for churros and hot chocolate, and easy to combine with a slow walk through the old center afterwards.',
    access: [{ from: 'amara-playa', distanceMetres: 950 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.breakfast.hotel-riu-monica',
    destination: 'nerja',
    topic: 'breakfast',
    place: { name: 'Hotel Riu Monica', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hotel+Riu+Monica+Nerja' },
    summary: 'A very comfortable option when you want a bigger breakfast and do not feel like deciding too much. Especially practical if you want a generous start to the day very close to the seafront.',
    access: [{ from: 'amara-playa', distanceMetres: 150 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.breakfast.hotel-plaza-cavana',
    destination: 'nerja',
    topic: 'breakfast',
    place: { name: 'Hotel Plaza Cavana', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hotel+Plaza+Cavana+Nerja' },
    summary: 'A nice choice if you would like a buffet breakfast in a more central setting without it feeling too formal. Works well when you want to combine breakfast with a walk around Balcón de Europa afterwards.',
    access: [{ from: 'amara-playa', distanceMetres: 1100 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.breakfast.nybakat-bakery',
    destination: 'nerja',
    topic: 'breakfast',
    place: { name: 'Nybakat Bakery', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nybakat+Bakery+Nerja' },
    summary: 'This is more of a "go there because you feel like it" breakfast — less about speed, more about quality and the little outing around it. A very nice idea when you are heading toward Burriana anyway and want something a little more artisanal.',
    access: [{ from: 'amara-playa', distanceMetres: 2300 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  }
]);
