import { defineKnowledgeRecommendations } from '../../schema';

export const nerjaEssentialsRecommendations = defineKnowledgeRecommendations([
  {
    id: 'nerja.essentials.lidl',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Lidl Nerja', kind: 'shop', placeId: 'ChIJvymkvBglcg0R9Krp1OTyAao' },
    summary: 'Lidl Nerja: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.mercadona',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Mercadona Nerja', kind: 'shop', address: 'Calle San Miguel', placeId: 'ChIJjSZ_9hAlcg0ReZbcNgz4bh8' },
    summary: 'Mercadona Nerja: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.europcar-nerja',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Europcar Nerja', kind: 'provider', address: 'Edificio Toboso II', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Europcar+Nerja+Edificio+Toboso+II', website: 'https://www.europcar.com/en-us/places/car-rental-spain/nerja/nerja' },
    summary: 'Europcar Nerja: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.lessaggro-car-hire',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Lessaggro Car Hire Nerja', kind: 'provider', website: 'https://carhirenerja.com/' },
    summary: 'Lessaggro Car Hire Nerja: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.bahia-sexi-rent-a-car',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Bahia Sexi Rent a Car', kind: 'provider', website: 'https://bahiasexirentacar.com/rent-a-car-in-nerja/' },
    summary: 'Bahia Sexi Rent a Car: listed in the AMARA guide as a provider used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.centro-de-salud-nerja',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Centro de Salud Nerja', kind: 'service', address: 'Calle Carlos Millón, s/n, 29780 Nerja', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Centro+de+Salud+Nerja', phone: '+34951289662' },
    summary: 'Centro de Salud Nerja: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'split',
    basis: 'published-guide-carryover',
    factIds: [
      'nerja.health.centro-address-and-contact',
      'nerja.health.current-published-hours'
    ],
    checkedAt: '2026-08-28',
    reviewAfter: '2027-02-28',
    volatility: 'high',
    claimBoundary: 'Carried over from the published guide; the referenced facts bound the verified details, everything else is editorial selection without a dated check.'
  },
  {
    id: 'nerja.essentials.carrefour-express',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Carrefour Express', kind: 'shop', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Carrefour+Express+Nerja' },
    summary: 'Carrefour Express: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.mas-supermercado',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Mas Supermercado', kind: 'shop', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mas+Supermercado+Nerja' },
    summary: 'Mas Supermercado: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.aldi',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Aldi Nerja', kind: 'shop', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Aldi+Nerja' },
    summary: 'Aldi Nerja: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.lavanderia-nerja',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Lavandería Nerja', kind: 'service', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lavanderia+Nerja' },
    summary: 'Lavandería Nerja: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.open-wash-nerja',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Lavandería Autoservicio Open Wash Nerja', kind: 'service', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lavanderia+Autoservicio+Open+Wash+Nerja' },
    summary: 'Lavandería Autoservicio Open Wash Nerja: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.unicaja-atm',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Unicaja ATM Nerja', kind: 'service', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Unicaja+Nerja' },
    summary: 'Unicaja ATM Nerja: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.caixabank-atm',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'CaixaBank ATM Nerja', kind: 'service', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=CaixaBank+Nerja' },
    summary: 'CaixaBank ATM Nerja: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.oficina-de-turismo',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Oficina de Turismo Nerja', kind: 'service', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Oficina+de+Turismo+Nerja', phone: '+34952521531' },
    summary: 'Oficina de Turismo Nerja: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.radio-taxis-nerja',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Radio Taxis Nerja', kind: 'service', phone: '+34952520537' },
    summary: 'Radio Taxis Nerja: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'nerja.essentials.taxi-nerja-21',
    destination: 'nerja',
    topic: 'essentials',
    place: { name: 'Taxi Nerja 21', kind: 'service', phone: '+34610795909' },
    summary: 'Taxi Nerja 21: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  }
]);
