import { defineKnowledgeRecommendations } from '../../schema';

export const nerjaRestaurantRecommendations = defineKnowledgeRecommendations([
  {
    id: 'nerja.restaurants.el-pulguilla',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'El Pulguilla', kind: 'restaurant', address: 'Old town, near the Balcón de Europa', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bar+El+Pulguilla+Nerja' },
    summary: 'Classic Nerja seafood-tapas energy — casual, loud, and very Spanish. Great for fried fish and quick seafood rounds.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'split',
    basis: 'published-guide-carryover',
    factIds: [
      'nerja.restaurants.el-pulguilla.old-town-fish-format'
    ],
    checkedAt: '2026-08-28',
    reviewAfter: '2027-02-28',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide; the referenced facts bound the verified details, everything else is editorial selection without a dated check.'
  },
  {
    id: 'nerja.restaurants.dolores-el-chispa',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Dolores El Chispa', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dolores+El+Chispa+Nerja' },
    summary: 'Raw, authentic taberna vibe with generous seafood — a true local experience. Perfect when you want "no frills, just great fish".',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.la-puntilla',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'La Puntilla', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Puntilla+Nerja' },
    summary: 'Reliable choice for seafood and tapas — great value and a proper Andalusian rhythm. Try gambas al pil-pil and mixed fried fish.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'split',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.puerta-del-mar',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Puerta del Mar', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Restaurante+Puerta+del+Mar+Nerja' },
    summary: 'A more premium seafood pick with a prime location near Balcón de Europa. Great when you want a calmer sit-down meal with sea views.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.chiringuito-ayo',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Chiringuito AYO', kind: 'restaurant', address: 'Paseo Burriana 15', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Chiringuito+Ayo+Nerja' },
    summary: 'Iconic beach paella at lunchtime — rustic, fast, and a local institution. Best combined with Burriana Beach: swim first, lunch after. Paseo Burriana 15; open 09:00–19:00 with kitchen 12:00–18:00 (2026), so it is a lunch place, not a dinner option.',
    operating: { note: 'Open 09:00–19:00, kitchen 12:00–18:00: a lunch place, not a dinner option (operator page)', observedAt: '2026-08-28' },
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'split',
    basis: 'published-guide-carryover',
    factIds: [
      'nerja.restaurants.ayo.burriana-daytime-service-2026'
    ],
    checkedAt: '2026-08-28',
    reviewAfter: '2027-02-28',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide; the referenced facts bound the verified details, everything else is editorial selection without a dated check.'
  },
  {
    id: 'nerja.restaurants.merendero-la-barca',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Merendero La Barca', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Merendero+La+Barca+Nerja' },
    summary: 'Great for rice dishes beyond "classic paella" — especially lobster rice (arroz con bogavante). Strong option when you want a proper lunch on a beach day.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.playa-sol-lounge',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Playa & Sol Lounge', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Playa+y+Sol+Lounge+Nerja' },
    summary: 'A more modern take on the Burriana strip — good value paella and great fideuá. Nice pick when you want something relaxed but a bit more "current".',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.la-torrecilla',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'La Torrecilla', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Restaurante+La+Torrecilla+Nerja' },
    summary: 'Great choice if you want rice dishes with variety — including arroz negro. Also a strong option when you need a vegetarian-friendly rice dish.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.burriana-beach-lunch-zone',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Burriana Beach lunch zone', kind: 'venue', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Playa+Burriana+Nerja' },
    summary: 'Burriana is the easiest "full beach day + lunch" setup in Nerja. If you want a sure paella stop, AYO is the classic.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.chiringuito-mauri',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Chiringuito Mauri', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Chiringuito+Mauri+Nerja' },
    summary: 'A very strong pick for espetos (sardines on the fire) and classic beach food. Great when you want the "old-school coastal" experience.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.la-gustosa-beach',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'La Gustosa Beach', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Gustosa+Beach+Nerja' },
    summary: 'Beachfront option with a great setting — good when you want easy food with a view. Nice for a relaxed afternoon that can roll into evening.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.rincon-del-sol',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Rincón del Sol', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Rincon+del+Sol+Nerja' },
    summary: 'More "lounge / beach club" atmosphere — good for cocktails and a stylish sunset feel. Best when you want ambience as much as food.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.lamalaka',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Lamalaka', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lamalaka+Nerja' },
    summary: 'Big "new Nerja" concept: beach club, restaurant, and cocktails in a prime location. Go when you want a modern lifestyle vibe (especially around sunset).',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.oculto',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'OCULTO', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=OCULTO+Nerja' },
    summary: 'Speakeasy-style "night restaurant" — modern, energetic, and very experience-driven. Booking ahead is important in peak season.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.botanic',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Botanic', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Botanic+Nerja' },
    summary: 'Stylish, contemporary and calm — strong if you care about plating, seasonal food, and gin. Great for a date night that\'s not too formal.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.trattoria-italia',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Trattoria Italia', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Trattoria+Italia+Nerja' },
    summary: 'A newer crowd favorite for a classic Italian dinner with a very nice ambience. Great when you want a break from tapas and seafood.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.bar-redondo',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Bar Redondo', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bar+Redondo+Nerja' },
    summary: 'Tapas institution and a social hotspot — great for a fun, busy evening out. Go early for a calmer start; later it gets packed.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.el-refugio',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'El Refugio', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=El+Refugio+Calle+Pintada+27+Nerja' },
    summary: 'A cozy, rustic-feel place that\'s easy to love — great for classic tapas. Good choice when you want something simple and warm.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.la-rienda',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'La Rienda', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Rienda+Nerja' },
    summary: 'Easy, generous tapas with a calmer local crowd. Great for a relaxed "let\'s stay a bit longer" evening.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.dvinos',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'D\'Vinos', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=D%27Vinos+Nerja' },
    summary: 'A fun, modern tapas and wine option — great if you want something different. Good for a relaxed evening with sharing plates.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.esquina-paulina',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Esquina Paulina', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Esquina+Paulina+Nerja' },
    summary: 'Small, easygoing spot for cheese boards and a casual glass of wine. Nice for a light evening without a full sit-down meal.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.bar-turry',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Bar Turry', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bar+Turry+Nerja' },
    summary: 'Reliable local favorite slightly outside the tourist core. Try the famous pollo al curry.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.oliva',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Oliva', kind: 'restaurant', address: 'Plaza de España', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Restaurante+Oliva+Nerja' },
    summary: 'Top fine-dining pick in Nerja — ideal for a calm, high-quality dinner. Great if you enjoy tasting menus and seasonal cooking. Terrace facing the square; dinner orders daily 19:00–22:00 (as published in 2026, weather-dependent).',
    operating: { note: 'Dinner orders daily 19:00–22:00 on the operator page; terrace faces the square and is weather-dependent', observedAt: '2026-08-28' },
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'split',
    basis: 'published-guide-carryover',
    factIds: [
      'nerja.restaurants.oliva.position-terrace-and-service-2026'
    ],
    checkedAt: '2026-08-28',
    reviewAfter: '2027-02-28',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide; the referenced facts bound the verified details, everything else is editorial selection without a dated check.'
  },
  {
    id: 'nerja.restaurants.restaurant-34',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Restaurant 34', kind: 'restaurant', address: 'Hotel Carabeo', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Restaurante+34+Nerja' },
    summary: 'A strong "celebration / romantic evening" pick with a refined feel. Reserve in summer — and ask for a calmer table if you prefer it quiet. In Hotel Carabeo: inside, by the pool or on the summer terrace above the sea; dinner 19:00–22:30, closed Mondays (as published in 2026).',
    operating: { note: 'Dinner 19:00–22:30, closed Mondays; dining inside, by the pool or on the summer terrace above the sea (operator page)', observedAt: '2026-08-28' },
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'split',
    basis: 'published-guide-carryover',
    factIds: [
      'nerja.restaurants.restaurant34.sea-terrace-and-service-2026'
    ],
    checkedAt: '2026-08-28',
    reviewAfter: '2027-02-28',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide; the referenced facts bound the verified details, everything else is editorial selection without a dated check.'
  },
  {
    id: 'nerja.restaurants.sollun',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Sollun', kind: 'restaurant', address: 'Calle Pintada 9', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Restaurante+Sollun+Nerja' },
    summary: 'Excellent modern Andalusian cooking in a warm, unpretentious setting. Great when you want a "serious meal" that still feels relaxed. Calle Pintada 9, cocina de autor by Juan Quintanilla.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    factIds: [
      'nerja.restaurants.sollun.position-and-concept'
    ],
    checkedAt: '2026-08-28',
    reviewAfter: '2027-02-28',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide; the referenced facts bound the verified details, everything else is editorial selection without a dated check.'
  },
  {
    id: 'nerja.restaurants.patanegra-57',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'Patanegra 57', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Patanegra+57+Nerja' },
    summary: 'High-end option with a beautiful atmosphere — great for a special night. Strong if you care about quality ingredients and a curated wine list.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'nerja.restaurants.la-bottega',
    destination: 'nerja',
    topic: 'restaurants',
    place: { name: 'La Bottega', kind: 'restaurant', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Bottega+Nerja' },
    summary: 'A comfortable, dependable choice when you want a smooth evening without overthinking it. Earlier is calmer; later feels more lively — choose based on your mood.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  }
]);
