import {
  resolveLocale,
  type LocalizedText,
  type LocalizedTextList,
} from "../types/content";
import type { AmaraAuthoringSeo, AmaraLanguage } from "../types/seo";

const text = (
  en: string,
  de: string,
  es: string,
  nl: string,
  sv: string,
): LocalizedText => ({ en, de, es, nl, sv });

export const amaraExperienceSeo: AmaraAuthoringSeo = {
  version: "2026-09-01-amara-experience-v1.9",
  pageType: "C",
  entityKey: "amara-brand",
  languages: {
    en: {
      title: "AMARA Experience | Exclusive direct-booking benefit",
      description:
        "Personal insider tips for romantic time, hidden treasures and quieter places in Frigiliana, Nerja and Tarifa — exclusively for AMARA direct bookers.",
      robots: "index, follow",
      canonical: "auto",
    },
    de: {
      title: "AMARA Experience | Exklusiver Direktbucher-Vorteil",
      description:
        "Persönliche Insider-Tipps für romantische Zeit, versteckte Schätze und ruhige Orte in Frigiliana, Nerja und Tarifa – exklusiv für AMARA-Direktbucher.",
      robots: "index, follow",
      canonical: "auto",
    },
    es: {
      title: "AMARA Experience | Ventaja exclusiva de reserva directa",
      description:
        "Recomendaciones personales para momentos románticos, rincones escondidos y lugares tranquilos en Frigiliana, Nerja y Tarifa, solo con reserva directa.",
      robots: "index, follow",
      canonical: "auto",
    },
    nl: {
      title: "AMARA Experience | Exclusief voordeel van direct boeken",
      description:
        "Persoonlijke insidertips voor romantische tijd, verborgen parels en rustige plekken in Frigiliana, Nerja en Tarifa, exclusief bij direct boeken.",
      robots: "index, follow",
      canonical: "auto",
    },
    sv: {
      title: "AMARA Experience | Exklusiv fördel vid direktbokning",
      description:
        "Personliga insidertips för romantisk tid, dolda pärlor och lugnare platser i Frigiliana, Nerja och Tarifa – exklusivt vid direktbokning.",
      robots: "index, follow",
      canonical: "auto",
    },
  },
};

const content = {
  eyebrow: text(
    "Exclusive to direct bookers",
    "Exklusiv für Direktbucher",
    "Exclusivo al reservar directamente",
    "Exclusief bij direct boeken",
    "Exklusivt vid direktbokning",
  ),
  title: text(
    "AMARA Experience",
    "AMARA Experience",
    "AMARA Experience",
    "AMARA Experience",
    "AMARA Experience",
  ),
  subtitle: text(
    "More local knowledge. More romantic time together in Frigiliana, Nerja and Tarifa.",
    "Mehr lokales Wissen. Mehr romantische Zeit zu zweit in Frigiliana, Nerja und Tarifa.",
    "Más conocimiento local. Más tiempo romántico juntos en Frigiliana, Nerja y Tarifa.",
    "Meer lokale kennis. Meer romantische tijd samen in Frigiliana, Nerja en Tarifa.",
    "Mer lokalkännedom. Mer romantisk tid tillsammans i Frigiliana, Nerja och Tarifa.",
  ),
  directAnswer: text(
    "AMARA Experience is our exclusive direct-booking benefit for couples staying with us in Frigiliana, Nerja or Tarifa: a private guide with personal recommendations that go beyond the familiar sights. Once your direct booking is confirmed, we share **local favourites**, **hidden treasures** and **lesser-known places** — from a romantic restaurant or quiet beach to a walk, shared activity or town worth a day trip. This is not a generic list of supposed secret spots. We check what fits each AMARA destination, explain why a place or time of day may be worthwhile and help you spend more time **off the beaten track**, away from the busiest routes. You spend less time searching and more time experiencing your holiday together.",
    "AMARA Experience ist unser exklusiver Direktbucher-Vorteil für Paare mit einem Aufenthalt bei uns in Frigiliana, Nerja oder Tarifa: ein privater Guide mit persönlichen Empfehlungen, die über die bekannten Sehenswürdigkeiten hinausgehen. Nach bestätigter Direktbuchung teilen wir **lokale Favoriten**, **versteckte Schätze** und **weniger bekannte Orte** – vom romantischen Restaurant und ruhigen Strand bis zur Wanderung, Aktivität oder Stadt für einen gemeinsamen Ausflug. Dabei geht es nicht um eine beliebige Liste vermeintlicher Geheimtipps. Wir prüfen, was zum jeweiligen AMARA-Reiseziel passt, erklären, warum sich ein Ort oder Zeitpunkt lohnt, und helfen euch, öfter **abseits der Touristenpfade** unterwegs zu sein. So verbringt ihr weniger Zeit mit Suchen und mehr mit Erleben.",
    "AMARA Experience es nuestra ventaja exclusiva para parejas que os alojáis con nosotros en Frigiliana, Nerja o Tarifa y reserváis directamente: una guía privada con recomendaciones personales que van más allá de los lugares conocidos. Tras confirmar la reserva directa, compartimos **favoritos locales**, **rincones escondidos** y **sitios menos conocidos**, desde un restaurante romántico o una playa tranquila hasta una ruta, una actividad para dos o una localidad que merece una excursión. No es una lista genérica de supuestos lugares secretos. Comprobamos qué encaja con cada destino AMARA, explicamos por qué merece la pena un lugar o un momento del día y os ayudamos a moveros **fuera de las rutas turísticas más transitadas**. Así buscáis menos y disfrutáis más juntos.",
    "AMARA Experience is ons exclusieve voordeel voor stellen die hun verblijf bij ons in Frigiliana, Nerja of Tarifa rechtstreeks boeken: een privégids met persoonlijke aanbevelingen die verder gaan dan de bekende bezienswaardigheden. Na bevestiging van jullie directe boeking delen we **lokale favorieten**, **verborgen parels** en **minder bekende plekken** — van een romantisch restaurant of rustig strand tot een wandeling, activiteit samen of plaats die een dagtrip waard is. Dit is geen algemene lijst met vermeende geheime plekken. We controleren wat bij elke AMARA-bestemming past, leggen uit waarom een plek of tijdstip de moeite waard kan zijn en helpen jullie vaker **buiten de gebaande toeristische paden** te komen. Zo zoeken jullie minder en beleven jullie samen meer van de vakantie.",
    "AMARA Experience är vår exklusiva fördel för par som bokar direkt och bor hos oss i Frigiliana, Nerja eller Tarifa: en privat guide med personliga rekommendationer bortom de välkända sevärdheterna. När direktbokningen är bekräftad delar vi **lokala favoriter**, **dolda pärlor** och **mindre kända platser** — från en romantisk restaurang eller lugn strand till en vandring, gemensam aktivitet eller ort värd en dagsutflykt. Det här är ingen allmän lista över påstått hemliga platser. Vi kontrollerar vad som passar varje AMARA-destination, förklarar varför en plats eller tid på dagen kan vara värd att välja och hjälper er oftare **bortom de mest välbesökta turiststråken**. Då lägger ni mindre tid på att leta och mer på att uppleva semestern tillsammans.",
  ),
  heroAccent: text(
    "Less searching. More experiencing together.",
    "Weniger suchen. Mehr gemeinsam erleben.",
    "Menos tiempo buscando. Más tiempo disfrutando juntos.",
    "Minder zoeken. Meer samen beleven.",
    "Mindre letande. Mer att uppleva tillsammans.",
  ),
  promiseEyebrow: text(
    "What direct bookers receive",
    "Was Direktbucher erhalten",
    "Lo que recibís al reservar directamente",
    "Wat jullie bij direct boeken ontvangen",
    "Det här får ni när ni bokar direkt",
  ),
  promiseTitle: text(
    "Authentic. Exclusive. Beyond the crowds.",
    "Authentisch. Exklusiv. Abseits der Massen.",
    "Auténtico. Exclusivo. Lejos de las multitudes.",
    "Authentiek. Exclusief. Buiten de drukte.",
    "Genuint. Exklusivt. Bortom trängseln.",
  ),
  promiseIntro: text(
    "The value is not a longer list. It is a considered selection with the practical context, timing and honest alternatives that help a day work once you are there.",
    "Der Mehrwert ist keine längere Liste. Es ist eine durchdachte Auswahl mit praktischen Details, dem richtigen Zeitpunkt und ehrlichen Alternativen, damit ein Tag auch vor Ort funktioniert.",
    "El valor no está en una lista más larga, sino en una selección cuidada con información práctica, el momento adecuado y alternativas sinceras para que el día funcione sobre el terreno.",
    "De meerwaarde is geen langere lijst. Het is een doordachte selectie met praktische informatie, het juiste moment en eerlijke alternatieven waarmee een dag ter plaatse echt werkt.",
    "Värdet ligger inte i en längre lista. Det är ett genomtänkt urval med praktiska detaljer, rätt tidpunkt och ärliga alternativ som får dagen att fungera på plats.",
  ),
  promises: [
    {
      id: "authenticity",
      principle: text("Authenticity", "Authentizität", "Autenticidad", "Authenticiteit", "Genuinitet"),
      title: text(
        "Not only where — how the day works",
        "Nicht nur wohin – sondern wie der Tag funktioniert",
        "No solo adónde: también cómo funciona el día",
        "Niet alleen waarheen — ook hoe de dag werkt",
        "Inte bara vart — utan hur dagen fungerar",
      ),
      copy: text(
        "When it matters, a recommendation includes the detail that changes the day: a useful time to set off, how access or parking works, whether booking ahead makes sense and what should be checked again shortly before you go.",
        "Wenn es darauf ankommt, enthält eine Empfehlung die Details, die den Tag verändern: eine sinnvolle Startzeit, Hinweise zu Zufahrt oder Parken, ob eine Reservierung ratsam ist und was ihr kurz vorher noch einmal prüfen solltet.",
        "Cuando importa, una recomendación incluye los detalles que cambian el día: una buena hora para salir, cómo funcionan el acceso o el aparcamiento, si conviene reservar y qué deberíais comprobar poco antes.",
        "Waar het ertoe doet, bevat een aanbeveling de details die de dag veranderen: een slim vertrekmoment, hoe toegang of parkeren werkt, of reserveren verstandig is en wat jullie kort van tevoren nog moeten controleren.",
        "När det spelar roll innehåller ett tips detaljerna som förändrar dagen: en bra tid att ge sig av, hur tillträde eller parkering fungerar, om det är klokt att boka och vad ni bör kontrollera strax innan.",
      ),
    },
    {
      id: "exclusivity",
      principle: text("Exclusivity", "Exklusivität", "Exclusividad", "Exclusiviteit", "Exklusivitet"),
      title: text(
        "A short selection, shared privately",
        "Eine kleine Auswahl, privat geteilt",
        "Una selección breve, compartida en privado",
        "Een kleine selectie, privé gedeeld",
        "Ett litet urval, delat privat",
      ),
      copy: text(
        "We do not show you everything we found. Your confirmed direct booking opens a deliberately small selection for AMARA guests: places we can explain, **lesser-known options** we consider worthwhile and the practical context needed to enjoy them.",
        "Wir zeigen euch nicht alles, was wir gefunden haben. Eure bestätigte Direktbuchung öffnet eine bewusst kleine Auswahl für AMARA-Gäste: Orte, die wir begründen können, lohnende **weniger bekannte Alternativen** und den praktischen Kontext dazu.",
        "No os mostramos todo lo que hemos encontrado. La reserva directa confirmada abre una selección deliberadamente breve para huéspedes de AMARA: lugares que podemos explicar, **alternativas menos conocidas** que merecen la pena y su contexto práctico.",
        "We laten niet alles zien wat we hebben gevonden. Jullie bevestigde directe boeking opent een bewust kleine selectie voor AMARA-gasten: plekken die we kunnen toelichten, waardevolle **minder bekende alternatieven** en de praktische context erbij.",
        "Vi visar inte allt vi har hittat. Er bekräftade direktbokning öppnar ett medvetet litet urval för AMARA-gäster: platser vi kan motivera, värdefulla **mindre kända alternativ** och det praktiska sammanhanget runt dem.",
      ),
    },
    {
      id: "calm",
      principle: text("More calm", "Mehr Ruhe", "Más calma", "Meer rust", "Mer lugn"),
      title: text(
        "Popular when worthwhile. Quieter when better.",
        "Bekannt, wenn es sich lohnt. Ruhiger, wenn es besser passt.",
        "Conocido cuando merece la pena. Tranquilo cuando encaja mejor.",
        "Bekend als het de moeite waard is. Rustiger als dat beter past.",
        "Välkänt när det är värt det. Lugnare när det passar bättre.",
      ),
      copy: text(
        "A well-known place can be exactly right — but not automatically. We tell you when timing changes the experience and point to a **quieter alternative away from the crowds** when it gives you more of the day you actually want.",
        "Ein bekannter Ort kann genau richtig sein – aber nicht automatisch. Wir sagen euch, wann der Zeitpunkt das Erlebnis verändert, und zeigen eine **ruhigere Alternative abseits der Massen**, wenn sie besser zu eurem gewünschten Tag passt.",
        "Un lugar conocido puede ser justo lo que buscáis, pero no siempre. Os contamos cuándo el momento cambia la experiencia y señalamos una **alternativa tranquila lejos de las multitudes** cuando encaja mejor con el día que queréis vivir.",
        "Een bekende plek kan precies goed zijn, maar niet vanzelfsprekend. We vertellen wanneer het tijdstip de ervaring verandert en wijzen op een **rustiger alternatief buiten de drukte** als dat beter past bij de dag die jullie willen.",
        "En välkänd plats kan vara helt rätt, men inte automatiskt. Vi berättar när tidpunkten förändrar upplevelsen och visar ett **lugnare alternativ bortom trängseln** när det passar dagen ni faktiskt vill ha bättre.",
      ),
    },
  ],
  imageAlts: {
    village: text(
      "A white village street in Frigiliana beneath a clear blue sky",
      "Eine weiße Gasse in Frigiliana unter klarem blauem Himmel",
      "Una calle blanca de Frigiliana bajo un cielo azul despejado",
      "Een witte dorpsstraat in Frigiliana onder een heldere blauwe lucht",
      "En vit bygata i Frigiliana under en klarblå himmel",
    ),
    evening: text(
      "Bougainvillea and white houses in Frigiliana in the evening light",
      "Bougainvillea und weiße Häuser in Frigiliana im Abendlicht",
      "Bugambilia y casas blancas de Frigiliana a la luz de la tarde",
      "Bougainville en witte huizen in Frigiliana in het avondlicht",
      "Bougainvillea och vita hus i Frigiliana i kvällsljus",
    ),
    coast: text(
      "The coastline and beaches of Nerja seen from above",
      "Die Küste und Strände von Nerja aus der Luft",
      "La costa y las playas de Nerja vistas desde el aire",
      "De kust en stranden van Nerja vanuit de lucht",
      "Nerjas kust och stränder sedda från ovan",
    ),
  },
  valueEyebrow: text(
    "Romantic ideas, personally selected",
    "Romantische Ideen, persönlich ausgewählt",
    "Ideas románticas, seleccionadas personalmente",
    "Romantische ideeën, persoonlijk geselecteerd",
    "Romantiska idéer, personligt utvalda",
  ),
  valueTitle: text(
    "Romantic time that feels like the two of you.",
    "Romantische Zeit, die sich nach euch anfühlt.",
    "Tiempo romántico que se sienta realmente vuestro.",
    "Romantische tijd die echt als die van jullie voelt.",
    "Romantisk tid som känns som just er.",
  ),
  valueIntro: text(
    "A long dinner, a beautiful walk, a quiet beach or something new to do together: we show you why an idea may suit the moment and add it only after checking it for that destination.",
    "Ein langes Abendessen, ein schöner Weg, ein ruhiger Strand oder etwas Neues, das ihr gemeinsam erlebt: Wir zeigen euch, warum eine Idee zum Moment passen könnte, und nehmen sie erst auf, wenn sie für das Reiseziel geprüft ist.",
    "Una cena larga, un paseo bonito, una playa tranquila o algo nuevo que hacer juntos: os contamos por qué una idea puede encajar con el momento y solo la añadimos cuando está comprobada para ese destino.",
    "Lang tafelen, een mooie wandeling, een rustig strand of samen iets nieuws doen: we vertellen waarom een idee bij het moment kan passen en voegen het pas toe als het voor die bestemming is gecontroleerd.",
    "En lång middag, en vacker promenad, en lugn strand eller något nytt att göra tillsammans: vi berättar varför en idé kan passa stunden och lägger bara till den när den har kontrollerats för destinationen.",
  ),
  benefits: [
    {
      id: "eat",
      number: "01",
      title: text(
        "An evening for two",
        "Ein Abend zu zweit",
        "Una noche para dos",
        "Een avond met z'n tweeën",
        "En kväll för två",
      ),
      copy: text(
        "Restaurants and local places for a long dinner, a special evening or an unhurried drink together.",
        "Restaurants und lokale Adressen für ein langes Abendessen, einen besonderen Abend oder einen entspannten Drink zu zweit.",
        "Restaurantes y lugares locales para una cena larga, una noche especial o una copa sin prisas juntos.",
        "Restaurants en lokale adressen voor lang tafelen, een bijzondere avond of samen rustig iets drinken.",
        "Restauranger och lokala ställen för en lång middag, en särskild kväll eller något gott att dricka tillsammans i lugn och ro.",
      ),
    },
    {
      id: "sea",
      number: "02",
      title: text(
        "A beach for your rhythm",
        "Ein Strand für euren Rhythmus",
        "Una playa a vuestro ritmo",
        "Een strand op jullie tempo",
        "En strand i er takt",
      ),
      copy: text(
        "Beaches for a quiet morning, a swim together or a coast day with lunch and nowhere else you need to be.",
        "Strände für einen ruhigen Vormittag, ein gemeinsames Bad oder einen Küstentag mit Mittagessen und ohne weiteren Termin.",
        "Playas para una mañana tranquila, un baño juntos o un día de costa con comida y sin tener que llegar a ningún otro sitio.",
        "Stranden voor een rustige ochtend, samen zwemmen of een dag aan de kust met lunch en verder helemaal niets op de planning.",
        "Stränder för en lugn förmiddag, ett bad tillsammans eller en dag vid kusten med lunch och ingen annan tid att passa.",
      ),
    },
    {
      id: "walk",
      number: "03",
      title: text(
        "Walks with a view",
        "Wege mit Aussicht",
        "Paseos con vistas",
        "Wandelingen met uitzicht",
        "Promenader med utsikt",
      ),
      copy: text(
        "Village lanes, nature routes and viewpoints for talking as you go and stopping when the view deserves more time.",
        "Gassen, Naturwege und Aussichtspunkte, auf denen ihr unterwegs miteinander redet und dort bleibt, wo der Blick mehr Zeit verdient.",
        "Calles de pueblo, rutas por la naturaleza y miradores para conversar por el camino y deteneros cuando las vistas merezcan más tiempo.",
        "Dorpsstraatjes, natuurroutes en uitzichtpunten om onderweg te praten en te blijven waar het uitzicht wat meer tijd verdient.",
        "Bygator, naturleder och utsiktsplatser där ni kan prata längs vägen och stanna när utsikten förtjänar mer tid.",
      ),
    },
    {
      id: "together",
      number: "04",
      title: text(
        "Do something together",
        "Gemeinsam etwas erleben",
        "Hacer algo juntos",
        "Samen iets beleven",
        "Uppleva något tillsammans",
      ),
      copy: text(
        "Shared experiences that give the day its own story, chosen for the destination and with the practical details you need.",
        "Gemeinsame Erlebnisse, die dem Tag eine eigene Geschichte geben – passend zum Reiseziel und mit den praktischen Details, die ihr dafür braucht.",
        "Experiencias compartidas que den al día su propia historia, elegidas para el destino y con los detalles prácticos que necesitáis.",
        "Gedeelde ervaringen die de dag een eigen verhaal geven, gekozen voor de bestemming en met de praktische informatie die jullie nodig hebben.",
        "Gemensamma upplevelser som ger dagen sin egen berättelse, utvalda för destinationen och med den praktiska information ni behöver.",
      ),
    },
    {
      id: "day-trip",
      number: "05",
      title: text(
        "A day trip worth taking",
        "Ein Ausflug, der sich lohnt",
        "Una excursión que merece la pena",
        "Een uitstapje dat de moeite waard is",
        "En utflykt värd tiden",
      ),
      copy: text(
        "Nearby villages, towns and day trips that reward the journey when you want to discover somewhere new as a couple.",
        "Nahe Dörfer, Städte und Tagesausflüge, die den Weg lohnen, wenn ihr als Paar gemeinsam etwas Neues entdecken möchtet.",
        "Pueblos, ciudades y excursiones cercanas que compensan el trayecto cuando os apetece descubrir juntos un lugar nuevo.",
        "Dorpen, steden en dagtrips in de buurt die de reis waard zijn als jullie samen een nieuwe plek willen ontdekken.",
        "Närliggande byar, städer och dagsutflykter som är värda resan när ni vill upptäcka en ny plats tillsammans.",
      ),
    },
  ],
  hostEyebrow: text(
    "The host behind the recommendations",
    "Der Gastgeber hinter den Empfehlungen",
    "El anfitrión detrás de las recomendaciones",
    "De host achter de aanbevelingen",
    "Värden bakom rekommendationerna",
  ),
  hostTitle: text(
    "A recommendation begins with a real stay, not a ranking.",
    "Eine Empfehlung beginnt mit einem echten Aufenthalt – nicht mit einem Ranking.",
    "Una recomendación nace de una estancia real, no de un ranking.",
    "Een aanbeveling begint bij een echt verblijf, niet bij een ranglijst.",
    "En rekommendation börjar med en verklig vistelse, inte med en topplista.",
  ),
  hostParagraphs: {
    en: [
      "Robert has hosted AMARA guests since May 2021 and regularly returns to the stays in Frigiliana, Nerja and Tarifa. He does not live in Andalusia permanently, and we say so openly. Our personal recommendations grow from the time we spend in the stays and destinations; opening hours, access rules and other changing details are checked separately.",
      "That is why a beach tip also explains what it means for your day. From AMARA Playa, Torrecilla is about 200 metres away, so it works for a quick swim or a return near sunset. In Tarifa, we use the Mercadona opposite the apartment for everyday shopping and choose Pastelito or Bernal for bread — especially Bernal's Pan Macho. Details like these turn a list into local guidance.",
      "The private AMARA Experience follows the same principle for romantic restaurants, quieter beaches, walks, shared activities and day trips: we tell you what we know, why it may fit and what you should check before setting out.",
    ],
    de: [
      "Robert empfängt seit Mai 2021 Gäste bei AMARA und ist regelmäßig in den Unterkünften in Frigiliana, Nerja und Tarifa. Er lebt nicht dauerhaft in Andalusien – und genau diese Unterscheidung nennen wir offen. Unsere persönlichen Empfehlungen entstehen aus der Zeit, die wir selbst in den Unterkünften und Orten verbringen. Öffnungszeiten, Zufahrten und andere veränderliche Angaben prüfen wir davon getrennt.",
      "Darum erklärt ein Strandtipp auch, was er für euren Tag bedeutet: Von AMARA Playa liegt Torrecilla rund 200 Meter entfernt – gut für ein schnelles Bad oder einen zweiten Besuch gegen Sonnenuntergang. In Tarifa nutzen wir den Mercadona direkt gegenüber dem Apartment; Brot holen wir bei Pastelito oder Bernal, besonders gern Bernals Pan Macho. Solche Details machen aus einer Liste lokale Orientierung.",
      "Im privaten AMARA Experience Guide gilt dasselbe für romantische Restaurants, ruhigere Strände, Wege, gemeinsame Aktivitäten und Ausflüge: Wir sagen euch, was wir wissen, warum es passen könnte und was ihr vor dem Aufbruch noch prüfen solltet.",
    ],
    es: [
      "Robert recibe a huéspedes de AMARA desde mayo de 2021 y vuelve con regularidad a los alojamientos de Frigiliana, Nerja y Tarifa. No vive permanentemente en Andalucía, y lo contamos con claridad. Nuestras recomendaciones personales nacen del tiempo que pasamos en los alojamientos y destinos; los horarios, accesos y demás datos que cambian se comprueban por separado.",
      "Por eso una recomendación de playa explica también qué aporta al día. Torrecilla está a unos 200 metros de AMARA Playa, así que permite un baño rápido o volver cerca del atardecer. En Tarifa usamos el Mercadona frente al apartamento para la compra diaria y elegimos Pastelito o Bernal para el pan, especialmente el Pan Macho de Bernal. Esos detalles convierten una lista en orientación local.",
      "La AMARA Experience privada aplica el mismo criterio a restaurantes románticos, playas tranquilas, paseos, actividades para dos y excursiones: os contamos qué sabemos, por qué puede encajar y qué conviene comprobar antes de salir.",
    ],
    nl: [
      "Robert ontvangt sinds mei 2021 gasten bij AMARA en verblijft regelmatig in de accommodaties in Frigiliana, Nerja en Tarifa. Hij woont niet permanent in Andalusië, en daar zijn we open over. Onze persoonlijke aanbevelingen komen voort uit de tijd die we zelf in de verblijven en bestemmingen doorbrengen; openingstijden, toegangsregels en andere veranderlijke details controleren we apart.",
      "Daarom vertelt een strandtip ook wat die voor jullie dag betekent. Torrecilla ligt op ongeveer 200 meter van AMARA Playa, dus een snelle duik of terugkeer rond zonsondergang is eenvoudig. In Tarifa gebruiken we de Mercadona tegenover het appartement voor dagelijkse boodschappen en kiezen we Pastelito of Bernal voor brood, vooral Bernals Pan Macho. Zulke details maken van een lijst lokale begeleiding.",
      "De besloten AMARA Experience werkt volgens hetzelfde principe voor romantische restaurants, rustige stranden, wandelingen, activiteiten samen en uitstapjes: we vertellen wat we weten, waarom het kan passen en wat jullie voor vertrek nog moeten controleren.",
    ],
    sv: [
      "Robert har varit värd för AMARA-gäster sedan maj 2021 och återvänder regelbundet till boendena i Frigiliana, Nerja och Tarifa. Han bor inte permanent i Andalusien, och det är vi öppna med. Våra personliga rekommendationer växer fram ur tiden vi själva tillbringar i boendena och på destinationerna; öppettider, tillträdesregler och andra uppgifter som ändras kontrolleras separat.",
      "Därför förklarar ett strandtips också vad platsen betyder för dagen. Torrecilla ligger omkring 200 meter från AMARA Playa, så ett snabbt dopp eller ett återbesök nära solnedgången är enkelt. I Tarifa använder vi Mercadona mittemot lägenheten för vardagsinköp och väljer Pastelito eller Bernal för bröd, särskilt Bernals Pan Macho. Sådana detaljer gör en lista till lokal vägledning.",
      "Den privata AMARA Experience följer samma princip för romantiska restauranger, lugnare stränder, promenader, gemensamma aktiviteter och utflykter: vi berättar vad vi vet, varför det kan passa och vad ni bör kontrollera innan ni ger er av.",
    ],
  } satisfies LocalizedTextList,
  hostAuthorName: "Robert Sebastian Böhmer",
  hostUpdated: text(
    "Editorially reviewed in September 2026",
    "Redaktionell geprüft im September 2026",
    "Revisado editorialmente en septiembre de 2026",
    "Redactioneel gecontroleerd in september 2026",
    "Redaktionellt granskat i september 2026",
  ),
  hostNote: text(
    "First-hand experience is identified as such; changing practical details are verified separately.",
    "Eigene Erfahrung kennzeichnen wir als solche; veränderliche praktische Angaben prüfen wir separat.",
    "Identificamos la experiencia propia como tal y comprobamos por separado los datos prácticos que pueden cambiar.",
    "Eigen ervaring benoemen we als zodanig; veranderlijke praktische informatie controleren we apart.",
    "Egna erfarenheter anges som sådana; praktiska uppgifter som kan ändras kontrolleras separat.",
  ),
  accessEyebrow: text(
    "Already booked directly?",
    "Schon direkt gebucht?",
    "¿Ya habéis reservado directamente?",
    "Al rechtstreeks geboekt?",
    "Har ni redan bokat direkt?",
  ),
  accessTitle: text(
    "Your private guide is ready here",
    "Euer privater Guide beginnt hier",
    "Vuestra guía privada empieza aquí",
    "Jullie privégids begint hier",
    "Er privata guide börjar här",
  ),
  accessIntro: text(
    "Use the first name and travel dates from your confirmation. We will check the booking securely and open the guide for your stay.",
    "Verwendet den Vornamen und die Reisedaten aus eurer Bestätigung. Wir gleichen die Buchung sicher ab und öffnen euren Guide für den Aufenthalt.",
    "Usad el nombre y las fechas de la confirmación. Comprobaremos la reserva de forma segura y abriremos la guía para vuestra estancia.",
    "Gebruik de voornaam en reisdata uit jullie bevestiging. We controleren de boeking veilig en openen de gids voor jullie verblijf.",
    "Använd förnamnet och resedatumen i bekräftelsen. Vi kontrollerar bokningen säkert och öppnar guiden för er vistelse.",
  ),
  formTitle: text(
    "Open your AMARA Experience",
    "Eure AMARA Experience öffnen",
    "Abrid vuestra AMARA Experience",
    "Open jullie AMARA Experience",
    "Öppna er AMARA Experience",
  ),
  formIntro: text(
    "Enter the details exactly as they appear in the booking confirmation.",
    "Gebt die Angaben genau wie in eurer Buchungsbestätigung ein.",
    "Introducid los datos tal como aparecen en la confirmación.",
    "Vul de gegevens precies in zoals ze in de boekingsbevestiging staan.",
    "Ange uppgifterna precis som de står i bokningsbekräftelsen.",
  ),
  firstNameLabel: text(
    "First name of booking holder",
    "Vorname der buchenden Person",
    "Nombre de la persona titular",
    "Voornaam van de hoofdboeker",
    "Bokningsinnehavarens förnamn",
  ),
  arrivalLabel: text(
    "Arrival date",
    "Anreisedatum",
    "Fecha de llegada",
    "Aankomstdatum",
    "Ankomstdatum",
  ),
  departureLabel: text(
    "Departure date",
    "Abreisedatum",
    "Fecha de salida",
    "Vertrekdatum",
    "Avresedatum",
  ),
  submitLabel: text(
    "Open AMARA Experience",
    "AMARA Experience öffnen",
    "Abrir AMARA Experience",
    "AMARA Experience openen",
    "Öppna AMARA Experience",
  ),
  pendingLabel: text(
    "Checking booking…",
    "Buchung wird geprüft…",
    "Comprobando la reserva…",
    "Boeking controleren…",
    "Kontrollerar bokningen…",
  ),
  deniedMessage: text(
    "We could not open the guide with these details. Check the booking confirmation or contact us if you need help.",
    "Mit diesen Angaben konnten wir den Guide nicht öffnen. Prüft bitte die Buchungsbestätigung oder meldet euch bei uns.",
    "No hemos podido abrir la guía con estos datos. Revisad la confirmación o contactadnos si necesitáis ayuda.",
    "Met deze gegevens konden we de gids niet openen. Controleer de bevestiging of neem contact met ons op.",
    "Vi kunde inte öppna guiden med de här uppgifterna. Kontrollera bekräftelsen eller kontakta oss om ni behöver hjälp.",
  ),
  unavailableMessage: text(
    "The private guide is not available right now. Please try again later.",
    "Der private Guide ist gerade nicht verfügbar. Bitte versucht es später noch einmal.",
    "La guía privada no está disponible ahora. Intentadlo de nuevo más tarde.",
    "De privégids is nu niet beschikbaar. Probeer het later opnieuw.",
    "Den privata guiden är inte tillgänglig just nu. Försök igen senare.",
  ),
  sessionEndedMessage: text(
    "Your guide session has ended. Enter the booking details again if the stay is still active.",
    "Eure Guide-Sitzung ist beendet. Gebt die Buchungsdaten erneut ein, falls der Aufenthalt noch aktiv ist.",
    "La sesión de la guía ha terminado. Volved a introducir los datos si la estancia sigue activa.",
    "Jullie gidssessie is beëindigd. Vul de boekingsgegevens opnieuw in als het verblijf nog actief is.",
    "Guidesessionen har avslutats. Ange bokningsuppgifterna igen om vistelsen fortfarande är aktiv.",
  ),
  privacyNote: text(
    "We use these details only to verify access against the confirmed booking and to create a necessary encrypted session cookie.",
    "Wir nutzen diese Angaben nur für den Abgleich mit der bestätigten Buchung und ein notwendiges verschlüsseltes Sitzungscookie.",
    "Usamos estos datos únicamente para verificar la reserva confirmada y crear una cookie de sesión cifrada necesaria.",
    "We gebruiken deze gegevens alleen om de bevestigde boeking te controleren en een noodzakelijke versleutelde sessiecookie te maken.",
    "Vi använder uppgifterna endast för att kontrollera den bekräftade bokningen och skapa en nödvändig krypterad sessionscookie.",
  ),
  closingTitle: text(
    "Not booked yet?",
    "Noch nicht gebucht?",
    "¿Todavía no habéis reservado?",
    "Nog niet geboekt?",
    "Har ni inte bokat ännu?",
  ),
  closingLead: text(
    "Book your Romantic Hideaway directly with AMARA. Once confirmed, your private AMARA Experience opens for the dates of your stay.",
    "Bucht euren Romantic Hideaway direkt bei AMARA. Nach der Bestätigung öffnet sich eure private AMARA Experience für die Reisedaten eures Aufenthalts.",
    "Reservad vuestro Romantic Hideaway directamente con AMARA. Una vez confirmado, vuestra AMARA Experience privada se abrirá para las fechas de la estancia.",
    "Boek jullie Romantic Hideaway rechtstreeks bij AMARA. Na bevestiging gaat jullie privé-AMARA Experience open voor de data van het verblijf.",
    "Boka ert Romantic Hideaway direkt med AMARA. Efter bekräftelsen öppnas er privata AMARA Experience för datumen för vistelsen.",
  ),
  availabilityLabel: text(
    "Check availability",
    "Verfügbarkeit prüfen",
    "Consultar disponibilidad",
    "Beschikbaarheid bekijken",
    "Kontrollera tillgänglighet",
  ),
};

export function getAmaraExperienceContent(lang: AmaraLanguage) {
  return resolveLocale(content, lang);
}
