import {
  resolveLocale,
  type LocalizedText,
  type LocalizedTextList,
} from "../types/content";
import type { AmaraAuthoringSeo, AmaraLanguage } from "../types/seo";

const text = (
  en: string,
  de: string,
  es: string,
  nl: string,
  sv: string,
): LocalizedText => ({ en, de, es, nl, sv });

export const amaraExperienceSeo: AmaraAuthoringSeo = {
  version: "2026-09-01-amara-experience-v2.1",
  pageType: "C",
  entityKey: "amara-brand",
  languages: {
    en: {
      title: "AMARA Guest Guide | Private local guide for couples",
      description:
        "Our personal recommendations for couples in Frigiliana, Nerja and Tarifa, with the route, the timing and what to check, exclusively for AMARA direct bookers.",
      robots: "index, follow",
      canonical: "auto",
    },
    de: {
      title: "AMARA Gästeguide | Privater Reiseguide für Paare",
      description:
        "Unsere persönlichen Empfehlungen für Paare in Frigiliana, Nerja und Tarifa, mit Weg, Zeitpunkt und dem, was zu prüfen ist, exklusiv für AMARA-Direktbucher.",
      robots: "index, follow",
      canonical: "auto",
    },
    es: {
      title: "Guía para huéspedes de AMARA | Guía local privada para parejas",
      description:
        "Nuestras recomendaciones personales para parejas en Frigiliana, Nerja y Tarifa, con el camino, el momento y lo que conviene comprobar, solo con reserva directa.",
      robots: "index, follow",
      canonical: "auto",
    },
    nl: {
      title: "AMARA Gastengids | Privégids voor stellen",
      description:
        "Onze persoonlijke aanbevelingen voor stellen in Frigiliana, Nerja en Tarifa, met route, timing en wat te controleren, exclusief bij direct boeken.",
      robots: "index, follow",
      canonical: "auto",
    },
    sv: {
      title: "AMARA Gästguide | Privat lokalguide för par",
      description:
        "Våra personliga rekommendationer för par i Frigiliana, Nerja och Tarifa, med väg, tidpunkt och vad som bör kontrolleras, exklusivt vid direktbokning.",
      robots: "index, follow",
      canonical: "auto",
    },
  },
};

const content = {
  eyebrow: text(
    "For guests who book directly",
    "Für Gäste, die direkt buchen",
    "Para huéspedes que reservan directamente",
    "Voor gasten die rechtstreeks boeken",
    "För gäster som bokar direkt",
  ),
  title: text(
    "AMARA Guest Guide",
    "AMARA Gästeguide",
    "Guía para huéspedes de AMARA",
    "AMARA Gastengids",
    "AMARA Gästguide",
  ),
  subtitle: text(
    "The addresses we give our friends.",
    "Die Adressen, die wir Freunden geben.",
    "Las direcciones que damos a nuestros amigos.",
    "De adressen die we onze vrienden geven.",
    "Adresserna vi ger våra vänner.",
  ),
  directAnswer: text(
    "Book directly with us and after confirmation you receive the AMARA Guest Guide: our restaurants, beaches and walks in Frigiliana, Nerja and Tarifa, with phone number, directions and what we experienced there ourselves. Plus everything about the house, from the wifi to the coffee machine.",
    "Wer direkt bei uns bucht, bekommt nach der Bestätigung den AMARA Gästeguide: unsere Restaurants, Strände und Wege in Frigiliana, Nerja und Tarifa, mit Telefonnummer, Anfahrt und dem, was wir dort selbst erlebt haben. Dazu alles zum Haus, vom WLAN bis zur Kaffeemaschine.",
    "Quien reserva directamente con nosotros recibe tras la confirmación la Guía de huéspedes AMARA: nuestros restaurantes, playas y caminos en Frigiliana, Nerja y Tarifa, con teléfono, cómo llegar y lo que hemos vivido allí. Además, todo sobre la casa, del wifi a la cafetera.",
    "Wie rechtstreeks bij ons boekt, krijgt na de bevestiging de AMARA gastengids: onze restaurants, stranden en wandelingen in Frigiliana, Nerja en Tarifa, met telefoonnummer, route en wat we er zelf hebben beleefd. Plus alles over het huis, van de wifi tot het koffiezetapparaat.",
    "Den som bokar direkt hos oss får efter bekräftelsen AMARA gästguide: våra restauranger, stränder och promenader i Frigiliana, Nerja och Tarifa, med telefonnummer, vägbeskrivning och det vi själva upplevt där. Dessutom allt om huset, från wifi till kaffemaskin.",
  ),
  heroAccent: text(
    "Less searching, more holiday.",
    "Weniger suchen, mehr Urlaub.",
    "Menos buscar, más vacaciones.",
    "Minder zoeken, meer vakantie.",
    "Mindre letande, mer semester.",
  ),
  promiseEyebrow: text(
    "What is inside",
    "Was drinsteht",
    "Lo que contiene",
    "Wat erin staat",
    "Vad som står i den",
  ),
  promiseTitle: text(
    "Addresses, not adverts",
    "Adressen, keine Anzeigen",
    "Direcciones, no anuncios",
    "Adressen, geen advertenties",
    "Adresser, inga annonser",
  ),
  promiseIntro: text(
    "A small selection we use ourselves, with the time to go, where to park and whether you need to book.",
    "Eine kleine Auswahl, die wir selbst nutzen, mit Uhrzeit, Parkplatz und der Frage, ob man reservieren muss.",
    "Una selección pequeña que usamos nosotros, con la hora, el aparcamiento y si hace falta reservar.",
    "Een kleine selectie die we zelf gebruiken, met tijdstip, parkeerplek en de vraag of je moet reserveren.",
    "Ett litet urval som vi själva använder, med tid, parkering och frågan om man måste boka.",
  ),
  promises: [
    {
      id: "authenticity",
      principle: text("Our addresses", "Unsere Adressen", "Nuestras direcciones", "Onze adressen", "Våra adresser"),
      title: text(
        "Where we eat, swim and walk ourselves",
        "Wo wir selbst essen, baden, laufen",
        "Donde comemos, nos bañamos y caminamos nosotros",
        "Waar we zelf eten, zwemmen, wandelen",
        "Där vi själva äter, badar, går",
      ),
      copy: text(
        "Bernal’s Pan Macho in Tarifa, the sundowner at Cochran’s in Nerja, the table above the rooftops of Frigiliana: places we have been, with start time, parking and reservation.",
        "Bernals Pan Macho in Tarifa, der Sundowner bei Cochran’s in Nerja, der Tisch über den Dächern von Frigiliana: Orte, an denen wir waren, mit Startzeit, Parken und Reservierung.",
        "El Pan Macho de Bernal en Tarifa, el atardecer con copa en Cochran’s en Nerja, la mesa sobre los tejados de Frigiliana: sitios en los que hemos estado, con hora de salida, aparcamiento y reserva.",
        "Bernals Pan Macho in Tarifa, de sundowner bij Cochran’s in Nerja, de tafel boven de daken van Frigiliana: plekken waar we zijn geweest, met starttijd, parkeren en reserveren.",
        "Bernals Pan Macho i Tarifa, sundownern på Cochran’s i Nerja, bordet över Frigilianas tak: platser där vi varit, med starttid, parkering och bokning.",
      ),
    },
    {
      id: "exclusivity",
      principle: text("Only in the Guest Guide", "Nur im Gästeguide", "Solo en la Guía de huéspedes", "Alleen in de gastengids", "Bara i gästguiden"),
      title: text(
        "Some of it is only there",
        "Ein Teil steht nur dort",
        "Una parte solo está ahí",
        "Een deel staat alleen daar",
        "En del står bara där",
      ),
      copy: text(
        "A few addresses we keep off the website because they are small. They are in the Guest Guide, with a second address in case the first is full.",
        "Ein paar Adressen halten wir aus der Website heraus, weil sie klein sind. Im Gästeguide stehen sie, mit einer zweiten Adresse, falls die erste voll ist.",
        "Algunas direcciones las dejamos fuera de la web porque son pequeñas. Están en la Guía de huéspedes, con una segunda dirección por si la primera está llena.",
        "Een paar adressen houden we van de website omdat ze klein zijn. Ze staan in de gastengids, met een tweede adres voor als het eerste vol is.",
        "Några adresser håller vi utanför webbplatsen eftersom de är små. De står i gästguiden, med en andra adress om den första är full.",
      ),
    },
    {
      id: "calm",
      principle: text("At the right time", "Zur richtigen Zeit", "En el momento adecuado", "Op het juiste moment", "Vid rätt tidpunkt"),
      title: text(
        "When a place is at its best",
        "Wann ein Ort am schönsten ist",
        "Cuándo un lugar está en su mejor momento",
        "Wanneer een plek op zijn mooist is",
        "När en plats är som vackrast",
      ),
      copy: text(
        "The Balcón at seven in the morning, the coves of Maro before high season, the market before ten: we tell you when well-known places are at their best.",
        "Der Balcón um sieben Uhr morgens, die Buchten von Maro vor der Hochsaison, der Markt vor zehn: Wir sagen euch, wann bekannte Orte am schönsten sind.",
        "El Balcón a las siete de la mañana, las calas de Maro antes de la temporada alta, el mercado antes de las diez: os decimos cuándo los sitios conocidos están en su mejor momento.",
        "De Balcón om zeven uur ’s ochtends, de baaien van Maro vóór het hoogseizoen, de markt vóór tienen: we vertellen wanneer bekende plekken op hun mooist zijn.",
        "Balcón klockan sju på morgonen, vikarna vid Maro före högsäsongen, marknaden före tio: vi berättar när kända platser är som vackrast.",
      ),
    },
  ],
  imageAlts: {
    village: text(
      "A white village street in Frigiliana beneath a clear blue sky",
      "Eine weiße Gasse in Frigiliana unter klarem blauem Himmel",
      "Una calle blanca de Frigiliana bajo un cielo azul despejado",
      "Een witte dorpsstraat in Frigiliana onder een heldere blauwe lucht",
      "En vit bygata i Frigiliana under en klarblå himmel",
    ),
    evening: text(
      "Bougainvillea and white houses in Frigiliana in the evening light",
      "Bougainvillea und weiße Häuser in Frigiliana im Abendlicht",
      "Bugambilia y casas blancas de Frigiliana a la luz de la tarde",
      "Bougainville en witte huizen in Frigiliana in het avondlicht",
      "Bougainvillea och vita hus i Frigiliana i kvällsljus",
    ),
    coast: text(
      "The coastline and beaches of Nerja seen from above",
      "Die Küste und Strände von Nerja aus der Luft",
      "La costa y las playas de Nerja vistas desde el aire",
      "De kust en stranden van Nerja vanuit de lucht",
      "Nerjas kust och stränder sedda från ovan",
    ),
  },
  valueEyebrow: text(
    "For days as a couple",
    "Für Tage zu zweit",
    "Para días en pareja",
    "Voor dagen met z’n tweeën",
    "För dagar på tu man hand",
  ),
  valueTitle: text(
    "Five ways to spend a day",
    "Fünf Arten, einen Tag zu verbringen",
    "Cinco maneras de pasar un día",
    "Vijf manieren om een dag te besteden",
    "Fem sätt att spendera en dag",
  ),
  valueIntro: text(
    "A long dinner, a walk with a view, a quiet beach or something you have never done. Each idea says why it suits this place.",
    "Ein langes Abendessen, ein Weg mit Aussicht, ein stiller Strand oder etwas, das ihr noch nie gemacht habt. Zu jeder Idee steht, warum sie zu diesem Ort passt.",
    "Una cena larga, un camino con vistas, una playa tranquila o algo que nunca habéis hecho. Junto a cada idea está por qué encaja en este lugar.",
    "Een lang diner, een wandeling met uitzicht, een stil strand of iets wat jullie nog nooit hebben gedaan. Bij elk idee staat waarom het bij deze plek past.",
    "En lång middag, en promenad med utsikt, en stilla strand eller något ni aldrig gjort. Vid varje idé står varför den passar just den här platsen.",
  ),
  benefits: [
    {
      id: "eat",
      number: "01",
      title: text(
        "An evening for two",
        "Ein Abend zu zweit",
        "Una noche para dos",
        "Een avond met z'n tweeën",
        "En kväll för två",
      ),
      copy: text(
        "Restaurants for a long dinner, a bar for the sundowner, a table with a view.",
        "Restaurants für ein langes Abendessen, eine Bar für den Sundowner, ein Tisch mit Blick.",
        "Restaurantes para una cena larga, un bar para el atardecer, una mesa con vistas.",
        "Restaurants voor een lang diner, een bar voor de sundowner, een tafel met uitzicht.",
        "Restauranger för en lång middag, en bar för sundownern, ett bord med utsikt.",
      ),
    },
    {
      id: "sea",
      number: "02",
      title: text(
        "A beach for the day",
        "Ein Strand für den Tag",
        "Una playa para el día",
        "Een strand voor de dag",
        "En strand för dagen",
      ),
      copy: text(
        "Quiet mornings, a swim before breakfast, a coast day with lunch at the chiringuito.",
        "Ruhige Vormittage, ein Bad vor dem Frühstück, ein Küstentag mit Mittagessen im Chiringuito.",
        "Mañanas tranquilas, un baño antes del desayuno, un día de costa con comida en el chiringuito.",
        "Rustige ochtenden, een duik voor het ontbijt, een kustdag met lunch in de chiringuito.",
        "Lugna förmiddagar, ett dopp före frukost, en kustdag med lunch på chiringuiton.",
      ),
    },
    {
      id: "walk",
      number: "03",
      title: text(
        "Walks with a view",
        "Wege mit Aussicht",
        "Paseos con vistas",
        "Wandelingen met uitzicht",
        "Promenader med utsikt",
      ),
      copy: text(
        "Lanes, nature trails and viewpoints where you stop longer than planned.",
        "Gassen, Naturwege und Aussichtspunkte, an denen man länger stehen bleibt als geplant.",
        "Callejuelas, senderos y miradores en los que uno se queda más de lo previsto.",
        "Steegjes, natuurpaden en uitzichtpunten waar je langer blijft staan dan gepland.",
        "Gränder, naturstigar och utsiktsplatser där man stannar längre än planerat.",
      ),
    },
    {
      id: "together",
      number: "04",
      title: text(
        "Do something together",
        "Gemeinsam etwas erleben",
        "Hacer algo juntos",
        "Samen iets beleven",
        "Uppleva något tillsammans",
      ),
      copy: text(
        "A kite lesson, a boat trip or the cave: experiences that give the day a story, with everything you need to know for them.",
        "Kitekurs, Bootstour oder Höhle: Erlebnisse, die dem Tag eine Geschichte geben, mit allem, was ihr dafür wissen müsst.",
        "Un curso de kite, una salida en barco o la cueva: experiencias que dan al día una historia, con todo lo que necesitáis saber.",
        "Kiteles, boottocht of grot: belevenissen die de dag een verhaal geven, met alles wat jullie ervoor moeten weten.",
        "Kitekurs, båttur eller grotta: upplevelser som ger dagen en berättelse, med allt ni behöver veta.",
      ),
    },
    {
      id: "day-trip",
      number: "05",
      title: text(
        "A day trip worth taking",
        "Ein Ausflug, der sich lohnt",
        "Una excursión que merece la pena",
        "Een uitstapje dat de moeite waard is",
        "En utflykt värd tiden",
      ),
      copy: text(
        "Nearby villages, towns and day trips, with driving time and the best place to start.",
        "Dörfer, Städte und Tagesausflüge in der Nähe, mit Fahrzeit und dem besten Startpunkt.",
        "Pueblos, ciudades y excursiones cercanas, con tiempo de viaje y el mejor punto de partida.",
        "Dorpen, steden en dagtochten in de buurt, met rijtijd en het beste startpunt.",
        "Byar, städer och dagsutflykter i närheten, med restid och bästa startpunkt.",
      ),
    },
  ],
  hostEyebrow: text(
    "First-hand",
    "Aus erster Hand",
    "De primera mano",
    "Uit eerste hand",
    "Från första hand",
  ),
  hostTitle: text(
    "We live here, and every recommendation in the guide has been approved by Robert himself.",
    "Wir wohnen hier, und jede Empfehlung im Guide hat Robert selbst freigegeben.",
    "Vivimos aquí, y cada recomendación de la guía la ha aprobado el propio Robert.",
    "We wonen hier, en elke aanbeveling in de gids heeft Robert zelf goedgekeurd.",
    "Vi bor här, och varje rekommendation i guiden har Robert själv godkänt.",
  ),
  hostParagraphs: {
    en: [
      "We have welcomed AMARA guests since May 2021 and regularly return to our stays in Frigiliana, Nerja and Tarifa. Our personal perspective grows from these stays and the time we spend in each destination. We verify opening hours, access rules and other changing details separately.",
      "That is why a beach tip also explains what it means for your day. From AMARA Playa, Torrecilla is about 200 metres away, so it works for a quick swim or a return near sunset. In Tarifa, we use the Mercadona opposite the apartment for everyday shopping and choose Pastelito or Bernal for bread — especially Bernal's Pan Macho. Details like these turn a list into local guidance.",
      "The private AMARA Experience follows the same principle for romantic restaurants, quieter beaches, walks, shared activities and day trips: we tell you what we know, why it may fit and what you should check before setting out.",
    ],
    de: [
      "Seit Mai 2021 empfangen wir Gäste bei AMARA und sind regelmäßig in unseren Unterkünften in Frigiliana, Nerja und Tarifa. Unsere persönliche Perspektive entsteht aus diesen Aufenthalten und der Zeit, die wir an jedem der drei Orte verbringen. Öffnungszeiten, Zufahrten und andere veränderliche Angaben prüfen wir separat.",
      "Darum erklärt ein Strandtipp auch, was er für euren Tag bedeutet: Von AMARA Playa liegt Torrecilla rund 200 Meter entfernt – gut für ein schnelles Bad oder einen zweiten Besuch gegen Sonnenuntergang. In Tarifa nutzen wir den Mercadona direkt gegenüber dem Apartment; Brot holen wir bei Pastelito oder Bernal, besonders gern Bernals Pan Macho. Solche Details machen aus einer Liste lokale Orientierung.",
      "Im privaten AMARA Experience Guide gilt dasselbe für romantische Restaurants, ruhigere Strände, Wege, gemeinsame Aktivitäten und Ausflüge: Wir sagen euch, was wir wissen, warum es passen könnte und was ihr vor dem Aufbruch noch prüfen solltet.",
    ],
    es: [
      "Recibimos a huéspedes de AMARA desde mayo de 2021 y volvemos con regularidad a nuestros alojamientos de Frigiliana, Nerja y Tarifa. Nuestra perspectiva personal nace de estas estancias y del tiempo que pasamos en cada destino. Comprobamos por separado los horarios, accesos y demás datos que cambian.",
      "Por eso una recomendación de playa explica también qué aporta al día. Torrecilla está a unos 200 metros de AMARA Playa, así que permite un baño rápido o volver cerca del atardecer. En Tarifa usamos el Mercadona frente al apartamento para la compra diaria y elegimos Pastelito o Bernal para el pan, especialmente el Pan Macho de Bernal. Esos detalles convierten una lista en orientación local.",
      "La AMARA Experience privada aplica el mismo criterio a restaurantes románticos, playas tranquilas, paseos, actividades para dos y excursiones: os contamos qué sabemos, por qué puede encajar y qué conviene comprobar antes de salir.",
    ],
    nl: [
      "Sinds mei 2021 ontvangen we gasten bij AMARA en verblijven we regelmatig in onze accommodaties in Frigiliana, Nerja en Tarifa. Ons persoonlijke perspectief komt voort uit deze verblijven en de tijd die we op elke bestemming doorbrengen. Openingstijden, toegangsregels en andere veranderlijke details controleren we apart.",
      "Daarom vertelt een strandtip ook wat die voor jullie dag betekent. Torrecilla ligt op ongeveer 200 meter van AMARA Playa, dus een snelle duik of terugkeer rond zonsondergang is eenvoudig. In Tarifa gebruiken we de Mercadona tegenover het appartement voor dagelijkse boodschappen en kiezen we Pastelito of Bernal voor brood, vooral Bernals Pan Macho. Zulke details maken van een lijst lokale begeleiding.",
      "De besloten AMARA Experience werkt volgens hetzelfde principe voor romantische restaurants, rustige stranden, wandelingen, activiteiten samen en uitstapjes: we vertellen wat we weten, waarom het kan passen en wat jullie voor vertrek nog moeten controleren.",
    ],
    sv: [
      "Vi har tagit emot AMARA-gäster sedan maj 2021 och återvänder regelbundet till våra boenden i Frigiliana, Nerja och Tarifa. Vårt personliga perspektiv växer fram ur vistelserna och tiden vi tillbringar på varje destination. Vi kontrollerar öppettider, tillträdesregler och andra uppgifter som ändras separat.",
      "Därför förklarar ett strandtips också vad platsen betyder för dagen. Torrecilla ligger omkring 200 meter från AMARA Playa, så ett snabbt dopp eller ett återbesök nära solnedgången är enkelt. I Tarifa använder vi Mercadona mittemot lägenheten för vardagsinköp och väljer Pastelito eller Bernal för bröd, särskilt Bernals Pan Macho. Sådana detaljer gör en lista till lokal vägledning.",
      "Den privata AMARA Experience följer samma princip för romantiska restauranger, lugnare stränder, promenader, gemensamma aktiviteter och utflykter: vi berättar vad vi vet, varför det kan passa och vad ni bör kontrollera innan ni ger er av.",
    ],
  } satisfies LocalizedTextList,
  hostAuthorName: "Robert Sebastian Böhmer",
  hostUpdated: text(
    "As of September 2026",
    "Stand September 2026",
    "Actualizado en septiembre de 2026",
    "Stand september 2026",
    "Uppdaterad september 2026",
  ),
  hostNote: text(
    "",
    "",
    "",
    "",
    "",
  ),
  accessEyebrow: text(
    "Already booked directly?",
    "Schon direkt gebucht?",
    "¿Ya habéis reservado directamente?",
    "Al rechtstreeks geboekt?",
    "Har ni redan bokat direkt?",
  ),
  accessTitle: text(
    "This is the way in",
    "Hier geht es hinein",
    "Por aquí se entra",
    "Hier ga je naar binnen",
    "Här går ni in",
  ),
  accessGuideLabel: text(
    "AMARA Guest Guide",
    "AMARA Gästeguide",
    "Guía para huéspedes de AMARA",
    "AMARA Gastengids",
    "AMARA Gästguide",
  ),
  accessIntro: text(
    "Everything about your stay, the essentials on site and our recommendations for Frigiliana, Nerja or Tarifa.",
    "Alles zu eurer Unterkunft, das Wichtigste vor Ort und unsere Empfehlungen für Frigiliana, Nerja oder Tarifa.",
    "Todo sobre vuestro alojamiento, lo esencial del lugar y nuestras recomendaciones para Frigiliana, Nerja o Tarifa.",
    "Alles over jullie accommodatie, het belangrijkste ter plaatse en onze aanbevelingen voor Frigiliana, Nerja of Tarifa.",
    "Allt om ert boende, det viktigaste på plats och våra rekommendationer för Frigiliana, Nerja eller Tarifa.",
  ),
  accessInstructions: text(
    "Use your guide before and during your stay. Enter the first name on your reservation and your arrival date.",
    "Für den Zugang gebt einfach den Vornamen aus eurer Reservierung und euer Anreisedatum ein.",
    "Usad vuestra guía antes y durante la estancia. Introducid el nombre de la reserva y vuestra fecha de llegada.",
    "Gebruik jullie gids vóór en tijdens het verblijf. Vul de voornaam op de reservering en jullie aankomstdatum in.",
    "Använd er guide före och under vistelsen. Ange förnamnet i bokningen och ert ankomstdatum.",
  ),
  accessLandingLabel: text(
    "Learn more about the AMARA Guest Guide",
    "Mehr über den AMARA Gästeguide",
    "Más sobre la guía para huéspedes de AMARA",
    "Meer over de AMARA Gastengids",
    "Läs mer om AMARA Gästguide",
  ),
  formTitle: text(
    "AMARA Guest Guide",
    "AMARA Gästeguide",
    "Guía para huéspedes de AMARA",
    "AMARA Gastengids",
    "AMARA Gästguide",
  ),
  firstNameLabel: text(
    "First name on reservation",
    "Vorname in der Reservierung",
    "Nombre de la reserva",
    "Voornaam op de reservering",
    "Förnamn i bokningen",
  ),
  arrivalLabel: text(
    "Arrival date",
    "Anreisedatum",
    "Fecha de llegada",
    "Aankomstdatum",
    "Ankomstdatum",
  ),
  chooseArrivalLabel: text(
    "Choose arrival date",
    "Anreisedatum wählen",
    "Elegir fecha de llegada",
    "Aankomstdatum kiezen",
    "Välj ankomstdatum",
  ),
  datePickerTitle: text(
    "Select your arrival date",
    "Anreisedatum auswählen",
    "Seleccionad vuestra fecha de llegada",
    "Kies jullie aankomstdatum",
    "Välj ert ankomstdatum",
  ),
  datePickerHelp: text(
    "Use the date from your reservation.",
    "Nehmt das Datum aus eurer Reservierung.",
    "Usad la fecha de vuestra reserva.",
    "Gebruik de datum van jullie reservering.",
    "Använd datumet från er bokning.",
  ),
  datePickerRequiredMessage: text(
    "Use the date from your reservation.",
    "Nehmt das Datum aus eurer Reservierung.",
    "Usad la fecha de vuestra reserva.",
    "Gebruik de datum van jullie reservering.",
    "Använd datumet från er bokning.",
  ),
  previousMonthLabel: text(
    "Show previous month",
    "Vorherigen Monat anzeigen",
    "Mostrar el mes anterior",
    "Vorige maand tonen",
    "Visa föregående månad",
  ),
  nextMonthLabel: text(
    "Show next month",
    "Nächsten Monat anzeigen",
    "Mostrar el mes siguiente",
    "Volgende maand tonen",
    "Visa nästa månad",
  ),
  submitLabel: text(
    "Open the Guest Guide",
    "Gästeguide öffnen",
    "Abrir la guía para huéspedes",
    "Gastengids openen",
    "Öppna gästguiden",
  ),
  pendingLabel: text(
    "Checking booking…",
    "Buchung wird geprüft…",
    "Comprobando la reserva…",
    "Boeking controleren…",
    "Kontrollerar bokningen…",
  ),
  deniedMessage: text(
    "We found no booking with these details. Check the booking confirmation or write to us.",
    "Mit diesen Angaben haben wir keine Buchung gefunden. Schaut in die Buchungsbestätigung oder schreibt uns.",
    "Con estos datos no hemos encontrado ninguna reserva. Mirad la confirmación de reserva o escribidnos.",
    "Met deze gegevens hebben we geen boeking gevonden. Kijk in de boekingsbevestiging of schrijf ons.",
    "Med de här uppgifterna hittade vi ingen bokning. Titta i bokningsbekräftelsen eller skriv till oss.",
  ),
  unavailableMessage: text(
    "The private guide is not available right now. Please try again later.",
    "Der private Guide ist gerade nicht verfügbar. Bitte versucht es später noch einmal.",
    "La guía privada no está disponible ahora. Intentadlo de nuevo más tarde.",
    "De privégids is nu niet beschikbaar. Probeer het later opnieuw.",
    "Den privata guiden är inte tillgänglig just nu. Försök igen senare.",
  ),
  sessionEndedMessage: text(
    "Your guide session has ended. Enter the booking details again if the stay is still active.",
    "Eure Guide-Sitzung ist beendet. Gebt die Buchungsdaten erneut ein, falls der Aufenthalt noch aktiv ist.",
    "La sesión de la guía ha terminado. Volved a introducir los datos si la estancia sigue activa.",
    "Jullie gidssessie is beëindigd. Vul de boekingsgegevens opnieuw in als het verblijf nog actief is.",
    "Guidesessionen har avslutats. Ange bokningsuppgifterna igen om vistelsen fortfarande är aktiv.",
  ),
  privacyNote: text(
    "Used only to verify your booking and keep you signed in.",
    "Nur zur Buchungsprüfung und Anmeldung.",
    "Solo para verificar la reserva y mantener la sesión.",
    "Alleen voor boekingscontrole en aanmelding.",
    "Endast för bokningskontroll och inloggning.",
  ),
  closingTitle: text(
    "Time together in an AMARA Romantic Hideaway.",
    "Zeit für euch in einem AMARA Romantic Hideaway.",
    "Tiempo para vosotros en un Romantic Hideaway de AMARA.",
    "Tijd voor elkaar in een AMARA Romantic Hideaway.",
    "Tid tillsammans i ett AMARA Romantic Hideaway.",
  ),
  closingLead: text(
    "Book directly with AMARA. With the confirmation, your Guest Guide opens for the days of your stay.",
    "Bucht direkt bei AMARA. Mit der Bestätigung öffnet sich euer Gästeguide für die Tage eures Aufenthalts.",
    "Reservad directamente con AMARA. Con la confirmación se abre vuestra Guía de huéspedes para los días de la estancia.",
    "Boek rechtstreeks bij AMARA. Met de bevestiging opent jullie gastengids voor de dagen van jullie verblijf.",
    "Boka direkt hos AMARA. Med bekräftelsen öppnas er gästguide för dagarna ni bor här.",
  ),
  availabilityLabel: text(
    "Check availability",
    "Verfügbarkeit prüfen",
    "Consultar disponibilidad",
    "Beschikbaarheid bekijken",
    "Kontrollera tillgänglighet",
  ),
};

export function getAmaraExperienceContent(lang: AmaraLanguage) {
  return resolveLocale(content, lang);
}
