import {
  resolveLocale,
  type LocalizedText,
  type LocalizedTextList,
} from "../types/content";
import type { AmaraAuthoringSeo, AmaraLanguage } from "../types/seo";

const text = (
  en: string,
  de: string,
  es: string,
  nl: string,
  sv: string,
): LocalizedText => ({ en, de, es, nl, sv });

export const amaraExperienceSeo: AmaraAuthoringSeo = {
  version: "2026-09-01-amara-experience-v2.1",
  pageType: "C",
  entityKey: "amara-brand",
  languages: {
    en: {
      title: "AMARA Experience | Private local guide for couples",
      description:
        "Personal insider tips for romantic time, hidden treasures and quieter places in Frigiliana, Nerja and Tarifa — exclusively for AMARA direct bookers.",
      robots: "index, follow",
      canonical: "auto",
    },
    de: {
      title: "AMARA Experience | Privater Reiseguide für Paare",
      description:
        "Persönliche Insider-Tipps für romantische Zeit, versteckte Schätze und ruhige Orte in Frigiliana, Nerja und Tarifa – exklusiv für AMARA-Direktbucher.",
      robots: "index, follow",
      canonical: "auto",
    },
    es: {
      title: "AMARA Experience | Guía local privada para parejas",
      description:
        "Recomendaciones personales para momentos románticos, rincones escondidos y lugares tranquilos en Frigiliana, Nerja y Tarifa, solo con reserva directa.",
      robots: "index, follow",
      canonical: "auto",
    },
    nl: {
      title: "AMARA Experience | Privégids voor stellen",
      description:
        "Persoonlijke insidertips voor romantische tijd, verborgen parels en rustige plekken in Frigiliana, Nerja en Tarifa, exclusief bij direct boeken.",
      robots: "index, follow",
      canonical: "auto",
    },
    sv: {
      title: "AMARA Experience | Privat lokalguide för par",
      description:
        "Personliga insidertips för romantisk tid, dolda pärlor och lugnare platser i Frigiliana, Nerja och Tarifa – exklusivt vid direktbokning.",
      robots: "index, follow",
      canonical: "auto",
    },
  },
};

const content = {
  eyebrow: text(
    "Private local guide for direct bookers",
    "Privater Reiseguide für Direktbucher",
    "Guía local privada al reservar directamente",
    "Privégids bij direct boeken",
    "Privat lokalguide vid direktbokning",
  ),
  title: text(
    "AMARA Experience",
    "AMARA Experience",
    "AMARA Experience",
    "AMARA Experience",
    "AMARA Experience",
  ),
  subtitle: text(
    "More local knowledge. More romantic time together in Frigiliana, Nerja and Tarifa.",
    "Mehr lokales Wissen. Mehr romantische Zeit zu zweit in Frigiliana, Nerja und Tarifa.",
    "Más conocimiento local. Más tiempo romántico juntos en Frigiliana, Nerja y Tarifa.",
    "Meer lokale kennis. Meer romantische tijd samen in Frigiliana, Nerja en Tarifa.",
    "Mer lokalkännedom. Mer romantisk tid tillsammans i Frigiliana, Nerja och Tarifa.",
  ),
  directAnswer: text(
    "AMARA Experience is our exclusive direct-booking benefit for couples staying with us in Frigiliana, Nerja or Tarifa: a **private guide with personal insider tips** that go beyond the familiar sights. Once your direct booking is confirmed, we share **local favourites**, **hidden treasures** and **lesser-known places** — from a romantic restaurant or quiet beach to a walk, shared activity or town worth a day trip. Every recommendation has a reason. We check what fits each AMARA destination, explain why a place or time of day may be worthwhile and help you enjoy more time **off the beaten track**, away from the busiest routes. Your holiday holds more time to experience these places together.",
    "AMARA Experience ist unser exklusiver Direktbucher-Vorteil für Paare mit einem Aufenthalt bei uns in Frigiliana, Nerja oder Tarifa: ein **privater Guide mit persönlichen Insider-Tipps**, die über die bekannten Sehenswürdigkeiten hinausgehen. Nach bestätigter Direktbuchung teilen wir **lokale Favoriten**, **versteckte Schätze** und **weniger bekannte Orte** – vom romantischen Restaurant und ruhigen Strand bis zur Wanderung, Aktivität oder Stadt für einen gemeinsamen Ausflug. Jede Empfehlung hat einen guten Grund. Wir prüfen, was zum jeweiligen AMARA-Reiseziel passt, erklären, warum sich ein Ort oder Zeitpunkt lohnt, und helfen euch, öfter **abseits der Touristenpfade** unterwegs zu sein. So bleibt euch im Urlaub mehr Zeit, diese Orte gemeinsam zu erleben.",
    "AMARA Experience es nuestra ventaja exclusiva para parejas que os alojáis con nosotros en Frigiliana, Nerja o Tarifa y reserváis directamente: una **guía privada con recomendaciones locales** que van más allá de los lugares conocidos. Tras confirmar la reserva directa, compartimos **favoritos locales**, **rincones escondidos** y **sitios menos conocidos**, desde un restaurante romántico o una playa tranquila hasta una ruta, una actividad para dos o una localidad que merece una excursión. Cada recomendación tiene un motivo. Comprobamos qué encaja con cada destino AMARA, explicamos por qué merece la pena un lugar o un momento del día y os ayudamos a disfrutar **fuera de las rutas turísticas más transitadas**. Así tenéis más tiempo para vivir juntos estos lugares.",
    "AMARA Experience is ons exclusieve voordeel voor stellen die hun verblijf bij ons in Frigiliana, Nerja of Tarifa rechtstreeks boeken: een **privégids met persoonlijke insidertips** die verder gaan dan de bekende bezienswaardigheden. Na bevestiging van jullie directe boeking delen we **lokale favorieten**, **verborgen parels** en **minder bekende plekken** — van een romantisch restaurant of rustig strand tot een wandeling, activiteit samen of plaats die een dagtrip waard is. Elke aanbeveling heeft een goede reden. We controleren wat bij elke AMARA-bestemming past, leggen uit waarom een plek of tijdstip de moeite waard kan zijn en helpen jullie vaker **buiten de gebaande toeristische paden** te komen. Zo blijft er meer tijd over om deze plekken samen te beleven.",
    "AMARA Experience är vår exklusiva fördel för par som bokar direkt och bor hos oss i Frigiliana, Nerja eller Tarifa: en **privat guide med personliga insidertips** bortom de välkända sevärdheterna. När direktbokningen är bekräftad delar vi **lokala favoriter**, **dolda pärlor** och **mindre kända platser** — från en romantisk restaurang eller lugn strand till en vandring, gemensam aktivitet eller ort värd en dagsutflykt. Varje rekommendation har en tydlig anledning. Vi kontrollerar vad som passar varje AMARA-destination, förklarar varför en plats eller tid på dagen kan vara värd att välja och hjälper er att uppleva mer **bortom de mest välbesökta turiststråken**. Då får ni mer tid att upptäcka platserna tillsammans.",
  ),
  heroAccent: text(
    "More time to experience it together.",
    "Mehr Zeit zum gemeinsamen Erleben.",
    "Más tiempo para disfrutar juntos.",
    "Meer tijd om samen te beleven.",
    "Mer tid att uppleva tillsammans.",
  ),
  promiseEyebrow: text(
    "What direct bookers receive",
    "Was Direktbucher erhalten",
    "Lo que recibís al reservar directamente",
    "Wat jullie bij direct boeken ontvangen",
    "Det här får ni när ni bokar direkt",
  ),
  promiseTitle: text(
    "Authentic. Exclusive. Beyond the crowds.",
    "Authentisch. Exklusiv. Abseits der Massen.",
    "Auténtico. Exclusivo. Lejos de las multitudes.",
    "Authentiek. Exclusief. Buiten de drukte.",
    "Genuint. Exklusivt. Bortom trängseln.",
  ),
  promiseIntro: text(
    "A small, personal selection with practical details, good timing and honest alternatives helps you enjoy the day from the moment you set off.",
    "Eine kleine, persönliche Auswahl mit praktischen Details, dem passenden Zeitpunkt und ehrlichen Alternativen macht euch den Tag von Anfang an leichter.",
    "Una selección breve y personal, con información práctica, el momento adecuado y alternativas sinceras, os ayuda a disfrutar del día desde que salís.",
    "Een kleine, persoonlijke selectie met praktische informatie, een goed moment en eerlijke alternatieven maakt de dag vanaf vertrek gemakkelijker.",
    "Ett litet, personligt urval med praktiska detaljer, bra tidpunkter och ärliga alternativ gör dagen enklare redan från start.",
  ),
  promises: [
    {
      id: "authenticity",
      principle: text("Authenticity", "Authentizität", "Autenticidad", "Authenticiteit", "Genuinitet"),
      title: text(
        "Local favourites and personal insider tips",
        "Lokale Favoriten und persönliche Insider-Tipps",
        "Favoritos locales y recomendaciones personales",
        "Lokale favorieten en persoonlijke insidertips",
        "Lokala favoriter och personliga insidertips",
      ),
      copy: text(
        "We share local favourites with the detail that changes the day: a useful time to set off, how access or parking works, whether booking ahead makes sense and what should be checked again shortly before you go.",
        "Wir teilen lokale Favoriten mit den Details, die den Tag verändern: eine sinnvolle Startzeit, Hinweise zu Zufahrt oder Parken, ob eine Reservierung ratsam ist und was ihr kurz vorher noch einmal prüfen solltet.",
        "Compartimos favoritos locales con los detalles que cambian el día: una buena hora para salir, cómo funcionan el acceso o el aparcamiento, si conviene reservar y qué deberíais comprobar poco antes.",
        "We delen lokale favorieten met de details die de dag veranderen: een slim vertrekmoment, hoe toegang of parkeren werkt, of reserveren verstandig is en wat jullie kort van tevoren nog moeten controleren.",
        "Vi delar lokala favoriter med detaljerna som förändrar dagen: en bra tid att ge sig av, hur tillträde eller parkering fungerar, om det är klokt att boka och vad ni bör kontrollera strax innan.",
      ),
    },
    {
      id: "exclusivity",
      principle: text("Exclusivity", "Exklusivität", "Exclusividad", "Exclusiviteit", "Exklusivitet"),
      title: text(
        "Hidden treasures and lesser-known places",
        "Versteckte Schätze und weniger bekannte Orte",
        "Rincones escondidos y lugares menos conocidos",
        "Verborgen parels en minder bekende plekken",
        "Dolda pärlor och mindre kända platser",
      ),
      copy: text(
        "Your confirmed direct booking opens a deliberately small selection for AMARA guests: places we can explain, **lesser-known options** we consider worthwhile and the practical context needed to enjoy them.",
        "Eure bestätigte Direktbuchung öffnet eine bewusst kleine Auswahl für AMARA-Gäste: Orte, die wir begründen können, lohnende **weniger bekannte Alternativen** und den praktischen Kontext dazu.",
        "La reserva directa confirmada abre una selección deliberadamente breve para huéspedes de AMARA: lugares que podemos explicar, **alternativas menos conocidas** que merecen la pena y su contexto práctico.",
        "Jullie bevestigde directe boeking opent een bewust kleine selectie voor AMARA-gasten: plekken die we kunnen toelichten, waardevolle **minder bekende alternatieven** en de praktische context erbij.",
        "Er bekräftade direktbokning öppnar ett medvetet litet urval för AMARA-gäster: platser vi kan motivera, värdefulla **mindre kända alternativ** och det praktiska sammanhanget runt dem.",
      ),
    },
    {
      id: "calm",
      principle: text("More calm", "Mehr Ruhe", "Más calma", "Meer rust", "Mer lugn"),
      title: text(
        "Off the beaten track, away from the crowds",
        "Abseits der Touristenpfade und der Massen",
        "Fuera de las rutas turísticas más transitadas",
        "Buiten de gebaande paden en de drukte",
        "Bortom turiststråken och trängseln",
      ),
      copy: text(
        "We share well-known places when the timing makes them enjoyable and a quieter alternative when it suits the day you want even better.",
        "Wir empfehlen bekannte Orte zu den Zeiten, in denen sie besonders schön sind, und eine ruhigere Alternative, wenn sie noch besser zu eurem Tag passt.",
        "Os recomendamos los lugares conocidos en el momento en que más se disfrutan y una alternativa tranquila cuando encaja todavía mejor con el día que queréis vivir.",
        "We delen bekende plekken op het moment dat ze het prettigst zijn en een rustiger alternatief wanneer dat nog beter past bij de dag die jullie willen.",
        "Vi tipsar om välkända platser vid tiden då de är som mest njutbara och visar ett lugnare alternativ när det passar er dag ännu bättre.",
      ),
    },
  ],
  imageAlts: {
    village: text(
      "A white village street in Frigiliana beneath a clear blue sky",
      "Eine weiße Gasse in Frigiliana unter klarem blauem Himmel",
      "Una calle blanca de Frigiliana bajo un cielo azul despejado",
      "Een witte dorpsstraat in Frigiliana onder een heldere blauwe lucht",
      "En vit bygata i Frigiliana under en klarblå himmel",
    ),
    evening: text(
      "Bougainvillea and white houses in Frigiliana in the evening light",
      "Bougainvillea und weiße Häuser in Frigiliana im Abendlicht",
      "Bugambilia y casas blancas de Frigiliana a la luz de la tarde",
      "Bougainville en witte huizen in Frigiliana in het avondlicht",
      "Bougainvillea och vita hus i Frigiliana i kvällsljus",
    ),
    coast: text(
      "The coastline and beaches of Nerja seen from above",
      "Die Küste und Strände von Nerja aus der Luft",
      "La costa y las playas de Nerja vistas desde el aire",
      "De kust en stranden van Nerja vanuit de lucht",
      "Nerjas kust och stränder sedda från ovan",
    ),
  },
  valueEyebrow: text(
    "Romantic ideas, personally selected",
    "Romantische Ideen, persönlich ausgewählt",
    "Ideas románticas, seleccionadas personalmente",
    "Romantische ideeën, persoonlijk geselecteerd",
    "Romantiska idéer, personligt utvalda",
  ),
  valueTitle: text(
    "Romantic time that feels like the two of you.",
    "Romantische Zeit, die sich nach euch anfühlt.",
    "Tiempo romántico que se sienta realmente vuestro.",
    "Romantische tijd die echt als die van jullie voelt.",
    "Romantisk tid som känns som just er.",
  ),
  valueIntro: text(
    "A long dinner, a beautiful walk, a quiet beach or something new to do together: we show you why an idea may suit the moment and add it only after checking it for that destination.",
    "Ein langes Abendessen, ein schöner Weg, ein ruhiger Strand oder etwas Neues, das ihr gemeinsam erlebt: Wir zeigen euch, warum eine Idee zum Moment passen könnte, und nehmen sie erst auf, wenn sie für das Reiseziel geprüft ist.",
    "Una cena larga, un paseo bonito, una playa tranquila o algo nuevo que hacer juntos: os contamos por qué una idea puede encajar con el momento y solo la añadimos cuando está comprobada para ese destino.",
    "Lang tafelen, een mooie wandeling, een rustig strand of samen iets nieuws doen: we vertellen waarom een idee bij het moment kan passen en voegen het pas toe als het voor die bestemming is gecontroleerd.",
    "En lång middag, en vacker promenad, en lugn strand eller något nytt att göra tillsammans: vi berättar varför en idé kan passa stunden och lägger bara till den när den har kontrollerats för destinationen.",
  ),
  benefits: [
    {
      id: "eat",
      number: "01",
      title: text(
        "An evening for two",
        "Ein Abend zu zweit",
        "Una noche para dos",
        "Een avond met z'n tweeën",
        "En kväll för två",
      ),
      copy: text(
        "Restaurants and local places for a long dinner, a special evening or an unhurried drink together.",
        "Restaurants und lokale Adressen für ein langes Abendessen, einen besonderen Abend oder einen entspannten Drink zu zweit.",
        "Restaurantes y lugares locales para una cena larga, una noche especial o una copa sin prisas juntos.",
        "Restaurants en lokale adressen voor lang tafelen, een bijzondere avond of samen rustig iets drinken.",
        "Restauranger och lokala ställen för en lång middag, en särskild kväll eller något gott att dricka tillsammans i lugn och ro.",
      ),
    },
    {
      id: "sea",
      number: "02",
      title: text(
        "A beach for your rhythm",
        "Ein Strand für euren Rhythmus",
        "Una playa a vuestro ritmo",
        "Een strand op jullie tempo",
        "En strand i er takt",
      ),
      copy: text(
        "Beaches for a quiet morning, a swim together or a coast day with lunch and nowhere else you need to be.",
        "Strände für einen ruhigen Vormittag, ein gemeinsames Bad oder einen Küstentag mit Mittagessen und ohne weiteren Termin.",
        "Playas para una mañana tranquila, un baño juntos o un día de costa con comida y sin tener que llegar a ningún otro sitio.",
        "Stranden voor een rustige ochtend, samen zwemmen of een dag aan de kust met lunch en verder helemaal niets op de planning.",
        "Stränder för en lugn förmiddag, ett bad tillsammans eller en dag vid kusten med lunch och ingen annan tid att passa.",
      ),
    },
    {
      id: "walk",
      number: "03",
      title: text(
        "Walks with a view",
        "Wege mit Aussicht",
        "Paseos con vistas",
        "Wandelingen met uitzicht",
        "Promenader med utsikt",
      ),
      copy: text(
        "Village lanes, nature routes and viewpoints for talking as you go and stopping when the view deserves more time.",
        "Gassen, Naturwege und Aussichtspunkte, auf denen ihr unterwegs miteinander redet und dort bleibt, wo der Blick mehr Zeit verdient.",
        "Calles de pueblo, rutas por la naturaleza y miradores para conversar por el camino y deteneros cuando las vistas merezcan más tiempo.",
        "Dorpsstraatjes, natuurroutes en uitzichtpunten om onderweg te praten en te blijven waar het uitzicht wat meer tijd verdient.",
        "Bygator, naturleder och utsiktsplatser där ni kan prata längs vägen och stanna när utsikten förtjänar mer tid.",
      ),
    },
    {
      id: "together",
      number: "04",
      title: text(
        "Do something together",
        "Gemeinsam etwas erleben",
        "Hacer algo juntos",
        "Samen iets beleven",
        "Uppleva något tillsammans",
      ),
      copy: text(
        "Shared experiences that give the day its own story, chosen for the destination and with the practical details you need.",
        "Gemeinsame Erlebnisse, die dem Tag eine eigene Geschichte geben – passend zum Reiseziel und mit den praktischen Details, die ihr dafür braucht.",
        "Experiencias compartidas que den al día su propia historia, elegidas para el destino y con los detalles prácticos que necesitáis.",
        "Gedeelde ervaringen die de dag een eigen verhaal geven, gekozen voor de bestemming en met de praktische informatie die jullie nodig hebben.",
        "Gemensamma upplevelser som ger dagen sin egen berättelse, utvalda för destinationen och med den praktiska information ni behöver.",
      ),
    },
    {
      id: "day-trip",
      number: "05",
      title: text(
        "A day trip worth taking",
        "Ein Ausflug, der sich lohnt",
        "Una excursión que merece la pena",
        "Een uitstapje dat de moeite waard is",
        "En utflykt värd tiden",
      ),
      copy: text(
        "Nearby villages, towns and day trips that reward the journey when you want to discover somewhere new as a couple.",
        "Nahe Dörfer, Städte und Tagesausflüge, die den Weg lohnen, wenn ihr als Paar gemeinsam etwas Neues entdecken möchtet.",
        "Pueblos, ciudades y excursiones cercanas que compensan el trayecto cuando os apetece descubrir juntos un lugar nuevo.",
        "Dorpen, steden en dagtrips in de buurt die de reis waard zijn als jullie samen een nieuwe plek willen ontdekken.",
        "Närliggande byar, städer och dagsutflykter som är värda resan när ni vill upptäcka en ny plats tillsammans.",
      ),
    },
  ],
  hostEyebrow: text(
    "Our recommendations, first-hand",
    "Unsere Empfehlungen aus erster Hand",
    "Nuestras recomendaciones, de primera mano",
    "Onze aanbevelingen uit eigen ervaring",
    "Våra rekommendationer från egen erfarenhet",
  ),
  hostTitle: text(
    "Time spent in each place shapes every recommendation.",
    "Unsere Zeit vor Ort prägt jede Empfehlung.",
    "El tiempo que pasamos en cada lugar da forma a cada recomendación.",
    "Onze tijd ter plaatse vormt elke aanbeveling.",
    "Tiden på plats formar varje rekommendation.",
  ),
  hostParagraphs: {
    en: [
      "We have welcomed AMARA guests since May 2021 and regularly return to our stays in Frigiliana, Nerja and Tarifa. Our personal perspective grows from these stays and the time we spend in each destination. We verify opening hours, access rules and other changing details separately.",
      "That is why a beach tip also explains what it means for your day. From AMARA Playa, Torrecilla is about 200 metres away, so it works for a quick swim or a return near sunset. In Tarifa, we use the Mercadona opposite the apartment for everyday shopping and choose Pastelito or Bernal for bread — especially Bernal's Pan Macho. Details like these turn a list into local guidance.",
      "The private AMARA Experience follows the same principle for romantic restaurants, quieter beaches, walks, shared activities and day trips: we tell you what we know, why it may fit and what you should check before setting out.",
    ],
    de: [
      "Seit Mai 2021 empfangen wir Gäste bei AMARA und sind regelmäßig in unseren Unterkünften in Frigiliana, Nerja und Tarifa. Unsere persönliche Perspektive entsteht aus diesen Aufenthalten und der Zeit, die wir an jedem der drei Orte verbringen. Öffnungszeiten, Zufahrten und andere veränderliche Angaben prüfen wir separat.",
      "Darum erklärt ein Strandtipp auch, was er für euren Tag bedeutet: Von AMARA Playa liegt Torrecilla rund 200 Meter entfernt – gut für ein schnelles Bad oder einen zweiten Besuch gegen Sonnenuntergang. In Tarifa nutzen wir den Mercadona direkt gegenüber dem Apartment; Brot holen wir bei Pastelito oder Bernal, besonders gern Bernals Pan Macho. Solche Details machen aus einer Liste lokale Orientierung.",
      "Im privaten AMARA Experience Guide gilt dasselbe für romantische Restaurants, ruhigere Strände, Wege, gemeinsame Aktivitäten und Ausflüge: Wir sagen euch, was wir wissen, warum es passen könnte und was ihr vor dem Aufbruch noch prüfen solltet.",
    ],
    es: [
      "Recibimos a huéspedes de AMARA desde mayo de 2021 y volvemos con regularidad a nuestros alojamientos de Frigiliana, Nerja y Tarifa. Nuestra perspectiva personal nace de estas estancias y del tiempo que pasamos en cada destino. Comprobamos por separado los horarios, accesos y demás datos que cambian.",
      "Por eso una recomendación de playa explica también qué aporta al día. Torrecilla está a unos 200 metros de AMARA Playa, así que permite un baño rápido o volver cerca del atardecer. En Tarifa usamos el Mercadona frente al apartamento para la compra diaria y elegimos Pastelito o Bernal para el pan, especialmente el Pan Macho de Bernal. Esos detalles convierten una lista en orientación local.",
      "La AMARA Experience privada aplica el mismo criterio a restaurantes románticos, playas tranquilas, paseos, actividades para dos y excursiones: os contamos qué sabemos, por qué puede encajar y qué conviene comprobar antes de salir.",
    ],
    nl: [
      "Sinds mei 2021 ontvangen we gasten bij AMARA en verblijven we regelmatig in onze accommodaties in Frigiliana, Nerja en Tarifa. Ons persoonlijke perspectief komt voort uit deze verblijven en de tijd die we op elke bestemming doorbrengen. Openingstijden, toegangsregels en andere veranderlijke details controleren we apart.",
      "Daarom vertelt een strandtip ook wat die voor jullie dag betekent. Torrecilla ligt op ongeveer 200 meter van AMARA Playa, dus een snelle duik of terugkeer rond zonsondergang is eenvoudig. In Tarifa gebruiken we de Mercadona tegenover het appartement voor dagelijkse boodschappen en kiezen we Pastelito of Bernal voor brood, vooral Bernals Pan Macho. Zulke details maken van een lijst lokale begeleiding.",
      "De besloten AMARA Experience werkt volgens hetzelfde principe voor romantische restaurants, rustige stranden, wandelingen, activiteiten samen en uitstapjes: we vertellen wat we weten, waarom het kan passen en wat jullie voor vertrek nog moeten controleren.",
    ],
    sv: [
      "Vi har tagit emot AMARA-gäster sedan maj 2021 och återvänder regelbundet till våra boenden i Frigiliana, Nerja och Tarifa. Vårt personliga perspektiv växer fram ur vistelserna och tiden vi tillbringar på varje destination. Vi kontrollerar öppettider, tillträdesregler och andra uppgifter som ändras separat.",
      "Därför förklarar ett strandtips också vad platsen betyder för dagen. Torrecilla ligger omkring 200 meter från AMARA Playa, så ett snabbt dopp eller ett återbesök nära solnedgången är enkelt. I Tarifa använder vi Mercadona mittemot lägenheten för vardagsinköp och väljer Pastelito eller Bernal för bröd, särskilt Bernals Pan Macho. Sådana detaljer gör en lista till lokal vägledning.",
      "Den privata AMARA Experience följer samma princip för romantiska restauranger, lugnare stränder, promenader, gemensamma aktiviteter och utflykter: vi berättar vad vi vet, varför det kan passa och vad ni bör kontrollera innan ni ger er av.",
    ],
  } satisfies LocalizedTextList,
  hostAuthorName: "Robert Sebastian Böhmer",
  hostUpdated: text(
    "Editorially reviewed in September 2026",
    "Redaktionell geprüft im September 2026",
    "Revisado editorialmente en septiembre de 2026",
    "Redactioneel gecontroleerd in september 2026",
    "Redaktionellt granskat i september 2026",
  ),
  hostNote: text(
    "First-hand experience is identified as such; changing practical details are verified separately.",
    "Eigene Erfahrung kennzeichnen wir als solche; veränderliche praktische Angaben prüfen wir separat.",
    "Identificamos la experiencia propia como tal y comprobamos por separado los datos prácticos que pueden cambiar.",
    "Eigen ervaring benoemen we als zodanig; veranderlijke praktische informatie controleren we apart.",
    "Egna erfarenheter anges som sådana; praktiska uppgifter som kan ändras kontrolleras separat.",
  ),
  accessEyebrow: text(
    "Already booked directly?",
    "Schon direkt gebucht?",
    "¿Ya habéis reservado directamente?",
    "Al rechtstreeks geboekt?",
    "Har ni redan bokat direkt?",
  ),
  accessTitle: text(
    "Your private guide is ready here",
    "Euer privater Guide beginnt hier",
    "Vuestra guía privada empieza aquí",
    "Jullie privégids begint hier",
    "Er privata guide börjar här",
  ),
  accessGuideLabel: text(
    "AMARA Guest Guide",
    "AMARA Guest Guide",
    "Guía para huéspedes de AMARA",
    "AMARA-gastengids",
    "AMARA-gästguide",
  ),
  accessIntro: text(
    "Here you’ll find information about your accommodation, local essentials and our personal insider tips. All booked guests have access before and during their stay. Simply enter the first name on the booking and the arrival and departure dates.",
    "Hier findet ihr Informationen zu eurer Unterkunft, Wichtigem vor Ort und unseren persönlichen Insider-Tipps. Alle gebuchten Gäste haben vor und während ihres Aufenthalts Zugang. Gebt einfach den Vornamen eurer Buchung sowie das An- und Abreisedatum ein.",
    "Aquí encontraréis información sobre el alojamiento, lo esencial del lugar y nuestros consejos personales. Todos los huéspedes con reserva tienen acceso antes y durante su estancia. Introducid simplemente el nombre que figura en la reserva y las fechas de llegada y salida.",
    "Hier vinden jullie informatie over de accommodatie, praktische zaken ter plaatse en onze persoonlijke insidertips. Alle geboekte gasten hebben voor en tijdens hun verblijf toegang. Vul eenvoudig de voornaam op de boeking en de aankomst- en vertrekdatum in.",
    "Här hittar ni information om boendet, praktiska saker på plats och våra personliga insidertips. Alla bokade gäster har tillgång före och under vistelsen. Ange helt enkelt förnamnet i bokningen samt ankomst- och avresedatum.",
  ),
  accessLandingLabel: text(
    "Learn more about AMARA Experience",
    "Mehr über AMARA Experience",
    "Más sobre AMARA Experience",
    "Meer over AMARA Experience",
    "Läs mer om AMARA Experience",
  ),
  formTitle: text(
    "AMARA Experience",
    "AMARA Experience",
    "AMARA Experience",
    "AMARA Experience",
    "AMARA Experience",
  ),
  firstNameLabel: text(
    "First name on booking",
    "Vorname der Buchung",
    "Nombre de la reserva",
    "Voornaam op de boeking",
    "Förnamn i bokningen",
  ),
  arrivalLabel: text(
    "Arrival date",
    "Anreisedatum",
    "Fecha de llegada",
    "Aankomstdatum",
    "Ankomstdatum",
  ),
  departureLabel: text(
    "Departure date",
    "Abreisedatum",
    "Fecha de salida",
    "Vertrekdatum",
    "Avresedatum",
  ),
  chooseArrivalLabel: text(
    "Choose arrival date",
    "Anreisedatum wählen",
    "Elegir fecha de llegada",
    "Aankomstdatum kiezen",
    "Välj ankomstdatum",
  ),
  chooseDepartureLabel: text(
    "Choose departure date",
    "Abreisedatum wählen",
    "Elegir fecha de salida",
    "Vertrekdatum kiezen",
    "Välj avresedatum",
  ),
  datePickerTitle: text(
    "Choose your travel dates",
    "Eure Reisedaten auswählen",
    "Elegid vuestras fechas",
    "Kies jullie reisdata",
    "Välj era resedatum",
  ),
  datePickerHelp: text(
    "Choose the arrival date, then the departure date from your confirmation.",
    "Wählt zuerst das Anreisedatum und danach das Abreisedatum aus eurer Bestätigung.",
    "Elegid primero la fecha de llegada y después la fecha de salida de vuestra confirmación.",
    "Kies eerst de aankomstdatum en daarna de vertrekdatum uit jullie bevestiging.",
    "Välj först ankomstdatum och sedan avresedatum från er bekräftelse.",
  ),
  datePickerDepartureHelp: text(
    "Arrival selected. Now choose the departure date from your confirmation.",
    "Anreise gewählt. Wählt jetzt das Abreisedatum aus eurer Bestätigung.",
    "Llegada seleccionada. Elegid ahora la fecha de salida de vuestra confirmación.",
    "Aankomst gekozen. Kies nu de vertrekdatum uit jullie bevestiging.",
    "Ankomst vald. Välj nu avresedatum från er bekräftelse.",
  ),
  datePickerCompleteHelp: text(
    "Your travel dates are selected.",
    "Eure Reisedaten sind ausgewählt.",
    "Vuestras fechas están seleccionadas.",
    "Jullie reisdata zijn gekozen.",
    "Era resedatum är valda.",
  ),
  datePickerRequiredMessage: text(
    "Choose the arrival and departure dates from your confirmation.",
    "Wählt das Anreise- und Abreisedatum aus eurer Bestätigung.",
    "Elegid las fechas de llegada y salida de vuestra confirmación.",
    "Kies de aankomst- en vertrekdatum uit jullie bevestiging.",
    "Välj ankomst- och avresedatum från er bekräftelse.",
  ),
  previousMonthLabel: text(
    "Show previous month",
    "Vorherigen Monat anzeigen",
    "Mostrar el mes anterior",
    "Vorige maand tonen",
    "Visa föregående månad",
  ),
  nextMonthLabel: text(
    "Show next month",
    "Nächsten Monat anzeigen",
    "Mostrar el mes siguiente",
    "Volgende maand tonen",
    "Visa nästa månad",
  ),
  submitLabel: text(
    "Open AMARA Experience",
    "AMARA Experience öffnen",
    "Abrir AMARA Experience",
    "AMARA Experience openen",
    "Öppna AMARA Experience",
  ),
  pendingLabel: text(
    "Checking booking…",
    "Buchung wird geprüft…",
    "Comprobando la reserva…",
    "Boeking controleren…",
    "Kontrollerar bokningen…",
  ),
  deniedMessage: text(
    "We could not open the guide with these details. Check the booking confirmation or contact us if you need help.",
    "Mit diesen Angaben konnten wir den Guide nicht öffnen. Prüft bitte die Buchungsbestätigung oder meldet euch bei uns.",
    "No hemos podido abrir la guía con estos datos. Revisad la confirmación o contactadnos si necesitáis ayuda.",
    "Met deze gegevens konden we de gids niet openen. Controleer de bevestiging of neem contact met ons op.",
    "Vi kunde inte öppna guiden med de här uppgifterna. Kontrollera bekräftelsen eller kontakta oss om ni behöver hjälp.",
  ),
  unavailableMessage: text(
    "The private guide is not available right now. Please try again later.",
    "Der private Guide ist gerade nicht verfügbar. Bitte versucht es später noch einmal.",
    "La guía privada no está disponible ahora. Intentadlo de nuevo más tarde.",
    "De privégids is nu niet beschikbaar. Probeer het later opnieuw.",
    "Den privata guiden är inte tillgänglig just nu. Försök igen senare.",
  ),
  sessionEndedMessage: text(
    "Your guide session has ended. Enter the booking details again if the stay is still active.",
    "Eure Guide-Sitzung ist beendet. Gebt die Buchungsdaten erneut ein, falls der Aufenthalt noch aktiv ist.",
    "La sesión de la guía ha terminado. Volved a introducir los datos si la estancia sigue activa.",
    "Jullie gidssessie is beëindigd. Vul de boekingsgegevens opnieuw in als het verblijf nog actief is.",
    "Guidesessionen har avslutats. Ange bokningsuppgifterna igen om vistelsen fortfarande är aktiv.",
  ),
  privacyNote: text(
    "Used only to verify your booking and keep you signed in.",
    "Nur zur Buchungsprüfung und Anmeldung.",
    "Solo para verificar la reserva y mantener la sesión.",
    "Alleen voor boekingscontrole en aanmelding.",
    "Endast för bokningskontroll och inloggning.",
  ),
  closingTitle: text(
    "Time together in an AMARA Romantic Hideaway.",
    "Zeit für euch in einem AMARA Romantic Hideaway.",
    "Tiempo para vosotros en un Romantic Hideaway de AMARA.",
    "Tijd voor elkaar in een AMARA Romantic Hideaway.",
    "Tid tillsammans i ett AMARA Romantic Hideaway.",
  ),
  closingLead: text(
    "Book your Romantic Hideaway directly with AMARA. Once confirmed, your private AMARA Experience opens for the dates of your stay.",
    "Bucht euren Romantic Hideaway direkt bei AMARA. Nach der Bestätigung öffnet sich eure private AMARA Experience für die Reisedaten eures Aufenthalts.",
    "Reservad vuestro Romantic Hideaway directamente con AMARA. Una vez confirmado, vuestra AMARA Experience privada se abrirá para las fechas de la estancia.",
    "Boek jullie Romantic Hideaway rechtstreeks bij AMARA. Na bevestiging gaat jullie privé-AMARA Experience open voor de data van het verblijf.",
    "Boka ert Romantic Hideaway direkt med AMARA. Efter bekräftelsen öppnas er privata AMARA Experience för datumen för vistelsen.",
  ),
  availabilityLabel: text(
    "Check availability",
    "Verfügbarkeit prüfen",
    "Consultar disponibilidad",
    "Beschikbaarheid bekijken",
    "Kontrollera tillgänglighet",
  ),
};

export function getAmaraExperienceContent(lang: AmaraLanguage) {
  return resolveLocale(content, lang);
}
