import type { LocalizedText } from '../types/content';


/** One authored string in the five AMARA locales, in EN, DE, ES, NL, SV order. */
const l = (en: string, de: string, es: string, nl: string, sv: string): LocalizedText => ({ en, de, es, nl, sv });

export const BOOKING_STAY_TERMS_VERSION = '1.0';
export const BOOKING_STAY_TERMS_PUBLISHED_AT = '2026-08-17';

export interface BookingStayTermSection {
  id: string;
  title: string;
  paragraphs: string[];
  bullets?: string[];
}

interface BookingStayTermsLocale {
  seo: {
    title: string;
    description: string;
  };
  hero: {
    subtitle: string;
    title: string;
    lead: string;
  };
  identity: {
    heading: string;
    name: string;
    tradingAs: string;
    address: string;
    status: string;
    statusValue: string;
    email: string;
    country: string;
  };
  sections: BookingStayTermSection[];
  privacyLinkLabel: string;
  closingNote: string;
  versionNote: string;
}

export const bookingStayTermsContent = {
  seo: {
    title: l("Booking Terms | AMARA", "Buchungsbedingungen | AMARA", "Condiciones de reserva | AMARA", "Boekingsvoorwaarden | AMARA", "Bokningsvillkor | AMARA"),
    description: l("General booking terms for direct reservations with AMARA Lodging.", "Allgemeine Buchungsbedingungen für Direktbuchungen bei AMARA Lodging.", "Condiciones generales para las reservas directas con AMARA Lodging.", "Algemene boekingsvoorwaarden voor rechtstreekse boekingen bij AMARA Lodging.", "Allmänna bokningsvillkor för direktbokningar hos AMARA Lodging.")
  },
  hero: {
    subtitle: l("Clear and reliable.", "Klar und verlässlich.", "Claras y fiables.", "Helder en betrouwbaar.", "Tydliga och tillförlitliga."),
    title: l("Booking Terms", "Buchungsbedingungen", "Condiciones de reserva", "Boekingsvoorwaarden", "Bokningsvillkor"),
    lead: l("The general terms for **direct bookings with AMARA Lodging**.", "Die allgemeinen Bedingungen für **Direktbuchungen bei AMARA Lodging**.", "Las condiciones generales para las **reservas directas con AMARA Lodging**.", "De algemene voorwaarden voor **rechtstreekse boekingen bij AMARA Lodging**.", "De allmänna villkoren för **direktbokningar hos AMARA Lodging**.")
  },
  identity: {
    heading: l("Contracting party", "Vertragspartner", "Parte contratante", "Contractspartij", "Avtalspart"),
    name: l("Name", "Name", "Nombre", "Naam", "Namn"),
    tradingAs: l("Trading as", "Handelnd unter", "Nombre comercial", "Handelend onder de naam", "Verksam under namnet"),
    address: l("Address", "Anschrift", "Domicilio", "Adres", "Adress"),
    status: l("Status", "Status", "Condición", "Status", "Status"),
    statusValue: l("Private host – not registered in the commercial register", "Privater Gastgeber – nicht im Handelsregister eingetragen", "Anfitrión particular – no inscrito en el Registro Mercantil", "Particuliere verhuurder – niet ingeschreven in het handelsregister", "Privat värd – inte registrerad i handelsregistret"),
    email: l("Email", "E-Mail", "Correo electrónico", "E-mail", "E-post"),
    country: l("Spain", "Spanien", "España", "Spanje", "Spanien")
  },
  sections: [
    {
      id: "scope",
      title: l("1. Contracting Party and Scope", "1. Vertragspartner und Geltungsbereich", "1. Parte contratante y ámbito de aplicación", "1. Contractspartij en toepassingsgebied", "1. Avtalspart och tillämpningsområde"),
      paragraphs: [
        l("These Booking Terms govern short-term tourist accommodation provided by the contracting party identified on this page (“Host”) at the accommodation specified in the booking confirmation. AMARA Lodging is the Host’s trading name and is not a separate contracting entity.", "Diese Buchungsbedingungen gelten für die kurzfristige touristische Beherbergung durch den auf dieser Seite genannten Vertragspartner („Gastgeber“) in der Unterkunft, die in der Buchungsbestätigung bezeichnet ist. AMARA Lodging ist die geschäftliche Bezeichnung des Gastgebers und keine eigenständige Vertragspartei.", "Estas Condiciones de reserva regulan el alojamiento turístico de corta duración prestado por la parte contratante identificada en esta página (“Anfitrión”) en el alojamiento indicado en la confirmación de la reserva. AMARA Lodging es el nombre comercial del Anfitrión y no una entidad contratante independiente.", "Deze Boekingsvoorwaarden gelden voor toeristische accommodatie voor korte duur die door de op deze pagina vermelde contractspartij (“Host”) wordt aangeboden in de accommodatie die in de boekingsbevestiging staat. AMARA Lodging is de handelsnaam van de Host en geen afzonderlijke contractspartij.", "Dessa Bokningsvillkor gäller för kortvarigt turistboende som tillhandahålls av den avtalspart som anges på denna sida (“Värden”) i det boende som anges i bokningsbekräftelsen. AMARA Lodging är Värdens verksamhetsnamn och inte en separat avtalspart."),
        l("The person completing the reservation is the lead guest (“Guest”). The Guest confirms that the booking information is correct and is responsible for communicating the relevant terms and property rules to all accompanying guests.", "Die Person, welche die Reservierung abschließt, ist der buchende Hauptgast („Gast“). Der Gast bestätigt die Richtigkeit der Buchungsangaben und sorgt dafür, dass alle mitreisenden Personen die für sie maßgeblichen Bedingungen und Hausregeln kennen.", "La persona que completa la reserva es el huésped principal (“Huésped”). El Huésped confirma que los datos de la reserva son correctos y se responsabiliza de comunicar a todos sus acompañantes las condiciones y normas del alojamiento que les resulten aplicables.", "De persoon die de reservering voltooit, is de hoofdgast (“Gast”). De Gast bevestigt dat de boekingsgegevens juist zijn en zorgt ervoor dat alle medereizigers kennisnemen van de voor hen relevante voorwaarden en huisregels.", "Den person som slutför bokningen är huvudgästen (“Gästen”). Gästen bekräftar att bokningsuppgifterna är korrekta och ansvarar för att alla medresenärer får kännedom om de villkor och boenderegler som berör dem.")
      ]
    },
    {
      id: "contract-documents",
      title: l("2. Contract Documents and Formation", "2. Vertragsunterlagen und Vertragsschluss", "2. Documentos contractuales y formalización", "2. Contractstukken en totstandkoming", "2. Avtalshandlingar och avtalets ingående"),
      paragraphs: [
        l("The accommodation contract consists of these terms in the version referenced in the booking confirmation, the booking-specific information displayed before the final checkout action, the booking confirmation and any material property rules made available before booking.", "Der Beherbergungsvertrag besteht aus der in der Buchungsbestätigung genannten Version dieser Bedingungen, den vor der abschließenden Buchungshandlung im Checkout angezeigten Buchungsdetails, der Buchungsbestätigung und den wesentlichen unterkunftsspezifischen Regeln, die vor der Buchung bereitgestellt wurden.", "El contrato de alojamiento se compone de estas condiciones en la versión citada en la confirmación, la información específica mostrada antes de la acción final del proceso de reserva, la confirmación de la reserva y las normas esenciales del alojamiento facilitadas antes de reservar.", "De accommodatieovereenkomst bestaat uit deze voorwaarden in de versie waarnaar de boekingsbevestiging verwijst, de boekingsspecifieke informatie die vóór de laatste boekingshandeling wordt getoond, de boekingsbevestiging en belangrijke accommodatieregels die vóór het boeken beschikbaar zijn gesteld.", "Boendeavtalet består av dessa villkor i den version som anges i bokningsbekräftelsen, de bokningsspecifika uppgifter som visas före den sista bokningsåtgärden, bokningsbekräftelsen och viktiga boenderegler som gjorts tillgängliga före bokningen."),
        l("The contract is formed when the Host issues the booking confirmation after the Guest has completed checkout and any payment or payment authorisation then due has been successfully processed. A mere technical receipt message is not a booking confirmation unless it is expressly described as such.", "Der Vertrag kommt zustande, sobald der Gastgeber nach Abschluss des Checkouts eine Buchungsbestätigung versendet und eine zu diesem Zeitpunkt fällige Zahlung oder Zahlungsautorisierung erfolgreich verarbeitet wurde. Eine rein technische Eingangsmitteilung ist nur dann eine Buchungsbestätigung, wenn sie ausdrücklich so bezeichnet ist.", "El contrato se formaliza cuando el Anfitrión envía la confirmación después de que el Huésped haya completado el proceso de reserva y se haya procesado correctamente cualquier pago o autorización de pago exigible en ese momento. Un simple acuse técnico no constituye confirmación salvo que se identifique expresamente como tal.", "De overeenkomst komt tot stand wanneer de Host de boekingsbevestiging verstuurt nadat de Gast het boekingsproces heeft voltooid en een op dat moment verschuldigde betaling of betaalautorisatie succesvol is verwerkt. Een puur technische ontvangstmelding is alleen een boekingsbevestiging wanneer deze uitdrukkelijk zo wordt genoemd.", "Avtalet ingås när Värden skickar bokningsbekräftelsen efter att Gästen har slutfört bokningsprocessen och en betalning eller betalningsauktorisation som då förfaller har behandlats korrekt. Ett rent tekniskt mottagningsmeddelande är endast en bokningsbekräftelse om det uttryckligen anges som en sådan."),
        l("Mandatory law takes priority. For booking-specific commercial details, the booking confirmation takes priority over these general terms; these terms govern all remaining matters.", "Zwingendes Recht hat Vorrang. Für die wirtschaftlichen Einzelheiten der konkreten Buchung geht die Buchungsbestätigung diesen allgemeinen Bedingungen vor; im Übrigen gelten diese Bedingungen.", "La normativa imperativa prevalece. Para los detalles económicos específicos, prevalece la confirmación de la reserva; estas condiciones rigen todas las demás cuestiones.", "Dwingend recht heeft voorrang. Voor de commerciële gegevens van de concrete boeking heeft de boekingsbevestiging voorrang op deze algemene voorwaarden; voor alle overige onderwerpen gelden deze voorwaarden.", "Tvingande lag har företräde. För den konkreta bokningens kommersiella uppgifter har bokningsbekräftelsen företräde framför dessa allmänna villkor; i övrigt gäller dessa villkor.")
      ]
    },
    {
      id: "booking-details",
      title: l("3. Booking Confirmation", "3. Buchungsbestätigung", "3. Confirmación de la reserva", "3. Boekingsbevestiging", "3. Bokningsbekräftelse"),
      paragraphs: [
        l("Before the Guest completes the booking, the price, payment and cancellation terms for the selected accommodation and rate are displayed. The booking confirmation records the agreed accommodation, travel dates, guest count, total price and the terms that apply to that reservation in a form the Guest can retain.", "Vor Abschluss der Buchung werden die Preis-, Zahlungs- und Stornierungsbedingungen für die gewählte Unterkunft und den gewählten Tarif angezeigt. Die Buchungsbestätigung hält die vereinbarte Unterkunft, die Reisedaten, die Gästezahl, den Gesamtpreis und die für diese Reservierung geltenden Bedingungen in einer Form fest, die der Gast dauerhaft speichern kann.", "Antes de completar la reserva se muestran las condiciones de precio, pago y cancelación aplicables al alojamiento y a la tarifa seleccionados. La confirmación recoge el alojamiento acordado, las fechas, el número de huéspedes, el precio total y las condiciones aplicables a esa reserva en un formato que el Huésped puede conservar.", "Voordat de Gast de boeking voltooit, worden de prijs-, betaal- en annuleringsvoorwaarden voor de gekozen accommodatie en het gekozen tarief getoond. De boekingsbevestiging legt de overeengekomen accommodatie, reisdata, het aantal gasten, de totaalprijs en de voorwaarden voor die reservering vast in een vorm die de Gast kan bewaren.", "Innan Gästen slutför bokningen visas de pris-, betalnings- och avbokningsvillkor som gäller för valt boende och vald prisplan. Bokningsbekräftelsen anger det avtalade boendet, resedatumen, antalet gäster, totalpriset och villkoren för bokningen i en form som Gästen kan spara.")
      ]
    },
    {
      id: "payment",
      title: l("4. Price and Payment", "4. Preis und Zahlung", "4. Precio y pago", "4. Prijs en betaling", "4. Pris och betalning"),
      paragraphs: [
        l("The total price, any advance payment, remaining balance and their due dates are those displayed in checkout and repeated in the booking confirmation. Optional extras are charged only when expressly selected or subsequently agreed.", "Gesamtpreis, Anzahlung, Restbetrag und jeweilige Fälligkeit ergeben sich aus dem Checkout und werden in der Buchungsbestätigung wiedergegeben. Optionale Zusatzleistungen werden nur berechnet, wenn sie ausdrücklich gewählt oder nachträglich vereinbart wurden.", "El precio total, cualquier anticipo, el saldo restante y sus vencimientos son los mostrados durante la reserva y reiterados en la confirmación. Los extras opcionales solo se cobran cuando se hayan seleccionado expresamente o acordado posteriormente.", "De totaalprijs, eventuele aanbetaling, het resterende saldo en de vervaldata zijn de bedragen en termijnen die bij het boeken worden getoond en in de boekingsbevestiging worden herhaald. Optionele extra’s worden alleen berekend wanneer ze uitdrukkelijk zijn gekozen of later zijn overeengekomen.", "Totalpris, eventuell förskottsbetalning, återstående belopp och förfallodagar är de som visas vid bokningen och upprepas i bokningsbekräftelsen. Valfria tillägg debiteras endast om de uttryckligen har valts eller senare avtalats."),
        l("Payments are processed through the official AMARA booking environment and the payment providers offered there. If an amount is not received when due, the Host may take the measures stated in the confirmed payment terms and permitted by law, including cancellation after appropriate notice where required.", "Zahlungen werden über die offizielle AMARA-Buchungsumgebung und die dort angebotenen Zahlungsdienstleister abgewickelt. Geht ein Betrag nicht fristgerecht ein, kann der Gastgeber die in den bestätigten Zahlungsbedingungen vorgesehenen und gesetzlich zulässigen Maßnahmen ergreifen – soweit erforderlich nach angemessener Mitteilung auch die Stornierung.", "Los pagos se procesan a través del entorno oficial de reservas de AMARA y de los proveedores de pago ofrecidos en él. Si un importe no se recibe a su vencimiento, el Anfitrión podrá adoptar las medidas previstas en las condiciones de pago confirmadas y permitidas por la ley, incluida la cancelación previa notificación adecuada cuando proceda.", "Betalingen worden verwerkt via de officiële boekingsomgeving van AMARA en de daar aangeboden betaaldienstverleners. Als een bedrag niet op tijd wordt ontvangen, kan de Host de in de bevestigde betaalvoorwaarden genoemde en wettelijk toegestane maatregelen nemen, waaronder annulering na passende kennisgeving wanneer dat vereist is.", "Betalningar behandlas via AMARA:s officiella bokningsmiljö och de betalningsleverantörer som erbjuds där. Om ett belopp inte tas emot i tid får Värden vidta de åtgärder som anges i de bekräftade betalningsvillkoren och som lagen tillåter, inklusive avbokning efter lämpligt meddelande när det krävs.")
      ]
    },
    {
      id: "cancellation",
      title: l("5. Cancellation, Changes, No-show and Early Departure", "5. Stornierung, Änderungen, Nichterscheinen und vorzeitige Abreise", "5. Cancelación, cambios, no presentación y salida anticipada", "5. Annulering, wijzigingen, niet verschijnen en vroegtijdig vertrek", "5. Avbokning, ändringar, utebliven ankomst och förtida avresa"),
      paragraphs: [
        l("The cancellation and refund policy shown for the selected rate immediately before booking and repeated in the booking confirmation is binding for that booking. It also states the consequences of a no-show or early departure.", "Für die jeweilige Buchung gilt die Stornierungs- und Erstattungsregel, die für den gewählten Tarif unmittelbar vor dem Buchungsabschluss angezeigt und in der Buchungsbestätigung wiedergegeben wird. Dort sind auch die Folgen eines Nichterscheinens oder einer vorzeitigen Abreise geregelt.", "La política de cancelación y reembolso mostrada para la tarifa seleccionada inmediatamente antes de reservar y repetida en la confirmación es vinculante para esa reserva. También determina las consecuencias de la no presentación o de una salida anticipada.", "Het annulerings- en restitutiebeleid dat voor het gekozen tarief direct vóór het boeken wordt getoond en in de bevestiging wordt herhaald, is bindend voor die boeking. Het bepaalt ook de gevolgen van niet verschijnen of vroegtijdig vertrek.", "Den avboknings- och återbetalningspolicy som visas för den valda prisplanen omedelbart före bokningen och upprepas i bekräftelsen är bindande för bokningen. Den anger även följderna av utebliven ankomst eller förtida avresa."),
        l("A cancellation must be sent through the channel stated in the confirmation and takes effect when received. A requested change of dates, accommodation or guest count is effective only after the Host confirms it; changed prices or conditions may apply.", "Eine Stornierung ist über den in der Bestätigung genannten Kontaktweg zu übermitteln und wird mit ihrem Eingang wirksam. Eine gewünschte Änderung von Reisedaten, Unterkunft oder Gästezahl gilt erst nach Bestätigung durch den Gastgeber; geänderte Preise oder Bedingungen können zur Anwendung kommen.", "La cancelación deberá comunicarse por el canal indicado en la confirmación y será efectiva cuando se reciba. Una solicitud de cambio de fechas, alojamiento o número de huéspedes solo será efectiva tras su confirmación por el Anfitrión; podrán aplicarse precios o condiciones diferentes.", "Een annulering moet via het in de bevestiging genoemde kanaal worden verstuurd en wordt van kracht bij ontvangst. Een verzoek tot wijziging van data, accommodatie of gastenaantal geldt pas nadat de Host dit heeft bevestigd; gewijzigde prijzen of voorwaarden kunnen van toepassing zijn.", "En avbokning ska skickas via den kanal som anges i bekräftelsen och gäller när den har tagits emot. En begäran om ändrade datum, annat boende eller ändrat antal gäster gäller först när Värden har bekräftat den; ändrade priser eller villkor kan tillämpas."),
        l("If the Host cancels a confirmed stay, amounts paid for accommodation not provided will be refunded. This does not limit any further mandatory rights of the Guest.", "Storniert der Gastgeber einen bestätigten Aufenthalt, werden die für nicht erbrachte Beherbergungsleistungen gezahlten Beträge erstattet. Weitergehende zwingende Rechte des Gastes bleiben unberührt.", "Si el Anfitrión cancela una estancia confirmada, se reembolsarán los importes pagados por el alojamiento no prestado. Esto no limita otros derechos imperativos del Huésped.", "Als de Host een bevestigde boeking annuleert, worden bedragen voor niet geleverde accommodatie terugbetaald. Dit beperkt geen verdere dwingende rechten van de Gast.", "Om Värden avbokar en bekräftad vistelse återbetalas belopp som betalats för boende som inte tillhandahålls. Detta begränsar inte Gästens ytterligare tvingande rättigheter.")
      ]
    },
    {
      id: "arrival",
      title: l("6. Arrival, Departure and Guest Registration", "6. Anreise, Abreise und Gästeregistrierung", "6. Entrada, salida y registro de huéspedes", "6. Aankomst, vertrek en gastenregistratie", "6. Ankomst, avresa och gästregistrering"),
      paragraphs: [
        l("The applicable check-in and check-out times are stated in the booking confirmation. Early arrival or late departure requires prior confirmation and may carry a fee only where that fee was disclosed and agreed.", "Die geltenden Check-in- und Check-out-Zeiten stehen in der Buchungsbestätigung. Eine frühere Anreise oder spätere Abreise bedarf der vorherigen Bestätigung und kann nur dann kostenpflichtig sein, wenn die Gebühr offengelegt und vereinbart wurde.", "Los horarios aplicables de entrada y salida constan en la confirmación. Una entrada anticipada o una salida tardía requieren confirmación previa y solo podrán generar un cargo si este fue informado y aceptado.", "De geldende in- en uitchecktijden staan in de boekingsbevestiging. Vroeg aankomen of later vertrekken vereist voorafgaande bevestiging en kan alleen tegen betaling zijn wanneer die vergoeding vooraf is meegedeeld en overeengekomen.", "Gällande in- och utcheckningstider anges i bokningsbekräftelsen. Tidig ankomst eller sen avresa kräver förhandsgodkännande och kan endast medföra en avgift om avgiften har upplysts om och godkänts."),
        l("Guests must provide the identification and registration information required by Spanish law. Digital or contactless check-in does not remove that obligation. The Host will provide the access and operational information needed for the booked accommodation.", "Die Gäste müssen die nach spanischem Recht erforderlichen Identitäts- und Meldedaten zur Verfügung stellen. Auch ein digitaler oder kontaktloser Check-in lässt diese Verpflichtung unberührt. Der Gastgeber stellt die für den Zugang und die Nutzung der gebuchten Unterkunft erforderlichen Informationen bereit.", "Los huéspedes deberán facilitar los datos de identificación y registro exigidos por la legislación española. El registro digital o la entrada sin contacto no eliminan esta obligación. El Anfitrión facilitará la información necesaria para acceder al alojamiento reservado y utilizarlo correctamente.", "Gasten moeten de identificatie- en registratiegegevens verstrekken die volgens de Spaanse wet verplicht zijn. Digitaal of contactloos inchecken verandert deze verplichting niet. De Host verstrekt de informatie die nodig is voor toegang tot en correct gebruik van de geboekte accommodatie.", "Gäster måste lämna de identitets- och registreringsuppgifter som krävs enligt spansk lag. Digital eller kontaktlös incheckning tar inte bort denna skyldighet. Värden tillhandahåller den information som behövs för tillträde till och korrekt användning av det bokade boendet.")
      ]
    },
    {
      id: "occupancy",
      title: l("7. Occupancy and Permitted Use", "7. Belegung und erlaubte Nutzung", "7. Ocupación y uso permitido", "7. Bezetting en toegestaan gebruik", "7. Beläggning och tillåten användning"),
      paragraphs: [
        l("Only the number of guests confirmed in the booking may stay overnight. Additional overnight guests require prior approval and may not exceed the licensed capacity.", "Übernachten dürfen nur die in der Buchung bestätigten Gäste. Weitere Übernachtungsgäste bedürfen der vorherigen Zustimmung und dürfen die genehmigte Höchstbelegung nicht überschreiten.", "Solo podrán pernoctar los huéspedes confirmados en la reserva. Cualquier huésped adicional requiere autorización previa y nunca podrá superarse la capacidad autorizada.", "Alleen het in de boeking bevestigde aantal gasten mag overnachten. Extra overnachtende gasten vereisen voorafgaande toestemming en de vergunde capaciteit mag nooit worden overschreden.", "Endast det antal gäster som bekräftats i bokningen får övernatta. Ytterligare övernattande gäster kräver förhandsgodkännande och den licensierade maxkapaciteten får aldrig överskridas."),
        l("The accommodation is provided solely for temporary tourist accommodation. Subletting, unlawful activity, commercial use, parties, events or professional productions are not permitted unless expressly agreed in writing. The lead Guest remains responsible for accompanying guests, visitors and minors under their supervision.", "Die Unterkunft wird ausschließlich zur vorübergehenden touristischen Beherbergung überlassen. Untervermietung, rechtswidrige oder gewerbliche Nutzung, Feiern, Veranstaltungen oder professionelle Produktionen sind ohne ausdrückliche schriftliche Vereinbarung nicht gestattet. Der Hauptgast bleibt für Mitreisende, Besucher und beaufsichtigte Minderjährige verantwortlich.", "El alojamiento se ofrece exclusivamente para una estancia turística temporal. No se permiten el subarriendo, las actividades ilícitas, el uso comercial, las fiestas, los eventos ni las producciones profesionales salvo acuerdo expreso por escrito. El Huésped principal responde de sus acompañantes, visitantes y menores bajo su supervisión.", "De accommodatie wordt uitsluitend voor tijdelijk toeristisch verblijf aangeboden. Onderverhuur, onwettige activiteiten, commercieel gebruik, feesten, evenementen of professionele producties zijn niet toegestaan zonder uitdrukkelijke schriftelijke afspraak. De hoofdgast blijft verantwoordelijk voor medegasten, bezoekers en minderjarigen onder zijn of haar toezicht.", "Boendet tillhandahålls enbart för tillfällig turistvistelse. Andrahandsuthyrning, olaglig verksamhet, kommersiell användning, fester, evenemang eller professionella produktioner är inte tillåtna utan uttrycklig skriftlig överenskommelse. Huvudgästen ansvarar för medresenärer, besökare och minderåriga under sin tillsyn.")
      ]
    },
    {
      id: "house-rules",
      title: l("8. House Rules, Quiet, Smoking and Pets", "8. Hausregeln, Ruhe, Rauchen und Haustiere", "8. Normas, descanso, tabaco y mascotas", "8. Huisregels, rust, roken en huisdieren", "8. Ordningsregler, hänsyn, rökning och husdjur"),
      paragraphs: [
        l("Guests must respect neighbours, shared areas, property-specific quiet hours and the material house rules shown before booking or included with the confirmation. Operational instructions may also be provided at or before arrival.", "Die Gäste nehmen Rücksicht auf Nachbarn und Gemeinschaftsflächen und beachten die unterkunftsspezifischen Ruhezeiten sowie die wesentlichen Hausregeln, die vor der Buchung oder mit der Bestätigung bereitgestellt werden. Organisatorische Hinweise können zusätzlich vor oder bei der Anreise übermittelt werden.", "Los huéspedes respetarán al vecindario y las zonas comunes, los horarios de descanso específicos y las normas esenciales comunicadas antes de la reserva o incluidas con la confirmación. También podrán facilitarse instrucciones operativas antes de la llegada o en ese momento.", "Gasten respecteren buren en gemeenschappelijke ruimten, accommodatiespecifieke rusttijden en de belangrijke huisregels die vóór het boeken of bij de bevestiging zijn verstrekt. Praktische instructies kunnen ook vóór of bij aankomst worden gegeven.", "Gäster ska visa hänsyn till grannar och gemensamma utrymmen och följa boendets särskilda tystnadstider och viktiga ordningsregler som har lämnats före bokningen eller tillsammans med bekräftelsen. Praktiska instruktioner kan även ges före eller vid ankomst."),
        l("Smoking inside is not permitted. Pets are not permitted in any AMARA Lodging accommodation. Mandatory rules concerning recognised assistance animals remain unaffected.", "Das Rauchen in Innenräumen ist nicht gestattet. Haustiere sind in keiner Unterkunft von AMARA Lodging erlaubt. Zwingende Vorschriften zu anerkannten Assistenzhunden bleiben unberührt.", "No está permitido fumar en el interior. No se admiten mascotas en ningún alojamiento de AMARA Lodging. Las normas imperativas relativas a perros de asistencia reconocidos no se ven afectadas.", "Binnen roken is niet toegestaan. Huisdieren zijn in geen enkele AMARA Lodging-accommodatie toegestaan. Dwingende regels voor erkende assistentiedieren blijven onverminderd gelden.", "Rökning inomhus är inte tillåten. Husdjur är inte tillåtna i något av AMARA Lodgings boenden. Tvingande regler om erkända assistansdjur påverkas inte."),
        l("For a serious or repeated breach, the Host may take reasonable and proportionate measures permitted by law, including requiring the conduct to stop or, where justified, ending the stay. Any refund consequence is determined by the confirmed booking conditions and mandatory law; it is not automatically forfeited.", "Bei einem schwerwiegenden oder wiederholten Verstoß kann der Gastgeber angemessene und verhältnismäßige, gesetzlich zulässige Maßnahmen ergreifen. Dazu kann bei entsprechender Rechtfertigung auch die Beendigung des Aufenthalts gehören. Ob eine Erstattung erfolgt, richtet sich nach den bestätigten Buchungsbedingungen und zwingendem Recht; sie entfällt nicht automatisch.", "Ante un incumplimiento grave o reiterado, el Anfitrión podrá adoptar medidas razonables, proporcionadas y permitidas por la ley, incluida la finalización de la estancia cuando esté justificada. Las consecuencias sobre un posible reembolso se determinan conforme a las condiciones confirmadas y la ley imperativa; el reembolso no se pierde automáticamente.", "Bij een ernstige of herhaalde overtreding kan de Host redelijke, evenredige en wettelijk toegestane maatregelen nemen, waaronder beëindiging van het verblijf wanneer dat gerechtvaardigd is. De gevolgen voor een eventuele terugbetaling volgen uit de bevestigde voorwaarden en het dwingende recht; een terugbetaling vervalt niet automatisch.", "Vid en allvarlig eller upprepad överträdelse får Värden vidta rimliga, proportionerliga och lagliga åtgärder, inklusive att avsluta vistelsen när det är motiverat. Konsekvenserna för eventuell återbetalning bestäms av de bekräftade villkoren och tvingande lag; återbetalningen förverkas inte automatiskt.")
      ]
    },
    {
      id: "care-damage",
      title: l("9. Care, Damage, Keys and Deposits", "9. Sorgfalt, Schäden, Schlüssel und Kautionen", "9. Cuidado, daños, llaves y depósitos", "9. Zorg, schade, sleutels en borg", "9. Omsorg, skador, nycklar och deposition"),
      paragraphs: [
        l("Guests must treat the accommodation, furnishings and equipment with reasonable care and report damage, defects or lost access items promptly so that avoidable loss can be limited.", "Die Gäste behandeln Unterkunft, Einrichtung und Ausstattung mit angemessener Sorgfalt und melden Schäden, Mängel oder verlorene Zugangsmittel unverzüglich, damit vermeidbare Folgeschäden begrenzt werden können.", "Los huéspedes tratarán con el debido cuidado el alojamiento, el mobiliario y el equipamiento y comunicarán sin demora cualquier daño, defecto o pérdida de medios de acceso para limitar perjuicios evitables.", "Gasten behandelen de accommodatie, inrichting en apparatuur met redelijke zorg en melden schade, gebreken of verloren toegangsmiddelen onmiddellijk, zodat vermijdbare vervolgschade kan worden beperkt.", "Gäster ska behandla boendet, inredningen och utrustningen med rimlig omsorg och omedelbart rapportera skador, fel eller förlorade tillträdesmedel så att undvikbara följdskador kan begränsas."),
        l("To the extent provided by applicable law, the Guest is responsible for damage caused intentionally or negligently, missing keys or equipment, and reasonable additional cleaning required beyond normal use. Normal wear and tear is not chargeable.", "Soweit gesetzlich vorgesehen, haftet der Gast für vorsätzlich oder fahrlässig verursachte Schäden, verlorene Schlüssel oder Ausstattungsgegenstände sowie angemessene zusätzliche Reinigungskosten, die über die normale Nutzung hinausgehen. Normale Abnutzung wird nicht berechnet.", "En la medida prevista por la ley aplicable, el Huésped responde de los daños causados dolosa o negligentemente, de las llaves o equipos perdidos y de los costes razonables de limpieza adicional que exceda el uso normal. El desgaste ordinario no se cobra.", "Voor zover het toepasselijke recht dat bepaalt, is de Gast verantwoordelijk voor opzettelijk of door nalatigheid veroorzaakte schade, verloren sleutels of apparatuur en redelijke extra schoonmaakkosten boven normaal gebruik. Normale slijtage wordt niet in rekening gebracht.", "I den utsträckning tillämplig lag föreskriver ansvarar Gästen för skador som orsakats uppsåtligen eller genom vårdslöshet, förlorade nycklar eller utrustning samt rimliga kostnader för extra städning utöver normalt bruk. Normalt slitage debiteras inte."),
        l("Before seeking payment, the Host will provide a comprehensible description and reasonable evidence of the loss and give the Guest an opportunity to respond. A security deposit or payment authorisation applies only if it was shown before booking and recorded in the confirmation.", "Bevor eine Zahlung verlangt wird, legt der Gastgeber den Schaden nachvollziehbar dar, stellt angemessene Nachweise bereit und gibt dem Gast Gelegenheit zur Stellungnahme. Eine Kaution oder Zahlungsautorisierung gilt nur, wenn sie vor der Buchung angezeigt und in der Bestätigung festgehalten wurde.", "Antes de exigir un pago, el Anfitrión facilitará una descripción comprensible y pruebas razonables del perjuicio y dará al Huésped la oportunidad de responder. Solo se aplicará un depósito o autorización de pago si se mostró antes de reservar y quedó recogido en la confirmación.", "Voordat betaling wordt gevraagd, geeft de Host een begrijpelijke omschrijving en redelijk bewijs van het verlies en krijgt de Gast gelegenheid om te reageren. Een borg of betaalautorisatie geldt alleen wanneer deze vóór het boeken werd getoond en in de bevestiging is vastgelegd.", "Innan betalning begärs lämnar Värden en begriplig beskrivning och rimliga bevis på förlusten och ger Gästen möjlighet att svara. En deposition eller betalningsauktorisation gäller endast om den visades före bokningen och dokumenterades i bekräftelsen.")
      ]
    },
    {
      id: "safety-liability",
      title: l("10. Safety and Liability", "10. Sicherheit und Haftung", "10. Seguridad y responsabilidad", "10. Veiligheid en aansprakelijkheid", "10. Säkerhet och ansvar"),
      paragraphs: [
        l("The Host will provide the accommodation as confirmed and is liable in accordance with applicable law. Nothing in these terms excludes or limits liability or consumer rights where exclusion or limitation is not legally permitted.", "Der Gastgeber stellt die Unterkunft wie bestätigt zur Verfügung und haftet nach den anwendbaren gesetzlichen Vorschriften. Diese Bedingungen schließen keine Haftung und keine Verbraucherrechte aus oder beschränken sie, soweit ein Ausschluss oder eine Beschränkung gesetzlich unzulässig ist.", "El Anfitrión facilitará el alojamiento según lo confirmado y responderá conforme a la legislación aplicable. Estas condiciones no excluyen ni limitan responsabilidades o derechos de los consumidores cuando la ley no permita tal exclusión o limitación.", "De Host stelt de accommodatie beschikbaar zoals bevestigd en is aansprakelijk volgens het toepasselijke recht. Niets in deze voorwaarden sluit aansprakelijkheid of consumentenrechten uit of beperkt deze wanneer dat wettelijk niet is toegestaan.", "Värden tillhandahåller boendet enligt bekräftelsen och ansvarar i enlighet med tillämplig lag. Inget i dessa villkor utesluter eller begränsar ansvar eller konsumenträttigheter när ett sådant undantag eller en sådan begränsning inte är tillåten enligt lag."),
        l("Guests must use stairs, terraces, balconies, pools, appliances and other facilities with reasonable care and follow safety and operating instructions. The Host is responsible for loss of or damage to personal belongings only where responsibility arises under applicable law.", "Treppen, Terrassen, Balkone, Pools, Geräte und andere Einrichtungen sind mit angemessener Sorgfalt und unter Beachtung der Sicherheits- und Bedienhinweise zu nutzen. Für Verlust oder Beschädigung persönlicher Gegenstände haftet der Gastgeber nur, soweit sich eine Verantwortlichkeit aus dem anwendbaren Recht ergibt.", "Los huéspedes utilizarán escaleras, terrazas, balcones, piscinas, aparatos y demás instalaciones con la debida precaución y siguiendo las indicaciones de seguridad y uso. El Anfitrión solo responde de la pérdida o daño de objetos personales cuando así resulte de la legislación aplicable.", "Gasten gebruiken trappen, terrassen, balkons, zwembaden, apparaten en andere voorzieningen met redelijke zorg en volgen veiligheids- en bedieningsinstructies. De Host is alleen verantwoordelijk voor verlies van of schade aan persoonlijke bezittingen wanneer die verantwoordelijkheid uit het toepasselijke recht voortvloeit.", "Gäster ska använda trappor, terrasser, balkonger, pooler, apparater och andra faciliteter med rimlig försiktighet och följa säkerhets- och användningsinstruktioner. Värden ansvarar för förlust av eller skada på personliga tillhörigheter endast när ansvar följer av tillämplig lag."),
        l("Travel and health insurance appropriate to the Guest’s circumstances is recommended but does not replace the Host’s legal obligations.", "Eine den persönlichen Umständen entsprechende Reise- und Krankenversicherung wird empfohlen, ersetzt jedoch nicht die gesetzlichen Pflichten des Gastgebers.", "Se recomienda contratar un seguro de viaje y salud adecuado a las circunstancias personales, sin que ello sustituya las obligaciones legales del Anfitrión.", "Een reis- en ziektekostenverzekering die past bij de persoonlijke omstandigheden van de Gast wordt aanbevolen, maar vervangt de wettelijke verplichtingen van de Host niet.", "En rese- och sjukförsäkring som passar Gästens personliga omständigheter rekommenderas, men ersätter inte Värdens rättsliga skyldigheter.")
      ]
    },
    {
      id: "exceptional-events",
      title: l("11. Events Outside Reasonable Control", "11. Ereignisse außerhalb des zumutbaren Einflussbereichs", "11. Acontecimientos fuera del control razonable", "11. Gebeurtenissen buiten redelijke controle", "11. Händelser utanför rimlig kontroll"),
      paragraphs: [
        l("If an exceptional and unavoidable event affects performance, the parties will notify each other promptly and take reasonable steps to limit its consequences. The rights and obligations of both parties are determined by mandatory law and the confirmed booking conditions.", "Beeinträchtigt ein außergewöhnliches und unvermeidbares Ereignis die Vertragserfüllung, informieren sich die Parteien unverzüglich und ergreifen angemessene Maßnahmen, um die Folgen zu begrenzen. Rechte und Pflichten beider Parteien bestimmen sich nach zwingendem Recht und den bestätigten Buchungsbedingungen.", "Si un acontecimiento excepcional e inevitable afecta al cumplimiento, las partes se informarán sin demora y adoptarán medidas razonables para limitar sus consecuencias. Los derechos y obligaciones se determinarán conforme a la legislación imperativa y a las condiciones confirmadas de la reserva.", "Als een uitzonderlijke en onvermijdelijke gebeurtenis de uitvoering beïnvloedt, informeren de partijen elkaar onmiddellijk en nemen zij redelijke maatregelen om de gevolgen te beperken. De rechten en verplichtingen van beide partijen worden bepaald door dwingend recht en de bevestigde boekingsvoorwaarden.", "Om en exceptionell och oundviklig händelse påverkar fullgörandet ska parterna informera varandra omgående och vidta rimliga åtgärder för att begränsa följderna. Båda parters rättigheter och skyldigheter bestäms av tvingande lag och de bekräftade bokningsvillkoren."),
        l("A temporary interruption or external event does not automatically remove either party’s rights. Any refund, alternative accommodation or other remedy depends on the circumstances and the law applicable to the booking.", "Eine vorübergehende Unterbrechung oder ein externes Ereignis beseitigt die Rechte einer Partei nicht automatisch. Ob Erstattung, Ersatzunterkunft oder ein anderer Ausgleich geschuldet ist, hängt von den Umständen und dem auf die Buchung anwendbaren Recht ab.", "Una interrupción temporal o un acontecimiento externo no elimina automáticamente los derechos de ninguna de las partes. El reembolso, alojamiento alternativo u otra solución dependerán de las circunstancias y de la normativa aplicable a la reserva.", "Een tijdelijke onderbreking of externe gebeurtenis neemt de rechten van geen van beide partijen automatisch weg. Een terugbetaling, alternatieve accommodatie of andere oplossing hangt af van de omstandigheden en het recht dat op de boeking van toepassing is.", "Ett tillfälligt avbrott eller en extern händelse tar inte automatiskt bort någon parts rättigheter. Återbetalning, alternativt boende eller annan gottgörelse beror på omständigheterna och den lag som gäller för bokningen.")
      ]
    },
    {
      id: "consumer-law",
      title: l("12. Consumer Rights, Applicable Law and Disputes", "12. Verbraucherrechte, anwendbares Recht und Streitigkeiten", "12. Derechos de consumo, legislación aplicable y conflictos", "12. Consumentenrechten, toepasselijk recht en geschillen", "12. Konsumenträttigheter, tillämplig lag och tvister"),
      paragraphs: [
        l("Spanish law applies, including the applicable Andalusian tourism and consumer rules. A consumer does not lose mandatory protection granted by the law that would otherwise apply to them.", "Es gilt spanisches Recht einschließlich der einschlägigen andalusischen Tourismus- und Verbrauchervorschriften. Zwingender Verbraucherschutz, der ohne diese Rechtswahl anwendbar wäre, wird dadurch nicht entzogen.", "Se aplica la legislación española, incluidas las normas andaluzas de turismo y consumo correspondientes. La persona consumidora no pierde la protección imperativa que le otorgaría la legislación aplicable en ausencia de esta elección.", "Spaans recht is van toepassing, waaronder de relevante Andalusische regels voor toerisme en consumenten. Een consument verliest hierdoor geen dwingende bescherming van het recht dat zonder deze rechtskeuze van toepassing zou zijn.", "Spansk lag gäller, inklusive relevanta andalusiska turist- och konsumentregler. En konsument förlorar inte det tvingande skydd som den lag som annars skulle vara tillämplig ger."),
        l("Because the service is accommodation for specific dates, the general statutory withdrawal period for distance contracts does not normally apply. The Guest’s contractual cancellation rights are the policy confirmed for the booking.", "Da es sich um eine Beherbergungsleistung für einen bestimmten Zeitraum handelt, besteht in der Regel kein allgemeines gesetzliches Widerrufsrecht für Fernabsatzverträge. Die vertraglichen Stornierungsrechte des Gastes ergeben sich aus der für die Buchung bestätigten Regelung.", "Al tratarse de un servicio de alojamiento para fechas concretas, normalmente no existe el derecho general de desistimiento previsto para los contratos a distancia. Los derechos contractuales de cancelación son los confirmados para la reserva.", "Omdat het om accommodatie voor specifieke data gaat, geldt de algemene wettelijke bedenktijd voor overeenkomsten op afstand normaal gesproken niet. De contractuele annuleringsrechten van de Gast zijn vastgelegd in het voor de boeking bevestigde beleid.", "Eftersom tjänsten avser boende för bestämda datum gäller den allmänna lagstadgade ångerfristen för distansavtal normalt inte. Gästens avtalsenliga avbokningsrättigheter anges i den policy som bekräftades för bokningen."),
        l("Disputes are heard by the courts competent under mandatory law. Before starting formal proceedings, Guests are invited to contact the Host so that a practical solution can be sought. Official consumer complaint forms are available where required.", "Für Streitigkeiten sind die nach zwingendem Recht zuständigen Gerichte maßgeblich. Vor der Einleitung eines förmlichen Verfahrens wird der Gast gebeten, den Gastgeber zu kontaktieren, damit eine praktische Lösung gesucht werden kann. Soweit vorgeschrieben, stehen offizielle Verbraucher-Beschwerdeformulare zur Verfügung.", "Los conflictos se someterán a los tribunales competentes según la normativa imperativa. Antes de iniciar un procedimiento formal, se invita al Huésped a contactar con el Anfitrión para buscar una solución práctica. Se facilitan las hojas oficiales de quejas y reclamaciones cuando resulten exigibles.", "Geschillen worden behandeld door de volgens dwingend recht bevoegde rechter. Voordat een formele procedure wordt gestart, wordt de Gast verzocht contact op te nemen met de Host om een praktische oplossing te zoeken. Officiële klachtenformulieren voor consumenten zijn beschikbaar wanneer dat verplicht is.", "Tvister prövas av de domstolar som är behöriga enligt tvingande lag. Innan ett formellt förfarande inleds uppmanas Gästen att kontakta Värden för att försöka hitta en praktisk lösning. Officiella klagomålsblanketter för konsumenter finns tillgängliga när det krävs.")
      ]
    },
    {
      id: "version",
      title: l("13. Version, Changes and Contact", "13. Version, Änderungen und Kontakt", "13. Versión, modificaciones y contacto", "13. Versie, wijzigingen en contact", "13. Version, ändringar och kontakt"),
      paragraphs: [
        l("A material change to these terms creates a new version and applies only to bookings that refer to that new version. The version accepted for an existing booking remains unchanged unless both parties expressly agree otherwise in a durable form.", "Eine inhaltlich wesentliche Änderung dieser Bedingungen erhält eine neue Version und gilt nur für Buchungen, die auf diese neue Version verweisen. Für eine bestehende Buchung bleibt die angenommene Version unverändert, sofern die Parteien nicht ausdrücklich in dauerhafter Form etwas anderes vereinbaren.", "Toda modificación material de estas condiciones genera una nueva versión y solo se aplica a las reservas que hagan referencia a ella. La versión aceptada para una reserva existente no cambia salvo acuerdo expreso de ambas partes en un soporte duradero.", "Een materiële wijziging van deze voorwaarden krijgt een nieuwe versie en geldt alleen voor boekingen die naar die nieuwe versie verwijzen. De voor een bestaande boeking aanvaarde versie blijft ongewijzigd, tenzij beide partijen uitdrukkelijk anders overeenkomen op een duurzame gegevensdrager.", "En väsentlig ändring av dessa villkor får en ny version och gäller endast för bokningar som hänvisar till den nya versionen. Den version som godkänts för en befintlig bokning förblir oförändrad om inte båda parter uttryckligen avtalar annat på ett varaktigt medium."),
        l("Guests should retain the booking confirmation together with these terms. Questions about a booking or these terms can be sent using the contact details above.", "Der Gast sollte die Buchungsbestätigung gemeinsam mit diesen Bedingungen aufbewahren. Fragen zur Buchung oder zu diesen Bedingungen können über die oben genannten Kontaktdaten gestellt werden.", "El Huésped deberá conservar la confirmación junto con estas condiciones. Las consultas sobre una reserva o sobre estas condiciones pueden enviarse utilizando los datos de contacto anteriores.", "De Gast bewaart de boekingsbevestiging samen met deze voorwaarden. Vragen over een boeking of deze voorwaarden kunnen via de bovenstaande contactgegevens worden gesteld.", "Gästen bör spara bokningsbekräftelsen tillsammans med dessa villkor. Frågor om en bokning eller villkoren kan skickas via kontaktuppgifterna ovan.")
      ]
    }
  ],
  privacyLinkLabel: l("Legal Notice & Privacy Policy", "Impressum & Datenschutzerklärung", "Aviso legal y política de privacidad", "Juridische kennisgeving & privacybeleid", "Juridisk information & integritetspolicy"),
  closingNote: l("Privacy and guest-registration information is provided separately and forms no replacement for these booking terms.", "Informationen zum Datenschutz und zur Gästeregistrierung werden gesondert bereitgestellt und ersetzen diese Buchungsbedingungen nicht.", "La información sobre privacidad y registro de huéspedes se facilita por separado y no sustituye estas condiciones de reserva.", "Informatie over privacy en gastenregistratie wordt afzonderlijk verstrekt en vervangt deze boekingsvoorwaarden niet.", "Information om integritet och gästregistrering lämnas separat och ersätter inte dessa bokningsvillkor."),
  versionNote: l("Last updated: 17 August 2026 · Version 1.0", "Stand: 17. August 2026 · Version 1.0", "Actualizado: 17 de agosto de 2026 · Versión 1.0", "Bijgewerkt: 17 augustus 2026 · Versie 1.0", "Uppdaterad: 17 augusti 2026 · Version 1.0")
};
