import type { LinkToken } from '../lib/linkResolver';
import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';

export type DailyLifeDestination = 'frigiliana' | 'nerja' | 'tarifa';

interface ContextBlock { eyebrow: string; title: string; paragraphs: string[] }
export interface DailyLifeGuideSection {
  id: 'supermarkets-everyday-shopping' | 'health-emergency' | 'good-to-know';
  eyebrow: string;
  title: string;
  intro: string[];
  /** Flattened compatibility view for authority-family characterization tooling. */
  paragraphs: string[];
  localContext: ContextBlock;
  amaraContext: ContextBlock;
  guestGuideNote?: string;
}
export interface DailyLifeGuideLocale {
  navLabel: string;
  hero: { eyebrow: string; title: string; standfirst: string; note: string; updated: string };
  facts: Array<{ label: string; value: string }>;
  sections: DailyLifeGuideSection[];
  mobilitySummary: string;
  related: { eyebrow: string; title: string; links: Array<{ token: LinkToken; label: string; text: string }> };
  sources: { eyebrow: string; title: string; intro: string; checked: string; links: Array<{ label: string; text: string; href: string }> };
  closing: { eyebrow: string; title: string; body: string; availabilityLabel: string; locationLabel: string };
}

const article = {
  datePublished: '2026-08-13', dateModified: '2026-08-22',
  authorName: 'Robert Sebastian Böhmer', authorType: 'Person' as const, authorSlug: 'amara-about-us'
};
const seoTitles: Record<AmaraLanguage, (place: string) => string> = {
  en: (p) => `Groceries, Pharmacy & Daily Life in ${p}`,
  de: (p) => `Einkaufen, Apotheke & Alltag in ${p}`,
  es: (p) => `Compras, farmacia y vida diaria en ${p}`,
  nl: (p) => `Boodschappen, apotheek & dagelijks leven in ${p}`,
  sv: (p) => `Matinköp, apotek & vardag i ${p}`
};
const seoDescriptions: Record<AmaraLanguage, (place: string) => string> = {
  en: (p) => `Our host guide to groceries, pharmacy and medical help in ${p}, with practical recommendations from an AMARA stay.`,
  de: (p) => `Unser Gastgeberguide zu Einkauf, Apotheke und medizinischer Hilfe in ${p} – konkret von AMARA aus gedacht.`,
  es: (p) => `Nuestra guía como anfitriones sobre compras, farmacia y asistencia médica en ${p}, pensada desde AMARA.`,
  nl: (p) => `Onze gastheergids voor boodschappen, apotheek en medische hulp in ${p}, praktisch bekeken vanuit AMARA.`,
  sv: (p) => `Vår värdguide till matinköp, apotek och vård i ${p}, med praktiska råd från AMARA.`
};
function makeSeo(destination: DailyLifeDestination, place: string): AmaraAuthoringSeo {
  return {
    version: `2026-08-22-${destination}-daily-life-v3.0`, pageType: 'A', entityKey: 'amara-brand', article,
    languages: Object.fromEntries((['en', 'de', 'es', 'nl', 'sv'] as AmaraLanguage[]).map((lang) => [
      lang, { title: seoTitles[lang](place), description: seoDescriptions[lang](place), robots: 'index, follow', canonical: 'auto' }
    ])) as AmaraAuthoringSeo['languages']
  };
}
export const dailyLifeGuideSeo: Record<DailyLifeDestination, AmaraAuthoringSeo> = {
  frigiliana: makeSeo('frigiliana', 'Frigiliana'),
  nerja: makeSeo('nerja', 'Nerja'),
  tarifa: makeSeo('tarifa', 'Tarifa')
};

const urls = {
  emergency: 'https://www.sspa.juntadeandalucia.es/servicioandaluzdesalud/emergencias061/ciudadania/atencion-a-la-ciudadania',
  frigilianaShopping: 'https://www.eroski.es/localizador-de-tiendas/supermercado/malaga/frigiliana/eroskicity-frigiliana/',
  frigilianaHealth: 'https://www.sspa.juntadeandalucia.es/servicioandaluzdesalud/el-sas/servicios-y-centros/informacion-por-centros/23954',
  nerjaShopping: 'https://www.aldi.es/encuentra-tu-supermercado/nerja/avenida-alcalde-antonio-villasclaras-5/4374698.html',
  nerjaHealth: 'https://www.sspa.juntadeandalucia.es/servicioandaluzdesalud/el-sas/servicios-y-centros/informacion-por-centros/24887',
  tarifaShopping: 'https://tutienda.dia.es/buscador-tiendas/cadiz/tarifa',
  tarifaHealth: 'https://www.sspa.juntadeandalucia.es/servicioandaluzdesalud/el-sas/servicios-y-centros/informacion-por-centros/24526'
};
const relatedTokens: Record<DailyLifeDestination, [LinkToken, LinkToken, LinkToken]> = {
  frigiliana: ['frigiliana_food_authority', 'frigiliana_market', 'frigiliana_experience_hub'],
  nerja: ['nerja_food_authority', 'nerja_experience_hub', 'nerja_beaches_authority'],
  tarifa: ['tarifa_food_evening_life', 'tarifa_experience_hub', 'tarifa_beaches_authority']
};

const labels = {
  en: { nav: 'Daily life & essentials', host: 'What this means at AMARA', shop: 'Groceries & self-catering', health: 'Pharmacy & medical help', good: 'Good to know', guide: 'Booked AMARA guests receive detailed, current information in the Digital Guest Guide.', medicalGuide: 'Booked AMARA guests receive direct phone and map links plus accommodation-specific emergency information in the Digital Guest Guide.', note: 'Opening hours and phone numbers change. If one of them decides your day, ask us first.', updated: 'Last checked in August 2026', related: 'Keep reading', relatedTitle: 'Eating out, markets and what else there is', food: 'Food, breakfast & evenings', foodText: 'Discover where we like to eat, linger and start the day.', discover: 'Markets & experiences', discoverText: 'Weekly markets are an experience, not a supermarket substitute.', more: 'More holiday ideas', moreText: 'Continue with beaches and local experiences.', source: 'Sources', sourceTitle: 'Where these details come from', sourceIntro: 'Our personal tips come from staying and working here. We verify the practical framework with current operator and public-service sources.', checked: 'Last checked in August 2026', closing: 'Your holiday, your rhythm', closingTitle: 'Cook one evening, eat out the next', closingBody: 'Breakfast on the terrace, lunch at a chiringuito or dinner in town: **you choose what feels right that day**.', availability: 'Check availability', location: 'Explore the location' },
  de: { nav: 'Alltag & Versorgung', host: 'Was bedeutet das bei AMARA?', shop: 'Einkaufen & Selbstversorgung', health: 'Apotheke & medizinische Hilfe', good: 'Gut zu wissen', guide: 'Ausführliche und aktuelle Informationen hierzu stellen wir unseren gebuchten Gästen in der digitalen Gästemappe zur Verfügung.', medicalGuide: 'Direkte Telefon- und Kartenlinks sowie die für eure Unterkunft relevanten Notfallinformationen stellen wir unseren gebuchten Gästen in der digitalen Gästemappe zur Verfügung.', note: 'Öffnungszeiten und Telefonnummern ändern sich. Wenn eine davon euren Tag entscheidet, fragt uns vorher.', updated: 'Zuletzt im August 2026 nachgesehen', related: 'Weiterlesen', relatedTitle: 'Essen gehen, Märkte und was es sonst gibt', food: 'Essen, Frühstück & Abende', foodText: 'Entdeckt die Orte, an denen wir selbst gerne essen und in den Tag starten.', discover: 'Märkte & Erlebnisse', discoverText: 'Wochenmärkte sind ein Erlebnis und kein Ersatz für den Supermarkt.', more: 'Mehr Urlaubsideen', moreText: 'Weiter zu Stränden und lokalen Erlebnissen.', source: 'Quellen', sourceTitle: 'Woher diese Angaben kommen', sourceIntro: 'Unsere persönlichen Tipps entstehen aus unserer Zeit und Arbeit vor Ort. Den praktischen Rahmen prüfen wir mit aktuellen Betreiber- und öffentlichen Quellen.', checked: 'Zuletzt im August 2026 nachgesehen', closing: 'Euer Urlaub, euer Rhythmus', closingTitle: 'Einen Abend kochen, den nächsten essen gehen', closingBody: 'Frühstück auf der Terrasse, Mittagessen im Chiringuito oder ein Abend im Ort: **Ihr entscheidet, was an diesem Tag zu euch passt**.', availability: 'Verfügbarkeit prüfen', location: 'Den Standort entdecken' },
  es: { nav: 'Vida diaria y servicios', host: '¿Qué significa esto en AMARA?', shop: 'Compras y cocina propia', health: 'Farmacia y asistencia médica', good: 'Conviene saberlo', guide: 'Ponemos información detallada y actualizada a disposición de nuestros huéspedes con reserva en la guía digital.', medicalGuide: 'Facilitamos a nuestros huéspedes con reserva enlaces directos de teléfono y mapas, además de información de emergencia específica del alojamiento, en la guía digital.', note: 'Los horarios y los teléfonos cambian. Si alguno decide vuestro día, preguntadnos antes.', updated: 'Revisado por última vez en agosto de 2026', related: 'Seguir leyendo', relatedTitle: 'Comer fuera, mercados y qué más hay', food: 'Comer, desayunar y salir', foodText: 'Descubrid dónde nos gusta comer y empezar el día.', discover: 'Mercados y experiencias', discoverText: 'Los mercadillos son una experiencia, no sustituyen al supermercado.', more: 'Más ideas de vacaciones', moreText: 'Continuad con playas y experiencias locales.', source: 'Fuentes', sourceTitle: 'De dónde salen estos datos', sourceIntro: 'Nuestros consejos nacen de vivir y trabajar aquí. Comprobamos el marco práctico con fuentes actuales de operadores y servicios públicos.', checked: 'Revisado por última vez en agosto de 2026', closing: 'Vuestras vacaciones, vuestro ritmo', closingTitle: 'Una noche cocináis, la siguiente salís', closingBody: 'Desayunar en la terraza, comer en un chiringuito o salir a cenar: **vosotros decidís qué os apetece ese día**.', availability: 'Comprobar disponibilidad', location: 'Descubrir el destino' },
  nl: { nav: 'Dagelijks leven & voorzieningen', host: 'Wat betekent dit bij AMARA?', shop: 'Boodschappen & zelf koken', health: 'Apotheek & medische hulp', good: 'Goed om te weten', guide: 'Onze geboekte gasten krijgen uitgebreide en actuele informatie hierover in de digitale gastenmap.', medicalGuide: 'Directe telefoon- en kaartlinks en noodinformatie voor jullie accommodatie staan voor geboekte gasten in de digitale gastenmap.', note: 'Openingstijden en telefoonnummers veranderen. Als er één jullie dag bepaalt, vraag het ons eerst.', updated: 'Voor het laatst nagekeken in augustus 2026', related: 'Verder lezen', relatedTitle: 'Uit eten, markten en wat er verder is', food: 'Eten, ontbijten & uitgaan', foodText: 'Ontdek waar wij graag eten en de dag beginnen.', discover: 'Markten & belevenissen', discoverText: 'Weekmarkten zijn een belevenis, geen vervanging voor de supermarkt.', more: 'Meer vakantie-ideeën', moreText: 'Ga verder naar stranden en lokale belevenissen.', source: 'Bronnen', sourceTitle: 'Waar deze gegevens vandaan komen', sourceIntro: 'Onze tips komen voort uit wonen en werken op deze plekken. We controleren de praktische informatie bij aanbieders en openbare diensten.', checked: 'Voor het laatst nagekeken in augustus 2026', closing: 'Jullie vakantie, jullie ritme', closingTitle: 'De ene avond koken, de volgende uit eten', closingBody: 'Ontbijten op het terras, lunchen bij een chiringuito of uit eten: **jullie kiezen waar die dag behoefte aan is**.', availability: 'Beschikbaarheid bekijken', location: 'Ontdek de locatie' },
  sv: { nav: 'Vardag & service', host: 'Vad betyder det på AMARA?', shop: 'Matinköp & självhushåll', health: 'Apotek & medicinsk hjälp', good: 'Bra att veta', guide: 'Bokade AMARA-gäster får utförlig och aktuell information om detta i den digitala gästguiden.', medicalGuide: 'Direkta telefon- och kartlänkar samt boendespecifik nödinformation finns för bokade gäster i den digitala gästguiden.', note: 'Öppettider och telefonnummer ändras. Om något av dem avgör er dag, fråga oss först.', updated: 'Senast kontrollerat i augusti 2026', related: 'Läs vidare', relatedTitle: 'Äta ute, marknader och vad mer som finns', food: 'Mat, frukost & kvällar', foodText: 'Upptäck var vi gärna äter och börjar dagen.', discover: 'Marknader & upplevelser', discoverText: 'Veckomarknader är en upplevelse, inte en ersättning för mataffären.', more: 'Fler semesteridéer', moreText: 'Fortsätt till stränder och lokala upplevelser.', source: 'Källor', sourceTitle: 'Varifrån uppgifterna kommer', sourceIntro: 'Våra tips kommer från att vistas och arbeta här. Vi kontrollerar praktiska fakta mot butiker och offentliga tjänster.', checked: 'Senast kontrollerat i augusti 2026', closing: 'Er semester, er rytm', closingTitle: 'Laga mat en kväll, ät ute nästa', closingBody: 'Frukost på terrassen, lunch på en chiringuito eller middag på stan: **ni väljer vad som känns rätt just den dagen**.', availability: 'Kontrollera tillgänglighet', location: 'Upptäck platsen' }
} satisfies Record<AmaraLanguage, Record<string, string>>;

interface RawSection { title: string; intro: string[]; localTitle: string; local: string[]; amaraTitle: string; amara: string[] }
interface RawLocale {
  title: string; standfirst: string; facts: string[]; factLabels: string[];
  shop: RawSection; health: RawSection; good: RawSection; mobility: string;
}

const raw: Record<DailyLifeDestination, Record<AmaraLanguage, RawLocale>> = {
  frigiliana: {
    en: {
      title: 'The freedom to enjoy Frigiliana your way', standfirst: 'Frigiliana is made for long lunches and evenings in the village. And some days, the nicest plan is **fresh bread, coffee and breakfast at your own AMARA home**.',
      factLabels: ['Closest shop', 'Our bakery', 'Large arrival shop', 'Medical route'], facts: ['Silvia, a few steps away', 'Panadería Manolo', 'Lidl in upper Nerja', 'Nerja, then Vélez-Málaga'],
      shop: { title: 'Eating out is part of the holiday. So is choosing not to.', intro: ['Our food guides share where we like to eat. At AMARA you can also breakfast on the terrace, pack for the beach or make an easy dinner.'], localTitle: 'Small shops cover normal holiday needs', local: ['Frigiliana has several food shops and EROSKI/city in the **newer part of the village**. Nerja adds Lidl, Aldi and Mercadona for a larger shop.', 'In high season supermarkets also open on Sundays; outside high season and on holidays, check current hours.'], amaraTitle: 'For small things we walk; for the big shop we stop in Nerja', amara: ['We start with **Supermarket Silvia**: step outside, turn right and it is a few steps away. For bread we like **Panadería Manolo**, about four minutes along Calle Real with no stairs.', 'If you arrive late, shop at Lidl high in Nerja near the motorway before driving up. It is almost on your route and saves a second trip.'] },
      health: { title: 'A simple route when you need help', intro: ['Most small holiday problems start with a pharmacy.'], localTitle: 'One village pharmacy, healthcare in Nerja', local: ['Frigiliana has **one pharmacy**. For non-emergency public care, use **Centro de Salud Nerja**, Calle Carlos Millón s/n. Before setting out, check current service hours with SAS, Salud Responde (**+34 955 54 50 60**) or the centre (**+34 951 28 96 62**).', 'For urgent medical help without immediate danger to life, call **+34 951 03 14 37**. In a life-threatening medical emergency call **061**; **112** is the general emergency number. The nearest hospital is Hospital de La Axarquía in Vélez-Málaga.'], amaraTitle: 'The pharmacy is walkable; Nerja is a short drive', amara: ['The village pharmacy is reached along Calle Real toward the newer area. Centro de Salud Nerja is normally 10–15 minutes away by car.'] },
      good: { title: 'Village convenience with Nerja as an easy extension', intro: ['Many everyday errands happen on foot while Nerja adds choice when needed.'], localTitle: 'You do not need a large supermarket every day', local: ['A bread walk, small village shops and one larger purchase on a Nerja or beach day make a relaxed combination.'], amaraTitle: 'Do the first big shop before driving up', amara: ['We shop in upper Nerja on arrival, then use Frigiliana’s local businesses during the stay.'] },
      mobility: 'Daily essentials are walkable in Frigiliana; Nerja adds larger shops and medical care.'
    },
    de: {
      title: 'Die Freiheit, Frigiliana auf eure Art zu genießen', standfirst: 'Frigiliana ist wie gemacht für lange Mittagessen und Abende im Dorf. Und manchmal ist der schönste Plan **frisches Brot, Kaffee und Frühstück im eigenen AMARA-Zuhause**.',
      factLabels: ['Nächster Laden', 'Unsere Bäckerei', 'Großeinkauf bei Anreise', 'Medizinischer Weg'], facts: ['Silvia, wenige Schritte entfernt', 'Panadería Manolo', 'Lidl oben in Nerja', 'Nerja, dann Vélez-Málaga'],
      shop: { title: 'Essen gehen gehört zum Urlaub. Die Freiheit, es nicht zu müssen, auch.', intro: ['Unsere Food-Guides zeigen, wo wir gerne essen. Bei AMARA könnt ihr genauso gut auf der Terrasse frühstücken, etwas für den Strand einpacken oder einfach selbst kochen.'], localTitle: 'Kleine Geschäfte decken den normalen Urlaubsbedarf', local: ['Frigiliana hat mehrere Lebensmittelgeschäfte und EROSKI/city im **neuen Ortsteil**. Für einen größeren Einkauf ergänzt Nerja die Auswahl mit Lidl, Aldi und Mercadona.', 'In der Hauptsaison öffnen Supermärkte auch sonntags; außerhalb der Hauptsaison und an Feiertagen prüft ihr besser die aktuellen Zeiten.'], amaraTitle: 'Für Kleinigkeiten gehen wir zu Fuß, für den Großeinkauf nach Nerja', amara: ['Wir beginnen beim **Supermarkt Silvia**: aus dem Haus, rechts und wenige Schritte später seid ihr da. Brot holen wir bei **Panadería Manolo**, etwa vier Minuten über die Calle Real und ohne Treppen.', 'Bei später Anreise kauft ihr am besten bei Lidl oben in Nerja nahe der Autobahn ein. Er liegt fast auf eurem Weg und erspart eine zweite Fahrt.'] },
      health: { title: 'Ein klarer Weg, wenn ihr Hilfe braucht', intro: ['Bei den meisten kleinen Urlaubsproblemen hilft zuerst eine Apotheke.'], localTitle: 'Eine Apotheke im Dorf, medizinische Versorgung in Nerja', local: ['Frigiliana hat **genau eine Apotheke**. Für öffentliche medizinische Hilfe ohne Notfall nutzt ihr das **Centro de Salud Nerja**, Calle Carlos Millón s/n. Prüft vor der Fahrt die aktuellen Servicezeiten beim SAS, über Salud Responde (**+34 955 54 50 60**) oder direkt beim Zentrum (**+34 951 28 96 62**).', 'Für dringende medizinische Hilfe ohne unmittelbare Lebensgefahr wählt ihr **+34 951 03 14 37**. Bei einem lebensbedrohlichen medizinischen Notfall ruft ihr **061** an; **112** ist die allgemeine Notrufnummer. Das nächste Krankenhaus ist das Hospital de La Axarquía in Vélez-Málaga.'], amaraTitle: 'Die Apotheke erreicht ihr zu Fuß, Nerja in kurzer Fahrt', amara: ['Zur Dorfapotheke geht ihr über die Calle Real in Richtung des neuen Ortsteils. Das Centro de Salud Nerja erreicht ihr mit dem Auto normalerweise in 10–15 Minuten.'] },
      good: { title: 'Dorfkomfort – mit Nerja als unkomplizierter Ergänzung', intro: ['Vieles erledigt ihr zu Fuß, während Nerja Auswahl ergänzt, wenn ihr sie braucht.'], localTitle: 'Ihr braucht nicht jeden Tag einen großen Supermarkt', local: ['Bäcker am Morgen, kleine Einkäufe im Dorf und ein größerer Einkauf an einem Nerja- oder Strandtag sind die entspannteste Kombination.'], amaraTitle: 'Den ersten Großeinkauf vor der Auffahrt erledigen', amara: ['Wir kaufen bei der Anreise oben in Nerja ein und nutzen danach die kleinen Geschäfte in Frigiliana.'] },
      mobility: 'Den täglichen Bedarf erreicht ihr in Frigiliana zu Fuß; Nerja ergänzt Großeinkauf und medizinische Versorgung.'
    },
    es: {
      title: 'La libertad de disfrutar Frigiliana a vuestra manera', standfirst: 'Frigiliana invita a alargar las comidas y las noches del pueblo. Y otros días, el mejor plan es **pan fresco, café y desayuno en vuestro alojamiento AMARA**.',
      factLabels: ['Tienda más cercana', 'Nuestra panadería', 'Compra grande al llegar', 'Ruta sanitaria'], facts: ['Silvia, a pocos pasos', 'Panadería Manolo', 'Lidl en la parte alta de Nerja', 'Nerja y Vélez-Málaga'],
      shop: { title: 'Salir a comer forma parte de las vacaciones. Poder elegir no hacerlo, también.', intro: ['En las guías gastronómicas compartimos dónde comemos. En AMARA también podéis desayunar en la terraza, preparar algo para la playa o cocinar en casa.'], localTitle: 'Las tiendas pequeñas cubren la compra normal', local: ['Frigiliana tiene varias tiendas y EROSKI/city en la **parte nueva del pueblo**. Nerja amplía la oferta con Lidl, Aldi y Mercadona.', 'En temporada alta los supermercados también abren los domingos; fuera de temporada y en festivos conviene comprobar el horario.'], amaraTitle: 'Para lo pequeño vamos andando; para la compra grande, a Nerja', amara: ['Empezamos por **Supermercado Silvia**: salís, giráis a la derecha y está a pocos pasos. Para el pan elegimos **Panadería Manolo**, a unos cuatro minutos y sin escaleras.', 'Si llegáis tarde, comprad antes en Lidl, en la parte alta de Nerja junto a la autovía. Está casi de camino y evita volver a bajar.'] },
      health: { title: 'Una ruta clara cuando necesitáis ayuda', intro: ['Los pequeños problemas suelen empezar en una farmacia.'], localTitle: 'Una farmacia en el pueblo y atención en Nerja', local: ['Frigiliana tiene **una sola farmacia**. Para atención pública sin emergencia, acudid al **Centro de Salud Nerja**, Calle Carlos Millón s/n. Antes de salir, comprobad el horario actual en el SAS, con Salud Responde (**+34 955 54 50 60**) o con el centro (**+34 951 28 96 62**).', 'Para asistencia médica urgente sin riesgo vital inmediato, llamad al **+34 951 03 14 37**. Ante una emergencia médica con riesgo vital llamad al **061**; el **112** es el número general de emergencias. El hospital más cercano es Hospital de La Axarquía, en Vélez-Málaga.'], amaraTitle: 'La farmacia queda a pie; Nerja, a un trayecto corto', amara: ['Llegáis a la farmacia por Calle Real hacia la parte nueva. El Centro de Salud Nerja suele quedar a 10–15 minutos en coche.'] },
      good: { title: 'La comodidad del pueblo, con Nerja como complemento', intro: ['Muchas cosas se hacen a pie y Nerja añade variedad cuando la necesitáis.'], localTitle: 'No necesitáis un gran supermercado cada día', local: ['Pan por la mañana, compras pequeñas en el pueblo y una compra grande coincidiendo con Nerja o la playa es la combinación más relajada.'], amaraTitle: 'Haced la primera compra antes de subir', amara: ['Nosotros compramos arriba en Nerja al llegar y usamos después las tiendas de Frigiliana.'] },
      mobility: 'La compra diaria se hace a pie en Frigiliana; Nerja complementa con supermercados grandes y atención médica.'
    },
    nl: {
      title: 'De vrijheid om Frigiliana op jullie manier te beleven', standfirst: 'Frigiliana nodigt uit tot lange lunches en avonden in het dorp. En soms is het fijnste plan **vers brood, koffie en ontbijt in jullie AMARA-verblijf**.',
      factLabels: ['Dichtstbijzijnde winkel', 'Onze bakker', 'Grote boodschap bij aankomst', 'Medische route'], facts: ['Silvia, op een paar stappen', 'Panadería Manolo', 'Lidl boven in Nerja', 'Nerja, daarna Vélez-Málaga'],
      shop: { title: 'Uit eten hoort bij vakantie. De vrijheid om dat niet te doen ook.', intro: ['Onze foodgidsen tonen waar wij graag eten. Bij AMARA kunnen jullie ook op het terras ontbijten, iets voor het strand meenemen of thuis koken.'], localTitle: 'Kleine winkels dekken normale vakantieboodschappen', local: ['Frigiliana heeft verschillende winkels en EROSKI/city in het **nieuwe deel van het dorp**. Nerja geeft meer keuze met Lidl, Aldi en Mercadona.', 'In het hoogseizoen zijn supermarkten ook op zondag open; controleer daarbuiten en op feestdagen de actuele uren.'], amaraTitle: 'Voor kleine boodschappen lopen we; voor de grote gaan we naar Nerja', amara: ['We beginnen bij **Supermarkt Silvia**: naar buiten, rechts en een paar stappen. Brood halen we bij **Panadería Manolo**, circa vier minuten zonder trappen.', 'Bij late aankomst winkelen jullie het best eerst bij Lidl boven in Nerja, vlak bij de snelweg en bijna op de route.'] },
      health: { title: 'Een duidelijke route als jullie hulp nodig hebben', intro: ['Kleine vakantieproblemen beginnen meestal bij de apotheek.'], localTitle: 'Eén apotheek in het dorp, zorg in Nerja', local: ['Frigiliana heeft **één apotheek**. Voor openbare zorg zonder noodgeval gaan jullie naar **Centro de Salud Nerja**, Calle Carlos Millón s/n. Controleer voor vertrek de actuele dienstverlening bij SAS, Salud Responde (**+34 955 54 50 60**) of het centrum (**+34 951 28 96 62**).', 'Voor dringende medische hulp zonder direct levensgevaar bellen jullie **+34 951 03 14 37**. Bij een levensbedreigende medische noodsituatie bellen jullie **061**; **112** is het algemene alarmnummer. Het dichtstbijzijnde ziekenhuis is Hospital de La Axarquía in Vélez-Málaga.'], amaraTitle: 'De apotheek is te voet bereikbaar; Nerja is een korte rit', amara: ['De apotheek ligt via Calle Real richting het nieuwe deel. Centro de Salud Nerja ligt doorgaans 10–15 minuten rijden.'] },
      good: { title: 'Dorpsgemak met Nerja als aanvulling', intro: ['Veel gebeurt te voet; Nerja vult aan wanneer meer keuze nodig is.'], localTitle: 'Een grote supermarkt is niet elke dag nodig', local: ['Brood halen, kleine dorpsboodschappen en één grote winkelronde op een Nerja- of stranddag is het meest ontspannen.'], amaraTitle: 'Doe de eerste grote boodschap vóór de rit omhoog', amara: ['Wij winkelen boven in Nerja bij aankomst en gebruiken daarna de kleine winkels van Frigiliana.'] },
      mobility: 'Dagelijkse boodschappen zijn te voet bereikbaar; Nerja vult aan met grote winkels en medische zorg.'
    },
    sv: {
      title: 'Friheten att njuta av Frigiliana på ert sätt', standfirst: 'Frigiliana bjuder in till långa luncher och kvällar i byn. Och ibland är den bästa planen **färskt bröd, kaffe och frukost i ert AMARA-boende**.',
      factLabels: ['Närmaste butik', 'Vårt bageri', 'Storhandling vid ankomst', 'Vårdvägen'], facts: ['Silvia, några steg bort', 'Panadería Manolo', 'Lidl högt upp i Nerja', 'Nerja, sedan Vélez-Málaga'],
      shop: { title: 'Att äta ute hör till semestern. Friheten att låta bli också.', intro: ['Våra matguider visar var vi äter. På AMARA kan ni också äta frukost på terrassen, packa till stranden eller laga mat hemma.'], localTitle: 'Små butiker täcker semesterbehovet', local: ['Frigiliana har flera butiker och EROSKI/city i den **nya delen av byn**. Nerja kompletterar med Lidl, Aldi och Mercadona.', 'Under högsäsong är mataffärer öppna även på söndagar; kontrollera tiderna utanför säsong och på helgdagar.'], amaraTitle: 'För småinköp går vi; för storhandling åker vi till Nerja', amara: ['Vi börjar på **Supermarket Silvia**: ut, höger och några steg. Bröd hämtar vi på **Panadería Manolo**, cirka fyra minuter utan trappor.', 'Vid sen ankomst handlar ni bäst på Lidl högt upp i Nerja nära motorvägen, nästan på vägen till Frigiliana.'] },
      health: { title: 'En tydlig väg när ni behöver hjälp', intro: ['Små semesterproblem börjar oftast på apoteket.'], localTitle: 'Ett apotek i byn, vård i Nerja', local: ['Frigiliana har **ett enda apotek**. För offentlig vård utan nödläge använder ni **Centro de Salud Nerja**, Calle Carlos Millón s/n. Kontrollera aktuella servicetider före avfärd via SAS, Salud Responde (**+34 955 54 50 60**) eller vårdcentralen (**+34 951 28 96 62**).', 'För brådskande medicinsk hjälp utan omedelbar livsfara ringer ni **+34 951 03 14 37**. Vid en livshotande medicinsk nödsituation ringer ni **061**; **112** är det allmänna larmnumret. Närmaste sjukhus är Hospital de La Axarquía i Vélez-Málaga.'], amaraTitle: 'Apoteket nås till fots; Nerja med en kort bilresa', amara: ['Apoteket nås längs Calle Real mot den nya delen. Centro de Salud Nerja ligger vanligtvis 10–15 minuter bort med bil.'] },
      good: { title: 'Bykänsla med Nerja som enkel komplettering', intro: ['Mycket görs till fots och Nerja ger mer urval vid behov.'], localTitle: 'En stor mataffär behövs inte varje dag', local: ['En brödpromenad, småinköp i byn och en storhandling under en Nerja- eller stranddag är lugnast.'], amaraTitle: 'Storhandla innan ni kör upp', amara: ['Vi handlar högt upp i Nerja vid ankomsten och använder sedan Frigilianas små butiker.'] },
      mobility: 'Vardagsinköp nås till fots; Nerja kompletterar med stora butiker och vård.'
    }
  },
  nerja: {} as Record<AmaraLanguage, RawLocale>,
  tarifa: {} as Record<AmaraLanguage, RawLocale>
};

const nerjaBase: Record<AmaraLanguage, RawLocale> = {
  en: { title: 'Everyday things are on your doorstep in Nerja', standfirst: 'Nerja makes it easy to go out for breakfast or dinner. At AMARA you also have the freedom to **start slowly at home or cook when that feels better**.', factLabels: ['Closest supermarket', 'Our breakfast choice', 'Larger shop', 'Medical care'], facts: ['Carrefour Express, same street', 'Good Stuff, about 2 minutes', 'Lidl or Aldi by the N-340', 'Centro de Salud, about 10 minutes'], shop: { title: 'The supermarket is on the same street', intro: ['Our Experience guides share where we like to eat; your own kitchen gives you another choice.'], localTitle: 'Large chains and small shops across Nerja', local: ['Nerja has Carrefour, Mercadona, Mas, Lidl, Aldi and many smaller shops. Central stores suit daily needs; larger formats by the N-340 suit a full basket.', 'In high season supermarkets also open on Sundays; check branch hours for a late shop.'], amaraTitle: 'Everyday shopping starts on our street', amara: ['**Carrefour Express** is on the same street. Mas and Mercadona add choice in the centre; for a large shop we choose Lidl or Aldi by the N-340.', 'For bread or breakfast we recommend **Good Stuff Cafe & Bakery**, about two minutes away.'] }, health: { title: 'Useful care is close to the apartment', intro: ['Pharmacy and public medical care are both accessible in town.'], localTitle: 'Several pharmacies and a public health centre', local: ['**Centro de Salud Nerja**, Calle Carlos Millón s/n, is the local public centre. Before setting out, check current service hours with SAS, Salud Responde (**+34 955 54 50 60**) or the centre (**+34 951 28 96 62**).', 'For urgent medical help without immediate danger to life, call **+34 951 03 14 37**. In a life-threatening medical emergency call **061**; **112** is the general emergency number. The nearest hospital is Hospital de La Axarquía in Vélez-Málaga.'], amaraTitle: 'Start on Calle Castilla Pérez', amara: ['We recommend the pharmacy on Calle Castilla Pérez first. Centro de Salud Nerja is roughly ten minutes away on foot.'] }, good: { title: 'Most daily errands fit into a walk', intro: ['Supermarket, bakery, pharmacy and centre are all within an easy radius.'], localTitle: 'The town for daily life, outer roads for stocking up', local: ['Separate the large arrival shop from normal top-ups and the car disappears from small decisions.'], amaraTitle: 'Shop big on arrival, then live locally', amara: ['We use Lidl or Aldi on arrival, then walk to Carrefour Express, Good Stuff and the centre.'] }, mobility: 'Supermarket, bakery, pharmacy and public healthcare are part of a walkable daily routine.' },
  de: { title: 'Der Alltag liegt in Nerja vor der Tür', standfirst: 'In Nerja könnt ihr wunderbar frühstücken oder essen gehen. Bei AMARA habt ihr zusätzlich die Freiheit, **langsam zu Hause zu starten oder selbst zu kochen**.', factLabels: ['Nächster Supermarkt', 'Unser Frühstückstipp', 'Größerer Einkauf', 'Medizinische Hilfe'], facts: ['Carrefour Express, gleiche Straße', 'Good Stuff, etwa 2 Minuten', 'Lidl oder Aldi an der N-340', 'Centro de Salud, etwa 10 Minuten'], shop: { title: 'Der Supermarkt liegt in derselben Straße', intro: ['Unsere Experience-Guides zeigen, wo wir gerne essen; die eigene Küche gibt euch eine weitere Freiheit.'], localTitle: 'Große Ketten und kleine Läden in ganz Nerja', local: ['Nerja hat Carrefour, Mercadona, Mas, Lidl, Aldi und viele kleine Geschäfte. Das Zentrum eignet sich für den Alltag, die N-340 für den Großeinkauf.', 'In der Hauptsaison öffnen Supermärkte auch sonntags; für späte Einkäufe prüft ihr die Filialzeiten.'], amaraTitle: 'Der tägliche Einkauf beginnt in unserer Straße', amara: ['**Carrefour Express** liegt in derselben Straße. Mas und Mercadona ergänzen das Zentrum; für den Großeinkauf nutzen wir Lidl oder Aldi an der N-340.', 'Für Brot oder Frühstück empfehlen wir **Good Stuff Cafe & Bakery**, ungefähr zwei Minuten entfernt.'] }, health: { title: 'Die praktische Versorgung liegt nah am Apartment', intro: ['Apotheken und öffentliche medizinische Hilfe erreicht ihr im Ort.'], localTitle: 'Mehrere Apotheken und ein öffentliches Gesundheitszentrum', local: ['Das **Centro de Salud Nerja**, Calle Carlos Millón s/n, ist die örtliche öffentliche Anlaufstelle. Prüft vor dem Weg dorthin die aktuellen Servicezeiten beim SAS, über Salud Responde (**+34 955 54 50 60**) oder direkt beim Zentrum (**+34 951 28 96 62**).', 'Für dringende medizinische Hilfe ohne unmittelbare Lebensgefahr wählt ihr **+34 951 03 14 37**. Bei einem lebensbedrohlichen medizinischen Notfall ruft ihr **061** an; **112** ist die allgemeine Notrufnummer. Das nächste Krankenhaus ist das Hospital de La Axarquía in Vélez-Málaga.'], amaraTitle: 'Unsere erste Empfehlung liegt in der Calle Castilla Pérez', amara: ['Wir empfehlen zuerst die Apotheke in der Calle Castilla Pérez. Das Centro de Salud Nerja erreicht ihr in ungefähr zehn Minuten zu Fuß.'] }, good: { title: 'Die meisten Erledigungen passen in einen Spaziergang', intro: ['Supermarkt, Bäckerei, Apotheke und Zentrum liegen in angenehmer Entfernung.'], localTitle: 'Im Ort täglich einkaufen, an der N-340 Vorräte auffüllen', local: ['Trennt den Großeinkauf bei Anreise von kleinen Besorgungen, dann braucht ihr das Auto nicht für jede Entscheidung.'], amaraTitle: 'Bei Anreise groß einkaufen, danach lokal leben', amara: ['Wir nutzen bei Anreise Lidl oder Aldi und laufen danach zu Carrefour Express, Good Stuff und ins Zentrum.'] }, mobility: 'Supermarkt, Bäckerei, Apotheke und öffentliche Gesundheitsversorgung gehören zum fußläufigen Alltag.' },
  es: { title: 'Lo cotidiano está a la puerta en Nerja', standfirst: 'Nerja invita a desayunar y cenar fuera. En AMARA también tenéis la libertad de **empezar despacio en casa o cocinar cuando os apetezca**.', factLabels: ['Supermercado más cercano', 'Nuestro desayuno', 'Compra grande', 'Atención médica'], facts: ['Carrefour Express, misma calle', 'Good Stuff, unos 2 minutos', 'Lidl o Aldi junto a la N-340', 'Centro de Salud, unos 10 minutos'], shop: { title: 'El supermercado está en la misma calle', intro: ['En las guías de experiencias compartimos dónde comemos; la cocina propia os da otra opción.'], localTitle: 'Grandes cadenas y pequeñas tiendas', local: ['Nerja tiene Carrefour, Mercadona, Mas, Lidl, Aldi y tiendas pequeñas. El centro sirve para el día a día; la N-340 para llenar la cesta.', 'En temporada alta también abren los domingos; comprobad cada tienda para compras tardías.'], amaraTitle: 'La compra diaria empieza en nuestra calle', amara: ['**Carrefour Express** está en la misma calle. Mas y Mercadona amplían el centro; para una compra grande usamos Lidl o Aldi junto a la N-340.', 'Para pan o desayuno recomendamos **Good Stuff Cafe & Bakery**, a unos dos minutos.'] }, health: { title: 'La atención práctica queda cerca', intro: ['Farmacias y atención pública están dentro de Nerja.'], localTitle: 'Varias farmacias y un centro de salud', local: ['El **Centro de Salud Nerja**, Calle Carlos Millón s/n, es el centro público local. Antes de salir, comprobad el horario actual en el SAS, con Salud Responde (**+34 955 54 50 60**) o con el centro (**+34 951 28 96 62**).', 'Para asistencia médica urgente sin riesgo vital inmediato, llamad al **+34 951 03 14 37**. Ante una emergencia médica con riesgo vital llamad al **061**; el **112** es el número general de emergencias. El hospital más cercano es Hospital de La Axarquía en Vélez-Málaga.'], amaraTitle: 'Empezad en Calle Castilla Pérez', amara: ['Recomendamos primero la farmacia de Calle Castilla Pérez. El Centro de Salud queda a unos diez minutos a pie.'] }, good: { title: 'La mayoría de los recados encajan en un paseo', intro: ['Supermercado, panadería, farmacia y centro están a una distancia cómoda.'], localTitle: 'El centro para el día a día; la N-340 para la despensa', local: ['Separad la compra grande de las pequeñas y el coche deja de formar parte de cada decisión.'], amaraTitle: 'Compra grande al llegar y vida local después', amara: ['Usamos Lidl o Aldi al llegar y luego caminamos a Carrefour Express, Good Stuff y el centro.'] }, mobility: 'Supermercado, panadería, farmacia y atención pública forman parte de un día a día a pie.' },
  nl: { title: 'Het dagelijkse ligt in Nerja voor de deur', standfirst: 'Nerja maakt buiten ontbijten en eten makkelijk. Bij AMARA kunnen jullie ook **rustig thuis beginnen of koken wanneer dat beter voelt**.', factLabels: ['Dichtstbijzijnde supermarkt', 'Onze ontbijtkeuze', 'Grote boodschap', 'Medische zorg'], facts: ['Carrefour Express, dezelfde straat', 'Good Stuff, circa 2 minuten', 'Lidl of Aldi aan de N-340', 'Centro de Salud, circa 10 minuten'], shop: { title: 'De supermarkt ligt in dezelfde straat', intro: ['Onze experiencegidsen delen waar wij eten; de eigen keuken geeft een extra keuze.'], localTitle: 'Grote ketens en kleine winkels', local: ['Nerja heeft Carrefour, Mercadona, Mas, Lidl, Aldi en kleine winkels. Het centrum is voor dagelijks gebruik; de N-340 voor een volle kar.', 'In het hoogseizoen zijn winkels ook op zondag open; controleer filialen voor late boodschappen.'], amaraTitle: 'De dagelijkse boodschap begint in onze straat', amara: ['**Carrefour Express** ligt in dezelfde straat. Mas en Mercadona vullen het centrum aan; voor groot inkopen gebruiken we Lidl of Aldi aan de N-340.', 'Voor brood of ontbijt raden we **Good Stuff Cafe & Bakery** aan, circa twee minuten weg.'] }, health: { title: 'Praktische zorg ligt dichtbij', intro: ['Apotheken en openbare zorg zijn in Nerja bereikbaar.'], localTitle: 'Meerdere apotheken en een gezondheidscentrum', local: ['**Centro de Salud Nerja**, Calle Carlos Millón s/n, is het lokale openbare zorgpunt. Controleer voor vertrek de actuele dienstverlening bij SAS, Salud Responde (**+34 955 54 50 60**) of het centrum (**+34 951 28 96 62**).', 'Voor dringende medische hulp zonder direct levensgevaar bellen jullie **+34 951 03 14 37**. Bij een levensbedreigende medische noodsituatie bellen jullie **061**; **112** is het algemene alarmnummer. Het dichtstbijzijnde ziekenhuis is Hospital de La Axarquía in Vélez-Málaga.'], amaraTitle: 'Begin op Calle Castilla Pérez', amara: ['We raden eerst de apotheek op Calle Castilla Pérez aan. Centro de Salud ligt op ongeveer tien minuten lopen.'] }, good: { title: 'De meeste dingen passen in een wandeling', intro: ['Supermarkt, bakker, apotheek en centrum liggen prettig dichtbij.'], localTitle: 'Het centrum dagelijks; de N-340 voor voorraad', local: ['Scheid de grote aankomstboodschap van kleine inkopen en de auto is niet steeds nodig.'], amaraTitle: 'Groot inkopen bij aankomst, daarna lokaal leven', amara: ['Wij gebruiken Lidl of Aldi bij aankomst en lopen daarna naar Carrefour Express, Good Stuff en het centrum.'] }, mobility: 'Supermarkt, bakker, apotheek en openbare zorg horen bij een wandelbare dagelijkse routine.' },
  sv: { title: 'Vardagen ligger utanför dörren i Nerja', standfirst: 'Nerja gör det lätt att äta frukost och middag ute. På AMARA kan ni också **börja långsamt hemma eller laga mat när det känns bäst**.', factLabels: ['Närmaste mataffär', 'Vårt frukostval', 'Storhandling', 'Medicinsk hjälp'], facts: ['Carrefour Express, samma gata', 'Good Stuff, cirka 2 minuter', 'Lidl eller Aldi vid N-340', 'Centro de Salud, cirka 10 minuter'], shop: { title: 'Mataffären ligger på samma gata', intro: ['Våra upplevelseguider visar var vi äter; eget kök ger ytterligare ett val.'], localTitle: 'Stora kedjor och små butiker', local: ['Nerja har Carrefour, Mercadona, Mas, Lidl, Aldi och småbutiker. Centrum passar vardagen; N-340 passar storhandling.', 'Under högsäsong är butiker öppna även på söndagar; kontrollera tiderna för sena inköp.'], amaraTitle: 'Vardagsinköpen börjar på vår gata', amara: ['**Carrefour Express** ligger på samma gata. Mas och Mercadona kompletterar centrum; för storhandling använder vi Lidl eller Aldi vid N-340.', 'För bröd eller frukost rekommenderar vi **Good Stuff Cafe & Bakery**, cirka två minuter bort.'] }, health: { title: 'Praktisk vård finns nära', intro: ['Apotek och offentlig vård finns i Nerja.'], localTitle: 'Flera apotek och en vårdcentral', local: ['**Centro de Salud Nerja**, Calle Carlos Millón s/n, är den lokala offentliga vårdcentralen. Kontrollera aktuella servicetider före avfärd via SAS, Salud Responde (**+34 955 54 50 60**) eller vårdcentralen (**+34 951 28 96 62**).', 'För brådskande medicinsk hjälp utan omedelbar livsfara ringer ni **+34 951 03 14 37**. Vid en livshotande medicinsk nödsituation ringer ni **061**; **112** är det allmänna larmnumret. Närmaste sjukhus är Hospital de La Axarquía i Vélez-Málaga.'], amaraTitle: 'Börja på Calle Castilla Pérez', amara: ['Vi rekommenderar först apoteket på Calle Castilla Pérez. Centro de Salud ligger ungefär tio minuters promenad bort.'] }, good: { title: 'De flesta ärenden passar i en promenad', intro: ['Mataffär, bageri, apotek och centrum ligger bekvämt nära.'], localTitle: 'Centrum till vardags; N-340 för förråden', local: ['Skilj storhandlingen vid ankomst från småinköp så behövs bilen inte varje gång.'], amaraTitle: 'Storhandla vid ankomst och lev lokalt sedan', amara: ['Vi använder Lidl eller Aldi vid ankomsten och går sedan till Carrefour Express, Good Stuff och centrum.'] }, mobility: 'Mataffär, bageri, apotek och offentlig vård ingår i en promenadvänlig vardag.' }
};

const tarifaBase: Record<AmaraLanguage, RawLocale> = {
  en: { title: 'Tarifa outside the door, freedom at home', standfirst: 'Breakfast cafés, chiringuitos and old-town evenings are part of Tarifa. At AMARA you can also **breakfast slowly on the terrace or keep dinner beautifully simple**.', factLabels: ['Closest supermarket', 'Our bread choices', 'Closest pharmacy', 'Hospital care'], facts: ['Mercadona, opposite AMARA', 'Pastelito or Bernal', 'Same street, about 2 minutes', 'Algeciras'], shop: { title: 'The supermarket is directly opposite', intro: ['Our Experience guides share where we like to eat. Sometimes you simply want breakfast on the terrace or bread and wine at home.'], localTitle: 'Supermarkets, small shops and bakeries', local: ['Tarifa has Mercadona, Lidl, DIA, Supeco and smaller shops. The public market and the weekly market are worth a visit of their own.'], amaraTitle: 'The daily shop is literally across the road', amara: ['**Mercadona is directly opposite our apartment**; we use Lidl for a larger shop. For bread we choose **Pastelito or Bernal** — especially Bernal’s delicious **Pan Macho**.'] }, health: { title: 'Pharmacy nearby, clear routes for anything more', intro: ['Tarifa has local public care; hospital care is in Algeciras.'], localTitle: 'Local care, regional hospital', local: ['Use Centro de Salud Tarifa for non-emergency care, call **112** in an emergency, and Hospital Universitario Punta de Europa in Algeciras for hospital care.'], amaraTitle: 'The pharmacy is on our street', amara: ['**La Farmacia del Viento** is on the same street, about 100 metres or two minutes away.'] }, good: { title: 'Short distances matter even more on windy days', intro: ['On a strong Levante day, nearby essentials feel especially valuable.'], localTitle: 'Let the wind shape the day', local: ['Tarifa rewards flexible plans rather than fighting the conditions.'], amaraTitle: 'Keep daily errands local', amara: ['We use Mercadona and the nearby pharmacy daily, Pastelito for quick bread and Bernal when heading into the old town.'] }, mobility: 'Supermarket and pharmacy are on the same street; bakeries and centre combine easily on foot.' },
  de: { title: 'Tarifa vor der Tür, Freiheit im eigenen Apartment', standfirst: 'Frühstückscafés, Chiringuitos und Abende in der Altstadt gehören zu Tarifa. Bei AMARA könnt ihr genauso gut **auf der Terrasse frühstücken oder das Abendessen herrlich einfach halten**.', factLabels: ['Nächster Supermarkt', 'Unsere Bäckereien', 'Nächste Apotheke', 'Krankenhausversorgung'], facts: ['Mercadona, gegenüber von AMARA', 'Pastelito oder Bernal', 'Gleiche Straße, etwa 2 Minuten', 'Algeciras'], shop: { title: 'Der Supermarkt liegt direkt gegenüber', intro: ['Unsere Experience-Guides zeigen, wo wir gerne essen. Manchmal möchtet ihr einfach auf der Terrasse frühstücken oder Brot und Wein zu Hause genießen.'], localTitle: 'Supermärkte, kleine Läden und Bäckereien', local: ['Tarifa hat Mercadona, Lidl, DIA, Supeco und kleine Geschäfte. Der Mercado Público und der Wochenmarkt sind einen eigenen Besuch wert.'], amaraTitle: 'Der tägliche Einkauf liegt buchstäblich gegenüber', amara: ['**Mercadona liegt direkt gegenüber unserem Apartment**; Lidl nutzen wir für einen größeren Einkauf. Brot holen wir bei **Pastelito oder Bernal** – besonders Bernals sehr leckeres **Pan Macho**.'] }, health: { title: 'Apotheke in der Nähe, klare Wege für alles Weitere', intro: ['Tarifa hat eine öffentliche Versorgung vor Ort; die Krankenhausversorgung liegt in Algeciras.'], localTitle: 'Versorgung vor Ort, Krankenhaus in der Region', local: ['Für Hilfe ohne Notfall nutzt ihr das Centro de Salud Tarifa, im Notfall die **112** und für Krankenhausversorgung das Hospital Universitario Punta de Europa in Algeciras.'], amaraTitle: 'Die Apotheke liegt in unserer Straße', amara: ['Die **Farmacia del Viento** liegt in derselben Straße, etwa 100 Meter beziehungsweise zwei Gehminuten entfernt.'] }, good: { title: 'Kurze Wege sind an windigen Tagen besonders wertvoll', intro: ['An einem kräftigen Levante-Tag merkt ihr besonders, wie angenehm alles in der Nähe liegt.'], localTitle: 'Den Wind in den Tagesplan einbauen', local: ['Tarifa belohnt flexible Pläne, statt gegen die Bedingungen anzukämpfen.'], amaraTitle: 'Die täglichen Wege klein halten', amara: ['Wir nutzen Mercadona und die nahe Apotheke im Alltag, Pastelito für schnelles Brot und Bernal auf dem Weg in die Altstadt.'] }, mobility: 'Supermarkt und Apotheke liegen in derselben Straße; Bäckereien und Zentrum lassen sich zu Fuß verbinden.' },
  es: { title: 'Tarifa al salir, libertad dentro del apartamento', standfirst: 'Cafeterías, chiringuitos y noches en el casco antiguo forman parte de Tarifa. En AMARA también podéis **desayunar en la terraza o preparar una cena sencilla**.', factLabels: ['Supermercado más cercano', 'Nuestras panaderías', 'Farmacia más cercana', 'Atención hospitalaria'], facts: ['Mercadona, frente a AMARA', 'Pastelito o Bernal', 'Misma calle, unos 2 minutos', 'Algeciras'], shop: { title: 'El supermercado está justo enfrente', intro: ['En las guías de experiencias compartimos dónde comemos. A veces solo apetece desayunar en la terraza o tomar pan y vino en casa.'], localTitle: 'Supermercados, tiendas y panaderías', local: ['Tarifa tiene Mercadona, Lidl, DIA, Supeco y tiendas pequeñas. El Mercado Público y el mercadillo siguen como experiencias propias.'], amaraTitle: 'La compra diaria está literalmente enfrente', amara: ['**Mercadona está justo enfrente del apartamento**; usamos Lidl para una compra grande. Para pan elegimos **Pastelito o Bernal**, especialmente el delicioso **Pan Macho** de Bernal.'] }, health: { title: 'Farmacia cerca y rutas claras para lo demás', intro: ['Tarifa tiene atención pública local; el hospital está en Algeciras.'], localTitle: 'Atención local y hospital comarcal', local: ['Para atención sin emergencia, Centro de Salud Tarifa; ante una emergencia, **112**; para hospital, Hospital Universitario Punta de Europa en Algeciras.'], amaraTitle: 'La farmacia está en nuestra calle', amara: ['La **Farmacia del Viento** está en la misma calle, a unos 100 metros o dos minutos.'] }, good: { title: 'Las distancias cortas valen más con viento', intro: ['Con Levante fuerte se agradece tener lo esencial cerca.'], localTitle: 'Adaptad el día al viento', local: ['Tarifa premia los planes flexibles.'], amaraTitle: 'Mantened cerca los recados', amara: ['Usamos Mercadona y la farmacia cercana a diario, Pastelito para pan rápido y Bernal al ir al casco antiguo.'] }, mobility: 'Supermercado y farmacia están en la misma calle; panaderías y centro se combinan a pie.' },
  nl: { title: 'Tarifa voor de deur, vrijheid in het appartement', standfirst: 'Ontbijtcafés, chiringuitos en avonden in de oude stad horen bij Tarifa. Bij AMARA kunnen jullie ook **op het terras ontbijten of eenvoudig thuis eten**.', factLabels: ['Dichtstbijzijnde supermarkt', 'Onze bakkers', 'Dichtstbijzijnde apotheek', 'Ziekenhuiszorg'], facts: ['Mercadona, tegenover AMARA', 'Pastelito of Bernal', 'Dezelfde straat, circa 2 minuten', 'Algeciras'], shop: { title: 'De supermarkt ligt recht tegenover', intro: ['Onze experiencegidsen delen waar wij eten. Soms willen jullie gewoon ontbijt op het terras of brood en wijn thuis.'], localTitle: 'Supermarkten, kleine winkels en bakkers', local: ['Tarifa heeft Mercadona, Lidl, DIA, Supeco en kleinere winkels. De openbare en weekmarkt blijven aparte belevenissen.'], amaraTitle: 'De dagelijkse boodschappen liggen letterlijk tegenover', amara: ['**Mercadona ligt direct tegenover het appartement**; Lidl gebruiken we voor groot inkopen. Voor brood kiezen we **Pastelito of Bernal**, vooral Bernals heerlijke **Pan Macho**.'] }, health: { title: 'Apotheek dichtbij, duidelijke routes voor de rest', intro: ['Tarifa heeft lokale openbare zorg; ziekenhuiszorg is in Algeciras.'], localTitle: 'Lokale zorg, regionaal ziekenhuis', local: ['Voor zorg zonder nood: Centro de Salud Tarifa; bij nood: **112**; voor ziekenhuiszorg: Hospital Universitario Punta de Europa in Algeciras.'], amaraTitle: 'De apotheek ligt in onze straat', amara: ['**La Farmacia del Viento** ligt in dezelfde straat, circa 100 meter of twee minuten lopen.'] }, good: { title: 'Korte afstanden tellen extra op winderige dagen', intro: ['Bij sterke Levante is alles dichtbij extra prettig.'], localTitle: 'Laat de wind het plan vormen', local: ['Tarifa beloont flexibele plannen.'], amaraTitle: 'Houd dagelijkse boodschappen lokaal', amara: ['Wij gebruiken Mercadona en de apotheek dagelijks, Pastelito voor snel brood en Bernal onderweg naar de oude stad.'] }, mobility: 'Supermarkt en apotheek liggen in dezelfde straat; bakkers en centrum zijn te voet te combineren.' },
  sv: { title: 'Tarifa utanför dörren, frihet i lägenheten', standfirst: 'Frukostkaféer, chiringuitos och kvällar i gamla stan hör till Tarifa. På AMARA kan ni också **äta frukost på terrassen eller hålla middagen enkel**.', factLabels: ['Närmaste mataffär', 'Våra bagerier', 'Närmaste apotek', 'Sjukhusvård'], facts: ['Mercadona, mittemot AMARA', 'Pastelito eller Bernal', 'Samma gata, cirka 2 minuter', 'Algeciras'], shop: { title: 'Mataffären ligger mitt emot', intro: ['Våra upplevelseguider visar var vi äter. Ibland vill ni bara ha frukost på terrassen eller bröd och vin hemma.'], localTitle: 'Mataffärer, småbutiker och bagerier', local: ['Tarifa har Mercadona, Lidl, DIA, Supeco och mindre butiker. Saluhallen och veckomarknaden är separata upplevelser.'], amaraTitle: 'Vardagsinköpen ligger bokstavligen mittemot', amara: ['**Mercadona ligger direkt mittemot lägenheten**; Lidl använder vi för storhandling. För bröd väljer vi **Pastelito eller Bernal**, särskilt Bernals utsökta **Pan Macho**.'] }, health: { title: 'Apotek nära, tydliga vägar för resten', intro: ['Tarifa har lokal offentlig vård; sjukhusvård finns i Algeciras.'], localTitle: 'Lokal vård, regionalt sjukhus', local: ['För vård utan nödläge: Centro de Salud Tarifa; vid nödläge: **112**; för sjukhusvård: Hospital Universitario Punta de Europa i Algeciras.'], amaraTitle: 'Apoteket ligger på vår gata', amara: ['**La Farmacia del Viento** ligger på samma gata, cirka 100 meter eller två minuter bort.'] }, good: { title: 'Korta avstånd betyder mer på blåsiga dagar', intro: ['Under stark Levante är allt nära extra värdefullt.'], localTitle: 'Låt vinden forma dagen', local: ['Tarifa belönar flexibla planer.'], amaraTitle: 'Håll vardagsärendena lokala', amara: ['Vi använder Mercadona och apoteket dagligen, Pastelito för snabbt bröd och Bernal på väg till gamla stan.'] }, mobility: 'Mataffär och apotek ligger på samma gata; bagerier och centrum kombineras till fots.' }
};
raw.nerja = nerjaBase;
raw.tarifa = tarifaBase;

function buildLocale(destination: DailyLifeDestination, lang: AmaraLanguage, place: string, data: RawLocale): DailyLifeGuideLocale {
  const l = labels[lang];
  const sourcePair = destination === 'frigiliana' ? [urls.frigilianaShopping, urls.frigilianaHealth] : destination === 'nerja' ? [urls.nerjaShopping, urls.nerjaHealth] : [urls.tarifaShopping, urls.tarifaHealth];
  const makeSection = (id: DailyLifeGuideSection['id'], eyebrow: string, section: RawSection, note?: string): DailyLifeGuideSection => ({
    id, eyebrow, title: section.title, intro: section.intro,
    paragraphs: [...section.intro, ...section.local, ...section.amara],
    localContext: { eyebrow: place, title: section.localTitle, paragraphs: section.local },
    amaraContext: { eyebrow: l.host, title: section.amaraTitle, paragraphs: section.amara },
    guestGuideNote: note
  });
  const tokens = relatedTokens[destination];
  return {
    navLabel: l.nav,
    hero: { eyebrow: `${place} · ${l.nav}`, title: data.title, standfirst: data.standfirst, note: l.note, updated: l.updated },
    facts: data.facts.map((value, index) => ({ label: data.factLabels[index], value })),
    sections: [
      makeSection('supermarkets-everyday-shopping', l.shop, data.shop, l.guide),
      makeSection('health-emergency', l.health, data.health, l.medicalGuide),
      makeSection('good-to-know', l.good, data.good)
    ],
    mobilitySummary: data.mobility,
    related: { eyebrow: l.related, title: l.relatedTitle, links: [
      { token: tokens[0], label: l.food, text: l.foodText },
      { token: tokens[1], label: l.discover, text: l.discoverText },
      { token: tokens[2], label: l.more, text: l.moreText }
    ] },
    sources: { eyebrow: l.source, title: l.sourceTitle, intro: l.sourceIntro, checked: l.checked, links: [
      { label: 'Supermarkets', text: l.shop, href: sourcePair[0] },
      { label: 'Servicio Andaluz de Salud', text: l.health, href: sourcePair[1] },
      { label: 'Emergencias Sanitarias de Andalucía', text: '061 / 112', href: urls.emergency }
    ] },
    closing: { eyebrow: l.closing, title: l.closingTitle, body: l.closingBody, availabilityLabel: l.availability, locationLabel: l.location }
  };
}

export const dailyLifeGuideContent = Object.fromEntries(
  (['frigiliana', 'nerja', 'tarifa'] as DailyLifeDestination[]).map((destination) => [
    destination,
    Object.fromEntries((['en', 'de', 'es', 'nl', 'sv'] as AmaraLanguage[]).map((lang) => [
      lang, buildLocale(destination, lang, destination[0].toUpperCase() + destination.slice(1), raw[destination][lang])
    ]))
  ])
) as Record<DailyLifeDestination, Record<AmaraLanguage, DailyLifeGuideLocale>>;
