import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';
import type { ParkingGuideLocale, ParkingGuideSection } from './parkingGuideContent';

type Localized = Record<AmaraLanguage, string>;
const l = (en: string, de: string, es: string, nl: string, sv: string): Localized => ({ en, de, es, nl, sv });
const langs: AmaraLanguage[] = ['en', 'de', 'es', 'nl', 'sv'];

const article = { datePublished: '2026-07-27', dateModified: '2026-08-21', authorName: 'Robert Sebastian Böhmer', authorType: 'Person' as const, authorSlug: 'amara-about-us' };

export const frigilianaParkingGuideSeo: AmaraAuthoringSeo = {
  version: '2026-08-21-frigiliana-parking-v3.0', pageType: 'A', entityKey: 'amara-brand', article,
  ogImage: '/images/amara-frigiliana-pueblo/JPG_Frigiliana_Pueblo/2000px_72dpi_sRGB/01-frigiliana-pueblo.jpg',
  languages: {
    en: { title: 'Parking in Frigiliana: Old Town Access & Final Walk', description: 'Plan parking in Frigiliana around day-visitor rhythms, the historic hillside, luggage, the final walk and current local rules.', robots: 'index, follow', canonical: 'auto' },
    de: { title: 'Parken in Frigiliana: Altstadt, Gepäck & letzter Weg', description: 'Plant das Parken in Frigiliana mit Tagesbesucher-Rhythmus, historischer Hanglage, Gepäck, letztem Fußweg und aktuellen Regeln.', robots: 'index, follow', canonical: 'auto' },
    es: { title: 'Aparcar en Frigiliana: casco antiguo y último tramo', description: 'Planificad dónde aparcar en Frigiliana teniendo en cuenta visitantes de día, ladera histórica, equipaje, último tramo y reglas actuales.', robots: 'index, follow', canonical: 'auto' },
    nl: { title: 'Parkeren in Frigiliana: oude kern en laatste route', description: 'Plan parkeren in Frigiliana rond dagbezoekers, de historische helling, bagage, het laatste stuk en actuele lokale regels.', robots: 'index, follow', canonical: 'auto' },
    sv: { title: 'Parkering i Frigiliana: gamla stan och sista vägen', description: 'Planera parkering i Frigiliana utifrån dagsbesökare, den historiska sluttningen, bagage, sista promenaden och aktuella regler.', robots: 'index, follow', canonical: 'auto' }
  }
};

const navLabel = l('Parking & Accessibility', 'Parken & Erreichbarkeit', 'Aparcamiento y acceso', 'Parkeren & toegankelijkheid', 'Parkering & tillgänglighet');
const hero = {
  eyebrow: l('Parking & access · Frigiliana', 'Parken & Erreichbarkeit · Frigiliana', 'Aparcamiento y acceso · Frigiliana', 'Parkeren & toegankelijkheid · Frigiliana', 'Parkering & tillgänglighet · Frigiliana'),
  title: l('Parking follows the rhythm of the village', 'Parken folgt dem Rhythmus des Dorfes', 'Aparcar sigue el ritmo del pueblo', 'Parkeren volgt het ritme van het dorp', 'Parkeringen följer byns rytm'),
  standfirst: l(
    'Frigiliana’s parking pressure is often shaped by day visitors arriving late morning and leaving after lunch. Overnight guests tend to move differently: many head towards the coast as that wave arrives and return after it has faded. That does not guarantee a space, but it changes the plan. The decisive detail is then the final route through a historic hillside village — luggage, cobbles, gradients and steps matter more than a neat map pin.',
    'Der Parkdruck in Frigiliana wird häufig von Tagesgästen geprägt, die am späten Vormittag ankommen und nach dem Mittag wieder fahren. Übernachtungsgäste bewegen sich anders: Viele fahren an die Küste, wenn diese Welle eintrifft, und kommen später zurück. Das garantiert keinen Platz, verändert aber die Planung. Entscheidend ist anschließend der letzte Weg durch den historischen Hangort – Gepäck, Pflaster, Steigungen und Stufen zählen mehr als ein schöner Kartenpunkt.',
    'La presión de aparcamiento en Frigiliana suele estar marcada por visitantes de día que llegan a última hora de la mañana y salen después de comer. Quienes se alojan siguen otro ritmo: muchos bajan a la costa cuando llega ese flujo y regresan más tarde. No garantiza plaza, pero cambia el plan. Después importa el último tramo por un pueblo histórico en ladera: equipaje, empedrado, pendientes y escalones pesan más que un punto bonito en el mapa.',
    'De parkeerdruk in Frigiliana wordt vaak bepaald door dagbezoekers die laat in de ochtend aankomen en na de lunch vertrekken. Verblijfsgasten bewegen anders: velen gaan naar de kust wanneer die stroom arriveert en keren later terug. Dat garandeert geen plek, maar verandert de planning. Daarna telt de laatste route door het historische hellingdorp — bagage, kasseien, stijgingen en trappen zijn belangrijker dan een nette kaartpin.',
    'Parkeringspressen i Frigiliana formas ofta av dagsbesökare som kommer sent på förmiddagen och åker efter lunch. Övernattande gäster rör sig annorlunda: många åker mot kusten när den vågen kommer och återvänder senare. Det garanterar ingen plats men ändrar planeringen. Därefter avgör den sista vägen genom den historiska sluttningen — bagage, stenläggning, lutning och trappor betyder mer än en snygg kartnål.'
  ),
  note: l('Host experience is marked as first-party observation. Current signs and official notices always override saved instructions.', 'Gastgebererfahrung ist als First-Party-Beobachtung gekennzeichnet. Aktuelle Schilder und amtliche Hinweise haben immer Vorrang.', 'La experiencia del anfitrión se identifica como observación propia. Las señales y avisos actuales siempre tienen prioridad.', 'Ervaring van de host staat als eigen observatie vermeld. Actuele borden en berichten gaan altijd voor.', 'Värdens erfarenhet markeras som egen observation. Aktuella skyltar och kommunala besked gäller alltid först.'),
  updated: l('Research and first-party experience reviewed August 2026', 'Recherche und persönliche Erfahrung geprüft im August 2026', 'Investigación y experiencia revisadas en agosto de 2026', 'Onderzoek en eigen ervaring herzien in augustus 2026', 'Research och egen erfarenhet granskade augusti 2026')
};

const facts = [
  { label: l('Two rhythms', 'Zwei Rhythmen', 'Dos ritmos', 'Twee ritmes', 'Två rytmer'), value: l('Day visit and overnight stay are different parking journeys', 'Tagesbesuch und Übernachtung sind andere Parkwege', 'Visita de día y estancia requieren planes distintos', 'Dagbezoek en overnachting vragen een ander plan', 'Dagsbesök och övernattning kräver olika planering') },
  { label: l('The real last mile', 'Die echte letzte Etappe', 'El último tramo real', 'De echte laatste route', 'Den verkliga sista sträckan'), value: l('Gradient, surface and steps matter', 'Steigung, Belag und Stufen zählen', 'Pendiente, pavimento y escalones importan', 'Helling, ondergrond en trappen tellen', 'Lutning, underlag och trappor räknas') },
  { label: l('Current rule', 'Aktuelle Regel', 'Regla actual', 'Actuele regel', 'Aktuell regel'), value: l('Live signs beat old screenshots', 'Schilder schlagen alte Screenshots', 'Las señales mandan sobre capturas antiguas', 'Borden gaan voor oude screenshots', 'Skyltar går före gamla skärmbilder') },
  { label: l('No promise', 'Keine Garantie', 'Sin promesas', 'Geen garantie', 'Ingen garanti'), value: l('A parking space is never guaranteed', 'Ein Stellplatz wird nie versprochen', 'Nunca se garantiza una plaza', 'Een parkeerplek wordt nooit beloofd', 'En parkeringsplats utlovas aldrig') }
] as const;

const sections: Array<{ id: ParkingGuideSection['id']; eyebrow: Localized; title: Localized; paragraphs: Localized[] }> = [
  { id: 'parking-reality', eyebrow: l('01 · Parking reality', '01 · Die Parkrealität', '01 · La realidad', '01 · De realiteit', '01 · Verkligheten'), title: l('A large search topic, driven by short visits', 'Ein großes Suchthema, geprägt von kurzen Besuchen', 'Una gran búsqueda impulsada por visitas cortas', 'Een groot zoekthema door korte bezoeken', 'Ett stort sökämne som drivs av korta besök'), paragraphs: [
    l('AMARA’s operating experience places the main day-visitor arrival in the later morning and departure in the early afternoon; overnight guests often leave for the beach around then and return later. Treat those hours as local experience, not measured occupancy.', 'Nach AMARA-Erfahrung liegt die stärkste Ankunft der Tagesgäste am späteren Vormittag und die Abreise am frühen Nachmittag; Übernachtungsgäste fahren oft dann zum Strand und kommen später zurück. Das ist Gastgeberwissen, keine gemessene Auslastung.', 'Según la experiencia de AMARA, los visitantes de día llegan sobre todo a última hora de la mañana y salen a primera hora de la tarde; los huéspedes suelen ir a la playa entonces y volver después. Es experiencia local, no una medición.', 'Volgens AMARA-ervaring komen dagbezoekers vooral laat in de ochtend en vertrekken vroeg in de middag; verblijfsgasten gaan dan vaak naar het strand en keren later terug. Dit is lokale ervaring, geen meting.', 'Enligt AMARA-erfarenhet kommer dagsbesökare främst sent på förmiddagen och lämnar tidigt på eftermiddagen; boende gäster åker ofta till stranden då och återvänder senare. Det är lokal erfarenhet, inte mätning.'),
    l('A guest staying in the village is not simply another day visitor. The page therefore explains timing without promising that a particular car park will be free.', 'Wer im Dorf schläft, ist nicht einfach ein weiterer Tagesgast. Deshalb erklären wir den Rhythmus, ohne jemals einen freien Platz zu versprechen.', 'Quien duerme en el pueblo no es simplemente otro excursionista. Explicamos el ritmo sin prometer una plaza concreta.', 'Wie in het dorp slaapt, is niet gewoon nog een dagbezoeker. Daarom leggen we het ritme uit zonder een vrije plek te beloven.', 'Den som bor i byn är inte bara ännu en dagsbesökare. Därför förklarar vi rytmen utan att lova en ledig plats.')
  ]},
  { id: 'arrival-luggage', eyebrow: l('02 · Arrival and luggage', '02 · Ankunft und Gepäck', '02 · Llegada y equipaje', '02 · Aankomst en bagage', '02 · Ankomst och bagage'), title: l('Choose the parking context, then the route to the door', 'Erst den Parkkontext wählen, dann den Weg zur Tür', 'Primero el contexto; después la ruta a la puerta', 'Eerst de parkeercontext, daarna de route naar de deur', 'Välj parkeringssammanhang, sedan vägen till dörren'), paragraphs: [
    l('The lower village around Plaza de las Tres Culturas is a practical orientation point. Historic-centre destinations can require a final walk, and the shortest-looking route is not automatically easiest with luggage.', 'Der untere Ort rund um die Plaza de las Tres Culturas ist ein praktischer Orientierungspunkt. Für Ziele in der Altstadt folgt oft ein Fußweg; die kürzeste Kartenstrecke ist mit Gepäck nicht automatisch die einfachste.', 'La zona baja alrededor de Plaza de las Tres Culturas orienta bien. Para destinos del casco histórico puede quedar un tramo a pie y la ruta más corta no siempre es la más cómoda con equipaje.', 'Het lagere dorp rond Plaza de las Tres Culturas is een praktisch oriëntatiepunt. Naar de oude kern volgt vaak een wandeling; de kortste route is met bagage niet altijd de makkelijkste.', 'Den lägre byn kring Plaza de las Tres Culturas är en praktisk orienteringspunkt. Till gamla stan återstår ofta en promenad; kortast är inte alltid enklast med bagage.'),
    l('Do not improvise a drop-off in a narrow street. Follow the property instructions, read the signs and separate a legal stop from the place where the car remains.', 'Improvisiert keinen Gepäckstopp in einer engen Gasse. Nutzt die Objekthinweise, lest die Schilder und trennt legalen Halt vom endgültigen Stellplatz.', 'No improviséis una descarga en una calle estrecha. Seguid las instrucciones, leed las señales y separad la parada legal del estacionamiento final.', 'Improviseer geen stop in een smalle straat. Volg de woninginstructies, lees de borden en scheid lossen van definitief parkeren.', 'Improvisera inte ett stopp på en smal gata. Följ boendets instruktion, läs skyltarna och skilj avlastning från slutlig parkering.')
  ]},
  { id: 'during-stay', eyebrow: l('03 · During your stay', '03 · Während des Aufenthalts', '03 · Durante la estancia', '03 · Tijdens het verblijf', '03 · Under vistelsen'), title: l('Your car can follow a different timetable', 'Euer Auto kann einen anderen Tagesplan haben', 'El coche puede seguir otro horario', 'De auto kan een ander dagritme volgen', 'Bilen kan följa en annan dagsrytm'), paragraphs: [
    l('The car may leave for Nerja or the coast while day visitors fill the village and return later. On other days it can remain parked while you walk locally.', 'Das Auto fährt vielleicht Richtung Nerja oder Küste, während Tagesgäste den Ort füllen, und kommt später zurück. An anderen Tagen bleibt es stehen, während ihr zu Fuß unterwegs seid.', 'El coche puede salir hacia Nerja o la costa cuando llegan visitantes de día y volver más tarde. Otros días puede quedarse aparcado mientras camináis.', 'De auto kan naar Nerja of de kust vertrekken wanneer dagbezoekers komen en later terugkeren. Op andere dagen blijft hij staan terwijl jullie lopen.', 'Bilen kan åka mot Nerja eller kusten när dagsbesökarna kommer och återvända senare. Andra dagar står den kvar medan ni går.'),
    l('Plan by journey purpose rather than chasing one supposedly perfect space. Arrival, a beach day and an evening return are different parking moments.', 'Plant nach Fahrtzweck statt nach einem vermeintlich perfekten Parkplatz. Ankunft, Strandtag und Rückkehr am Abend sind unterschiedliche Situationen.', 'Planificad según el objetivo: llegada, día de playa y regreso son momentos distintos.', 'Plan per doel: aankomst, stranddag en terugkeer zijn verschillende parkeermomenten.', 'Planera efter syfte: ankomst, stranddag och kvällsretur är olika situationer.')
  ]},
  { id: 'last-mile', eyebrow: l('04 · Last mile and accessibility', '04 · Letzter Weg und Zugänglichkeit', '04 · Último tramo y accesibilidad', '04 · Laatste route en toegankelijkheid', '04 · Sista sträckan och tillgänglighet'), title: l('Distance alone tells you very little', 'Entfernung allein sagt hier fast nichts', 'La distancia por sí sola dice muy poco', 'Afstand alleen zegt hier bijna niets', 'Avstånd ensamt säger nästan ingenting'), paragraphs: [
    l('A route can include slopes, cobbles or steps. A nearby bay does not prove a step-free path, and a reduced-mobility space does not describe the whole journey to a home.', 'Ein Weg kann Steigungen, Pflaster oder Stufen enthalten. Ein naher Stellplatz beweist keine stufenfreie Route; auch ein PMR-Platz beschreibt nicht den ganzen Weg.', 'Una ruta puede incluir pendiente, empedrado o escalones. Una plaza cercana no demuestra un camino sin escalones ni describe todo el acceso.', 'Een route kan hellingen, kasseien of trappen hebben. Een nabije plaats bewijst geen trapvrije route en beschrijft niet de hele weg.', 'En väg kan ha lutningar, stenläggning eller trappor. En närliggande plats bevisar inte en stegfri rutt och beskriver inte hela vägen.'),
    l('Guests with mobility or luggage concerns need the exact property route. Describe surfaces and steps; do not rely on a broad “accessible” label.', 'Bei Mobilitäts- oder Gepäckthemen braucht ihr die konkrete Objektroute. Oberflächen und Stufen sind hilfreicher als das pauschale Wort „barrierefrei“.', 'Si hay necesidades de movilidad o equipaje, pedid la ruta exacta. Es mejor describir superficies y escalones que decir “accesible”.', 'Vraag bij mobiliteits- of bagagezorgen om de exacte woningroute. Beschrijf ondergrond en treden, niet algemeen “toegankelijk”.', 'Be om exakt boenderutt vid rörelse- eller bagagebehov. Beskriv underlag och steg i stället för att generellt säga “tillgänglig”.')
  ]},
  { id: 'seasonal-rules', eyebrow: l('05 · Seasons and rules', '05 · Saison und Regeln', '05 · Temporada y reglas', '05 · Seizoen en regels', '05 · Säsong och regler'), title: l('Historic rules need a current reading', 'Historische Regeln brauchen eine heutige Prüfung', 'Las normas históricas necesitan una lectura actual', 'Historische regels moeten actueel worden gecontroleerd', 'Historiska regler måste kontrolleras i nutid'), paragraphs: [
    l('A historic-centre traffic ordinance entered into force in 2011; the municipality began a consultation toward repeal in 2018. Public evidence does not establish the complete 2026 legal position.', '2011 trat eine Altstadt-Verkehrsordnung in Kraft; 2018 begann die Gemeinde eine Konsultation zu ihrer Aufhebung. Die öffentlichen Belege klären den vollständigen Rechtsstand 2026 nicht.', 'Una ordenanza del casco histórico entró en vigor en 2011; en 2018 el Ayuntamiento inició una consulta para derogarla. Las fuentes públicas no cierran el estado completo de 2026.', 'In 2011 trad een verkeersregel voor de oude kern in werking; in 2018 begon een raadpleging over intrekking. Publieke bronnen leggen de volledige situatie in 2026 niet vast.', 'En trafikförordning för gamla stan trädde i kraft 2011; 2018 inleddes en konsultation om upphävande. Offentliga källor klargör inte hela läget 2026.'),
    l('Temporary controls, events and signs can alter access. Check municipal notices and never turn an old price, hour or street permission into a permanent promise.', 'Temporäre Maßnahmen, Veranstaltungen und Schilder können die Zufahrt ändern. Prüft kommunale Hinweise und macht aus alten Preisen, Zeiten oder Erlaubnissen kein Versprechen.', 'Controles temporales, eventos y señales pueden cambiar el acceso. Consultad avisos municipales y no convirtáis precios u horarios antiguos en promesas.', 'Tijdelijke maatregelen, evenementen en borden kunnen toegang veranderen. Controleer gemeentelijke berichten en maak van oude prijzen of tijden geen belofte.', 'Tillfälliga åtgärder, evenemang och skyltar kan ändra infarten. Kontrollera kommunala besked och gör inte gamla priser eller tider till löften.')
  ]},
  { id: 'amara-boundary', eyebrow: l('06 · AMARA boundary', '06 · AMARA-Grenze', '06 · Límite AMARA', '06 · AMARA-grens', '06 · AMARA-gränsen'), title: l('Village guidance ends where the property route begins', 'Die Dorfberatung endet dort, wo die Objektroute beginnt', 'La guía del pueblo termina donde empieza la ruta de la vivienda', 'Dorpsadvies eindigt waar de woningroute begint', 'Byguiden slutar där boenderutten börjar'), paragraphs: [
    l('This guide explains the village-wide logic. The exact stopping point, walking route and steps belong to the selected AMARA home and must be checked for that door.', 'Dieser Guide erklärt die Logik des Ortes. Konkreter Haltepunkt, Fußweg und Stufen gehören zum gewählten AMARA-Haus und müssen für diese Tür geprüft werden.', 'Esta guía explica la lógica general. El punto de parada, la ruta y los escalones pertenecen a cada casa AMARA.', 'Deze gids legt de dorpslogica uit. Stopplaats, looproute en trappen horen bij de gekozen AMARA-woning.', 'Guiden förklarar byns logik. Stopplats, gångväg och trappor hör till det valda AMARA-hemmet.'),
    l('Use the page to decide whether the hillside reality suits you, then use property instructions for the final metres and current municipal sources for dynamic rules.', 'Nutzt die Seite, um zu entscheiden, ob die Hanglage zu euch passt. Für die letzten Meter gelten Objekthinweise, für dynamische Regeln aktuelle Gemeindequellen.', 'Usad la página para decidir si la ladera os encaja y después consultad las instrucciones específicas y las fuentes municipales actuales.', 'Bepaal eerst of de helling past en gebruik daarna de specifieke instructies en actuele gemeentelijke bronnen.', 'Avgör först om sluttningen passar och använd sedan boendets instruktioner och aktuella kommunala källor.')
  ]}
];

const related = [
  { token: 'getting_to_frigiliana' as const, label: l('Arrival & Mobility', 'Anreise & Mobilität', 'Llegada y movilidad', 'Aankomst & mobiliteit', 'Ankomst & mobilitet'), text: l('Airports, roads and the approach to the village.', 'Flughäfen, Straßen und die Zufahrt zum Ort.', 'Aeropuertos, carreteras y acceso al pueblo.', 'Luchthavens, wegen en de benadering van het dorp.', 'Flygplatser, vägar och infarten till byn.') },
  { token: 'frigiliana_stairs' as const, label: l('Streets & Stairs', 'Gassen & Treppen', 'Calles y escaleras', 'Straten & trappen', 'Gränder & trappor'), text: l('Understand the terrain before choosing a route.', 'Das Gelände verstehen, bevor ihr eine Route wählt.', 'Entended el terreno antes de elegir ruta.', 'Begrijp het terrein vóór de routekeuze.', 'Förstå terrängen innan ni väljer rutt.') },
  { token: 'nerja_vs_frigiliana' as const, label: l('Frigiliana or Nerja?', 'Frigiliana oder Nerja?', '¿Frigiliana o Nerja?', 'Frigiliana of Nerja?', 'Frigiliana eller Nerja?'), text: l('Compare the hillside village with a coastal base.', 'Den Hangort mit einer Küstenbasis vergleichen.', 'Comparad el pueblo en ladera con una base costera.', 'Vergelijk het hellingdorp met een kustbasis.', 'Jämför sluttningens by med en kustbas.') }
];

const sourceRows = [
  { label: l('Official street map', 'Offizieller Ortsplan', 'Callejero oficial', 'Officiële kaart', 'Officiell karta'), text: l('Orientation, not live availability.', 'Orientierung, keine Live-Verfügbarkeit.', 'Orientación, no disponibilidad.', 'Oriëntatie, geen live beschikbaarheid.', 'Orientering, inte live-tillgänglighet.'), href: 'https://www.turismofrigiliana.es/es/callejero.html' },
  { label: l('Historic traffic ordinance', 'Historische Verkehrsordnung', 'Ordenanza histórica', 'Historische verkeersregel', 'Historisk trafikförordning'), text: l('2011 source; not the full current rule.', 'Quelle von 2011; nicht der vollständige aktuelle Stand.', 'Fuente de 2011; no régimen completo actual.', 'Bron uit 2011; niet het volledige huidige regime.', 'Källa från 2011; inte hela dagens regelverk.'), href: 'https://frigiliana.es/entrada-en-vigor-de-la-ordenanza-de-regulacion-del-trafico-en-el-casco-antiguo/' },
  { label: l('Repeal consultation', 'Aufhebungskonsultation', 'Consulta de derogación', 'Intrekkingsconsultatie', 'Konsultation om upphävande'), text: l('2018 review of the earlier framework.', 'Überprüfung des früheren Rahmens im Jahr 2018.', 'Revisión del marco anterior en 2018.', 'Herziening van het oude kader in 2018.', 'Översyn av det äldre ramverket 2018.'), href: 'https://frigiliana.es/memoria-de-derogacion-ordenanza-trafico-casco-antiguo/' },
  { label: l('Frigiliana Informa', 'Frigiliana Informa', 'Frigiliana Informa', 'Frigiliana Informa', 'Frigiliana Informa'), text: l('Municipal channel for current notices and warnings.', 'Kommunaler Kanal für aktuelle Hinweise und Warnungen.', 'Canal municipal para avisos y alertas actuales.', 'Gemeentelijk kanaal voor actuele berichten.', 'Kommunal kanal för aktuella besked.'), href: 'https://frigiliana.es/toda-la-informacion-de-frigiliana-en-tu-movil/' }
];

const makeLocale = (lang: AmaraLanguage): ParkingGuideLocale => ({
  navLabel: navLabel[lang],
  hero: { eyebrow: hero.eyebrow[lang], title: hero.title[lang], standfirst: hero.standfirst[lang], note: hero.note[lang], updated: hero.updated[lang] },
  facts: facts.map((item) => ({ label: item.label[lang], value: item.value[lang] })),
  sections: sections.map((section) => ({ id: section.id, eyebrow: section.eyebrow[lang], title: section.title[lang], paragraphs: section.paragraphs.map((p) => p[lang]) })),
  related: { eyebrow: l('Continue planning', 'Weiter planen', 'Seguir planificando', 'Verder plannen', 'Planera vidare')[lang], title: l('Connect parking to the complete arrival', 'Parken mit der vollständigen Ankunft verbinden', 'Unid el aparcamiento con la llegada completa', 'Verbind parkeren met de volledige aankomst', 'Koppla parkering till hela ankomsten')[lang], links: related.map((item) => ({ token: item.token, label: item.label[lang], text: item.text[lang] })) },
  sources: { eyebrow: l('Sources and live checks', 'Quellen und Live-Prüfung', 'Fuentes y comprobación', 'Bronnen en live-check', 'Källor och livekontroll')[lang], title: l('Stable orientation, dynamic rules', 'Stabile Orientierung, dynamische Regeln', 'Orientación estable, reglas dinámicas', 'Stabiele oriëntatie, dynamische regels', 'Stabil orientering, dynamiska regler')[lang], intro: l('Official history explains why old access claims require care. Current notices and signs govern the day itself.', 'Die kommunale Historie zeigt, warum alte Zufahrtsaussagen Vorsicht brauchen. Aktuelle Hinweise und Schilder regeln den Tag.', 'La historia municipal exige cautela con reglas antiguas. Los avisos y señales actuales mandan.', 'De gemeentelijke geschiedenis vraagt voorzichtigheid met oude regels. Actuele berichten en borden bepalen de dag.', 'Kommunens historik kräver försiktighet med gamla regler. Aktuella besked och skyltar styr dagen.')[lang], checked: l('Sources reviewed 21 August 2026', 'Quellen geprüft am 21. August 2026', 'Fuentes revisadas el 21 de agosto de 2026', 'Bronnen gecontroleerd op 21 augustus 2026', 'Källor granskade 21 augusti 2026')[lang], links: sourceRows.map((item) => ({ label: item.label[lang], text: item.text[lang], href: item.href })) },
  closing: { eyebrow: l('Arrive with the right expectation', 'Mit der richtigen Erwartung ankommen', 'Llegad con la expectativa correcta', 'Kom met de juiste verwachting', 'Anländ med rätt förväntan')[lang], title: l('Plan the car and final walk as one journey', 'Auto und letzten Fußweg als eine Reise planen', 'Planificad el coche y el último tramo como un viaje', 'Plan auto en laatste wandeling als één reis', 'Planera bilen och sista promenaden som en resa')[lang], body: l('Understand the village rhythm, accept changing availability and choose the AMARA home whose final route fits you.', 'Versteht den Ortsrhythmus, akzeptiert wechselnde Verfügbarkeit und wählt das AMARA-Haus, dessen letzter Weg zu euch passt.', 'Entended el ritmo, aceptad que la disponibilidad cambia y elegid la casa AMARA cuya ruta final os encaje.', 'Begrijp het ritme, accepteer wisselende beschikbaarheid en kies de AMARA-woning met een passende laatste route.', 'Förstå rytmen, acceptera varierande tillgång och välj AMARA-hemmet vars sista väg passar er.')[lang], locationLabel: l('Explore Frigiliana', 'Frigiliana entdecken', 'Descubrir Frigiliana', 'Ontdek Frigiliana', 'Upptäck Frigiliana')[lang], propertyLabel: l('View AMARA homes', 'AMARA-Häuser ansehen', 'Ver casas AMARA', 'Bekijk AMARA-woningen', 'Se AMARA-boenden')[lang] }
});

export const frigilianaParkingGuideContent = Object.fromEntries(langs.map((lang) => [lang, makeLocale(lang)])) as Record<AmaraLanguage, ParkingGuideLocale>;
