import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';
import type { ParkingGuideLocale, ParkingGuideSection } from './parkingGuideContent';

type Localized = Record<AmaraLanguage, string>;
const l = (en: string, de: string, es: string, nl: string, sv: string): Localized => ({ en, de, es, nl, sv });
const langs: AmaraLanguage[] = ['en', 'de', 'es', 'nl', 'sv'];

const article = { datePublished: '2026-07-27', dateModified: '2026-08-21', authorName: 'Robert Sebastian Böhmer', authorType: 'Person' as const, authorSlug: 'amara-about-us' };

export const frigilianaParkingGuideSeo: AmaraAuthoringSeo = {
  version: '2026-08-21-frigiliana-parking-v3.2', pageType: 'A', entityKey: 'amara-brand', article,
  ogImage: '/images/amara-frigiliana-pueblo/JPG_Frigiliana_Pueblo/2000px_72dpi_sRGB/01-frigiliana-pueblo.jpg',
  languages: {
    en: { title: 'Parking in Frigiliana: Old Town Access & Final Walk', description: 'Plan parking in Frigiliana around day-visitor rhythms, the historic hillside, luggage, the final walk and current local rules.', robots: 'index, follow', canonical: 'auto' },
    de: { title: 'Parken in Frigiliana: Altstadt, Gepäck & letzter Weg', description: 'Plant das Parken in Frigiliana mit Tagesbesucher-Rhythmus, historischer Hanglage, Gepäck, letztem Fußweg und aktuellen Regeln.', robots: 'index, follow', canonical: 'auto' },
    es: { title: 'Aparcar en Frigiliana: casco antiguo y último tramo', description: 'Planificad dónde aparcar en Frigiliana teniendo en cuenta visitantes de día, ladera histórica, equipaje, último tramo y reglas actuales.', robots: 'index, follow', canonical: 'auto' },
    nl: { title: 'Parkeren in Frigiliana: oude kern en laatste route', description: 'Plan parkeren in Frigiliana rond dagbezoekers, de historische helling, bagage, het laatste stuk en actuele lokale regels.', robots: 'index, follow', canonical: 'auto' },
    sv: { title: 'Parkering i Frigiliana: gamla stan och sista vägen', description: 'Planera parkering i Frigiliana utifrån dagsbesökare, den historiska sluttningen, bagage, sista promenaden och aktuella regler.', robots: 'index, follow', canonical: 'auto' }
  }
};

const navLabel = l('Parking & Accessibility', 'Parken & Erreichbarkeit', 'Aparcamiento y acceso', 'Parkeren & toegankelijkheid', 'Parkering & tillgänglighet');
const hero = {
  eyebrow: l('Parking & access · Frigiliana', 'Parken & Erreichbarkeit · Frigiliana', 'Aparcamiento y acceso · Frigiliana', 'Parkeren & toegankelijkheid · Frigiliana', 'Parkering & tillgänglighet · Frigiliana'),
  title: l('Parking follows the rhythm of the village', 'Parken folgt dem Rhythmus des Dorfes', 'Aparcar sigue el ritmo del pueblo', 'Parkeren volgt het ritme van het dorp', 'Parkeringen följer byns rytm'),
  standfirst: l(
    'Frigiliana’s parking pressure is often shaped by day visitors arriving late morning and leaving after lunch. Overnight guests tend to move differently: many head towards the coast as that wave arrives and return after it has faded. That does not guarantee a space, but it changes the plan. The decisive detail is then the final route through a historic hillside village — luggage, cobbles, gradients and steps matter more than a neat map pin.',
    'Der Parkdruck in Frigiliana wird häufig von Tagesgästen geprägt, die am späten Vormittag ankommen und nach dem Mittag wieder fahren. Übernachtungsgäste bewegen sich anders: Viele fahren an die Küste, wenn diese Welle eintrifft, und kommen später zurück. Das garantiert keinen Platz, verändert aber die Planung. Entscheidend ist anschließend der letzte Weg durch den historischen Hangort – Gepäck, Pflaster, Steigungen und Stufen zählen mehr als ein schöner Kartenpunkt.',
    'La presión de aparcamiento en Frigiliana suele estar marcada por visitantes de día que llegan a última hora de la mañana y salen después de comer. Quienes se alojan siguen otro ritmo: muchos bajan a la costa cuando llega ese flujo y regresan más tarde. No garantiza plaza, pero cambia el plan. Después importa el último tramo por un pueblo histórico en ladera: equipaje, empedrado, pendientes y escalones pesan más que un punto bonito en el mapa.',
    'De parkeerdruk in Frigiliana wordt vaak bepaald door dagbezoekers die laat in de ochtend aankomen en na de lunch vertrekken. Verblijfsgasten bewegen anders: velen gaan naar de kust wanneer die stroom arriveert en keren later terug. Dat garandeert geen plek, maar verandert de planning. Daarna telt de laatste route door het historische hellingdorp — bagage, kasseien, stijgingen en trappen zijn belangrijker dan een nette kaartpin.',
    'Parkeringspressen i Frigiliana formas ofta av dagsbesökare som kommer sent på förmiddagen och åker efter lunch. Övernattande gäster rör sig annorlunda: många åker mot kusten när den vågen kommer och återvänder senare. Det garanterar ingen plats men ändrar planeringen. Därefter avgör den sista vägen genom den historiska sluttningen — bagage, stenläggning, lutning och trappor betyder mer än en snygg kartnål.'
  ),
  note: l('This is how we experience the village as hosts. On the day itself, the current signs always come first.', 'So erleben wir das Dorf als Gastgeber. Am Tag selbst haben die aktuellen Schilder immer Vorrang.', 'Así vivimos el pueblo como anfitriones. Ese día, las señales actuales siempre tienen prioridad.', 'Zo ervaren we het dorp als hosts. Op de dag zelf gaan de actuele borden altijd voor.', 'Så upplever vi byn som värdar. På själva dagen gäller de aktuella skyltarna alltid först.'),
  updated: l('Personally updated by Robert · August 2026', 'Von Robert persönlich aktualisiert · August 2026', 'Actualizado personalmente por Robert · agosto de 2026', 'Persoonlijk bijgewerkt door Robert · augustus 2026', 'Personligen uppdaterad av Robert · augusti 2026')
};

const facts = [
  { label: l('Two rhythms', 'Zwei Rhythmen', 'Dos ritmos', 'Twee ritmes', 'Två rytmer'), value: l('Day visit and overnight stay are different parking journeys', 'Tagesbesuch und Übernachtung sind andere Parkwege', 'Visita de día y estancia requieren planes distintos', 'Dagbezoek en overnachting vragen een ander plan', 'Dagsbesök och övernattning kräver olika planering') },
  { label: l('The real last mile', 'Die echte letzte Etappe', 'El último tramo real', 'De echte laatste route', 'Den verkliga sista sträckan'), value: l('Gradient, surface and steps matter', 'Steigung, Belag und Stufen zählen', 'Pendiente, pavimento y escalones importan', 'Helling, ondergrond en trappen tellen', 'Lutning, underlag och trappor räknas') },
  { label: l('Current rule', 'Aktuelle Regel', 'Regla actual', 'Actuele regel', 'Aktuell regel'), value: l('Live signs beat old screenshots', 'Schilder schlagen alte Screenshots', 'Las señales mandan sobre capturas antiguas', 'Borden gaan voor oude screenshots', 'Skyltar går före gamla skärmbilder') },
  { label: l('Through traffic', 'Durchfahrt', 'Tráfico de paso', 'Doorgaand verkeer', 'Genomfart'), value: l('Usually closed from 10–11am to about 5pm', 'Meist von 10–11 bis etwa 17 Uhr gesperrt', 'Cerrada normalmente de 10–11 h a 17 h', 'Meestal dicht van 10–11 tot ongeveer 17 uur', 'Oftast avstängd 10–11 till cirka 17') }
] as const;

const sections: Array<{ id: ParkingGuideSection['id']; eyebrow: Localized; title: Localized; paragraphs: Localized[] }> = [
  { id: 'parking-reality', eyebrow: l('01 · Parking reality', '01 · Die Parkrealität', '01 · La realidad', '01 · De realiteit', '01 · Verkligheten'), title: l('A large search topic, driven by short visits', 'Ein großes Suchthema, geprägt von kurzen Besuchen', 'Una gran búsqueda impulsada por visitas cortas', 'Een groot zoekthema door korte bezoeken', 'Ett stort sökämne som drivs av korta besök'), paragraphs: [
    l('Over the years we have noticed a clear rhythm: many day visitors arrive later in the morning and leave again in the early afternoon. Our overnight guests often do almost the opposite — they head to the beach around that time and return later. These are not measured occupancy figures, just the practical pattern we use when advising guests.', 'Über die Jahre haben wir einen klaren Rhythmus beobachtet: Viele Tagesgäste kommen am späteren Vormittag und fahren am frühen Nachmittag wieder. Unsere Übernachtungsgäste machen häufig fast das Gegenteil – sie fahren dann zum Strand und kommen später zurück. Das sind keine gemessenen Auslastungszahlen, sondern das praktische Muster, nach dem wir unsere Gäste beraten.', 'Con los años hemos observado un ritmo claro: muchos visitantes de día llegan a última hora de la mañana y se marchan a primera hora de la tarde. Nuestros huéspedes suelen hacer casi lo contrario: bajan a la playa y regresan después. No son cifras de ocupación, sino el patrón práctico que utilizamos al aconsejaros.', 'Door de jaren heen hebben we een duidelijk ritme gezien: veel dagbezoekers komen later in de ochtend en vertrekken vroeg in de middag. Onze verblijfsgasten doen vaak bijna het tegenovergestelde: zij gaan dan naar het strand en komen later terug. Het zijn geen bezettingscijfers, maar het praktische patroon waarmee we gasten adviseren.', 'Under åren har vi sett en tydlig rytm: många dagsbesökare kommer senare på förmiddagen och åker tidigt på eftermiddagen. Våra boende gäster gör ofta nästan tvärtom – de åker till stranden då och kommer tillbaka senare. Det är inga beläggningssiffror, utan det praktiska mönster vi använder när vi ger råd.'),
    l('There is a second rhythm on top of that one. Only two streets really run through Frigiliana — Calle Real and its continuation, Calle Chorruelo — and because of the day visitors the local police usually close them from around ten or eleven in the morning until roughly five in the afternoon. Arriving before or after that window makes the last stretch far easier.', 'Dazu kommt ein zweiter Rhythmus. Durch Frigiliana führen praktisch nur zwei Straßen – die Calle Real und ihre Verlängerung, die Calle Chorruelo –, und wegen der Tagesbesucher sperrt die örtliche Polizei sie meist zwischen zehn und elf Uhr bis etwa 17 Uhr. Wer davor oder danach ankommt, hat es auf dem letzten Stück deutlich leichter.', 'A eso se suma un segundo ritmo. Por Frigiliana solo pasan realmente dos calles, la calle Real y su prolongación, la calle Chorruelo, y por la afluencia de visitantes la policía local suele cerrarlas entre las diez u once de la mañana y las cinco de la tarde. Llegar antes o después de esa franja facilita mucho el último tramo.', 'Daar komt een tweede ritme bij. Door Frigiliana lopen eigenlijk maar twee straten — Calle Real en het verlengde daarvan, Calle Chorruelo — en vanwege de dagbezoekers sluit de lokale politie ze meestal van ongeveer tien of elf uur in de ochtend tot een uur of vijf in de middag. Wie daarvoor of daarna aankomt, heeft het op het laatste stuk veel makkelijker.', 'Till det kommer en andra rytm. Genom Frigiliana går egentligen bara två gator – Calle Real och dess förlängning Calle Chorruelo – och på grund av dagsbesökarna stänger den lokala polisen dem oftast från omkring tio eller elva på förmiddagen till cirka fem på eftermiddagen. Kommer ni före eller efter det fönstret blir sista sträckan betydligt enklare.')
  ]},
  { id: 'arrival-luggage', eyebrow: l('02 · Arrival and luggage', '02 · Ankunft und Gepäck', '02 · Llegada y equipaje', '02 · Aankomst en bagage', '02 · Ankomst och bagage'), title: l('Choose the parking context, then the route to the door', 'Erst den Parkkontext wählen, dann den Weg zur Tür', 'Primero el contexto; después la ruta a la puerta', 'Eerst de parkeercontext, daarna de route naar de deur', 'Välj parkeringssammanhang, sedan vägen till dörren'), paragraphs: [
    l('The lower village around Plaza de las Tres Culturas is a practical orientation point. Historic-centre destinations can require a final walk, and the shortest-looking route is not automatically easiest with luggage.', 'Der untere Ort rund um die Plaza de las Tres Culturas ist ein praktischer Orientierungspunkt. Für Ziele in der Altstadt folgt oft ein Fußweg; die kürzeste Kartenstrecke ist mit Gepäck nicht automatisch die einfachste.', 'La zona baja alrededor de Plaza de las Tres Culturas orienta bien. Para destinos del casco histórico puede quedar un tramo a pie y la ruta más corta no siempre es la más cómoda con equipaje.', 'Het lagere dorp rond Plaza de las Tres Culturas is een praktisch oriëntatiepunt. Naar de oude kern volgt vaak een wandeling; de kortste route is met bagage niet altijd de makkelijkste.', 'Den lägre byn kring Plaza de las Tres Culturas är en praktisk orienteringspunkt. Till gamla stan återstår ofta en promenad; kortast är inte alltid enklast med bagage.'),
    l('Please do not improvise a luggage stop in a narrow street. We will show you the sensible approach for your AMARA home; you then follow the signs and keep a legal short stop separate from the place where the car finally stays.', 'Bitte improvisiert keinen Gepäckstopp in einer engen Gasse. Wir zeigen euch die sinnvolle Anfahrt zu eurem AMARA-Haus; vor Ort folgt ihr den Schildern und trennt einen legalen kurzen Halt vom endgültigen Stellplatz.', 'No improviséis una descarga en una calle estrecha. Os indicaremos la llegada adecuada a vuestra casa AMARA; después seguid las señales y separad una parada legal del lugar donde quedará el coche.', 'Improviseer geen bagagestop in een smalle straat. We tonen jullie de verstandige aanrijroute naar de AMARA-woning; volg daarna de borden en houd een legale korte stop apart van de definitieve parkeerplek.', 'Improvisera inte ett bagagestopp på en smal gata. Vi visar den lämpliga infarten till ert AMARA-boende; följ sedan skyltarna och skilj ett lagligt kort stopp från platsen där bilen ska stå.')
  ]},
  { id: 'during-stay', eyebrow: l('03 · During your stay', '03 · Während des Aufenthalts', '03 · Durante la estancia', '03 · Tijdens het verblijf', '03 · Under vistelsen'), title: l('Your car can follow a different timetable', 'Euer Auto kann einen anderen Tagesplan haben', 'El coche puede seguir otro horario', 'De auto kan een ander dagritme volgen', 'Bilen kan följa en annan dagsrytm'), paragraphs: [
    l('The car may leave for Nerja or the coast while day visitors fill the village and return later. On other days it can remain parked while you walk locally.', 'Das Auto fährt vielleicht Richtung Nerja oder Küste, während Tagesgäste den Ort füllen, und kommt später zurück. An anderen Tagen bleibt es stehen, während ihr zu Fuß unterwegs seid.', 'El coche puede salir hacia Nerja o la costa cuando llegan visitantes de día y volver más tarde. Otros días puede quedarse aparcado mientras camináis.', 'De auto kan naar Nerja of de kust vertrekken wanneer dagbezoekers komen en later terugkeren. Op andere dagen blijft hij staan terwijl jullie lopen.', 'Bilen kan åka mot Nerja eller kusten när dagsbesökarna kommer och återvända senare. Andra dagar står den kvar medan ni går.'),
    l('Plan by journey purpose rather than chasing one supposedly perfect space. Arrival, a beach day and an evening return are different parking moments.', 'Plant nach Fahrtzweck statt nach einem vermeintlich perfekten Parkplatz. Ankunft, Strandtag und Rückkehr am Abend sind unterschiedliche Situationen.', 'Planificad según el objetivo: llegada, día de playa y regreso son momentos distintos.', 'Plan per doel: aankomst, stranddag en terugkeer zijn verschillende parkeermomenten.', 'Planera efter syfte: ankomst, stranddag och kvällsretur är olika situationer.')
  ]},
  { id: 'last-mile', eyebrow: l('04 · Last mile and accessibility', '04 · Letzter Weg und Zugänglichkeit', '04 · Último tramo y accesibilidad', '04 · Laatste route en toegankelijkheid', '04 · Sista sträckan och tillgänglighet'), title: l('Distance alone tells you very little', 'Entfernung allein sagt hier fast nichts', 'La distancia por sí sola dice muy poco', 'Afstand alleen zegt hier bijna niets', 'Avstånd ensamt säger nästan ingenting'), paragraphs: [
    l('A route can include slopes, cobbles or steps. A nearby bay does not prove a step-free path, and a reduced-mobility space does not describe the whole journey to a home.', 'Ein Weg kann Steigungen, Pflaster oder Stufen enthalten. Ein naher Stellplatz beweist keine stufenfreie Route; auch ein PMR-Platz beschreibt nicht den ganzen Weg.', 'Una ruta puede incluir pendiente, empedrado o escalones. Una plaza cercana no demuestra un camino sin escalones ni describe todo el acceso.', 'Een route kan hellingen, kasseien of trappen hebben. Een nabije plaats bewijst geen trapvrije route en beschrijft niet de hele weg.', 'En väg kan ha lutningar, stenläggning eller trappor. En närliggande plats bevisar inte en stegfri rutt och beskriver inte hela vägen.'),
    l('Guests with mobility or luggage concerns need the exact property route. Describe surfaces and steps; do not rely on a broad “accessible” label.', 'Bei Mobilitäts- oder Gepäckthemen braucht ihr die konkrete Objektroute. Oberflächen und Stufen sind hilfreicher als das pauschale Wort „barrierefrei“.', 'Si hay necesidades de movilidad o equipaje, pedid la ruta exacta. Es mejor describir superficies y escalones que decir “accesible”.', 'Vraag bij mobiliteits- of bagagezorgen om de exacte woningroute. Beschrijf ondergrond en treden, niet algemeen “toegankelijk”.', 'Be om exakt boenderutt vid rörelse- eller bagagebehov. Beskriv underlag och steg i stället för att generellt säga “tillgänglig”.')
  ]},
  { id: 'seasonal-rules', eyebrow: l('05 · Seasons and rules', '05 · Saison und Regeln', '05 · Temporada y reglas', '05 · Seizoen en regels', '05 · Säsong och regler'), title: l('Historic rules need a current reading', 'Historische Regeln brauchen eine heutige Prüfung', 'Las normas históricas necesitan una lectura actual', 'Historische regels moeten actueel worden gecontroleerd', 'Historiska regler måste kontrolleras i nutid'), paragraphs: [
    l('You will find old access rules for Frigiliana online. We checked them carefully: a historic-centre ordinance started in 2011, but the town was already consulting on its repeal in 2018. That is why we do not copy an old rule onto this page and pretend it still settles today’s arrival.', 'Online findet ihr alte Zufahrtsregeln für Frigiliana. Wir haben sie sorgfältig geprüft: 2011 trat eine Altstadt-Verkehrsordnung in Kraft, doch schon 2018 beriet die Gemeinde über ihre Aufhebung. Deshalb kopieren wir keine alte Regel auf diese Seite und tun so, als würde sie eure heutige Ankunft eindeutig klären.', 'En internet encontraréis antiguas normas de acceso a Frigiliana. Las hemos revisado con cuidado: una ordenanza del casco histórico entró en vigor en 2011, pero en 2018 el Ayuntamiento ya consultaba su derogación. Por eso no copiamos una norma antigua ni fingimos que resuelve la llegada de hoy.', 'Online vinden jullie oude toegangsregels voor Frigiliana. We hebben ze zorgvuldig nagekeken: in 2011 trad een regel voor de oude kern in werking, maar in 2018 besprak de gemeente al de intrekking. Daarom kopiëren we geen oude regel alsof die de aankomst van vandaag volledig bepaalt.', 'På nätet hittar ni äldre tillträdesregler för Frigiliana. Vi har kontrollerat dem noga: en förordning för gamla stan började gälla 2011, men redan 2018 diskuterade kommunen ett upphävande. Därför kopierar vi inte en gammal regel och låtsas att den avgör dagens ankomst.'),
    l('Events, temporary controls and new signs can change the situation. Our simple advice is to read what is displayed when you arrive and never rely on an old price, time or screenshot.', 'Veranstaltungen, temporäre Regelungen und neue Schilder können die Situation verändern. Unser einfacher Rat: Lest bei der Ankunft, was tatsächlich ausgeschildert ist, und verlasst euch nicht auf alte Preise, Zeiten oder Screenshots.', 'Eventos, controles temporales y nuevas señales pueden cambiar la situación. Nuestro consejo es sencillo: leed lo que indique la señal al llegar y no confiéis en precios, horarios o capturas antiguas.', 'Evenementen, tijdelijke regels en nieuwe borden kunnen de situatie veranderen. Ons eenvoudige advies: lees bij aankomst wat er werkelijk staat en vertrouw niet op oude prijzen, tijden of screenshots.', 'Evenemang, tillfälliga regler och nya skyltar kan ändra läget. Vårt enkla råd är att läsa vad som faktiskt står när ni kommer och inte lita på gamla priser, tider eller skärmbilder.')
  ]},
  { id: 'amara-boundary', eyebrow: l('06 · Our advice for your AMARA home', '06 · Unser Rat für euer AMARA-Haus', '06 · Nuestro consejo para vuestra casa AMARA', '06 · Ons advies voor jullie AMARA-woning', '06 · Vårt råd för ert AMARA-boende'), title: l('The village plan comes first — then your exact route home', 'Erst der Dorfplan – dann euer genauer Weg zum Haus', 'Primero el plan del pueblo; después vuestra ruta exacta', 'Eerst het dorpsplan, daarna jullie exacte route', 'Först byplanen, sedan er exakta väg hem'), paragraphs: [
    l('Here we explain how parking in the village generally works. For the AMARA home you choose, we will then give you the exact practical route: where to approach, what the final walk is like and which steps belong to that particular door.', 'Hier erklären wir euch, wie das Parken im Dorf grundsätzlich funktioniert. Für das AMARA-Haus, das ihr auswählt, bekommt ihr von uns anschließend den konkreten praktischen Weg: wie ihr anfahrt, wie der letzte Fußweg aussieht und welche Stufen genau zu dieser Tür gehören.', 'Aquí os explicamos cómo funciona el aparcamiento en el pueblo en general. Para la casa AMARA que elijáis, os daremos después la ruta práctica exacta: por dónde llegar, cómo es el último tramo y qué escalones pertenecen a esa puerta.', 'Hier leggen we uit hoe parkeren in het dorp in grote lijnen werkt. Voor de AMARA-woning die jullie kiezen, geven we daarna de exacte praktische route: hoe jullie aanrijden, hoe het laatste stuk is en welke trappen bij die deur horen.', 'Här förklarar vi hur parkering i byn fungerar i stort. För det AMARA-boende ni väljer ger vi sedan den exakta praktiska vägen: hur ni kör fram, hur sista promenaden ser ut och vilka trappor som hör till just den dörren.'),
    l('Our aim is not to make the hillside sound easier than it is. We want you to know beforehand whether this beautiful village and the final walk suit you.', 'Unser Ziel ist nicht, die Hanglage einfacher klingen zu lassen, als sie ist. Wir möchten, dass ihr vorher wisst, ob dieses wunderschöne Dorf und der letzte Fußweg zu euch passen.', 'Nuestro objetivo no es hacer que la ladera parezca más fácil de lo que es. Queremos que sepáis antes si este pueblo precioso y el último tramo os encajan.', 'Ons doel is niet de helling makkelijker te laten klinken dan ze is. We willen dat jullie vooraf weten of dit prachtige dorp en het laatste stuk bij jullie passen.', 'Vårt mål är inte att få sluttningen att låta enklare än den är. Vi vill att ni i förväg vet om den vackra byn och sista promenaden passar er.')
  ]}
];

const related = [
  { token: 'getting_to_frigiliana' as const, label: l('Arrival & Mobility', 'Anreise & Mobilität', 'Llegada y movilidad', 'Aankomst & mobiliteit', 'Ankomst & mobilitet'), text: l('Airports, roads and the approach to the village.', 'Flughäfen, Straßen und die Zufahrt zum Ort.', 'Aeropuertos, carreteras y acceso al pueblo.', 'Luchthavens, wegen en de benadering van het dorp.', 'Flygplatser, vägar och infarten till byn.') },
  { token: 'frigiliana_stairs' as const, label: l('Streets & Stairs', 'Gassen & Treppen', 'Calles y escaleras', 'Straten & trappen', 'Gränder & trappor'), text: l('Understand the terrain before choosing a route.', 'Das Gelände verstehen, bevor ihr eine Route wählt.', 'Entended el terreno antes de elegir ruta.', 'Begrijp het terrein vóór de routekeuze.', 'Förstå terrängen innan ni väljer rutt.') },
  { token: 'nerja_vs_frigiliana' as const, label: l('Frigiliana or Nerja?', 'Frigiliana oder Nerja?', '¿Frigiliana o Nerja?', 'Frigiliana of Nerja?', 'Frigiliana eller Nerja?'), text: l('Compare the hillside village with a coastal base.', 'Den Hangort mit einer Küstenbasis vergleichen.', 'Comparad el pueblo en ladera con una base costera.', 'Vergelijk het hellingdorp met een kustbasis.', 'Jämför sluttningens by med en kustbas.') }
];

const sourceRows = [
  { label: l('Official street map', 'Offizieller Ortsplan', 'Callejero oficial', 'Officiële kaart', 'Officiell karta'), text: l('Orientation, not live availability.', 'Orientierung, keine Live-Verfügbarkeit.', 'Orientación, no disponibilidad.', 'Oriëntatie, geen live beschikbaarheid.', 'Orientering, inte live-tillgänglighet.'), href: 'https://www.turismofrigiliana.es/es/callejero.html' },
  { label: l('Historic traffic ordinance', 'Historische Verkehrsordnung', 'Ordenanza histórica', 'Historische verkeersregel', 'Historisk trafikförordning'), text: l('2011 source; not the full current rule.', 'Quelle von 2011; nicht der vollständige aktuelle Stand.', 'Fuente de 2011; no régimen completo actual.', 'Bron uit 2011; niet het volledige huidige regime.', 'Källa från 2011; inte hela dagens regelverk.'), href: 'https://frigiliana.es/entrada-en-vigor-de-la-ordenanza-de-regulacion-del-trafico-en-el-casco-antiguo/' },
  { label: l('Repeal consultation', 'Aufhebungskonsultation', 'Consulta de derogación', 'Intrekkingsconsultatie', 'Konsultation om upphävande'), text: l('2018 review of the earlier framework.', 'Überprüfung des früheren Rahmens im Jahr 2018.', 'Revisión del marco anterior en 2018.', 'Herziening van het oude kader in 2018.', 'Översyn av det äldre ramverket 2018.'), href: 'https://frigiliana.es/memoria-de-derogacion-ordenanza-trafico-casco-antiguo/' },
  { label: l('Frigiliana Informa', 'Frigiliana Informa', 'Frigiliana Informa', 'Frigiliana Informa', 'Frigiliana Informa'), text: l('Municipal channel for current notices and warnings.', 'Kommunaler Kanal für aktuelle Hinweise und Warnungen.', 'Canal municipal para avisos y alertas actuales.', 'Gemeentelijk kanaal voor actuele berichten.', 'Kommunal kanal för aktuella besked.'), href: 'https://frigiliana.es/toda-la-informacion-de-frigiliana-en-tu-movil/' }
];

const makeLocale = (lang: AmaraLanguage): ParkingGuideLocale => ({
  navLabel: navLabel[lang],
  hero: { eyebrow: hero.eyebrow[lang], title: hero.title[lang], standfirst: hero.standfirst[lang], note: hero.note[lang], updated: hero.updated[lang] },
  facts: facts.map((item) => ({ label: item.label[lang], value: item.value[lang] })),
  sections: sections.map((section) => ({ id: section.id, eyebrow: section.eyebrow[lang], title: section.title[lang], paragraphs: section.paragraphs.map((p) => p[lang]) })),
  related: { eyebrow: l('Continue planning', 'Weiter planen', 'Seguir planificando', 'Verder plannen', 'Planera vidare')[lang], title: l('Connect parking to the complete arrival', 'Parken mit der vollständigen Ankunft verbinden', 'Unid el aparcamiento con la llegada completa', 'Verbind parkeren met de volledige aankomst', 'Koppla parkering till hela ankomsten')[lang], links: related.map((item) => ({ token: item.token, label: item.label[lang], text: item.text[lang] })) },
  sources: { eyebrow: l('What we checked for you', 'Was wir für euch geprüft haben', 'Lo que hemos comprobado para vosotros', 'Wat we voor jullie hebben nagekeken', 'Det vi har kontrollerat åt er')[lang], title: l('Good orientation — and current signs on arrival', 'Gute Orientierung – und aktuelle Schilder bei der Ankunft', 'Buena orientación y señales actuales al llegar', 'Goede oriëntatie en actuele borden bij aankomst', 'Bra orientering och aktuella skyltar vid ankomst')[lang], intro: l('We checked the official map and the history of the access rules. They explain the village, while the current signs tell you what applies on your arrival day.', 'Wir haben den offiziellen Ortsplan und die Geschichte der Zufahrtsregeln geprüft. Sie erklären den Ort; was am Tag eurer Ankunft gilt, zeigen euch die aktuellen Schilder.', 'Hemos revisado el plano oficial y la historia de las normas de acceso. Explican el pueblo; las señales actuales os dicen qué vale el día de llegada.', 'We hebben de officiële kaart en de geschiedenis van de toegangsregels nagekeken. Die leggen het dorp uit; actuele borden vertellen wat op jullie aankomstdag geldt.', 'Vi har kontrollerat den officiella kartan och tillträdesreglernas historia. De förklarar byn; aktuella skyltar visar vad som gäller på ankomstdagen.')[lang], checked: l('Sources checked 21 August 2026', 'Quellen geprüft am 21. August 2026', 'Fuentes comprobadas el 21 de agosto de 2026', 'Bronnen gecontroleerd op 21 augustus 2026', 'Källor kontrollerade 21 augusti 2026')[lang], links: sourceRows.map((item) => ({ label: item.label[lang], text: item.text[lang], href: item.href })) },
  closing: { eyebrow: l('Arrive with the right expectation', 'Mit der richtigen Erwartung ankommen', 'Llegad con la expectativa correcta', 'Kom met de juiste verwachting', 'Anländ med rätt förväntan')[lang], title: l('Plan the car and final walk as one journey', 'Auto und letzten Fußweg als eine Reise planen', 'Planificad el coche y el último tramo como un viaje', 'Plan auto en laatste wandeling als één reis', 'Planera bilen och sista promenaden som en resa')[lang], body: l('Understand the village rhythm, accept changing availability and choose the AMARA home whose final route fits you.', 'Versteht den Ortsrhythmus, akzeptiert wechselnde Verfügbarkeit und wählt das AMARA-Haus, dessen letzter Weg zu euch passt.', 'Entended el ritmo, aceptad que la disponibilidad cambia y elegid la casa AMARA cuya ruta final os encaje.', 'Begrijp het ritme, accepteer wisselende beschikbaarheid en kies de AMARA-woning met een passende laatste route.', 'Förstå rytmen, acceptera varierande tillgång och välj AMARA-hemmet vars sista väg passar er.')[lang], locationLabel: l('Explore Frigiliana', 'Frigiliana entdecken', 'Descubrir Frigiliana', 'Ontdek Frigiliana', 'Upptäck Frigiliana')[lang], propertyLabel: l('View AMARA homes', 'AMARA-Häuser ansehen', 'Ver casas AMARA', 'Bekijk AMARA-woningen', 'Se AMARA-boenden')[lang] }
});

export const frigilianaParkingGuideContent = Object.fromEntries(langs.map((lang) => [lang, makeLocale(lang)])) as Record<AmaraLanguage, ParkingGuideLocale>;
