import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';
import { vacationRentalEntitiesByKey } from './vacationRentalEntities';
import type { WinterStaysLocale } from './winterStaysContent';

const winterRentalKeys = ['amara-farah', 'amara-lounis', 'amara-zaid', 'amara-maha'] as const;
const pelletStoveKeys = ['amara-lounis', 'amara-zaid', 'amara-maha'] as const;
const hasAmenity = (key: (typeof winterRentalKeys)[number], name: string) =>
  vacationRentalEntitiesByKey[key].amenityFeatures.some(
    (feature) => feature.name === name && feature.value === true
  );

if (
  !winterRentalKeys.every((key) => hasAmenity(key, 'heating'))
  || !winterRentalKeys.every((key) => vacationRentalEntitiesByKey[key].bathroomUnderfloorHeating)
  || !pelletStoveKeys.every((key) => hasAmenity(key, 'pelletStove'))
) {
  throw new Error('[Frigiliana Winter Stays] Winter-comfort copy is out of sync with vacationRentalEntities.');
}

const article = {
  datePublished: '2026-08-11',
  dateModified: '2026-08-21',
  authorName: 'Robert Sebastian Böhmer',
  authorType: 'Person' as const,
  authorSlug: 'amara-about-us'
};

export const frigilianaWinterStaysSeo: AmaraAuthoringSeo = {
  version: '2026-08-21-frigiliana-winter-stays-v2.0',
  pageType: 'A',
  entityKey: 'amara-brand',
  article,
  languages: {
    en: { title: 'Frigiliana in Winter: Winter Sun & Longer Stays', description: 'Discover winter in Frigiliana: quieter village days, hill walks, realistic weather planning and heated AMARA stays for a few nights to three weeks.', robots: 'index, follow', canonical: 'auto' },
    de: { title: 'Frigiliana im Winter: Wintersonne & längere Aufenthalte', description: 'Entdeckt Frigiliana im Winter: ruhigere Dorftage, Wanderungen, ehrliche Wetterplanung und beheizte AMARA-Unterkünfte für einige Nächte bis drei Wochen.', robots: 'index, follow', canonical: 'auto' },
    es: { title: 'Frigiliana en invierno: sol y estancias más largas', description: 'Descubrid Frigiliana en invierno: días tranquilos, rutas, planificación realista y alojamientos AMARA con calefacción para unas noches o hasta tres semanas.', robots: 'index, follow', canonical: 'auto' },
    nl: { title: 'Frigiliana in de winter: winterzon & langer verblijf', description: 'Ontdek Frigiliana in de winter: rustige dorpsdagen, wandelingen, eerlijke weersplanning en verwarmde AMARA-verblijven voor enkele nachten tot drie weken.', robots: 'index, follow', canonical: 'auto' },
    sv: { title: 'Frigiliana på vintern: vintersol & längre vistelser', description: 'Upptäck Frigiliana på vintern: lugnare dagar, vandring, realistisk väderplanering och uppvärmda AMARA-boenden för några nätter till tre veckor.', robots: 'index, follow', canonical: 'auto' }
  }
};

const sourceHrefs = {
  travelIntent: 'https://etc-corporate.org/reports/monitoring-sentiment-for-intra-european-travel-autumn-25-winter-2026/',
  streets: 'https://turismofrigiliana.es/es/las-calles.html',
  elFuerte: 'https://www.turismofrigiliana.es/es/el-fuerte.html'
} as const;

export const frigilianaWinterStaysContent: Record<AmaraLanguage, WinterStaysLocale> = {
  en: {
    navLabel: 'Winter Stays',
    hero: { eyebrow: 'Winter stays · Frigiliana', title: 'A winter that makes room for the village', standfirst: 'Winter in Frigiliana exchanges northern darkness and summer intensity for brighter days, quieter lanes and time outdoors whenever conditions allow. The historic village remains steep, evenings can feel cool and some plans stay weather-dependent. That is precisely why the right home matters: a comfortable base for slow mornings, hill walks, coast days and evenings indoors.', note: 'Destination facts are source-based. Home details come from AMARA’s current property records and should be checked again when booking.', updated: 'Research and property records reviewed August 2026', mark: 'WINTER' },
    facts: [
      { label: 'The appeal', value: 'Village rhythm instead of peak-season intensity' },
      { label: 'Underfoot', value: 'Narrow, winding and steep historic streets' },
      { label: 'Plan for', value: 'Flexible days and cooler evenings' },
      { label: 'At AMARA', value: 'Heating · warm bathroom floors · three pellet stoves' }
    ],
    sections: [
      { id: 'when-summer-leaves', eyebrow: '01 · Why winter', title: 'Why leave northern winter for Frigiliana?', paragraphs: ['The attraction is the combination of daylight, outdoor possibilities and a different pace. European travel research also points to fewer crowds, lower costs and avoiding extreme heat as important reasons for shifting trips away from peak months.', 'Frigiliana gives that choice a strong sense of place: white houses, a real hillside village and the Mediterranean landscape close by. Winter works best for guests who want to experience the destination rather than reproduce a summer beach holiday.'] },
      { id: 'northern-winter', eyebrow: '02 · Local winter', title: 'The village after the day visitors thin out', paragraphs: ['The historic centre does not become flat or effortless in winter. Its narrow, winding and steep lanes remain part of everyday life, while quieter periods can make it easier to notice the architecture and landscape around them.', 'Do not plan around the assumption that every restaurant or service keeps summer hours. Check what matters for your dates and treat the village’s slower rhythm as part of the stay, not as a promise that everything will be open.'] },
      { id: 'winter-light', eyebrow: '03 · A realistic day', title: 'Build the day around what the weather gives you', paragraphs: ['A good winter day might begin slowly in the village, use the clearer middle hours for the streets or a walk, and leave Nerja or the coast as an option rather than an obligation. The El Fuerte route starts in Frigiliana, but its steps and exposed terrain require a current conditions check.', 'If rain or wind changes the plan, the day is not lost. A long lunch, time at home or a cultural stop towards Nerja belongs in a realistic winter itinerary. Flexibility is more useful than a rigid checklist.'] },
      { id: 'changing-days', eyebrow: '04 · Weather boundary', title: 'Seasonal guidance is not your forecast', paragraphs: ['The climate guide explains long-term patterns, rainfall and the differences between the village and coast. For a winter stay, the practical message is simpler: bring layers, expect variation and check the official forecast before walks or longer outdoor plans.'] },
      { id: 'quieter-tarifa', eyebrow: '05 · Stay longer', title: 'From a short reset to three unhurried weeks', paragraphs: ['A few nights can provide a change of scene; one to three weeks allow routines to develop. You can alternate village days, coast days and time at home instead of trying to fit every highlight into one forecast window.', 'AMARA’s current Frigiliana offer is for holiday stays of a few nights up to three weeks. It is not presented as residential overwintering or an open-ended monthly rental. Current availability and conditions apply.'] },
      { id: 'winter-day', eyebrow: '06 · Home comfort', title: 'In winter, the house becomes part of the destination', paragraphs: ['All four AMARA stays in Frigiliana have heating and bathroom underfloor heating in the current property records. Lounis, Zaid and Maha also have pellet stoves. Those are practical differences when the evening is spent at home.', 'Historic character does not remove the need for ordinary comfort. Choose by the space, terrace and equipment that fit your stay, and confirm any feature that is decisive for you before booking.'] },
      { id: 'home-matters', eyebrow: '07 · Fit and non-fit', title: 'Who will enjoy Frigiliana in winter — and who may not', paragraphs: ['It can suit couples, walkers, slow travellers and guests who value village atmosphere more than constant entertainment. It also works well when the coast is an option but does not need to be outside the door.', 'It may be a poor fit if steep streets are a serious barrier, if guaranteed beach weather is essential or if you expect every summer business and service to operate unchanged. Honest fit is more useful than a universal recommendation.'] },
      { id: 'who-enjoys-winter', eyebrow: '08 · Plan with local context', title: 'Separate stable knowledge from today’s conditions', paragraphs: ['Use the Weather & Seasons guide for climate context and the Where to Stay guide for slopes, stairs and daily routes. Then check the forecast, current opening hours and transport for your actual dates.', 'AMARA’s role is to explain the village and the homes clearly. Personal winter routines and business recommendations will be added only when they can be dated and distinguished from general destination facts.'] },
      { id: 'amara-la-marina', eyebrow: '09 · Your winter base', title: 'Choose the Frigiliana stay that fits your winter', paragraphs: ['Farah is the more compact option, while Lounis, Zaid and Maha add pellet stoves and different private outdoor spaces. The right choice depends on how long you stay, how much time you expect to spend at home and which features matter most.', 'Start with the winter proposition, compare the individual homes and then check live availability. The page does not need a climate superlative: the real offer is a memorable village and a comfortable place to return to.'] }
    ],
    related: { eyebrow: 'Continue planning', title: 'Put climate, terrain and location together', links: [
      { token: 'weather_frigiliana', label: 'Weather & Seasons', text: 'Climate patterns, seasons and the official forecast boundary.' },
      { token: 'frigiliana_stairs', label: 'Where to Stay', text: 'Slopes, stairs and how different parts of the village affect daily life.' },
      { token: 'frigiliana_geography', label: 'Geography & Orientation', text: 'Understand the hillside village, the coast and the wider landscape.' },
      { token: 'nerja_vs_frigiliana', label: 'Frigiliana or Nerja?', text: 'Compare village life with staying directly on the coast.' }
    ] },
    sources: { eyebrow: 'Sources', title: 'Where these facts come from', intro: 'Terrain and route context come from official destination sources, the travel motives from European research, and the comfort details from our own current property records.', checked: 'Sources reviewed 21 August 2026', links: [
      { label: 'European Travel Commission · winter travel sentiment', text: 'European travel intent and the boundary between stated plans and actual bookings.', href: sourceHrefs.travelIntent },
      { label: 'Turismo de Frigiliana · historic streets', text: 'Official description of the old quarter’s narrow, winding and steep lanes.', href: sourceHrefs.streets },
      { label: 'Turismo de Frigiliana · El Fuerte', text: 'Official route context beginning in the village.', href: sourceHrefs.elFuerte }
    ] },
    closing: { eyebrow: 'Winter, without the sales fiction', title: 'Stay for the village — choose the home for the evening', body: 'Frigiliana in winter rewards guests who want atmosphere, landscape and time rather than guaranteed summer conditions. Compare the AMARA homes, decide which winter comforts matter and check current availability for your dates.', locationLabel: 'Explore Frigiliana', propertyLabel: 'Check winter availability' }
  },
  de: {
    navLabel: 'Winteraufenthalte',
    hero: { eyebrow: 'Winteraufenthalte · Frigiliana', title: 'Ein Winter mit mehr Raum für das Dorf', standfirst: 'Der Winter in Frigiliana tauscht nordeuropäische Dunkelheit und sommerliche Intensität gegen hellere Tage, ruhigere Gassen und Zeit draußen, wann immer das Wetter mitspielt. Das historische Dorf bleibt steil, Abende können kühl wirken und manche Pläne bleiben wetterabhängig. Genau deshalb zählt das richtige Zuhause: als komfortable Basis für langsame Morgen, Wanderungen, Küstentage und Abende drinnen.', note: 'Ortsfakten sind quellenbasiert. Angaben zu den Unterkünften stammen aus den aktuellen AMARA-Objektdaten und sollten bei der Buchung bestätigt werden.', updated: 'Recherche und Objektdaten geprüft im August 2026', mark: 'WINTER' },
    facts: [
      { label: 'Der Reiz', value: 'Dorfleben statt Hochsaison-Intensität' },
      { label: 'Unterwegs', value: 'Enge, verwinkelte und steile Altstadtgassen' },
      { label: 'Einplanen', value: 'Flexible Tage und kühlere Abende' },
      { label: 'Bei AMARA', value: 'Heizung · warme Badböden · drei Pelletöfen' }
    ],
    sections: [
      { id: 'when-summer-leaves', eyebrow: '01 · Warum Winter', title: 'Warum dem nordeuropäischen Winter nach Frigiliana entkommen?', paragraphs: ['Der Reiz ist die Verbindung aus Tageslicht, Möglichkeiten draußen und einem anderen Tempo. Europäische Reiseforschung nennt außerdem weniger Andrang, geringere Kosten und das Vermeiden extremer Hitze als wichtige Motive für Reisen außerhalb der Spitzenmonate.', 'Frigiliana gibt dieser Entscheidung einen unverwechselbaren Ort: weiße Häuser, ein echtes Hangdorf und die Mittelmeerlandschaft in der Nähe. Der Winter passt am besten, wenn ihr das Reiseziel erleben und keinen Sommer-Strandurlaub nachstellen möchtet.'] },
      { id: 'northern-winter', eyebrow: '02 · Lokaler Winter', title: 'Das Dorf, wenn weniger Tagesgäste unterwegs sind', paragraphs: ['Die Altstadt wird im Winter weder flach noch mühelos. Enge, verwinkelte und steile Gassen bleiben Teil des Alltags; in ruhigeren Phasen fallen Architektur und Landschaft dafür stärker auf.', 'Plant nicht mit der Annahme, dass jedes Restaurant oder jeder Service die Sommerzeiten behält. Prüft, was für eure Reisedaten wichtig ist, und versteht den langsameren Rhythmus als Teil des Aufenthalts – nicht als Versprechen, dass alles geöffnet bleibt.'] },
      { id: 'winter-light', eyebrow: '03 · Ein realistischer Tag', title: 'Nutzt, was der jeweilige Tag möglich macht', paragraphs: ['Ein guter Wintertag kann langsam im Dorf beginnen, die klareren Stunden für die Gassen oder eine Wanderung nutzen und Nerja oder die Küste als Möglichkeit offenlassen. Die Route El Fuerte beginnt in Frigiliana; Stufen und exponiertes Gelände verlangen jedoch eine aktuelle Prüfung der Bedingungen.', 'Wenn Regen oder Wind den Plan ändert, ist der Tag nicht verloren. Ein langes Mittagessen, Zeit zuhause oder ein kultureller Abstecher Richtung Nerja gehören zu einem realistischen Winterprogramm. Flexibilität ist wertvoller als eine starre Liste.'] },
      { id: 'changing-days', eyebrow: '04 · Wettergrenze', title: 'Saisonale Orientierung ist keine Vorhersage', paragraphs: ['Der Klima-Guide erklärt langfristige Muster, Niederschlag und die Unterschiede zwischen Dorf und Küste. Für euren Winteraufenthalt zählt vor allem: Kleidung in Schichten, wechselnde Bedingungen und die offizielle Vorhersage vor Wanderungen oder längeren Outdoor-Plänen.'] },
      { id: 'quieter-tarifa', eyebrow: '05 · Länger bleiben', title: 'Vom kurzen Tapetenwechsel bis zu drei ruhigen Wochen', paragraphs: ['Ein paar Nächte schaffen Abstand; in ein bis drei Wochen entstehen Routinen. Dorf-, Küsten- und Zuhause-Tage lassen sich abwechseln, statt alle Höhepunkte in ein einziges Wetterfenster zu pressen.', 'Das aktuelle Frigiliana-Angebot von AMARA umfasst Ferienaufenthalte von einigen Nächten bis zu drei Wochen. Es wird nicht als dauerhaftes Überwintern oder offene Monatsmiete angeboten. Es gelten die aktuellen Konditionen und Verfügbarkeiten.'] },
      { id: 'winter-day', eyebrow: '06 · Wohnkomfort', title: 'Im Winter wird das Zuhause Teil des Reiseziels', paragraphs: ['Alle vier AMARA-Unterkünfte in Frigiliana verfügen laut aktuellen Objektdaten über Heizung und Fußbodenheizung im Bad. Lounis, Zaid und Maha haben zusätzlich einen Pelletofen. Diese praktischen Unterschiede zählen, wenn der Abend zuhause stattfindet.', 'Historischer Charakter ersetzt keinen Alltagskomfort. Wählt nach Raum, Terrasse und Ausstattung, die zu eurem Aufenthalt passen, und bestätigt vor der Buchung jedes Merkmal, das für euch entscheidend ist.'] },
      { id: 'home-matters', eyebrow: '07 · Passt – oder passt nicht', title: 'Wer Frigiliana im Winter genießen wird', paragraphs: ['Die Jahreszeit kann zu Paaren, Wandernden, Slow Travellern und Gästen passen, denen Dorfatmosphäre wichtiger ist als ständige Unterhaltung. Sie funktioniert auch gut, wenn die Küste eine Option sein darf, aber nicht vor der Haustür liegen muss.', 'Weniger passend ist sie, wenn steile Wege ein großes Hindernis sind, garantiertes Strandwetter unverzichtbar ist oder alle Sommerangebote unverändert verfügbar sein sollen. Ehrliche Passung hilft mehr als eine pauschale Empfehlung.'] },
      { id: 'who-enjoys-winter', eyebrow: '08 · Mit Ortskenntnis planen', title: 'Trennt stabiles Wissen von den Bedingungen heute', paragraphs: ['Nutzt „Wetter & Jahreszeiten“ für den Klimakontext und „Wo übernachten“ für Steigungen, Treppen und tägliche Wege. Prüft anschließend Vorhersage, Öffnungszeiten und Verkehr für eure konkreten Reisedaten.', 'AMARA erklärt Dorf und Unterkünfte so klar wie möglich. Persönliche Winterroutinen und Empfehlungen zu Betrieben ergänzen wir nur, wenn sie datiert und sauber von allgemeinen Ortsfakten getrennt werden können.'] },
      { id: 'amara-la-marina', eyebrow: '09 · Eure Winterbasis', title: 'Wählt die Unterkunft, die zu eurem Winter passt', paragraphs: ['Farah ist die kompaktere Option; Lounis, Zaid und Maha ergänzen einen Pelletofen und unterschiedliche private Außenbereiche. Welche Unterkunft passt, hängt von Aufenthaltsdauer, Zeit zuhause und euren wichtigsten Ausstattungswünschen ab.', 'Beginnt mit dem Wintergefühl, vergleicht dann die einzelnen Unterkünfte und prüft die Live-Verfügbarkeit. Die Seite braucht keinen Klima-Superlativ: Das echte Angebot ist ein besonderes Dorf und ein komfortabler Rückzugsort.'] }
    ],
    related: { eyebrow: 'Weiter planen', title: 'Klima, Wege und Lage zusammendenken', links: [
      { token: 'weather_frigiliana', label: 'Wetter & Jahreszeiten', text: 'Klimamuster, Jahreszeiten und die Grenze zur aktuellen Vorhersage.' },
      { token: 'frigiliana_stairs', label: 'Wo übernachten', text: 'Steigungen, Treppen und die Unterschiede im Alltag der verschiedenen Lagen.' },
      { token: 'frigiliana_geography', label: 'Geografie & Orientierung', text: 'Das Hangdorf, die Küste und die größere Landschaft verstehen.' },
      { token: 'nerja_vs_frigiliana', label: 'Frigiliana oder Nerja?', text: 'Dorfleben mit einem Aufenthalt direkt an der Küste vergleichen.' }
    ] },
    sources: { eyebrow: 'Quellen', title: 'Woher diese Angaben stammen', intro: 'Gelände und Routenkontext stammen aus offiziellen Ortsquellen, die Reisemotive aus europäischer Reiseforschung und die Komfortangaben aus unseren eigenen aktuellen Objektdaten.', checked: 'Quellen geprüft am 21. August 2026', links: [
      { label: 'European Travel Commission · Reisestimmung im Winter', text: 'Europäische Reiseabsichten und die Grenze zwischen Planung und tatsächlicher Buchung.', href: sourceHrefs.travelIntent },
      { label: 'Turismo de Frigiliana · historische Gassen', text: 'Offizielle Beschreibung der engen, verwinkelten und steilen Altstadtwege.', href: sourceHrefs.streets },
      { label: 'Turismo de Frigiliana · El Fuerte', text: 'Offizieller Routenkontext mit Start im Dorf.', href: sourceHrefs.elFuerte }
    ] },
    closing: { eyebrow: 'Winter ohne Verkaufsfiktion', title: 'Kommt wegen des Dorfes – wählt das Zuhause für den Abend', body: 'Frigiliana im Winter passt zu Gästen, die Atmosphäre, Landschaft und Zeit wichtiger finden als garantierte Sommerbedingungen. Vergleicht die AMARA-Unterkünfte, entscheidet über euren Winterkomfort und prüft die aktuelle Verfügbarkeit.', locationLabel: 'Frigiliana entdecken', propertyLabel: 'Winterverfügbarkeit prüfen' }
  },
  es: {
    navLabel: 'Estancias de invierno',
    hero: { eyebrow: 'Estancias de invierno · Frigiliana', title: 'Un invierno con más espacio para el pueblo', standfirst: 'El invierno en Frigiliana cambia la oscuridad del norte y la intensidad del verano por días más luminosos, calles tranquilas y tiempo al aire libre siempre que acompañen las condiciones. El casco histórico sigue siendo empinado, las tardes pueden sentirse frescas y algunos planes dependen del tiempo. Por eso importa la casa adecuada: una base cómoda para mañanas lentas, rutas, días de costa y tardes en el interior.', note: 'Los datos del destino proceden de fuentes. La información de las casas procede de los registros actuales de AMARA y debe confirmarse al reservar.', updated: 'Investigación y datos de las casas revisados en agosto de 2026', mark: 'INVIERNO' },
    facts: [{ label: 'El atractivo', value: 'Ritmo de pueblo frente a la intensidad estival' }, { label: 'El terreno', value: 'Calles estrechas, sinuosas y empinadas' }, { label: 'Conviene prever', value: 'Días flexibles y tardes más frescas' }, { label: 'En AMARA', value: 'Calefacción · suelo radiante · tres estufas de pellets' }],
    sections: [
      { id: 'when-summer-leaves', eyebrow: '01 · Por qué invierno', title: '¿Por qué cambiar el invierno del norte por Frigiliana?', paragraphs: ['El atractivo es la combinación de luz, posibilidades al aire libre y otro ritmo. La investigación europea también señala menos aglomeraciones, ahorro y evitar el calor extremo como motivos para viajar fuera de los meses punta.', 'Frigiliana aporta un lugar con identidad: casas blancas, un pueblo real en la ladera y el paisaje mediterráneo cerca. Funciona mejor para quien quiere vivir el destino y no reproducir unas vacaciones de playa en verano.'] },
      { id: 'northern-winter', eyebrow: '02 · Invierno local', title: 'El pueblo cuando disminuyen las visitas del día', paragraphs: ['El casco histórico no deja de ser empinado en invierno. Las calles estrechas y sinuosas siguen formando parte de la vida cotidiana, aunque con menos afluencia se perciben mejor la arquitectura y el paisaje.', 'No deis por hecho que todos los negocios mantienen el horario de verano. Comprobad lo importante para vuestras fechas y entended el ritmo pausado como parte de la estancia, no como promesa de que todo estará abierto.'] },
      { id: 'winter-light', eyebrow: '03 · Un día realista', title: 'Construid el día con lo que permita el tiempo', paragraphs: ['Un buen día puede empezar despacio en el pueblo, aprovechar las horas más claras para pasear o caminar y dejar Nerja o la costa como opción. La ruta de El Fuerte parte de Frigiliana, pero sus escalones y terreno expuesto exigen comprobar las condiciones.', 'Si la lluvia o el viento cambian el plan, el día no está perdido. Una comida larga, tiempo en casa o una visita cultural hacia Nerja también forman parte de un invierno realista.'] },
      { id: 'changing-days', eyebrow: '04 · Límite meteorológico', title: 'La orientación estacional no es una previsión', paragraphs: ['La guía climática explica patrones, lluvia y diferencias entre pueblo y costa. Para la estancia importan las capas de ropa, aceptar variación y consultar la previsión oficial antes de rutas largas.', 'No trasladamos a Frigiliana la antigua afirmación climática de Torrox ni prometemos temperaturas concretas. La página debe ayudar a decidir, no convertir medias en garantías.'] },
      { id: 'quieter-tarifa', eyebrow: '05 · Quedarse más', title: 'De una pausa breve a tres semanas tranquilas', paragraphs: ['Unas noches cambian el escenario; entre una y tres semanas permiten crear rutinas y alternar pueblo, costa y casa según el tiempo.', 'La oferta actual de AMARA en Frigiliana comprende estancias vacacionales de unas noches hasta tres semanas. No se presenta como alquiler residencial o mensual abierto; rigen disponibilidad y condiciones actuales.'] },
      { id: 'winter-day', eyebrow: '06 · Confort en casa', title: 'En invierno, la casa forma parte del destino', paragraphs: ['Los cuatro alojamientos AMARA en Frigiliana tienen calefacción y suelo radiante en el baño según los registros actuales. Lounis, Zaid y Maha cuentan además con estufa de pellets.', 'El carácter histórico no sustituye la comodidad diaria. Elegid según espacio, terraza y equipamiento, y confirmad antes de reservar cualquier detalle decisivo.'] },
      { id: 'home-matters', eyebrow: '07 · Encaja o no encaja', title: 'Quién disfrutará Frigiliana en invierno', paragraphs: ['Puede encajar con parejas, senderistas y viajeros lentos que valoran el ambiente del pueblo más que el entretenimiento continuo, y con quienes quieren la costa como opción.', 'Encaja menos si las cuestas son un obstáculo serio, necesitáis tiempo de playa garantizado o esperáis que toda la oferta de verano funcione igual.'] },
      { id: 'who-enjoys-winter', eyebrow: '08 · Planificar con contexto', title: 'Separad el conocimiento estable de las condiciones actuales', paragraphs: ['Usad Clima y estaciones para el contexto y Dónde alojarse para cuestas, escaleras y recorridos. Después comprobad previsión, horarios y transporte para vuestras fechas.', 'AMARA explica pueblo y casas con claridad. Las rutinas personales y recomendaciones de negocios solo se añadirán cuando puedan fecharse y distinguirse de los hechos generales.'] },
      { id: 'amara-la-marina', eyebrow: '09 · Vuestra base', title: 'Elegid la casa que encaje con vuestro invierno', paragraphs: ['Farah es la opción más compacta; Lounis, Zaid y Maha añaden estufa de pellets y distintos espacios exteriores privados. La elección depende de duración, tiempo en casa y prioridades.', 'Comparad los alojamientos y consultad la disponibilidad real. La propuesta no necesita un superlativo climático: consiste en un pueblo singular y una casa cómoda a la que volver.'] }
    ],
    related: { eyebrow: 'Seguir planificando', title: 'Unid clima, terreno y ubicación', links: [{ token: 'weather_frigiliana', label: 'Clima y estaciones', text: 'Patrones climáticos, estaciones y previsión actual.' }, { token: 'frigiliana_stairs', label: 'Dónde alojarse', text: 'Cuestas, escaleras y diferencias prácticas entre zonas.' }, { token: 'frigiliana_geography', label: 'Geografía y orientación', text: 'El pueblo en ladera, la costa y el paisaje.' }, { token: 'nerja_vs_frigiliana', label: '¿Frigiliana o Nerja?', text: 'Comparad el pueblo con una estancia junto al mar.' }] },
    sources: { eyebrow: 'Fuentes', title: 'De dónde salen estos datos', intro: 'El terreno y las rutas proceden de fuentes oficiales, los motivos de viaje de la investigación europea y los detalles de confort de nuestros propios registros actuales.', checked: 'Fuentes revisadas el 21 de agosto de 2026', links: [{ label: 'European Travel Commission · viajes de invierno', text: 'Intención europea y diferencia entre planes y reservas.', href: sourceHrefs.travelIntent }, { label: 'Turismo de Frigiliana · calles históricas', text: 'Descripción oficial de las calles estrechas, sinuosas y empinadas.', href: sourceHrefs.streets }, { label: 'Turismo de Frigiliana · El Fuerte', text: 'Contexto oficial de la ruta que comienza en el pueblo.', href: sourceHrefs.elFuerte }] },
    closing: { eyebrow: 'Invierno sin ficción comercial', title: 'Venid por el pueblo; elegid la casa para la tarde', body: 'Frigiliana en invierno recompensa a quien busca ambiente, paisaje y tiempo, no condiciones estivales garantizadas. Comparad las casas AMARA y consultad la disponibilidad actual.', locationLabel: 'Descubrir Frigiliana', propertyLabel: 'Consultar disponibilidad' }
  },
  nl: {
    navLabel: 'Winterverblijven',
    hero: { eyebrow: 'Winterverblijven · Frigiliana', title: 'Een winter met meer ruimte voor het dorp', standfirst: 'De winter in Frigiliana verruilt noordelijke duisternis en zomerse drukte voor lichtere dagen, rustige straatjes en tijd buiten wanneer het weer meewerkt. Het historische dorp blijft steil, avonden kunnen fris aanvoelen en plannen blijven deels weersafhankelijk. Juist daarom telt het juiste huis: een comfortabele basis voor trage ochtenden, wandelingen, kustdagen en avonden binnen.', note: 'Bestemmingsfeiten zijn brongebaseerd. Huisdetails komen uit de actuele AMARA-objectgegevens en moeten bij boeking worden bevestigd.', updated: 'Onderzoek en objectgegevens gecontroleerd in augustus 2026', mark: 'WINTER' },
    facts: [{ label: 'De aantrekkingskracht', value: 'Dorpsritme in plaats van hoogseizoendrukte' }, { label: 'Onderweg', value: 'Smalle, kronkelende en steile straten' }, { label: 'Reken op', value: 'Flexibele dagen en frisse avonden' }, { label: 'Bij AMARA', value: 'Verwarming · warme badkamervloeren · drie pelletkachels' }],
    sections: [
      { id: 'when-summer-leaves', eyebrow: '01 · Waarom winter', title: 'Waarom de Noord-Europese winter inruilen voor Frigiliana?', paragraphs: ['De aantrekkingskracht is daglicht, buitenmogelijkheden en een ander tempo. Europees onderzoek noemt ook minder drukte, lagere kosten en het vermijden van extreme hitte als motieven voor reizen buiten de piekmaanden.', 'Frigiliana geeft die keuze karakter: witte huizen, een echt heuveldorp en het mediterrane landschap dichtbij. De winter past bij wie de bestemming wil beleven en geen zomerse strandvakantie wil nabootsen.'] },
      { id: 'northern-winter', eyebrow: '02 · Lokale winter', title: 'Het dorp wanneer er minder dagbezoekers zijn', paragraphs: ['De oude kern wordt in de winter niet vlak of moeiteloos. Smalle, kronkelende en steile straten blijven deel van het dagelijks leven; in rustigere periodes vallen architectuur en landschap sterker op.', 'Ga er niet van uit dat elke zaak zomeruren houdt. Controleer wat voor jullie data belangrijk is en zie het tragere ritme als onderdeel van het verblijf.'] },
      { id: 'winter-light', eyebrow: '03 · Een realistische dag', title: 'Bouw de dag rond wat het weer toelaat', paragraphs: ['Begin rustig in het dorp, gebruik heldere uren voor de straatjes of een wandeling en houd Nerja of de kust als optie. De route El Fuerte begint in Frigiliana, maar trappen en blootgesteld terrein vragen een actuele controle.', 'Verandert regen of wind het plan, dan is de dag niet verloren. Een lange lunch, tijd thuis of cultuur richting Nerja hoort bij een realistische winter.'] },
      { id: 'changing-days', eyebrow: '04 · Weersgrens', title: 'Seizoensinformatie is geen voorspelling', paragraphs: ['De klimaatgids beschrijft patronen en verschillen tussen dorp en kust. Neem laagjes mee, verwacht variatie en controleer de officiële verwachting voor langere buitenplannen.'] },
      { id: 'quieter-tarifa', eyebrow: '05 · Langer blijven', title: 'Van een korte pauze tot drie rustige weken', paragraphs: ['Enkele nachten geven afstand; één tot drie weken laten routines ontstaan en geven ruimte om dorp, kust en thuisdagen af te wisselen.', 'AMARA biedt in Frigiliana momenteel vakanties van enkele nachten tot drie weken, niet een open residentiële of maandelijkse huur. Actuele voorwaarden gelden.'] },
      { id: 'winter-day', eyebrow: '06 · Comfort thuis', title: 'In de winter wordt het huis onderdeel van de bestemming', paragraphs: ['Alle vier AMARA-verblijven hebben volgens de actuele objectgegevens verwarming en vloerverwarming in de badkamer. Lounis, Zaid en Maha hebben ook een pelletkachel.', 'Kies op ruimte, terras en uitrusting en bevestig vóór boeking ieder detail dat doorslaggevend is.'] },
      { id: 'home-matters', eyebrow: '07 · Past wel of niet', title: 'Wie Frigiliana in de winter zal waarderen', paragraphs: ['Het past bij stellen, wandelaars en langzame reizigers die dorpssfeer belangrijker vinden dan continu vermaak en de kust als optie zien.', 'Het past minder bij wie steile straten moeilijk vindt, gegarandeerd strandweer nodig heeft of verwacht dat alles als in de zomer werkt.'] },
      { id: 'who-enjoys-winter', eyebrow: '08 · Plannen met context', title: 'Scheid vaste kennis van de omstandigheden van vandaag', paragraphs: ['Gebruik Weer & seizoenen voor klimaat en Waar verblijven voor hellingen, trappen en routes. Controleer daarna verwachting, openingstijden en vervoer voor jullie data.', 'Persoonlijke routines en bedrijfstips voegen we alleen toe wanneer ze gedateerd en duidelijk als ervaring te herkennen zijn.'] },
      { id: 'amara-la-marina', eyebrow: '09 · Jullie winterbasis', title: 'Kies het verblijf dat bij jullie winter past', paragraphs: ['Farah is compacter; Lounis, Zaid en Maha voegen pelletkachels en verschillende buitenruimtes toe. De keuze hangt af van duur, tijd thuis en prioriteiten.', 'Vergelijk de huizen en controleer live beschikbaarheid. Het echte aanbod is een bijzonder dorp en een comfortabele plek om naar terug te keren.'] }
    ],
    related: { eyebrow: 'Verder plannen', title: 'Combineer klimaat, terrein en ligging', links: [{ token: 'weather_frigiliana', label: 'Weer & seizoenen', text: 'Klimaatpatronen, seizoenen en actuele verwachting.' }, { token: 'frigiliana_stairs', label: 'Waar verblijven', text: 'Hellingen, trappen en dagelijkse verschillen per zone.' }, { token: 'frigiliana_geography', label: 'Geografie & oriëntatie', text: 'Het heuveldorp, de kust en het landschap.' }, { token: 'nerja_vs_frigiliana', label: 'Frigiliana of Nerja?', text: 'Vergelijk het dorp met direct verblijf aan de kust.' }] },
    sources: { eyebrow: 'Bronnen', title: 'Waar deze gegevens vandaan komen', intro: 'Terrein en route komen uit officiële bronnen, de reismotieven uit Europees onderzoek en de comfortdetails uit onze eigen actuele objectgegevens.', checked: 'Bronnen gecontroleerd op 21 augustus 2026', links: [{ label: 'European Travel Commission · winterreizen', text: 'Europese intentie en het verschil tussen plannen en boekingen.', href: sourceHrefs.travelIntent }, { label: 'Turismo de Frigiliana · historische straten', text: 'Officiële beschrijving van smalle, kronkelende en steile straten.', href: sourceHrefs.streets }, { label: 'Turismo de Frigiliana · El Fuerte', text: 'Officiële routecontext vanuit het dorp.', href: sourceHrefs.elFuerte }] },
    closing: { eyebrow: 'Winter zonder verkoopfictie', title: 'Kom voor het dorp; kies het huis voor de avond', body: 'Frigiliana in de winter past bij gasten die sfeer, landschap en tijd waarderen boven gegarandeerde zomercondities. Vergelijk de AMARA-huizen en bekijk de actuele beschikbaarheid.', locationLabel: 'Ontdek Frigiliana', propertyLabel: 'Bekijk winterbeschikbaarheid' }
  },
  sv: {
    navLabel: 'Vintervistelser',
    hero: { eyebrow: 'Vintervistelser · Frigiliana', title: 'En vinter med mer plats för byn', standfirst: 'Vintern i Frigiliana byter nordligt mörker och sommarens intensitet mot ljusare dagar, lugnare gränder och tid utomhus när vädret tillåter. Den historiska byn är fortfarande brant, kvällarna kan kännas svala och vissa planer förblir väderberoende. Därför betyder rätt hem mycket: en bekväm bas för långsamma morgnar, vandring, kustdagar och kvällar inomhus.', note: 'Fakta om platsen bygger på källor. Hemdetaljer kommer från AMARAs aktuella objektdata och bör bekräftas vid bokning.', updated: 'Research och objektdata granskade i augusti 2026', mark: 'VINTER' },
    facts: [{ label: 'Lockelsen', value: 'Byrytm i stället för högsäsongens intensitet' }, { label: 'Under fötterna', value: 'Smala, slingrande och branta gator' }, { label: 'Planera för', value: 'Flexibla dagar och svalare kvällar' }, { label: 'Hos AMARA', value: 'Värme · varma badrumsgolv · tre pelletskaminer' }],
    sections: [
      { id: 'when-summer-leaves', eyebrow: '01 · Varför vinter', title: 'Varför lämna den nordiska vintern för Frigiliana?', paragraphs: ['Lockelsen är dagsljus, möjligheter utomhus och ett annat tempo. Europeisk forskning nämner också färre folkmassor, lägre kostnader och att undvika extrem värme som skäl att resa utanför toppmånaderna.', 'Frigiliana ger valet en tydlig plats: vita hus, en riktig by på sluttningen och medelhavslandskapet nära. Vintern passar den som vill uppleva destinationen och inte återskapa en sommarsemester.'] },
      { id: 'northern-winter', eyebrow: '02 · Lokal vinter', title: 'Byn när färre dagsbesökare är på plats', paragraphs: ['Gamla stan blir inte platt eller enkel på vintern. Smala, slingrande och branta gator förblir del av vardagen, men i lugnare perioder framträder arkitekturen och landskapet tydligare.', 'Räkna inte med att alla verksamheter håller sommartider. Kontrollera det som är viktigt för era datum och se det långsammare tempot som en del av vistelsen.'] },
      { id: 'winter-light', eyebrow: '03 · En realistisk dag', title: 'Bygg dagen kring vad vädret tillåter', paragraphs: ['Börja långsamt i byn, använd klara timmar till gränder eller vandring och låt Nerja eller kusten vara ett alternativ. El Fuerte börjar i Frigiliana men trappor och exponerad terräng kräver aktuell kontroll.', 'Om regn eller vind ändrar planen är dagen inte förlorad. En lång lunch, tid hemma eller kultur mot Nerja hör till en realistisk vinter.'] },
      { id: 'changing-days', eyebrow: '04 · Vädergräns', title: 'Säsongsvägledning är inte en prognos', paragraphs: ['Klimatguiden förklarar mönster och skillnader mellan by och kust. Ta lager, vänta variation och kontrollera den officiella prognosen före längre utomhusplaner.'] },
      { id: 'quieter-tarifa', eyebrow: '05 · Stanna längre', title: 'Från en kort paus till tre lugna veckor', paragraphs: ['Några nätter ger miljöombyte; en till tre veckor låter rutiner växa och ger utrymme för by-, kust- och hemmadagar.', 'AMARAs aktuella erbjudande i Frigiliana är semestervistelser från några nätter till tre veckor, inte öppen bostads- eller månadshyra. Aktuella villkor gäller.'] },
      { id: 'winter-day', eyebrow: '06 · Komfort hemma', title: 'På vintern blir hemmet en del av destinationen', paragraphs: ['Alla fyra AMARA-boenden har enligt aktuell objektdata värme och golvvärme i badrummet. Lounis, Zaid och Maha har också pelletskamin.', 'Välj efter yta, terrass och utrustning och bekräfta före bokning varje detalj som är avgörande för er.'] },
      { id: 'home-matters', eyebrow: '07 · Passar eller inte', title: 'Vem uppskattar Frigiliana på vintern?', paragraphs: ['Det kan passa par, vandrare och långsamma resenärer som värderar byatmosfär mer än ständig underhållning och ser kusten som ett alternativ.', 'Det passar mindre om branta gator är ett stort hinder, garanterat strandväder krävs eller allt förväntas fungera som på sommaren.'] },
      { id: 'who-enjoys-winter', eyebrow: '08 · Planera med sammanhang', title: 'Skilj stabil kunskap från dagens villkor', paragraphs: ['Använd Väder & årstider för klimat och Var ska man bo för backar, trappor och vägar. Kontrollera sedan prognos, öppettider och transport för era datum.', 'Personliga rutiner och företagstips läggs bara till när de kan dateras och tydligt märkas som erfarenhet.'] },
      { id: 'amara-la-marina', eyebrow: '09 · Er vinterbas', title: 'Välj boendet som passar er vinter', paragraphs: ['Farah är kompaktare; Lounis, Zaid och Maha erbjuder pelletskaminer och olika privata uteplatser. Valet beror på längd, tid hemma och prioriteringar.', 'Jämför hemmen och kontrollera live-tillgänglighet. Det verkliga erbjudandet är en minnesvärd by och ett bekvämt hem att återvända till.'] }
    ],
    related: { eyebrow: 'Planera vidare', title: 'Kombinera klimat, terräng och läge', links: [{ token: 'weather_frigiliana', label: 'Väder & årstider', text: 'Klimatmönster, årstider och aktuell prognos.' }, { token: 'frigiliana_stairs', label: 'Var ska man bo', text: 'Backar, trappor och vardagliga skillnader mellan områden.' }, { token: 'frigiliana_geography', label: 'Geografi & orientering', text: 'Sluttningsbyn, kusten och landskapet.' }, { token: 'nerja_vs_frigiliana', label: 'Frigiliana eller Nerja?', text: 'Jämför byliv med boende direkt vid kusten.' }] },
    sources: { eyebrow: 'Källor', title: 'Varifrån uppgifterna kommer', intro: 'Terräng och rutt kommer från officiella källor, resmotiven från europeisk forskning och komfortuppgifterna från våra egna aktuella objektdata.', checked: 'Källor granskade 21 augusti 2026', links: [{ label: 'European Travel Commission · vinterresor', text: 'Europeisk resavsikt och skillnaden mellan planer och bokningar.', href: sourceHrefs.travelIntent }, { label: 'Turismo de Frigiliana · historiska gator', text: 'Officiell beskrivning av smala, slingrande och branta gator.', href: sourceHrefs.streets }, { label: 'Turismo de Frigiliana · El Fuerte', text: 'Officiell ruttkontext från byn.', href: sourceHrefs.elFuerte }] },
    closing: { eyebrow: 'Vinter utan säljfiktion', title: 'Kom för byn; välj hemmet för kvällen', body: 'Frigiliana på vintern passar gäster som värderar atmosfär, landskap och tid mer än garanterade sommarvillkor. Jämför AMARA-hemmen och se aktuell tillgänglighet.', locationLabel: 'Upptäck Frigiliana', propertyLabel: 'Kontrollera vintertillgänglighet' }
  }
};
