import type { LocalizedText } from '../types/content';
import { resolveLocale } from '../types/content';
import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';

const l = (en: string, de: string, es: string, nl: string, sv: string): LocalizedText => ({ en, de, es, nl, sv });

export const hikingExternalLinks = {
  officialIndex: 'https://www.turismofrigiliana.es/es/rutas-de-senderismo.html',
  cruzDePinto: 'https://www.turismofrigiliana.es/es/cruz-de-pinto.html',
  higueron: 'https://www.turismofrigiliana.es/es/cahorros-del-rio-higueron.html',
  elFuerte: 'https://www.turismofrigiliana.es/es/el-fuerte.html',
  granSenda: 'https://www.gransendademalaga.es/es/etapas/lis_cd-6608/gran-senda-de-malaga-gr-249-etapa-06-frigiliana-competa',
  granSendaLibrary: 'https://www.malaga.es/medioambiente/1407/com1_md1_cd-198006/etapas-de-la-gran-senda-de-malaga',
  chillarStatus: 'https://www.nerja.es/el-acceso-al-rio-chillar-permanece-cerrado/',
  komootDiscovery: 'https://www.komoot.com/de-de/discover/Frigiliana/@36.7909126,-3.8953919/tours?sport=hike&map=true&regionId=62082&max_distance=6000'
} as const;

type HikingRouteId = 'cruz-de-pinto' | 'rio-higueron' | 'el-fuerte' | 'gr-249';

export interface HikingRoute {
  id: HikingRouteId;
  title: LocalizedText;
  bestFor: LocalizedText;
  commitment: LocalizedText;
  difficulty: LocalizedText;
  condition: LocalizedText;
  why: LocalizedText;
  access: LocalizedText;
  hike: LocalizedText;
  note: LocalizedText;
  weather: LocalizedText;
  officialHref: string;
  officialLabel: LocalizedText;
  secondaryHref?: string;
  secondaryLabel?: LocalizedText;
}

const routes: HikingRoute[] = [
  {
    id: 'cruz-de-pinto',
    title: l('Cruz de Pinto', 'Cruz de Pinto', 'Cruz de Pinto', 'Cruz de Pinto', 'Cruz de Pinto'),
    bestFor: l('A characteristic half-day panorama', 'Eine charakteristische Panorama-Halbtagestour', 'Una panorámica muy propia de Frigiliana', 'Een karakteristieke panoramatocht van een halve dag', 'En karakteristisk panoramatur för en halvdag'),
    commitment: l('Half day', 'Halber Tag', 'Media jornada', 'Halve dag', 'Halvdag'),
    difficulty: l('Moderate', 'Mittelschwer', 'Moderada', 'Gemiddeld', 'Medelsvår'),
    condition: l('Open slopes; check heat and rain', 'Offene Hänge; Hitze und Regen prüfen', 'Laderas abiertas; comprobad calor y lluvia', 'Open hellingen; controleer hitte en regen', 'Öppna sluttningar; kontrollera värme och regn'),
    why: l('Choose Cruz de Pinto when you want a proper walk without committing the whole day. Its open hillsides and coastal outlook give it a clear sense of leaving the village behind.', 'Cruz de Pinto passt, wenn ihr richtig wandern möchtet, ohne den ganzen Tag einzuplanen. An den offenen Hängen mit Küstenblick liegt das Dorf bald deutlich hinter euch.', 'Elegid Cruz de Pinto si queréis una caminata de verdad sin dedicarle el día entero. Las laderas abiertas y las vistas hacia la costa hacen que el pueblo quede pronto atrás.', 'Kies Cruz de Pinto als jullie echt willen wandelen zonder de hele dag vast te leggen. Op de open hellingen met uitzicht naar de kust laten jullie het dorp duidelijk achter je.', 'Välj Cruz de Pinto när ni vill ha en riktig vandring utan att avsätta hela dagen. De öppna sluttningarna och kustvyerna ger snabbt en tydlig känsla av att lämna byn bakom er.'),
    access: l('Leave Casa AMARA on foot and cross the historic village towards Plaza del Ingenio and the beginning of Cuesta del Apero. That is the official route area; the walk from Calle Chorruelo is access to it, not part of the published hiking route.', 'Von Casa AMARA geht ihr zu Fuß durch die Altstadt zur Plaza del Ingenio und zum Beginn der Cuesta del Apero. Dort liegt der offizielle Routenstart; der Weg ab Calle Chorruelo ist der Zugang dorthin und nicht Teil der veröffentlichten Wanderroute.', 'Desde Casa AMARA camináis por el casco histórico hacia la Plaza del Ingenio y el inicio de la Cuesta del Apero. Allí se sitúa el comienzo oficial; el trayecto desde Calle Chorruelo es el acceso, no parte de la ruta publicada.', 'Vanaf Casa AMARA lopen jullie door de historische kern naar Plaza del Ingenio en het begin van Cuesta del Apero. Daar ligt het officiële startgebied; de wandeling vanaf Calle Chorruelo is de toegang en geen deel van de gepubliceerde route.', 'Från Casa AMARA går ni genom den historiska byn mot Plaza del Ingenio och början av Cuesta del Apero. Där ligger den officiella starten; promenaden från Calle Chorruelo är anslutningen dit och ingår inte i den publicerade vandringsleden.'),
    hike: l('The official description first descends towards the Río Higuerón, follows the river briefly and then turns onto the ascent towards Cruz de Pinto. Expect natural paths and a sustained climb rather than a village stroll.', 'Die offizielle Beschreibung führt zunächst hinab zum Río Higuerón, kurz am Fluss entlang und dann in den Anstieg zur Cruz de Pinto. Rechnet mit Naturwegen und einem längeren Anstieg statt mit einem Dorfspaziergang.', 'La descripción oficial baja primero hacia el Río Higuerón, sigue brevemente el cauce y toma después la subida a la Cruz de Pinto. Es una ruta de senderos naturales y ascenso sostenido, no un paseo por el pueblo.', 'De officiële beschrijving daalt eerst af naar de Río Higuerón, volgt de rivier kort en buigt dan af naar de klim richting Cruz de Pinto. Reken op natuurpaden en een aanhoudende klim, niet op een dorpswandeling.', 'Den officiella beskrivningen går först ner mot Río Higuerón, följer floden en kort sträcka och viker sedan av upp mot Cruz de Pinto. Räkna med naturstig och en ihållande stigning, inte en bypromenad.'),
    note: l('This is our balanced choice when views matter but El Fuerte would make the day too demanding.', 'Das ist unsere ausgewogene Wahl, wenn euch Aussicht wichtig ist, El Fuerte für den Tag aber zu anspruchsvoll wäre.', 'Es nuestra opción equilibrada si buscáis vistas pero El Fuerte os exigiría demasiado ese día.', 'Dit is onze evenwichtige keuze als uitzicht belangrijk is maar El Fuerte die dag te zwaar zou zijn.', 'Det här är vårt balanserade val när utsikten är viktig men El Fuerte skulle bli för krävande den dagen.'),
    weather: l('Much of the route is exposed. On a hot day, move the walk to the cooler hours; after rain, check current trail conditions before leaving.', 'Große Teile liegen offen. Legt die Tour an heißen Tagen in die kühleren Stunden und prüft nach Regen den aktuellen Zustand der Wege.', 'Buena parte del recorrido está expuesta. En días calurosos, salid en las horas más frescas; después de lluvia, comprobad el estado actual del sendero.', 'Een groot deel ligt onbeschut. Wandel op hete dagen in de koelere uren en controleer na regen de actuele toestand van het pad.', 'Stora delar är exponerade. Välj svalare timmar under heta dagar och kontrollera ledens aktuella skick efter regn.'),
    officialHref: hikingExternalLinks.cruzDePinto,
    officialLabel: l('Official Cruz de Pinto route', 'Offizielle Route Cruz de Pinto', 'Ruta oficial de la Cruz de Pinto', 'Officiële route Cruz de Pinto', 'Officiell led till Cruz de Pinto')
  },
  {
    id: 'rio-higueron',
    title: l('Río Higuerón & Cahorros', 'Río Higuerón & Cahorros', 'Río Higuerón y Cahorros', 'Río Higuerón & Cahorros', 'Río Higuerón & Cahorros'),
    bestFor: l('Riverbed and narrow-gorge landscape', 'Flussbett und schmale Felspassagen', 'Cauce y pasos estrechos entre roca', 'Rivierbedding en smalle rotskloven', 'Flodbädd och smala klippassager'),
    commitment: l('Flexible half day', 'Flexibler halber Tag', 'Media jornada flexible', 'Flexibele halve dag', 'Flexibel halvdag'),
    difficulty: l('Moderate; conditions matter', 'Mittelschwer; Bedingungen beachten', 'Moderada; depende de las condiciones', 'Gemiddeld; omstandigheden tellen', 'Medelsvår; förhållandena avgör'),
    condition: l('Do not enter after heavy rain', 'Nach starkem Regen nicht begehen', 'No entréis después de lluvias fuertes', 'Niet betreden na zware regen', 'Gå inte in efter kraftigt regn'),
    why: l('The Higuerón offers the most distinct landscape in this selection: the route drops from the village into a river corridor and passes through the narrow cahorros.', 'Der Higuerón bietet die eigenständigste Landschaft dieser Auswahl: Vom Dorf geht es hinab in einen Flusskorridor und durch die engen Cahorros.', 'El Higuerón ofrece el paisaje más distinto de esta selección: se baja desde el pueblo al corredor del río y se atraviesan los estrechos cahorros.', 'De Higuerón biedt het meest afwijkende landschap van deze selectie: vanuit het dorp daalt de route af naar de riviercorridor en loopt door de smalle cahorros.', 'Higuerón ger den tydligast annorlunda miljön i urvalet: leden går ner från byn till flodkorridoren och genom de smala cahorros.'),
    access: l('Walk from Casa AMARA through the village towards Plaza del Ingenio and Cuesta del Apero, where the official access descends towards the river. The village walk is the connector; river conditions begin to matter once you enter the route itself.', 'Von Casa AMARA geht ihr durch den Ort zur Plaza del Ingenio und zur Cuesta del Apero, wo der offizielle Zugang zum Fluss hinabführt. Der Dorfweg ist die Verbindung; im eigentlichen Routenbereich zählen dann die Bedingungen im Flussbett.', 'Desde Casa AMARA cruzáis el pueblo hacia la Plaza del Ingenio y la Cuesta del Apero, donde el acceso oficial baja al río. El paseo urbano es la conexión; las condiciones del cauce importan al entrar en la ruta.', 'Vanaf Casa AMARA lopen jullie door het dorp naar Plaza del Ingenio en Cuesta del Apero, waar de officiële toegang naar de rivier afdaalt. De dorpswandeling is de verbinding; in de eigenlijke route worden de rivieromstandigheden bepalend.', 'Från Casa AMARA går ni genom byn mot Plaza del Ingenio och Cuesta del Apero, där den officiella anslutningen går ner mot floden. Bypromenaden är länken; inne på själva leden blir flodförhållandena avgörande.'),
    hike: l('This is natural river terrain, not a maintained waterside promenade. Water levels vary and long sections can be dry; the defining features are the rocky bed and narrow gorge passages.', 'Das ist natürliches Flussgelände und keine ausgebaute Uferpromenade. Der Wasserstand variiert, lange Abschnitte können trocken sein; prägend sind das felsige Bett und die engen Schluchtpassagen.', 'Es terreno fluvial natural, no un paseo acondicionado. El caudal varía y puede haber tramos largos secos; lo característico son el lecho rocoso y los pasos estrechos del desfiladero.', 'Dit is natuurlijk rivierterrein, geen aangelegde oeverwandeling. Het waterpeil wisselt en lange stukken kunnen droog zijn; kenmerkend zijn de rotsige bedding en nauwe kloofpassages.', 'Det här är naturlig flodterräng, inte en anlagd strandpromenad. Vattennivån varierar och långa delar kan vara torra; den steniga bädden och trånga passagerna präglar turen.'),
    note: l('Choose this for the landscape, not because you expect a continuous walk through water. Turn back if the conditions are unclear.', 'Wählt die Tour wegen der Landschaft, nicht in Erwartung eines durchgehenden Wasserwegs. Kehrt um, wenn die Bedingungen unklar sind.', 'Elegidla por el paisaje, no porque esperéis caminar continuamente por el agua. Dad la vuelta si las condiciones no están claras.', 'Kies deze tocht voor het landschap, niet omdat jullie voortdurend door water verwachten te lopen. Keer om als de omstandigheden onduidelijk zijn.', 'Välj turen för landskapet, inte för att ni räknar med att gå i vatten hela tiden. Vänd om ifall förhållandena är oklara.'),
    weather: l('Heavy rain can change a gorge quickly. Check the forecast and official local information, and choose another route when rain or runoff makes the river corridor uncertain.', 'Starker Regen kann eine Schlucht rasch verändern. Prüft Vorhersage und amtliche Hinweise und wählt eine andere Route, wenn Regen oder Abfluss den Flusskorridor unsicher machen.', 'La lluvia fuerte puede cambiar un desfiladero rápidamente. Consultad la previsión y la información oficial y elegid otra ruta si la lluvia o la escorrentía generan dudas.', 'Zware regen kan een kloof snel veranderen. Controleer de verwachting en officiële lokale informatie en kies een andere route als regen of afstroming onzekerheid geeft.', 'Kraftigt regn kan snabbt förändra en ravin. Kontrollera prognos och officiell lokal information och välj en annan led om regn eller avrinning gör flodkorridoren osäker.'),
    officialHref: hikingExternalLinks.higueron,
    officialLabel: l('Official Río Higuerón route', 'Offizielle Route Río Higuerón', 'Ruta oficial del Río Higuerón', 'Officiële route Río Higuerón', 'Officiell led vid Río Higuerón')
  },
  {
    id: 'el-fuerte',
    title: l('El Fuerte summit', 'El Fuerte · Gipfel', 'Cumbre de El Fuerte', 'Top van El Fuerte', 'El Fuerte · toppen'),
    bestFor: l('A proper mountain climb and the widest views', 'Ein richtiger Berganstieg mit weitem Blick', 'Una subida de montaña y las vistas más amplias', 'Een echte bergklim met het ruimste uitzicht', 'En riktig bergsstigning med vid utsikt'),
    commitment: l('Demanding half day', 'Anspruchsvoller halber Tag', 'Media jornada exigente', 'Zware halve dag', 'Krävande halvdag'),
    difficulty: l('Challenging', 'Anspruchsvoll', 'Exigente', 'Zwaar', 'Krävande'),
    condition: l('Steep, rocky and exposed', 'Steil, felsig und offen', 'Empinada, pedregosa y expuesta', 'Steil, rotsachtig en onbeschut', 'Brant, stenig och exponerad'),
    why: l('This is the route we would choose when the aim is a serious climb rather than a gentle walk. El Fuerte rises directly behind Frigiliana and gives the strongest mountain character in this selection.', 'Diese Route würden wir wählen, wenn ihr einen ernsthaften Anstieg statt eines sanften Spaziergangs sucht. El Fuerte steigt direkt hinter Frigiliana auf und hat in dieser Auswahl den deutlichsten Bergcharakter.', 'Es la ruta que elegiríamos si buscáis una subida seria y no un paseo suave. El Fuerte se eleva justo detrás de Frigiliana y ofrece el carácter más montañero de la selección.', 'Deze route zouden we kiezen als jullie een serieuze klim zoeken in plaats van een rustige wandeling. El Fuerte rijst direct achter Frigiliana op en heeft van deze selectie het sterkste bergkarakter.', 'Det här är leden vi skulle välja när målet är en ordentlig stigning snarare än en lugn promenad. El Fuerte reser sig direkt bakom Frigiliana och har tydligast bergskaraktär i urvalet.'),
    access: l('The formal route begins at Plaza del Ingenio. From Casa AMARA, walk through the historic village to that official start; the approach then continues towards Pozo de Lízar, where the mountain path is reached.', 'Der formale Routenstart liegt an der Plaza del Ingenio. Von Casa AMARA geht ihr durch die Altstadt dorthin; der Zustieg führt anschließend weiter zum Pozo de Lízar, wo der Bergpfad erreicht wird.', 'La ruta formal comienza en la Plaza del Ingenio. Desde Casa AMARA camináis por el casco histórico hasta ese punto; la aproximación continúa hacia el Pozo de Lízar, donde se alcanza el sendero de montaña.', 'De formele route begint op Plaza del Ingenio. Vanaf Casa AMARA lopen jullie door de historische kern naar die officiële start; de aanloop gaat vervolgens richting Pozo de Lízar, waar het bergpad begint.', 'Den formella leden börjar vid Plaza del Ingenio. Från Casa AMARA går ni genom den historiska byn dit; anslutningen fortsätter sedan mot Pozo de Lízar, där bergsstigen nås.'),
    hike: l('The route climbs on steep, rocky natural paths to the summit of the Peñón de Frigiliana. Treat it as a mountain hike: secure footwear, water and comfort with sustained ascent matter.', 'Auf steilen, felsigen Naturpfaden geht es zum Gipfel des Peñón de Frigiliana. Behandelt die Tour als Bergwanderung: sichere Schuhe, Wasser und Erfahrung mit längerem Anstieg zählen.', 'La ruta asciende por senderos naturales, empinados y pedregosos hasta la cima del Peñón de Frigiliana. Es una caminata de montaña: importan el calzado firme, el agua y sentirse cómodo con una subida sostenida.', 'De route klimt over steile, rotsachtige natuurpaden naar de top van de Peñón de Frigiliana. Behandel dit als een bergwandeling: stevige schoenen, water en vertrouwdheid met langdurig stijgen zijn belangrijk.', 'Leden stiger på branta, steniga naturstigar till toppen av Peñón de Frigiliana. Se den som en bergsvandring: stadiga skor, vatten och vana vid lång stigning spelar roll.'),
    note: l('Do not use the summit route as a substitute for the unverified shorter “viewpoints” walk. Choose the summit only when everyone in the group is ready for the full climb.', 'Nutzt die Gipfeltour nicht als Ersatz für die noch ungeprüfte kürzere „Aussichtspunkte“-Variante. Wählt den Gipfel nur, wenn alle in der Gruppe für den vollständigen Anstieg bereit sind.', 'No uséis la ruta de cumbre como sustituto de la variante corta de “miradores”, todavía sin verificar. Elegid la cima solo si todo el grupo está preparado para la subida completa.', 'Gebruik de toproute niet als vervanging voor de nog niet geverifieerde kortere “uitzichtpunten”-wandeling. Kies de top alleen als iedereen klaar is voor de volledige klim.', 'Använd inte toppturen som ersättning för den ännu overifierade kortare varianten till “utsiktsplatserna”. Välj toppen endast när hela gruppen är redo för hela stigningen.'),
    weather: l('The climb is exposed and offers little protection from strong sun. In warm weather, start in the cooler hours and reconsider the summit when heat, wind or visibility are poor.', 'Der Aufstieg liegt offen und bietet wenig Schutz vor starker Sonne. Startet bei Wärme in den kühleren Stunden und überdenkt den Gipfel bei Hitze, starkem Wind oder schlechter Sicht.', 'La subida está expuesta y ofrece poca protección frente al sol fuerte. Con calor, salid en las horas más frescas y replantead la cima si hay calor intenso, viento o mala visibilidad.', 'De klim ligt onbeschut en biedt weinig bescherming tegen felle zon. Start bij warm weer in de koelere uren en heroverweeg de top bij hitte, wind of slecht zicht.', 'Stigningen är exponerad och ger lite skydd mot stark sol. Börja under svalare timmar och avstå toppen vid kraftig värme, vind eller dålig sikt.'),
    officialHref: hikingExternalLinks.elFuerte,
    officialLabel: l('Official El Fuerte route', 'Offizielle Route El Fuerte', 'Ruta oficial de El Fuerte', 'Officiële route El Fuerte', 'Officiell led till El Fuerte')
  },
  {
    id: 'gr-249',
    title: l('GR 249 Stage 6 · Frigiliana to Cómpeta', 'GR 249 · Etappe 6 von Frigiliana nach Cómpeta', 'GR 249 · etapa 6 de Frigiliana a Cómpeta', 'GR 249 · etappe 6 van Frigiliana naar Cómpeta', 'GR 249 · etapp 6 från Frigiliana till Cómpeta'),
    bestFor: l('A committed full day on an official long-distance trail', 'Ein voller Tag auf einem offiziellen Fernwanderweg', 'Una jornada completa en un sendero oficial de gran recorrido', 'Een volle dag op een officiële langeafstandswandeling', 'En heldag på en officiell långfärdsled'),
    commitment: l('Full day; arrange the return', 'Ganzer Tag; Rückfahrt organisieren', 'Día completo; organizad la vuelta', 'Volle dag; regel de terugreis', 'Heldag; ordna återresan'),
    difficulty: l('Challenging', 'Anspruchsvoll', 'Exigente', 'Zwaar', 'Krävande'),
    condition: l('Long and point-to-point', 'Lang und ohne Rückweg zum Start', 'Larga y lineal', 'Lang en van punt naar punt', 'Lång och enkelriktad'),
    why: l('Choose Stage 6 when the walk is the whole day. It is the clearest official long-distance option from Frigiliana and continues across mountain country to Cómpeta.', 'Wählt Etappe 6, wenn die Wanderung den ganzen Tag bestimmen soll. Sie ist Frigilianas klarste offizielle Fernwanderoption und führt durch Bergland nach Cómpeta.', 'Elegid la etapa 6 cuando la caminata sea el plan de todo el día. Es la opción oficial de gran recorrido más clara desde Frigiliana y atraviesa la montaña hasta Cómpeta.', 'Kies etappe 6 als de wandeling de hele dag mag bepalen. Het is de duidelijkste officiële langeafstandsoptie vanuit Frigiliana en loopt door bergland naar Cómpeta.', 'Välj etapp 6 när vandringen får ta hela dagen. Det är det tydligaste officiella långfärdsalternativet från Frigiliana och fortsätter genom bergsterräng till Cómpeta.'),
    access: l('The official stage starts at Plaza del Ingenio. Walk there from Casa AMARA through the historic village, then follow the GR 249 rather than treating the access from Calle Chorruelo as part of the official stage.', 'Die offizielle Etappe beginnt an der Plaza del Ingenio. Geht von Casa AMARA durch die Altstadt dorthin und folgt dann dem GR 249; der Zugang ab Calle Chorruelo gehört nicht zur offiziellen Etappe.', 'La etapa oficial comienza en la Plaza del Ingenio. Llegad a pie desde Casa AMARA por el casco histórico y seguid desde allí el GR 249; el acceso desde Calle Chorruelo no forma parte de la etapa oficial.', 'De officiële etappe start op Plaza del Ingenio. Loop er vanaf Casa AMARA door de historische kern naartoe en volg daar de GR 249; de toegang vanaf Calle Chorruelo hoort niet bij de officiële etappe.', 'Den officiella etappen börjar vid Plaza del Ingenio. Gå dit från Casa AMARA genom den historiska byn och följ sedan GR 249; anslutningen från Calle Chorruelo ingår inte i den officiella etappen.'),
    hike: l('This is a long, linear mountain stage, not a loop back to Frigiliana. Use the official stage information and track, carry what the full day requires and decide how you will return from Cómpeta before setting out.', 'Das ist eine lange lineare Bergetappe und keine Runde zurück nach Frigiliana. Nutzt Etappenbeschreibung und Track, nehmt alles für den ganzen Tag mit und klärt vor dem Start die Rückfahrt ab Cómpeta.', 'Es una etapa de montaña larga y lineal, no una ruta circular de regreso a Frigiliana. Usad la ficha y el track oficiales, llevad lo necesario para el día entero y decidid antes cómo volver desde Cómpeta.', 'Dit is een lange, lineaire bergetappe en geen rondwandeling terug naar Frigiliana. Gebruik de officiële etappe-informatie en track, neem mee wat een volle dag vraagt en bepaal vooraf hoe jullie uit Cómpeta terugkomen.', 'Det här är en lång, linjär bergsetapp och ingen rundtur tillbaka till Frigiliana. Använd den officiella etappinformationen och spåret, ta med det en heldag kräver och ordna återresan från Cómpeta före start.'),
    note: l('The route is worthwhile precisely because it goes somewhere. The return plan is part of choosing it, not an afterthought at the end of the day.', 'Die Stärke der Route ist gerade, dass sie ein Ziel hat. Die Rückfahrt gehört deshalb zur Routenwahl und darf nicht erst am Tagesende geklärt werden.', 'La ruta merece la pena precisamente porque lleva a otro pueblo. La vuelta forma parte de la elección, no es algo que se resuelva al final del día.', 'De route is juist de moeite waard omdat hij ergens naartoe gaat. De terugreis hoort bij de keuze en is geen bijzaak voor het einde van de dag.', 'Leden är värd att välja just för att den leder någonstans. Återresan är en del av valet, inte något att lösa vid dagens slut.'),
    weather: l('Check temperature, daylight and warnings for the entire day, not only the conditions at breakfast in Frigiliana.', 'Prüft Temperatur, Tageslicht und Warnungen für den gesamten Tag, nicht nur das Wetter beim Frühstück in Frigiliana.', 'Comprobad temperatura, horas de luz y avisos para toda la jornada, no solo el tiempo al desayunar en Frigiliana.', 'Controleer temperatuur, daglicht en waarschuwingen voor de hele dag, niet alleen het weer bij het ontbijt in Frigiliana.', 'Kontrollera temperatur, dagsljus och varningar för hela dagen, inte bara vädret vid frukosten i Frigiliana.'),
    officialHref: hikingExternalLinks.granSenda,
    officialLabel: l('Official GR 249 Stage 6', 'Offizielle GR-249-Etappe 6', 'Etapa 6 oficial del GR 249', 'Officiële GR 249-etappe 6', 'Officiell GR 249 etapp 6'),
    secondaryHref: hikingExternalLinks.granSendaLibrary,
    secondaryLabel: l('Official documents and GPX library', 'Offizielle Dokumente und GPX-Bibliothek', 'Documentos y biblioteca GPX oficiales', 'Officiële documenten en GPX-bibliotheek', 'Officiella dokument och GPX-bibliotek')
  }
];

const ui = {
  hero: {
    kicker: l('Hiking from Frigiliana', 'Wandern ab Frigiliana', 'Senderismo desde Frigiliana', 'Wandelen vanuit Frigiliana', 'Vandring från Frigiliana'),
    title: l('Hiking in Frigiliana — routes to reach from your stay in the village', 'Wandern in Frigiliana – Routen, die ihr vom Dorf aus erreicht', 'Senderismo en Frigiliana — rutas accesibles desde vuestra estancia en el pueblo', 'Wandelen in Frigiliana — routes bereikbaar vanuit jullie verblijf in het dorp', 'Vandring i Frigiliana – leder ni når från ert boende i byn'),
    paragraphs: l('Frigiliana is a strong base for walking into the Sierra, but a useful guide does not need to list every track. We recommend four clearly different hikes: a panoramic half day, a river gorge, a serious summit and a full-day GR stage. Several can be approached on foot from Casa AMARA through the historic village. We explain that local connection and the choice each route represents; the official sources and GPX tools remain the right place for the live track and navigation.', 'Frigiliana ist ein starker Ausgangspunkt für Touren in die Sierra – ein guter Guide muss dafür aber nicht jeden Track aufzählen. Wir empfehlen vier klar unterschiedliche Wanderungen: eine Panorama-Halbtagestour, eine Flussschlucht, einen anspruchsvollen Gipfel und eine ganztägige GR-Etappe. Mehrere erreicht ihr von Casa AMARA zu Fuß durch die Altstadt. Wir erklären diese örtliche Verbindung und die jeweilige Wahl; für Track und Navigation bleiben die offiziellen Quellen und GPX-Werkzeuge zuständig.', 'Frigiliana es una base excelente para adentrarse a pie en la sierra, pero una guía útil no necesita enumerar todos los tracks. Recomendamos cuatro rutas realmente distintas: una panorámica de media jornada, un desfiladero fluvial, una cumbre exigente y una etapa GR de día completo. A varias se llega caminando desde Casa AMARA por el casco histórico. Nosotros explicamos esa conexión local y qué aporta cada elección; las fuentes oficiales y las herramientas GPX siguen siendo el lugar adecuado para el trazado y la navegación.', 'Frigiliana is een sterke uitvalsbasis om de Sierra in te wandelen, maar een nuttige gids hoeft niet elk spoor op te sommen. Wij bevelen vier duidelijk verschillende tochten aan: een panoramische halve dag, een rivierkloof, een serieuze top en een volledige GR-dagetappe. Verschillende routes zijn te voet bereikbaar vanaf Casa AMARA door de historische kern. Wij leggen die lokale verbinding en de keuze uit; officiële bronnen en GPX-tools blijven de juiste plek voor de track en navigatie.', 'Frigiliana är en stark bas för vandringar in i Sierran, men en användbar guide behöver inte lista varje spår. Vi rekommenderar fyra tydligt olika turer: en panoramisk halvdag, en flodravin, en krävande topp och en GR-etapp för en hel dag. Flera kan nås till fots från Casa AMARA genom den historiska byn. Vi förklarar den lokala anslutningen och vad varje val innebär; officiella källor och GPX-verktyg är fortfarande rätt plats för spår och navigering.'),
    imageAlt: l('Frigiliana and the foothills of the Sierra Almijara', 'Frigiliana und die Ausläufer der Sierra Almijara', 'Frigiliana y las estribaciones de la Sierra Almijara', 'Frigiliana en de uitlopers van de Sierra Almijara', 'Frigiliana och Sierra Almijaras förberg')
  },
  overview: {
    kicker: l('Four deliberate choices', 'Vier bewusste Empfehlungen', 'Cuatro elecciones deliberadas', 'Vier bewuste keuzes', 'Fyra medvetna val'),
    title: l('Which hike suits your day?', 'Welche Wanderung passt zu eurem Tag?', '¿Qué ruta encaja con vuestro día?', 'Welke wandeling past bij jullie dag?', 'Vilken vandring passar er dag?'),
    intro: l('Start with the kind of day you want, then check the official route and current conditions before leaving.', 'Beginnt mit der Art von Tag, die ihr möchtet, und prüft dann vor dem Aufbruch die offizielle Route und die aktuellen Bedingungen.', 'Empezad por el tipo de día que queréis y, antes de salir, comprobad la ruta oficial y las condiciones actuales.', 'Begin met het soort dag dat jullie willen en controleer voor vertrek de officiële route en actuele omstandigheden.', 'Börja med vilken sorts dag ni vill ha och kontrollera sedan den officiella leden och aktuella förhållanden före avfärd.'),
    labels: {
      bestFor: l('Best for', 'Am besten für', 'Ideal para', 'Beste voor', 'Bäst för'),
      commitment: l('Commitment', 'Zeitbedarf', 'Dedicación', 'Tijd', 'Tidsåtgång'),
      difficulty: l('Difficulty', 'Schwierigkeit', 'Dificultad', 'Moeilijkheid', 'Svårighet'),
      condition: l('Know before choosing', 'Vor der Wahl beachten', 'Antes de elegir', 'Voor het kiezen', 'Före valet')
    }
  },
  fromAmara: {
    kicker: l('The AMARA difference', 'Der AMARA-Unterschied', 'La diferencia AMARA', 'Het verschil van AMARA', 'Skillnaden med AMARA'),
    title: l('Hiking from Casa AMARA', 'Wandern von Casa AMARA', 'Salir a caminar desde Casa AMARA', 'Wandelen vanaf Casa AMARA', 'Vandra från Casa AMARA'),
    intro: l('Casa AMARA sits in Frigiliana’s historic village. For these routes, leaving the house on foot means walking to the documented start or join point — it does not change where the official hike begins.', 'Casa AMARA liegt in Frigilianas Altstadt. Wenn ihr zu Fuß aufbrecht, geht ihr zunächst zum dokumentierten Start oder Einstieg – der offizielle Beginn der Wanderung ändert sich dadurch nicht.', 'Casa AMARA está en el casco histórico de Frigiliana. Salir andando significa llegar primero al inicio o punto de enlace documentado; no cambia dónde comienza oficialmente la ruta.', 'Casa AMARA ligt in de historische kern van Frigiliana. Te voet vertrekken betekent eerst naar de gedocumenteerde start of aansluiting lopen; het verandert niet waar de officiële wandeling begint.', 'Casa AMARA ligger i Frigilianas historiska by. Att gå hemifrån betyder att ni först går till den dokumenterade starten eller anslutningen – det ändrar inte var den officiella vandringen börjar.'),
    steps: [l('Casa AMARA · Calle Chorruelo 5', 'Casa AMARA · Calle Chorruelo 5', 'Casa AMARA · Calle Chorruelo 5', 'Casa AMARA · Calle Chorruelo 5', 'Casa AMARA · Calle Chorruelo 5'), l('Access walk through the historic village', 'Zugang zu Fuß durch die Altstadt', 'Acceso a pie por el casco histórico', 'Toegangswandeling door de historische kern', 'Anslutning till fots genom den historiska byn'), l('Official start or route join point', 'Offizieller Start oder Routeneinstieg', 'Inicio oficial o punto de enlace', 'Officiële start of aansluiting', 'Officiell start eller anslutning'), l('The documented hiking route', 'Die dokumentierte Wanderroute', 'La ruta de senderismo documentada', 'De gedocumenteerde wandelroute', 'Den dokumenterade vandringsleden')],
    locationLabel: l('Understand Frigiliana and its setting', 'Frigilianas Lage verstehen', 'Entender Frigiliana y su entorno', 'Begrijp Frigiliana en de ligging', 'Förstå Frigiliana och dess läge')
  },
  routeLabels: {
    why: l('Why we recommend it', 'Warum wir die Route empfehlen', 'Por qué la recomendamos', 'Waarom we deze aanraden', 'Varför vi rekommenderar den'),
    from: l('From AMARA', 'Von AMARA', 'Desde AMARA', 'Vanaf AMARA', 'Från AMARA'),
    hike: l('The hike', 'Die Wanderung', 'La ruta', 'De wandeling', 'Vandringen'),
    note: l('AMARA note', 'AMARA-Hinweis', 'Nota AMARA', 'AMARA-notitie', 'AMARA-råd'),
    weather: l('Weather & timing', 'Wetter & Timing', 'Tiempo y horario', 'Weer & timing', 'Väder & tidpunkt'),
    navigate: l('Navigate', 'Navigation', 'Navegar', 'Navigeren', 'Navigera')
  },
  chillar: {
    kicker: l("A route we don't recommend right now", 'Eine Route, die wir derzeit nicht empfehlen', 'Una ruta que ahora no recomendamos', 'Een route die we nu niet aanraden', 'En led vi inte rekommenderar just nu'),
    title: l('Río Chíllar — currently closed', 'Río Chíllar – derzeit gesperrt', 'Río Chíllar — actualmente cerrado', 'Río Chíllar — momenteel gesloten', 'Río Chíllar – för närvarande stängd'),
    text: l('The classic Río Chíllar access remains officially closed as checked on 27 August 2026. Nerja cites fire-prevention and safety reasons, so we would not plan a hiking day around it or provide trailhead and navigation directions while the closure remains in place.', 'Der klassische Zugang zum Río Chíllar ist nach Prüfung am 27. August 2026 weiterhin amtlich gesperrt. Nerja nennt Brandvorsorge und Sicherheit; solange die Sperrung gilt, würden wir keinen Wandertag darum planen und keine Start- oder Navigationshinweise geben.', 'El acceso clásico al Río Chíllar sigue cerrado oficialmente, según la comprobación del 27 de agosto de 2026. Nerja cita prevención de incendios y seguridad; mientras siga cerrado, no organizaríamos un día de senderismo en torno a él ni daríamos indicaciones de acceso o navegación.', 'De klassieke toegang tot de Río Chíllar is volgens de controle van 27 augustus 2026 nog officieel gesloten. Nerja noemt brandpreventie en veiligheid; zolang de sluiting geldt, plannen wij er geen wandeldag omheen en geven we geen route- of navigatieaanwijzingen.', 'Den klassiska tillfarten till Río Chíllar är fortfarande officiellt stängd enligt kontrollen den 27 augusti 2026. Nerja anger brandförebyggande arbete och säkerhet; så länge stängningen gäller rekommenderar vi inte att planera en vandringsdag kring leden och ger inga start- eller navigeringsanvisningar.'),
    label: l('Check the official Río Chíllar status', 'Amtlichen Status des Río Chíllar prüfen', 'Consultar el estado oficial del Río Chíllar', 'Controleer de officiële status van Río Chíllar', 'Kontrollera officiell status för Río Chíllar')
  },
  weather: {
    kicker: l('Conditions decide the day', 'Die Bedingungen entscheiden', 'Las condiciones deciden el día', 'De omstandigheden bepalen de dag', 'Förhållandena avgör dagen'),
    title: l('Is today a good day for hiking?', 'Ist heute ein guter Wandertag?', '¿Es hoy un buen día para caminar?', 'Is vandaag een goede wandeldag?', 'Är det en bra dag för vandring?'),
    text: l('Exposed mountain routes can become very hot, so the cooler hours matter in warm weather. Rain changes the decision differently: a riverbed or narrow gorge can become the wrong choice even when an open route remains possible. Check the forecast, warnings and daylight before choosing the route, not after packing.', 'Offene Bergrouten können sehr heiß werden; bei Wärme zählen deshalb die kühleren Stunden. Regen verändert die Wahl anders: Ein Flussbett oder eine enge Schlucht kann ungeeignet sein, obwohl eine offene Route noch möglich ist. Prüft Vorhersage, Warnungen und Tageslicht vor der Routenwahl, nicht erst nach dem Packen.', 'Las rutas de montaña expuestas pueden calentarse mucho; con calor importan las horas más frescas. La lluvia cambia la decisión de otro modo: un cauce o un desfiladero estrecho puede dejar de ser buena opción aunque un recorrido abierto siga siendo posible. Consultad previsión, avisos y horas de luz antes de elegir.', 'Onbeschutte bergroutes kunnen zeer heet worden, dus bij warm weer zijn de koelere uren belangrijk. Regen verandert de keuze anders: een rivierbedding of nauwe kloof kan ongeschikt worden terwijl een open route nog mogelijk is. Controleer verwachting, waarschuwingen en daglicht voordat jullie kiezen.', 'Exponerade bergsleder kan bli mycket heta, så svalare timmar spelar roll i varmt väder. Regn ändrar valet på ett annat sätt: en flodbädd eller trång ravin kan bli fel val även om en öppen led fortfarande är möjlig. Kontrollera prognos, varningar och dagsljus innan ni väljer.'),
    label: l('Check Frigiliana weather and seasons', 'Wetter und Jahreszeiten in Frigiliana prüfen', 'Consultar el tiempo y las estaciones en Frigiliana', 'Bekijk weer en seizoenen in Frigiliana', 'Se väder och årstider i Frigiliana')
  },
  more: {
    title: l('Looking for more routes?', 'Sucht ihr weitere Routen?', '¿Buscáis más rutas?', 'Zoeken jullie meer routes?', 'Letar ni efter fler leder?'),
    text: l('We deliberately keep our list short. For a wider route catalogue and navigation, Komoot is the better tool; for route identity and official notices, use Turismo de Frigiliana and Gran Senda de Málaga.', 'Wir halten unsere Auswahl bewusst kurz. Für einen breiteren Routenkatalog und Navigation ist Komoot das bessere Werkzeug; für Routenidentität und amtliche Hinweise nutzt ihr Turismo de Frigiliana und die Gran Senda de Málaga.', 'Mantenemos nuestra selección corta a propósito. Para un catálogo más amplio y navegación, Komoot es mejor herramienta; para la identidad de las rutas y los avisos oficiales, acudid a Turismo de Frigiliana y la Gran Senda de Málaga.', 'We houden onze selectie bewust kort. Voor een ruimer routeaanbod en navigatie is Komoot de betere tool; voor route-identiteit en officiële berichten gebruiken jullie Turismo de Frigiliana en Gran Senda de Málaga.', 'Vi håller medvetet vårt urval kort. För en bredare ledkatalog och navigering är Komoot ett bättre verktyg; för ledidentitet och officiella besked använder ni Turismo de Frigiliana och Gran Senda de Málaga.'),
    komoot: l('Explore Frigiliana routes on Komoot', 'Frigiliana-Routen auf Komoot entdecken', 'Explorar rutas de Frigiliana en Komoot', 'Ontdek Frigiliana-routes op Komoot', 'Utforska Frigiliana-leder på Komoot'),
    official: l('Official Frigiliana hiking routes', 'Offizielle Frigiliana-Wanderrouten', 'Rutas oficiales de senderismo de Frigiliana', 'Officiële wandelroutes van Frigiliana', 'Officiella vandringsleder i Frigiliana'),
    granSenda: l('Gran Senda official stages and GPX', 'Offizielle Gran-Senda-Etappen und GPX', 'Etapas y GPX oficiales de la Gran Senda', 'Officiële Gran Senda-etappes en GPX', 'Officiella Gran Senda-etapper och GPX')
  },
  after: {
    title: l('After the hike', 'Nach der Wanderung', 'Después de la ruta', 'Na de wandeling', 'Efter vandringen'),
    items: [
      { title: l('Hungry?', 'Hungrig?', '¿Tenéis hambre?', 'Honger?', 'Hungriga?'), text: l('Choose a table in the village rather than searching when everyone is tired.', 'Wählt schon im Ort einen passenden Tisch, statt müde weiterzusuchen.', 'Elegid una mesa en el pueblo en lugar de buscar cuando ya estéis cansados.', 'Kies een tafel in het dorp in plaats van moe verder te zoeken.', 'Välj ett bord i byn i stället för att leta när alla redan är trötta.'), label: l('See our Frigiliana restaurants', 'Unsere Restaurants in Frigiliana', 'Ver nuestros restaurantes de Frigiliana', 'Bekijk onze restaurants in Frigiliana', 'Se våra restauranger i Frigiliana'), token: 'frigiliana_food_authority' as const },
      { title: l("Checking tomorrow's conditions?", 'Bedingungen für morgen prüfen?', '¿Queréis comprobar las condiciones de mañana?', 'Morgens omstandigheden bekijken?', 'Kontrollera morgondagens förhållanden?'), text: l('Use the climate guide for the seasonal pattern and the official forecast for the actual day.', 'Nutzt den Klima-Guide für das Saisonmuster und die amtliche Vorhersage für den konkreten Tag.', 'Usad la guía climática para el patrón estacional y la previsión oficial para el día concreto.', 'Gebruik de klimaatgids voor het seizoenspatroon en de officiële verwachting voor de dag zelf.', 'Använd klimatguiden för säsongsmönstret och den officiella prognosen för den aktuella dagen.'), label: l('Open Frigiliana weather', 'Wetter in Frigiliana öffnen', 'Ver el tiempo en Frigiliana', 'Open het weer voor Frigiliana', 'Öppna vädret för Frigiliana'), token: 'weather_frigiliana' as const },
      { title: l('Back to AMARA?', 'Zurück zu AMARA?', '¿De vuelta a AMARA?', 'Terug naar AMARA?', 'Tillbaka till AMARA?'), text: l('Finish in the village, come back to the house and let the rest of the day slow down.', 'Beendet die Tour im Dorf, kommt zurück ins Haus und lasst den restlichen Tag ruhiger werden.', 'Terminada la ruta en el pueblo, volved a la casa y dejad que el resto del día baje el ritmo.', 'Eindig in het dorp, kom terug naar het huis en laat de rest van de dag vertragen.', 'Avsluta i byn, kom tillbaka till huset och låt resten av dagen sakta ner.'), label: l('See our stays in Frigiliana', 'Unsere Unterkünfte in Frigiliana', 'Ver nuestros alojamientos en Frigiliana', 'Bekijk onze verblijven in Frigiliana', 'Se våra boenden i Frigiliana'), token: 'romantic_hideaways' as const }
    ]
  },
  closing: {
    title: l('Make Frigiliana your walking base', 'Frigiliana als Wanderbasis', 'Convertid Frigiliana en vuestra base para caminar', 'Maak Frigiliana jullie wandelbasis', 'Gör Frigiliana till er vandringsbas'),
    lead: l('Stay in the historic village, choose the route that fits the day and return to a place where the evening is already within walking reach.', 'Übernachtet in der Altstadt, wählt die Route passend zum Tag und kehrt an einen Ort zurück, an dem der Abend bereits zu Fuß erreichbar ist.', 'Alojaos en el casco histórico, elegid la ruta que encaje con el día y volved a un lugar desde el que la tarde y la cena quedan a pie.', 'Verblijf in de historische kern, kies de route die bij de dag past en keer terug naar een plek waar de avond al te voet bereikbaar is.', 'Bo i den historiska byn, välj leden som passar dagen och återvänd till en plats där kvällen redan finns inom gångavstånd.'),
    stays: l('See our stays in Frigiliana', 'Unsere Unterkünfte in Frigiliana', 'Ver nuestros alojamientos en Frigiliana', 'Bekijk onze verblijven in Frigiliana', 'Se våra boenden i Frigiliana'),
    book: l('Check availability', 'Verfügbarkeit prüfen', 'Consultar disponibilidad', 'Beschikbaarheid bekijken', 'Kontrollera tillgänglighet')
  }
};

export const frigilianaHikingSeo: AmaraAuthoringSeo = {
  version: '2026-08-27-frigiliana-hiking-v2.0-B', pageType: 'B', entityKey: 'amara-brand', ogImage: '/images/hero-frigiliana.jpg',
  languages: {
    en: { title: 'Hiking in Frigiliana: 4 Routes from the Historic Village', description: 'Choose four worthwhile Frigiliana hikes with official route sources, local access context from Casa AMARA and practical weather guidance.', robots: 'index, follow', canonical: 'auto' },
    de: { title: 'Wandern in Frigiliana: 4 Routen ab der Altstadt', description: 'Vier lohnende Wanderungen in Frigiliana mit offiziellen Quellen, Zugang von Casa AMARA und praktischen Wetterhinweisen.', robots: 'index, follow', canonical: 'auto' },
    es: { title: 'Senderismo en Frigiliana: 4 rutas desde el casco histórico', description: 'Cuatro rutas recomendadas en Frigiliana con fuentes oficiales, acceso desde Casa AMARA y consejos prácticos sobre el tiempo.', robots: 'index, follow', canonical: 'auto' },
    nl: { title: 'Wandelen in Frigiliana: 4 routes vanuit de historische kern', description: 'Kies vier waardevolle wandelingen in Frigiliana met officiële bronnen, toegang vanaf Casa AMARA en praktisch weeradvies.', robots: 'index, follow', canonical: 'auto' },
    sv: { title: 'Vandring i Frigiliana: 4 leder från historiska byn', description: 'Välj fyra givande vandringar i Frigiliana med officiella källor, anslutning från Casa AMARA och praktiska väderråd.', robots: 'index, follow', canonical: 'auto' }
  }
};

const t = (value: LocalizedText, lang: AmaraLanguage) => resolveLocale(value, lang);

export function getFrigilianaHikingContent(lang: AmaraLanguage) {
  return {
    hero: { kicker: t(ui.hero.kicker, lang), title: t(ui.hero.title, lang), paragraphs: [t(ui.hero.paragraphs, lang)], imageAlt: t(ui.hero.imageAlt, lang) },
    overview: { kicker: t(ui.overview.kicker, lang), title: t(ui.overview.title, lang), intro: t(ui.overview.intro, lang), labels: Object.fromEntries(Object.entries(ui.overview.labels).map(([key, value]) => [key, t(value, lang)])) as Record<keyof typeof ui.overview.labels, string> },
    fromAmara: { kicker: t(ui.fromAmara.kicker, lang), title: t(ui.fromAmara.title, lang), intro: t(ui.fromAmara.intro, lang), steps: ui.fromAmara.steps.map((step) => t(step, lang)), locationLabel: t(ui.fromAmara.locationLabel, lang) },
    routeLabels: Object.fromEntries(Object.entries(ui.routeLabels).map(([key, value]) => [key, t(value, lang)])) as Record<keyof typeof ui.routeLabels, string>,
    routes: routes.map((route) => ({ ...route, title: t(route.title, lang), bestFor: t(route.bestFor, lang), commitment: t(route.commitment, lang), difficulty: t(route.difficulty, lang), condition: t(route.condition, lang), why: t(route.why, lang), access: t(route.access, lang), hike: t(route.hike, lang), note: t(route.note, lang), weather: t(route.weather, lang), officialLabel: t(route.officialLabel, lang), secondaryLabel: route.secondaryLabel ? t(route.secondaryLabel, lang) : undefined })),
    chillar: { kicker: t(ui.chillar.kicker, lang), title: t(ui.chillar.title, lang), text: t(ui.chillar.text, lang), label: t(ui.chillar.label, lang) },
    weather: { kicker: t(ui.weather.kicker, lang), title: t(ui.weather.title, lang), text: t(ui.weather.text, lang), label: t(ui.weather.label, lang) },
    more: { title: t(ui.more.title, lang), text: t(ui.more.text, lang), komoot: t(ui.more.komoot, lang), official: t(ui.more.official, lang), granSenda: t(ui.more.granSenda, lang) },
    after: { title: t(ui.after.title, lang), items: ui.after.items.map((item) => ({ ...item, title: t(item.title, lang), text: t(item.text, lang), label: t(item.label, lang) })) },
    closing: { title: t(ui.closing.title, lang), lead: t(ui.closing.lead, lang), stays: t(ui.closing.stays, lang), book: t(ui.closing.book, lang) }
  };
}
