import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';
import { vacationRentalEntitiesByKey } from './vacationRentalEntities';
import type { WinterStaysLocale } from './winterStaysContent';

const playa = vacationRentalEntitiesByKey['amara-playa'];
const hasPlayaAmenity = (name: string) =>
  playa.amenityFeatures.some((feature) => feature.name === name && feature.value === true);

if (!['wifi', 'washingMachine', 'kitchen', 'balcony', 'elevator'].every(hasPlayaAmenity)) {
  throw new Error('[Nerja Winter Stays] AMARA Playa copy is out of sync with vacationRentalEntities.');
}

const article = {
  datePublished: '2026-08-21',
  dateModified: '2026-08-21',
  authorName: 'Robert Sebastian Böhmer',
  authorType: 'Person' as const,
  authorSlug: 'amara-about-us'
};

export const nerjaWinterStaysSeo: AmaraAuthoringSeo = {
  version: '2026-08-21-nerja-winter-stays-v1.0',
  pageType: 'A',
  entityKey: 'amara-brand',
  article,
  languages: {
    en: { title: 'Nerja in Winter: Winter Sun, Coast & Longer Stays', description: 'Plan a winter stay in Nerja around coastal walks, town life, all-weather culture and AMARA Playa — with honest limits on weather and seasonal beach services.', robots: 'index, follow', canonical: 'auto' },
    de: { title: 'Nerja im Winter: Wintersonne, Küste & längere Aufenthalte', description: 'Plant Nerja im Winter mit Küstenspaziergängen, Stadtleben, wetterfesten Kulturzielen und AMARA Playa – ohne falsche Wetter- oder Strandversprechen.', robots: 'index, follow', canonical: 'auto' },
    es: { title: 'Nerja en invierno: sol, costa y estancias más largas', description: 'Planificad Nerja en invierno con paseos costeros, vida urbana, cultura para días variables y AMARA Playa, sin promesas falsas de tiempo o playa.', robots: 'index, follow', canonical: 'auto' },
    nl: { title: 'Nerja in de winter: winterzon, kust & langer verblijf', description: 'Plan Nerja in de winter rond kustwandelingen, stadsleven, cultuur voor wisselweer en AMARA Playa — met eerlijke grenzen rond weer en stranddiensten.', robots: 'index, follow', canonical: 'auto' },
    sv: { title: 'Nerja på vintern: vintersol, kust & längre vistelser', description: 'Planera Nerja på vintern med kustpromenader, stadsliv, kultur för skiftande dagar och AMARA Playa — utan falska väder- eller strandlöften.', robots: 'index, follow', canonical: 'auto' }
  }
};

const sourceHrefs = {
  travelIntent: 'https://etc-corporate.org/reports/monitoring-sentiment-for-intra-european-travel-autumn-25-winter-2026/',
  cave: 'https://cuevadenerja.es/',
  museum: 'https://cuevadenerja.es/museodenerja/',
  lifeguards: 'https://www.nerja.es/el-servicio-de-vigilancia-y-socorrismo-de-playas-se-amplia-hasta-los-50-efectivos/'
} as const;

export const nerjaWinterStaysContent: Record<AmaraLanguage, WinterStaysLocale> = {
  en: {
    navLabel: 'Winter Stays',
    hero: { eyebrow: 'Winter stays · Nerja', title: 'Winter by the sea, with a town around you', standfirst: 'Nerja in winter is more than a search for a warmer number on a weather app. The coast remains part of everyday life, the town gives you alternatives when conditions change, and places such as the Cueva de Nerja and Museo de Nerja add genuine all-weather depth. The trade-off is important: the sea is not a heated pool, beach services are seasonal and no climate average guarantees your week.', note: 'This guide separates published opening patterns and seasonal services from general impressions. Always check current hours, sea conditions and forecasts.', updated: 'Research and destination sources reviewed August 2026', mark: 'WINTER' },
    facts: [{ label: 'The appeal', value: 'Coast, daylight and everyday town life' }, { label: 'All-weather anchors', value: 'Cueva de Nerja · Museo de Nerja' }, { label: 'Remember', value: 'Sea conditions and beach services are seasonal' }, { label: 'At AMARA Playa', value: 'Kitchen · washing machine · Wi-Fi · lift · balcony' }],
    sections: [
      { id: 'when-summer-leaves', eyebrow: '01 · Why winter', title: 'Why Nerja works beyond the beach season', paragraphs: ['Winter travel can be motivated by brighter days, fewer crowds, better value and avoiding peak heat. Nerja adds a practical advantage: coast and town sit together, so a stay does not depend on one perfect beach forecast.', 'Winter is an invitation to use the coast differently — for walks, light, views and an ordinary daily rhythm — with cultural and indoor options alongside.'] },
      { id: 'northern-winter', eyebrow: '02 · Local winter', title: 'A coastal town, not a resort switched off for the season', paragraphs: ['Nerja keeps its residents, streets, shops and cultural life through the winter, though opening hours and individual businesses change with the season.', 'What can be stated more precisely is that the Cueva de Nerja publishes a year-round 2026 opening pattern with closure dates, while Museo de Nerja publishes regular opening through the year and describes an ongoing cultural programme. Check again for your dates.'] },
      { id: 'winter-light', eyebrow: '03 · A realistic day', title: 'Coast when it is inviting, culture when it is not', paragraphs: ['A winter day can begin with a walk near Torrecilla or through the centre, continue with lunch in town and use the cave or museum when conditions make a longer coast plan less attractive.', 'Leave space in the schedule. You may get a bright terrace afternoon, a cloudy walking day or weather that makes time at home the better choice. A flexible sequence is more realistic than a list of guaranteed outdoor experiences.'] },
      { id: 'changing-days', eyebrow: '04 · Weather boundary', title: 'Milder is not the same as predictable', paragraphs: ['Nerja’s Climate & Seasons guide explains the coastal setting, seasonal rain and sea temperatures. Use it for long-term orientation, then use the current official forecast and sea information for the dates of your stay.', 'We do not borrow Málaga Airport values as if they were measured in Nerja, and we do not transfer Torrox’s historic climate superlative. Winter planning should stay useful and local without pretending the future week is known.'] },
      { id: 'quieter-tarifa', eyebrow: '05 · Stay longer', title: 'What changes when a holiday becomes a routine', paragraphs: ['A longer stay changes the questions. Grocery shopping, laundry, cooking, Wi-Fi and an easy route home matter more than fitting every landmark into two days.', 'Searches for “winter rental” can imply monthly or residential stays. AMARA Playa is presented here as a holiday home; the actual duration, price and conditions are those shown in the current booking process.'] },
      { id: 'winter-day', eyebrow: '06 · Home comfort', title: 'AMARA Playa as a compact everyday base', paragraphs: ['AMARA Playa is a 37 m² fifth-floor apartment for two with a lift. Current property records include a kitchen, washing machine, Wi-Fi and balcony — practical features when you stay long enough to develop a routine.', 'Winter suitability is not reduced to an amenity list. If temperature control, workspace or a particular sun orientation is decisive, confirm it before booking rather than relying on a general destination page.'] },
      { id: 'home-matters', eyebrow: '07 · Fit and non-fit', title: 'Who will enjoy Nerja in winter — and who may not', paragraphs: ['It can suit couples who want the coast close, everyday town life and alternatives to beach time. It also works for guests who prefer a compact base and like to move through the destination on foot.', 'It may not fit guests seeking guaranteed swimming weather, full summer beach services, a large apartment or a residential monthly let. Winter is a coastal stay with variation, not a substitute for July.'] },
      { id: 'who-enjoys-winter', eyebrow: '08 · Plan with local context', title: 'Check what changes with the season', paragraphs: ['Municipal lifeguard and surveillance services are described as seasonal summer operations. That does not mean the coast is closed; it means winter swimming and sea access require current conditions and personal judgement.', 'Use the weather, geography and where-to-stay guides for stable orientation. Recheck museum hours, transport, businesses and official safety information close to travel.'] },
      { id: 'amara-la-marina', eyebrow: '09 · Your winter base', title: 'Choose Nerja for the coast-and-town combination', paragraphs: ['AMARA Playa places two guests close to Torrecilla and central Nerja while providing the everyday basics of an apartment. Its winter value is the combination of location and routine, not an invented promise about permanent sun.', 'First decide whether that coastal-town model fits your trip. Then view the apartment and current booking conditions. If village atmosphere and a historic home matter more, compare Frigiliana before choosing.'] }
    ],
    related: { eyebrow: 'Continue planning', title: 'Connect the winter idea to the real place', links: [{ token: 'nerja_weather', label: 'Weather & Seasons', text: 'Coastal climate, sea temperature and current-forecast boundaries.' }, { token: 'nerja_where_to_stay', label: 'Where to Stay', text: 'Areas, routes and the practical meaning of staying near the coast or centre.' }, { token: 'nerja_geography', label: 'Geography & Orientation', text: 'Cliffs, beaches, town and the landscape around Nerja.' }, { token: 'nerja_daily_life', label: 'Daily Life & Essentials', text: 'Shopping, services and ordinary practical planning.' }] },
    sources: { eyebrow: 'Sources', title: 'Where these facts come from', intro: 'Published opening patterns and seasonal beach services come from official destination sources; the general winter travel motives from European research.', checked: 'Sources reviewed 21 August 2026', links: [{ label: 'European Travel Commission · winter travel sentiment', text: 'European intentions and the boundary between survey plans and bookings.', href: sourceHrefs.travelIntent }, { label: 'Cueva de Nerja · 2026 opening information', text: 'Published year-round pattern with specified closure dates.', href: sourceHrefs.cave }, { label: 'Museo de Nerja · opening and programme', text: 'Published hours and cultural activity information.', href: sourceHrefs.museum }, { label: 'Ayuntamiento de Nerja · beach surveillance', text: 'Municipal description of the seasonal summer service.', href: sourceHrefs.lifeguards }] },
    closing: { eyebrow: 'Winter on the coast, honestly explained', title: 'Choose Nerja for the life around the sea', body: 'Nerja can make winter feel more open without turning it into guaranteed summer. If coast, town and a compact apartment routine are the right combination, continue to AMARA Playa and check the current conditions for your stay.', locationLabel: 'Explore Nerja', propertyLabel: 'View AMARA Playa' }
  },
  de: {
    navLabel: 'Winteraufenthalte',
    hero: { eyebrow: 'Winteraufenthalte · Nerja', title: 'Winter am Meer – mit einer Stadt drum herum', standfirst: 'Nerja im Winter ist mehr als die Suche nach einer wärmeren Zahl in der Wetter-App. Die Küste bleibt Teil des Alltags, die Stadt bietet Alternativen bei wechselnden Bedingungen und Orte wie die Cueva de Nerja und das Museo de Nerja geben auch unbeständigen Tagen Substanz. Der wichtige Gegenpol: Das Meer ist kein beheizter Pool, Strandservices sind saisonal und kein Klimamittelwert garantiert eure Woche.', note: 'Dieser Guide trennt veröffentlichte Öffnungsmuster und saisonale Services von allgemeinen Eindrücken. Prüft Öffnungszeiten, Meer und Vorhersage aktuell.', updated: 'Recherche und Ortsquellen geprüft im August 2026', mark: 'WINTER' },
    facts: [{ label: 'Der Reiz', value: 'Küste, Tageslicht und städtischer Alltag' }, { label: 'Bei jedem Wetter', value: 'Cueva de Nerja · Museo de Nerja' }, { label: 'Wichtig', value: 'Meer und Strandservices bleiben saisonabhängig' }, { label: 'In AMARA Playa', value: 'Küche · Waschmaschine · WLAN · Aufzug · Balkon' }],
    sections: [
      { id: 'when-summer-leaves', eyebrow: '01 · Warum Winter', title: 'Warum Nerja jenseits der Strandsaison funktioniert', paragraphs: ['Winterreisen können durch hellere Tage, weniger Andrang, bessere Preise und das Vermeiden großer Hitze motiviert sein. Nerja verbindet Küste und Stadt, sodass der Aufenthalt nicht von einer perfekten Strandvorhersage abhängt.', 'Das bedeutet nicht, dass Winter wie Sommer ist. Die Küste wird anders genutzt: für Spaziergänge, Licht, Ausblicke und Alltag, ergänzt durch kulturelle und wetterfeste Optionen.'] },
      { id: 'northern-winter', eyebrow: '02 · Lokaler Winter', title: 'Eine Küstenstadt – kein Ferienort mit ausgeschaltetem Schalter', paragraphs: ['Nerja behält im Winter seine Bewohner, Straßen, Geschäfte und Kulturorte – Öffnungszeiten und einzelne Betriebe ändern sich allerdings mit der Saison.', 'Konkreter ist: Die Cueva de Nerja veröffentlicht für 2026 ein ganzjähriges Öffnungsmuster mit Schließtagen. Das Museo de Nerja nennt regelmäßige Öffnung über das Jahr und ein fortlaufendes Kulturprogramm. Prüft beides für eure Daten.'] },
      { id: 'winter-light', eyebrow: '03 · Ein realistischer Tag', title: 'Küste, wenn sie einlädt – Kultur, wenn nicht', paragraphs: ['Ein Wintertag kann mit einem Spaziergang bei Torrecilla oder durch das Zentrum beginnen, mit Mittagessen weitergehen und Höhle oder Museum einbauen, wenn längere Küstenpläne weniger attraktiv sind.', 'Lasst Spielraum: sonniger Terrassennachmittag, bewölkter Wandertag oder Zeit zuhause sind alles realistische Varianten.'] },
      { id: 'changing-days', eyebrow: '04 · Wettergrenze', title: 'Milder bedeutet nicht vorhersehbar', paragraphs: ['Der Klima-Guide erklärt Küstenlage, Regenverteilung und Wassertemperaturen. Danach zählen die offizielle Vorhersage und aktuelle Meerinformationen für eure Reisedaten.', 'Wir geben Málaga-Flughafenwerte nicht als Nerja-Messung aus und übertragen den historischen Torrox-Superlativ nicht. Nützliche Planung braucht keine falsche Sicherheit.'] },
      { id: 'quieter-tarifa', eyebrow: '05 · Länger bleiben', title: 'Was sich ändert, wenn Urlaub zur Routine wird', paragraphs: ['Bei längeren Aufenthalten werden Einkaufen, Wäsche, Kochen, WLAN und der einfache Heimweg wichtiger als ein dichtes Sehenswürdigkeitenprogramm.', '„Winter Rental“ kann Monats- oder Wohnmiete erwarten lassen. AMARA Playa wird als Ferienwohnung angeboten; Dauer, Preis und Konditionen zeigt der aktuelle Buchungsprozess.'] },
      { id: 'winter-day', eyebrow: '06 · Wohnkomfort', title: 'AMARA Playa als kompakte Alltagsbasis', paragraphs: ['AMARA Playa ist ein 37 m² großes Apartment für zwei im fünften Stock mit Aufzug. Die aktuellen Objektdaten nennen Küche, Waschmaschine, WLAN und Balkon.', 'Wenn Temperaturregelung, Arbeitsplatz oder eine bestimmte Sonnenausrichtung entscheidend sind, bestätigt diese Punkte vor der Buchung.'] },
      { id: 'home-matters', eyebrow: '07 · Passt – oder passt nicht', title: 'Wer Nerja im Winter genießen wird', paragraphs: ['Nerja kann zu Paaren passen, die Küste, städtischen Alltag und Alternativen zum Strand suchen und eine kompakte Basis bevorzugen.', 'Weniger passend ist es bei garantiertem Badewetter, vollständigem Sommer-Strandservice, viel Wohnfläche oder dem Wunsch nach offener Monatsmiete.'] },
      { id: 'who-enjoys-winter', eyebrow: '08 · Mit Ortskenntnis planen', title: 'Prüft, was sich mit der Saison verändert', paragraphs: ['Kommunale Überwachungs- und Rettungsdienste am Strand werden als saisonale Sommerangebote beschrieben. Das bedeutet nicht geschlossene Küste, sondern mehr Verantwortung für aktuelle Bedingungen.', 'Nutzt Wetter, Geografie und Wo übernachten für stabile Orientierung. Öffnungszeiten, Verkehr, Betriebe und Sicherheit prüft ihr kurz vor der Reise.'] },
      { id: 'amara-la-marina', eyebrow: '09 · Eure Winterbasis', title: 'Wählt Nerja für die Verbindung aus Küste und Stadt', paragraphs: ['AMARA Playa liegt für zwei Gäste nahe Torrecilla und dem Zentrum und bietet die praktischen Grundlagen eines Apartments. Der Winterwert liegt in Lage und Routine, nicht in einem Sonnengarantie-Versprechen.', 'Entscheidet zuerst, ob dieses Aufenthaltsmodell passt. Danach seht ihr euch Apartment und aktuelle Buchungsbedingungen an; für Dorfatmosphäre vergleicht ihr Frigiliana.'] }
    ],
    related: { eyebrow: 'Weiter planen', title: 'Die Winteridee mit dem echten Ort verbinden', links: [{ token: 'nerja_weather', label: 'Wetter & Jahreszeiten', text: 'Küstenklima, Wassertemperatur und Grenzen der Vorhersage.' }, { token: 'nerja_where_to_stay', label: 'Wo übernachten', text: 'Lagen, Wege und die praktische Bedeutung von Küsten- oder Zentrumsnähe.' }, { token: 'nerja_geography', label: 'Geografie & Orientierung', text: 'Klippen, Strände, Stadt und Landschaft.' }, { token: 'nerja_daily_life', label: 'Alltag & Versorgung', text: 'Einkaufen, Services und praktische Planung.' }] },
    sources: { eyebrow: 'Quellen', title: 'Woher diese Angaben stammen', intro: 'Öffnungsmuster und saisonale Strandservices stammen aus offiziellen Quellen, die allgemeinen Reisemotive im Winter aus europäischer Forschung.', checked: 'Quellen geprüft am 21. August 2026', links: [{ label: 'European Travel Commission · Reisestimmung im Winter', text: 'Absichten und Grenze zwischen Befragungsplan und Buchung.', href: sourceHrefs.travelIntent }, { label: 'Cueva de Nerja · Öffnungszeiten 2026', text: 'Veröffentlichtes Jahresmuster mit benannten Schließtagen.', href: sourceHrefs.cave }, { label: 'Museo de Nerja · Öffnung und Programm', text: 'Veröffentlichte Zeiten und Kulturinformationen.', href: sourceHrefs.museum }, { label: 'Ayuntamiento de Nerja · Strandüberwachung', text: 'Kommunale Beschreibung des saisonalen Sommerdienstes.', href: sourceHrefs.lifeguards }] },
    closing: { eyebrow: 'Winter an der Küste, ehrlich erklärt', title: 'Wählt Nerja für das Leben rund um das Meer', body: 'Nerja kann den Winter offener wirken lassen, ohne ihn zum garantierten Sommer zu erklären. Wenn Küste, Stadt und kompakter Apartmentalltag passen, geht weiter zu AMARA Playa.', locationLabel: 'Nerja entdecken', propertyLabel: 'AMARA Playa ansehen' }
  },
  es: {
    navLabel: 'Estancias de invierno',
    hero: { eyebrow: 'Estancias de invierno · Nerja', title: 'Invierno junto al mar, con una ciudad alrededor', standfirst: 'Nerja en invierno es más que buscar una cifra más alta en la aplicación del tiempo. La costa sigue presente en la vida diaria, la ciudad ofrece alternativas cuando cambian las condiciones y la Cueva de Nerja y el Museo de Nerja aportan contenido real para cualquier tiempo. La contrapartida importa: el mar no es una piscina climatizada, los servicios de playa son estacionales y ninguna media garantiza vuestra semana.', note: 'La guía separa horarios publicados y servicios estacionales de impresiones generales. Comprobad horarios, mar y previsión actual.', updated: 'Investigación y fuentes revisadas en agosto de 2026', mark: 'INVIERNO' },
    facts: [{ label: 'El atractivo', value: 'Costa, luz y vida cotidiana' }, { label: 'Para cualquier tiempo', value: 'Cueva de Nerja · Museo de Nerja' }, { label: 'Recordad', value: 'Mar y servicios de playa son estacionales' }, { label: 'En AMARA Playa', value: 'Cocina · lavadora · wifi · ascensor · balcón' }],
    sections: [
      { id: 'when-summer-leaves', eyebrow: '01 · Por qué invierno', title: 'Por qué Nerja funciona fuera de la temporada de playa', paragraphs: ['Los días luminosos, menos aglomeraciones, el valor y evitar el calor intenso pueden motivar el viaje. Nerja une costa y ciudad, de modo que la estancia no depende de una previsión perfecta.', 'No significa que el invierno sea verano: la costa sirve para pasear, mirar y vivir el día a día, con opciones culturales cuando cambia el tiempo.'] },
      { id: 'northern-winter', eyebrow: '02 · Invierno local', title: 'Una ciudad costera, no un complejo apagado', paragraphs: ['Nerja mantiene en invierno sus residentes, calles, comercios y vida cultural, aunque los horarios y algunos negocios cambian con la temporada.', 'La Cueva publica un patrón anual 2026 con cierres concretos; el Museo publica horarios regulares y actividad cultural durante el año. Comprobad las fechas.'] },
      { id: 'winter-light', eyebrow: '03 · Un día realista', title: 'Costa cuando invita, cultura cuando no', paragraphs: ['Podéis empezar cerca de Torrecilla o en el centro, comer en la ciudad y recurrir a la cueva o al museo si la costa no invita a un plan largo.', 'Dejad margen para terraza, paseo nublado o tiempo en casa. La flexibilidad es más realista que garantizar experiencias exteriores.'] },
      { id: 'changing-days', eyebrow: '04 · Límite meteorológico', title: 'Más suave no significa previsible', paragraphs: ['La guía climática explica costa, lluvia y mar. Para vuestras fechas importan la previsión oficial y la información marítima actual.', 'No presentamos datos del aeropuerto de Málaga como mediciones de Nerja ni trasladamos el superlativo histórico de Torrox.'] },
      { id: 'quieter-tarifa', eyebrow: '05 · Quedarse más', title: 'Cuando las vacaciones se convierten en rutina', paragraphs: ['En una estancia larga importan compra, colada, cocina, wifi y regreso sencillo más que acumular visitas.', '“Winter rental” puede sugerir alquiler mensual. AMARA Playa es vivienda turística; duración, precio y condiciones son los del proceso de reserva actual.'] },
      { id: 'winter-day', eyebrow: '06 · Confort en casa', title: 'AMARA Playa como base cotidiana compacta', paragraphs: ['AMARA Playa es un apartamento de 37 m² para dos, en la quinta planta con ascensor. Los registros actuales incluyen cocina, lavadora, wifi y balcón.', 'Si climatización, espacio de trabajo u orientación solar son decisivos, confirmadlos antes de reservar.'] },
      { id: 'home-matters', eyebrow: '07 · Encaja o no', title: 'Quién disfrutará Nerja en invierno', paragraphs: ['Puede encajar con parejas que quieren costa, vida urbana y alternativas a la playa desde una base compacta.', 'Encaja menos si necesitáis baño garantizado, todos los servicios estivales, una vivienda grande o alquiler mensual residencial.'] },
      { id: 'who-enjoys-winter', eyebrow: '08 · Planificar con contexto', title: 'Comprobad lo que cambia con la temporada', paragraphs: ['La vigilancia y el socorrismo municipal se describen como servicios estivales. La costa no está cerrada, pero exige condiciones actuales y criterio personal.', 'Usad clima, geografía y zonas para lo estable; revisad horarios, transporte y seguridad cerca del viaje.'] },
      { id: 'amara-la-marina', eyebrow: '09 · Vuestra base', title: 'Elegid Nerja por la combinación de costa y ciudad', paragraphs: ['AMARA Playa acerca a dos huéspedes a Torrecilla y al centro con los básicos cotidianos de un apartamento. Su valor está en esa combinación cotidiana.', 'Decidid si encaja el modelo costero y urbano; después consultad apartamento y condiciones. Comparad Frigiliana si preferís pueblo histórico.'] }
    ],
    related: { eyebrow: 'Seguir planificando', title: 'Conectad el invierno con el lugar real', links: [{ token: 'nerja_weather', label: 'Clima y estaciones', text: 'Clima costero, mar y límites de la previsión.' }, { token: 'nerja_where_to_stay', label: 'Dónde alojarse', text: 'Zonas, recorridos y significado práctico de costa o centro.' }, { token: 'nerja_geography', label: 'Geografía y orientación', text: 'Acantilados, playas, ciudad y paisaje.' }, { token: 'nerja_daily_life', label: 'Vida diaria y servicios', text: 'Compras, servicios y planificación.' }] },
    sources: { eyebrow: 'Fuentes', title: 'De dónde salen estos datos', intro: 'Los horarios y los servicios estacionales proceden de fuentes oficiales; los motivos generales de viaje, de la investigación europea.', checked: 'Fuentes revisadas el 21 de agosto de 2026', links: [{ label: 'European Travel Commission · invierno', text: 'Intenciones y diferencia entre planes y reservas.', href: sourceHrefs.travelIntent }, { label: 'Cueva de Nerja · horarios 2026', text: 'Patrón anual publicado con cierres.', href: sourceHrefs.cave }, { label: 'Museo de Nerja · horarios y programa', text: 'Información cultural publicada.', href: sourceHrefs.museum }, { label: 'Ayuntamiento · vigilancia de playas', text: 'Descripción del servicio estival.', href: sourceHrefs.lifeguards }] },
    closing: { eyebrow: 'Invierno en la costa, explicado con honestidad', title: 'Elegid Nerja por la vida alrededor del mar', body: 'Nerja abre el invierno sin fingir que es verano. Si encajan costa, ciudad y un apartamento compacto, continuad a AMARA Playa.', locationLabel: 'Descubrir Nerja', propertyLabel: 'Ver AMARA Playa' }
  },
  nl: {
    navLabel: 'Winterverblijven',
    hero: { eyebrow: 'Winterverblijven · Nerja', title: 'Winter aan zee, met een stad eromheen', standfirst: 'Nerja in de winter is meer dan zoeken naar een warmer getal in een weerapp. De kust blijft deel van het dagelijks leven, de stad biedt alternatieven wanneer omstandigheden veranderen en de Cueva de Nerja en het Museo de Nerja geven wisselende dagen echte inhoud. De keerzijde telt: de zee is geen verwarmd zwembad, stranddiensten zijn seizoensgebonden en geen klimaatgemiddelde garandeert jullie week.', note: 'De gids scheidt gepubliceerde openingstijden en seizoensdiensten van algemene indrukken. Controleer actuele uren, zee en verwachting.', updated: 'Onderzoek en bronnen gecontroleerd in augustus 2026', mark: 'WINTER' },
    facts: [{ label: 'De aantrekkingskracht', value: 'Kust, daglicht en dagelijks stadsleven' }, { label: 'Voor elk weer', value: 'Cueva de Nerja · Museo de Nerja' }, { label: 'Onthoud', value: 'Zee en stranddiensten zijn seizoensgebonden' }, { label: 'In AMARA Playa', value: 'Keuken · wasmachine · wifi · lift · balkon' }],
    sections: [
      { id: 'when-summer-leaves', eyebrow: '01 · Waarom winter', title: 'Waarom Nerja buiten het strandseizoen werkt', paragraphs: ['Lichtere dagen, minder drukte, waarde en het vermijden van hitte kunnen motieven zijn. Nerja combineert kust en stad, zodat het verblijf niet van één perfecte stranddag afhangt.', 'Winter is geen zomer: gebruik de kust voor wandelen, licht en uitzicht, met cultuur als het weer verandert.'] },
      { id: 'northern-winter', eyebrow: '02 · Lokale winter', title: 'Een kuststad, geen resort dat wordt uitgeschakeld', paragraphs: ['Nerja houdt bewoners, straten en cultuur, maar we zeggen niet dat alles precies als in de zomer draait. Uren veranderen.', 'De grot publiceert voor 2026 een jaarpatroon met sluitingsdagen; het museum regelmatige uren en een cultureel programma. Controleer jullie data.'] },
      { id: 'winter-light', eyebrow: '03 · Een realistische dag', title: 'Kust wanneer het uitnodigt, cultuur wanneer niet', paragraphs: ['Begin bij Torrecilla of in het centrum, lunch in de stad en kies grot of museum wanneer een lang kustplan minder aantrekkelijk is.', 'Laat ruimte voor terras, bewolkte wandeling of thuisblijven. Flexibiliteit is realistischer dan garanties.'] },
      { id: 'changing-days', eyebrow: '04 · Weersgrens', title: 'Zachter is niet hetzelfde als voorspelbaar', paragraphs: ['De klimaatgids legt kust, regen en zee uit. Gebruik daarna actuele officiële verwachting en zee-informatie.', 'We presenteren Málaga Airport niet als Nerja-meting en nemen Torrox’ historische superlatief niet over.'] },
      { id: 'quieter-tarifa', eyebrow: '05 · Langer blijven', title: 'Wanneer vakantie routine wordt', paragraphs: ['Boodschappen, wassen, koken, wifi en eenvoudig thuiskomen worden belangrijker dan elk hoogtepunt in twee dagen.', '“Winter rental” kan maandhuur suggereren. AMARA Playa is vakantieverblijf; actuele boeking toont duur, prijs en voorwaarden.'] },
      { id: 'winter-day', eyebrow: '06 · Comfort thuis', title: 'AMARA Playa als compacte dagelijkse basis', paragraphs: ['AMARA Playa is 37 m² voor twee op de vijfde verdieping met lift. Actuele objectdata noemt keuken, wasmachine, wifi en balkon.', 'Bevestig klimaatregeling, werkplek of zonligging als die beslissend zijn.'] },
      { id: 'home-matters', eyebrow: '07 · Past wel of niet', title: 'Wie Nerja in de winter waardeert', paragraphs: ['Het past bij stellen die kust, stadsleven en alternatieven voor strandtijd vanuit een compacte basis zoeken.', 'Minder bij gegarandeerd zwemweer, volledige zomerdiensten, veel woonruimte of residentiële maandhuur.'] },
      { id: 'who-enjoys-winter', eyebrow: '08 · Plannen met context', title: 'Controleer wat per seizoen verandert', paragraphs: ['Gemeentelijke strandbewaking en redding worden als zomerdienst beschreven. De kust is niet dicht, maar actuele omstandigheden tellen.', 'Gebruik weer, geografie en verblijfszones voor vaste context; controleer uren, vervoer en veiligheid kort voor vertrek.'] },
      { id: 'amara-la-marina', eyebrow: '09 · Jullie basis', title: 'Kies Nerja voor kust én stad', paragraphs: ['AMARA Playa brengt twee gasten dicht bij Torrecilla en het centrum met dagelijkse appartementbasis. De waarde is ligging en routine, geen zonbelofte.', 'Bepaal eerst of dit model past; bekijk dan appartement en voorwaarden. Vergelijk Frigiliana voor historische dorpssfeer.'] }
    ],
    related: { eyebrow: 'Verder plannen', title: 'Verbind het winteridee met de echte plek', links: [{ token: 'nerja_weather', label: 'Weer & seizoenen', text: 'Kustklimaat, zee en voorspellingsgrenzen.' }, { token: 'nerja_where_to_stay', label: 'Waar verblijven', text: 'Gebieden, routes en kust- of centrumligging.' }, { token: 'nerja_geography', label: 'Geografie & oriëntatie', text: 'Kliffen, stranden, stad en landschap.' }, { token: 'nerja_daily_life', label: 'Dagelijks leven', text: 'Winkels, diensten en planning.' }] },
    sources: { eyebrow: 'Bronnen', title: 'Waar deze gegevens vandaan komen', intro: 'Openingstijden en seizoensdiensten komen uit officiële bronnen, de algemene winterse reismotieven uit Europees onderzoek.', checked: 'Bronnen gecontroleerd op 21 augustus 2026', links: [{ label: 'European Travel Commission · winter', text: 'Intenties versus boekingen.', href: sourceHrefs.travelIntent }, { label: 'Cueva de Nerja · uren 2026', text: 'Gepubliceerd jaarpatroon.', href: sourceHrefs.cave }, { label: 'Museo de Nerja · uren en programma', text: 'Gepubliceerde cultuurinformatie.', href: sourceHrefs.museum }, { label: 'Gemeente · strandbewaking', text: 'Beschrijving zomerdienst.', href: sourceHrefs.lifeguards }] },
    closing: { eyebrow: 'Winter aan de kust, eerlijk uitgelegd', title: 'Kies Nerja voor het leven rond de zee', body: 'Nerja kan winter opener maken zonder gegarandeerde zomer te beloven. Past kust, stad en compact appartementleven, ga dan door naar AMARA Playa.', locationLabel: 'Ontdek Nerja', propertyLabel: 'Bekijk AMARA Playa' }
  },
  sv: {
    navLabel: 'Vintervistelser',
    hero: { eyebrow: 'Vintervistelser · Nerja', title: 'Vinter vid havet, med en stad omkring er', standfirst: 'Nerja på vintern är mer än att leta efter en varmare siffra i en väderapp. Kusten är kvar i vardagen, staden ger alternativ när villkoren skiftar och Cueva de Nerja samt Museo de Nerja ger verkligt innehåll för alla väder. Motvikten är viktig: havet är ingen uppvärmd pool, strandtjänster är säsongsbundna och inget klimatmedel garanterar er vecka.', note: 'Guiden skiljer publicerade öppningsmönster och säsongstjänster från allmänna intryck. Kontrollera aktuella tider, hav och prognos.', updated: 'Research och platskällor granskade i augusti 2026', mark: 'VINTER' },
    facts: [{ label: 'Lockelsen', value: 'Kust, dagsljus och vardagligt stadsliv' }, { label: 'För alla väder', value: 'Cueva de Nerja · Museo de Nerja' }, { label: 'Kom ihåg', value: 'Hav och strandtjänster är säsongsbundna' }, { label: 'I AMARA Playa', value: 'Kök · tvättmaskin · wifi · hiss · balkong' }],
    sections: [
      { id: 'when-summer-leaves', eyebrow: '01 · Varför vinter', title: 'Varför Nerja fungerar utanför strandsäsongen', paragraphs: ['Ljusare dagar, färre folkmassor, värde och att undvika stark värme kan motivera resan. Nerja kombinerar kust och stad så vistelsen inte beror på en perfekt strandprognos.', 'Vintern är inte sommar: använd kusten för promenader, ljus och utsikt, med kultur när vädret skiftar.'] },
      { id: 'northern-winter', eyebrow: '02 · Lokal vinter', title: 'En kuststad, inte en avstängd semesterort', paragraphs: ['Nerja behåller sina boende, gator, butiker och sitt kulturliv på vintern – öppettider och enskilda verksamheter ändras dock med säsongen.', 'Grottan publicerar ett årsmönster för 2026 med stängningsdagar; museet regelbundna tider och kulturprogram. Kontrollera era datum.'] },
      { id: 'winter-light', eyebrow: '03 · En realistisk dag', title: 'Kust när den lockar, kultur när den inte gör det', paragraphs: ['Börja vid Torrecilla eller i centrum, ät lunch i stan och välj grotta eller museum när en lång kustplan känns mindre bra.', 'Lämna utrymme för terrass, molnig promenad eller tid hemma. Flexibilitet är mer realistisk än garantier.'] },
      { id: 'changing-days', eyebrow: '04 · Vädergräns', title: 'Mildare betyder inte förutsägbart', paragraphs: ['Klimatguiden förklarar kust, regn och hav. Använd sedan aktuell officiell prognos och havsinformation.', 'Vi presenterar inte Málaga flygplats som Nerja-mätning och överför inte Torrox historiska superlativ.'] },
      { id: 'quieter-tarifa', eyebrow: '05 · Stanna längre', title: 'När semester blir rutin', paragraphs: ['Matinköp, tvätt, matlagning, wifi och enkel väg hem blir viktigare än att pressa in allt på två dagar.', '“Winter rental” kan antyda månadshyra. AMARA Playa är semesterboende; aktuell bokning visar längd, pris och villkor.'] },
      { id: 'winter-day', eyebrow: '06 · Komfort hemma', title: 'AMARA Playa som kompakt vardagsbas', paragraphs: ['AMARA Playa är 37 m² för två på femte våningen med hiss. Aktuell objektdata omfattar kök, tvättmaskin, wifi och balkong.', 'Bekräfta temperaturkontroll, arbetsplats eller solläge om det är avgörande.'] },
      { id: 'home-matters', eyebrow: '07 · Passar eller inte', title: 'Vem uppskattar Nerja på vintern?', paragraphs: ['Det kan passa par som vill ha kust, stadsliv och alternativ till strandtid från en kompakt bas.', 'Mindre för garanterat badväder, alla sommartjänster, stor bostad eller bostadsmånadshyra.'] },
      { id: 'who-enjoys-winter', eyebrow: '08 · Planera med sammanhang', title: 'Kontrollera vad som ändras med säsongen', paragraphs: ['Kommunal strandbevakning och räddning beskrivs som sommartjänster. Kusten är inte stängd, men aktuella villkor styr.', 'Använd väder, geografi och områden för stabil kontext; kontrollera tider, transport och säkerhet nära resan.'] },
      { id: 'amara-la-marina', eyebrow: '09 · Er bas', title: 'Välj Nerja för kust och stad tillsammans', paragraphs: ['AMARA Playa placerar två gäster nära Torrecilla och centrum med lägenhetens vardagsgrunder. Värdet är läge och rutin, inte solgaranti.', 'Avgör om modellen passar; se sedan lägenhet och villkor. Jämför Frigiliana för historisk bykänsla.'] }
    ],
    related: { eyebrow: 'Planera vidare', title: 'Koppla vinteridén till den verkliga platsen', links: [{ token: 'nerja_weather', label: 'Väder & årstider', text: 'Kustklimat, hav och prognosgränser.' }, { token: 'nerja_where_to_stay', label: 'Var ska man bo', text: 'Områden, vägar och kust- eller centrumläge.' }, { token: 'nerja_geography', label: 'Geografi & orientering', text: 'Klippor, stränder, stad och landskap.' }, { token: 'nerja_daily_life', label: 'Vardag & service', text: 'Inköp, tjänster och planering.' }] },
    sources: { eyebrow: 'Källor', title: 'Varifrån uppgifterna kommer', intro: 'Öppettider och säsongstjänster kommer från officiella källor, de allmänna vintermotiven från europeisk forskning.', checked: 'Källor granskade 21 augusti 2026', links: [{ label: 'European Travel Commission · vinter', text: 'Avsikter jämfört med bokningar.', href: sourceHrefs.travelIntent }, { label: 'Cueva de Nerja · tider 2026', text: 'Publicerat årsmönster.', href: sourceHrefs.cave }, { label: 'Museo de Nerja · tider och program', text: 'Publicerad kulturinformation.', href: sourceHrefs.museum }, { label: 'Kommunen · strandbevakning', text: 'Beskrivning av sommartjänst.', href: sourceHrefs.lifeguards }] },
    closing: { eyebrow: 'Vinter vid kusten, ärligt förklarad', title: 'Välj Nerja för livet kring havet', body: 'Nerja kan göra vintern öppnare utan att lova garanterad sommar. Om kust, stad och kompakt lägenhetsliv passar, fortsätt till AMARA Playa.', locationLabel: 'Upptäck Nerja', propertyLabel: 'Visa AMARA Playa' }
  }
};
