import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';
import type { ParkingGuideLocale, ParkingGuideSection } from './parkingGuideContent';

type Localized = Record<AmaraLanguage, string>;
const l = (en: string, de: string, es: string, nl: string, sv: string): Localized => ({ en, de, es, nl, sv });
const langs: AmaraLanguage[] = ['en', 'de', 'es', 'nl', 'sv'];
const article = { datePublished: '2026-08-21', dateModified: '2026-08-21', authorName: 'Robert Sebastian Böhmer', authorType: 'Person' as const, authorSlug: 'amara-about-us' };

export const nerjaParkingSeo: AmaraAuthoringSeo = {
  version: '2026-08-21-nerja-parking-v1.2', pageType: 'A', entityKey: 'amara-brand', article,
  languages: {
    en: { title: 'Parking in Nerja: Centre, Balcón, Burriana & Torrecilla', description: 'Our local guide to parking in Nerja: how to choose between the centre, Balcón, Verano Azul, Burriana and Torrecilla, with practical arrival advice.', robots: 'index, follow', canonical: 'auto' },
    de: { title: 'Parken in Nerja: Zentrum, Balcón, Burriana & Torrecilla', description: 'Unsere Gastgeber-Tipps zum Parken in Nerja: Zentrum, Balcón, Verano Azul, Burriana und Torrecilla mit praktischen Hinweisen zur Ankunft.', robots: 'index, follow', canonical: 'auto' },
    es: { title: 'Aparcar en Nerja: centro, Balcón, Burriana y Torrecilla', description: 'Nuestra guía para aparcar en Nerja: cómo elegir entre el centro, Balcón, Verano Azul, Burriana y Torrecilla, con consejos prácticos para llegar.', robots: 'index, follow', canonical: 'auto' },
    nl: { title: 'Parkeren in Nerja: centrum, Balcón, Burriana & Torrecilla', description: 'Onze lokale gids voor parkeren in Nerja: kies tussen het centrum, Balcón, Verano Azul, Burriana en Torrecilla, met praktisch aankomstadvies.', robots: 'index, follow', canonical: 'auto' },
    sv: { title: 'Parkering i Nerja: centrum, Balcón, Burriana & Torrecilla', description: 'Vår lokala guide till parkering i Nerja: välj mellan centrum, Balcón, Verano Azul, Burriana och Torrecilla, med praktiska råd inför ankomsten.', robots: 'index, follow', canonical: 'auto' }
  }
};

const navLabel = l('Parking & Accessibility', 'Parken & Erreichbarkeit', 'Aparcamiento y acceso', 'Parkeren & toegankelijkheid', 'Parkering & tillgänglighet');
const hero = {
  eyebrow: l('Parking & access · Nerja', 'Parken & Erreichbarkeit · Nerja', 'Aparcamiento y acceso · Nerja', 'Parkeren & toegankelijkheid · Nerja', 'Parkering & tillgänglighet · Nerja'),
  title: l('In Nerja, the right area matters more than one “best” car park', 'In Nerja zählt die richtige Zone mehr als der eine „beste“ Parkplatz', 'En Nerja importa más la zona correcta que un único aparcamiento “mejor”', 'In Nerja telt het juiste gebied meer dan één “beste” parking', 'I Nerja betyder rätt område mer än ett enda “bästa” garage'),
  standfirst: l(
    'When guests ask us for the best place to park in Nerja, our honest answer is: it depends on where you are going. The centre and Balcón de Europa, Verano Azul, Burriana and Torrecilla are different arrival situations. Nerja is investing in its car parks and guidance systems, and from our local experience orientation is improving. Even so, we would never promise a free space or one right beside the door. Choose your destination first, then decide where to unload and where the car can stay.',
    'Wenn Gäste uns nach dem besten Parkplatz in Nerja fragen, lautet unsere ehrliche Antwort: Es kommt darauf an, wohin ihr wollt. Zentrum und Balcón de Europa, Verano Azul, Burriana und Torrecilla sind ganz unterschiedliche Ankunftssituationen. Nerja investiert sichtbar in Parkplätze und Leitsysteme, und aus unserer Erfahrung wird die Orientierung besser. Trotzdem würden wir euch nie einen freien Platz oder einen Stellplatz direkt vor der Tür versprechen. Wählt zuerst euer Ziel – und entscheidet dann, wo ihr ausladet und wo das Auto bleiben kann.',
    'Cuando nuestros huéspedes nos preguntan cuál es el mejor sitio para aparcar en Nerja, nuestra respuesta sincera es: depende de adónde vayáis. El centro y Balcón de Europa, Verano Azul, Burriana y Torrecilla son situaciones de llegada muy distintas. Nerja está invirtiendo en aparcamientos y sistemas de guiado y, por nuestra experiencia local, orientarse resulta cada vez más fácil. Aun así, nunca os prometeríamos una plaza libre ni un sitio junto a la puerta. Elegid primero el destino y después dónde descargar y dejar el coche.',
    'Wanneer gasten ons vragen waar ze het beste kunnen parkeren in Nerja, is ons eerlijke antwoord: dat hangt af van waar jullie heen willen. Het centrum en Balcón de Europa, Verano Azul, Burriana en Torrecilla zijn heel verschillende aankomstsituaties. Nerja investeert zichtbaar in parkeerplaatsen en geleiding, en vanuit onze lokale ervaring wordt de oriëntatie beter. Toch beloven we nooit een vrije plek of een plaats voor de deur. Kies eerst jullie bestemming en bepaal daarna waar jullie lossen en waar de auto blijft.',
    'När gäster frågar oss var det är bäst att parkera i Nerja är vårt ärliga svar: det beror på vart ni ska. Centrum och Balcón de Europa, Verano Azul, Burriana och Torrecilla är helt olika ankomstsituationer. Nerja investerar tydligt i parkeringar och vägvisning, och enligt vår lokala erfarenhet blir det lättare att orientera sig. Ändå lovar vi aldrig en ledig plats eller parkering vid dörren. Välj målet först och bestäm sedan var ni lastar av och var bilen får stå.'
  ),
  note: l('Our advice combines local experience with current official information. Signs on the day always come first.', 'Unser Rat verbindet persönliche Erfahrung mit aktuellen offiziellen Informationen. Vor Ort haben die Schilder immer Vorrang.', 'Nuestros consejos combinan experiencia local e información oficial actual. Las señales del día siempre tienen prioridad.', 'Ons advies combineert lokale ervaring met actuele officiële informatie. De borden ter plaatse gaan altijd voor.', 'Våra råd kombinerar lokal erfarenhet med aktuell officiell information. Skyltarna på plats gäller alltid först.'),
  updated: l('Personally updated by Robert · August 2026', 'Von Robert persönlich aktualisiert · August 2026', 'Actualizado personalmente por Robert · agosto de 2026', 'Persoonlijk bijgewerkt door Robert · augustus 2026', 'Personligen uppdaterad av Robert · augusti 2026')
};

const facts = [
  { label: l('Think in areas', 'In Zonen denken', 'Pensad por zonas', 'Denk in gebieden', 'Tänk i områden'), value: l('Centre · Verano Azul · Burriana · Torrecilla', 'Zentrum · Verano Azul · Burriana · Torrecilla', 'Centro · Verano Azul · Burriana · Torrecilla', 'Centrum · Verano Azul · Burriana · Torrecilla', 'Centrum · Verano Azul · Burriana · Torrecilla') },
  { label: l('What we notice', 'Was wir beobachten', 'Lo que observamos', 'Wat we merken', 'Vad vi märker'), value: l('Orientation is improving', 'Die Orientierung wird besser', 'Orientarse resulta más fácil', 'De oriëntatie wordt beter', 'Det blir lättare att hitta') },
  { label: l('At AMARA Playa', 'Bei AMARA Playa', 'En AMARA Playa', 'Bij AMARA Playa', 'Vid AMARA Playa'), value: l('Plan for street parking', 'Plant mit Straßenparken', 'Contad con aparcar en la calle', 'Reken op straatparkeren', 'Räkna med gatuparkering') },
  { label: l('Our honest promise', 'Unser ehrliches Versprechen', 'Nuestra promesa sincera', 'Onze eerlijke belofte', 'Vårt ärliga löfte'), value: l('Clear advice, never a guaranteed space', 'Klare Hilfe, aber kein garantierter Platz', 'Ayuda clara, nunca una plaza garantizada', 'Duidelijk advies, nooit een gegarandeerde plek', 'Tydliga råd, aldrig en garanterad plats') }
] as const;

const sections: Array<{ id: ParkingGuideSection['id']; eyebrow: Localized; title: Localized; paragraphs: Localized[] }> = [
  { id: 'parking-reality', eyebrow: l('01 · Parking reality', '01 · Die Parkrealität', '01 · La realidad', '01 · De realiteit', '01 · Verkligheten'), title: l('Nerja has several parking systems, not one universal answer', 'Nerja hat mehrere Parksysteme, nicht eine Universallösung', 'Nerja tiene varios sistemas, no una respuesta universal', 'Nerja heeft meerdere systemen, geen universeel antwoord', 'Nerja har flera system, inte ett universellt svar'), paragraphs: [
    l('For central Nerja, we recommend starting with Balcón de Europa or Parque Verano Azul. Burriana is a separate parking area, so if the beach is your destination, plan around Burriana itself. There is also a proposed car park near Avenida de Pescia with 847 spaces. The latest confirmed status we have is from August 2025, when it was still at the anteproject stage, so for now we do not count it as an available option.', 'Für das Zentrum von Nerja empfehlen wir euch zuerst Balcón de Europa oder Parque Verano Azul. Burriana ist eine eigene Parksituation: Wenn der Strand euer Ziel ist, plant ihr am besten direkt rund um Burriana. Bei der Avenida de Pescia ist außerdem ein Parkhaus mit 847 Stellplätzen geplant. Der letzte bestätigte Stand, der uns vorliegt, stammt aus August 2025; damals war es noch ein Vorprojekt. Deshalb zählen wir diese Plätze vorerst nicht zu den verfügbaren Parkmöglichkeiten.', 'Para el centro de Nerja os recomendamos empezar por Balcón de Europa o Parque Verano Azul. Burriana funciona como una zona de aparcamiento aparte: si vais a la playa, planificad directamente alrededor de Burriana. También hay un aparcamiento de 847 plazas previsto junto a la Avenida de Pescia. El último estado confirmado que tenemos es de agosto de 2025, cuando todavía era un anteproyecto, así que por ahora no contamos esas plazas como disponibles.', 'Voor het centrum van Nerja raden we aan om eerst bij Balcón de Europa of Parque Verano Azul te kijken. Burriana is een aparte parkeersituatie: als het strand jullie bestemming is, plan dan rond Burriana zelf. Bij Avenida de Pescia is ook een parkeergarage met 847 plaatsen gepland. De laatste bevestigde status die we hebben, dateert van augustus 2025; toen ging het nog om een voorontwerp. Daarom rekenen we die plaatsen voorlopig niet als beschikbaar.', 'För centrala Nerja rekommenderar vi att ni börjar vid Balcón de Europa eller Parque Verano Azul. Burriana är ett eget parkeringsområde, så om stranden är målet planerar ni bäst direkt kring Burriana. Det finns också planer på ett parkeringshus med 847 platser nära Avenida de Pescia. Den senaste bekräftade status vi har är från augusti 2025, då projektet fortfarande var på förslagsstadiet. Därför räknar vi tills vidare inte platserna som tillgängliga.'),
    l('Choose by destination: central sightseeing, a specific beach or a multi-day stay create different priorities. No single car park is “best” for every journey.', 'Wählt nach Ziel: Zentrum, bestimmter Strand oder mehrtägiger Aufenthalt erzeugen andere Prioritäten. Kein Parkplatz ist für jede Fahrt „der beste“.', 'Elegid según destino: centro, una playa concreta o varios días crean prioridades distintas. Ningún aparcamiento es el mejor para todo.', 'Kies op bestemming: centrum, een specifiek strand of meerdere dagen vragen andere prioriteiten. Geen parking is voor alles het best.', 'Välj efter mål: centrum, en viss strand eller flera dagar ger olika prioriteringar. Ingen parkering är bäst för allt.')
  ]},
  { id: 'arrival-luggage', eyebrow: l('02 · Arrival and luggage', '02 · Ankunft und Gepäck', '02 · Llegada y equipaje', '02 · Aankomst en bagage', '02 · Ankomst och bagage'), title: l('A luggage stop and a parking place are different decisions', 'Gepäckstopp und Stellplatz sind verschiedene Entscheidungen', 'Descargar y aparcar son decisiones distintas', 'Lossen en parkeren zijn verschillende keuzes', 'Avlastning och parkering är olika beslut'), paragraphs: [
    l('At AMARA Playa near Torrecilla, please plan for street parking. We do not promise a private space there, and we cannot reserve the legal space closest to the door. What we can do is give you clear arrival instructions so that luggage and parking do not become one confused search.', 'Bei AMARA Playa nahe Torrecilla plant ihr bitte mit Straßenparken. Einen privaten Stellplatz versprechen wir euch dort nicht, und auch den nächsten legalen Platz vor der Tür können wir nicht reservieren. Was wir euch geben können, ist eine klare Ankunftsanleitung, damit Ausladen und Parken nicht zu einer einzigen hektischen Suche werden.', 'En AMARA Playa, cerca de Torrecilla, contad con aparcar en la calle. No os prometemos una plaza privada ni podemos reservar el sitio legal más cercano a la puerta. Lo que sí podemos daros son instrucciones claras para que descargar y aparcar no se conviertan en una sola búsqueda con prisas.', 'Bij AMARA Playa, vlak bij Torrecilla, rekenen jullie op straatparkeren. We beloven daar geen privéplek en kunnen de dichtstbijzijnde legale plaats niet reserveren. Wat we wel kunnen geven, zijn duidelijke aankomstinstructies, zodat lossen en parkeren geen gehaaste zoektocht worden.', 'Vid AMARA Playa nära Torrecilla ska ni räkna med gatuparkering. Vi lovar ingen privat plats och kan inte reservera den närmaste lagliga platsen vid dörren. Det vi kan ge er är tydliga ankomstinstruktioner, så att avlastning och parkering inte blir en stressig gemensam jakt.'),
    l('Our practical advice is to treat unloading and parking as two steps. First follow the arrival instructions for your luggage; then park legally and walk the short final section back without pressure.', 'Unser praktischer Rat: Betrachtet Ausladen und Parken als zwei Schritte. Folgt zuerst der Ankunftsanleitung für euer Gepäck; danach parkt ihr in Ruhe legal und geht das letzte Stück zurück.', 'Nuestro consejo práctico es separar descarga y aparcamiento. Primero seguid las instrucciones para el equipaje; después aparcad legalmente y volved caminando con calma.', 'Ons praktische advies: zie lossen en parkeren als twee stappen. Volg eerst de aankomstinstructies voor jullie bagage; parkeer daarna legaal en loop rustig het laatste stukje terug.', 'Vårt praktiska råd är att se avlastning och parkering som två steg. Följ först ankomstinstruktionen för bagaget; parkera sedan lagligt och gå lugnt den sista biten tillbaka.')
  ]},
  { id: 'during-stay', eyebrow: l('03 · During your stay', '03 · Während des Aufenthalts', '03 · Durante la estancia', '03 · Tijdens het verblijf', '03 · Under vistelsen'), title: l('Decide when the car adds value — and when it can stay', 'Entscheidet, wann das Auto nützt – und wann es stehen kann', 'Decidid cuándo aporta el coche y cuándo puede quedarse', 'Bepaal wanneer de auto helpt en wanneer hij kan blijven staan', 'Avgör när bilen hjälper och när den kan stå kvar'), paragraphs: [
    l('Central Nerja and Torrecilla can support many plans on foot. Burriana, Maro or trips beyond town can create a different case for using the car.', 'Zentrales Nerja und Torrecilla ermöglichen viele Wege zu Fuß. Burriana, Maro oder Ausflüge außerhalb der Stadt können einen anderen Autoeinsatz sinnvoll machen.', 'El centro y Torrecilla permiten muchos planes a pie. Burriana, Maro o excursiones fuera crean otro caso para usar coche.', 'Centrum en Torrecilla maken veel plannen te voet mogelijk. Burriana, Maro of uitstapjes buiten de stad kunnen een ander autogebruik vragen.', 'Centrum och Torrecilla möjliggör mycket till fots. Burriana, Maro eller utflykter utanför staden kan ge ett annat bilbehov.'),
    l('If you are staying for several days, parking once and walking can be more useful than repeatedly searching close to every destination. The right answer depends on your area and plans for the day.', 'Wenn ihr mehrere Tage bleibt, kann einmal parken und zu Fuß gehen sinnvoller sein, als an jedem Ziel erneut einen Platz zu suchen. Was für euch passt, hängt von eurer Lage und eurem Tagesplan ab.', 'Si os quedáis varios días, puede ser más práctico aparcar una vez y moveros a pie que buscar sitio junto a cada destino. La mejor opción depende de vuestra zona y del plan del día.', 'Als jullie meerdere dagen blijven, kan één keer parkeren en verder lopen handiger zijn dan bij elke bestemming opnieuw zoeken. Wat het beste werkt, hangt af van jullie locatie en dagplanning.', 'Om ni stannar flera dagar kan det vara smidigare att parkera en gång och gå än att leta på nytt vid varje mål. Vad som passar bäst beror på var ni bor och dagens planer.')
  ]},
  { id: 'last-mile', eyebrow: l('04 · Last mile and accessibility', '04 · Letzter Weg und Zugänglichkeit', '04 · Último tramo y accesibilidad', '04 · Laatste route en toegankelijkheid', '04 · Sista sträckan och tillgänglighet'), title: l('A town route and a property entrance are not the same thing', 'Stadtweg und Hauseingang sind nicht dasselbe', 'La ruta urbana y la entrada no son lo mismo', 'Stadsroute en woningingang zijn niet hetzelfde', 'Stadsväg och bostadsentré är inte samma sak'), paragraphs: [
    l('A nearby street or municipal facility does not prove a step-free route. Kerbs, gradients, surfaces and the building entrance must be checked together.', 'Eine nahe Straße oder Anlage beweist keine stufenfreie Route. Bordsteine, Steigungen, Oberflächen und Hauseingang müssen zusammen geprüft werden.', 'Una calle o instalación cercana no demuestra ruta sin escalones. Bordillos, pendientes, pavimento y entrada deben revisarse juntos.', 'Een nabije straat of voorziening bewijst geen trapvrije route. Stoepen, hellingen, ondergrond en ingang moeten samen worden bekeken.', 'En närliggande gata eller anläggning bevisar ingen stegfri rutt. Kanter, lutning, underlag och entré måste granskas tillsammans.'),
    l('There are steps on the route at AMARA Playa. If walking, luggage or mobility is important for your decision, please ask us before booking; we would rather explain the route honestly than surprise you on arrival.', 'Bei AMARA Playa gehören Stufen zum Weg. Wenn Laufen, Gepäck oder Mobilität für eure Entscheidung wichtig sind, fragt uns bitte vor der Buchung. Wir erklären euch den Weg lieber ehrlich, als euch bei der Ankunft zu überraschen.', 'En AMARA Playa hay escalones en el recorrido. Si caminar, el equipaje o la movilidad son importantes para decidir, preguntadnos antes de reservar. Preferimos explicaros la ruta con sinceridad antes que sorprenderos al llegar.', 'Bij AMARA Playa horen trappen bij de route. Als lopen, bagage of mobiliteit belangrijk is voor jullie keuze, vraag het ons dan vóór het boeken. We leggen de route liever eerlijk uit dan jullie bij aankomst te verrassen.', 'Vid AMARA Playa finns trappsteg längs vägen. Om gång, bagage eller rörlighet är viktigt för ert val, fråga oss före bokning. Vi förklarar hellre vägen ärligt än överraskar er vid ankomst.')
  ]},
  { id: 'seasonal-rules', eyebrow: l('05 · Seasons and live systems', '05 · Saison und Live-Systeme', '05 · Temporada y sistemas actuales', '05 · Seizoen en live-systemen', '05 · Säsong och livesystem'), title: l('The city is improving parking — while the details keep moving', 'Die Stadt verbessert das Parken – während Details sich verändern', 'La ciudad mejora el aparcamiento mientras cambian los detalles', 'De stad verbetert parkeren terwijl details veranderen', 'Staden förbättrar parkering medan detaljer förändras'), paragraphs: [
    l('Recent municipal projects show that Nerja is investing in parking: Verano Azul was freshly marked in 2026, an extension of Balcón’s guidance system was commissioned, and Burriana received a smart-parking project. We see that as encouraging, but it still does not mean the next space will be free.', 'Aktuelle städtische Projekte zeigen, dass Nerja in das Parken investiert: Verano Azul wurde 2026 neu markiert, die Erweiterung des Leitsystems am Balcón wurde beauftragt und Burriana erhielt ein Smart-Parking-Projekt. Das finden wir ermutigend – es bedeutet aber noch lange nicht, dass der nächste Platz frei ist.', 'Los proyectos municipales recientes muestran que Nerja está invirtiendo en aparcamiento: Verano Azul se repintó en 2026, se adjudicó la ampliación del sistema de guiado del Balcón y Burriana recibió un proyecto de aparcamiento inteligente. Nos parece una buena señal, pero no significa que la próxima plaza vaya a estar libre.', 'Recente gemeentelijke projecten laten zien dat Nerja in parkeren investeert: Verano Azul kreeg in 2026 nieuwe markeringen, de uitbreiding van het geleidingssysteem bij Balcón werd aanbesteed en Burriana kreeg een slimparkeerproject. Dat vinden we bemoedigend, maar het betekent nog niet dat de volgende plek vrij is.', 'Nya kommunala projekt visar att Nerja investerar i parkering: Verano Azul fick nya markeringar 2026, en utbyggnad av vägledningssystemet vid Balcón beställdes och Burriana fick ett projekt för smart parkering. Vi ser det som positivt, men det betyder fortfarande inte att nästa plats är ledig.'),
    l('Numbers, prices and operating details can change. Before you drive into a car park, check its current sign and display; that is more useful than an old screenshot on this page.', 'Zahlen, Preise und Betriebsdetails können sich ändern. Bevor ihr in eine Anlage fahrt, schaut bitte auf das aktuelle Schild und die Anzeige vor Ort – das hilft euch mehr als ein alter Screenshot auf dieser Seite.', 'Las cifras, los precios y el funcionamiento pueden cambiar. Antes de entrar, mirad la señal y el panel actuales; os ayudarán más que una captura antigua en esta página.', 'Aantallen, prijzen en werking kunnen veranderen. Kijk vóór het inrijden naar het actuele bord en display; dat helpt jullie meer dan een oude screenshot op deze pagina.', 'Antal, priser och drift kan ändras. Kontrollera skylten och displayen innan ni kör in; det hjälper er mer än en gammal skärmbild på sidan.')
  ]},
  { id: 'amara-boundary', eyebrow: l('06 · Our advice for AMARA Playa', '06 · Unser Rat für AMARA Playa', '06 · Nuestro consejo para AMARA Playa', '06 · Ons advies voor AMARA Playa', '06 · Vårt råd för AMARA Playa'), title: l('First choose the right part of Nerja — then follow our arrival route', 'Erst den richtigen Bereich wählen – dann unserer Ankunftsroute folgen', 'Primero elegid la zona; después seguid nuestra ruta de llegada', 'Kies eerst het juiste gebied en volg daarna onze aankomstroute', 'Välj först rätt område och följ sedan vår ankomstrutt'), paragraphs: [
    l('On this page we can help you choose the right part of Nerja. What we cannot do is promise the nearest street space for the exact minute you arrive.', 'Auf dieser Seite helfen wir euch, den richtigen Bereich in Nerja zu wählen. Was wir nicht können: euch für die genaue Minute eurer Ankunft den nächsten Straßenplatz versprechen.', 'En esta página podemos ayudaros a elegir la parte adecuada de Nerja. Lo que no podemos hacer es prometeros la plaza en la calle más cercana justo en el momento de vuestra llegada.', 'Op deze pagina helpen we jullie het juiste deel van Nerja te kiezen. Wat we niet kunnen, is voor het precieze aankomstmoment de dichtstbijzijnde straatplek beloven.', 'På den här sidan hjälper vi er att välja rätt del av Nerja. Det vi inte kan göra är att lova närmaste gatuplats exakt när ni anländer.'),
    l('For AMARA Playa we will give you the practical details separately: where to approach, how to handle luggage and which route leads to the apartment. That is the information you need on arrival — not database language.', 'Für AMARA Playa bekommt ihr von uns separat die praktischen Details: wie ihr anfahrt, wie ihr mit dem Gepäck umgeht und welcher Weg zur Wohnung führt. Genau das braucht ihr bei der Ankunft – keine Datenbanksprache.', 'Para AMARA Playa os daremos aparte los detalles prácticos: por dónde llegar, cómo gestionar el equipaje y qué ruta lleva al apartamento. Eso es lo que necesitáis al llegar, no lenguaje de base de datos.', 'Voor AMARA Playa geven we jullie apart de praktische details: hoe jullie aanrijden, de bagage regelen en welke route naar het appartement leidt. Dat hebben jullie bij aankomst nodig, geen databasetaal.', 'För AMARA Playa ger vi er de praktiska detaljerna separat: hur ni kör fram, hanterar bagaget och vilken väg som leder till lägenheten. Det är vad ni behöver vid ankomst, inte databasspråk.')
  ]}
];

const related = [
  { token: 'getting_to_nerja' as const, label: l('Arrival & Mobility', 'Anreise & Mobilität', 'Llegada y movilidad', 'Aankomst & mobiliteit', 'Ankomst & mobilitet'), text: l('Airports, roads and regional transport.', 'Flughäfen, Straßen und Regionalverkehr.', 'Aeropuertos, carreteras y transporte regional.', 'Luchthavens, wegen en regionaal vervoer.', 'Flygplatser, vägar och regional transport.') },
  { token: 'nerja_where_to_stay' as const, label: l('Where to Stay', 'Wo übernachten', 'Dónde alojarse', 'Waar overnachten', 'Var ska man bo'), text: l('Choose the area before choosing the parking strategy.', 'Erst die Lage, dann die Parkstrategie wählen.', 'Elegid la zona antes de la estrategia de aparcamiento.', 'Kies het gebied vóór de parkeerstrategie.', 'Välj område före parkeringsstrategi.') },
  { token: 'nerja_beaches_authority' as const, label: l('Beaches & Coast', 'Strände & Küste', 'Playas y costa', 'Stranden & kust', 'Stränder & kust'), text: l('Connect Burriana, Torrecilla and other beach days to their own context.', 'Burriana, Torrecilla und andere Strandtage im eigenen Kontext planen.', 'Planificad Burriana, Torrecilla y otras playas en su contexto.', 'Plan Burriana, Torrecilla en andere stranden in hun context.', 'Planera Burriana, Torrecilla och andra stränder i sitt sammanhang.') }
];

const sourceRows = [
  { label: l('Town of Nerja · car parks and the Pescia plan', 'Stadt Nerja · Parkplätze und Pescia-Plan', 'Ayuntamiento · aparcamientos y plan de Pescia', 'Gemeente Nerja · parkings en Pescia-plan', 'Nerja kommun · parkeringar och Pescia-plan'), text: l('This is where we checked which facilities exist and why the 847 spaces are still only planned.', 'Hier haben wir geprüft, welche Anlagen bestehen und warum die 847 Plätze weiterhin nur geplant sind.', 'Aquí comprobamos qué instalaciones existen y por qué las 847 plazas siguen siendo solo un proyecto.', 'Hier hebben we gecontroleerd welke voorzieningen bestaan en waarom de 847 plaatsen nog gepland zijn.', 'Här kontrollerade vi vilka anläggningar som finns och varför de 847 platserna fortfarande bara är planerade.'), href: 'https://www.nerja.es/luz-verde-al-anteproyecto-del-nuevo-aparcamiento-con-847-plazas/' },
  { label: l('Balcón · parking guidance', 'Balcón · Parkleitsystem', 'Balcón · guiado de plazas', 'Balcón · parkeerbegeleiding', 'Balcón · parkeringsvägledning'), text: l('The town’s 2026 update on guidance to available spaces.', 'Die Mitteilung der Stadt von 2026 zum Leitsystem für freie Plätze.', 'La actualización municipal de 2026 sobre el guiado de plazas libres.', 'De gemeentelijke update uit 2026 over begeleiding naar vrije plekken.', 'Kommunens uppdatering 2026 om vägledning till lediga platser.'), href: 'https://www.nerja.es/el-ayuntamiento-completara-el-guiado-de-plazas-libres-del-aparcamiento-balcon-de-europa/' },
  { label: l('Verano Azul · refreshed markings', 'Verano Azul · erneuerte Markierungen', 'Verano Azul · nueva señalización', 'Verano Azul · vernieuwde markering', 'Verano Azul · förnyad markering'), text: l('The town’s 2026 update on the work carried out there.', 'Die Mitteilung der Stadt von 2026 zu den dort ausgeführten Arbeiten.', 'La información municipal de 2026 sobre los trabajos realizados.', 'De gemeentelijke informatie uit 2026 over de uitgevoerde werkzaamheden.', 'Kommunens information 2026 om arbetet som utfördes där.'), href: 'https://www.nerja.es/el-ayuntamiento-sigue-mejorando-los-aparcamientos-municipales-con-la-pintura-integral-del-verano-azul/' },
  { label: l('Burriana · smart parking', 'Burriana · Smart Parking', 'Burriana · smart parking', 'Burriana · smart parking', 'Burriana · smart parking'), text: l('The 2026 project update; please check the current operation on arrival.', 'Die Projektmeldung von 2026; den aktuellen Betrieb prüft ihr bitte bei der Ankunft.', 'La noticia del proyecto de 2026; comprobad el funcionamiento actual al llegar.', 'De projectupdate uit 2026; controleer bij aankomst hoe het systeem nu werkt.', 'Projektuppdateringen 2026; kontrollera aktuell drift vid ankomst.'), href: 'https://www.nerja.es/el-aparcamiento-municipal-de-burriana-contara-con-un-sistema-inteligente-de-guiado-de-plazas-libres/' }
];

const makeLocale = (lang: AmaraLanguage): ParkingGuideLocale => ({
  navLabel: navLabel[lang], hero: { eyebrow: hero.eyebrow[lang], title: hero.title[lang], standfirst: hero.standfirst[lang], note: hero.note[lang], updated: hero.updated[lang] },
  facts: facts.map((item) => ({ label: item.label[lang], value: item.value[lang] })),
  sections: sections.map((section) => ({ id: section.id, eyebrow: section.eyebrow[lang], title: section.title[lang], paragraphs: section.paragraphs.map((p) => p[lang]) })),
  related: { eyebrow: l('Continue planning', 'Weiter planen', 'Seguir planificando', 'Verder plannen', 'Planera vidare')[lang], title: l('Connect the parking choice to the real area', 'Die Parkentscheidung mit der echten Lage verbinden', 'Conectad el aparcamiento con la zona real', 'Verbind de parkeerkeuze met het echte gebied', 'Koppla parkeringsvalet till rätt område')[lang], links: related.map((item) => ({ token: item.token, label: item.label[lang], text: item.text[lang] })) },
  sources: { eyebrow: l('What we checked for you', 'Was wir für euch geprüft haben', 'Lo que hemos comprobado para vosotros', 'Wat we voor jullie hebben nagekeken', 'Det vi har kontrollerat åt er')[lang], title: l('Useful official updates — with the right limits', 'Hilfreiche offizielle Informationen – richtig eingeordnet', 'Información oficial útil, bien interpretada', 'Nuttige officiële informatie, met de juiste nuance', 'Användbar officiell information, rätt tolkad')[lang], intro: l('We use the town’s own updates for facilities and improvement projects. For the day of your arrival, the current signs still matter most.', 'Für Anlagen und Verbesserungen nutzen wir die Informationen der Stadt selbst. Am Tag eurer Ankunft zählen trotzdem die aktuellen Schilder vor Ort am meisten.', 'Para las instalaciones y mejoras utilizamos la información del propio Ayuntamiento. El día de vuestra llegada, las señales actuales siguen siendo lo más importante.', 'Voor voorzieningen en verbeteringen gebruiken we de informatie van de gemeente zelf. Op jullie aankomstdag zijn de actuele borden ter plaatse het belangrijkst.', 'För anläggningar och förbättringar använder vi kommunens egen information. På ankomstdagen är de aktuella skyltarna på plats ändå viktigast.')[lang], checked: l('Sources checked 21 August 2026', 'Quellen geprüft am 21. August 2026', 'Fuentes comprobadas el 21 de agosto de 2026', 'Bronnen gecontroleerd op 21 augustus 2026', 'Källor kontrollerade 21 augusti 2026')[lang], links: sourceRows.map((item) => ({ label: item.label[lang], text: item.text[lang], href: item.href })) },
  closing: { eyebrow: l('Our simple Nerja rule', 'Unsere einfache Nerja-Regel', 'Nuestra regla sencilla para Nerja', 'Onze eenvoudige Nerja-regel', 'Vår enkla Nerja-regel')[lang], title: l('Choose the area first, then the parking place', 'Erst die Lage wählen, dann den Parkplatz', 'Primero la zona, después el aparcamiento', 'Eerst het gebied, daarna de parkeerplek', 'Välj område först, sedan parkering')[lang], body: l('Nerja becomes much easier once you stop treating the centre, the beaches and your accommodation as the same destination. For AMARA Playa, we will also give you the practical arrival details you need.', 'Nerja wird deutlich einfacher, sobald ihr Zentrum, Strände und Unterkunft nicht mehr als dasselbe Ziel behandelt. Für AMARA Playa bekommt ihr von uns zusätzlich die praktischen Ankunftsdetails, die ihr wirklich braucht.', 'Nerja resulta mucho más sencillo cuando no tratáis el centro, las playas y el alojamiento como un único destino. Para AMARA Playa también os daremos los detalles prácticos que necesitáis al llegar.', 'Nerja wordt veel eenvoudiger zodra jullie het centrum, de stranden en jullie verblijf niet als dezelfde bestemming behandelen. Voor AMARA Playa geven we jullie ook de praktische aankomstdetails die jullie echt nodig hebben.', 'Nerja blir mycket enklare när ni inte behandlar centrum, stränder och boende som samma mål. För AMARA Playa ger vi er också de praktiska ankomstdetaljer ni behöver.')[lang], locationLabel: l('Explore Nerja', 'Nerja entdecken', 'Descubrir Nerja', 'Ontdek Nerja', 'Upptäck Nerja')[lang], propertyLabel: l('View AMARA Playa', 'AMARA Playa ansehen', 'Ver AMARA Playa', 'Bekijk AMARA Playa', 'Se AMARA Playa')[lang] }
});

export const nerjaParkingContent = Object.fromEntries(langs.map((lang) => [lang, makeLocale(lang)])) as Record<AmaraLanguage, ParkingGuideLocale>;
