import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';
import type { ParkingGuideLocale, ParkingGuideSection } from './parkingGuideContent';

type Localized = Record<AmaraLanguage, string>;
const l = (en: string, de: string, es: string, nl: string, sv: string): Localized => ({ en, de, es, nl, sv });
const langs: AmaraLanguage[] = ['en', 'de', 'es', 'nl', 'sv'];
const article = { datePublished: '2026-08-21', dateModified: '2026-08-21', authorName: 'Robert Sebastian Böhmer', authorType: 'Person' as const, authorSlug: 'amara-about-us' };

export const nerjaParkingSeo: AmaraAuthoringSeo = {
  version: '2026-08-21-nerja-parking-v1.0', pageType: 'A', entityKey: 'amara-brand', article,
  languages: {
    en: { title: 'Parking in Nerja: Centre, Balcón, Burriana & Torrecilla', description: 'Understand parking in Nerja by area: centre and Balcón de Europa, Verano Azul, Burriana, Torrecilla, luggage and live municipal information.', robots: 'index, follow', canonical: 'auto' },
    de: { title: 'Parken in Nerja: Zentrum, Balcón, Burriana & Torrecilla', description: 'Parken in Nerja nach Lagen verstehen: Zentrum und Balcón de Europa, Verano Azul, Burriana, Torrecilla, Gepäck und aktuelle Gemeindeinfos.', robots: 'index, follow', canonical: 'auto' },
    es: { title: 'Aparcar en Nerja: centro, Balcón, Burriana y Torrecilla', description: 'Entended el aparcamiento en Nerja por zonas: centro y Balcón, Verano Azul, Burriana, Torrecilla, equipaje e información municipal actual.', robots: 'index, follow', canonical: 'auto' },
    nl: { title: 'Parkeren in Nerja: centrum, Balcón, Burriana & Torrecilla', description: 'Begrijp parkeren in Nerja per gebied: centrum en Balcón, Verano Azul, Burriana, Torrecilla, bagage en actuele gemeente-informatie.', robots: 'index, follow', canonical: 'auto' },
    sv: { title: 'Parkering i Nerja: centrum, Balcón, Burriana & Torrecilla', description: 'Förstå parkering i Nerja per område: centrum och Balcón, Verano Azul, Burriana, Torrecilla, bagage och aktuell kommuninformation.', robots: 'index, follow', canonical: 'auto' }
  }
};

const navLabel = l('Parking & Accessibility', 'Parken & Erreichbarkeit', 'Aparcamiento y acceso', 'Parkeren & toegankelijkheid', 'Parkering & tillgänglighet');
const hero = {
  eyebrow: l('Parking & access · Nerja', 'Parken & Erreichbarkeit · Nerja', 'Aparcamiento y acceso · Nerja', 'Parkeren & toegankelijkheid · Nerja', 'Parkering & tillgänglighet · Nerja'),
  title: l('In Nerja, the right area matters more than one “best” car park', 'In Nerja zählt die richtige Zone mehr als der eine „beste“ Parkplatz', 'En Nerja importa más la zona correcta que un único aparcamiento “mejor”', 'In Nerja telt het juiste gebied meer dan één “beste” parking', 'I Nerja betyder rätt område mer än ett enda “bästa” garage'),
  standfirst: l(
    'Parking in Nerja is not one problem with one answer. The centre and Balcón de Europa, Verano Azul, Burriana and the Torrecilla area serve different journeys. The municipality is actively maintaining and digitising several facilities, which supports the sense that parking is becoming easier to navigate — but it does not prove that spaces are mostly free or always available. Start with your destination, separate unloading from long-stay parking and use current signs and official systems for the day itself.',
    'Parken in Nerja ist nicht ein Problem mit einer Antwort. Zentrum und Balcón de Europa, Verano Azul, Burriana und Torrecilla bedienen unterschiedliche Wege. Die Gemeinde pflegt und digitalisiert mehrere Anlagen; das stützt den Eindruck, dass Parken leichter zu navigieren wird – beweist aber weder überwiegend kostenlose noch stets verfügbare Plätze. Beginnt mit eurem Ziel, trennt Ausladen vom längeren Parken und nutzt am Reisetag aktuelle Schilder und offizielle Systeme.',
    'Aparcar en Nerja no es un problema con una sola respuesta. Centro y Balcón de Europa, Verano Azul, Burriana y Torrecilla sirven trayectos distintos. El Ayuntamiento mantiene y digitaliza varias instalaciones; eso apoya la idea de una orientación más sencilla, pero no demuestra que la mayoría sea gratis ni que haya plazas siempre. Empezad por el destino, separad descarga de estacionamiento y usad señales y sistemas actuales.',
    'Parkeren in Nerja is niet één probleem met één antwoord. Centrum en Balcón de Europa, Verano Azul, Burriana en Torrecilla horen bij verschillende ritten. De gemeente onderhoudt en digitaliseert meerdere voorzieningen; dat ondersteunt het idee dat parkeren overzichtelijker wordt, maar bewijst niet dat het meestal gratis of altijd beschikbaar is. Begin bij het doel, scheid lossen van langer parkeren en volg actuele borden.',
    'Parkering i Nerja är inte ett problem med ett svar. Centrum och Balcón de Europa, Verano Azul, Burriana och Torrecilla hör till olika resor. Kommunen underhåller och digitaliserar flera anläggningar; det stödjer bilden av enklare orientering men bevisar inte att det mesta är gratis eller alltid ledigt. Börja med målet, skilj avlastning från längre parkering och följ aktuella skyltar.'
  ),
  note: l('Municipal projects are dated facts, not live-space promises. Property-specific arrival details remain separate.', 'Kommunale Projekte sind datierte Fakten, keine Live-Platzversprechen. Objektspezifische Ankunft bleibt getrennt.', 'Los proyectos municipales son hechos fechados, no promesas de plazas libres. La llegada al alojamiento queda separada.', 'Gemeentelijke projecten zijn gedateerde feiten, geen belofte van vrije plaatsen. Woningdetails blijven apart.', 'Kommunala projekt är daterade fakta, inte löften om lediga platser. Boendedetaljer hålls separat.'),
  updated: l('Municipal sources and AMARA baseline reviewed August 2026', 'Gemeindequellen und AMARA-Bestand geprüft im August 2026', 'Fuentes municipales y base AMARA revisadas en agosto de 2026', 'Gemeentebronnen en AMARA-basis herzien in augustus 2026', 'Kommunala källor och AMARA-baslinje granskade augusti 2026')
};

const facts = [
  { label: l('Think in areas', 'In Zonen denken', 'Pensad por zonas', 'Denk in gebieden', 'Tänk i områden'), value: l('Centre · Verano Azul · Burriana · Torrecilla', 'Zentrum · Verano Azul · Burriana · Torrecilla', 'Centro · Verano Azul · Burriana · Torrecilla', 'Centrum · Verano Azul · Burriana · Torrecilla', 'Centrum · Verano Azul · Burriana · Torrecilla') },
  { label: l('Municipal direction', 'Kommunale Richtung', 'Dirección municipal', 'Gemeentelijke richting', 'Kommunal riktning'), value: l('Maintenance and smart guidance are expanding', 'Instandhaltung und digitale Führung werden ausgebaut', 'Crece el mantenimiento y el guiado inteligente', 'Onderhoud en slimme begeleiding groeien', 'Underhåll och smart vägledning byggs ut') },
  { label: l('At AMARA Playa', 'Bei AMARA Playa', 'En AMARA Playa', 'Bij AMARA Playa', 'Vid AMARA Playa'), value: l('Street-parking context, not a promised private bay', 'Straßenparken, kein zugesagter Privatplatz', 'Contexto de calle, no plaza privada prometida', 'Straatparkeren, geen beloofde privéplek', 'Gatuparkering, ingen utlovad privat plats') },
  { label: l('Do not hard-code', 'Nicht festschreiben', 'No fijar', 'Niet vastzetten', 'Lås inte'), value: l('Capacity, price or live availability', 'Kapazität, Preis oder Live-Verfügbarkeit', 'Capacidad, precio o disponibilidad', 'Capaciteit, prijs of beschikbaarheid', 'Kapacitet, pris eller tillgänglighet') }
] as const;

const sections: Array<{ id: ParkingGuideSection['id']; eyebrow: Localized; title: Localized; paragraphs: Localized[] }> = [
  { id: 'parking-reality', eyebrow: l('01 · Parking reality', '01 · Die Parkrealität', '01 · La realidad', '01 · De realiteit', '01 · Verkligheten'), title: l('Nerja has several parking systems, not one universal answer', 'Nerja hat mehrere Parksysteme, nicht eine Universallösung', 'Nerja tiene varios sistemas, no una respuesta universal', 'Nerja heeft meerdere systemen, geen universeel antwoord', 'Nerja har flera system, inte ett universellt svar'), paragraphs: [
    l('The municipality names Balcón de Europa, Parque Verano Azul and Burriana as existing public facilities. A separate 847-space project near Avenida de Pescia was still an anteproject in 2025 and must not be presented as open.', 'Die Gemeinde nennt Balcón de Europa, Parque Verano Azul und Burriana als bestehende Anlagen. Ein separates Projekt mit 847 Plätzen bei Avenida de Pescia war 2025 noch Vorprojekt und darf nicht als geöffnet erscheinen.', 'El Ayuntamiento cita Balcón de Europa, Parque Verano Azul y Burriana como instalaciones existentes. Otro proyecto de 847 plazas junto a Avenida de Pescia seguía siendo anteproyecto en 2025.', 'De gemeente noemt Balcón de Europa, Parque Verano Azul en Burriana als bestaande voorzieningen. Een project met 847 plaatsen bij Avenida de Pescia was in 2025 nog een voorontwerp.', 'Kommunen nämner Balcón de Europa, Parque Verano Azul och Burriana som befintliga anläggningar. Ett projekt med 847 platser vid Avenida de Pescia var 2025 fortfarande ett förprojekt.'),
    l('Choose by destination: central sightseeing, a specific beach or a multi-day stay create different priorities. No single car park is “best” for every journey.', 'Wählt nach Ziel: Zentrum, bestimmter Strand oder mehrtägiger Aufenthalt erzeugen andere Prioritäten. Kein Parkplatz ist für jede Fahrt „der beste“.', 'Elegid según destino: centro, una playa concreta o varios días crean prioridades distintas. Ningún aparcamiento es el mejor para todo.', 'Kies op bestemming: centrum, een specifiek strand of meerdere dagen vragen andere prioriteiten. Geen parking is voor alles het best.', 'Välj efter mål: centrum, en viss strand eller flera dagar ger olika prioriteringar. Ingen parkering är bäst för allt.')
  ]},
  { id: 'arrival-luggage', eyebrow: l('02 · Arrival and luggage', '02 · Ankunft und Gepäck', '02 · Llegada y equipaje', '02 · Aankomst en bagage', '02 · Ankomst och bagage'), title: l('A luggage stop and a parking place are different decisions', 'Gepäckstopp und Stellplatz sind verschiedene Entscheidungen', 'Descargar y aparcar son decisiones distintas', 'Lossen en parkeren zijn verschillende keuzes', 'Avlastning och parkering är olika beslut'), paragraphs: [
    l('For AMARA Playa near Torrecilla, the current property baseline describes street parking. It does not establish a private bay or guarantee a legal space beside the door.', 'Für AMARA Playa bei Torrecilla nennt der aktuelle Objektbestand Straßenparken. Er belegt keinen Privatplatz und garantiert keinen legalen Stellplatz vor der Tür.', 'Para AMARA Playa cerca de Torrecilla, la ficha actual indica aparcamiento en la calle. No demuestra plaza privada ni garantiza sitio junto a la puerta.', 'Voor AMARA Playa bij Torrecilla noemt de huidige woninginfo straatparkeren. Dat bewijst geen privéplek en garandeert geen plaats bij de deur.', 'För AMARA Playa nära Torrecilla anger dagens boendeinfo gatuparkering. Det bevisar ingen privat plats och garanterar ingen plats vid dörren.'),
    l('Use the exact property instructions for unloading. A legal short stop, the final parking context and the walk back to the apartment may be three separate steps.', 'Nutzt zum Ausladen die konkrete Objekthinweise. Legal kurz halten, endgültig parken und zur Wohnung zurückgehen können drei getrennte Schritte sein.', 'Usad las instrucciones del alojamiento para descargar. Parar legalmente, aparcar y volver andando pueden ser tres pasos.', 'Gebruik de woninginstructies voor het lossen. Legaal kort stoppen, definitief parkeren en teruglopen kunnen drie stappen zijn.', 'Använd boendets instruktioner för avlastning. Lagligt kort stopp, slutlig parkering och promenad tillbaka kan vara tre steg.')
  ]},
  { id: 'during-stay', eyebrow: l('03 · During your stay', '03 · Während des Aufenthalts', '03 · Durante la estancia', '03 · Tijdens het verblijf', '03 · Under vistelsen'), title: l('Decide when the car adds value — and when it can stay', 'Entscheidet, wann das Auto nützt – und wann es stehen kann', 'Decidid cuándo aporta el coche y cuándo puede quedarse', 'Bepaal wanneer de auto helpt en wanneer hij kan blijven staan', 'Avgör när bilen hjälper och när den kan stå kvar'), paragraphs: [
    l('Central Nerja and Torrecilla can support many plans on foot. Burriana, Maro or trips beyond town can create a different case for using the car.', 'Zentrales Nerja und Torrecilla ermöglichen viele Wege zu Fuß. Burriana, Maro oder Ausflüge außerhalb der Stadt können einen anderen Autoeinsatz sinnvoll machen.', 'El centro y Torrecilla permiten muchos planes a pie. Burriana, Maro o excursiones fuera crean otro caso para usar coche.', 'Centrum en Torrecilla maken veel plannen te voet mogelijk. Burriana, Maro of uitstapjes buiten de stad kunnen een ander autogebruik vragen.', 'Centrum och Torrecilla möjliggör mycket till fots. Burriana, Maro eller utflykter utanför staden kan ge ett annat bilbehov.'),
    l('For a multi-day stay, parking once and walking can be more useful than repeatedly searching close to every destination. The right answer depends on your area and day plan.', 'Bei mehreren Tagen kann einmal parken und laufen sinnvoller sein als ständig direkt am Ziel neu zu suchen. Die Antwort hängt von Lage und Tagesplan ab.', 'En varios días puede ser mejor aparcar una vez y caminar que buscar junto a cada destino. Depende de la zona y del plan.', 'Bij meerdere dagen kan één keer parkeren en lopen beter zijn dan steeds dichtbij zoeken. Het hangt van gebied en dagplan af.', 'Under flera dagar kan en parkering och promenader vara bättre än att söka vid varje mål. Det beror på område och dagsplan.')
  ]},
  { id: 'last-mile', eyebrow: l('04 · Last mile and accessibility', '04 · Letzter Weg und Zugänglichkeit', '04 · Último tramo y accesibilidad', '04 · Laatste route en toegankelijkheid', '04 · Sista sträckan och tillgänglighet'), title: l('A town route and a property entrance are not the same thing', 'Stadtweg und Hauseingang sind nicht dasselbe', 'La ruta urbana y la entrada no son lo mismo', 'Stadsroute en woningingang zijn niet hetzelfde', 'Stadsväg och bostadsentré är inte samma sak'), paragraphs: [
    l('A nearby street or municipal facility does not prove a step-free route. Kerbs, gradients, surfaces and the building entrance must be checked together.', 'Eine nahe Straße oder Anlage beweist keine stufenfreie Route. Bordsteine, Steigungen, Oberflächen und Hauseingang müssen zusammen geprüft werden.', 'Una calle o instalación cercana no demuestra ruta sin escalones. Bordillos, pendientes, pavimento y entrada deben revisarse juntos.', 'Een nabije straat of voorziening bewijst geen trapvrije route. Stoepen, hellingen, ondergrond en ingang moeten samen worden bekeken.', 'En närliggande gata eller anläggning bevisar ingen stegfri rutt. Kanter, lutning, underlag och entré måste granskas tillsammans.'),
    l('AMARA’s current amenities baseline indicates stairs for AMARA Playa. Guests for whom this matters should confirm the exact arrival route before booking.', 'Der aktuelle AMARA-Ausstattungsbestand weist bei AMARA Playa auf Stufen hin. Wenn das entscheidend ist, bestätigt vor der Buchung die konkrete Ankunftsroute.', 'La base actual de AMARA indica escaleras en AMARA Playa. Si importa, confirmad la ruta exacta antes de reservar.', 'De huidige AMARA-basis noemt trappen bij AMARA Playa. Bevestig de exacte route vóór boeken als dit belangrijk is.', 'AMARA:s nuvarande baslinje anger trappor vid AMARA Playa. Bekräfta exakt rutt före bokning om det är viktigt.')
  ]},
  { id: 'seasonal-rules', eyebrow: l('05 · Seasons and live systems', '05 · Saison und Live-Systeme', '05 · Temporada y sistemas actuales', '05 · Seizoen en live-systemen', '05 · Säsong och livesystem'), title: l('The city is improving parking — while the details keep moving', 'Die Stadt verbessert das Parken – während Details sich verändern', 'La ciudad mejora el aparcamiento mientras cambian los detalles', 'De stad verbetert parkeren terwijl details veranderen', 'Staden förbättrar parkering medan detaljer förändras'), paragraphs: [
    l('In 2026 Verano Azul was re-marked, Balcón’s free-space guidance was extended by contract and Burriana received a smart-parking contract. These are real municipal actions, not proof that parking is always easy.', '2026 wurde Verano Azul neu markiert, die Freiplatzführung am Balcón vertraglich erweitert und Burriana mit Smart Parking beauftragt. Das sind reale Maßnahmen, kein Beweis für stets einfaches Parken.', 'En 2026 se repintó Verano Azul, se contrató ampliar el guiado del Balcón y se adjudicó smart parking en Burriana. Son acciones reales, no prueba de facilidad constante.', 'In 2026 werd Verano Azul opnieuw gemarkeerd, begeleiding bij Balcón uitgebreid en smart parking voor Burriana aanbesteed. Dat bewijst niet dat parkeren altijd makkelijk is.', 'Under 2026 målades Verano Azul om, vägledningen vid Balcón utökades genom avtal och Burriana fick smart parking-kontrakt. Det bevisar inte att parkering alltid är enkel.'),
    l('Published capacity figures for Balcón conflict, and project completion can lag behind announcements. Use current operator information; do not hard-code capacity, price or live availability.', 'Veröffentlichte Kapazitäten für den Balcón widersprechen sich, und Projektabschluss kann Meldungen hinterherlaufen. Nutzt Betreiberinfos; schreibt Kapazität, Preis oder Verfügbarkeit nicht fest.', 'Las cifras de capacidad del Balcón se contradicen y la finalización puede ir detrás del anuncio. Usad información actual y no fijéis capacidad, precio o disponibilidad.', 'Capaciteitscijfers voor Balcón spreken elkaar tegen en uitvoering kan achter berichten lopen. Gebruik actuele informatie en zet capaciteit, prijs of beschikbaarheid niet vast.', 'Kapacitetssiffror för Balcón motsäger varandra och genomförande kan släpa efter besked. Använd aktuell information och lås inte kapacitet, pris eller tillgång.')
  ]},
  { id: 'amara-boundary', eyebrow: l('06 · AMARA boundary', '06 · AMARA-Grenze', '06 · Límite AMARA', '06 · AMARA-grens', '06 · AMARA-gränsen'), title: l('Destination guidance and AMARA arrival instructions have different jobs', 'Ortsguide und AMARA-Ankunftsanweisung haben andere Aufgaben', 'La guía del destino y la llegada AMARA cumplen funciones distintas', 'Bestemmingsgids en AMARA-aankomst hebben andere taken', 'Destinationsguide och AMARA-ankomst har olika uppgifter'), paragraphs: [
    l('This page explains how Nerja’s areas and public systems differ. It cannot promise the nearest street space for a specific arrival.', 'Diese Seite erklärt Zonen und öffentliche Systeme. Sie kann für eine konkrete Ankunft keinen nächsten Straßenplatz versprechen.', 'Esta página explica zonas y sistemas públicos. No puede prometer la plaza de calle más cercana para una llegada.', 'Deze pagina legt gebieden en publieke systemen uit. Ze kan geen dichtstbijzijnde straatplek beloven.', 'Sidan förklarar områden och offentliga system. Den kan inte lova närmaste gatuplats vid en ankomst.'),
    l('AMARA Playa instructions should own the unloading point, exact walking route and confirmed property access. Keep those details current and separate from general Nerja claims.', 'AMARA-Playa-Hinweise besitzen Ausladepunkt, exakten Fußweg und bestätigten Zugang. Diese Details bleiben aktuell und getrennt von allgemeinen Nerja-Aussagen.', 'Las instrucciones de AMARA Playa deben contener descarga, ruta exacta y acceso confirmado, separados de afirmaciones generales.', 'AMARA Playa-instructies horen lossen, exacte looproute en toegang te bevatten, los van algemene Nerja-claims.', 'AMARA Playa-instruktioner ska äga avlastning, exakt gångväg och bekräftad entré, skilt från allmänna Nerja-påståenden.')
  ]}
];

const related = [
  { token: 'getting_to_nerja' as const, label: l('Arrival & Mobility', 'Anreise & Mobilität', 'Llegada y movilidad', 'Aankomst & mobiliteit', 'Ankomst & mobilitet'), text: l('Airports, roads and regional transport.', 'Flughäfen, Straßen und Regionalverkehr.', 'Aeropuertos, carreteras y transporte regional.', 'Luchthavens, wegen en regionaal vervoer.', 'Flygplatser, vägar och regional transport.') },
  { token: 'nerja_where_to_stay' as const, label: l('Where to Stay', 'Wo übernachten', 'Dónde alojarse', 'Waar overnachten', 'Var ska man bo'), text: l('Choose the area before choosing the parking strategy.', 'Erst die Lage, dann die Parkstrategie wählen.', 'Elegid la zona antes de la estrategia de aparcamiento.', 'Kies het gebied vóór de parkeerstrategie.', 'Välj område före parkeringsstrategi.') },
  { token: 'nerja_beaches_authority' as const, label: l('Beaches & Coast', 'Strände & Küste', 'Playas y costa', 'Stranden & kust', 'Stränder & kust'), text: l('Connect Burriana, Torrecilla and other beach days to their own context.', 'Burriana, Torrecilla und andere Strandtage im eigenen Kontext planen.', 'Planificad Burriana, Torrecilla y otras playas en su contexto.', 'Plan Burriana, Torrecilla en andere stranden in hun context.', 'Planera Burriana, Torrecilla och andra stränder i sitt sammanhang.') }
];

const sourceRows = [
  { label: l('Ayuntamiento · existing facilities and planned project', 'Ayuntamiento · bestehende Anlagen und Projekt', 'Ayuntamiento · instalaciones y proyecto', 'Gemeente · voorzieningen en project', 'Kommunen · anläggningar och projekt'), text: l('Names Balcón, Verano Azul and Burriana; the 847 spaces remain planned.', 'Nennt Balcón, Verano Azul und Burriana; 847 Plätze bleiben geplant.', 'Cita Balcón, Verano Azul y Burriana; 847 plazas siguen previstas.', 'Noemt Balcón, Verano Azul en Burriana; 847 plaatsen blijven gepland.', 'Nämner Balcón, Verano Azul och Burriana; 847 platser är planerade.'), href: 'https://www.nerja.es/luz-verde-al-anteproyecto-del-nuevo-aparcamiento-con-847-plazas/' },
  { label: l('Balcón · free-space guidance', 'Balcón · Freiplatzführung', 'Balcón · guiado de plazas', 'Balcón · vrije-plekbegeleiding', 'Balcón · vägledning till lediga platser'), text: l('Dated 2026 contract and rollout information.', 'Datierte Vertrags- und Rolloutinformation 2026.', 'Contrato y despliegue fechado en 2026.', 'Gedateerde contract- en uitrolinfo 2026.', 'Daterad avtals- och utrullningsinfo 2026.'), href: 'https://www.nerja.es/el-ayuntamiento-completara-el-guiado-de-plazas-libres-del-aparcamiento-balcon-de-europa/' },
  { label: l('Verano Azul · municipal maintenance', 'Verano Azul · kommunale Instandhaltung', 'Verano Azul · mantenimiento municipal', 'Verano Azul · gemeentelijk onderhoud', 'Verano Azul · kommunalt underhåll'), text: l('Current re-marking, not a tariff or availability claim.', 'Aktuelle Neumarkierung, keine Preis- oder Verfügbarkeitsaussage.', 'Repintado actual, no afirmación de precio o disponibilidad.', 'Actuele markering, geen prijs- of beschikbaarheidsclaim.', 'Aktuell ommålning, inget pris- eller tillgänglighetspåstående.'), href: 'https://www.nerja.es/el-ayuntamiento-sigue-mejorando-los-aparcamientos-municipales-con-la-pintura-integral-del-verano-azul/' },
  { label: l('Burriana · smart-parking project', 'Burriana · Smart-Parking-Projekt', 'Burriana · proyecto smart parking', 'Burriana · smart-parkingproject', 'Burriana · smart parking-projekt'), text: l('Contracted functionality; verify live operation.', 'Beauftragte Funktion; Live-Betrieb prüfen.', 'Función adjudicada; comprobad operación real.', 'Aanbestede functie; controleer live werking.', 'Avtalad funktion; kontrollera live-drift.'), href: 'https://www.nerja.es/el-aparcamiento-municipal-de-burriana-contara-con-un-sistema-inteligente-de-guiado-de-plazas-libres/' }
];

const makeLocale = (lang: AmaraLanguage): ParkingGuideLocale => ({
  navLabel: navLabel[lang], hero: { eyebrow: hero.eyebrow[lang], title: hero.title[lang], standfirst: hero.standfirst[lang], note: hero.note[lang], updated: hero.updated[lang] },
  facts: facts.map((item) => ({ label: item.label[lang], value: item.value[lang] })),
  sections: sections.map((section) => ({ id: section.id, eyebrow: section.eyebrow[lang], title: section.title[lang], paragraphs: section.paragraphs.map((p) => p[lang]) })),
  related: { eyebrow: l('Continue planning', 'Weiter planen', 'Seguir planificando', 'Verder plannen', 'Planera vidare')[lang], title: l('Connect the parking choice to the real area', 'Die Parkentscheidung mit der echten Lage verbinden', 'Conectad el aparcamiento con la zona real', 'Verbind de parkeerkeuze met het echte gebied', 'Koppla parkeringsvalet till rätt område')[lang], links: related.map((item) => ({ token: item.token, label: item.label[lang], text: item.text[lang] })) },
  sources: { eyebrow: l('Official evidence', 'Amtliche Belege', 'Fuentes oficiales', 'Officiële bronnen', 'Officiella källor')[lang], title: l('Projects show direction, not a guaranteed space', 'Projekte zeigen Richtung, keinen garantierten Platz', 'Los proyectos muestran dirección, no una plaza garantizada', 'Projecten tonen richting, geen gegarandeerde plek', 'Projekt visar riktning, inte garanterad plats')[lang], intro: l('Municipal sources verify facilities and improvement projects. Prices, capacity and live availability remain dynamic.', 'Gemeindequellen belegen Anlagen und Verbesserungen. Preise, Kapazität und Verfügbarkeit bleiben dynamisch.', 'Las fuentes municipales verifican instalaciones y mejoras. Precios, capacidad y disponibilidad siguen dinámicos.', 'Gemeentebronnen bevestigen voorzieningen en verbeteringen. Prijs, capaciteit en beschikbaarheid blijven dynamisch.', 'Kommunala källor bekräftar anläggningar och förbättringar. Pris, kapacitet och tillgång förblir dynamiska.')[lang], checked: l('Sources reviewed 21 August 2026', 'Quellen geprüft am 21. August 2026', 'Fuentes revisadas el 21 de agosto de 2026', 'Bronnen gecontroleerd op 21 augustus 2026', 'Källor granskade 21 augusti 2026')[lang], links: sourceRows.map((item) => ({ label: item.label[lang], text: item.text[lang], href: item.href })) },
  closing: { eyebrow: l('Park for the Nerja you actually plan to use', 'Für das Nerja parken, das ihr wirklich nutzt', 'Aparcad para la Nerja que realmente vais a usar', 'Parkeer voor het Nerja dat jullie echt gebruiken', 'Parkera för det Nerja ni faktiskt ska använda')[lang], title: l('Choose the area first, then the parking context', 'Erst die Lage wählen, dann den Parkkontext', 'Primero la zona, después el aparcamiento', 'Eerst het gebied, daarna de parkeercontext', 'Välj område först, sedan parkering')[lang], body: l('Nerja becomes easier to understand when centre, beach and accommodation are not treated as the same destination. For AMARA Playa, continue with the current property and arrival details.', 'Nerja wird leichter verständlich, wenn Zentrum, Strand und Unterkunft nicht dasselbe Ziel sind. Für AMARA Playa geht es mit aktuellen Objekt- und Ankunftsdetails weiter.', 'Nerja se entiende mejor cuando centro, playa y alojamiento no son el mismo destino. Para AMARA Playa, seguid con los datos actuales de la vivienda.', 'Nerja wordt duidelijker wanneer centrum, strand en verblijf niet hetzelfde doel zijn. Ga voor AMARA Playa verder met actuele woning- en aankomstinfo.', 'Nerja blir tydligare när centrum, strand och boende inte behandlas som samma mål. Fortsätt till aktuella boende- och ankomstuppgifter för AMARA Playa.')[lang], locationLabel: l('Explore Nerja', 'Nerja entdecken', 'Descubrir Nerja', 'Ontdek Nerja', 'Upptäck Nerja')[lang], propertyLabel: l('View AMARA Playa', 'AMARA Playa ansehen', 'Ver AMARA Playa', 'Bekijk AMARA Playa', 'Se AMARA Playa')[lang] }
});

export const nerjaParkingContent = Object.fromEntries(langs.map((lang) => [lang, makeLocale(lang)])) as Record<AmaraLanguage, ParkingGuideLocale>;
