import type { LinkToken } from '../lib/linkResolver';
import type { LocalizedText } from '../types/content';
import type { AmaraAuthoringSeo } from '../types/seo';

/** One authored string in the five AMARA locales, in EN, DE, ES, NL, SV order. */
const l = (en: string, de: string, es: string, nl: string, sv: string): LocalizedText => ({ en, de, es, nl, sv });

/**
 * Primary intent: the lived proposition of a multi-day or multi-week Tarifa winter stay.
 * Weather detail remains with the seasonal guide; remote work remains a supporting use case.
 * Native query families:
 * EN Tarifa in winter / winter in Tarifa / Tarifa winter weather / winter stay / long stay / winter sun / remote work;
 * DE Tarifa im Winter / Winter in Tarifa / Winterwetter / Winteraufenthalt / Langzeiturlaub / Wintersonne / Workation;
 * ES Tarifa en invierno / invierno en Tarifa / tiempo en invierno / estancia de invierno / larga estancia / sol de invierno / teletrabajo;
 * NL Tarifa in de winter / winter in Tarifa / winterweer / winterverblijf / lang verblijf / winterzon / werken op afstand;
 * SV Tarifa på vintern / vinter i Tarifa / vinterväder / vintervistelse / längre vistelse / vintersol / distansarbete.
 * Entities: Tarifa, La Marina, Mar Adriático 29, AMARA Family & Surf, the Atlantic coast,
 * Strait of Gibraltar, Africa, the Atlas Mountains and Tarifa Old Town.
 */

const article = {
  datePublished: '2026-08-13',
  dateModified: '2026-08-21',
  authorName: 'Robert Sebastian Böhmer',
  authorType: 'Person' as const,
  authorSlug: 'amara-about-us'
};

export const tarifaWinterStaysSeo: AmaraAuthoringSeo = {
  version: '2026-08-21-tarifa-winter-stays-v2.0',
  pageType: 'A',
  entityKey: 'amara-brand',
  article,
  languages: {
    en: {
      title: 'Tarifa in Winter: Light, Calm & Longer Stays',
      description: 'See what winter in Tarifa feels like: milder days, Atlantic walks, a more familiar town and a comfortable home for staying several weeks.',
      robots: 'index, follow',
      canonical: 'auto'
    },
    de: {
      title: 'Tarifa im Winter: Licht, Ruhe & längere Aufenthalte',
      description: 'So fühlt sich Tarifa im Winter an: mildere Tage, Atlantikspaziergänge, ein vertrauterer Ort und ein komfortables Zuhause für mehrere Wochen.',
      robots: 'index, follow',
      canonical: 'auto'
    },
    es: {
      title: 'Tarifa en invierno: luz, calma y estancias largas',
      description: 'Así se vive Tarifa en invierno: días suaves, paseos por el Atlántico, una localidad más cercana y una casa cómoda para quedaros varias semanas.',
      robots: 'index, follow',
      canonical: 'auto'
    },
    nl: {
      title: 'Tarifa in de winter: licht, rust & langer verblijven',
      description: 'Ervaar Tarifa in de winter: mildere dagen, Atlantische wandelingen, een vertrouwdere stad en een comfortabel huis voor enkele weken.',
      robots: 'index, follow',
      canonical: 'auto'
    },
    sv: {
      title: 'Tarifa på vintern: ljus, lugn och längre vistelser',
      description: 'Så känns Tarifa på vintern: mildare dagar, promenader vid Atlanten, en mer välbekant stad och ett bekvämt hem för flera veckor.',
      robots: 'index, follow',
      canonical: 'auto'
    }
  }
};

const sourceHrefs = {
  tarifaNormals: 'https://www.aemet.es/es/serviciosclimaticos/datosclimatologicos/valoresclimatologicos?k=and&l=6001',
  tarifaViewpoints: 'https://turismodetarifa.com/que-hacer/parques-naturales-senderismo/',
  tarifaWind: 'https://www.juntadeandalucia.es/medioambiente/portal/landing-page-%C3%ADndice/-/asset_publisher/zX2ouZa4r1Rf/content/viento/20151',
  travelIntent: 'https://etc-corporate.org/reports/monitoring-sentiment-for-intra-european-travel-autumn-25-winter-2026/'
} as const;

export const tarifaWinterStaysContent = {
  navLabel: l("Winter Stays", "Winteraufenthalte", "Estancias de invierno", "Winterverblijven", "Vintervistelser"),
  hero: {
    eyebrow: l("A host’s winter guide to Tarifa", "Ein persönlicher Winterguide für Tarifa", "Una guía personal del invierno en Tarifa", "Een persoonlijke wintergids voor Tarifa", "En personlig vinterguide till Tarifa"),
    title: l("Winter in Tarifa is a different season, not a lesser one", "Der Winter ist nicht die kleinere Version von Tarifa", "El invierno no es una versión menor de Tarifa", "De winter is geen mindere versie van Tarifa", "Vintern är inte en mindre version av Tarifa"),
    standfirst: l("Summer brings intensity. Winter makes room for daylight, Atlantic walks, changing weather and the ordinary rhythm of town. For guests who can stay for more than a few days, **that quieter version can be the more rewarding one**.", "Der Sommer bringt Intensität. Im Winter entstehen Freiräume für Tageslicht, Atlantikspaziergänge, wechselndes Wetter und den normalen Rhythmus des Ortes. Wenn ihr länger als ein paar Tage bleiben könnt, erlebt ihr möglicherweise **gerade diese ruhigere Seite als die wertvollere**.", "El verano trae intensidad. El invierno deja espacio para la luz, los paseos junto al Atlántico, el tiempo cambiante y el ritmo normal de la localidad. Para quienes pueden quedarse más de unos días, **esa versión tranquila quizá sea la más gratificante**.", "De zomer brengt intensiteit. De winter geeft ruimte aan daglicht, wandelingen langs de Atlantische Oceaan, wisselend weer en het gewone ritme van de stad. Wie langer dan enkele dagen kan blijven, ervaart **die rustigere versie misschien als de meest waardevolle**.", "Sommaren ger intensitet. Vintern lämnar utrymme för dagsljus, promenader vid Atlanten, växlande väder och stadens vanliga rytm. För er som kan stanna längre än några dagar kan **den lugnare versionen vara den mest givande**."),
    note: l("Written from Robert’s first-hand host experience. Personal observations describe how winter has felt to us over time; they are not promises about every day or every visit.", "Geschrieben aus Roberts eigener Erfahrung als Gastgeber. Die persönlichen Beobachtungen beschreiben, wie wir den Winter über die Jahre erlebt haben.", "Escrita desde la experiencia directa de Robert como anfitrión. Las observaciones personales cuentan cómo hemos vivido el invierno a lo largo del tiempo.", "Geschreven vanuit Roberts eigen ervaring als host. Persoonlijke observaties beschrijven hoe de winter door de jaren heen voor ons voelde; ze beloven niet dat elke dag of elk verblijf hetzelfde is.", "Skriven utifrån Roberts egen erfarenhet som värd. De personliga observationerna beskriver hur vintern har känts för oss över tid."),
    updated: l("Host perspective and supporting sources reviewed August 2026", "Gastgeberperspektive und Quellen geprüft im August 2026", "Perspectiva del anfitrión y fuentes revisadas en agosto de 2026", "Hostperspectief en bronnen gecontroleerd in augustus 2026", "Värdperspektiv och källor granskade i augusti 2026"),
    mark: l("WINTER", "WINTER", "INVIERNO", "WINTER", "VINTER")
  },
  facts: [
    {
      label: l("Host perspective", "Gastgeberperspektive", "Perspectiva del anfitrión", "Hostperspectief", "Värdperspektiv"),
      value: l("One of Robert’s favourite times in Tarifa", "Eine von Roberts liebsten Zeiten in Tarifa", "Una de las épocas favoritas de Robert en Tarifa", "Een van Roberts favoriete periodes in Tarifa", "En av Roberts favorittider i Tarifa")
    },
    {
      label: l("Winter rhythm", "Winterrhythmus", "Ritmo de invierno", "Winterritme", "Vinterrytm"),
      value: l("More usable daylight than northern Europe", "Mehr nutzbares Tageslicht als in Nordeuropa", "Más luz aprovechable que en el norte de Europa", "Meer bruikbaar daglicht dan in Noord-Europa", "Mer användbart dagsljus än i norra Europa")
    },
    {
      label: l("Atlantic time", "Zeit am Atlantik", "Tiempo atlántico", "Tijd aan de Atlantische kust", "Tid vid Atlanten"),
      value: l("Walking · waves · sunsets · fresh air", "Gehen · Wellen · Sonnenuntergänge · frische Luft", "Caminar · olas · atardeceres · aire libre", "Wandelen · golven · zonsondergang · buitenlucht", "Promenader · vågor · solnedgång · frisk luft")
    },
    {
      label: l("At home", "Zu Hause", "En casa", "Thuis", "Hemma"),
      value: l("Heating · fireplace · kitchen · washing machine", "Heizung · Kamin · Küche · Waschmaschine", "Calefacción · chimenea · cocina · lavadora", "Verwarming · open haard · keuken · wasmachine", "Värme · eldstad · kök · tvättmaskin")
    }
  ],
  sections: [
    {
      id: "when-summer-leaves",
      eyebrow: l("01 · A different Tarifa", "01 · Ein anderes Tarifa", "01 · Otra Tarifa", "01 · Een ander Tarifa", "01 · Ett annat Tarifa"),
      title: l("Tarifa when summer leaves", "Tarifa, wenn der Sommer vorbei ist", "Tarifa cuando termina el verano", "Tarifa wanneer de zomer vertrekt", "Tarifa när sommaren lämnar"),
      paragraphs: [
        l("Winter has always been one of Robert’s favourite times in Tarifa. After the highly transient rhythm of summer, the town feels smaller, calmer and more familiar to us — not empty, and not reduced to a town populated only by residents.", "Der Winter war für Robert schon immer eine der liebsten Zeiten in Tarifa. Nach dem sehr flüchtigen Sommerrhythmus wirkt der Ort auf uns kleiner, ruhiger und vertrauter — nicht leer und auch nicht wie ein Ort, in dem fast nur Einheimische leben.", "El invierno siempre ha sido una de las épocas favoritas de Robert en Tarifa. Tras el ritmo muy transitorio del verano, la localidad nos parece más pequeña, tranquila y familiar; no vacía ni habitada principalmente por gente local.", "De winter is altijd een van Roberts favoriete periodes in Tarifa geweest. Na het zeer vluchtige zomerritme voelt de stad voor ons kleiner, rustiger en vertrouwder — niet leeg en ook niet alsof er vooral inwoners zouden zijn.", "Vintern har alltid varit en av Roberts favorittider i Tarifa. Efter sommarens mycket tillfälliga rytm känns staden för oss mindre, lugnare och mer välbekant — inte tom och inte som om den främst bestod av lokalbefolkning."),
        l("Over a longer winter stay, the same faces start to reappear in cafés, around town, on the beach and in ordinary routines. That familiarity is one of the quieter pleasures of the season.", "Während eines längeren Winteraufenthalts begegnen euch in Cafés, im Ort, am Strand und in alltäglichen Abläufen bald dieselben Gesichter wieder. Diese Vertrautheit gehört für uns zum Schönsten an der Jahreszeit.", "Durante una estancia larga de invierno suelen reaparecer caras conocidas en cafeterías, por el centro, en la playa y en las rutinas diarias. Es una observación de primera mano, no una promesa de que haréis amigos o viviréis la misma experiencia social.", "Tijdens een langer winterverblijf duiken dezelfde gezichten al snel weer op in cafés, in de stad, op het strand en in dagelijkse routines. Die vertrouwdheid hoort voor ons bij het mooiste van het seizoen.", "Under en längre vintervistelse återkommer ofta bekanta ansikten på kaféer, i stan, på stranden och i vardagens rutiner. Det är en förstahandsobservation, inte ett löfte om att ni får nya vänner eller samma sociala upplevelse."),
        l("The practical consequence is time. A few summer days can be built around highlights; several winter weeks allow Tarifa to become a place you temporarily live in. AMARA in La Marina gives that slower rhythm a real home rather than a short-break base.", "Der praktische Unterschied ist Zeit. Einige Sommertage drehen sich leicht um Höhepunkte; in mehreren Winterwochen kann Tarifa vorübergehend zum eigenen Alltag werden. AMARA in La Marina gibt diesem langsameren Rhythmus ein richtiges Zuhause statt nur eine Basis für einen Kurztrip.", "La consecuencia práctica es el tiempo. Unos días de verano pueden girar alrededor de los lugares imprescindibles; varias semanas de invierno permiten vivir Tarifa temporalmente. AMARA, en La Marina, ofrece una casa real para ese ritmo lento, no solo una base para una escapada.", "Het praktische verschil is tijd. Enkele zomerdagen draaien gemakkelijk om hoogtepunten; in meerdere winterweken kan Tarifa tijdelijk een plek worden waar jullie leven. AMARA in La Marina geeft dat langzamere ritme een echt thuis in plaats van alleen een uitvalsbasis voor een korte reis.", "Den praktiska skillnaden är tid. Några sommardagar kan byggas kring höjdpunkter; flera vinterveckor låter Tarifa bli en plats där ni tillfälligt lever. AMARA i La Marina ger den långsammare rytmen ett verkligt hem i stället för bara en bas för en kort resa.")
      ]
    },
    {
      id: "northern-winter",
      eyebrow: l("02 · South without false promises", "02 · Süden ohne falsche Versprechen", "02 · Sur sin falsas promesas", "02 · Zuiden zonder valse belofte", "02 · Söder utan falska löften"),
      title: l("Escaping the northern winter", "Dem nordeuropäischen Winter entkommen", "Escapar del invierno del norte", "Ontsnappen aan de Noord-Europese winter", "Lämna den nordliga vintern en stund"),
      paragraphs: [
        l("Tarifa sits far south of the northern-European markets from which many guests travel. Winter can bring mild, bright days and more usable daylight, while northern days are often shorter and colder. It is still winter: rain, wind and cool evenings remain part of the season.", "Tarifa liegt weit südlich der nordeuropäischen Märkte, aus denen viele Gäste anreisen. Der Winter kann milde, helle Tage und mehr nutzbares Tageslicht bringen, während die Tage im Norden oft kürzer und kälter sind. Trotzdem bleibt es Winter: Regen, Wind und kühle Abende gehören zur Jahreszeit.", "Tarifa está muy al sur de los mercados del norte de Europa desde los que viajan muchos huéspedes. El invierno puede traer días suaves, luminosos y con más horas aprovechables, mientras que en el norte suelen ser más cortos y fríos. Sigue siendo invierno: lluvia, viento y noches frescas forman parte de la estación.", "Tarifa ligt ver ten zuiden van de Noord-Europese markten waar veel gasten vandaan komen. De winter kan milde, heldere dagen en meer bruikbaar daglicht brengen, terwijl noordelijke dagen vaak korter en kouder zijn. Het blijft winter: regen, wind en koele avonden horen bij het seizoen.", "Tarifa ligger långt söder om de nordeuropeiska marknader som många gäster reser från. Vintern kan ge milda, ljusa dagar och mer användbart dagsljus, medan dagarna i norr ofta är kortare och kallare. Det är fortfarande vinter: regn, vind och svala kvällar hör till säsongen."),
        l("The difference matters most when you have time to use the good hours rather than expecting every day to behave like summer. A late walk, lunch outside on a mild day or time by the coast may become possible; none should be scheduled as a weather guarantee.", "Der Unterschied zählt besonders, wenn ihr genug Zeit habt, die guten Stunden zu nutzen, statt von jedem Tag Sommerwetter zu erwarten. Ein später Spaziergang, Mittagessen draußen an einem milden Tag oder Zeit an der Küste können möglich sein; nichts davon ist eine Wettergarantie.", "La diferencia se aprecia sobre todo cuando tenéis tiempo para aprovechar las mejores horas sin exigir que cada día se comporte como verano. Un paseo tardío, comer fuera en un día suave o pasar tiempo en la costa pueden ser posibles; nunca deben planificarse como garantía meteorológica.", "Het verschil telt vooral wanneer jullie tijd hebben om de goede uren te gebruiken zonder te verwachten dat elke dag zomers is. Een late wandeling, buiten lunchen op een milde dag of tijd aan de kust kan mogelijk zijn; niets daarvan is een weergarantie.", "Skillnaden betyder mest när ni har tid att använda de bra timmarna utan att vänta er sommar varje dag. En sen promenad, lunch utomhus en mild dag eller tid vid kusten kan vara möjlig; inget av det ska planeras som en vädergaranti."),
        l("For a stay of several weeks, AMARA combines that southern setting with heating, hot-and-cold air-conditioning and a wood-burning fireplace. The proposition is not endless sun, but more chances to be outside and a comfortable place to return to when the day changes.", "Für mehrere Wochen verbindet AMARA diese südliche Lage mit Heizung, Klimaanlage zum Kühlen und Heizen sowie einem Holzkamin. Es geht nicht um endlose Sonne, sondern um mehr Chancen draußen und ein komfortables Zuhause, wenn der Tag umschlägt.", "Para varias semanas, AMARA une este entorno meridional con calefacción, aire acondicionado con frío y calor y chimenea de leña. La propuesta no es sol infinito, sino más ocasiones para salir y una casa cómoda a la que volver cuando cambia el día.", "Voor enkele weken combineert AMARA die zuidelijke ligging met verwarming, airconditioning voor koelen en verwarmen en een houtgestookte open haard. Het verhaal is geen eindeloze zon, maar meer kansen om buiten te zijn en een comfortabel huis wanneer de dag omslaat.", "För flera veckor förenar AMARA det sydliga läget med värme, luftkonditionering för kyla och värme samt en vedeldad eldstad. Berättelsen är inte oändlig sol, utan fler chanser utomhus och ett bekvämt hem när dagen ändras.")
      ]
    },
    {
      id: "winter-light",
      eyebrow: l("03 · Horizon and daylight", "03 · Horizont und Tageslicht", "03 · Horizonte y luz", "03 · Horizon en daglicht", "03 · Horisont och dagsljus"),
      title: l("Winter light, Africa and the long view", "Winterlicht, Afrika und der weite Blick", "Luz de invierno, África y amplitud de vistas", "Winterlicht, Afrika en het verre uitzicht", "Vinterljus, Afrika och den långa utsikten"),
      paragraphs: [
        l("Tarifa’s official tourism information describes views towards Africa from the town and coast, and even the Atlas Mountains from La Peña on clear days. That geography is real in every season; visibility always depends on the conditions of the day.", "Tarifas offizielle Tourismusinformationen beschreiben Blicke nach Afrika vom Ort und von der Küste; an klaren Tagen sind vom Mirador de la Peña sogar die Atlasberge zu sehen. Diese Geografie ist zu jeder Jahreszeit real, die Sicht hängt immer von den Bedingungen des Tages ab.", "La información oficial de Turismo de Tarifa describe vistas hacia África desde el núcleo y la costa, e incluso hacia el Atlas desde La Peña en días claros. Esa geografía existe todo el año; la visibilidad depende siempre de las condiciones concretas.", "De officiële toeristische informatie van Tarifa beschrijft uitzichten richting Afrika vanuit de stad en vanaf de kust, en op heldere dagen zelfs naar het Atlasgebergte vanaf La Peña. Die geografie is er elk seizoen; zicht hangt altijd af van de omstandigheden.", "Tarifas officiella turistinformation beskriver utsikt mot Afrika från staden och kusten, och på klara dagar även Atlasbergen från La Peña. Geografin är verklig under alla årstider; sikten beror alltid på dagens förhållanden."),
        l("In Robert’s own winter experience, the clarity can sometimes feel especially striking: lower light across the Atlantic, the African coast on the horizon and sunsets that give an ordinary afternoon a clear destination. That is a host memory, not a meteorological rule about winter air.", "In Roberts eigener Wintererfahrung kann die Klarheit manchmal besonders eindrucksvoll wirken: tiefes Licht über dem Atlantik, die afrikanische Küste am Horizont und Sonnenuntergänge, die einem normalen Nachmittag ein klares Ziel geben. Das ist Gastgebererfahrung, keine allgemeine Wetterregel für Winterluft.", "En la experiencia invernal de Robert, la claridad puede resultar a veces especialmente llamativa: luz baja sobre el Atlántico, la costa africana en el horizonte y atardeceres que dan un destino claro a una tarde normal. Es memoria de anfitrión, no una regla meteorológica sobre el aire invernal.", "In Roberts eigen winterervaring kan de helderheid soms bijzonder sterk overkomen: laag licht over de Atlantische Oceaan, de Afrikaanse kust aan de horizon en zonsondergangen die een gewone middag richting geven. Dat is een herinnering van de host, geen algemene meteorologische regel.", "I Roberts egen vintererfarenhet kan klarheten ibland kännas särskilt stark: lågt ljus över Atlanten, Afrikas kust vid horisonten och solnedgångar som ger en vanlig eftermiddag ett tydligt mål. Det är ett värdminne, inte en allmän meteorologisk regel."),
        l("For guests staying longer, usable afternoon light changes the shape of a day. Work or errands can finish before a coastal walk, a viewpoint or sunset, while AMARA’s Atlantic-facing terrace and easy route towards the western coast keep that horizon close.", "Bei einem längeren Aufenthalt verändert nutzbares Nachmittagslicht den Tag. Arbeit oder Erledigungen können vor einem Küstenspaziergang, Aussichtspunkt oder Sonnenuntergang enden; AMARAs Atlantikterrasse und der kurze Weg Richtung Westküste halten diesen Horizont nah.", "En una estancia larga, la luz útil de la tarde cambia el día. El trabajo o los recados pueden terminar antes de un paseo costero, un mirador o la puesta de sol; la terraza de AMARA orientada al Atlántico y la salida hacia poniente mantienen ese horizonte cerca.", "Tijdens een langer verblijf verandert bruikbaar middaglicht de dag. Werk of boodschappen kunnen eindigen voor een kustwandeling, uitzichtpunt of zonsondergang; AMARA’s terras aan de Atlantische zijde en de eenvoudige route westwaarts houden die horizon dichtbij.", "Under en längre vistelse ändrar användbart eftermiddagsljus dagens form. Arbete eller ärenden kan sluta före en kustpromenad, en utsiktsplats eller solnedgång; AMARAs terrass mot Atlanten och enkla väg västerut håller horisonten nära.")
      ]
    },
    {
      id: "changing-days",
      eyebrow: l("04 · Keep the day flexible", "04 · Bleibt mit dem Tag flexibel", "04 · Flexibilidad diaria", "04 · Houd ruimte in de dag", "04 · Lämna utrymme i dagen"),
      title: l("Wind, sun and changing days", "Wind, Sonne und wechselnde Tage", "Viento, sol y días cambiantes", "Wind, zon en wisselende dagen", "Vind, sol och skiftande dagar"),
      paragraphs: [
        l("Tarifa remains variable in winter. Levante can be strong, Atlantic fronts can bring rain, and calm or mild sunny periods can sit between them. The Weather & Seasons guide owns the climate detail; no winter-stay story should turn those patterns into a daily forecast.", "Tarifa bleibt im Winter wechselhaft. Der Levante kann stark sein, Atlantikfronten können Regen bringen, dazwischen liegen ruhige oder milde sonnige Phasen. Die Klimadetails gehören in Wetter & Jahreszeiten; kein Winterguide sollte daraus eine Tagesprognose machen.", "Tarifa continúa variable en invierno. El Levante puede soplar fuerte, los frentes atlánticos pueden traer lluvia y entre ambos aparecen periodos tranquilos o suaves y soleados. Los detalles climáticos pertenecen a Tiempo y estaciones; esta página no convierte patrones en pronósticos.", "Tarifa blijft in de winter veranderlijk. De Levante kan sterk zijn, Atlantische fronten kunnen regen brengen en daartussen liggen rustige of milde zonnige perioden. De klimaatdetails staan bij Weer & seizoenen; dit winterverhaal maakt van patronen geen dagvoorspelling.", "Tarifa fortsätter att vara omväxlande på vintern. Levante kan vara stark, Atlantfronter kan ge regn och mellan dem finns lugna eller milda soliga perioder. Klimatdetaljerna hör hemma i Väder & årstider; vinterberättelsen gör inte mönster till dagsprognoser."),
        l("A longer stay gives you a useful advantage: you can move the coast, town, work or a drive to the better part of the forecast. The aim is not to defeat the weather but to avoid making one day carry the whole trip.", "Ein längerer Aufenthalt gibt euch einen Vorteil: Küste, Ort, Arbeit oder Ausfahrt lassen sich in den besseren Teil der Vorhersage legen. Es geht nicht darum, das Wetter zu besiegen, sondern darum, dass nicht ein einzelner Tag die ganze Reise tragen muss.", "Una estancia larga ofrece una ventaja: podéis mover costa, pueblo, trabajo o excursión hacia el mejor tramo de la previsión. No se trata de vencer al tiempo, sino de evitar que un solo día tenga que sostener todo el viaje.", "Een langer verblijf geeft een voordeel: kust, stad, werk of autorit kunnen naar het betere deel van de verwachting verschuiven. Het doel is niet het weer te verslaan, maar te voorkomen dat één dag de hele reis moet dragen.", "En längre vistelse ger en fördel: kust, stad, arbete eller bilutflykt kan flyttas till den bättre delen av prognosen. Målet är inte att besegra vädret, utan att en enda dag inte ska behöva bära hela resan."),
        l("At AMARA, the full kitchen, heating and fireplace support the indoor part of that flexibility. Reserved underground parking and practical westbound access make it easier to use a brighter coastal window without implying that parking elsewhere will always be easy.", "Bei AMARA unterstützen die vollständige Küche, Heizung und der Kamin die Zeit drinnen. Reservierte Tiefgarage und praktische Ausfahrt Richtung Westen helfen, ein helleres Zeitfenster an der Küste zu nutzen, ohne freie Parkplätze an anderen Orten zu versprechen.", "En AMARA, la cocina completa, la calefacción y la chimenea respaldan la parte interior de esa flexibilidad. El garaje subterráneo reservado y la salida práctica hacia poniente ayudan a aprovechar un claro sin prometer aparcamiento fácil en otros destinos.", "Bij AMARA ondersteunen de volledige keuken, verwarming en open haard de tijd binnen. De gereserveerde ondergrondse parking en praktische route westwaarts helpen om een helder moment aan de kust te gebruiken zonder vrije parking elders te beloven.", "På AMARA stödjer det fullständiga köket, värmen och eldstaden tiden inomhus. Reserverad underjordisk parkering och praktisk väg västerut gör det enklare att använda en ljus kustperiod utan att lova ledig parkering vid andra mål.")
      ]
    },
    {
      id: "quieter-tarifa",
      eyebrow: l("05 · Familiarity over intensity", "05 · Vertrautheit statt Intensität", "05 · Familiaridad frente a intensidad", "05 · Vertrouwdheid boven intensiteit", "05 · Igenkänning framför intensitet"),
      title: l("The quieter side of Tarifa", "Die ruhigere Seite von Tarifa", "El lado más tranquilo de Tarifa", "De rustigere kant van Tarifa", "Tarifas lugnare sida"),
      paragraphs: [
        l("Summer can feel anonymous and highly transient. In our winter experience, there is usually less high-season pressure and more room for spontaneous everyday choices — but a popular restaurant can still be busy, a parking space elsewhere can still be hard to find and a beach is never promised empty.", "Der Sommer kann anonym und sehr flüchtig wirken. Nach unserer Wintererfahrung gibt es meist weniger Hochsaisondruck und mehr Raum für spontane Alltagsentscheidungen. Trotzdem kann ein beliebtes Restaurant voll sein, ein Parkplatz anderswo schwer zu finden und kein Strand wird als leer versprochen.", "El verano puede resultar anónimo y muy transitorio. En nuestra experiencia invernal suele haber menos presión de temporada alta y más margen para decisiones espontáneas. Aun así, un restaurante popular puede llenarse, aparcar en otro lugar puede ser difícil y nunca prometemos playas vacías.", "De zomer kan anoniem en zeer vluchtig aanvoelen. In onze winterervaring is er doorgaans minder hoogseizoendruk en meer ruimte voor spontane keuzes. Toch kan een populair restaurant vol zijn, parkeren elders lastig blijven en wordt geen strand als leeg beloofd.", "Sommaren kan kännas anonym och mycket tillfällig. Enligt vår vintererfarenhet är trycket från högsäsongen oftast lägre och det finns mer rum för spontana vardagsval. Ändå kan en populär restaurang vara full, parkering på annan plats svår och ingen strand lovas tom."),
        l("What changes most for us is familiarity. Seeing the same people again at a café, on a town walk or beside the Atlantic can make Tarifa feel more personal and connected, even when those encounters remain no more than a nod or a brief exchange.", "Für uns verändert sich vor allem die Vertrautheit. Dieselben Menschen wieder im Café, beim Weg durch den Ort oder am Atlantik zu sehen, kann Tarifa persönlicher und verbundener wirken lassen — selbst wenn es nur bei einem Nicken oder kurzen Austausch bleibt.", "Lo que más cambia para nosotros es la familiaridad. Volver a ver a las mismas personas en una cafetería, por el centro o junto al Atlántico puede hacer que Tarifa se sienta más personal y conectada, aunque el encuentro no pase de un saludo.", "Wat voor ons het meest verandert, is vertrouwdheid. Dezelfde mensen opnieuw zien in een café, tijdens een wandeling door de stad of langs de Atlantische Oceaan kan Tarifa persoonlijker en meer verbonden laten voelen, ook als het bij een knikje of kort gesprek blijft.", "Det som förändras mest för oss är igenkänningen. Att se samma människor igen på ett kafé, under en promenad i stan eller vid Atlanten kan få Tarifa att kännas mer personligt och sammanbundet, även om mötet stannar vid en nick eller kort växling."),
        l("AMARA’s La Marina setting keeps everyday shopping and the Old Town within the same practical part of Tarifa. Check the actual route for your mobility and pace rather than treating an estimated walking time as a promise.", "AMARAs Lage in La Marina verbindet alltägliche Einkäufe und Altstadt im selben praktischen Teil Tarifas. Prüft die konkrete Route für eure Mobilität und euer Tempo, statt eine geschätzte Gehzeit als Versprechen zu verstehen.", "La ubicación de AMARA en La Marina mantiene las compras cotidianas y el casco antiguo dentro de la misma parte práctica de Tarifa. Comprobad el recorrido adecuado para vuestra movilidad y ritmo, sin convertir un tiempo estimado en promesa.", "AMARA’s ligging in La Marina houdt dagelijkse boodschappen en de oude stad binnen hetzelfde praktische deel van Tarifa. Controleer de route voor jullie mobiliteit en tempo in plaats van een geschatte looptijd als belofte te zien.", "AMARAs läge i La Marina håller vardagsinköp och Gamla stan inom samma praktiska del av Tarifa. Kontrollera rutten för er rörlighet och takt i stället för att behandla en uppskattad gångtid som ett löfte.")
      ]
    },
    {
      id: "winter-day",
      eyebrow: l("06 · A day with room to change", "06 · Ein Tag mit Spielraum", "06 · Un día con margen", "06 · Een dag met speelruimte", "06 · En dag med spelrum"),
      title: l("A winter day in Tarifa", "Ein Wintertag in Tarifa", "Un día de invierno en Tarifa", "Een winterdag in Tarifa", "En vinterdag i Tarifa"),
      paragraphs: [
        l("Start with the forecast rather than a rigid itinerary. Breakfast at home can lead into a town walk or a few focused hours; the best outdoor window can then be kept for Los Lances, the western coast or a viewpoint.", "Beginnt mit der Vorhersage statt mit einem starren Ablauf. Auf das Frühstück zu Hause können ein Weg durch den Ort oder einige konzentrierte Stunden folgen; das beste Zeitfenster draußen bleibt dann für Los Lances, die Westküste oder einen Aussichtspunkt frei.", "Empezad por la previsión, no por un itinerario rígido. El desayuno en casa puede continuar con un paseo por el centro o unas horas de concentración; la mejor ventana exterior queda entonces para Los Lances, la costa occidental o un mirador.", "Begin met de weersverwachting in plaats van een strak schema. Een ontbijt thuis kan overgaan in een stadswandeling of enkele geconcentreerde uren; het beste buitenmoment blijft dan voor Los Lances, de westkust of een uitzichtpunt.", "Börja med prognosen i stället för ett fast schema. Frukost hemma kan följas av en promenad i stan eller några fokuserade timmar; det bästa fönstret utomhus kan sedan sparas till Los Lances, västkusten eller en utsiktsplats."),
        l("In summer the beach often carries the intensity of the day. In winter, Robert values the Atlantic coast differently: for space, movement, fresh air, waves, landscape and sunset. It can feel calm without ever being described as deserted.", "Im Sommer trägt der Strand oft die Intensität des Tages. Im Winter schätzt Robert die Atlantikküste anders: für Weite, Bewegung, frische Luft, Wellen, Landschaft und Sonnenuntergang. Sie kann ruhig wirken, ohne deshalb als verlassen beschrieben zu werden.", "En verano, la playa suele concentrar la intensidad del día. En invierno, Robert valora la costa atlántica de otra forma: por el espacio, el movimiento, el aire fresco, las olas, el paisaje y el atardecer. Puede transmitir calma sin describirla como desierta.", "In de zomer draagt het strand vaak de intensiteit van de dag. In de winter waardeert Robert de Atlantische kust anders: om ruimte, beweging, frisse lucht, golven, landschap en zonsondergang. De kust kan kalm voelen zonder verlaten te worden genoemd.", "På sommaren bär stranden ofta dagens intensitet. På vintern uppskattar Robert Atlantkusten på ett annat sätt: för utrymme, rörelse, frisk luft, vågor, landskap och solnedgång. Den kan kännas lugn utan att beskrivas som övergiven."),
        l("When the light goes, the day returns indoors. Groceries from across the road, a proper kitchen, comfortable living space and warmth matter more in winter because the evening at home is not a gap between activities; it is part of the stay.", "Wenn das Licht geht, führt der Tag nach drinnen. Einkäufe von gegenüber, eine richtige Küche, komfortabler Wohnraum und Wärme zählen im Winter mehr, denn der Abend zu Hause ist keine Lücke zwischen Aktivitäten, sondern Teil des Aufenthalts.", "Cuando termina la luz, el día vuelve al interior. Compras de enfrente, una cocina de verdad, espacio cómodo para estar y calor importan más en invierno: la noche en casa no es un hueco entre actividades, sino parte de la estancia.", "Wanneer het licht verdwijnt, keert de dag naar binnen. Boodschappen van de overkant, een echte keuken, comfortabele leefruimte en warmte tellen meer in de winter: de avond thuis is geen opening tussen activiteiten, maar onderdeel van het verblijf.", "När ljuset försvinner återvänder dagen inomhus. Inköp från andra sidan gatan, ett riktigt kök, bekvämt vardagsrum och värme betyder mer på vintern: kvällen hemma är inte en lucka mellan aktiviteter, utan en del av vistelsen.")
      ]
    },
    {
      id: "home-matters",
      eyebrow: l("07 · Comfort becomes essential", "07 · Komfort wird wesentlich", "07 · El confort se vuelve esencial", "07 · Comfort wordt essentieel", "07 · Komfort blir avgörande"),
      title: l("Why the home matters more in winter", "Warum das Zuhause im Winter wichtiger wird", "Por qué la casa importa más en invierno", "Waarom het huis in de winter belangrijker is", "Varför hemmet betyder mer på vintern"),
      paragraphs: [
        l("A summer stay can revolve around being outside. In winter, the quality of the home becomes part of the destination: somewhere to read, cook, work when necessary, dry clothes after a changing day and spend an evening without needing to go out.", "Ein Sommeraufenthalt kann fast vollständig draußen stattfinden. Im Winter wird die Qualität des Zuhauses Teil des Reiseziels: zum Lesen, Kochen, bei Bedarf Arbeiten, Trocknen von Kleidung nach wechselndem Wetter und für einen Abend, an dem ihr nicht ausgehen müsst.", "Una estancia de verano puede girar casi por completo alrededor del exterior. En invierno, la calidad de la vivienda forma parte del destino: leer, cocinar, trabajar si hace falta, secar la ropa tras un día cambiante o pasar una noche sin necesidad de salir.", "Een zomervakantie kan bijna volledig buiten plaatsvinden. In de winter wordt de kwaliteit van het huis onderdeel van de bestemming: lezen, koken, zo nodig werken, kleding laten drogen na wisselend weer en een avond doorbrengen zonder uit te hoeven.", "En sommarvistelse kan nästan helt kretsa kring utomhuslivet. På vintern blir hemmets kvalitet en del av destinationen: en plats att läsa, laga mat, arbeta vid behov, torka kläder efter skiftande väder och tillbringa en kväll utan att behöva gå ut."),
        l("AMARA’s current property records list Wi-Fi, heating, hot-and-cold air-conditioning, a wood-burning fireplace, a full kitchen and washing machine. Confirm any feature that is decisive for your stay when booking.", "Die aktuellen AMARA-Objektdaten nennen WLAN, Heizung, Klimaanlage zum Kühlen und Heizen, Holzkamin, vollständige Küche und Waschmaschine. Bestätigt bei der Buchung jedes Merkmal, das für euch entscheidend ist.", "AMARA Family & Surf tiene confirmados Wi-Fi, calefacción, aire acondicionado con frío y calor, chimenea de leña, cocina completa, lavadora y zonas de estar cómodas. Son prestaciones prácticas, no adjetivos decorativos.", "AMARA Family & Surf heeft bevestigde wifi, verwarming, airconditioning voor koelen en verwarmen, een houtgestookte open haard, volledige keuken, wasmachine en comfortabele leefruimtes. Dat zijn praktische kenmerken, geen sfeervolle bijvoeglijke naamwoorden.", "AMARAs aktuella objektdata anger wifi, värme, luftkonditionering för kyla och värme, vedeldad eldstad, fullständigt kök och tvättmaskin. Bekräfta varje avgörande funktion vid bokning."),
        l("Over several weeks, those basics create continuity. You can cook a normal meal, keep laundry moving and warm the house for the evening, making a mixed-weather day feel like part of real winter life rather than lost holiday time.", "Über mehrere Wochen schaffen diese Grundlagen Kontinuität. Ihr könnt normal kochen, Wäsche waschen und das Haus am Abend wärmen. So fühlt sich ein Tag mit gemischtem Wetter wie echtes Winterleben an und nicht wie verlorene Urlaubszeit.", "Durante varias semanas, esas bases crean continuidad. Podéis cocinar con normalidad, mantener la colada al día y calentar la casa para la noche. Así, una jornada de tiempo mixto forma parte de la vida de invierno en vez de sentirse como vacaciones perdidas.", "Over enkele weken zorgen die basisvoorzieningen voor continuïteit. Jullie kunnen normaal koken, de was bijhouden en het huis voor de avond verwarmen. Zo voelt gemengd weer als onderdeel van het winterleven en niet als verloren vakantietijd.", "Över flera veckor skapar grunderna kontinuitet. Ni kan laga vanlig mat, hålla tvätten igång och värma hemmet inför kvällen. Då blir en dag med blandat väder en del av vinterlivet i stället för förlorad semestertid.")
      ]
    },
    {
      id: "who-enjoys-winter",
      eyebrow: l("08 · Who this season suits", "08 · Für wen diese Jahreszeit passt", "08 · Para quién es esta estación", "08 · Voor wie dit seizoen werkt", "08 · Vem säsongen passar"),
      title: l("Who will enjoy Tarifa in winter", "Wer Tarifa im Winter genießen wird", "Quién disfrutará Tarifa en invierno", "Wie Tarifa in de winter zal waarderen", "Vem kommer att uppskatta Tarifa på vintern"),
      paragraphs: [
        l("Winter can suit couples, longer stays, guests taking a break from darker northern months, surf- or kite-oriented travellers and people who prefer calm town life to peak-season intensity. It rewards flexibility more than a checklist of guaranteed conditions.", "Der Winter kann zu Paaren, längeren Aufenthalten, einer Pause von dunkleren nördlichen Monaten, Surf- oder Kite-Reisenden und Menschen passen, die ruhiges Ortsleben der Hochsaisonintensität vorziehen. Er belohnt Flexibilität mehr als eine Liste garantierter Bedingungen.", "El invierno puede gustar a parejas, estancias largas, personas que descansan de los meses oscuros del norte, viajeros de surf o kite y quienes prefieren una vida local tranquila a la intensidad máxima. Recompensa la flexibilidad más que una lista de condiciones garantizadas.", "De winter kan aantrekkelijk zijn voor stellen, langere verblijven, gasten die ontsnappen aan donkere noordelijke maanden, surf- of kitereizigers en mensen die kalm stadsleven verkiezen boven hoogseizoenintensiteit. Flexibiliteit wordt meer beloond dan een lijst gegarandeerde omstandigheden.", "Vintern kan passa par, längre vistelser, gäster som tar paus från mörkare nordliga månader, surf- eller kiteresenärer och personer som föredrar lugnt stadsliv framför högsäsongens intensitet. Flexibilitet belönas mer än en lista med garanterade villkor."),
        l("For guests who need to work during part of a longer stay, Wi-Fi and a private home can make focused hours possible. Confirm that the workspace and connection suit your needs; we do not turn every winter stay into a workation story.", "Wenn ihr während eines längeren Aufenthalts teilweise arbeiten müsst, können WLAN und ein privates Zuhause konzentrierte Stunden ermöglichen. Bestätigt, ob Arbeitsplatz und Verbindung passen; nicht jeder Winteraufenthalt ist eine Workation.", "Para quienes necesiten trabajar durante parte de una estancia larga, el wifi y una casa privada pueden permitir horas de concentración. Confirmad si espacio y conexión responden a vuestras necesidades; no convertimos cada estancia en una historia de teletrabajo.", "Voor gasten die tijdens een langer verblijf deels moeten werken, kunnen wifi en een privéhuis geconcentreerde uren mogelijk maken. Bevestig of werkplek en verbinding passen; niet ieder winterverblijf is een workation.", "För gäster som behöver arbeta under en del av en längre vistelse kan wifi och ett privat hem möjliggöra fokuserade timmar. Bekräfta att arbetsplats och anslutning passar; varje vintervistelse är inte en workation."),
        l("Guests seeking the warmest sea, dense high-season energy, the broadest seasonal opening or a trip built almost entirely around beach heat may prefer summer. Winter asks you to value changing days, indoor comfort and a slower relationship with the town.", "Wenn ihr das wärmste Meer, dichte Hochsaisonenergie, die breiteste saisonale Öffnung oder eine Reise fast nur für Strandhitze sucht, ist der Sommer wahrscheinlich passender. Im Winter müsst ihr wechselnde Tage, Komfort drinnen und eine langsamere Beziehung zum Ort schätzen.", "Quienes busquen el mar más cálido, mucha energía de temporada alta, la máxima oferta estacional o un viaje casi íntegramente de calor y playa quizá prefieran el verano. El invierno pide valorar los días cambiantes, el confort interior y una relación más lenta con Tarifa.", "Wie de warmste zee, veel hoogseizoenenergie, het breedste seizoensaanbod of vooral strandwarmte zoekt, kiest mogelijk beter de zomer. De winter vraagt waardering voor veranderlijke dagen, comfort binnen en een langzamere relatie met de stad.", "Den som söker varmast hav, tät högsäsongsenergi, bredast säsongsutbud eller en resa nästan helt byggd kring strandvärme kan föredra sommaren. Vintern kräver att ni uppskattar växlande dagar, komfort inomhus och en långsammare relation till staden.")
      ]
    },
    {
      id: "amara-la-marina",
      eyebrow: l("09 · Your winter base", "09 · Eure Winterbasis", "09 · Vuestra base de invierno", "09 · Jullie winterbasis", "09 · Er vinterbas"),
      title: l("Winter at AMARA in La Marina", "Winter bei AMARA in La Marina", "El invierno en AMARA, en La Marina", "Winter bij AMARA in La Marina", "Vinter på AMARA i La Marina"),
      paragraphs: [
        l("AMARA Family & Surf is in La Marina, between everyday Tarifa and the wider Atlantic coast. Shopping and the Old Town are part of the local routine, but current businesses and the route that suits you should be checked for your dates.", "AMARA Family & Surf liegt in La Marina zwischen dem alltäglichen Tarifa und der weiteren Atlantikküste. Einkaufen und Altstadt gehören zum lokalen Alltag; aktuelle Betriebe und die passende Route prüft ihr für eure Reisedaten.", "AMARA Family & Surf está en La Marina, entre el Tarifa cotidiano y la costa atlántica. Compras y casco antiguo forman parte de la rutina local, pero conviene comprobar negocios y recorridos actuales para las fechas concretas.", "AMARA Family & Surf ligt in La Marina tussen het dagelijkse Tarifa en de Atlantische kust. Winkels en de oude stad horen bij de lokale routine; controleer actuele zaken en een passende route voor jullie data.", "AMARA Family & Surf ligger i La Marina mellan vardagens Tarifa och Atlantkusten. Inköp och Gamla stan hör till den lokala rutinen; kontrollera aktuella verksamheter och en lämplig rutt för era datum."),
        l("A reserved underground space settles where your own car sleeps. For beaches and the town centre in season, allow a little extra time. Inside, heating, hot-and-cold air-conditioning, the fireplace, kitchen, washing machine, Wi-Fi and living space support the routines of a stay measured in weeks.", "Ein reservierter Tiefgaragenplatz klärt, wo euer eigenes Auto zu Hause steht. Für Strände und die Innenstadt plant in der Saison etwas mehr Zeit ein. Drinnen unterstützen Heizung, Klimaanlage, Kamin, Küche, Waschmaschine, WLAN und Wohnraum Routinen über mehrere Wochen.", "La plaza reservada en el garaje subterráneo resuelve dónde dejar vuestro coche en casa. Para playas y centro en temporada, contad con algo más de tiempo. Dentro, calefacción, aire acondicionado, chimenea, cocina, lavadora, Wi-Fi y espacio de estar respaldan rutinas de varias semanas.", "Een gereserveerde ondergrondse plek lost op waar jullie eigen auto thuis staat. Reken voor stranden en het centrum in het seizoen op wat extra tijd. Binnen ondersteunen verwarming, airconditioning, open haard, keuken, wasmachine, wifi en leefruimte routines van meerdere weken.", "En reserverad underjordisk plats löser var den egna bilen står hemma. Räkna med lite extra tid för stränder och centrum under säsong. Inomhus stödjer värme, luftkonditionering, eldstad, kök, tvättmaskin, wifi och sällskapsytor rutiner över flera veckor."),
        l("That is the winter proposition: a milder southern season outside, a comfortable real home inside and normal Tarifa life close by. Winter is not the lesser version of Tarifa. It is a different version — and for some guests, perhaps the more rewarding one.", "Das ist die Winteridee: draußen ein milderer südlicher Winter, drinnen ein komfortables echtes Zuhause und das normale Tarifa ganz nah. Der Winter ist nicht die kleinere Version von Tarifa. Er ist eine andere — und für manche Gäste vielleicht die lohnendere.", "Esa es la propuesta invernal: una estación meridional más suave fuera, una casa real y cómoda dentro y la vida normal de Tarifa cerca. El invierno no es una versión menor de Tarifa. Es una versión distinta y, para algunos huéspedes, quizá la más gratificante.", "Dat is het winterverhaal: buiten een milder zuidelijk seizoen, binnen een comfortabel echt huis en het normale leven van Tarifa dichtbij. De winter is geen mindere versie van Tarifa. Het is een andere — en voor sommige gasten misschien de meest waardevolle.", "Det är vinterns erbjudande: en mildare sydlig säsong utanför, ett bekvämt verkligt hem innanför och Tarifas vanliga liv nära. Vintern är inte en mindre version av Tarifa. Den är en annan — och för vissa gäster kanske den mer givande.")
      ]
    }
  ],
  related: {
    eyebrow: l("Continue with the practical detail", "Weiter zu den praktischen Details", "Continuad con el detalle práctico", "Ga verder met de praktische details", "Fortsätt med praktiska detaljer"),
    title: l("Where to go from here", "Plant den Winteraufenthalt ohne denselben Guide zu wiederholen", "Planificad el invierno sin repetir la misma guía", "Plan het winterverblijf zonder dezelfde gids te herhalen", "Planera vintervistelsen utan att upprepa samma guide"),
    links: [
      {
        token: "tarifa_weather" as LinkToken,
        label: l("Weather & Seasons", "Wetter & Jahreszeiten", "Tiempo y estaciones", "Weer & seizoenen", "Väder & årstider"),
        text: l("Official climate figures, and how Levante and Poniente shape the season.", "Offizielle Klimadaten, Levante, Poniente und die Grenzen jeder saisonalen Erwartung.", "Datos climáticos oficiales, Levante, Poniente y límites de cualquier expectativa estacional.", "Officiële klimaatgegevens, Levante, Poniente en de grenzen van seizoensverwachtingen.", "Officiella klimatdata, Levante, Poniente och gränserna för säsongsförväntningar.")
      },
      {
        token: "tarifa_daily_life" as LinkToken,
        label: l("Daily Life & Services", "Alltag & Versorgung", "Vida diaria y servicios", "Dagelijks leven & voorzieningen", "Vardag & service"),
        text: l("Groceries, healthcare, normal errands and practical planning for a longer stay.", "Einkaufen, medizinische Versorgung, normale Erledigungen und alle Coworking-Details.", "Compras, atención sanitaria, recados y planificación práctica.", "Boodschappen, zorg, normale taken en praktische planning.", "Inköp, vård, vanliga ärenden och praktisk planering.")
      },
      {
        token: "tarifa_beaches_authority" as LinkToken,
        label: l("Beaches & coast", "Strände & Küste", "Playas y costa", "Stranden & kust", "Stränder & kust"),
        text: l("Choose between the urban shore and the wider Atlantic coast for the day you have.", "Wählt für den jeweiligen Tag zwischen Stadtküste und weiter Atlantikküste.", "Elegid entre la costa urbana y el Atlántico occidental para el día concreto.", "Kies voor de concrete dag tussen stadskust en de bredere Atlantische kust.", "Välj mellan stadskusten och den vidare Atlantkusten för den konkreta dagen.")
      },
      {
        token: "tarifa_wind_kitesurfing_authority" as LinkToken,
        label: l("Wind & watersports", "Wind & Wassersport", "Viento y deportes acuáticos", "Wind & watersport", "Vind & vattensport"),
        text: l("Technical wind, safety and water-sports planning belongs in the specialist guide.", "Technische Wind-, Sicherheits- und Wassersportplanung steht im Spezialguide.", "La planificación técnica de viento, seguridad y agua pertenece a la guía especializada.", "Technische wind-, veiligheids- en watersportplanning staat in de specialistische gids.", "Teknisk vind-, säkerhets- och vattensportplanering finns i specialistguiden.")
      },
      {
        token: "tarifa" as LinkToken,
        label: l("AMARA Family & Surf", "AMARA Family & Surf", "AMARA Family & Surf", "AMARA Family & Surf", "AMARA Family & Surf"),
        text: l("See the home when its winter role and practical setting are clear.", "Seht euch das Zuhause an, wenn seine Winterrolle und Lage klar sind.", "Ved la casa cuando su función invernal y su ubicación hayan quedado claras.", "Bekijk het huis wanneer zijn winterrol en praktische ligging duidelijk zijn.", "Se hemmet när dess vinterroll och praktiska läge är tydliga.")
      }
    ]
  },
  sources: {
    eyebrow: l("Evidence and perspective", "Belege und Perspektive", "Evidencia y perspectiva", "Onderbouwing en perspectief", "Underlag och perspektiv"),
    title: l("Official facts, clearly separated from host experience", "Offizielle Fakten, klar getrennt von Gastgebererfahrung", "Datos oficiales separados de la experiencia del anfitrión", "Officiële feiten, duidelijk gescheiden van hostervaring", "Officiella fakta tydligt skilda från värderfarenhet"),
    intro: l("Climate, wind and viewpoint facts use current official sources. The quieter winter feeling is explicitly Robert’s host perspective; property details come from AMARA’s current records.", "Klima-, Wind- und Aussichtsfakten nutzen aktuelle offizielle Quellen. Das ruhigere Wintergefühl ist ausdrücklich Roberts Perspektive; Objektdetails stammen aus den aktuellen AMARA-Daten.", "Los datos de clima, viento y miradores usan fuentes oficiales. La sensación de un invierno tranquilo es la perspectiva expresa de Robert; los detalles de la casa proceden de los registros actuales de AMARA.", "Klimaat-, wind- en uitzichtfeiten gebruiken officiële bronnen. Het rustigere wintergevoel is Roberts expliciete perspectief; huisdetails komen uit actuele AMARA-records.", "Fakta om klimat, vind och utsikt använder officiella källor. Den lugnare vinterkänslan är Roberts uttryckliga perspektiv; hemuppgifter kommer från aktuella AMARA-register."),
    checked: l("Sources reviewed 21 August 2026", "Quellen geprüft am 21. August 2026", "Fuentes revisadas el 21 de agosto de 2026", "Bronnen gecontroleerd op 21 augustus 2026", "Källor granskade den 21 augusti 2026"),
    links: [
      {
        label: l("AEMET · Tarifa climate normals", "AEMET · Klimanormalwerte Tarifa", "AEMET · valores normales de Tarifa", "AEMET · klimaatnormalen Tarifa", "AEMET · klimatnormaler för Tarifa"),
        text: l("Official monthly temperature, rainfall and rain-day averages for station 6001.", "Offizielle Monatswerte für Temperatur, Niederschlag und Regentage an Station 6001.", "Medias oficiales mensuales de temperatura, precipitación y días de lluvia de la estación 6001.", "Officiële maandwaarden voor temperatuur, neerslag en regendagen van station 6001.", "Officiella månadsvärden för temperatur, nederbörd och regndagar vid station 6001."),
        href: sourceHrefs.tarifaNormals
      },
      {
        label: l("Turismo de Tarifa · parks and walking routes", "Turismo de Tarifa · Naturparks und Wege", "Turismo de Tarifa · parques y senderos", "Turismo de Tarifa · natuurparken en routes", "Turismo de Tarifa · naturparker och leder"),
        text: l("Official viewpoint context, including Africa and the Atlas Mountains on clear days.", "Offizielle Aussichtsinformationen, einschließlich Afrika und Atlas an klaren Tagen.", "Información oficial de vistas, incluida África y el Atlas en días claros.", "Officiële uitzichtinformatie, inclusief Afrika en de Atlas op heldere dagen.", "Officiell utsiktsinformation, inklusive Afrika och Atlas på klara dagar."),
        href: sourceHrefs.tarifaViewpoints
      },
      {
        label: l("Junta de Andalucía · wind in the Strait", "Junta de Andalucía · Wind an der Meerenge", "Junta de Andalucía · viento en el Estrecho", "Junta de Andalucía · wind in de Straat", "Junta de Andalucía · vind i sundet"),
        text: l("Official qualitative context for Levante and Poniente.", "Offizieller qualitativer Kontext zu Levante und Poniente.", "Contexto cualitativo oficial sobre Levante y Poniente.", "Officiële kwalitatieve context voor Levante en Poniente.", "Officiell kvalitativ kontext för Levante och Poniente."),
        href: sourceHrefs.tarifaWind
      },
      {
        label: l("European Travel Commission · winter travel sentiment", "European Travel Commission · Winterreisen", "European Travel Commission · viajes de invierno", "European Travel Commission · winterreizen", "European Travel Commission · vinterresor"),
        text: l("European travel intentions and the boundary between survey plans and bookings.", "Europäische Reiseabsichten und die Grenze zwischen Plan und Buchung.", "Intenciones europeas y límite entre planes y reservas.", "Europese intenties en de grens tussen plan en boeking.", "Europeiska avsikter och gränsen mellan plan och bokning."),
        href: sourceHrefs.travelIntent
      }
    ]
  },
  closing: {
    eyebrow: l("Stay long enough to feel the difference", "Bleibt lange genug, um den Unterschied zu spüren", "Quedaos el tiempo suficiente para sentir la diferencia", "Blijf lang genoeg om het verschil te voelen", "Stanna länge nog för att känna skillnaden"),
    title: l("Let winter be its own version of Tarifa", "Lasst den Winter seine eigene Version von Tarifa sein", "Dejad que el invierno sea su propia versión de Tarifa", "Laat de winter zijn eigen Tarifa zijn", "Låt vintern vara sin egen version av Tarifa"),
    body: l("Choose it for usable light, Atlantic space, a calmer town rhythm and a home that remains comfortable when the weather changes. Start with Tarifa’s location or continue to AMARA Family & Surf.", "Wählt ihn für nutzbares Licht, Weite am Atlantik, einen ruhigeren Ortsrhythmus und ein Zuhause, das auch bei Wetterwechsel komfortabel bleibt. Beginnt mit Tarifas Lage oder geht weiter zu AMARA Family & Surf.", "Elegidlo por la luz aprovechable, el espacio atlántico, un ritmo más tranquilo y una casa cómoda cuando cambia el tiempo. Empezad por la ubicación de Tarifa o continuad hasta AMARA Family & Surf.", "Kies voor bruikbaar licht, Atlantische ruimte, een rustiger stadsritme en een huis dat comfortabel blijft wanneer het weer verandert. Begin bij de ligging van Tarifa of ga verder naar AMARA Family & Surf.", "Välj den för användbart ljus, Atlantens utrymme, en lugnare stadsrytm och ett hem som förblir bekvämt när vädret ändras. Börja med Tarifas läge eller fortsätt till AMARA Family & Surf."),
    locationLabel: l("Explore Tarifa’s location", "Tarifas Lage entdecken", "Descubrir la ubicación de Tarifa", "Ontdek de ligging van Tarifa", "Utforska Tarifas läge"),
    propertyLabel: l("View AMARA Family & Surf", "AMARA Family & Surf ansehen", "Ver AMARA Family & Surf", "Bekijk AMARA Family & Surf", "Visa AMARA Family & Surf")
  }
};
