import type { LocalizedText, LocalizedTextSection } from '../types/content';
import type { AmaraAuthoringSeo } from '../types/seo';
import type { LinkToken } from '../lib/linkResolver';

const l = (en: string, de: string, es: string, nl: string, sv: string): LocalizedText => ({ en, de, es, nl, sv });

const title = l(
  'Kitesurf spots in Tarifa: Los Lances, Valdevaqueros & Balneario',
  'Kitesurf-Spots in Tarifa: Los Lances, Valdevaqueros & Balneario',
  'Spots de kitesurf en Tarifa: Los Lances, Valdevaqueros y Balneario',
  'Kitesurfspots in Tarifa: Los Lances, Valdevaqueros & Balneario',
  'Kitesurfspots i Tarifa: Los Lances, Valdevaqueros & Balneario'
);
const description = l(
  'Los Lances or Valdevaqueros? We explain Tarifa’s kite spots by wind, season and riding level, with Robert’s experience and official beach rules.',
  'Los Lances oder Valdevaqueros? Wir ordnen Tarifas Kitespots nach Wind, Saison und Niveau ein – mit Roberts Erfahrung und offiziellen Strandregeln.',
  '¿Los Lances o Valdevaqueros? Os explicamos los spots según viento, temporada y nivel, con la experiencia de Robert y las normas oficiales de playa.',
  'Los Lances of Valdevaqueros? We bespreken de spots naar wind, seizoen en niveau, met Roberts ervaring en de officiële strandregels.',
  'Los Lances eller Valdevaqueros? Vi går igenom spots efter vind, säsong och nivå, med Roberts erfarenheter och officiella strandregler.'
);

export const tarifaKitesurfSpotsSeo: AmaraAuthoringSeo = {
  version: '2026-09-03-tarifa-kitesurf-spots-v1.0',
  pageType: 'B',
  entityKey: 'amara-brand',
  ogImage: '/images/amara-tarifa/amara-tarifa-apartment23.webp',
  article: {
    datePublished: '2026-09-03', dateModified: '2026-09-03',
    authorName: 'Robert Sebastian Böhmer', authorType: 'Person', authorSlug: 'staying-with-us'
  },
  languages: {
    en: { title: title.en, description: description.en, robots: 'index, follow', canonical: 'auto' },
    de: { title: title.de, description: description.de, robots: 'index, follow', canonical: 'auto' },
    es: { title: title.es, description: description.es, robots: 'index, follow', canonical: 'auto' },
    nl: { title: title.nl, description: description.nl, robots: 'index, follow', canonical: 'auto' },
    sv: { title: title.sv, description: description.sv, robots: 'index, follow', canonical: 'auto' }
  }
};

interface SpotSection extends LocalizedTextSection {
  observation?: LocalizedText;
  link?: { token: LinkToken; text: LocalizedText; label: LocalizedText };
}

const sections: SpotSection[] = [
  {
    id: 'los-lances',
    title: l('Los Lances: kiting right in front of Tarifa', 'Los Lances: Das Kitesurfen direkt vor Tarifa', 'Los Lances: navegar frente a Tarifa', 'Los Lances: kitesurfen vlak voor Tarifa', 'Los Lances: kitesurfing precis framför Tarifa'),
    paragraphs: {
      en: ['With Poniente, we look first at Los Lances. This open Atlantic coast can have wind waves, chop and shorebreak; the water at the launch matters as much as the wind direction. A beach that looks spacious still needs a permitted, usable launch area.', 'Sur is the stretch closer to town; Norte continues farther along the coast and has separately marked bathing, school and watersport areas. Independent riders need the zone designated for them. During the bathing season, a familiar town-side launch is no assurance of permission. Levante can blow offshore or cross-offshore here, making Los Lances a poor default for that direction.'],
      de: ['Bei Poniente schauen wir zuerst auf Los Lances. An dieser offenen Atlantikküste können Windwelle, Chop und Shorebreak entstehen; das Wasser am Einstieg zählt genauso wie die Windrichtung. Auch an einem weit wirkenden Strand braucht ihr einen erlaubten, tatsächlich nutzbaren Startbereich.', 'Sur ist der stadtnähere Abschnitt, Norte setzt sich weiter entlang der Küste fort und hat getrennt ausgewiesene Bade-, Schul- und Wassersportbereiche. Für selbstständiges Fahren braucht ihr die dafür vorgesehene Zone. Während der Badesaison bedeutet ein vertrauter Einstieg vor der Stadt noch keine Freigabe. Levante kann hier ablandig bis schräg ablandig wirken; Los Lances ist dann keine normale Plan-A-Empfehlung.'],
      es: ['Con poniente, miramos primero Los Lances. En esta costa atlántica abierta puede haber ola de viento, mar picado y rompiente en la orilla; el estado del agua en la entrada importa tanto como la dirección del viento. Aunque la playa parezca amplia, necesitáis una zona de salida autorizada y utilizable.', 'Sur es el tramo más cercano a la ciudad; Norte continúa por la costa y cuenta con zonas diferenciadas de baño, escuela y deportes acuáticos. Para navegar por vuestra cuenta necesitáis el sector correspondiente. En temporada de baño, conocer una entrada junto al pueblo no significa que esté permitida. El levante puede soplar de tierra o cruzado de tierra, por lo que Los Lances deja de ser nuestra primera orientación con ese viento.'],
      nl: ['Bij poniente kijken we eerst naar Los Lances. Aan deze open Atlantische kust kunnen windgolven, chop en branding aan de waterlijn ontstaan. Het water bij de instap telt net zo zwaar als de windrichting. Ook op een breed strand hebben jullie een toegestane, bruikbare startplek nodig.', 'Sur ligt dichter bij de stad; Norte loopt verder langs de kust en heeft afzonderlijke zwem-, les- en watersportzones. Zelfstandige kiters hebben de daarvoor aangewezen zone nodig. In het badseizoen betekent een vertrouwde instap bij de stad niet automatisch dat starten mag. Levante kan hier aflandig tot schuin aflandig staan; Los Lances is bij die richting geen vanzelfsprekend eerste plan.'],
      sv: ['Vid poniente tittar vi först på Los Lances. Längs den öppna Atlantkusten kan vindvågor, krabb sjö och strandbrytning uppstå. Vattnet vid starten spelar lika stor roll som vindriktningen. Även på en bred strand behöver ni en tillåten startplats som går att använda.', 'Sur ligger närmare staden; Norte fortsätter längs kusten med separata bad-, skol- och vattensportzoner. Självständiga åkare behöver den zon som är avsedd för dem. Under badsäsongen innebär en välbekant startplats vid staden inte att starten är tillåten. Levante kan blåsa från land eller snett från land här; Los Lances är då inget självklart förstaval.']
    },
    observation: l('Outside the summer months, Los Lances is my usual Tarifa spot. When Poniente arrives, I take my kit and walk towards the beach. A session right in front of Tarifa, with kiters coming down from town, is what gives me that Tarifa feeling.', 'Außerhalb der Sommermonate ist Los Lances mein typischer Tarifa-Spot. Wenn Poniente kommt, nehme ich mein Material und gehe zu Fuß Richtung Strand. Die Session direkt vor Tarifa und die Kiter, die aus der Stadt dazukommen, gehören für mich zum eigentlichen Tarifa-Gefühl.', 'Fuera de los meses de verano, Los Lances es mi spot habitual en Tarifa. Cuando entra poniente, cojo el material y voy andando hacia la playa. Navegar frente al pueblo, con otros kiters que bajan desde la ciudad, es lo que para mí hace especial a Tarifa.', 'Buiten de zomermaanden is Los Lances mijn gebruikelijke spot in Tarifa. Als de poniente komt, pak ik mijn materiaal en loop naar het strand. Een sessie vlak voor Tarifa, met kiters die vanuit de stad aansluiten, hoort voor mij bij het echte Tarifa-gevoel.', 'Utanför sommarmånaderna är Los Lances min vanliga spot i Tarifa. När poniente kommer tar jag utrustningen och går mot stranden. Ett pass precis framför Tarifa, med kitare som kommer ner från staden, är själva Tarifa-känslan för mig.'),
    link: {
      token: 'tarifa_kitesurf_wind_spots',
      text: l('An offshore wind changes the consequences of drifting away from this open beach. Before rigging, the distinction between Levante and Poniente matters:', 'Ablandiger Wind verändert an diesem offenen Strand die Folgen einer Abdrift. Vor dem Aufbau zählt deshalb der Unterschied zwischen Levante und Poniente:', 'El viento de tierra cambia las consecuencias de alejarse de esta costa abierta. Antes de montar, conviene entender la diferencia entre levante y poniente:', 'Aflandige wind verandert hier de gevolgen van afdrijven. Voor het optuigen is daarom het verschil tussen levante en poniente van belang:', 'Frånlandsvind förändrar följderna av att driva bort från den öppna stranden. Före riggningen är därför skillnaden mellan levante och poniente viktig:'),
      label: l('wind directions and current conditions', 'Windrichtungen und aktuelle Bedingungen', 'direcciones del viento y condiciones actuales', 'windrichtingen en actuele omstandigheden', 'vindriktningar och aktuella förhållanden')
    }
  },
  {
    id: 'rio-jara',
    title: l('Río Jara and the lagoon: a protected boundary', 'Río Jara und die Lagune: kein Spielraum für Interpretationen', 'Río Jara y la laguna: un límite que respetar', 'Río Jara en de lagune: een duidelijke grens', 'Río Jara och lagunen: en tydlig gräns'),
    paragraphs: {
      en: ['The Los Lances lagoon at Río Jara is protected natural habitat. Kitesurfing and all other watersports are prohibited in the lagoon. We therefore treat Río Jara as a protected boundary within the Los Lances area, not as a separate kite spot. Respect protected areas, buoys, signs and designated channels; during the bathing season, check the current zoning especially carefully.'],
      de: ['Die Los-Lances-Lagune am Río Jara ist geschützter Naturraum. Kitesurfen und jeder andere Wassersport sind in der Lagune verboten. Río Jara behandeln wir deshalb als Schutzgrenze innerhalb des Los-Lances-Gebiets, nicht als eigenständigen Kitespot. Respektiert Schutzbereiche, Bojen, Schilder und ausgewiesene Kanäle; während der Badesaison ist die Orientierung an der aktuellen Zonierung besonders wichtig.'],
      es: ['La laguna de Los Lances, junto al Río Jara, es un espacio natural protegido. En ella están prohibidos el kitesurf y cualquier otro deporte náutico. Por eso tratamos Río Jara como un límite de protección dentro de Los Lances, no como un spot independiente. Respetad las áreas protegidas, las boyas, las señales y los canales señalizados; durante la temporada de baño, comprobad la zonificación con especial atención.'],
      nl: ['De lagune van Los Lances bij Río Jara is beschermd natuurgebied. Kitesurfen en alle andere watersporten zijn er verboden. Río Jara behandelen we daarom als een beschermde grens binnen Los Lances, niet als een zelfstandige kitespot. Respecteer beschermde zones, boeien, borden en aangewezen doorgangen; let tijdens het badseizoen extra goed op de actuele zonering.'],
      sv: ['Los Lances-lagunen vid Río Jara är skyddad natur. Kitesurfing och all annan vattensport är förbjuden i lagunen. Vi behandlar därför Río Jara som en skyddsgräns inom Los Lances-området, inte som en egen kitespot. Respektera skyddsområden, bojar, skyltar och anvisade passager; under badsäsongen behöver ni läsa den aktuella zonindelningen särskilt noga.']
    }
  },
  {
    id: 'valdevaqueros',
    title: l('Valdevaqueros: the bay option for Levante', 'Valdevaqueros: Die Levante-Option in der Bucht', 'Valdevaqueros: la opción de la bahía con levante', 'Valdevaqueros: de baai bij levante', 'Valdevaqueros: bukten vid levante'),
    paragraphs: {
      en: ['With a suitable Levante angle, the curve of Valdevaqueros bay can leave a stretch of coast downwind of a rider. That can offer a more favourable coastal geometry than open Los Lances. It is a conditional advantage, not a safety guarantee: the exact launch point, wind angle, strength, gusts and your ability still determine whether a session is appropriate.', 'Punta Paloma belongs to the same decision, as the northern part of the bay. The curved shoreline changes the wind’s angle to the beach; the designated kite, windsurf and bathing areas still apply. Outside high summer, Valdevaqueros can be a suitable alternative when the conditions and permitted zone fit.'],
      de: ['Bei passendem Levante-Winkel kann durch die Krümmung der Bucht von Valdevaqueros ein Küstenabschnitt in eurer Abdriftrichtung liegen. Das kann gegenüber dem offenen Los Lances eine günstigere Downwind-Küstengeometrie bieten. Dieser bedingte Vorteil ist keine Sicherheitsgarantie: Der genaue Startpunkt, Windwinkel, Stärke, Böigkeit und euer Können entscheiden weiterhin über die Eignung.', 'Punta Paloma gehört als nördlicher Buchtbereich zu derselben Entscheidung. Mit der gekrümmten Uferlinie ändert sich der Windwinkel zum Strand; die ausgewiesenen Kite-, Windsurf- und Badebereiche gelten weiterhin. Außerhalb des Hochsommers kann Valdevaqueros eine passende Alternative sein, wenn Bedingungen und erlaubte Zone zusammenpassen.'],
      es: ['Con un ángulo de levante adecuado, la curva de la bahía de Valdevaqueros puede dejar un tramo de costa a sotavento de quien navega. Esa geometría puede resultar más favorable que la costa abierta de Los Lances. Es una ventaja condicionada, no una garantía de seguridad: siguen contando el punto exacto de salida, el ángulo, la fuerza, las rachas y vuestro nivel.', 'Punta Paloma forma parte de la misma decisión, como sector norte de la bahía. La curva de la orilla cambia el ángulo del viento respecto a la playa; siguen vigentes las zonas señalizadas de kite, windsurf y baño. Fuera del pleno verano, Valdevaqueros puede ser una alternativa adecuada si las condiciones y la zona autorizada encajan.'],
      nl: ['Bij een passende levantehoek kan door de kromming van de baai van Valdevaqueros nog een stuk kust benedenwinds van een kiter liggen. Dat kan gunstiger zijn dan de open kust van Los Lances. Dit voordeel geldt onder voorwaarden en biedt geen veiligheidsgarantie: de precieze startplek, windhoek, kracht, vlagen en jullie niveau blijven bepalend.', 'Punta Paloma hoort als noordelijk deel van de baai bij dezelfde afweging. Door de gebogen kust verandert de hoek van de wind ten opzichte van het strand; de aangewezen kite-, windsurf- en zwemzones blijven gelden. Buiten het hoogseizoen kan Valdevaqueros een passende optie zijn wanneer de omstandigheden en de toegestane zone aansluiten.'],
      sv: ['Vid en lämplig levantevinkel kan Valdevaqueros buktform innebära att en kuststräcka ligger i lä om åkaren. Det kan ge en gynnsammare kustgeometri än vid öppna Los Lances. Fördelen är villkorad och ingen säkerhetsgaranti: exakt startplats, vindvinkel, styrka, byighet och er förmåga avgör fortfarande om förhållandena passar.', 'Punta Paloma ingår i samma bedömning som buktens norra del. Den böjda strandlinjen förändrar vindens vinkel mot stranden; de markerade kite-, vindsurf- och badzonerna gäller fortfarande. Utanför högsommaren kan Valdevaqueros vara ett lämpligt alternativ när förhållandena och den tillåtna zonen passar.']
    },
    observation: l('In July and August I personally avoid Valdevaqueros when I have a choice. Between bathers, schools, kiters and separate zones, I find it can become very crowded and hard to read. That is my own preference, rather than a rule for everyone who rides there.', 'Im Juli und August fahre ich persönlich nicht nach Valdevaqueros, wenn ich die Wahl habe. Mit Badegästen, Schulen, Kitern und getrennten Zonen kann es mir dort sehr voll und unübersichtlich werden. Das ist meine persönliche Vorliebe, keine Regel für alle, die dort fahren.', 'En julio y agosto, personalmente evito Valdevaqueros cuando puedo elegir. Entre bañistas, escuelas, kiters y zonas separadas, puede resultarme muy lleno y difícil de interpretar. Es mi preferencia, no una regla para quienes navegan allí.', 'In juli en augustus ga ik persoonlijk niet naar Valdevaqueros als ik kan kiezen. Door badgasten, scholen, kiters en gescheiden zones kan het er voor mij erg druk en onoverzichtelijk worden. Dat is mijn voorkeur, geen regel voor iedereen die er vaart.', 'I juli och augusti undviker jag personligen Valdevaqueros när jag kan välja. Med badgäster, skolor, kitare och separata zoner kan det bli mycket trångt och svåröverskådligt för mig. Det är min personliga preferens, ingen regel för alla som åker där.')
  },
  {
    id: 'balneario',
    title: l('Balneario: watching Big Air, or riding at specialist level', 'Balneario: Big Air zum Zuschauen – oder für sehr erfahrene Fahrer', 'Balneario: ver Big Air o navegar con nivel de especialista', 'Balneario: Big Air kijken, of varen op specialistisch niveau', 'Balneario: se Big Air eller åka på specialistnivå'),
    paragraphs: {
      en: ['We place Balneario in the specialist category for Big Air and riders with extensive experience. For an ordinary freeride session, the main comparison remains Los Lances and Valdevaqueros. The following is Robert’s personal assessment as a passionate kitesurfer, not an official access or safety rule.'],
      de: ['Balneario ordnen wir als Spezialspot für Big Air und sehr erfahrene Fahrer ein. Für eine gewöhnliche Freeride-Session bleibt die Hauptentscheidung zwischen Los Lances und Valdevaqueros. Die folgende persönliche Einordnung stammt von Robert als passioniertem Kitesurfer; sie ist keine amtliche Zutritts- oder Sicherheitsregel.'],
      es: ['Situamos Balneario entre los spots especializados de Big Air y de riders con mucha experiencia. Para una sesión habitual de freeride, la comparación principal sigue siendo Los Lances o Valdevaqueros. La valoración que sigue es personal, de Robert como apasionado del kitesurf; no es una norma oficial de acceso ni de seguridad.'],
      nl: ['Balneario plaatsen we bij de specialistische spots voor Big Air en zeer ervaren kiters. Voor een gewone freeridesessie blijft de belangrijkste vergelijking Los Lances of Valdevaqueros. Hieronder geeft Robert zijn persoonlijke oordeel als gepassioneerd kitesurfer; het is geen officiële toegangs- of veiligheidsregel.'],
      sv: ['Vi räknar Balneario som en specialistspot för Big Air och mycket erfarna åkare. För ett vanligt freeridepass är huvudfrågan fortfarande Los Lances eller Valdevaqueros. Följande är Roberts personliga bedömning som passionerad kitesurfare, inte en officiell tillträdes- eller säkerhetsregel.']
    },
    observation: l('Unless you are specifically training to land a Double Kite Loop with control and consistency, Balneario is an interesting spot for you to watch — but not to ride.', 'Wenn du nicht gerade gezielt daran trainierst, einen Double Kite Loop kontrolliert und zuverlässig zu landen, ist Balneario für dich ein interessanter Spot zum Zuschauen – aber nicht zum Fahren.', 'Si no estáis entrenando específicamente para aterrizar un Double Kite Loop con control y de forma consistente, Balneario es un spot interesante para verlo desde fuera, pero no para navegar.', 'Tenzij jullie gericht trainen om een Double Kite Loop beheerst en consequent te landen, is Balneario een interessante spot om te kijken, maar niet om zelf te varen.', 'Om ni inte tränar målmedvetet på att landa en Double Kite Loop kontrollerat och tillförlitligt är Balneario en intressant spot att titta på, men inte att åka på.'),
    link: {
      token: 'tarifa_kitesurf_wind_spots',
      text: l('Specialist ability still needs suitable conditions. Our existing wind and safety guidance explains why gusty offshore wind changes the consequences of a session:', 'Auch auf Spezialniveau müssen die Bedingungen passen. Unsere bestehenden Wind- und Sicherheitshinweise erklären, weshalb böiger ablandiger Wind die Folgen einer Session verändert:', 'Incluso con nivel de especialista, las condiciones deben acompañar. Nuestros consejos de viento y seguridad explican por qué el viento racheado de tierra cambia las consecuencias de una sesión:', 'Ook op specialistisch niveau moeten de omstandigheden passen. Onze bestaande wind- en veiligheidsinformatie legt uit waarom vlagerige aflandige wind de gevolgen van een sessie verandert:', 'Även på specialistnivå måste förhållandena passa. Vår befintliga vind- och säkerhetsinformation förklarar varför byig frånlandsvind förändrar följderna av ett pass:'),
      label: l('wind and safety in Tarifa', 'Wind und Sicherheit in Tarifa', 'viento y seguridad en Tarifa', 'wind en veiligheid in Tarifa', 'vind och säkerhet i Tarifa')
    }
  },
  {
    id: 'arte-vida',
    title: l('Arte Vida: a specialist coastal setting', 'Arte Vida: kein dritter Hauptspot', 'Arte Vida: un entorno costero más técnico', 'Arte Vida: een specialistische kustplek', 'Arte Vida: en mer krävande kustmiljö'),
    paragraphs: {
      en: ['We keep Arte Vida in the more advanced wave and coastal category. It belongs in a session shaped around that setting and your experience. For a first comparison of Tarifa’s main kite areas, Los Lances and Valdevaqueros remain the two reference points.'],
      de: ['Arte Vida gehört für uns in einen fortgeschritteneren Wellen- und Küstenkontext. Der Bereich passt zu einer Session, die ihr gezielt nach diesem Revier und eurer Erfahrung beurteilt. Bei der ersten Orientierung zwischen Tarifas Hauptspots bleiben Los Lances und Valdevaqueros die beiden Bezugspunkte.'],
      es: ['Situamos Arte Vida en un contexto de olas y costa para riders más avanzados. Tiene sentido valorar una sesión allí según ese entorno y vuestra experiencia. Para una primera comparación de las principales zonas de kite de Tarifa, Los Lances y Valdevaqueros siguen siendo las dos referencias.'],
      nl: ['Arte Vida hoort voor ons bij een meer gevorderde golf- en kustomgeving. Beoordeel een sessie daar aan de hand van dat terrein en jullie ervaring. Voor de eerste vergelijking van de belangrijkste kitegebieden blijven Los Lances en Valdevaqueros de twee vertrekpunten.'],
      sv: ['Vi placerar Arte Vida i en mer avancerad våg- och kustmiljö. Ett pass där behöver bedömas utifrån just den miljön och er erfarenhet. För en första jämförelse av Tarifas viktigaste kiteområden är Los Lances och Valdevaqueros fortfarande de två utgångspunkterna.']
    }
  },
  {
    id: 'plan-b',
    title: l('Getares and Palmones: Plan B in very strong Levante', 'Getares und Palmones: Plan B bei sehr starkem Levante', 'Getares y Palmones: plan B con levante muy fuerte', 'Getares en Palmones: plan B bij zeer sterke levante', 'Getares och Palmones: plan B vid mycket stark levante'),
    paragraphs: {
      en: ['When Levante becomes very strong in Tarifa, Getares near Algeciras is a possible local Plan B. Check current permission for kitesurfing and seasonal zoning on site before launching. Palmones is another option discussed locally, but we have no verified current kite permission or zoning to offer for it. Neither name promises beginner conditions or a safer session.', 'Bolonia and Caños de Meca are separate areas with their own rules. A change of beach requires a fresh assessment of access, permitted use and conditions; we do not treat them as straightforward substitutes for a Tarifa session.'],
      de: ['Wird der Levante in Tarifa sehr stark, kommt Getares bei Algeciras als lokale Plan-B-Idee infrage. Prüft vor dem Start die aktuelle Kite-Freigabe und saisonale Zonierung vor Ort. Auch Palmones wird lokal als Alternative erwogen; eine aktuell verifizierte Kite-Freigabe oder Zonenkarte können wir dafür nicht nennen. Keiner der beiden Namen verspricht Anfängerbedingungen oder eine sicherere Session.', 'Bolonia und Caños de Meca sind separate Gebiete mit eigenen Regeln. Ein Strandwechsel verlangt eine neue Einschätzung von Zugang, erlaubter Nutzung und Bedingungen; als unkomplizierten Ersatz für eine Tarifa-Session führen wir sie deshalb nicht.'],
      es: ['Cuando el levante se vuelve muy fuerte en Tarifa, Getares, en Algeciras, puede entrar en la conversación como plan B local. Antes de salir, comprobad allí la autorización actual para kite y la zonificación de temporada. Palmones también se contempla en la práctica local, pero no contamos con una autorización ni un plano de kite vigente verificados. Ninguno de los dos nombres promete condiciones para principiantes ni una sesión más segura.', 'Bolonia y Caños de Meca son zonas distintas con sus propias normas. Cambiar de playa exige volver a valorar el acceso, los usos permitidos y las condiciones; no las presentamos como sustitutos sencillos de una sesión en Tarifa.'],
      nl: ['Als de levante in Tarifa zeer sterk wordt, kan Getares bij Algeciras een lokaal plan B zijn. Controleer voor de start ter plaatse of kitesurfen momenteel is toegestaan en welke seizoenszones gelden. Ook Palmones wordt lokaal als alternatief overwogen, maar daarvoor hebben we geen actuele, geverifieerde toestemming of kitezonering. Geen van beide namen belooft beginnersomstandigheden of een veiligere sessie.', 'Bolonia en Caños de Meca zijn afzonderlijke gebieden met eigen regels. Een ander strand vraagt om een nieuwe beoordeling van toegang, toegestaan gebruik en omstandigheden; we behandelen ze daarom niet als eenvoudige vervanging voor een sessie in Tarifa.'],
      sv: ['När levante blir mycket stark i Tarifa kan Getares vid Algeciras vara en lokal plan B. Kontrollera på plats om kitesurfing är tillåten och vilka säsongszoner som gäller innan ni startar. Även Palmones nämns lokalt som alternativ, men vi har inget verifierat aktuellt kitetillstånd eller någon aktuell zonkarta att hänvisa till. Inget av namnen lovar nybörjarförhållanden eller ett säkrare pass.', 'Bolonia och Caños de Meca är separata områden med egna regler. Ett strandbyte kräver en ny bedömning av tillträde, tillåten användning och förhållanden; vi behandlar dem därför inte som enkla ersättare för ett pass i Tarifa.']
    }
  }
];

export const tarifaKitesurfSpotsContent = {
  token: 'tarifa_kitesurf_spots' as const,
  hero: {
    eyebrow: 'Tarifa Experience Guide', title,
    lead: l(
      'Tarifa is a system of kite spots. For independent riders, we start with Los Lances in Poniente and consider Valdevaqueros in Levante, where a suitable wind angle can make the bay’s downwind coastline more favourable. That is no safety guarantee. Wind direction, season, riding level and current zoning belong in the same decision. The official bathing season runs from 15 June to 15 September; on-site signs, buoys and permitted zones take priority. Balneario is a specialist Big Air spot, and kitesurfing in the Los Lances lagoon is prohibited. Research checked: 3 September 2026.',
      'Tarifa ist ein System aus mehreren Kitesurf-Spots. Für selbstständige Fahrer schauen wir bei Poniente zuerst auf Los Lances und bei Levante auf Valdevaqueros, wo ein passender Windwinkel eine günstigere Küstengeometrie in Abdriftrichtung ermöglichen kann. Das ist keine Sicherheitsgarantie. Windrichtung, Saison, Niveau und aktuelle Zonierung gehören zur selben Entscheidung. Die offizielle Badesaison läuft vom 15. Juni bis 15. September; Schilder, Bojen und erlaubte Zonen vor Ort haben Vorrang. Balneario ist ein Big-Air-Spezialspot, in der Los-Lances-Lagune ist Kitesurfen verboten. Recherchestand: 3. September 2026.',
      'Tarifa reúne un sistema de spots de kitesurf. Para quienes navegáis por vuestra cuenta, miramos primero Los Lances con poniente y Valdevaqueros con levante: con el ángulo adecuado, la bahía puede ofrecer una costa más favorable a sotavento. Eso no garantiza la seguridad. Dirección del viento, temporada, nivel y zonificación actual forman parte de la misma decisión. La temporada oficial de baño va del 15 de junio al 15 de septiembre; prevalecen las señales, las boyas y las zonas autorizadas sobre el terreno. Balneario es un spot especializado de Big Air y en la laguna de Los Lances está prohibido el kite. Información comprobada el 3 de septiembre de 2026.',
      'Tarifa bestaat uit meerdere kitesurfspots die samen een gebied vormen. Voor zelfstandige kiters kijken we bij poniente eerst naar Los Lances en bij levante naar Valdevaqueros, waar een passende windhoek een gunstiger kustlijn benedenwinds kan opleveren. Dat biedt geen veiligheidsgarantie. Windrichting, seizoen, niveau en actuele zonering horen bij dezelfde afweging. Het officiële badseizoen loopt van 15 juni tot 15 september; borden, boeien en toegestane zones ter plaatse gaan voor. Balneario is een specialistische Big Air-spot en in de lagune van Los Lances is kitesurfen verboden. Informatie gecontroleerd op 3 september 2026.',
      'Tarifa består av flera kitesurfspots som tillsammans bildar ett område. För självständiga åkare tittar vi först på Los Lances vid poniente och på Valdevaqueros vid levante, där en lämplig vindvinkel kan ge en gynnsammare kustlinje i lä. Det är ingen säkerhetsgaranti. Vindriktning, säsong, nivå och aktuell zonindelning hör till samma bedömning. Den officiella badsäsongen löper från 15 juni till 15 september; skyltar, bojar och tillåtna zoner på plats har företräde. Balneario är en specialistspot för Big Air, och kitesurfing i Los Lances-lagunen är förbjuden. Uppgifterna kontrollerades den 3 september 2026.'
    ),
    updated: l('Checked 3 September 2026', 'Geprüft am 3. September 2026', 'Comprobado el 3 de septiembre de 2026', 'Gecontroleerd op 3 september 2026', 'Kontrollerat den 3 september 2026'),
    note: l('Official beach sources and clearly attributed personal observations.', 'Offizielle Strandquellen und ausdrücklich gekennzeichnete persönliche Beobachtungen.', 'Fuentes oficiales de playa y observaciones personales identificadas.', 'Officiële strandbronnen en herkenbaar toegeschreven persoonlijke observaties.', 'Officiella strandkällor och tydligt angivna personliga iakttagelser.'),
    imageAlt: l('View from AMARA across Tarifa towards the Atlantic coast', 'Blick von AMARA über Tarifa zur Atlantikküste', 'Vista desde AMARA sobre Tarifa hacia la costa atlántica', 'Uitzicht vanaf AMARA over Tarifa naar de Atlantische kust', 'Utsikt från AMARA över Tarifa mot Atlantkusten')
  },
  orientation: {
    title: l('The spot map: Tarifa at a glance', 'Die Spot-Landkarte: Tarifa auf einen Blick', 'El mapa de spots: Tarifa de un vistazo', 'De spots: Tarifa in één oogopslag', 'Spotkartan: Tarifa i överblick'),
    columns: [
      { id: 'spot', label: l('Spot', 'Spot', 'Spot', 'Spot', 'Spot') },
      { id: 'role', label: l('Role', 'Rolle', 'Función', 'Rol', 'Roll') },
      { id: 'orientation', label: l('First orientation', 'Erste Orientierung', 'Primera orientación', 'Eerste oriëntatie', 'Första vägledning') }
    ],
    rows: [
      { id: 'los-lances', name: 'Los Lances Sur & Norte', role: l('Main spot', 'Hauptspot', 'Spot principal', 'Hoofdspot', 'Huvudspot'), text: l('Primarily Poniente; open coast in front of Tarifa', 'Vor allem Poniente, offene Küste direkt vor Tarifa', 'Sobre todo poniente; costa abierta frente a Tarifa', 'Vooral poniente, open kust vlak voor Tarifa', 'Främst poniente, öppen kust framför Tarifa') },
      { id: 'valdevaqueros', name: 'Valdevaqueros & Punta Paloma', role: l('Main spot', 'Hauptspot', 'Spot principal', 'Hoofdspot', 'Huvudspot'), text: l('Often the more suitable Tarifa option in Levante', 'Häufig die passendere Tarifa-Option bei Levante', 'A menudo la opción más adecuada en Tarifa con levante', 'Vaak de passendere optie in Tarifa bij levante', 'Ofta det lämpligare alternativet i Tarifa vid levante') },
      { id: 'balneario', name: 'Balneario', role: l('Specialist spot', 'Spezialspot', 'Spot especializado', 'Specialistische spot', 'Specialistspot'), text: l('Big Air and highly experienced riders', 'Big Air und sehr erfahrene Fahrer', 'Big Air y riders con mucha experiencia', 'Big Air en zeer ervaren kiters', 'Big Air och mycket erfarna åkare') },
      { id: 'arte-vida', name: 'Arte Vida', role: l('Specialist spot', 'Spezialspot', 'Spot especializado', 'Specialistische spot', 'Specialistspot'), text: l('Advanced wave and coastal setting', 'Fortgeschrittener Wellen-/Küstenkontext', 'Entorno de olas y costa para nivel avanzado', 'Gevorderde golf- en kustomgeving', 'Avancerad våg- och kustmiljö') },
      { id: 'getares', name: 'Getares', role: l('Levante Plan B', 'Levante-Plan B', 'Plan B con levante', 'Levante-plan B', 'Plan B vid levante'), text: l('Possible in very strong Levante; check current permission', 'Bei sehr starkem Levante denkbar, aktuelle Freigabe prüfen', 'Posible con levante muy fuerte; comprobar autorización actual', 'Denkbaar bij zeer sterke levante; controleer actuele toestemming', 'Tänkbart vid mycket stark levante; kontrollera aktuellt tillstånd') },
      { id: 'palmones', name: 'Palmones', role: l('Levante Plan B', 'Levante-Plan B', 'Plan B con levante', 'Levante-plan B', 'Plan B vid levante'), text: l('Local alternative; check current permission and zoning', 'Lokale Alternative, aktuelle Freigabe und Zonierung prüfen', 'Alternativa local; comprobar autorización y zonas actuales', 'Lokaal alternatief; controleer toestemming en actuele zones', 'Lokalt alternativ; kontrollera tillstånd och aktuell zonindelning') },
      { id: 'lagoon', name: l('Río Jara lagoon', 'Río-Jara-Lagune', 'Laguna del Río Jara', 'Río Jara-lagune', 'Río Jara-lagunen'), role: l('No kiting', 'Kein Kitespot', 'No es un spot de kite', 'Geen kitespot', 'Ingen kitespot'), text: l('Protected habitat; kitesurfing prohibited', 'Geschützter Naturraum, Kitesurfen verboten', 'Espacio natural protegido; kitesurf prohibido', 'Beschermd natuurgebied, kitesurfen verboden', 'Skyddad natur, kitesurfing förbjuden') },
      { id: 'other-areas', name: 'Bolonia & Caños de Meca', role: l('Separate areas', 'Separate Gebiete', 'Zonas independientes', 'Aparte gebieden', 'Separata områden'), text: l('Their own rules; not straightforward Tarifa alternatives', 'Eigene Regeln, keine einfache Tarifa-Alternative', 'Normas propias; no son alternativas sencillas a Tarifa', 'Eigen regels, geen eenvoudig alternatief voor Tarifa', 'Egna regler, inga enkla Tarifa-alternativ') }
    ]
  },
  decision: {
    title: l('The main decision: Los Lances or Valdevaqueros?', 'Die Hauptentscheidung: Los Lances oder Valdevaqueros?', 'La decisión principal: ¿Los Lances o Valdevaqueros?', 'De belangrijkste keuze: Los Lances of Valdevaqueros?', 'Huvudfrågan: Los Lances eller Valdevaqueros?'),
    condition: l('Conditions or aim', 'Bedingung oder Vorhaben', 'Condición u objetivo', 'Omstandigheid of doel', 'Förhållande eller mål'),
    orientation: l('First consideration', 'Erste Orientierung', 'Primera orientación', 'Eerste afweging', 'Första bedömning'),
    rows: [
      { id: 'poniente', condition: l('Poniente', 'Poniente', 'Poniente', 'Poniente', 'Poniente'), text: l('Look first at Los Lances.', 'Los Lances als erste Orientierung.', 'Mirad primero Los Lances.', 'Kijk eerst naar Los Lances.', 'Titta först på Los Lances.') },
      { id: 'levante', condition: l('Levante', 'Levante', 'Levante', 'Levante', 'Levante'), text: l('Valdevaqueros is often the more suitable Tarifa option, depending on the angle.', 'Valdevaqueros ist je nach Windwinkel häufig die passendere Tarifa-Option.', 'Valdevaqueros suele encajar mejor en Tarifa, según el ángulo.', 'Valdevaqueros past vaak beter, afhankelijk van de windhoek.', 'Valdevaqueros passar ofta bättre, beroende på vindvinkeln.') },
      { id: 'bathing-season', condition: l('15 June–15 September', '15. Juni bis 15. September', '15 de junio–15 de septiembre', '15 juni tot 15 september', '15 juni–15 september'), text: l('The permitted zone comes before your favourite spot.', 'Die erlaubte Zone ist wichtiger als euer Lieblingsspot.', 'La zona autorizada tiene prioridad sobre vuestro spot favorito.', 'De toegestane zone gaat voor jullie favoriete spot.', 'Den tillåtna zonen går före er favoritspot.') },
      { id: 'strong-levante', condition: l('Very strong Levante', 'Sehr starker Levante', 'Levante muy fuerte', 'Zeer sterke levante', 'Mycket stark levante'), text: l('Getares or Palmones only as Plan B ideas; confirm permission locally.', 'Getares/Palmones nur als Plan-B-Idee; aktuelle Freigabe vor Ort prüfen.', 'Getares o Palmones solo como idea de plan B; comprobad la autorización allí.', 'Getares of Palmones alleen als plan B; controleer lokaal of starten mag.', 'Getares eller Palmones endast som plan B; kontrollera tillstånd på plats.') },
      { id: 'big-air', condition: l('Big Air', 'Big Air', 'Big Air', 'Big Air', 'Big Air'), text: l('Balneario calls for genuine specialist ability.', 'Balneario nur bei echtem Spezialniveau.', 'Balneario exige un nivel verdaderamente especializado.', 'Balneario vraagt om echt specialistisch niveau.', 'Balneario kräver verklig specialistnivå.') }
    ],
    note: l('This table cannot replace an assessment on the beach. June and September each overlap the official bathing season; check the date and the zone on the day.', 'Die Tabelle ersetzt keine Einschätzung am Strand. Juni und September überschneiden sich jeweils mit der offiziellen Badesaison; prüft das Datum und die aktuelle Zone am jeweiligen Tag.', 'La tabla no sustituye la valoración en la playa. Junio y septiembre coinciden parcialmente con la temporada oficial de baño; comprobad la fecha y la zona ese día.', 'Deze tabel vervangt geen beoordeling op het strand. Juni en september vallen elk deels in het officiële badseizoen; controleer de datum en de actuele zone op de dag zelf.', 'Tabellen ersätter inte en bedömning på stranden. Juni och september överlappar båda den officiella badsäsongen; kontrollera datum och aktuell zon för dagen.')
  },
  observationLabel: l('Robert · personal experience', 'Robert · persönliche Erfahrung', 'Robert · experiencia personal', 'Robert · persoonlijke ervaring', 'Robert · personlig erfarenhet'),
  sections,
  checklist: {
    title: l('What to check before every session', 'Was ihr vor jeder Session prüfen solltet', 'Qué comprobar antes de cada sesión', 'Wat jullie voor elke sessie controleren', 'Vad ni behöver kontrollera inför varje pass'),
    items: [
      { id: 'wind', text: l('Wind direction, strength and gusts.', 'Windrichtung, Stärke und Böigkeit.', 'Dirección, fuerza y rachas del viento.', 'Windrichting, kracht en vlagen.', 'Vindriktning, styrka och byighet.') },
      { id: 'signs', text: l('Current signs and buoys.', 'Aktuelle Schilder und Bojen.', 'Señales y boyas actuales.', 'Actuele borden en boeien.', 'Aktuella skyltar och bojar.') },
      { id: 'zones', text: l('Permitted kite, school and bathing zones.', 'Erlaubte Kite-, Schul- und Badezonen.', 'Zonas autorizadas de kite, escuela y baño.', 'Toegestane kite-, les- en zwemzones.', 'Tillåtna kite-, skol- och badzoner.') },
      { id: 'corridors', text: l('Designated launch and exit corridors.', 'Ausgewiesene Start- und Ausstiegskorridore.', 'Pasillos señalizados de entrada y salida.', 'Aangewezen start- en uitstapstroken.', 'Anvisade start- och landningspassager.') },
      { id: 'ability', text: l('Your own riding ability.', 'Euer eigener Könnensstand.', 'Vuestro nivel real.', 'Jullie eigen vaardigheid.', 'Er egen förmåga.') }
    ]
  },
  sources: {
    eyebrow: l('Editorial transparency', 'Redaktionelle Transparenz', 'Transparencia editorial', 'Redactionele transparantie', 'Redaktionell transparens'),
    title: l('Official sources and current rules', 'Offizielle Quellen und aktuelle Regeln', 'Fuentes oficiales y normas vigentes', 'Officiële bronnen en actuele regels', 'Officiella källor och aktuella regler'),
    text: l('We checked the research on 3 September 2026. The beach plan shows the areas and their uses; the bay comparison is a conditional interpretation of coastal geometry, not an official safety rating. Robert’s observations are attributed separately. Current signs, buoys, zones and safety channels on site take priority.', 'Wir haben die Recherche am 3. September 2026 geprüft. Der Strandplan zeigt Bereiche und Nutzungen; der Buchtvergleich ist eine bedingte Einordnung der Küstengeometrie, keine amtliche Sicherheitsbewertung. Roberts Beobachtungen sind gesondert gekennzeichnet. Aktuelle Schilder, Bojen, Zonen und Sicherheitskanäle vor Ort haben Vorrang.', 'Revisamos la investigación el 3 de septiembre de 2026. El plan de playas muestra zonas y usos; la comparación de la bahía es una interpretación condicionada de la geometría costera, no una evaluación oficial de seguridad. Las observaciones de Robert se identifican por separado. Prevalecen las señales, boyas, zonas y canales de seguridad actuales sobre el terreno.', 'We hebben het onderzoek op 3 september 2026 gecontroleerd. Het strandplan toont gebieden en gebruik; de vergelijking van de baai is een voorwaardelijke duiding van de kustvorm, geen officieel veiligheidsoordeel. Roberts observaties zijn apart aangeduid. Actuele borden, boeien, zones en veiligheidsdoorgangen ter plaatse gaan voor.', 'Vi granskade underlaget den 3 september 2026. Strandplanen visar områden och användning; jämförelsen av bukten är en villkorad tolkning av kustgeometrin, ingen officiell säkerhetsbedömning. Roberts iakttagelser anges separat. Aktuella skyltar, bojar, zoner och säkerhetspassager på plats har företräde.'),
    items: [
      { id: 'beach-plan', label: 'Ayuntamiento de Tarifa · Plan de Explotación de Playas 2024–2027', href: 'https://www.aytotarifa.com/notices/plan-de-explotacion-de-playas-2024-2027/' },
      { id: 'ordinance', label: 'Ayuntamiento de Tarifa · Ordenanza municipal de uso y disfrute de las playas', href: 'https://www.aytotarifa.com/notices/ordenanza-municipal-reguladora-del-uso-y-disfrute-de-las-playas-del-termino-municipal-de-tarifa/' },
      { id: 'lagoon', label: 'Junta de Andalucía · Playa de Los Lances', href: 'https://www.juntadeandalucia.es/medioambiente/portal/web/ventanadelvisitante/detalle-buscador-mapa/-/asset_publisher/Jlbxh2qB3NwR/content/playa-de-los-lances/255035' }
    ]
  },
  closing: {
    eyebrow: l('Your base in Tarifa', 'Eure Basis in Tarifa', 'Vuestra base en Tarifa', 'Jullie uitvalsbasis in Tarifa', 'Er bas i Tarifa'),
    observation: l('My passion for kitesurfing was one reason I chose this location for our accommodation. From AMARA, I walk with my kit towards Los Lances when Poniente comes.', 'Meine Kite-Leidenschaft war ein Grund, diese Lage für unsere Unterkunft zu wählen. Von AMARA gehe ich bei Poniente selbst mit meinem Material zu Fuß Richtung Los Lances.', 'Mi pasión por el kite fue uno de los motivos para elegir esta ubicación para nuestro alojamiento. Desde AMARA voy andando con el material hacia Los Lances cuando entra poniente.', 'Mijn passie voor kitesurfen speelde mee bij de keuze van deze locatie voor ons verblijf. Vanuit AMARA loop ik bij poniente zelf met mijn materiaal richting Los Lances.', 'Min passion för kitesurfing var ett av skälen till att jag valde den här platsen för vårt boende. Från AMARA går jag själv med utrustningen mot Los Lances när poniente kommer.'),
    text: l('If being able to walk towards Los Lances matters for your stay, our AMARA Family & Surf is the accommodation behind that personal experience.', 'Wenn der Weg zu Fuß Richtung Los Lances für euren Aufenthalt zählt: Unser AMARA Family & Surf ist die Unterkunft hinter dieser persönlichen Erfahrung.', 'Si poder ir andando hacia Los Lances cuenta para vuestra estancia, nuestro AMARA Family & Surf es el alojamiento al que se refiere esta experiencia personal.', 'Als lopend richting Los Lances kunnen gaan belangrijk is voor jullie verblijf, is ons AMARA Family & Surf de accommodatie achter deze persoonlijke ervaring.', 'Om möjligheten att gå mot Los Lances är viktig för er vistelse är vårt AMARA Family & Surf boendet bakom den personliga erfarenheten.'),
    stayLabel: l('View AMARA Family & Surf', 'AMARA Family & Surf ansehen', 'Ver AMARA Family & Surf', 'Bekijk AMARA Family & Surf', 'Visa AMARA Family & Surf'),
    availabilityLabel: l('Check availability', 'Verfügbarkeit prüfen', 'Consultar disponibilidad', 'Bekijk beschikbaarheid', 'Se tillgänglighet')
  }
};

export const tarifaKitesurfSpotsHandoff = {
  text: l('If you already ride independently, the open coast at Los Lances and the curved bay at Valdevaqueros make wind angle and permitted zones central to the day’s choice. Our spot comparison explains those differences:', 'Wenn ihr bereits selbstständig fahrt, sind die offene Küste von Los Lances und die gekrümmte Bucht von Valdevaqueros entscheidend: Windwinkel und erlaubte Zonen bestimmen die Wahl für den Tag. Unser Spotvergleich erklärt diese Unterschiede:', 'Si ya navegáis por vuestra cuenta, la costa abierta de Los Lances y la curva de Valdevaqueros hacen que el ángulo del viento y las zonas autorizadas sean decisivos. Nuestra comparación explica esas diferencias:', 'Als jullie al zelfstandig varen, maken de open kust bij Los Lances en de gebogen baai van Valdevaqueros de windhoek en toegestane zones bepalend voor de dag. Onze spotvergelijking legt die verschillen uit:', 'Om ni redan åker självständigt gör den öppna kusten vid Los Lances och den böjda bukten vid Valdevaqueros vindvinkeln och tillåtna zoner avgörande för dagen. Vår spotjämförelse förklarar skillnaderna:'),
  label: l('kitesurf spots in Tarifa', 'Kitesurf-Spots in Tarifa', 'spots de kitesurf en Tarifa', 'kitesurfspots in Tarifa', 'kitesurfspots i Tarifa')
};
