import type { LinkToken } from '../lib/linkResolver';
import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';

export type LocalizedKiteText = Record<AmaraLanguage, string>;
export type TarifaKitesurfSpokeId = 'kite-school' | 'kitecamp' | 'equipment' | 'wind-spots-safety';

type KiteLink = {
  token: LinkToken;
  label: LocalizedKiteText;
  text: LocalizedKiteText;
};

export interface TarifaKitesurfSpokeContent {
  id: TarifaKitesurfSpokeId;
  token: LinkToken;
  seo: AmaraAuthoringSeo;
  navLabel: LocalizedKiteText;
  hero: {
    eyebrow: LocalizedKiteText;
    title: LocalizedKiteText;
    subtitle: LocalizedKiteText;
    lead: LocalizedKiteText;
    imageAlt: LocalizedKiteText;
  };
  facts: Array<{ id: string; label: LocalizedKiteText; value: LocalizedKiteText }>;
  sections: Array<{
    id: string;
    eyebrow: LocalizedKiteText;
    title: LocalizedKiteText;
    paragraphs: LocalizedKiteText[];
  }>;
  partner: {
    title: LocalizedKiteText;
    text: LocalizedKiteText;
    href: string;
    label: LocalizedKiteText;
  };
  related: KiteLink[];
  closing: {
    title: LocalizedKiteText;
    text: LocalizedKiteText;
    contactLabel: LocalizedKiteText;
    contactMessage: LocalizedKiteText;
  };
}

const l = (en: string, de: string, es: string, nl: string, sv: string): LocalizedKiteText => ({ en, de, es, nl, sv });

const article = {
  datePublished: '2026-09-02',
  dateModified: '2026-09-02',
  authorName: 'Robert Sebastian Böhmer',
  authorType: 'Person' as const,
  authorSlug: 'staying-with-us'
};

const seo = (version: string, title: LocalizedKiteText, description: LocalizedKiteText): AmaraAuthoringSeo => ({
  version,
  pageType: 'B',
  entityKey: 'amara-brand',
  article,
  languages: {
    en: { title: title.en, description: description.en, robots: 'index, follow', canonical: 'auto' },
    de: { title: title.de, description: description.de, robots: 'index, follow', canonical: 'auto' },
    es: { title: title.es, description: description.es, robots: 'index, follow', canonical: 'auto' },
    nl: { title: title.nl, description: description.nl, robots: 'index, follow', canonical: 'auto' },
    sv: { title: title.sv, description: description.sv, robots: 'index, follow', canonical: 'auto' }
  }
});

const common = {
  imageAlt: l(
    'Tarifa Surf Club team together at the beach in Tarifa',
    'Das Team des Tarifa Surf Club gemeinsam am Strand in Tarifa',
    'El equipo de Tarifa Surf Club reunido en la playa de Tarifa',
    'Het team van Tarifa Surf Club samen op het strand in Tarifa',
    'Tarifa Surf Club-teamet tillsammans på stranden i Tarifa'
  ),
  contactLabel: l(
    'Message AMARA about your kite stay',
    'AMARA zum Kite-Aufenthalt schreiben',
    'Escribir a AMARA sobre vuestro viaje de kite',
    'Stuur AMARA een bericht over jullie kiteverblijf',
    'Skriv till AMARA om er kitevistelse'
  )
} as const;

const school: TarifaKitesurfSpokeContent = {
  id: 'kite-school',
  token: 'tarifa_kite_school',
  seo: seo(
    '2026-09-02-tarifa-kite-school-v1.0',
    l('Kite School Tarifa & Kitesurf Lessons | AMARA', 'Kiteschule Tarifa & Kitesurfkurse | AMARA', 'Escuela de kitesurf en Tarifa y cursos | AMARA', 'Kiteschool Tarifa & kitesurflessen | AMARA', 'Kiteskola Tarifa & kitesurfkurser | AMARA'),
    l('Combine your AMARA stay with kitesurf lessons for beginners or advanced riders at Tarifa Surf Club. We coordinate dates, level and course.', 'Verbindet euren AMARA-Aufenthalt mit Kitesurfkursen für Anfänger oder Fortgeschrittene beim Tarifa Surf Club. Wir stimmen Termine, Level und Kurs ab.', 'Combinad vuestra estancia AMARA con cursos para principiantes o avanzados en Tarifa Surf Club. Coordinamos fechas, nivel y curso.', 'Combineer jullie AMARA-verblijf met kitesurflessen voor beginners of gevorderden bij Tarifa Surf Club. Wij stemmen data, niveau en les af.', 'Kombinera ert AMARA-boende med kitesurfkurser för nybörjare eller erfarna hos Tarifa Surf Club. Vi samordnar datum, nivå och kurs.')
  ),
  navLabel: l('Kite school & courses', 'Kiteschule & Kurse', 'Escuela y cursos', 'Kiteschool & lessen', 'Kiteskola & kurser'),
  hero: {
    eyebrow: l('Kitesurf lessons in Tarifa', 'Kitesurfkurse in Tarifa', 'Cursos de kitesurf en Tarifa', 'Kitesurflessen in Tarifa', 'Kitesurfkurser i Tarifa'),
    title: l('Kite school in Tarifa', 'Kiteschule in Tarifa', 'Escuela de kite', 'Kiteschool in Tarifa', 'Kiteskola i Tarifa'),
    subtitle: l('The right course for your level, coordinated with your AMARA stay.', 'Der passende Kurs für euer Level, abgestimmt auf euren AMARA-Aufenthalt.', 'El curso adecuado para vuestro nivel, coordinado con vuestra estancia en AMARA.', 'De juiste les voor jullie niveau, afgestemd op jullie AMARA-verblijf.', 'Rätt kurs för er nivå, samordnad med ert AMARA-boende.'),
    lead: l(
      'Tell us whether you are starting from scratch, returning after a break or working on a specific skill. We coordinate group or private lessons with our friends at Tarifa Surf Club and align the course with your travel dates. The team decides the suitable beach and session time from the current wind, zones and your level. This keeps the practical details in one conversation while qualified instructors remain responsible for teaching and safety on the water.',
      'Sagt uns, ob ihr ganz neu beginnt, nach einer Pause zurückkehrt oder an einer bestimmten Technik arbeiten möchtet. Wir koordinieren Gruppen- oder Privatkurse mit unseren Freunden vom Tarifa Surf Club und stimmen sie auf eure Reisedaten ab. Das Team wählt Strand und Zeitfenster nach aktuellem Wind, Zonen und eurem Level. So bleiben die praktischen Details in einem Gespräch, während qualifizierte Lehrer Unterricht und Sicherheit auf dem Wasser verantworten.',
      'Contadnos si empezáis desde cero, retomáis el deporte o queréis trabajar una técnica concreta. Coordinamos clases en grupo o privadas con nuestros amigos de Tarifa Surf Club y las ajustamos a vuestras fechas. El equipo elige la playa y el horario según el viento, las zonas vigentes y vuestro nivel. Así reunimos la organización en una conversación y los instructores cualificados se ocupan de la enseñanza y la seguridad en el agua.',
      'Vertel ons of jullie voor het eerst beginnen, na een pauze terugkeren of aan een specifieke techniek willen werken. Wij stemmen groeps- of privélessen met onze vrienden van Tarifa Surf Club af op jullie reisdata. Het team kiest strand en tijdstip op basis van de actuele wind, zones en jullie niveau. Zo blijft de praktische organisatie in één gesprek, terwijl gekwalificeerde instructeurs les en veiligheid op het water verzorgen.',
      'Berätta om ni börjar från grunden, återvänder efter ett uppehåll eller vill utveckla en särskild teknik. Vi samordnar grupp- eller privatlektioner med våra vänner på Tarifa Surf Club och anpassar kursen till era resedatum. Teamet väljer strand och tid efter aktuell vind, zoner och nivå. Det praktiska samlas i en dialog, medan kvalificerade instruktörer ansvarar för undervisning och säkerhet på vattnet.'
    ),
    imageAlt: common.imageAlt
  },
  facts: [
    { id: 'level', label: l('Level', 'Level', 'Nivel', 'Niveau', 'Nivå'), value: l('First lesson to progression', 'Erster Kurs bis Fortschritt', 'Iniciación y progresión', 'Eerste les tot progressie', 'Första lektionen till utveckling') },
    { id: 'format', label: l('Format', 'Format', 'Formato', 'Vorm', 'Format'), value: l('Group or private', 'Gruppe oder privat', 'Grupo o privado', 'Groep of privé', 'Grupp eller privat') },
    { id: 'conditions', label: l('Daily decision', 'Tägliche Entscheidung', 'Decisión diaria', 'Dagelijkse keuze', 'Dagligt beslut'), value: l('Wind, zones and level', 'Wind, Zonen und Level', 'Viento, zonas y nivel', 'Wind, zones en niveau', 'Vind, zoner och nivå') }
  ],
  sections: [
    { id: 'right-course', eyebrow: l('Course fit', 'Kurswahl', 'Curso adecuado', 'Passende les', 'Rätt kurs'), title: l('Start with your real experience', 'Beginnt bei eurer tatsächlichen Erfahrung', 'Partid de vuestra experiencia real', 'Begin bij jullie echte ervaring', 'Utgå från er faktiska erfarenhet'), paragraphs: [l('A first water start needs a different lesson from confident riding or technique coaching. Share previous lessons, time since your last session and what you want to achieve.', 'Ein erster Wasserstart braucht einen anderen Kurs als sicheres Fahren oder Techniktraining. Nennt uns bisherige Kurse, die Zeit seit eurer letzten Session und euer Ziel.', 'Un primer waterstart requiere otra clase que navegar con soltura o perfeccionar técnica. Indicad cursos previos, tiempo desde la última sesión y vuestro objetivo.', 'Een eerste waterstart vraagt iets anders dan zeker varen of techniekcoaching. Deel eerdere lessen, de tijd sinds jullie laatste sessie en jullie doel.', 'En första vattenstart kräver en annan lektion än säker åkning eller teknikträning. Berätta om tidigare kurser, tid sedan senaste sessionen och ert mål.'), l('Tarifa Surf Club can then recommend the suitable course format and instructor setup. We connect that recommendation with the days you are staying at AMARA.', 'Der Tarifa Surf Club kann daraufhin Kursformat und Betreuung passend empfehlen. Wir verbinden diese Empfehlung mit den Tagen eures AMARA-Aufenthalts.', 'Tarifa Surf Club puede recomendar entonces el formato y la atención adecuados. Nosotros lo coordinamos con los días de vuestra estancia en AMARA.', 'Tarifa Surf Club kan vervolgens een passende lesvorm en begeleiding adviseren. Wij koppelen dat aan de dagen van jullie AMARA-verblijf.', 'Tarifa Surf Club kan då rekommendera lämpligt kursformat och upplägg. Vi kopplar det till dagarna för er AMARA-vistelse.')] },
    { id: 'daily-session', eyebrow: l('On the day', 'Am Kurstag', 'El día del curso', 'Op de lesdag', 'På kursdagen'), title: l('Conditions decide where the lesson happens', 'Die Bedingungen bestimmen den Kursort', 'Las condiciones determinan el lugar', 'De omstandigheden bepalen de plek', 'Förhållandena avgör platsen'), paragraphs: [l('The meeting point and timing may move with Levante, Poniente, tide, local zoning and safety guidance. Keep the course window flexible until the school confirms the session.', 'Treffpunkt und Uhrzeit können sich mit Levante, Poniente, Gezeiten, lokalen Zonen und Sicherheitshinweisen ändern. Haltet das Kursfenster flexibel, bis die Schule die Session bestätigt.', 'El punto de encuentro y la hora pueden cambiar con Levante, Poniente, la marea, las zonas y las indicaciones de seguridad. Mantened flexible la franja hasta que la escuela confirme la sesión.', 'Verzamelpunt en tijd kunnen veranderen door Levante, Poniente, getij, lokale zones en veiligheidsadvies. Houd het lesvenster flexibel tot de school de sessie bevestigt.', 'Mötesplats och tid kan ändras med Levante, Poniente, tidvatten, lokala zoner och säkerhetsråd. Håll kursfönstret flexibelt tills skolan bekräftar sessionen.') ] }
  ],
  partner: { title: l('Courses with Tarifa Surf Club', 'Kurse beim Tarifa Surf Club', 'Cursos con Tarifa Surf Club', 'Lessen bij Tarifa Surf Club', 'Kurser hos Tarifa Surf Club'), text: l('See the school offer and course formats directly from our partner.', 'Seht euch Angebot und Kursformate direkt bei unserem Partner an.', 'Consultad la oferta y los formatos directamente con nuestro colaborador.', 'Bekijk het aanbod en de lesvormen direct bij onze partner.', 'Se erbjudandet och kursformaten direkt hos vår partner.'), href: 'https://tarifasurfclub.com/kitekurs-in-tarifa', label: l('View kite courses', 'Kitesurfkurse ansehen', 'Ver cursos de kitesurf', 'Bekijk kitesurflessen', 'Se kitesurfkurser') },
  related: [],
  closing: { title: l('Match your lessons to your stay', 'Kurse und Aufenthalt zusammenbringen', 'Coordinar cursos y estancia', 'Stem lessen en verblijf op elkaar af', 'Samordna kurs och boende'), text: l('Send us your dates, number of guests and kite experience. We coordinate the next practical step with Tarifa Surf Club.', 'Schickt uns Reisedaten, Personenzahl und Kite-Erfahrung. Wir koordinieren den nächsten praktischen Schritt mit dem Tarifa Surf Club.', 'Enviadnos fechas, número de huéspedes y experiencia. Coordinamos el siguiente paso con Tarifa Surf Club.', 'Stuur ons reisdata, aantal gasten en kite-ervaring. Wij stemmen de volgende stap af met Tarifa Surf Club.', 'Skicka resedatum, antal gäster och kiteerfarenhet. Vi samordnar nästa steg med Tarifa Surf Club.'), contactLabel: common.contactLabel, contactMessage: l('Hello AMARA, we are interested in kitesurf lessons in Tarifa. Travel dates: / Guests: / Kite experience: / Private or group preference:', 'Hallo AMARA, wir interessieren uns für Kitesurfkurse in Tarifa. Reisedaten: / Gäste: / Kite-Erfahrung: / Wunsch privat oder Gruppe:', 'Hola AMARA, nos interesan cursos de kitesurf en Tarifa. Fechas: / Huéspedes: / Experiencia: / Preferencia grupo o privado:', 'Hallo AMARA, we hebben interesse in kitesurflessen in Tarifa. Reisdata: / Gasten: / Ervaring: / Voorkeur privé of groep:', 'Hej AMARA, vi är intresserade av kitesurfkurser i Tarifa. Resedatum: / Gäster: / Erfarenhet: / Önskemål privat eller grupp:') }
};

const camp: TarifaKitesurfSpokeContent = {
  id: 'kitecamp', token: 'tarifa_kitecamp',
  seo: seo('2026-09-02-tarifa-kitecamp-v1.0', l('Kitecamp Tarifa with Accommodation | AMARA', 'Kitecamp Tarifa mit Unterkunft | AMARA', 'Kitecamp en Tarifa con alojamiento | AMARA', 'Kitecamp Tarifa met verblijf | AMARA', 'Kitecamp Tarifa med boende | AMARA'), l('Combine a multi-day Tarifa kitecamp with AMARA Family & Surf. We coordinate accommodation and the Tarifa Surf Club programme in one conversation.', 'Verbindet ein mehrtägiges Kitecamp in Tarifa mit AMARA Family & Surf. Wir koordinieren Unterkunft und Surf-Club-Programm in einem Gespräch.', 'Combinad un kitecamp de varios días con AMARA Family & Surf. Coordinamos alojamiento y programa de Tarifa Surf Club en una conversación.', 'Combineer een meerdaags kitecamp met AMARA Family & Surf. Wij stemmen verblijf en het programma van Tarifa Surf Club in één gesprek af.', 'Kombinera ett kitecamp över flera dagar med AMARA Family & Surf. Vi samordnar boende och program hos Tarifa Surf Club i en dialog.')),
  navLabel: l('Kitecamp & stay', 'Kitecamp & Unterkunft', 'Kitecamp y alojamiento', 'Kitecamp & verblijf', 'Kitecamp & boende'),
  hero: { eyebrow: l('Several days on the water', 'Mehrere Tage auf dem Wasser', 'Varios días en el agua', 'Meerdere dagen op het water', 'Flera dagar på vattnet'), title: l('Kitecamp in Tarifa', 'Kitecamp in Tarifa', 'Kitecamp en Tarifa', 'Kitecamp in Tarifa', 'Kitecamp i Tarifa'), subtitle: l('Coaching, accommodation and personal coordination in one stay.', 'Betreuung, Unterkunft und persönliche Abstimmung in einem Aufenthalt.', 'Clases, alojamiento y coordinación personal en una estancia.', 'Coaching, verblijf en persoonlijke afstemming in één reis.', 'Coaching, boende och personlig samordning under en vistelse.'), lead: l('A kitecamp gives you several days to learn, practise and respond to Tarifa’s changing conditions. Tell us your dates, group size and level; we coordinate the programme with Tarifa Surf Club and match it with AMARA Family & Surf when available. The school remains responsible for the kite programme and adapts sessions to wind and safety. We keep accommodation and local coordination connected, including an introduction to premium Surf Club accommodation when AMARA is already booked.', 'Ein Kitecamp gibt euch mehrere Tage zum Lernen, Üben und Reagieren auf Tarifas wechselnde Bedingungen. Nennt uns Reisedaten, Personenzahl und Level; wir stimmen das Programm mit dem Tarifa Surf Club ab und verbinden es nach Verfügbarkeit mit AMARA Family & Surf. Die Schule verantwortet das Kiteprogramm und passt Sessions an Wind und Sicherheit an. Wir halten Unterkunft und lokale Abstimmung zusammen und vermitteln bei belegtem AMARA gern eine Premium-Unterkunft des Surf Clubs.', 'Un kitecamp os da varios días para aprender, practicar y adaptaros a las condiciones cambiantes de Tarifa. Indicadnos fechas, grupo y nivel; coordinamos el programa con Tarifa Surf Club y lo combinamos con AMARA Family & Surf cuando esté disponible. La escuela dirige el programa y adapta las sesiones al viento y la seguridad. Nosotros conectamos alojamiento y organización local, y si AMARA está completo os presentamos alojamientos premium del Surf Club.', 'Een kitecamp geeft jullie meerdere dagen om te leren, oefenen en in te spelen op de wisselende omstandigheden van Tarifa. Deel data, groepsgrootte en niveau; wij stemmen het programma af met Tarifa Surf Club en koppelen het waar mogelijk aan AMARA Family & Surf. De school verzorgt het kiteprogramma en past sessies aan wind en veiligheid aan. Is AMARA vol, dan brengen we jullie graag in contact met premium verblijf van de Surf Club.', 'Ett kitecamp ger flera dagar att lära, träna och anpassa sig till Tarifas skiftande förhållanden. Berätta datum, gruppstorlek och nivå; vi samordnar programmet med Tarifa Surf Club och kombinerar det med AMARA Family & Surf när det är ledigt. Skolan ansvarar för kiteprogrammet och anpassar passen efter vind och säkerhet. Om AMARA är fullbokat förmedlar vi gärna premiumboende hos Surf Club.'), imageAlt: common.imageAlt },
  facts: [
    { id: 'duration', label: l('Rhythm', 'Rhythmus', 'Ritmo', 'Ritme', 'Rytm'), value: l('Several coordinated days', 'Mehrere abgestimmte Tage', 'Varios días coordinados', 'Meerdere afgestemde dagen', 'Flera samordnade dagar') },
    { id: 'fit', label: l('Programme', 'Programm', 'Programa', 'Programma', 'Program'), value: l('Adapted to level and wind', 'An Level und Wind angepasst', 'Adaptado al nivel y al viento', 'Aangepast aan niveau en wind', 'Anpassat till nivå och vind') },
    { id: 'stay', label: l('Accommodation', 'Unterkunft', 'Alojamiento', 'Verblijf', 'Boende'), value: l('AMARA or partner option', 'AMARA oder Partneroption', 'AMARA u opción colaboradora', 'AMARA of partneroptie', 'AMARA eller partneralternativ') }
  ],
  sections: [
    { id: 'camp-shape', eyebrow: l('Camp format', 'Camp-Format', 'Formato del camp', 'Campvorm', 'Campformat'), title: l('A longer window creates better options', 'Ein längeres Zeitfenster schafft bessere Möglichkeiten', 'Más días ofrecen mejores opciones', 'Meer dagen geven meer mogelijkheden', 'Fler dagar ger bättre möjligheter'), paragraphs: [l('Tarifa does not promise the same wind every day. A multi-day stay gives the school room to place coaching in the suitable windows and gives you recovery time between sessions.', 'Tarifa verspricht nicht jeden Tag denselben Wind. Mehrere Tage geben der Schule Raum für passende Kursfenster und euch Erholung zwischen den Sessions.', 'Tarifa no ofrece el mismo viento cada día. Varios días permiten a la escuela situar las clases en las mejores franjas y os dejan tiempo para recuperaros.', 'Tarifa biedt niet elke dag dezelfde wind. Meerdere dagen geven de school ruimte voor passende lesmomenten en jullie hersteltijd tussen sessies.', 'Tarifa har inte samma vind varje dag. Flera dagar ger skolan utrymme för rätt lektionsfönster och er tid för återhämtning mellan passen.') ] },
    { id: 'accommodation', eyebrow: l('Stay together', 'Gemeinsam wohnen', 'Alojarse juntos', 'Samen verblijven', 'Bo tillsammans'), title: l('AMARA Family & Surf as your base', 'AMARA Family & Surf als Basis', 'AMARA Family & Surf como base', 'AMARA Family & Surf als basis', 'AMARA Family & Surf som bas'), paragraphs: [l('The apartment welcomes up to four guests and gives active days a private terrace, sea views, pool access and a reserved underground parking space.', 'Das Apartment bietet bis zu vier Gästen nach aktiven Tagen eine private Terrasse, Meerblick, Poolzugang und einen reservierten Tiefgaragenplatz.', 'El apartamento acoge hasta cuatro huéspedes con terraza privada, vistas al mar, piscina y plaza reservada en garaje.', 'Het appartement biedt maximaal vier gasten een privéterras, zeezicht, zwembad en een gereserveerde ondergrondse parkeerplaats.', 'Lägenheten välkomnar upp till fyra gäster med privat terrass, havsutsikt, pool och reserverad garageplats.'), l('If your dates are already booked, we can introduce you to one of Tarifa Surf Club’s premium accommodation options and keep the kite coordination in the same personal conversation.', 'Sind eure Daten bereits belegt, vermitteln wir euch gern eine Premium-Unterkunft des Tarifa Surf Club und halten die Kite-Abstimmung im selben persönlichen Gespräch.', 'Si vuestras fechas ya están ocupadas, os presentamos una opción premium de Tarifa Surf Club y mantenemos la coordinación del kite en la misma conversación.', 'Zijn jullie data al bezet, dan brengen we jullie graag in contact met premium verblijf van Tarifa Surf Club en houden we de kite-afstemming in hetzelfde persoonlijke gesprek.', 'Om era datum redan är bokade förmedlar vi gärna ett premiumboende hos Tarifa Surf Club och behåller samordningen i samma personliga dialog.') ] }
  ],
  partner: { title: l('The Tarifa Surf Club kitecamp', 'Das Kitecamp des Tarifa Surf Club', 'El kitecamp de Tarifa Surf Club', 'Het kitecamp van Tarifa Surf Club', 'Tarifa Surf Clubs kitecamp'), text: l('See the partner’s current camp programme and enquiry options.', 'Seht euch das aktuelle Camp-Programm und die Anfragemöglichkeiten unseres Partners an.', 'Consultad el programa actual y las opciones de contacto del colaborador.', 'Bekijk het actuele programma en de aanvraagmogelijkheden van onze partner.', 'Se partnerns aktuella program och kontaktvägar.'), href: 'https://tarifasurfclub.com/kitecamp-in-tarifa-spanien', label: l('View kitecamp', 'Kitecamp ansehen', 'Ver kitecamp', 'Bekijk kitecamp', 'Se kitecamp') },
  related: [],
  closing: { title: l('Bring camp and accommodation together', 'Kitecamp und Unterkunft zusammenbringen', 'Unir kitecamp y alojamiento', 'Breng kitecamp en verblijf samen', 'Samordna kitecamp och boende'), text: l('Share your dates, group size and level. We check the accommodation path and connect you with the suitable Surf Club programme.', 'Teilt uns Reisedaten, Personenzahl und Level mit. Wir prüfen die Unterkunft und verbinden euch mit dem passenden Surf-Club-Programm.', 'Compartid fechas, grupo y nivel. Comprobamos el alojamiento y os conectamos con el programa adecuado.', 'Deel data, groepsgrootte en niveau. Wij bekijken het verblijf en verbinden jullie met het passende programma.', 'Dela datum, gruppstorlek och nivå. Vi ser över boendet och kopplar er till rätt program.'), contactLabel: common.contactLabel, contactMessage: l('Hello AMARA, we are interested in a Tarifa kitecamp with accommodation. Travel dates: / Guests: / Kite level:', 'Hallo AMARA, wir interessieren uns für ein Kitecamp in Tarifa mit Unterkunft. Reisedaten: / Gäste: / Kite-Level:', 'Hola AMARA, nos interesa un kitecamp en Tarifa con alojamiento. Fechas: / Huéspedes: / Nivel:', 'Hallo AMARA, we hebben interesse in een kitecamp in Tarifa met verblijf. Reisdata: / Gasten: / Niveau:', 'Hej AMARA, vi är intresserade av ett kitecamp i Tarifa med boende. Resedatum: / Gäster: / Nivå:') }
};

const equipment: TarifaKitesurfSpokeContent = {
  id: 'equipment', token: 'tarifa_kite_equipment',
  seo: seo('2026-09-02-tarifa-kite-equipment-v1.0', l('Kite Equipment Rental & Shop Tarifa | AMARA', 'Kitematerial leihen & kaufen in Tarifa | AMARA', 'Alquiler y tienda de material de kite en Tarifa | AMARA', 'Kitemateriaal huren & kopen in Tarifa | AMARA', 'Hyra & köpa kiteutrustning i Tarifa | AMARA'), l('Rent or buy kitesurf equipment in Tarifa with local advice from Tarifa Surf Club, coordinated with your AMARA stay.', 'Kitematerial in Tarifa mit lokaler Beratung beim Tarifa Surf Club leihen oder kaufen – abgestimmt auf euren AMARA-Aufenthalt.', 'Alquilad o comprad material de kitesurf con asesoramiento local de Tarifa Surf Club, coordinado con vuestra estancia AMARA.', 'Huur of koop kitesurfmateriaal met lokaal advies van Tarifa Surf Club, afgestemd op jullie AMARA-verblijf.', 'Hyr eller köp kiteutrustning med lokala råd från Tarifa Surf Club, samordnat med ert AMARA-boende.')),
  navLabel: l('Equipment rental & shop', 'Material leihen & kaufen', 'Alquiler y tienda', 'Verhuur & shop', 'Uthyrning & butik'),
  hero: { eyebrow: l('Kite equipment in Tarifa', 'Kitematerial in Tarifa', 'Material de kite en Tarifa', 'Kitemateriaal in Tarifa', 'Kiteutrustning i Tarifa'), title: l('Rent or buy kite equipment', 'Kitematerial in Tarifa', 'Material de kite', 'Kitemateriaal huren of kopen', 'Hyr eller köp kiteutrustning'), subtitle: l('Local advice and equipment matched to your session.', 'Lokale Beratung und Material passend zu eurer Session.', 'Asesoramiento local y material adecuado para vuestra sesión.', 'Lokaal advies en materiaal voor jullie sessie.', 'Lokala råd och utrustning för er session.'), lead: l('If you prefer to travel light or need a different setup for Tarifa, our friends at Tarifa Surf Club offer current equipment to rent and a specialist shop for purchases. Tell us your dates, level and what you already ride; we connect the request with the team so they can advise on availability and suitability. The final setup always follows current conditions and professional guidance, especially when wind strength or direction changes.', 'Wenn ihr leicht reisen oder für Tarifa ein anderes Setup nutzen möchtet, bieten unsere Freunde vom Tarifa Surf Club aktuelles Material zum Leihen und einen spezialisierten Shop für den Kauf. Nennt uns Reisedaten, Level und euer gewohntes Setup; wir verbinden eure Anfrage mit dem Team, das Verfügbarkeit und Eignung beurteilt. Das endgültige Material richtet sich immer nach den aktuellen Bedingungen und professioneller Beratung – besonders bei wechselnder Windstärke oder -richtung.', 'Si preferís viajar ligeros o necesitáis otro equipo para Tarifa, nuestros amigos de Tarifa Surf Club ofrecen material actual de alquiler y una tienda especializada. Indicadnos fechas, nivel y el equipo que usáis; conectamos la consulta con el equipo para que valore disponibilidad e idoneidad. La configuración final sigue siempre las condiciones del día y el asesoramiento profesional, sobre todo cuando cambian la fuerza o la dirección del viento.', 'Willen jullie licht reizen of voor Tarifa een andere setup gebruiken, dan bieden onze vrienden van Tarifa Surf Club actueel huurmateriaal en een gespecialiseerde shop. Deel data, niveau en wat jullie normaal varen; wij verbinden de aanvraag met het team voor advies over beschikbaarheid en geschiktheid. De uiteindelijke setup volgt altijd de actuele omstandigheden en professioneel advies, vooral wanneer windkracht of richting verandert.', 'Om ni vill resa lätt eller behöver en annan setup i Tarifa erbjuder våra vänner på Tarifa Surf Club aktuell hyrutrustning och en specialiserad butik. Berätta datum, nivå och vad ni brukar åka med; vi kopplar frågan till teamet som bedömer tillgänglighet och lämplighet. Den slutliga utrustningen följer alltid dagens förhållanden och professionella råd, särskilt när vindstyrka eller riktning ändras.'), imageAlt: common.imageAlt },
  facts: [
    { id: 'rental', label: l('Rental', 'Verleih', 'Alquiler', 'Verhuur', 'Uthyrning'), value: l('Equipment for individual sessions', 'Material für einzelne Sessions', 'Material para sesiones individuales', 'Materiaal voor losse sessies', 'Utrustning för enskilda pass') },
    { id: 'shop', label: l('Shop', 'Shop', 'Tienda', 'Shop', 'Butik'), value: l('Kites, boards and accessories', 'Kites, Boards und Zubehör', 'Cometas, tablas y accesorios', 'Kites, boards en accessoires', 'Kites, brädor och tillbehör') },
    { id: 'advice', label: l('Advice', 'Beratung', 'Asesoramiento', 'Advies', 'Råd'), value: l('Local setup knowledge', 'Lokale Setup-Kenntnis', 'Conocimiento local del equipo', 'Lokale setupkennis', 'Lokal kunskap om setup') }
  ],
  sections: [
    { id: 'rent', eyebrow: l('Travel light', 'Leicht reisen', 'Viajar ligeros', 'Licht reizen', 'Res lätt'), title: l('Rent for the conditions you actually meet', 'Für die Bedingungen leihen, die ihr wirklich vorfindet', 'Alquilar para las condiciones reales', 'Huur voor de omstandigheden die er echt zijn', 'Hyr för de förhållanden ni faktiskt möter'), paragraphs: [l('Availability, size and setup need to be confirmed for the relevant dates. Share your weight, level and usual equipment so the team can start with useful information.', 'Verfügbarkeit, Größe und Setup müssen für die jeweiligen Daten bestätigt werden. Nennt Gewicht, Level und gewohntes Material, damit das Team mit hilfreichen Angaben starten kann.', 'Hay que confirmar disponibilidad, talla y configuración para las fechas. Indicad peso, nivel y material habitual para que el equipo parta de datos útiles.', 'Beschikbaarheid, maat en setup moeten voor de data worden bevestigd. Deel gewicht, niveau en gebruikelijk materiaal, zodat het team met nuttige informatie kan beginnen.', 'Tillgänglighet, storlek och setup måste bekräftas för datumen. Ange vikt, nivå och vanlig utrustning så att teamet får rätt utgångspunkt.') ] },
    { id: 'buy', eyebrow: l('Specialist shop', 'Spezialisierter Shop', 'Tienda especializada', 'Gespecialiseerde shop', 'Specialiserad butik'), title: l('Buy with advice from people who ride here', 'Mit Rat von Menschen kaufen, die hier fahren', 'Comprar con el consejo de quienes navegan aquí', 'Koop met advies van mensen die hier varen', 'Köp med råd från dem som åker här'), paragraphs: [l('The Surf Club shop carries kites, boards and accessories. Their local knowledge helps connect product questions with the wind range, riding style and practical use you describe.', 'Der Surf-Club-Shop führt Kites, Boards und Zubehör. Das lokale Wissen verbindet Produktfragen mit Windbereich, Fahrstil und dem praktischen Einsatz, den ihr beschreibt.', 'La tienda ofrece cometas, tablas y accesorios. Su conocimiento local ayuda a relacionar cada producto con el rango de viento, el estilo y el uso que describís.', 'De Surf Club-shop heeft kites, boards en accessoires. Hun lokale kennis koppelt productvragen aan windbereik, vaarstijl en het gebruik dat jullie beschrijven.', 'Surf Club-butiken har kites, brädor och tillbehör. Deras lokala kunskap kopplar produktfrågor till vindregister, åkstil och användning.') ] }
  ],
  partner: { title: l('Rental and shop at Tarifa Surf Club', 'Verleih und Shop beim Tarifa Surf Club', 'Alquiler y tienda de Tarifa Surf Club', 'Verhuur en shop bij Tarifa Surf Club', 'Uthyrning och butik hos Tarifa Surf Club'), text: l('Check the current rental information or browse the specialist shop.', 'Prüft die aktuellen Verleihinformationen oder besucht den spezialisierten Shop.', 'Consultad la información actual de alquiler o visitad la tienda especializada.', 'Bekijk de actuele verhuurinformatie of bezoek de gespecialiseerde shop.', 'Se aktuell hyrinformation eller besök specialbutiken.'), href: 'https://tarifasurfclub.com/kite-equipment-rental', label: l('View equipment rental', 'Materialverleih ansehen', 'Ver alquiler de material', 'Bekijk materiaalverhuur', 'Se uthyrning') },
  related: [],
  closing: { title: l('Tell us what you need for the water', 'Sagt uns, was ihr auf dem Wasser braucht', 'Contadnos qué necesitáis para el agua', 'Vertel ons wat jullie op het water nodig hebben', 'Berätta vad ni behöver på vattnet'), text: l('We connect your request with Tarifa Surf Club and keep it aligned with your travel dates.', 'Wir verbinden eure Anfrage mit dem Tarifa Surf Club und stimmen sie auf eure Reisedaten ab.', 'Conectamos vuestra solicitud con Tarifa Surf Club y la ajustamos a las fechas.', 'Wij verbinden jullie aanvraag met Tarifa Surf Club en stemmen die af op de reisdata.', 'Vi kopplar er fråga till Tarifa Surf Club och samordnar den med resedatumen.'), contactLabel: common.contactLabel, contactMessage: l('Hello AMARA, we are interested in kite equipment in Tarifa. Travel dates: / Guests: / Kite level: / Rental or purchase:', 'Hallo AMARA, wir interessieren uns für Kitematerial in Tarifa. Reisedaten: / Gäste: / Kite-Level: / Leihen oder kaufen:', 'Hola AMARA, nos interesa material de kite en Tarifa. Fechas: / Huéspedes: / Nivel: / Alquiler o compra:', 'Hallo AMARA, we hebben interesse in kitemateriaal in Tarifa. Reisdata: / Gasten: / Niveau: / Huren of kopen:', 'Hej AMARA, vi är intresserade av kiteutrustning i Tarifa. Resedatum: / Gäster: / Nivå: / Hyra eller köpa:') }
};

const wind: TarifaKitesurfSpokeContent = {
  id: 'wind-spots-safety', token: 'tarifa_wind_kitesurfing_authority',
  seo: seo('2026-09-02-tarifa-kitesurf-wind-spots-v1.0', l('Tarifa Kitesurf Wind, Spots & Safety | AMARA', 'Tarifa Kitesurfen: Wind, Spots & Sicherheit | AMARA', 'Kitesurf en Tarifa: viento, spots y seguridad | AMARA', 'Kitesurfen Tarifa: wind, spots & veiligheid | AMARA', 'Kitesurfing Tarifa: vind, spots & säkerhet | AMARA'), l('Understand Levante, Poniente, kite areas and daily safety decisions before your Tarifa session, with current local guidance taking priority.', 'Versteht Levante, Poniente, Kitezonen und tägliche Sicherheitsentscheidungen vor eurer Session in Tarifa. Aktuelle lokale Hinweise haben Vorrang.', 'Entended Levante, Poniente, zonas de kite y decisiones diarias de seguridad antes de vuestra sesión. La información local vigente tiene prioridad.', 'Begrijp Levante, Poniente, kitegebieden en dagelijkse veiligheidskeuzes voor jullie sessie. Actueel lokaal advies gaat voor.', 'Förstå Levante, Poniente, kiteområden och dagliga säkerhetsbeslut före sessionen. Aktuella lokala råd gäller först.')),
  navLabel: l('Wind, spots & safety', 'Wind, Spots & Sicherheit', 'Viento, spots y seguridad', 'Wind, spots & veiligheid', 'Vind, spots & säkerhet'),
  hero: { eyebrow: l('Conditions in Tarifa', 'Bedingungen in Tarifa', 'Condiciones en Tarifa', 'Omstandigheden in Tarifa', 'Förhållanden i Tarifa'), title: l('Wind, spots and safety', 'Wind, Spots und Sicherheit', 'Viento, spots y seguridad', 'Wind, spots en veiligheid', 'Vind, spots och säkerhet'), subtitle: l('Use the forecast for orientation and local guidance for the session.', 'Nutzt die Vorhersage zur Orientierung und lokale Hinweise für die Session.', 'Usad la previsión para orientaros y la información local para la sesión.', 'Gebruik de verwachting als oriëntatie en lokaal advies voor de sessie.', 'Använd prognosen för orientering och lokala råd för sessionen.'), lead: l('Tarifa’s two familiar wind systems are Levante from the east and Poniente from the west, but direction alone never decides whether a session fits. Strength, gusts, tide, swell, local effects, seasonal zones and your own level all matter. There is no single beach that is always right for beginners. Check a live forecast, current flags and local rules, then confirm the spot and timing with a qualified school or experienced local professional before entering the water.', 'Tarifas zwei bekannte Windsysteme sind Levante aus Osten und Poniente aus Westen, doch die Richtung allein entscheidet nie, ob eine Session passt. Stärke, Böen, Gezeiten, Wellengang, lokale Effekte, saisonale Zonen und euer Level wirken zusammen. Es gibt keinen Strand, der für Anfänger immer passt. Prüft Live-Vorhersage, aktuelle Flaggen und lokale Regeln und bestätigt Spot und Zeitpunkt vor dem Start mit einer qualifizierten Schule oder erfahrenen Fachleuten vor Ort.', 'Los dos sistemas conocidos de Tarifa son Levante del este y Poniente del oeste, pero la dirección por sí sola nunca decide si una sesión es adecuada. Fuerza, rachas, marea, oleaje, efectos locales, zonas estacionales y vuestro nivel cuentan juntos. No hay una playa siempre apropiada para principiantes. Consultad la previsión en directo, banderas y normas, y confirmad spot y horario con una escuela cualificada o un profesional local antes de entrar.', 'De twee bekende windsystemen van Tarifa zijn Levante uit het oosten en Poniente uit het westen, maar richting alleen bepaalt nooit of een sessie past. Kracht, vlagen, getij, deining, lokale effecten, seizoenszones en jullie niveau tellen samen. Er is geen strand dat altijd geschikt is voor beginners. Bekijk live verwachting, vlaggen en regels en bevestig spot en tijd bij een gekwalificeerde school of lokale professional voor jullie het water opgaan.', 'Tarifas två välkända vindsystem är Levante från öster och Poniente från väster, men riktningen ensam avgör aldrig om en session passar. Styrka, byar, tidvatten, dyning, lokala effekter, säsongszoner och er nivå samverkar. Ingen strand passar alltid nybörjare. Kontrollera liveprognos, flaggor och lokala regler och bekräfta plats och tid med en kvalificerad skola eller lokal yrkesperson innan ni går ut.'), imageAlt: common.imageAlt },
  facts: [
    { id: 'levante', label: l('Levante', 'Levante', 'Levante', 'Levante', 'Levante'), value: l('Easterly · often offshore', 'Östlich · häufig ablandig', 'De este · a menudo de tierra', 'Oostelijk · vaak aflandig', 'Ostlig · ofta frånlandsvind') },
    { id: 'poniente', label: l('Poniente', 'Poniente', 'Poniente', 'Poniente', 'Poniente'), value: l('Westerly · generally more onshore', 'Westlich · meist stärker auflandig', 'De oeste · generalmente más de mar', 'Westelijk · doorgaans meer aanlandig', 'Västlig · generellt mer pålandsvind') },
    { id: 'rule', label: l('Daily rule', 'Tägliche Regel', 'Regla diaria', 'Dagelijkse regel', 'Daglig regel'), value: l('Forecast, flags and zones', 'Vorhersage, Flaggen und Zonen', 'Previsión, banderas y zonas', 'Verwachting, vlaggen en zones', 'Prognos, flaggor och zoner') }
  ],
  sections: [
    { id: 'winds', eyebrow: l('Two wind systems', 'Zwei Windsysteme', 'Dos sistemas de viento', 'Twee windsystemen', 'Två vindsystem'), title: l('Levante and Poniente change the day', 'Levante und Poniente verändern den Tag', 'Levante y Poniente cambian el día', 'Levante en Poniente veranderen de dag', 'Levante och Poniente förändrar dagen'), paragraphs: [l('Levante can be powerful, gusty and offshore or cross-offshore on exposed sections. Flat water may look inviting while the direction increases the consequence of drift or equipment trouble.', 'Levante kann kräftig, böig und an offenen Abschnitten ablandig oder schräg ablandig sein. Flaches Wasser kann einladend wirken, während die Richtung die Folgen von Abdrift oder Materialproblemen erhöht.', 'El Levante puede ser fuerte, racheado y de tierra o cruzado de tierra en zonas expuestas. El agua plana puede parecer atractiva mientras la dirección aumenta las consecuencias de una deriva o avería.', 'Levante kan krachtig, vlagerig en op open stukken aflandig of schuin aflandig zijn. Vlak water kan aantrekkelijk lijken terwijl de richting de gevolgen van afdrijven of materiaalpech vergroot.', 'Levante kan vara kraftig, byig och frånlands- eller snett frånlandsvind på öppna sträckor. Platt vatten kan se lockande ut medan riktningen ökar följderna av drift eller utrustningsproblem.'), l('Poniente is generally more onshore and can feel steadier, yet tide, swell, crowds and local effects still change what is suitable. Treat both winds as a starting point for a current assessment.', 'Poniente ist meist stärker auflandig und kann gleichmäßiger wirken, doch Gezeiten, Wellengang, Betrieb und lokale Effekte verändern weiterhin die Eignung. Betrachtet beide Winde als Ausgangspunkt für eine aktuelle Einschätzung.', 'El Poniente suele ser más de mar y puede sentirse más estable, pero marea, oleaje, afluencia y efectos locales siguen cambiando la idoneidad. Tomad ambos vientos como punto de partida para una valoración actual.', 'Poniente is doorgaans meer aanlandig en kan gelijkmatiger voelen, maar getij, deining, drukte en lokale effecten blijven bepalend. Zie beide winden als beginpunt voor een actuele beoordeling.', 'Poniente är generellt mer pålandsvind och kan kännas jämnare, men tidvatten, dyning, trängsel och lokala effekter påverkar fortfarande. Se båda vindarna som startpunkt för en aktuell bedömning.') ] },
    { id: 'spot', eyebrow: l('Spot decision', 'Spot-Entscheidung', 'Elección del spot', 'Spotkeuze', 'Val av spot'), title: l('The right beach changes with the conditions', 'Der passende Strand wechselt mit den Bedingungen', 'La playa adecuada cambia con las condiciones', 'Het juiste strand verandert met de omstandigheden', 'Rätt strand ändras med förhållandena'), paragraphs: [l('Seasonal zoning and current rules can change where launching is permitted. Beach access, swimmer areas and safety flags on site take priority over an evergreen online recommendation.', 'Saisonale Zonen und aktuelle Regeln können verändern, wo Starts erlaubt sind. Strandzugang, Badebereiche und Sicherheitsflaggen vor Ort haben Vorrang vor einer dauerhaften Online-Empfehlung.', 'Las zonas estacionales y las normas vigentes pueden cambiar dónde se permite salir. Accesos, áreas de baño y banderas tienen prioridad sobre cualquier recomendación permanente en internet.', 'Seizoenszones en actuele regels kunnen veranderen waar starten mag. Toegang, zwemzones en veiligheidsvlaggen ter plaatse gaan voor een blijvend online advies.', 'Säsongszoner och aktuella regler kan ändra var start är tillåten. Tillträde, badzoner och säkerhetsflaggor på plats gäller före en tidlös rekommendation online.'), l('For lessons, let the school select the location. For independent riding, combine reliable experience with live checks and local confirmation before rigging.', 'Bei Kursen wählt die Schule den Ort. Beim selbstständigen Fahren verbindet ihr verlässliche Erfahrung mit Live-Checks und lokaler Bestätigung vor dem Aufbau.', 'En clases, dejad que la escuela elija el lugar. Para navegar por vuestra cuenta, combinad experiencia sólida, comprobaciones en directo y confirmación local antes de montar.', 'Laat bij lessen de school de plek kiezen. Combineer bij zelfstandig varen betrouwbare ervaring met live checks en lokale bevestiging voor het optuigen.', 'Låt skolan välja plats för lektioner. Vid självständig åkning kombinerar ni gedigen erfarenhet med livekontroller och lokal bekräftelse innan riggning.') ] }
  ],
  partner: { title: l('Confirm the day with local professionals', 'Den Tag mit lokalen Profis abstimmen', 'Confirmar el día con profesionales locales', 'Stem de dag af met lokale professionals', 'Bekräfta dagen med lokala proffs'), text: l('Tarifa Surf Club can assess the current conditions for its lessons, camps and equipment customers.', 'Der Tarifa Surf Club beurteilt die aktuellen Bedingungen für Kurse, Camps und Materialkunden.', 'Tarifa Surf Club valora las condiciones actuales para cursos, camps y clientes de material.', 'Tarifa Surf Club beoordeelt de actuele omstandigheden voor lessen, camps en materiaalklanten.', 'Tarifa Surf Club bedömer dagens förhållanden för kurser, camps och utrustningskunder.'), href: 'https://tarifasurfclub.com/windvorhersage-tarifa', label: l('View wind and weather', 'Wind & Wetter ansehen', 'Ver viento y tiempo', 'Bekijk wind en weer', 'Se vind och väder') },
  related: [],
  closing: { title: l('Let the conditions shape the session', 'Lasst die Bedingungen die Session bestimmen', 'Dejad que las condiciones definan la sesión', 'Laat de omstandigheden de sessie bepalen', 'Låt förhållandena forma sessionen'), text: l('For lessons, camp or equipment, tell us your level and dates. We connect you with Tarifa Surf Club for the current decision.', 'Für Kurse, Camp oder Material nennt uns Level und Reisedaten. Wir verbinden euch für die aktuelle Entscheidung mit dem Tarifa Surf Club.', 'Para cursos, camp o material, indicad nivel y fechas. Os conectamos con Tarifa Surf Club para la decisión actual.', 'Deel voor lessen, camp of materiaal jullie niveau en data. Wij verbinden jullie met Tarifa Surf Club voor de actuele keuze.', 'För kurs, camp eller utrustning anger ni nivå och datum. Vi kopplar er till Tarifa Surf Club för dagens beslut.'), contactLabel: common.contactLabel, contactMessage: l('Hello AMARA, we are planning kitesurfing in Tarifa. Travel dates: / Guests: / Kite level: / Question about wind or spots:', 'Hallo AMARA, wir planen Kitesurfen in Tarifa. Reisedaten: / Gäste: / Kite-Level: / Frage zu Wind oder Spots:', 'Hola AMARA, estamos organizando kitesurf en Tarifa. Fechas: / Huéspedes: / Nivel: / Pregunta sobre viento o spots:', 'Hallo AMARA, we plannen kitesurfen in Tarifa. Reisdata: / Gasten: / Niveau: / Vraag over wind of spots:', 'Hej AMARA, vi planerar kitesurfing i Tarifa. Resedatum: / Gäster: / Nivå: / Fråga om vind eller spots:') }
};

const relatedMap: Record<TarifaKitesurfSpokeId, LinkToken[]> = {
  'kite-school': ['tarifa_kitecamp', 'tarifa_kite_equipment', 'tarifa_wind_kitesurfing_authority'],
  kitecamp: ['tarifa_kite_school', 'tarifa_wind_kitesurfing_authority', 'tarifa_kite_equipment'],
  equipment: ['tarifa_wind_kitesurfing_authority', 'tarifa_kite_school', 'tarifa_kitecamp'],
  'wind-spots-safety': ['tarifa_kite_school', 'tarifa_kitecamp', 'tarifa_kite_equipment']
};

const relatedText: Record<TarifaKitesurfSpokeId, Partial<Record<LinkToken, LocalizedKiteText>>> = {
  'kite-school': {
    tarifa_kitecamp: l('Give coaching several days when you want more time to progress.', 'Gebt der Betreuung mehrere Tage, wenn ihr mehr Zeit für Fortschritte möchtet.', 'Dad varios días a las clases si queréis más tiempo para progresar.', 'Geef coaching meerdere dagen als jullie meer tijd voor progressie willen.', 'Ge coachingen flera dagar när ni vill ha mer tid att utvecklas.'),
    tarifa_kite_equipment: l('Match rental equipment to the level established for your lessons.', 'Stimmt Leihmaterial auf das Level eurer Kurse ab.', 'Ajustad el material de alquiler al nivel definido para las clases.', 'Stem huurmateriaal af op het niveau van jullie lessen.', 'Anpassa hyrutrustning till nivån för era lektioner.'),
    tarifa_wind_kitesurfing_authority: l('Understand why the school confirms beach and timing each day.', 'Versteht, warum die Schule Strand und Uhrzeit täglich bestätigt.', 'Entended por qué la escuela confirma playa y horario cada día.', 'Lees waarom de school strand en tijd elke dag bevestigt.', 'Förstå varför skolan bekräftar strand och tid varje dag.')
  },
  kitecamp: {
    tarifa_kite_school: l('See how course format follows your starting level and goals.', 'Seht, wie Kursformat, Ausgangslevel und Ziele zusammenpassen.', 'Ved cómo el formato del curso responde a vuestro nivel y objetivos.', 'Bekijk hoe lesvorm, startniveau en doelen samenhangen.', 'Se hur kursformatet följer startnivå och mål.'),
    tarifa_wind_kitesurfing_authority: l('Use a longer stay well by understanding Tarifa’s changing wind windows.', 'Nutzt einen längeren Aufenthalt besser, wenn ihr Tarifas wechselnde Windfenster versteht.', 'Aprovechad mejor varios días entendiendo las ventanas de viento de Tarifa.', 'Benut meerdaags verblijf beter door Tarifas wisselende windvensters te begrijpen.', 'Använd flera dagar bättre genom att förstå Tarifas skiftande vindfönster.'),
    tarifa_kite_equipment: l('Travel light and arrange the setup that suits the camp sessions.', 'Reist leicht und organisiert das Setup passend zu den Camp-Sessions.', 'Viajad ligeros y organizad el equipo adecuado para las sesiones del camp.', 'Reis licht en regel de setup die bij de campsessies past.', 'Res lätt och ordna en setup som passar campets pass.')
  },
  equipment: {
    tarifa_wind_kitesurfing_authority: l('Connect board and kite choice with the conditions you actually meet.', 'Verbindet Board- und Kitewahl mit den Bedingungen, die ihr wirklich vorfindet.', 'Relacionad la elección de tabla y kite con las condiciones reales.', 'Koppel board- en kitekeuze aan de omstandigheden die jullie echt treffen.', 'Koppla val av bräda och kite till de faktiska förhållandena.'),
    tarifa_kite_school: l('Add professional coaching when a new setup comes with a new skill.', 'Nehmt professionelle Betreuung dazu, wenn ein neues Setup neue Technik verlangt.', 'Añadid clases profesionales cuando un equipo nuevo requiera otra técnica.', 'Voeg professionele coaching toe wanneer een nieuwe setup nieuwe techniek vraagt.', 'Lägg till professionell coaching när en ny setup kräver ny teknik.'),
    tarifa_kitecamp: l('Combine equipment support with several coordinated days on the water.', 'Verbindet Materialunterstützung mit mehreren abgestimmten Tagen auf dem Wasser.', 'Combinad apoyo con el material y varios días coordinados en el agua.', 'Combineer materiaalondersteuning met meerdere afgestemde dagen op het water.', 'Kombinera utrustningsstöd med flera samordnade dagar på vattnet.')
  },
  'wind-spots-safety': {
    tarifa_kite_school: l('Let qualified instructors turn the day’s conditions into a suitable lesson.', 'Lasst qualifizierte Lehrer aus den Tagesbedingungen einen passenden Kurs machen.', 'Dejad que instructores cualificados conviertan las condiciones en una clase adecuada.', 'Laat gekwalificeerde instructeurs de omstandigheden vertalen naar een passende les.', 'Låt kvalificerade instruktörer göra dagens förhållanden till en lämplig lektion.'),
    tarifa_kitecamp: l('A multi-day window gives changing wind more room in your programme.', 'Ein mehrtägiges Zeitfenster gibt wechselndem Wind mehr Raum im Programm.', 'Varios días dan más margen al viento cambiante dentro del programa.', 'Meerdere dagen geven wisselende wind meer ruimte in het programma.', 'Flera dagar ger skiftande vind mer utrymme i programmet.'),
    tarifa_kite_equipment: l('Choose the final setup only after strength and direction are current.', 'Wählt das endgültige Setup erst mit aktueller Windstärke und -richtung.', 'Elegid el equipo final cuando fuerza y dirección sean actuales.', 'Kies de definitieve setup pas met actuele windkracht en richting.', 'Välj slutlig setup först med aktuell vindstyrka och riktning.')
  }
};

const all = { 'kite-school': school, kitecamp: camp, equipment, 'wind-spots-safety': wind };

for (const content of Object.values(all)) {
  content.related = relatedMap[content.id].map((token) => {
    const target = Object.values(all).find((item) => item.token === token)!;
    return {
      token,
      label: target.navLabel,
      text: relatedText[content.id][token]!
    };
  });
}

export const tarifaKitesurfSpokeContent: Record<TarifaKitesurfSpokeId, TarifaKitesurfSpokeContent> = all;
