import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';
import type { ParkingGuideLocale, ParkingGuideSection } from './parkingGuideContent';

type Localized = Record<AmaraLanguage, string>;
const l = (en: string, de: string, es: string, nl: string, sv: string): Localized => ({ en, de, es, nl, sv });
const langs: AmaraLanguage[] = ['en', 'de', 'es', 'nl', 'sv'];
const article = { datePublished: '2026-08-21', dateModified: '2026-08-21', authorName: 'Robert Sebastian Böhmer', authorType: 'Person' as const, authorSlug: 'amara-about-us' };

export const tarifaParkingSeo: AmaraAuthoringSeo = {
  version: '2026-08-21-tarifa-parking-v1.1', pageType: 'A', entityKey: 'amara-brand', article,
  languages: {
    en: { title: 'Parking in Tarifa: Old Town, Beaches & AMARA Garage', description: 'My host guide to parking in Tarifa: town and old town, beach days, July and August pressure and the included AMARA underground space.', robots: 'index, follow', canonical: 'auto' },
    de: { title: 'Parken in Tarifa: Altstadt, Strände & AMARA-Tiefgarage', description: 'Mein Gastgeber-Guide zum Parken in Tarifa: Stadt, Altstadt, Strandtage, Juli und August sowie der enthaltene AMARA-Tiefgaragenplatz.', robots: 'index, follow', canonical: 'auto' },
    es: { title: 'Aparcar en Tarifa: casco antiguo, playas y garaje AMARA', description: 'Planificad el aparcamiento en Tarifa: ciudad y casco antiguo, playas, presión de julio y agosto, equipaje, reglas actuales y garaje AMARA.', robots: 'index, follow', canonical: 'auto' },
    nl: { title: 'Parkeren in Tarifa: oude stad, stranden & AMARA-garage', description: 'Plan parkeren in Tarifa per context: stad en oude kern, stranddagen, drukte in juli en augustus, bagage, actuele regels en AMARA-garage.', robots: 'index, follow', canonical: 'auto' },
    sv: { title: 'Parkering i Tarifa: gamla stan, stränder & AMARA-garage', description: 'Planera parkering i Tarifa per sammanhang: stad och gamla stan, stranddagar, tryck i juli och augusti, bagage, aktuella regler och AMARA-garage.', robots: 'index, follow', canonical: 'auto' }
  }
};

const navLabel = l('Parking & Accessibility', 'Parken & Erreichbarkeit', 'Aparcamiento y acceso', 'Parkeren & toegankelijkheid', 'Parkering & tillgänglighet');
const hero = {
  eyebrow: l('Parking & access · Tarifa', 'Parken & Erreichbarkeit · Tarifa', 'Aparcamiento y acceso · Tarifa', 'Parkeren & toegankelijkheid · Tarifa', 'Parkering & tillgänglighet · Tarifa'),
  title: l('Tarifa parking starts with one question: town or beach?', 'Parken in Tarifa beginnt mit einer Frage: Stadt oder Strand?', 'Aparcar en Tarifa empieza con una pregunta: ¿ciudad o playa?', 'Parkeren in Tarifa begint met één vraag: stad of strand?', 'Parkering i Tarifa börjar med en fråga: stad eller strand?'),
  standfirst: l(
    'I always ask guests one question first: are you driving into town or spending the day at a beach such as Los Lances, Valdevaqueros or Bolonia? Those are completely different parking plans. In July and August I experience the public parking pressure as exceptionally high. That is exactly when our underground space at AMARA Family & Surf becomes a real advantage: your car has a place at the accommodation. For the old town, port and beaches, we still plan each journey separately.',
    'Ich stelle meinen Gästen zuerst immer eine Frage: Fahrt ihr in die Stadt oder verbringt ihr den Tag an einem Strand wie Los Lances, Valdevaqueros oder Bolonia? Das sind völlig verschiedene Parkpläne. Im Juli und August erlebe ich den öffentlichen Parkdruck als außergewöhnlich hoch. Genau dann ist unser Tiefgaragenplatz bei AMARA Family & Surf ein echter Vorteil: Euer Auto hat an der Unterkunft seinen Platz. Für Altstadt, Hafen und Strände planen wir trotzdem jede Fahrt separat.',
    'Siempre hago primero una pregunta a mis huéspedes: ¿vais a la ciudad o pasaréis el día en una playa como Los Lances, Valdevaqueros o Bolonia? Son planes de aparcamiento completamente distintos. En julio y agosto vivo una presión excepcional en el aparcamiento público. Precisamente entonces nuestra plaza subterránea en AMARA Family & Surf es una ventaja real: el coche tiene sitio en el alojamiento. Para casco antiguo, puerto y playas planificamos cada trayecto por separado.',
    'Ik stel gasten altijd eerst één vraag: rijden jullie naar de stad of brengen jullie de dag door bij Los Lances, Valdevaqueros of Bolonia? Dat zijn totaal verschillende parkeerplannen. In juli en augustus ervaar ik de druk op openbare parkeerplaatsen als uitzonderlijk hoog. Juist dan is onze ondergrondse plek bij AMARA Family & Surf een echt voordeel: de auto heeft een plek bij het verblijf. Voor oude stad, haven en stranden plannen we elke rit apart.',
    'Jag ställer alltid gästerna en fråga först: ska ni in till stan eller tillbringa dagen vid Los Lances, Valdevaqueros eller Bolonia? Det är helt olika parkeringsplaner. I juli och augusti upplever jag trycket på offentlig parkering som exceptionellt högt. Just då är vår underjordiska plats vid AMARA Family & Surf en verklig fördel: bilen har sin plats vid boendet. För gamla stan, hamnen och stränderna planerar vi varje resa separat.'
  ),
  note: l('The July and August advice comes from my own experience as a host. I will send the exact garage access with your arrival information.', 'Die Einschätzung zu Juli und August stammt aus meiner eigenen Gastgebererfahrung. Die genaue Garagenzufahrt bekommt ihr mit euren Ankunftsinformationen.', 'El consejo sobre julio y agosto nace de mi propia experiencia como anfitrión. Recibiréis el acceso exacto al garaje con la información de llegada.', 'Het advies over juli en augustus komt uit mijn eigen ervaring als host. De exacte garagetoegang krijgen jullie bij de aankomstinformatie.', 'Rådet om juli och augusti bygger på min egen erfarenhet som värd. Exakt garageinfart får ni med ankomstinformationen.'),
  updated: l('Personally updated by Robert · August 2026', 'Von Robert persönlich aktualisiert · August 2026', 'Actualizado personalmente por Robert · agosto de 2026', 'Persoonlijk bijgewerkt door Robert · augustus 2026', 'Personligen uppdaterad av Robert · augusti 2026')
};

const facts = [
  { label: l('Two parking worlds', 'Zwei Parkwelten', 'Dos mundos', 'Twee parkeerwerelden', 'Två parkeringsvärldar'), value: l('Town and old town ≠ beach destination', 'Stadt und Altstadt ≠ Strandziel', 'Ciudad y casco antiguo ≠ playa', 'Stad en oude kern ≠ strand', 'Stad och gamla stan ≠ strand') },
  { label: l('Peak pressure', 'Spitzendruck', 'Presión máxima', 'Piekdrukte', 'Högsta tryck'), value: l('July and August require the most caution', 'Juli und August brauchen die meiste Vorsicht', 'Julio y agosto exigen más previsión', 'Juli en augustus vragen de meeste planning', 'Juli och augusti kräver mest planering') },
  { label: l('At AMARA', 'Bei AMARA', 'En AMARA', 'Bij AMARA', 'Hos AMARA'), value: l('An underground guest space is currently included', 'Ein Tiefgaragenplatz ist aktuell enthalten', 'Actualmente se incluye plaza de garaje', 'Een ondergrondse plek is momenteel inbegrepen', 'En underjordisk gästplats ingår för närvarande') },
  { label: l('Live boundary', 'Live-Grenze', 'Límite actual', 'Live-grens', 'Live-gräns'), value: l('Zones, machines and beach access can change', 'Zonen, Automaten und Strandzufahrt können wechseln', 'Zonas, parquímetros y acceso pueden cambiar', 'Zones, automaten en strandtoegang kunnen veranderen', 'Zoner, automater och strandvägar kan ändras') }
] as const;

const sections: Array<{ id: ParkingGuideSection['id']; eyebrow: Localized; title: Localized; paragraphs: Localized[] }> = [
  { id: 'parking-reality', eyebrow: l('01 · Parking reality', '01 · Die Parkrealität', '01 · La realidad', '01 · De realiteit', '01 · Verkligheten'), title: l('Tarifa is a network of parking contexts', 'Tarifa ist ein Netz aus Parkkontexten', 'Tarifa es una red de contextos', 'Tarifa is een netwerk van parkeercontexten', 'Tarifa är ett nät av parkeringssammanhang'), paragraphs: [
    l('Town, old town, port and the individual beach areas are not interchangeable destinations. A place that works for an evening in the old town says little about a windy beach day farther west.', 'Stadt, Altstadt, Hafen und einzelne Strandbereiche sind keine austauschbaren Ziele. Ein Platz für den Altstadtabend sagt wenig über einen windigen Strandtag weiter westlich.', 'Ciudad, casco antiguo, puerto y playas no son destinos intercambiables. Una opción para la noche en el centro dice poco sobre un día de playa al oeste.', 'Stad, oude kern, haven en afzonderlijke stranden zijn geen uitwisselbare doelen. Een plek voor een avond in de oude stad zegt weinig over een stranddag westelijker.', 'Stad, gamla stan, hamn och enskilda stränder är inte utbytbara mål. En plats för en kväll i gamla stan säger lite om en stranddag längre västerut.'),
    l('That is why I never give one blanket parking answer for all of Tarifa. Tell me the destination first; for a specific beach, I then check the access and parking situation for that beach.', 'Deshalb gebe ich für Tarifa nie eine pauschale Parkantwort. Nennt mir zuerst euer Ziel; für einen bestimmten Strand schaue ich anschließend auf die Zufahrt und Parksituation genau dort.', 'Por eso nunca doy una respuesta general para toda Tarifa. Decidme primero el destino; para una playa concreta reviso después su acceso y aparcamiento.', 'Daarom geef ik nooit één algemeen parkeerantwoord voor heel Tarifa. Noem eerst jullie bestemming; voor een specifiek strand kijk ik daarna naar de toegang en parkeersituatie daar.', 'Därför ger jag aldrig ett generellt parkeringssvar för hela Tarifa. Berätta målet först; för en viss strand kontrollerar jag sedan tillfart och parkering just där.')
  ]},
  { id: 'arrival-luggage', eyebrow: l('02 · Arrival and luggage', '02 · Ankunft und Gepäck', '02 · Llegada y equipaje', '02 · Aankomst en bagage', '02 · Ankomst och bagage'), title: l('A private garage changes the accommodation arrival', 'Eine private Garage verändert die Ankunft', 'Un garaje privado cambia la llegada', 'Een privégarage verandert de aankomst', 'Ett privat garage förändrar ankomsten'), paragraphs: [
    l('At AMARA Family & Surf, an underground space is included for our guests. Before you travel, I will explain the entrance and access so that you know what to expect with your vehicle.', 'Bei AMARA Family & Surf ist für unsere Gäste ein Tiefgaragenplatz enthalten. Vor eurer Reise erkläre ich euch Einfahrt und Zugang, damit ihr mit eurem Fahrzeug genau wisst, was euch erwartet.', 'En AMARA Family & Surf se incluye una plaza subterránea para nuestros huéspedes. Antes del viaje os explicaré la entrada y el acceso para que sepáis qué esperar con vuestro vehículo.', 'Bij AMARA Family & Surf is een ondergrondse plek voor onze gasten inbegrepen. Voor vertrek leg ik ingang en toegang uit, zodat jullie weten wat je met de auto kunt verwachten.', 'Vid AMARA Family & Surf ingår en underjordisk plats för våra gäster. Före resan förklarar jag infart och tillträde så att ni vet vad ni kan förvänta er med bilen.'),
    l('The garage solves the parking question at your accommodation — and in high season that is worth a great deal. It does not automatically solve a trip to the old town or a day at the beach, so I treat those as separate plans.', 'Die Garage löst die Parkfrage an eurer Unterkunft – und in der Hochsaison ist das sehr viel wert. Sie löst aber nicht automatisch die Fahrt in die Altstadt oder den Strandtag; diese Pläne behandle ich deshalb separat.', 'El garaje resuelve el aparcamiento en el alojamiento, algo muy valioso en temporada alta. No resuelve automáticamente una visita al casco antiguo o un día de playa; por eso los planifico aparte.', 'De garage lost het parkeren bij jullie verblijf op — en dat is in het hoogseizoen veel waard. Hij lost niet automatisch een rit naar de oude stad of een stranddag op; die plan ik daarom apart.', 'Garaget löser parkeringen vid boendet — och under högsäsong är det mycket värt. Det löser inte automatiskt en tur till gamla stan eller en stranddag, så jag planerar dem separat.')
  ]},
  { id: 'during-stay', eyebrow: l('03 · During your stay', '03 · Während des Aufenthalts', '03 · Durante la estancia', '03 · Tijdens het verblijf', '03 · Under vistelsen'), title: l('Leave the car for town; use it selectively for the coast', 'Für die Stadt stehen lassen, für die Küste gezielt nutzen', 'Dejadlo para la ciudad; usadlo con criterio para la costa', 'Laat hem staan voor de stad; gebruik hem gericht voor de kust', 'Låt bilen stå för staden; använd den selektivt för kusten'), paragraphs: [
    l('A stay near La Marina can support walking into town and the old town while the car remains in its space. That can be especially valuable when public parking pressure is high.', 'Ein Aufenthalt bei La Marina ermöglicht Wege in Stadt und Altstadt zu Fuß, während das Auto stehen bleibt. Das ist besonders bei hohem öffentlichen Parkdruck wertvoll.', 'Una estancia cerca de La Marina permite ir andando a ciudad y casco antiguo mientras el coche queda guardado. Es especialmente valioso con alta presión.', 'Een verblijf bij La Marina maakt lopen naar stad en oude kern mogelijk terwijl de auto blijft staan. Dat is vooral waardevol bij hoge druk.', 'Ett boende nära La Marina kan möjliggöra promenad till stad och gamla stan medan bilen står kvar. Det är särskilt värdefullt vid högt tryck.'),
    l('Beach days are a different decision. Choose the beach first, then check its current access, nature-area rules, wind and seasonal operation rather than carrying one town-parking rule along the coast.', 'Strandtage sind eine andere Entscheidung. Wählt zuerst den Strand und prüft dann Zufahrt, Naturraumregeln, Wind und Saisonbetrieb statt eine Stadtparkregel mitzunehmen.', 'Los días de playa son otra decisión. Elegid primero la playa y comprobad acceso, reglas naturales, viento y temporada.', 'Stranddagen zijn een andere keuze. Kies eerst het strand en controleer toegang, natuurregels, wind en seizoen.', 'Stranddagar är ett annat beslut. Välj stranden först och kontrollera tillfart, naturregler, vind och säsong.')
  ]},
  { id: 'last-mile', eyebrow: l('04 · Last mile and accessibility', '04 · Letzter Weg und Zugänglichkeit', '04 · Último tramo y accesibilidad', '04 · Laatste route en toegankelijkheid', '04 · Sista sträckan och tillgänglighet'), title: l('A garage space does not describe the whole route', 'Ein Garagenplatz beschreibt nicht den ganzen Weg', 'Una plaza de garaje no describe toda la ruta', 'Een garageplek beschrijft niet de hele route', 'En garageplats beskriver inte hela vägen'), paragraphs: [
    l('For a comfortable arrival I look at the whole route with you: garage level, lift or stairs, kerbs and the building entrance. A private space is useful, but it does not automatically make every metre step-free.', 'Für eine angenehme Ankunft schaue ich mit euch auf den ganzen Weg: Garagenebene, Aufzug oder Stufen, Bordsteine und Hauseingang. Ein privater Platz ist hilfreich, macht aber nicht automatisch jeden Meter stufenfrei.', 'Para una llegada cómoda reviso con vosotros toda la ruta: nivel del garaje, ascensor o escaleras, bordillos y entrada. Una plaza privada ayuda, pero no convierte automáticamente todo el recorrido en accesible.', 'Voor een comfortabele aankomst kijk ik met jullie naar de hele route: garageniveau, lift of trappen, stoepen en ingang. Een privéplek helpt, maar maakt niet automatisch elke meter trapvrij.', 'För en bekväm ankomst går jag igenom hela vägen med er: garagenivå, hiss eller trappor, kanter och entré. En privat plats hjälper, men gör inte automatiskt varje meter stegfri.'),
    l('Guests with mobility needs should confirm the complete garage-to-door route. General PMR parking rights never prove that a particular accommodation route is suitable.', 'Bei Mobilitätsbedarf bestätigt ihr die vollständige Garage-zur-Tür-Route. Allgemeine PMR-Rechte beweisen nie die Eignung eines konkreten Objektwegs.', 'Si hay necesidades de movilidad, confirmad toda la ruta garaje-puerta. Los derechos PMR no demuestran que una ruta concreta sea adecuada.', 'Bevestig bij mobiliteitsbehoeften de volledige garage-tot-deurroute. PMR-rechten bewijzen geen geschikte woningroute.', 'Vid rörelsebehov ska hela garage-till-dörr-rutten bekräftas. PMR-rättigheter bevisar inte att en viss boenderutt passar.')
  ]},
  { id: 'seasonal-rules', eyebrow: l('05 · Peak season and current rules', '05 · Hochsaison und aktuelle Regeln', '05 · Temporada alta y reglas actuales', '05 · Hoogseizoen en actuele regels', '05 · Högsäsong och aktuella regler'), title: l('July and August need a different expectation', 'Juli und August brauchen eine andere Erwartung', 'Julio y agosto requieren otra expectativa', 'Juli en augustus vragen een andere verwachting', 'Juli och augusti kräver en annan förväntan'), paragraphs: [
    l('I will say it plainly: July and August are the hardest months for public parking in Tarifa. I would not call parking literally impossible, but I plan every trip more carefully then and value the private garage enormously.', 'Ich sage es ganz offen: Juli und August sind in Tarifa die schwierigsten Monate für öffentliches Parken. Ich würde Parken nicht wörtlich „unmöglich“ nennen, plane dann aber jede Fahrt sorgfältiger – und schätze die private Garage enorm.', 'Lo digo claramente: julio y agosto son los meses más difíciles para aparcar en la vía pública en Tarifa. No diría que es literalmente imposible, pero planifico cada trayecto con más cuidado y valoro muchísimo el garaje privado.', 'Ik zeg het eerlijk: juli en augustus zijn in Tarifa de moeilijkste maanden voor openbaar parkeren. Ik noem het niet letterlijk onmogelijk, maar plan elke rit zorgvuldiger en waardeer de privégarage enorm.', 'Jag säger det rakt: juli och augusti är de svåraste månaderna för offentlig parkering i Tarifa. Jag kallar det inte bokstavligen omöjligt, men planerar varje resa noggrannare och värdesätter det privata garaget enormt.'),
    l('The municipal system was also changing in 2025 and 2026, including new parking-meter and management technology. For that reason I ask you to check the current signs, tariff and payment method instead of relying on an old screenshot.', 'Auch das kommunale System veränderte sich 2025 und 2026, unter anderem bei Parkautomaten und Verwaltungstechnik. Deshalb bitte ich euch, aktuelle Schilder, Tarif und Zahlungsart zu prüfen, statt euch auf einen alten Screenshot zu verlassen.', 'El sistema municipal también cambió en 2025 y 2026, incluidos parquímetros y tecnología de gestión. Por eso os pido comprobar señales, tarifa y pago actuales en lugar de confiar en una captura antigua.', 'Ook het gemeentelijke systeem veranderde in 2025 en 2026, onder meer met automaten en beheertechniek. Controleer daarom actuele borden, tarief en betaling in plaats van op een oude screenshot te vertrouwen.', 'Det kommunala systemet förändrades också 2025 och 2026, bland annat med automater och hanteringsteknik. Kontrollera därför aktuella skyltar, pris och betalning i stället för att lita på en gammal skärmbild.')
  ]},
  { id: 'amara-boundary', eyebrow: l('06 · What I can promise', '06 · Was ich euch versprechen kann', '06 · Lo que puedo prometer', '06 · Wat ik kan beloven', '06 · Vad jag kan lova'), title: l('Your space at AMARA — honest advice everywhere else', 'Euer Platz bei AMARA – ehrlicher Rat für alle anderen Wege', 'Vuestra plaza en AMARA y consejo sincero para lo demás', 'Jullie plek bij AMARA en eerlijk advies voor de rest', 'Er plats vid AMARA och ärliga råd för resten'), paragraphs: [
    l('What I can promise is a parking place at AMARA Family & Surf when it is included in your booking. What I cannot promise is a public space at the old town, port or beach.', 'Was ich euch zusagen kann, ist der Stellplatz bei AMARA Family & Surf, wenn er in eurer Buchung enthalten ist. Was ich nicht versprechen kann, ist ein öffentlicher Platz an Altstadt, Hafen oder Strand.', 'Lo que sí puedo prometer es la plaza de AMARA Family & Surf cuando esté incluida en vuestra reserva. Lo que no puedo prometer es una plaza pública en casco antiguo, puerto o playa.', 'Wat ik kan toezeggen is de plek bij AMARA Family & Surf wanneer die in jullie boeking is inbegrepen. Wat ik niet kan beloven is een openbare plek bij oude stad, haven of strand.', 'Det jag kan lova är platsen vid AMARA Family & Surf när den ingår i bokningen. Det jag inte kan lova är en offentlig plats vid gamla stan, hamnen eller stranden.'),
    l('I will send the exact entrance and access with your arrival information. On this page I concentrate on the decision that helps you most: where are you actually driving today?', 'Die genaue Einfahrt und den Zugang schicke ich euch mit euren Ankunftsinformationen. Hier konzentriere ich mich auf die Entscheidung, die euch am meisten hilft: Wohin fahrt ihr heute tatsächlich?', 'Os enviaré la entrada y el acceso exactos con la información de llegada. Aquí me concentro en la decisión más útil: ¿adónde vais realmente hoy?', 'De exacte ingang en toegang stuur ik met jullie aankomstinformatie. Hier richt ik mij op de nuttigste beslissing: waar rijden jullie vandaag echt heen?', 'Exakt infart och tillträde skickar jag med ankomstinformationen. Här fokuserar jag på beslutet som hjälper mest: vart ska ni faktiskt köra i dag?')
  ]}
];

const related = [
  { token: 'getting_to_tarifa' as const, label: l('Arrival & Mobility', 'Anreise & Mobilität', 'Llegada y movilidad', 'Aankomst & mobiliteit', 'Ankomst & mobilitet'), text: l('Roads, airports, ferry and the approach to Tarifa.', 'Straßen, Flughäfen, Fähre und die Zufahrt nach Tarifa.', 'Carreteras, aeropuertos, ferry y llegada a Tarifa.', 'Wegen, luchthavens, ferry en aankomst in Tarifa.', 'Vägar, flygplatser, färja och infarten till Tarifa.') },
  { token: 'tarifa_beaches_authority' as const, label: l('Beaches & Coast', 'Strände & Küste', 'Playas y costa', 'Stranden & kust', 'Stränder & kust'), text: l('Choose the beach before checking its current access.', 'Erst den Strand wählen, dann dessen aktuelle Zufahrt prüfen.', 'Elegid la playa antes de comprobar su acceso.', 'Kies het strand vóór de actuele toegang.', 'Välj stranden före kontroll av aktuell tillfart.') },
  { token: 'tarifa_where_to_stay' as const, label: l('Where to Stay', 'Wo übernachten', 'Dónde alojarse', 'Waar overnachten', 'Var ska man bo'), text: l('Understand La Marina, old town and other stay contexts.', 'La Marina, Altstadt und andere Lagen verstehen.', 'Entended La Marina, casco antiguo y otras zonas.', 'Begrijp La Marina, oude stad en andere gebieden.', 'Förstå La Marina, gamla stan och andra områden.') }
];

const sourceRows = [
  { label: l('URTASA · parking-meter update', 'URTASA · Update zu Parkautomaten', 'URTASA · actualización de parquímetros', 'URTASA · update parkeerautomaten', 'URTASA · uppdatering om automater'), text: l('This is where I checked why tariffs and payment systems can change.', 'Hier habe ich geprüft, warum sich Tarife und Zahlungssysteme verändern können.', 'Aquí comprobé por qué pueden cambiar tarifas y sistemas de pago.', 'Hier controleerde ik waarom tarieven en betaalsystemen kunnen veranderen.', 'Här kontrollerade jag varför priser och betalningssystem kan ändras.'), href: 'https://www.aytotarifa.com/notice-category/perfil-del-contratante/' },
  { label: l('Paseo del Retiro · 2026 authorisations', 'Paseo del Retiro · Genehmigungen 2026', 'Paseo del Retiro · autorizaciones 2026', 'Paseo del Retiro · vergunningen 2026', 'Paseo del Retiro · tillstånd 2026'), text: l('Shows that parts of the facility follow an authorisation regime.', 'Zeigt, dass Teile einem Genehmigungsregime folgen.', 'Muestra que partes siguen un régimen de autorización.', 'Toont dat delen een vergunningstelsel volgen.', 'Visar att delar följer ett tillståndssystem.'), href: 'https://www.aytotarifa.com/notices/listado-de-aprobacion-de-listado-definitivo-de-personas-admitidas-en-el-proceso-de-concesion-de-autorizaciones-anuales-para-el-uso-de-plazas-de-estacionamiento-de-vehiculos-en-el-aparcamiento-municipa/' },
  { label: l('Tarifa beach-use plan 2024–2027', 'Tarifa-Strandplan 2024–2027', 'Plan de playas 2024–2027', 'Tarifa-strandplan 2024–2027', 'Tarifas strandplan 2024–2027'), text: l('Official structure of distinct beach areas; not one universal parking rule.', 'Amtliche Struktur verschiedener Strandräume, keine Universalparkregel.', 'Estructura oficial de playas distintas, no regla única.', 'Officiële structuur van verschillende stranden, geen universele regel.', 'Officiell struktur för olika stränder, inte en universell regel.'), href: 'https://www.aytotarifa.com/notices/plan-de-explotacion-de-playas-2024-2027/' }
];

const makeLocale = (lang: AmaraLanguage): ParkingGuideLocale => ({
  navLabel: navLabel[lang], hero: { eyebrow: hero.eyebrow[lang], title: hero.title[lang], standfirst: hero.standfirst[lang], note: hero.note[lang], updated: hero.updated[lang] },
  facts: facts.map((item) => ({ label: item.label[lang], value: item.value[lang] })),
  sections: sections.map((section) => ({ id: section.id, eyebrow: section.eyebrow[lang], title: section.title[lang], paragraphs: section.paragraphs.map((p) => p[lang]) })),
  related: { eyebrow: l('Continue planning', 'Weiter planen', 'Seguir planificando', 'Verder plannen', 'Planera vidare')[lang], title: l('Connect parking to the journey you actually plan', 'Parken mit der wirklich geplanten Fahrt verbinden', 'Conectad el aparcamiento con el trayecto real', 'Verbind parkeren met de geplande rit', 'Koppla parkering till den faktiska resan')[lang], links: related.map((item) => ({ token: item.token, label: item.label[lang], text: item.text[lang] })) },
  sources: { eyebrow: l('What I checked for you', 'Was ich für euch geprüft habe', 'Lo que he comprobado para vosotros', 'Wat ik voor jullie heb nagekeken', 'Det jag har kontrollerat åt er')[lang], title: l('Official updates for a system that keeps changing', 'Offizielle Hinweise für ein System, das sich verändert', 'Información oficial para un sistema que cambia', 'Officiële updates voor een veranderend systeem', 'Officiell information för ett system i förändring')[lang], intro: l('I checked the town’s information on parking technology, authorisations and beach areas. On arrival, please still follow the current signs and displayed tariff.', 'Ich habe die Angaben der Stadt zu Parktechnik, Genehmigungen und Strandbereichen geprüft. Bei der Ankunft folgt ihr bitte trotzdem den aktuellen Schildern und dem ausgewiesenen Tarif.', 'He revisado la información municipal sobre tecnología, autorizaciones y zonas de playa. Al llegar, seguid siempre las señales y la tarifa expuesta.', 'Ik heb de gemeentelijke informatie over techniek, vergunningen en strandgebieden nagekeken. Volg bij aankomst altijd de actuele borden en het getoonde tarief.', 'Jag har kontrollerat kommunens information om teknik, tillstånd och strandområden. Vid ankomst ska ni ändå följa aktuella skyltar och angivet pris.')[lang], checked: l('Personally checked 21 August 2026', 'Von mir geprüft am 21. August 2026', 'Comprobado personalmente el 21 de agosto de 2026', 'Door mij gecontroleerd op 21 augustus 2026', 'Personligen kontrollerat 21 augusti 2026')[lang], links: sourceRows.map((item) => ({ label: item.label[lang], text: item.text[lang], href: item.href })) },
  closing: { eyebrow: l('My simple Tarifa rule', 'Meine einfache Tarifa-Regel', 'Mi regla sencilla para Tarifa', 'Mijn eenvoudige Tarifa-regel', 'Min enkla Tarifa-regel')[lang], title: l('Use the garage as your base — then choose each destination', 'Nutzt die Garage als Basis – und wählt dann euer Ziel', 'Usad el garaje como base y elegid después el destino', 'Gebruik de garage als basis en kies daarna het doel', 'Använd garaget som bas och välj sedan målet')[lang], body: l('The AMARA space makes the accommodation arrival much easier, especially in July and August. For the old town, port and beaches, tell me the destination first and I will point you in the right direction.', 'Der AMARA-Stellplatz macht die Ankunft an der Unterkunft deutlich einfacher – besonders im Juli und August. Für Altstadt, Hafen und Strände nennt ihr mir zuerst euer Ziel, und ich zeige euch die richtige Richtung.', 'La plaza AMARA facilita mucho la llegada, sobre todo en julio y agosto. Para casco antiguo, puerto y playas, decidme primero el destino y os indicaré la dirección adecuada.', 'De AMARA-plek maakt de aankomst veel eenvoudiger, vooral in juli en augustus. Noem voor oude stad, haven en stranden eerst jullie doel en ik wijs de juiste richting.', 'AMARA-platsen gör ankomsten mycket enklare, särskilt i juli och augusti. För gamla stan, hamnen och stränderna berättar ni målet först, så visar jag rätt riktning.')[lang], locationLabel: l('Explore Tarifa', 'Tarifa entdecken', 'Descubrir Tarifa', 'Ontdek Tarifa', 'Upptäck Tarifa')[lang], propertyLabel: l('View AMARA Family & Surf', 'AMARA Family & Surf ansehen', 'Ver AMARA Family & Surf', 'Bekijk AMARA Family & Surf', 'Se AMARA Family & Surf')[lang] }
});

export const tarifaParkingContent = Object.fromEntries(langs.map((lang) => [lang, makeLocale(lang)])) as Record<AmaraLanguage, ParkingGuideLocale>;
