import type { AmaraAuthoringSeo, AmaraLanguage } from '../types/seo';
import type { ParkingGuideLocale, ParkingGuideSection } from './parkingGuideContent';

type Localized = Record<AmaraLanguage, string>;
const l = (en: string, de: string, es: string, nl: string, sv: string): Localized => ({ en, de, es, nl, sv });
const langs: AmaraLanguage[] = ['en', 'de', 'es', 'nl', 'sv'];
const article = { datePublished: '2026-08-21', dateModified: '2026-08-21', authorName: 'Robert Sebastian Böhmer', authorType: 'Person' as const, authorSlug: 'amara-about-us' };

export const tarifaParkingSeo: AmaraAuthoringSeo = {
  version: '2026-08-21-tarifa-parking-v1.0', pageType: 'A', entityKey: 'amara-brand', article,
  languages: {
    en: { title: 'Parking in Tarifa: Old Town, Beaches & AMARA Garage', description: 'Plan parking in Tarifa by context: town and old town, beach days, July and August pressure, luggage, current rules and AMARA’s included garage space.', robots: 'index, follow', canonical: 'auto' },
    de: { title: 'Parken in Tarifa: Altstadt, Strände & AMARA-Tiefgarage', description: 'Plant Parken in Tarifa nach Kontext: Stadt und Altstadt, Strandtage, Juli-/August-Druck, Gepäck, aktuelle Regeln und AMARA-Tiefgaragenplatz.', robots: 'index, follow', canonical: 'auto' },
    es: { title: 'Aparcar en Tarifa: casco antiguo, playas y garaje AMARA', description: 'Planificad el aparcamiento en Tarifa: ciudad y casco antiguo, playas, presión de julio y agosto, equipaje, reglas actuales y garaje AMARA.', robots: 'index, follow', canonical: 'auto' },
    nl: { title: 'Parkeren in Tarifa: oude stad, stranden & AMARA-garage', description: 'Plan parkeren in Tarifa per context: stad en oude kern, stranddagen, drukte in juli en augustus, bagage, actuele regels en AMARA-garage.', robots: 'index, follow', canonical: 'auto' },
    sv: { title: 'Parkering i Tarifa: gamla stan, stränder & AMARA-garage', description: 'Planera parkering i Tarifa per sammanhang: stad och gamla stan, stranddagar, tryck i juli och augusti, bagage, aktuella regler och AMARA-garage.', robots: 'index, follow', canonical: 'auto' }
  }
};

const navLabel = l('Parking & Accessibility', 'Parken & Erreichbarkeit', 'Aparcamiento y acceso', 'Parkeren & toegankelijkheid', 'Parkering & tillgänglighet');
const hero = {
  eyebrow: l('Parking & access · Tarifa', 'Parken & Erreichbarkeit · Tarifa', 'Aparcamiento y acceso · Tarifa', 'Parkeren & toegankelijkheid · Tarifa', 'Parkering & tillgänglighet · Tarifa'),
  title: l('Tarifa parking starts with one question: town or beach?', 'Parken in Tarifa beginnt mit einer Frage: Stadt oder Strand?', 'Aparcar en Tarifa empieza con una pregunta: ¿ciudad o playa?', 'Parkeren in Tarifa begint met één vraag: stad of strand?', 'Parkering i Tarifa börjar med en fråga: stad eller strand?'),
  standfirst: l(
    'Parking for Tarifa town and the old town is a different task from parking for a day at Los Lances, Valdevaqueros or Bolonia. July and August add another reality: AMARA’s host experience describes pressure as exceptionally high, so a private space changes the stay. AMARA Family & Surf currently includes an underground parking space for guests. That is a property advantage, not proof that Tarifa itself is easy to park in — and current municipal rules must still be checked for every other journey.',
    'Parken für Tarifa-Stadt und Altstadt ist eine andere Aufgabe als Parken für einen Tag an Los Lances, Valdevaqueros oder Bolonia. Juli und August bringen eine weitere Realität: Nach AMARA-Gastgebererfahrung ist der Druck außergewöhnlich hoch – ein privater Platz verändert dann den Aufenthalt. Bei AMARA Family & Surf ist aktuell ein Tiefgaragenstellplatz für Gäste enthalten. Das ist ein Objektvorteil, kein Beweis für einfaches Parken in Tarifa; für jede andere Fahrt gelten aktuelle Regeln.',
    'Aparcar para la ciudad y el casco antiguo es distinto de aparcar para un día en Los Lances, Valdevaqueros o Bolonia. Julio y agosto añaden otra realidad: la experiencia de AMARA describe una presión excepcional, por lo que una plaza privada cambia la estancia. AMARA Family & Surf incluye actualmente una plaza de garaje subterráneo para huéspedes. Es una ventaja del alojamiento, no prueba de que Tarifa sea fácil para aparcar; cada otro trayecto requiere reglas actuales.',
    'Parkeren voor Tarifa-stad en de oude kern is iets anders dan parkeren voor een dag bij Los Lances, Valdevaqueros of Bolonia. Juli en augustus voegen een andere realiteit toe: volgens AMARA-ervaring is de druk uitzonderlijk hoog, waardoor een privéplek het verblijf verandert. AMARA Family & Surf omvat momenteel een ondergrondse parkeerplek voor gasten. Dat is een woningvoordeel, geen bewijs dat Tarifa zelf makkelijk is; voor andere ritten gelden actuele regels.',
    'Parkering för Tarifa stad och gamla stan är en annan uppgift än parkering för en dag vid Los Lances, Valdevaqueros eller Bolonia. Juli och augusti ger en annan verklighet: AMARA:s erfarenhet beskriver trycket som exceptionellt, så en privat plats förändrar vistelsen. AMARA Family & Surf inkluderar för närvarande en underjordisk plats för gäster. Det är en boendefördel, inte bevis på att Tarifa är lätt att parkera i; andra resor kräver aktuella regler.'
  ),
  note: l('Peak-season pressure is first-party experience, not an occupancy statistic. Confirm the private space and current access in the booking information.', 'Hochsaisondruck ist First-Party-Erfahrung, keine Auslastungsstatistik. Privaten Platz und Zugang in den Buchungsinformationen bestätigen.', 'La presión estival es experiencia propia, no estadística. Confirmad plaza y acceso en la información de reserva.', 'Hoogseizoendruk is eigen ervaring, geen statistiek. Bevestig plek en toegang in de boekingsinfo.', 'Högsäsongstryck är egen erfarenhet, inte statistik. Bekräfta plats och tillträde i bokningsinformationen.'),
  updated: l('Municipal sources and AMARA property baseline reviewed August 2026', 'Gemeindequellen und AMARA-Objektbestand geprüft im August 2026', 'Fuentes municipales y base del alojamiento revisadas en agosto de 2026', 'Gemeentebronnen en woningbasis herzien in augustus 2026', 'Kommunala källor och boendebaslinje granskade augusti 2026')
};

const facts = [
  { label: l('Two parking worlds', 'Zwei Parkwelten', 'Dos mundos', 'Twee parkeerwerelden', 'Två parkeringsvärldar'), value: l('Town and old town ≠ beach destination', 'Stadt und Altstadt ≠ Strandziel', 'Ciudad y casco antiguo ≠ playa', 'Stad en oude kern ≠ strand', 'Stad och gamla stan ≠ strand') },
  { label: l('Peak pressure', 'Spitzendruck', 'Presión máxima', 'Piekdrukte', 'Högsta tryck'), value: l('July and August require the most caution', 'Juli und August brauchen die meiste Vorsicht', 'Julio y agosto exigen más previsión', 'Juli en augustus vragen de meeste planning', 'Juli och augusti kräver mest planering') },
  { label: l('At AMARA', 'Bei AMARA', 'En AMARA', 'Bij AMARA', 'Hos AMARA'), value: l('An underground guest space is currently included', 'Ein Tiefgaragenplatz ist aktuell enthalten', 'Actualmente se incluye plaza de garaje', 'Een ondergrondse plek is momenteel inbegrepen', 'En underjordisk gästplats ingår för närvarande') },
  { label: l('Live boundary', 'Live-Grenze', 'Límite actual', 'Live-grens', 'Live-gräns'), value: l('Zones, machines and beach access can change', 'Zonen, Automaten und Strandzufahrt können wechseln', 'Zonas, parquímetros y acceso pueden cambiar', 'Zones, automaten en strandtoegang kunnen veranderen', 'Zoner, automater och strandvägar kan ändras') }
] as const;

const sections: Array<{ id: ParkingGuideSection['id']; eyebrow: Localized; title: Localized; paragraphs: Localized[] }> = [
  { id: 'parking-reality', eyebrow: l('01 · Parking reality', '01 · Die Parkrealität', '01 · La realidad', '01 · De realiteit', '01 · Verkligheten'), title: l('Tarifa is a network of parking contexts', 'Tarifa ist ein Netz aus Parkkontexten', 'Tarifa es una red de contextos', 'Tarifa is een netwerk van parkeercontexten', 'Tarifa är ett nät av parkeringssammanhang'), paragraphs: [
    l('Town, old town, port and the individual beach areas are not interchangeable destinations. A place that works for an evening in the old town says little about a windy beach day farther west.', 'Stadt, Altstadt, Hafen und einzelne Strandbereiche sind keine austauschbaren Ziele. Ein Platz für den Altstadtabend sagt wenig über einen windigen Strandtag weiter westlich.', 'Ciudad, casco antiguo, puerto y playas no son destinos intercambiables. Una opción para la noche en el centro dice poco sobre un día de playa al oeste.', 'Stad, oude kern, haven en afzonderlijke stranden zijn geen uitwisselbare doelen. Een plek voor een avond in de oude stad zegt weinig over een stranddag westelijker.', 'Stad, gamla stan, hamn och enskilda stränder är inte utbytbara mål. En plats för en kväll i gamla stan säger lite om en stranddag längre västerut.'),
    l('The guide therefore explains how to choose the right context. Detailed access and parking for a specific beach belong to that beach guide and must use current conditions.', 'Der Guide erklärt deshalb die richtige Kontextwahl. Detaillierte Zufahrt und Parken für einen bestimmten Strand gehören in dessen Guide und brauchen aktuelle Bedingungen.', 'La guía explica cómo elegir contexto. El acceso y aparcamiento de una playa concreta pertenecen a su guía y necesitan datos actuales.', 'De gids legt daarom contextkeuze uit. Toegang en parkeren voor een specifiek strand horen in die strandgids met actuele informatie.', 'Guiden förklarar därför rätt sammanhang. Tillfart och parkering för en viss strand hör till strandguiden och kräver aktuella uppgifter.')
  ]},
  { id: 'arrival-luggage', eyebrow: l('02 · Arrival and luggage', '02 · Ankunft und Gepäck', '02 · Llegada y equipaje', '02 · Aankomst en bagage', '02 · Ankomst och bagage'), title: l('A private garage changes the accommodation arrival', 'Eine private Garage verändert die Ankunft', 'Un garaje privado cambia la llegada', 'Een privégarage verandert de aankomst', 'Ett privat garage förändrar ankomsten'), paragraphs: [
    l('Current AMARA guest information records an underground space for Family & Surf. Confirm the current assignment, access method and vehicle fit in the property instructions before travel.', 'Die aktuelle AMARA-Gästeinformation nennt einen Tiefgaragenplatz für Family & Surf. Bestätigt vor der Reise Zuordnung, Zugang und Fahrzeugpassung in den Objekthinweisen.', 'La información actual de AMARA registra plaza subterránea para Family & Surf. Confirmad asignación, acceso y tamaño en las instrucciones.', 'De huidige AMARA-info noemt een ondergrondse plek voor Family & Surf. Bevestig toewijzing, toegang en voertuigmaat vóór vertrek.', 'Nuvarande AMARA-information anger en underjordisk plats för Family & Surf. Bekräfta tilldelning, tillträde och fordonsmått före resan.'),
    l('The garage solves parking at the accommodation, not every Tarifa journey. Luggage unloading, the entrance and any stairs still require the exact property route.', 'Die Garage löst das Parken an der Unterkunft, nicht jede Tarifa-Fahrt. Gepäck, Eingang und mögliche Stufen brauchen weiterhin die konkrete Objektroute.', 'El garaje resuelve el alojamiento, no cada trayecto. Equipaje, entrada y posibles escaleras requieren la ruta exacta.', 'De garage lost parkeren bij het verblijf op, niet elke Tarifa-rit. Bagage, ingang en mogelijke trappen vragen nog steeds de exacte route.', 'Garaget löser parkering vid boendet, inte varje Tarifa-resa. Bagage, entré och eventuella trappor kräver exakt boenderutt.')
  ]},
  { id: 'during-stay', eyebrow: l('03 · During your stay', '03 · Während des Aufenthalts', '03 · Durante la estancia', '03 · Tijdens het verblijf', '03 · Under vistelsen'), title: l('Leave the car for town; use it selectively for the coast', 'Für die Stadt stehen lassen, für die Küste gezielt nutzen', 'Dejadlo para la ciudad; usadlo con criterio para la costa', 'Laat hem staan voor de stad; gebruik hem gericht voor de kust', 'Låt bilen stå för staden; använd den selektivt för kusten'), paragraphs: [
    l('A stay near La Marina can support walking into town and the old town while the car remains in its space. That can be especially valuable when public parking pressure is high.', 'Ein Aufenthalt bei La Marina ermöglicht Wege in Stadt und Altstadt zu Fuß, während das Auto stehen bleibt. Das ist besonders bei hohem öffentlichen Parkdruck wertvoll.', 'Una estancia cerca de La Marina permite ir andando a ciudad y casco antiguo mientras el coche queda guardado. Es especialmente valioso con alta presión.', 'Een verblijf bij La Marina maakt lopen naar stad en oude kern mogelijk terwijl de auto blijft staan. Dat is vooral waardevol bij hoge druk.', 'Ett boende nära La Marina kan möjliggöra promenad till stad och gamla stan medan bilen står kvar. Det är särskilt värdefullt vid högt tryck.'),
    l('Beach days are a different decision. Choose the beach first, then check its current access, nature-area rules, wind and seasonal operation rather than carrying one town-parking rule along the coast.', 'Strandtage sind eine andere Entscheidung. Wählt zuerst den Strand und prüft dann Zufahrt, Naturraumregeln, Wind und Saisonbetrieb statt eine Stadtparkregel mitzunehmen.', 'Los días de playa son otra decisión. Elegid primero la playa y comprobad acceso, reglas naturales, viento y temporada.', 'Stranddagen zijn een andere keuze. Kies eerst het strand en controleer toegang, natuurregels, wind en seizoen.', 'Stranddagar är ett annat beslut. Välj stranden först och kontrollera tillfart, naturregler, vind och säsong.')
  ]},
  { id: 'last-mile', eyebrow: l('04 · Last mile and accessibility', '04 · Letzter Weg und Zugänglichkeit', '04 · Último tramo y accesibilidad', '04 · Laatste route en toegankelijkheid', '04 · Sista sträckan och tillgänglighet'), title: l('A garage space does not describe the whole route', 'Ein Garagenplatz beschreibt nicht den ganzen Weg', 'Una plaza de garaje no describe toda la ruta', 'Een garageplek beschrijft niet de hele route', 'En garageplats beskriver inte hela vägen'), paragraphs: [
    l('Garage level, lift or stairs, kerbs and the building entrance all affect the real arrival. “Private parking” is not the same claim as “step-free access”.', 'Garagenebene, Aufzug oder Stufen, Bordsteine und Hauseingang prägen die echte Ankunft. „Privatparken“ ist nicht dasselbe wie „stufenfrei“.', 'Nivel del garaje, ascensor o escaleras, bordillos y entrada forman la llegada real. “Parking privado” no equivale a “sin escalones”.', 'Garageniveau, lift of trappen, stoepen en ingang bepalen de echte aankomst. “Privéparkeren” is niet hetzelfde als “trapvrij”.', 'Garagenivå, hiss eller trappor, kanter och entré formar ankomsten. “Privat parkering” är inte samma sak som “stegfritt”.'),
    l('Guests with mobility needs should confirm the complete garage-to-door route. General PMR parking rights never prove that a particular accommodation route is suitable.', 'Bei Mobilitätsbedarf bestätigt ihr die vollständige Garage-zur-Tür-Route. Allgemeine PMR-Rechte beweisen nie die Eignung eines konkreten Objektwegs.', 'Si hay necesidades de movilidad, confirmad toda la ruta garaje-puerta. Los derechos PMR no demuestran que una ruta concreta sea adecuada.', 'Bevestig bij mobiliteitsbehoeften de volledige garage-tot-deurroute. PMR-rechten bewijzen geen geschikte woningroute.', 'Vid rörelsebehov ska hela garage-till-dörr-rutten bekräftas. PMR-rättigheter bevisar inte att en viss boenderutt passar.')
  ]},
  { id: 'seasonal-rules', eyebrow: l('05 · Peak season and current rules', '05 · Hochsaison und aktuelle Regeln', '05 · Temporada alta y reglas actuales', '05 · Hoogseizoen en actuele regels', '05 · Högsäsong och aktuella regler'), title: l('July and August need a different expectation', 'Juli und August brauchen eine andere Erwartung', 'Julio y agosto requieren otra expectativa', 'Juli en augustus vragen een andere verwachting', 'Juli och augusti kräver en annan förväntan'), paragraphs: [
    l('AMARA’s host experience describes public parking pressure as exceptionally high in July and August. Publish that as experienced seasonality, not the literal claim that parking is impossible.', 'Nach AMARA-Gastgebererfahrung ist der öffentliche Parkdruck im Juli und August außergewöhnlich hoch. Das ist erlebte Saisonalität, nicht die wörtliche Aussage, Parken sei unmöglich.', 'La experiencia de AMARA describe presión excepcional en julio y agosto. Es estacionalidad vivida, no afirmación literal de imposibilidad.', 'AMARA-ervaring beschrijft uitzonderlijk hoge druk in juli en augustus. Dat is ervaren seizoen, niet letterlijk “onmogelijk”.', 'AMARA-erfarenhet beskriver exceptionellt högt tryck i juli och augusti. Det är upplevd säsong, inte bokstavligen “omöjligt”.'),
    l('Tarifa’s municipal parking system was changing through 2025–26, including an official meter and management-platform tender. Do not freeze zones, tariffs or payment methods without a current operator source.', 'Tarifas kommunales Parksystem veränderte sich 2025–26, unter anderem mit einer offiziellen Ausschreibung für Automaten und Plattform. Zonen, Tarife und Zahlung nie ohne aktuelle Betreiberquelle festschreiben.', 'El sistema municipal cambió en 2025–26, incluida una licitación de parquímetros y plataforma. No fijéis zonas, tarifas o pago sin fuente actual.', 'Het gemeentelijke systeem veranderde in 2025–26, met een aanbesteding voor automaten en platform. Zet zones, tarieven of betaling niet vast zonder actuele bron.', 'Kommunens system ändrades 2025–26, bland annat genom upphandling av automater och plattform. Lås inte zoner, priser eller betalning utan aktuell källa.')
  ]},
  { id: 'amara-boundary', eyebrow: l('06 · AMARA boundary', '06 · AMARA-Grenze', '06 · Límite AMARA', '06 · AMARA-grens', '06 · AMARA-gränsen'), title: l('Use the property advantage without turning it into a town claim', 'Objektvorteil nutzen, ohne ihn zur Stadtaussage zu machen', 'Usad la ventaja sin convertirla en afirmación sobre la ciudad', 'Gebruik het woningvoordeel zonder stadsclaim', 'Använd boendefördelen utan att göra den till stadspåstående'), paragraphs: [
    l('The included AMARA space can remove the hardest accommodation-parking question in peak season. It does not guarantee parking at the old town, port or beaches.', 'Der enthaltene AMARA-Platz kann in der Hochsaison die schwierigste Unterkunftsfrage lösen. Er garantiert nichts für Altstadt, Hafen oder Strände.', 'La plaza AMARA puede resolver la cuestión del alojamiento en temporada alta. No garantiza parking en casco antiguo, puerto o playas.', 'De AMARA-plek kan in het hoogseizoen de verblijfsvraag oplossen. Ze garandeert niets bij oude stad, haven of stranden.', 'AMARA-platsen kan lösa boendefrågan under högsäsong. Den garanterar inget vid gamla stan, hamn eller stränder.'),
    l('Keep the exact space, entrance and access method in current property instructions. Keep destination guidance focused on choosing the right context and checking live rules.', 'Exakten Platz, Einfahrt und Zugang hält die aktuelle Objekthinweise. Der Ortsguide konzentriert sich auf Kontextwahl und Live-Regeln.', 'La plaza exacta, entrada y acceso pertenecen a instrucciones actuales. La guía se centra en contexto y reglas vigentes.', 'Exacte plek, ingang en toegang horen in actuele woninginstructies. De gids focust op context en live regels.', 'Exakt plats, infart och tillträde hör till aktuella boendeinstruktioner. Guiden fokuserar på sammanhang och aktuella regler.')
  ]}
];

const related = [
  { token: 'getting_to_tarifa' as const, label: l('Arrival & Mobility', 'Anreise & Mobilität', 'Llegada y movilidad', 'Aankomst & mobiliteit', 'Ankomst & mobilitet'), text: l('Roads, airports, ferry and the approach to Tarifa.', 'Straßen, Flughäfen, Fähre und die Zufahrt nach Tarifa.', 'Carreteras, aeropuertos, ferry y llegada a Tarifa.', 'Wegen, luchthavens, ferry en aankomst in Tarifa.', 'Vägar, flygplatser, färja och infarten till Tarifa.') },
  { token: 'tarifa_beaches_authority' as const, label: l('Beaches & Coast', 'Strände & Küste', 'Playas y costa', 'Stranden & kust', 'Stränder & kust'), text: l('Choose the beach before checking its current access.', 'Erst den Strand wählen, dann dessen aktuelle Zufahrt prüfen.', 'Elegid la playa antes de comprobar su acceso.', 'Kies het strand vóór de actuele toegang.', 'Välj stranden före kontroll av aktuell tillfart.') },
  { token: 'tarifa_where_to_stay' as const, label: l('Where to Stay', 'Wo übernachten', 'Dónde alojarse', 'Waar overnachten', 'Var ska man bo'), text: l('Understand La Marina, old town and other stay contexts.', 'La Marina, Altstadt und andere Lagen verstehen.', 'Entended La Marina, casco antiguo y otras zonas.', 'Begrijp La Marina, oude stad en andere gebieden.', 'Förstå La Marina, gamla stan och andra områden.') }
];

const sourceRows = [
  { label: l('URTASA · parking-meter tender', 'URTASA · Parkautomaten-Ausschreibung', 'URTASA · licitación de parquímetros', 'URTASA · aanbesteding parkeerautomaten', 'URTASA · upphandling av parkeringsautomater'), text: l('Official evidence of a changing management system.', 'Amtlicher Beleg für ein verändertes Managementsystem.', 'Prueba oficial de un sistema en cambio.', 'Officieel bewijs van een veranderend systeem.', 'Officiellt belägg för ett system i förändring.'), href: 'https://www.aytotarifa.com/notice-category/perfil-del-contratante/' },
  { label: l('Paseo del Retiro · 2026 authorisations', 'Paseo del Retiro · Genehmigungen 2026', 'Paseo del Retiro · autorizaciones 2026', 'Paseo del Retiro · vergunningen 2026', 'Paseo del Retiro · tillstånd 2026'), text: l('Shows that parts of the facility follow an authorisation regime.', 'Zeigt, dass Teile einem Genehmigungsregime folgen.', 'Muestra que partes siguen un régimen de autorización.', 'Toont dat delen een vergunningstelsel volgen.', 'Visar att delar följer ett tillståndssystem.'), href: 'https://www.aytotarifa.com/notices/listado-de-aprobacion-de-listado-definitivo-de-personas-admitidas-en-el-proceso-de-concesion-de-autorizaciones-anuales-para-el-uso-de-plazas-de-estacionamiento-de-vehiculos-en-el-aparcamiento-municipa/' },
  { label: l('Tarifa beach-use plan 2024–2027', 'Tarifa-Strandplan 2024–2027', 'Plan de playas 2024–2027', 'Tarifa-strandplan 2024–2027', 'Tarifas strandplan 2024–2027'), text: l('Official structure of distinct beach areas; not one universal parking rule.', 'Amtliche Struktur verschiedener Strandräume, keine Universalparkregel.', 'Estructura oficial de playas distintas, no regla única.', 'Officiële structuur van verschillende stranden, geen universele regel.', 'Officiell struktur för olika stränder, inte en universell regel.'), href: 'https://www.aytotarifa.com/notices/plan-de-explotacion-de-playas-2024-2027/' }
];

const makeLocale = (lang: AmaraLanguage): ParkingGuideLocale => ({
  navLabel: navLabel[lang], hero: { eyebrow: hero.eyebrow[lang], title: hero.title[lang], standfirst: hero.standfirst[lang], note: hero.note[lang], updated: hero.updated[lang] },
  facts: facts.map((item) => ({ label: item.label[lang], value: item.value[lang] })),
  sections: sections.map((section) => ({ id: section.id, eyebrow: section.eyebrow[lang], title: section.title[lang], paragraphs: section.paragraphs.map((p) => p[lang]) })),
  related: { eyebrow: l('Continue planning', 'Weiter planen', 'Seguir planificando', 'Verder plannen', 'Planera vidare')[lang], title: l('Connect parking to the journey you actually plan', 'Parken mit der wirklich geplanten Fahrt verbinden', 'Conectad el aparcamiento con el trayecto real', 'Verbind parkeren met de geplande rit', 'Koppla parkering till den faktiska resan')[lang], links: related.map((item) => ({ token: item.token, label: item.label[lang], text: item.text[lang] })) },
  sources: { eyebrow: l('Official evidence', 'Amtliche Belege', 'Fuentes oficiales', 'Officiële bronnen', 'Officiella källor')[lang], title: l('A dynamic system needs current sources', 'Ein dynamisches System braucht aktuelle Quellen', 'Un sistema dinámico necesita fuentes actuales', 'Een dynamisch systeem vraagt actuele bronnen', 'Ett dynamiskt system kräver aktuella källor')[lang], intro: l('Municipal sources show authorisations, technology change and distinct beach areas. They do not create a permanent tariff or availability promise.', 'Gemeindequellen zeigen Genehmigungen, Technikwechsel und verschiedene Strandräume. Sie erzeugen kein dauerhaftes Preis- oder Verfügbarkeitsversprechen.', 'Las fuentes muestran autorizaciones, cambio tecnológico y playas distintas. No crean promesa permanente de precio o disponibilidad.', 'Gemeentebronnen tonen vergunningen, technische verandering en verschillende stranden. Ze creëren geen permanente prijs- of beschikbaarheidsbelofte.', 'Kommunala källor visar tillstånd, teknikskifte och olika stränder. De skapar inget permanent pris- eller tillgänglighetslöfte.')[lang], checked: l('Sources reviewed 21 August 2026', 'Quellen geprüft am 21. August 2026', 'Fuentes revisadas el 21 de agosto de 2026', 'Bronnen gecontroleerd op 21 augustus 2026', 'Källor granskade 21 augusti 2026')[lang], links: sourceRows.map((item) => ({ label: item.label[lang], text: item.text[lang], href: item.href })) },
  closing: { eyebrow: l('A calmer Tarifa arrival', 'Entspannter in Tarifa ankommen', 'Una llegada más tranquila', 'Rustiger aankomen in Tarifa', 'En lugnare ankomst i Tarifa')[lang], title: l('Use the garage as a base — then plan every other context', 'Die Garage als Basis nutzen – andere Kontexte separat planen', 'Usad el garaje como base y planificad cada otro contexto', 'Gebruik de garage als basis en plan andere contexten', 'Använd garaget som bas och planera övriga sammanhang')[lang], body: l('The included AMARA space can make July and August much easier at the accommodation. For old town, port and beach days, choose the destination first and check the current rule.', 'Der enthaltene AMARA-Platz kann Juli und August an der Unterkunft deutlich erleichtern. Für Altstadt, Hafen und Strandtage gilt: erst Ziel wählen, dann aktuelle Regel prüfen.', 'La plaza AMARA puede facilitar mucho julio y agosto en el alojamiento. Para casco antiguo, puerto y playas, elegid destino y comprobad la regla actual.', 'De AMARA-plek kan juli en augustus bij het verblijf sterk vereenvoudigen. Kies voor oude stad, haven en stranden eerst het doel en controleer de actuele regel.', 'AMARA-platsen kan göra juli och augusti betydligt enklare vid boendet. För gamla stan, hamn och stränder: välj mål först och kontrollera aktuell regel.')[lang], locationLabel: l('Explore Tarifa', 'Tarifa entdecken', 'Descubrir Tarifa', 'Ontdek Tarifa', 'Upptäck Tarifa')[lang], propertyLabel: l('View AMARA Family & Surf', 'AMARA Family & Surf ansehen', 'Ver AMARA Family & Surf', 'Bekijk AMARA Family & Surf', 'Se AMARA Family & Surf')[lang] }
});

export const tarifaParkingContent = Object.fromEntries(langs.map((lang) => [lang, makeLocale(lang)])) as Record<AmaraLanguage, ParkingGuideLocale>;
