import { defineKnowledgePageManifest } from '../../schema';

export const frigilianaLocationKnowledge = defineKnowledgePageManifest({
  id: 'page-frigiliana-location',
  destination: 'frigiliana',
  topic: 'location-hub',
  createdAt: '2026-08-28T18:00:00+02:00',
  updatedAt: '2026-08-28T18:00:00+02:00',
  status: 'needs-review',
  driveFolder: {
    id: '11ySQ05sa9Vjb8T6vzzef6os87OExdGuO',
    url: 'https://drive.google.com/drive/folders/11ySQ05sa9Vjb8T6vzzef6os87OExdGuO',
    path: 'AMARA – Research Vault/90_ARCHIVE/2026-08-24__121344__frigiliana-semantic-corpus-recovery__research-001',
  },
  publicContentPath: 'src/content/frigilianaLocationContent.ts',
  researchRunIds: [
    '2026-08-21__112650__geography-orientation__research-001',
    '2026-08-21__130535__where-to-stay-areas__research-001',
    '2026-08-21__142423__climate-seasons__research-001',
    '2026-08-21__184630__parking-accessibility__research-001',
    '2026-08-24__121344__frigiliana-semantic-corpus-recovery__research-001',
    '2026-08-24__121346__frigiliana-streetscape-overnight-atmosphere__research-001',
    '2026-08-28__092355__frigiliana-climate-seasons-decisions__research-001',
    '2026-08-28__092359__frigiliana-shopping-local-food-cooking__research-001',
  ],
  coverage: [
    {
      authoringArea: 'direct-answer-and-base-choice',
      purpose: 'Answer what changes when guests stay in Frigiliana for several nights instead of treating it as a short visit.',
      factIds: [
        'frigiliana.geography.historic-core.topography-shapes-layout',
        'frigiliana.atmosphere.evening-quiet.observation',
        'casa-amara.location.calle-chorruelo-calle-real',
      ],
      status: 'partial',
      notes: 'The hillside form, bounded evening observation and Casa AMARA position support the stay proposition. Village-wide quiet, exact visitor rhythms and superiority over Nerja must not be generalized.',
    },
    {
      authoringArea: 'orientation',
      purpose: 'Provide the mental map required to understand the historic core, later village, Sierra context and daily movement.',
      factIds: [
        'frigiliana.geography.main-settlement.reference-point',
        'frigiliana.geography.historic-core.topography-shapes-layout',
        'frigiliana.geography.ingenio.settlement-hinge',
        'frigiliana.geography.barribarto.medieval-core',
        'frigiliana.geography.barribajo.calle-real-axis',
        'frigiliana.geography.modern-expansion.ridge-south-of-ingenio',
        'frigiliana.geography.sierra.protected-area-context',
      ],
      status: 'covered',
      notes: 'Exact airport and Nerja distances or journey times require their own transport evidence and are not authorized by these geography facts.',
    },
    {
      authoringArea: 'overnight-rhythm',
      purpose: 'Explain the bounded host-observed difference between visiting the village and being present in the evening and morning.',
      factIds: [
        'frigiliana.atmosphere.evening-quiet.observation',
        'frigiliana.parking.operator-day-visitor-rhythm',
        'frigiliana.parking.day-and-overnight-demand-differ',
      ],
      status: 'partial',
      notes: 'These are first-party observations, not fixed-clock crowd data or a quiet guarantee for every date and address.',
    },
    {
      authoringArea: 'historic-village-context',
      purpose: 'Show why the old village looks and moves as it does without replacing the Old Town narrative.',
      factIds: [
        'frigiliana.heritage.historic-ensemble.bic',
        'frigiliana.history.muslim-civilization.deepest-urban-imprint',
        'frigiliana.heritage.streets.adarves-algorfas',
        'frigiliana.heritage.san-antonio.baroque',
      ],
      status: 'partial',
      notes: 'The hub may establish visible context and route to Old Town. Detailed chronology, the ceramic-panel walk and Casa AMARA building-age claims remain outside this owner.',
    },
    {
      authoringArea: 'areas-terrain-and-daily-routes',
      purpose: 'Translate hillside morphology into the stay-area and everyday walking decision.',
      factIds: [
        'frigiliana.stay.barribarto.medieval-core',
        'frigiliana.stay.barribajo.calle-real',
        'frigiliana.stay.ensanche.transition',
        'frigiliana.stay.southern-expansion',
        'frigiliana.stay.historic-mobility',
        'frigiliana.geography.routes.map-distance-insufficient',
      ],
      status: 'covered',
      notes: 'Area-level consequences are covered. Exact property routes, step counts and comparative elevation claims remain property evidence.',
    },
    {
      authoringArea: 'arrival-and-parking-overview',
      purpose: 'Prepare the airport-to-village and parking questions while keeping detailed rules with their specialist owners.',
      factIds: [
        'frigiliana.parking.orientation.lower-village',
        'frigiliana.parking.final-section-often-on-foot',
        'frigiliana.parking.final-walk-terrain-varies',
        'frigiliana.parking.availability-not-guaranteed',
      ],
      status: 'partial',
      notes: 'The hub may explain the planning consequence. Exact airport time, current bus/transfer operation, drop-off and Casa AMARA luggage route remain gaps.',
    },
    {
      authoringArea: 'daily-life-overview',
      purpose: 'Answer whether ordinary holiday essentials are available without turning the hub into a shop, health or restaurant directory.',
      factIds: [
        'frigiliana.shopping.eroski-city.address',
        'frigiliana.shopping.silvia.address-and-range',
        'frigiliana.shopping.garcia-berroa.address-and-range',
        'frigiliana.shopping.el-lagar.address-and-products',
      ],
      status: 'partial',
      notes: 'A bounded overview is possible. Current operation, precise walking routes, opening hours and host preference remain with Daily Life and its specialist manifests.',
    },
    {
      authoringArea: 'coast-and-nearby-nerja',
      purpose: 'Frame Frigiliana and Nerja as complementary parts of a stay, then hand beach and town-detail decisions to their owners.',
      factIds: [
        'nerja.beaches.burriana.profile-and-listed-services',
        'nerja.beaches.playazo.profile-and-listed-services',
        'nerja.beaches.maro.profile-and-seasonal-access',
      ],
      status: 'partial',
      notes: 'The hub may establish that materially different coast choices exist. Exact Frigiliana-to-coast journeys, parking and a winner comparison are not supported.',
    },
    {
      authoringArea: 'seasons-and-planning',
      purpose: 'State only the broad seasonal consequence and route to the Weather owner for climate detail and current forecast.',
      factIds: [
        'frigiliana.climate.regional-proxy.malaga-airport-method',
        'frigiliana.climate.regional-proxy.seasonal-contrast',
      ],
      status: 'partial',
      notes: 'The regional proxy must remain explicit. The hub must not reproduce unsupported local monthly values or convert climate into a current-condition promise.',
    },
    {
      authoringArea: 'casa-amara-location-projection',
      purpose: 'Use Casa AMARA as a truthful example of staying in the historic village without replacing the property narrative.',
      factIds: [
        'casa-amara.location.calle-chorruelo-calle-real',
        'casa-amara.access.shared-entrance-and-internal-steps',
        'casa-amara.access.village-core-route-after-door',
        'casa-amara.portfolio.four-stays-three-apartments-one-suite',
      ],
      status: 'partial',
      notes: 'Location, shared-door boundary and portfolio shape are supported. Exact parking-to-door route, comparative altitude, building age, restoration history and full amenity inventory are not authorized here.',
    },
    {
      authoringArea: 'current-route-and-distance-precision',
      purpose: 'Prevent current exact distance, duration, step and elevation values from surviving without a documented measurement owner.',
      factIds: [
        'frigiliana.geography.routes.map-distance-insufficient',
        'casa-amara.location.calle-chorruelo-calle-real',
        'casa-amara.access.village-core-route-after-door',
      ],
      status: 'gap',
      notes: 'The current 6-kilometre Nerja distance, 50–60-minute airport time, 150-metre/30-metre/30-step/3–5-minute property route and comparative lower-position claims require explicit route or transport evidence before reuse.',
    },
    {
      authoringArea: 'current-property-history-and-comfort',
      purpose: 'Keep building history, restoration and amenity claims with a dated property evidence owner.',
      factIds: ['casa-amara.portfolio.four-stays-three-apartments-one-suite'],
      status: 'gap',
      notes: 'The current building-age, well, 2020–2022 restoration, bathroom, shower, Wi-Fi, climate-control and heating narrative is not authorized by the shared Casa AMARA facts currently mapped to this hub.',
    },
    {
      authoringArea: 'faq-and-planning-routing',
      purpose: 'Answer only concise hub-level questions and route detail to Geography, Arrival, Parking, Streets & Stairs, Daily Life, Weather and property owners.',
      factIds: [
        'frigiliana.geography.historic-core.steps-and-road-access',
        'frigiliana.parking.availability-not-guaranteed',
        'casa-amara.access.shared-entrance-and-internal-steps',
      ],
      status: 'partial',
      notes: 'The routing role is clear. Existing transport, luggage, parking and property-access answers must be reconciled to the specialist manifests before authoring.',
    },
    {
      authoringArea: 'location-to-experience-transition',
      purpose: 'Move from the base decision to the variable menu of days only after the Frigiliana stay consequence is clear.',
      factIds: [
        'frigiliana.geography.sierra.protected-area-context',
        'frigiliana.climate.regional-proxy.seasonal-contrast',
        'frigiliana.atmosphere.evening-quiet.observation',
      ],
      status: 'partial',
      notes: 'These premises create next questions about walks, coast days and evenings. The Experience Hub owns the selection; the Location Hub must not duplicate its catalogue.',
    },
    {
      authoringArea: 'stay-decision-and-conversion',
      purpose: 'Introduce the AMARA stay choice only after village fit, terrain and daily-life consequences are understood.',
      factIds: [
        'casa-amara.portfolio.four-stays-three-apartments-one-suite',
        'casa-amara.location.calle-chorruelo-calle-real',
      ],
      status: 'partial',
      notes: 'The hub can route to the canonical property owner. It must not invent per-unit differences or turn destination evidence into a property promise.',
    },
    {
      authoringArea: 'excluded-specialist-detail',
      purpose: 'Keep complete route, beach, restaurant, parking, climate, property and private-arrival narratives with their canonical owners.',
      factIds: [],
      status: 'excluded',
      notes: 'The hub may create the next guest question and project only its necessary premise; it does not own specialist tables, route cards, live rules or property inventory.',
    },
  ],
});
