import { defineKnowledgeFacts } from '../../../schema';

export const frigilianaWhereToStayFacts = defineKnowledgeFacts([
  { id: 'frigiliana.stay.barribarto.medieval-core', subject: 'frigiliana', topic: 'where-to-stay-areas', statement: 'Barribarto is identified by the official heritage record as Frigiliana’s original medieval core.', status: 'verified', sourceIds: ['frigiliana-heritage-decree-2015'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'Historic morphology, not a present-day administrative boundary or universal access profile.' },
  { id: 'frigiliana.stay.barribajo.calle-real', subject: 'frigiliana', topic: 'where-to-stay-areas', statement: 'The official heritage description places Barribajo along the Calle Real axis.', status: 'verified', sourceIds: ['frigiliana-heritage-decree-2015'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'This supports a practical location model, not a parcel-level boundary.' },
  { id: 'frigiliana.stay.ensanche.transition', subject: 'frigiliana', topic: 'where-to-stay-areas', statement: 'The official description distinguishes an Ensanche transition around El Ingenio, El Apero, Maquinillas and Calle San Sebastián from both the older core and later southern expansion.', status: 'verified', sourceIds: ['frigiliana-heritage-decree-2015'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'A morphological transition area, not a current administrative accommodation district.' },
  { id: 'frigiliana.stay.southern-expansion', subject: 'frigiliana', topic: 'where-to-stay-areas', statement: 'Later Frigiliana expanded south of El Ingenio along the ridge and the Avenida de Andalucía and Príncipe de Asturias axes.', status: 'verified', sourceIds: ['frigiliana-heritage-decree-2015'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'The later area must not be equated with flat, step-free or universally easy vehicle access.' },
  { id: 'frigiliana.stay.historic-mobility', subject: 'frigiliana', topic: 'where-to-stay-areas', statement: 'In the protected historic fabric, contour-following streets and steep transverse links, many of them stepped, create materially different walking routes.', status: 'verified', sourceIds: ['frigiliana-heritage-decree-2015'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'No conclusion about a specific entrance, step count or accessibility follows without a route inspection.' },
  { id: 'frigiliana.stay.historic-vehicle-access', subject: 'frigiliana', topic: 'where-to-stay-areas', statement: 'Vehicle access to Frigiliana’s historic centre is municipally regulated.', status: 'partially-verified', sourceIds: ['frigiliana-historic-traffic-rule-2026'], checkedAt: '2026-08-21', reviewAfter: '2027-02-21', volatility: 'medium', claimBoundary: 'Current street-level permissions and loading rules must be checked before giving arrival advice.' },
  { id: 'frigiliana.stay.amara-san-antonio-distance', subject: 'frigiliana', topic: 'where-to-stay-areas', statement: 'AMARA’s current authoring places Casa AMARA about 15 metres from San Antonio church.', status: 'first-party-observation', sourceIds: ['amara-frigiliana-location-baseline-2026'], checkedAt: '2026-08-21', volatility: 'medium', claimBoundary: 'The reference points, measurement method and real walking route are not documented; public copy should say “near San Antonio” until measured.' }
] as const);
