import { defineKnowledgeFacts } from '../../../schema';

export const frigilianaWinterStaysFacts = defineKnowledgeFacts([
  { id: 'frigiliana.winter.historic-street-terrain', subject: 'frigiliana', topic: 'winter-stays', statement: 'Frigiliana’s official tourism information describes the historic streets as narrow, winding and steep.', status: 'verified', sourceIds: ['frigiliana-winter-streets-2026'], checkedAt: '2026-08-21', reviewAfter: '2028-08-21', volatility: 'low', claimBoundary: 'This supports terrain context, not a universal route, accessibility or surface claim for every address.' },
  { id: 'frigiliana.winter.el-fuerte-starts-in-village', subject: 'frigiliana', topic: 'winter-stays', statement: 'The official El Fuerte route description starts in Frigiliana and leaves the historic centre via steps.', status: 'verified', sourceIds: ['frigiliana-winter-el-fuerte-2026'], checkedAt: '2026-08-21', reviewAfter: '2027-08-21', volatility: 'medium', claimBoundary: 'The full route is not a universal casual walk; current weather, surface and route conditions require a day-specific check.' },
  { id: 'frigiliana.winter.one-business-winter-listing', subject: 'frigiliana', topic: 'winter-stays', statement: 'A municipal listing for The Garden Restaurant publishes a winter-opening context.', status: 'partially-verified', sourceIds: ['frigiliana-winter-garden-listing-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'high', claimBoundary: 'One business listing cannot support a town-wide year-round opening claim.' },
  { id: 'frigiliana.winter.amara-heating-baseline', subject: 'frigiliana', topic: 'winter-stays', statement: 'AMARA’s current authoring states that all four Frigiliana stays have heating.', status: 'first-party-observation', sourceIds: ['amara-frigiliana-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'medium', claimBoundary: 'Heating type, rooms served, operation and current inventory must be confirmed per stay in a dated property evidence pack.' },
  { id: 'frigiliana.winter.amara-bathroom-underfloor-heating-baseline', subject: 'frigiliana', topic: 'winter-stays', statement: 'AMARA’s current authoring states that the Casa AMARA bathrooms have underfloor heating.', status: 'first-party-observation', sourceIds: ['amara-frigiliana-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'medium', claimBoundary: 'Confirm the exact bathrooms, controls and operating status before public re-use.' },
  { id: 'frigiliana.winter.amara-pellet-stoves-baseline', subject: 'frigiliana', topic: 'winter-stays', statement: 'AMARA’s current authoring assigns pellet stoves to Lounis, Zaid and Maha.', status: 'first-party-observation', sourceIds: ['amara-frigiliana-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-11-21', volatility: 'medium', claimBoundary: 'Fuel supply, operating instructions, availability and safety arrangements require current operator confirmation.' },
  { id: 'frigiliana.winter.amara-duration-baseline', subject: 'frigiliana', topic: 'winter-stays', statement: 'AMARA’s current Frigiliana winter authoring offers stays from a few nights up to three weeks.', status: 'first-party-observation', sourceIds: ['amara-frigiliana-winter-baseline-2026'], checkedAt: '2026-08-21', reviewAfter: '2026-10-21', volatility: 'high', claimBoundary: 'Commercial duration and availability must be confirmed against current booking rules; this is not residential or monthly tenancy.' }
] as const);
