import { defineKnowledgePageManifest } from '../../schema';

export const frigilianaOldTownKnowledge = defineKnowledgePageManifest({
  id: 'page-frigiliana-old-town',
  destination: 'frigiliana',
  topic: 'old-town-history-walk',
  createdAt: '2026-08-28T18:30:00+02:00',
  updatedAt: '2026-08-28T18:30:00+02:00',
  status: 'needs-review',
  driveFolder: {
    id: '1QmNZHYefZNA0Sx6vTvGC00On5UP34HP_',
    url: 'https://drive.google.com/drive/folders/1QmNZHYefZNA0Sx6vTvGC00On5UP34HP_',
    path: 'AMARA – Research Vault/90_ARCHIVE/2026-08-24__121346__frigiliana-streetscape-overnight-atmosphere__research-001',
  },
  publicContentPath: 'src/content/frigilianaOldTownContent.ts',
  researchRunIds: [
    '2026-08-24__121344__frigiliana-semantic-corpus-recovery__research-001',
    '2026-08-24__121345__frigiliana-three-cultures-evidence__research-001',
    '2026-08-24__121346__frigiliana-streetscape-overnight-atmosphere__research-001',
    '2026-08-24__121347__frigiliana-agriculture-lived-landscape__research-001',
  ],
  coverage: [
    {
      authoringArea: 'direct-answer-and-walk-job',
      purpose: 'Explain what guests can notice on an old-town walk and which documented history makes the visible structure meaningful.',
      factIds: [
        'frigiliana.heritage.historic-ensemble.bic',
        'frigiliana.heritage.morisco-tradition.preservation',
        'frigiliana.heritage.streets.adarves-algorfas',
        'frigiliana.history.muslim-civilization.deepest-urban-imprint',
      ],
      status: 'covered',
      notes: 'The protected ensemble and visible urban-form premise are strong. The page must not promise a complete route or use the ceramic panels as unexamined historical proof.',
    },
    {
      authoringArea: 'visible-old-town-structure',
      purpose: 'Connect Calle Real, Barribajo, Barribarto, stepped links and protected street forms into a truthful mental walk.',
      factIds: [
        'frigiliana.geography.ingenio.settlement-hinge',
        'frigiliana.geography.barribarto.medieval-core',
        'frigiliana.geography.barribajo.calle-real-axis',
        'frigiliana.geography.historic-core.steps-and-road-access',
        'frigiliana.heritage.streets.adarves-algorfas',
      ],
      status: 'covered',
      notes: 'The structural sequence is supported; a fixed one-hour route, exact walking time or accessibility statement is not.',
    },
    {
      authoringArea: 'ceramic-panels',
      purpose: 'Treat the panels as public-history objects only after their commission, authorship, installation, sequence and source basis are documented.',
      factIds: [
        'frigiliana.history.morisco-uprising-expulsion-depopulation',
        'frigiliana.history.castillo-lizar.destroyed-1569',
      ],
      status: 'gap',
      notes: 'The current twelve-panel, hand-painted, sequential-route, 45-minute and “best way to understand” claims are not authorized. Historical facts must come from their canonical sources, not from assumed panel provenance.',
    },
    {
      authoringArea: 'el-ingenio',
      purpose: 'Explain El Ingenio as a visible historic and production landmark while preserving conflicts and access boundaries.',
      factIds: [
        'frigiliana.heritage.ingenio.origin-and-adaptation',
        'frigiliana.history.repopulation-and-sugar-recovery',
        'frigiliana.food.ingenio.current-cane-honey-production-claim',
      ],
      status: 'partial',
      notes: 'The official heritage owner describes a late-sixteenth-century residence later adapted for cane processing, while current public copy gives a 1725 industrial origin. The conflict must be reconciled before authoring. Current production is a bounded authority/producer claim; public access is not established.',
    },
    {
      authoringArea: 'casa-del-apero',
      purpose: 'Describe Casa del Apero, its date, former use and current public functions only from a normalized monument owner.',
      factIds: [],
      status: 'gap',
      notes: 'The current seventeenth-century, agricultural-storage, cultural-centre, library, archive and tourist-office claims are not represented in the canonical fact layer.',
    },
    {
      authoringArea: 'san-antonio',
      purpose: 'Correctly identify the church and its architectural period without freezing opening or event information.',
      factIds: ['frigiliana.heritage.san-antonio.baroque'],
      status: 'covered',
      notes: 'The Baroque classification and dating are supported. Interior access, service times and the church’s role in a specific future feria remain live or separate event evidence.',
    },
    {
      authoringArea: 'historical-sequence',
      purpose: 'Explain the documented rupture from conquest and forced Christianization through uprising, expulsion and later repopulation.',
      factIds: [
        'frigiliana.history.forced-christianization-and-1500-revolt',
        'frigiliana.history.morisco-uprising-expulsion-depopulation',
        'frigiliana.history.castillo-lizar.destroyed-1569',
        'frigiliana.history.repopulation-and-sugar-recovery',
        'frigiliana.history.villa-status-1640',
      ],
      status: 'covered',
      notes: 'The canonical sequence is supported. Exact battle-day chronology, troop counts or contemporary-chronicle interpretations require their own normalized facts.',
    },
    {
      authoringArea: 'three-cultures-boundary',
      purpose: 'Separate the modern public-history and festival frame from claims about medieval resident communities.',
      factIds: [
        'frigiliana.history.maymon-levi.taha-property-link',
        'frigiliana.culture.three-cultures.modern-public-history',
        'frigiliana.culture.three-cultures-festival.first-edition-2006',
      ],
      status: 'covered',
      notes: 'Do not infer a synagogue, permanent Jewish community or harmonious three-faith coexistence in Frigiliana from the Taha property link or modern festival.',
    },
    {
      authoringArea: 'preserved-material-character',
      purpose: 'Show how protected coatings, joinery and settlement form produce the visible old-town character.',
      factIds: [
        'frigiliana.heritage.exterior-view.compact-white-mass',
        'frigiliana.heritage.exterior-coatings.white',
        'frigiliana.heritage.woodwork.original-colour',
        'frigiliana.atmosphere.door-colour-variety.observation',
      ],
      status: 'partial',
      notes: 'White exterior treatment and preservation boundaries are supported. A representative door-colour route and detailed roof/material rules need specific evidence before broad visual claims.',
    },
    {
      authoringArea: 'living-heritage-esparto',
      purpose: 'Present a current craftsperson, workshop, process, demonstrations and booking only from current direct and first-party evidence.',
      factIds: [],
      status: 'gap',
      notes: 'The current Lourdes Bueno, El Rincón del Esparto, material-gathering, product and demonstration narrative has no canonical fact owner.',
    },
    {
      authoringArea: 'living-heritage-miel-de-cana',
      purpose: 'Connect visible production history to current miel de caña and bounded culinary uses without inventing provenance or access.',
      factIds: [
        'frigiliana.food.ingenio.current-cane-honey-production-claim',
        'frigiliana.food.traditional-dishes.municipal-tourism-set',
      ],
      status: 'partial',
      notes: 'Production association and selected municipal food uses are supported. The molasses distinction, arropía practice, continuous operation, raw-cane origin and visitor access require additional evidence.',
    },
    {
      authoringArea: 'market-festival-and-restaurant-transitions',
      purpose: 'Continue the walk only when the target page contains the matching current situation and practical consequence.',
      factIds: [
        'frigiliana.shopping.mercadillo.thursday-reference',
        'frigiliana.culture.three-cultures-festival.current-purpose',
        'frigiliana.restaurants.the-garden.position-and-format',
        'frigiliana.restaurants.la-taperia.position-and-cuisine',
      ],
      status: 'partial',
      notes: 'The target identities exist, but the current market route, festival operations, restaurant distribution and “few minutes” continuation claims are not jointly verified.',
    },
    {
      authoringArea: 'casa-amara-start-and-return',
      purpose: 'Place Casa AMARA near San Antonio as a bounded start or return context without turning the Old Town page into a property pitch.',
      factIds: [
        'casa-amara.location.calle-chorruelo-calle-real',
        'casa-amara.access.village-core-route-after-door',
      ],
      status: 'partial',
      notes: 'The central position and step-free route after the shared front-door step toward the village core are verified. “Lower old town”, comparative stair savings, shopping/luggage advantage and an exact walk require route evidence.',
    },
    {
      authoringArea: 'source-and-live-information-boundary',
      purpose: 'Expose stable heritage sources and keep openings, programmes, workshops and access as current checks.',
      factIds: [
        'frigiliana.heritage.historic-ensemble.bic',
        'frigiliana.heritage.san-antonio.baroque',
        'frigiliana.heritage.ingenio.origin-and-adaptation',
      ],
      status: 'partial',
      notes: 'The BOJA heritage record is a stable baseline. Current monument access, office functions, programmes and commercial operation require current direct sources.',
    },
  ],
});
