import { defineKnowledgePageManifest } from '../../schema';

export const frigilianaOldTownKnowledge = defineKnowledgePageManifest({
  id: 'page-frigiliana-old-town',
  destination: 'frigiliana',
  topic: 'old-town-history-walk',
  createdAt: '2026-08-28T18:30:00+02:00',
  updatedAt: '2026-09-13T16:10:00+02:00',
  status: 'needs-review',
  driveFolder: {
    id: '173h0XI3CxBVmTwcYIJBIGUanAjXRp2sw',
    url: 'https://drive.google.com/drive/folders/173h0XI3CxBVmTwcYIJBIGUanAjXRp2sw',
    path: 'AMARA – Research Vault/10_LOCATIONS/frigiliana/experiences/old-town',
  },
  publicContentPath: 'src/content/frigilianaOldTownContent.ts',
  researchRunIds: [
    '2026-08-24__121344__frigiliana-semantic-corpus-recovery__research-001',
    '2026-08-24__121345__frigiliana-three-cultures-evidence__research-001',
    '2026-08-24__121346__frigiliana-streetscape-overnight-atmosphere__research-001',
    '2026-08-24__121347__frigiliana-agriculture-lived-landscape__research-001',
    '2026-09-11__080827__frigiliana-ceramic-panels-provenance__research-001',
    '2026-09-11__123300__frigiliana-el-ingenio-provenance__research-001',
    '2026-09-11__133000__frigiliana-casa-del-apero-provenance__research-001',
    '2026-09-11__143000__frigiliana-san-antonio-provenance__research-001',
    '2026-09-13__150900__frigiliana-old-town-search-intent__research-001',
    '2026-09-13__150901__frigiliana-barribarto-entity__research-001',
    '2026-09-13__150902__frigiliana-calle-real-barribajo__research-001',
  ],
  coverage: [
    {
      authoringArea: 'direct-answer-and-walk-job',
      purpose: 'Explain what guests can notice on an old-town walk and which documented history makes the visible structure meaningful.',
      factIds: [
        'frigiliana.heritage.historic-ensemble.bic',
        'frigiliana.heritage.morisco-tradition.preservation',
        'frigiliana.heritage.streets.adarves-algorfas',
        'frigiliana.history.muslim-civilization.deepest-urban-imprint',
      ],
      status: 'covered',
      notes: 'The protected ensemble and visible urban-form premise are strong. The page must not promise a complete route or use the ceramic panels as unexamined historical proof.',
    },
    {
      authoringArea: 'visible-old-town-structure',
      purpose: 'Connect Calle Real, Barribajo, Barribarto, stepped links and protected street forms into a truthful mental walk.',
      factIds: [
        'frigiliana.geography.ingenio.settlement-hinge',
        'frigiliana.geography.barribarto.medieval-core',
        'frigiliana.geography.barribajo.calle-real-axis',
        'frigiliana.geography.historic-core.steps-and-road-access',
        'frigiliana.heritage.streets.adarves-algorfas',
      ],
      status: 'covered',
      notes: 'The structural sequence is supported; a fixed one-hour route, exact walking time or accessibility statement is not.',
    },
    {
      authoringArea: 'ceramic-panels',
      purpose: 'Author the panels as public-history objects: provenance, the twelve-panel sequence and the honest gap between the panels’ narrative and the documented record.',
      factIds: [
        'frigiliana.ceramic-panels.count.twelve',
        'frigiliana.ceramic-panels.installation.1982-beautification',
        'frigiliana.ceramic-panels.texts.navas-acosta',
        'frigiliana.ceramic-panels.ceramics.ruiz-de-luna',
        'frigiliana.ceramic-panels.technique.four-colours',
        'frigiliana.ceramic-panels.route.start-hernando-el-darra',
        'frigiliana.ceramic-panels.textual-basis.marmol-hurtado',
        'frigiliana.ceramic-panels.public-history.perspectival-inversion',
        'frigiliana.ceramic-panels.omission.28-may-1569',
        'frigiliana.ceramic-panels.anachronism.holocausto-patria',
        'frigiliana.ceramic-panels.casualties.figures',
      ],
      status: 'covered',
      notes: 'Provenance is now documented (research-001, 2026-09-11): twelve panels, installed 1982, texts by Navas Acosta, ceramics by Ruiz de Luna, four-colour technique. The twelve count and hand-painted, sequential-route claims are authorized. Exact per-panel positions (2–12) remain unverified — no turn-by-turn claim. Present the panels as 1982 public history and surface the documented differences (omitted 28 May 1569 assault; “Holocausto”/“patria” anachronisms), not as neutral primary proof.',
    },
    {
      authoringArea: 'el-ingenio',
      purpose: 'Author El Ingenio as its own authority spoke: the palace/sugar-works layers, the facade, miel de caña, the ibex on the roof and the access boundary.',
      factIds: [
        'frigiliana.ingenio.palace.manrique-de-lara-16c',
        'frigiliana.ingenio.lordship.manrique-1508',
        'frigiliana.ingenio.sugar.trapiche-to-ingenio-1725',
        'frigiliana.ingenio.archive.nobleza-toledo-1672-1730',
        'frigiliana.ingenio.facade.esgrafiado',
        'frigiliana.ingenio.facade.niches-and-sundials',
        'frigiliana.ingenio.mielcana.production-since-1725',
        'frigiliana.ingenio.mielcana.last-on-peninsula-attributed',
        'frigiliana.ingenio.ibex.cabra-montes-roofs',
        'frigiliana.ingenio.access.working-site',
        'frigiliana.heritage.ingenio.origin-and-adaptation',
        'frigiliana.history.repopulation-and-sugar-recovery',
        'frigiliana.food.ingenio.current-cane-honey-production-claim',
      ],
      status: 'covered',
      notes: 'Dating conflict reconciled by research-001 (2026-09-11): the 16th-century Manrique de Lara palace and the 1725 industrial ingenio are distinct layers of one building, both documented. Miel de caña produced since 1725 (factory Nuestra Señora del Carmen, 1950s mill train). Superlatives only attributed ("last ingenio of its kind on the peninsula", Diputación) — never "only factory in Europe". Ibex on the roof are wild cabra montés (not domestic goats/chamois); sightings not guaranteed. Working site — no promised public access.',
    },
    {
      authoringArea: 'casa-del-apero',
      purpose: 'Describe Casa del Apero: the early-17th-century ingenio annex, the fabric, and the current cultural-centre functions, keeping opening hours and admission as current checks.',
      factIds: [
        'frigiliana.casa-del-apero.origin.ingenio-annex-17c',
        'frigiliana.casa-del-apero.architecture.patio-tapial-brick',
        'frigiliana.casa-del-apero.restoration.1980s-1990s',
        'frigiliana.casa-del-apero.current-use.cultural-centre',
        'frigiliana.casa-del-apero.museum.archaeological',
      ],
      status: 'covered',
      notes: 'Covered by research-001 (2026-09-11): early-17th-century agricultural annex functionally linked to El Ingenio (granary, stables, apero store), rammed-earth-and-brick fabric around a patio, acquired early 1980s and restored through the 1990s; today the village cultural centre with library, archaeological museum, exhibition hall, historical archive and tourism office. Opening hours, admission and museum holdings stay current checks, not fixed facts. Photography for a spoke/tile is still missing.',
    },
    {
      authoringArea: 'san-antonio',
      purpose: 'Author San Antonio de Padua as its own spoke: the 1676 build on a former hermitage, the master builder and promoting bishop, the Latin-cross plan and Mudéjar armadura, and the official Baroque classification — without freezing opening or event information.',
      factIds: [
        'frigiliana.heritage.san-antonio.baroque',
        'frigiliana.san-antonio.build.1676-on-ermita',
        'frigiliana.san-antonio.builder.godoy-signed-beam',
        'frigiliana.san-antonio.promoter.bishop-santo-tomas',
        'frigiliana.san-antonio.plan.latin-cross-armadura',
        'frigiliana.san-antonio.style.baroque-classification',
      ],
      status: 'covered',
      notes: 'Authored as its own spoke by research-001 (2026-09-11): present church built 1676 on the site of an earlier hermitage beside Calle Real; master builder Bernardo de Godoy (signed roof beam quoted); promoted under Bishop Fray Alonso de Santo Tomás (coat of arms on the façade); Latin-cross plan, three naves with semi-circular arches, Mudéjar timber armadura; official Baroque classification supersedes the older Renaissance reading. The Mudéjar timber roof is a construction feature, not a competing style. Interior access, service times and any feria role stay current checks, not fixed facts. Photography for a spoke/tile is still missing.',
    },
    {
      authoringArea: 'old-town-monuments',
      purpose: 'Author five further old-town sights as their own spokes: the Fuente Vieja, the Castillo de Lizar ruins, Los Reales Pósitos, the Ermita de Ecce Homo and the Callejón del Peñón with its miradores.',
      factIds: [
        'frigiliana.fuente-vieja.build.1640-manrique',
        'frigiliana.fuente-vieja.name.fuente-nueva-origin',
        'frigiliana.fuente-vieja.spouts-and-trough',
        'frigiliana.fuente-vieja.decoration.pomegranate-pediment',
        'frigiliana.fuente-vieja.restoration.1990s',
        'frigiliana.fuente-vieja.location.plaza-calle-chorruelo',
        'frigiliana.castillo-lizar.moorish-fortress.9-11c',
        'frigiliana.castillo-lizar.razed.requesens-1569',
        'frigiliana.castillo-lizar.stone-reused-ingenio',
        'frigiliana.castillo-lizar.remains',
        'frigiliana.castillo-lizar.bic.1985',
        'frigiliana.castillo-lizar.distinct-from-el-fuerte',
        'frigiliana.reales-positos.grain-store.1767',
        'frigiliana.reales-positos.institution.pre-1767',
        'frigiliana.reales-positos.architecture.three-naves-arcades',
        'frigiliana.reales-positos.location.calle-real',
        'frigiliana.ermita-ecce-homo.chapel.18c',
        'frigiliana.ermita-ecce-homo.procession.holy-wednesday',
        'frigiliana.ermita-ecce-homo.name.cana-reed-scepter',
        'frigiliana.ermita-ecce-homo.figure.neo-baroque-20c',
        'frigiliana.ermita-ecce-homo.architecture.portico-hillside',
        'frigiliana.ermita-ecce-homo.devotion.post-morisco-interpretation',
        'frigiliana.callejon-penon.lane.barribarto-photographed',
        'frigiliana.callejon-penon.mirador.panorama',
        'frigiliana.callejon-penon.name.local-penon-not-battle-mount',
        'frigiliana.callejon-penon.named-miradores',
        'frigiliana.callejon-penon.adarves',
        'frigiliana.history.castillo-lizar.destroyed-1569',
      ],
      status: 'covered',
      notes: 'Graduated to dedicated spoke fact files by the 2026-09-12 web synthesis (facts/locations/frigiliana/{fuente-vieja,castillo-lizar,reales-positos,ermita-ecce-homo,callejon-penon}.ts; the bundled old-town-monuments.ts was retired). Municipal (turismofrigiliana.es), provincial (malaga.es) and heritage (BOJA Decreto 183/2014) sources verified the datings and corrected four operator-brief points: the Ermita procession is Miércoles Santo (Holy Wednesday), not Good Friday, and carries to San Antonio; "Santo Cristo de la Caña" is the reed mock-sceptre of the Ecce Homo, not sugar cane; the Fuente Vieja is a two-storey stone façade (coat of arms in the upper central field), not a brick arch, and its builder was the fifth Señor AND first Count; the Callejón del Peñón has a documented panorama over village/mountains/sea but no sourced "clearest view of / frames El Fuerte" — its "Peñón" is a local rock, distinct from the battle mount. Added detail: Castillo de Lizar razed under Requesens with Philip II’s approval and its stone reused for El Ingenio (~4,000 m²; BIC 1985); Reales Pósitos built by the counts, originally three naves of round arches. Live details (Ermita worship/procession times; Castillo open-ruin and Reales Pósitos private access) stay current checks. Photography exists only for the Fuente Vieja; the other four spokes use a typographic cover. The 2026-09-12 web synthesis that graduated these five fact files was recorded only through its sources (frigilianaOldTownMonumentsSources) and facts; it has no research-run record and no Drive run folder, so no run id is listed for it. The 2026-09-13 runs flag three positions for on-site confirmation (Fuente Vieja: operator pin vs inventory UTM; Reales Pósitos: Calle Real 1 vs the spoke’s Hernando el Darra coordinate; Ermita: end of Chorruelo vs the spoke’s coordinate near the church) and supersede frigiliana.callejon-penon.named-miradores: the Plaza de las Tres Culturas is in the lower village, not a mirador beside the Callejón. The affected spoke texts wait for the operator’s correction.',
    },
    {
      authoringArea: 'historical-sequence',
      purpose: 'Explain the documented rupture from conquest and forced Christianization through uprising, expulsion and later repopulation.',
      factIds: [
        'frigiliana.history.forced-christianization-and-1500-revolt',
        'frigiliana.history.morisco-uprising-expulsion-depopulation',
        'frigiliana.history.castillo-lizar.destroyed-1569',
        'frigiliana.history.repopulation-and-sugar-recovery',
        'frigiliana.history.villa-status-1640',
      ],
      status: 'covered',
      notes: 'The canonical sequence is supported. Exact battle-day chronology, troop counts or contemporary-chronicle interpretations require their own normalized facts.',
    },
    {
      authoringArea: 'three-cultures-boundary',
      purpose: 'Separate the modern public-history and festival frame from claims about medieval resident communities.',
      factIds: [
        'frigiliana.history.maymon-levi.taha-property-link',
        'frigiliana.culture.three-cultures.modern-public-history',
        'frigiliana.culture.three-cultures-festival.first-edition-2006',
      ],
      status: 'covered',
      notes: 'Do not infer a synagogue, permanent Jewish community or harmonious three-faith coexistence in Frigiliana from the Taha property link or modern festival.',
    },
    {
      authoringArea: 'preserved-material-character',
      purpose: 'Show how protected coatings, joinery and settlement form produce the visible old-town character.',
      factIds: [
        'frigiliana.heritage.exterior-view.compact-white-mass',
        'frigiliana.heritage.exterior-coatings.white',
        'frigiliana.heritage.woodwork.original-colour',
        'frigiliana.atmosphere.door-colour-variety.observation',
      ],
      status: 'partial',
      notes: 'White exterior treatment and preservation boundaries are supported. A representative door-colour route and detailed roof/material rules need specific evidence before broad visual claims.',
    },
    {
      authoringArea: 'living-heritage-esparto',
      purpose: 'Present a current craftsperson, workshop, process, demonstrations and booking only from current direct and first-party evidence.',
      factIds: [],
      status: 'gap',
      notes: 'The current Lourdes Bueno, El Rincón del Esparto, material-gathering, product and demonstration narrative has no canonical fact owner.',
    },
    {
      authoringArea: 'living-heritage-miel-de-cana',
      purpose: 'Connect visible production history to current miel de caña and bounded culinary uses without inventing provenance or access.',
      factIds: [
        'frigiliana.food.ingenio.current-cane-honey-production-claim',
        'frigiliana.food.traditional-dishes.municipal-tourism-set',
      ],
      status: 'partial',
      notes: 'Production association and selected municipal food uses are supported. The molasses distinction, arropía practice, continuous operation, raw-cane origin and visitor access require additional evidence.',
    },
    {
      authoringArea: 'market-festival-and-restaurant-transitions',
      purpose: 'Continue the walk only when the target page contains the matching current situation and practical consequence.',
      factIds: [
        'frigiliana.shopping.mercadillo.thursday-reference',
        'frigiliana.culture.three-cultures-festival.current-purpose',
        'frigiliana.restaurants.the-garden.position-and-format',
        'frigiliana.restaurants.la-taperia.position-and-cuisine',
      ],
      status: 'partial',
      notes: 'The target identities exist, but the current market route, festival operations, restaurant distribution and “few minutes” continuation claims are not jointly verified.',
    },
    {
      authoringArea: 'casa-amara-start-and-return',
      purpose: 'Place Casa AMARA near San Antonio as a bounded start or return context without turning the Old Town page into a property pitch.',
      factIds: [
        'casa-amara.location.calle-chorruelo-calle-real',
        'casa-amara.access.village-core-route-after-door',
        'casa-amara.location.inside-conjunto-historico-bic',
        'frigiliana.calle-real.becomes-chorruelo-at-plaza-iglesia',
        'frigiliana.barribarto.casa-amara.on-axis-not-inside-quarter',
      ],
      status: 'covered',
      notes: 'The central position and step-free route after the shared front-door step toward the village core are verified. Since the 2026-09-13 Calle Real run the position is also documented officially: the parcel (Catastro 9925509VF2792N, block 99255 parcel 09) is in the decree’s BIC parcel list, so “inside the protected historic ensemble, on its western edge” is publishable, and the municipality confirms that Calle Real becomes Calle Chorruelo at the Plaza de la Iglesia. The house is on the Calle Real axis, not inside the Barribarto. Comparative stair savings, shopping/luggage advantage and exact walking figures still require the operator’s route measurements.',
    },
    {
      authoringArea: 'source-and-live-information-boundary',
      purpose: 'Expose stable heritage sources and keep openings, programmes, workshops and access as current checks.',
      factIds: [
        'frigiliana.heritage.historic-ensemble.bic',
        'frigiliana.heritage.san-antonio.baroque',
        'frigiliana.heritage.ingenio.origin-and-adaptation',
      ],
      status: 'partial',
      notes: 'The BOJA heritage record is a stable baseline. Current monument access, office functions, programmes and commercial operation require current direct sources.',
    },
    {
      authoringArea: 'search-intent-and-page-set',
      purpose: 'Decide the page set, titles and long-tail ownership of the old-town cluster from documented search demand rather than from the monument list.',
      factIds: [],
      status: 'partial',
      notes: 'Search-intent run 2026-09-13 (dossier research/locations/frigiliana/old-town-search-intent/2026-09-13-normalized.md): blog listicles dominate every language; official pages win only entity queries; two rental hosts already rank. Decisions proposed to the operator: a Barribarto page scoped as the upper-quarter street-and-adarve page (mirroring Calle Real & Barribajo; viewpoints stay on the Callejón page); brand-free hub titles per locale with NL “oude centrum” and SV “gamla stadskärna”; old-town walks titled with the place, since bare “Rundgang / walking route / wandelroute” is hiking intent; a logistics bar (named car parks with prices, a “how long” answer, an FAQ, a route map) that the ranking pages carry. No facts are created by a demand study; the SERP claims it flagged live as open questions (white-façade basis, panel installation date, castle hill name).',
    },
    {
      authoringArea: 'barribarto-entity',
      purpose: 'Author the Barribarto as its own documented place: the decree typology, the name, the eleven adarves, the municipal walks, the miradores that really neighbour the Callejón del Peñón, and the position of Casa AMARA relative to the quarter.',
      factIds: [
        'frigiliana.barribarto.decree.medieval-core-typology',
        'frigiliana.barribarto.name.barrio-alto',
        'frigiliana.barribarto.adarves.eleven-named',
        'frigiliana.barribarto.adarves.decree-entry-types',
        'frigiliana.barribarto.zacatin.name-meaning',
        'frigiliana.barribarto.callejon-penon.mirador-urbano-and-santo-cristo',
        'frigiliana.barribarto.plaza-tres-culturas.lower-village',
        'frigiliana.barribarto.official-itineraries.three-plus-panels',
        'frigiliana.barribarto.official-walk.almona-garral-zacatin-lizar-penon',
        'frigiliana.barribarto.lpmbe.miradores-adarves-six-stops',
        'frigiliana.barribarto.tours.no-official-audio-guide',
        'frigiliana.barribarto.casa-amara.on-axis-not-inside-quarter',
        'frigiliana.barribarto.festival-market.lower-plazas',
        'frigiliana.barribarto.santo-cristo.new-mirador-2021',
        'frigiliana.barribarto.castillo.outside-bic-inside-entorno',
        'frigiliana.barribarto.whitewash.municipal-no-bye-law-statement',
      ],
      status: 'covered',
      notes: 'Barribarto run 2026-09-13 (dossier research/locations/frigiliana/barribarto/2026-09-13-normalized.md). The decree, the municipal tourism site, the Diputación and IGN CartoCiudad carry the entity; no Wikidata item exists for the Barribarto, the Reales Pósitos, the Ermita or any mirador. Correction candidate for the Callejón spoke: the Plaza de las Tres Culturas is in the lower village, not a neighbouring mirador (fact frigiliana.callejon-penon.named-miradores superseded). Which lanes are adarves in the decree’s sense, the platforms of the three miradores and the 2021 Santo Cristo mirador remain open; step counts, surfaces and views are the operator’s field work.',
    },
    {
      authoringArea: 'calle-real-barribajo',
      purpose: 'Author the lower old town from evidence: the decree’s Barribajo and Ensanche, El Torreón, the town hall, Calle Real as the only vehicle street that becomes Calle Chorruelo, the plazas, the 1640 and 1982 milestones, and the frontage of the Reales Pósitos and the position of the Ermita.',
      factIds: [
        'frigiliana.calle-real.decree.barribajo-typology',
        'frigiliana.calle-real.decree.ensanche-shops',
        'frigiliana.calle-real.decree.torreon-special-interest-preemption',
        'frigiliana.calle-real.only-vehicle-street-one-way',
        'frigiliana.calle-real.becomes-chorruelo-at-plaza-iglesia',
        'frigiliana.calle-real.chorruelo.former-last-street',
        'frigiliana.calle-real.length.about-half-km',
        'frigiliana.calle-real.numbering.rises-toward-church',
        'frigiliana.calle-real.torreon.18c-posito-site',
        'frigiliana.calle-real.torreon.hotel-since-2017',
        'frigiliana.calle-real.ayuntamiento.seat-cuesta-del-apero-10',
        'frigiliana.calle-real.casa-consistorial.plazuela-calle-real',
        'frigiliana.calle-real.plaza-ingenio.bus-and-car-park',
        'frigiliana.history.villa-1640.independence-ayuntamiento',
        'frigiliana.heritage.1982-award.premios-nacionales-turismo',
        'frigiliana.calle-real.reales-positos.frontage-calle-real-1',
        'frigiliana.calle-real.ermita.beyond-chorruelo-end',
      ],
      status: 'covered',
      notes: 'Calle Real & Barribajo run 2026-09-13 (dossier research/locations/frigiliana/calle-real-barribajo/2026-09-13-normalized.md). The existing spoke was authored without a run; this evidence supports its material revision. Two correction candidates for other spokes: the Reales Pósitos front Calle Real 1 (the spoke says Hernando el Darra with a coordinate about 100 m west) and the Ermita stands at the far end of Calle Chorruelo (the spoke’s coordinate is near the church and its “three minutes on the flat” is unsupported). The town-hall seat vs the historic Casa Consistorial on the Calle Real plazuela stays open. El Torreón is named only as the building’s current use, never promoted.',
    },
    {
      authoringArea: 'spatial-data-and-map-geometry',
      purpose: 'Provide the coordinates, official street geometry and height ladder for an old-town map drawn from real geometry, with distances, steps and heights from Casa AMARA measured on site.',
      factIds: [
        'casa-amara.location.inside-conjunto-historico-bic',
        'frigiliana.barribarto.cartociudad.official-street-geometry',
        'frigiliana.barribarto.fountains.stated-elevations',
        'frigiliana.barribarto.plaza-tres-culturas.lower-village',
        'frigiliana.calle-real.stepped-lanes-off-calle-real',
        'frigiliana.calle-real.length.about-half-km',
      ],
      status: 'partial',
      notes: 'Official centrelines (IGN CartoCiudad) and OSM steps/buildings are the geometry base; Wikidata QIDs exist for the church, plazas, fountains, town hall and Calle Real. Stated elevations exist only for four fountains (305–328 m); all other heights are EU-DEM ±10–15 m and must never become step, gradient or accessibility claims. Three landmark positions are disputed until the operator’s GPS fixes (Fuente Vieja, Reales Pósitos, Ermita), and the spoke logistics blocks were authored without a common measured baseline (El Ingenio “flat, three minutes” beside Casa del Apero “500 m, ten minutes”). The field measurement — metres, steps up and down, height gain, surface, minutes from the door of Casa AMARA to each sight — closes open questions frigiliana.geography.question.street-elevations-and-gradients and frigiliana.geography.question.property-routes and is the prerequisite for the map and for a consistent logistics block on all spokes.',
    },
  ],
});
