import { defineKnowledgePageManifest } from '../../schema';

export const frigilianaOldTownKnowledge = defineKnowledgePageManifest({
  id: 'page-frigiliana-old-town',
  destination: 'frigiliana',
  topic: 'old-town-history-walk',
  createdAt: '2026-08-28T18:30:00+02:00',
  updatedAt: '2026-09-11T08:20:00+02:00',
  status: 'needs-review',
  driveFolder: {
    id: '173h0XI3CxBVmTwcYIJBIGUanAjXRp2sw',
    url: 'https://drive.google.com/drive/folders/173h0XI3CxBVmTwcYIJBIGUanAjXRp2sw',
    path: 'AMARA – Research Vault/10_LOCATIONS/frigiliana/experiences/old-town',
  },
  publicContentPath: 'src/content/frigilianaOldTownContent.ts',
  researchRunIds: [
    '2026-08-24__121344__frigiliana-semantic-corpus-recovery__research-001',
    '2026-08-24__121345__frigiliana-three-cultures-evidence__research-001',
    '2026-08-24__121346__frigiliana-streetscape-overnight-atmosphere__research-001',
    '2026-08-24__121347__frigiliana-agriculture-lived-landscape__research-001',
    '2026-09-11__080827__frigiliana-ceramic-panels-provenance__research-001',
    '2026-09-11__123300__frigiliana-el-ingenio-provenance__research-001',
    '2026-09-11__133000__frigiliana-casa-del-apero-provenance__research-001',
    '2026-09-11__143000__frigiliana-san-antonio-provenance__research-001',
  ],
  coverage: [
    {
      authoringArea: 'direct-answer-and-walk-job',
      purpose: 'Explain what guests can notice on an old-town walk and which documented history makes the visible structure meaningful.',
      factIds: [
        'frigiliana.heritage.historic-ensemble.bic',
        'frigiliana.heritage.morisco-tradition.preservation',
        'frigiliana.heritage.streets.adarves-algorfas',
        'frigiliana.history.muslim-civilization.deepest-urban-imprint',
      ],
      status: 'covered',
      notes: 'The protected ensemble and visible urban-form premise are strong. The page must not promise a complete route or use the ceramic panels as unexamined historical proof.',
    },
    {
      authoringArea: 'visible-old-town-structure',
      purpose: 'Connect Calle Real, Barribajo, Barribarto, stepped links and protected street forms into a truthful mental walk.',
      factIds: [
        'frigiliana.geography.ingenio.settlement-hinge',
        'frigiliana.geography.barribarto.medieval-core',
        'frigiliana.geography.barribajo.calle-real-axis',
        'frigiliana.geography.historic-core.steps-and-road-access',
        'frigiliana.heritage.streets.adarves-algorfas',
      ],
      status: 'covered',
      notes: 'The structural sequence is supported; a fixed one-hour route, exact walking time or accessibility statement is not.',
    },
    {
      authoringArea: 'ceramic-panels',
      purpose: 'Author the panels as public-history objects: provenance, the twelve-panel sequence and the honest gap between the panels’ narrative and the documented record.',
      factIds: [
        'frigiliana.ceramic-panels.count.twelve',
        'frigiliana.ceramic-panels.installation.1982-beautification',
        'frigiliana.ceramic-panels.texts.navas-acosta',
        'frigiliana.ceramic-panels.ceramics.ruiz-de-luna',
        'frigiliana.ceramic-panels.technique.four-colours',
        'frigiliana.ceramic-panels.route.start-hernando-el-darra',
        'frigiliana.ceramic-panels.textual-basis.marmol-hurtado',
        'frigiliana.ceramic-panels.public-history.perspectival-inversion',
        'frigiliana.ceramic-panels.omission.28-may-1569',
        'frigiliana.ceramic-panels.anachronism.holocausto-patria',
        'frigiliana.ceramic-panels.casualties.figures',
      ],
      status: 'covered',
      notes: 'Provenance is now documented (research-001, 2026-09-11): twelve panels, installed 1982, texts by Navas Acosta, ceramics by Ruiz de Luna, four-colour technique. The twelve count and hand-painted, sequential-route claims are authorized. Exact per-panel positions (2–12) remain unverified — no turn-by-turn claim. Present the panels as 1982 public history and surface the documented differences (omitted 28 May 1569 assault; “Holocausto”/“patria” anachronisms), not as neutral primary proof.',
    },
    {
      authoringArea: 'el-ingenio',
      purpose: 'Author El Ingenio as its own authority spoke: the palace/sugar-works layers, the facade, miel de caña, the ibex on the roof and the access boundary.',
      factIds: [
        'frigiliana.ingenio.palace.manrique-de-lara-16c',
        'frigiliana.ingenio.lordship.manrique-1508',
        'frigiliana.ingenio.sugar.trapiche-to-ingenio-1725',
        'frigiliana.ingenio.archive.nobleza-toledo-1672-1730',
        'frigiliana.ingenio.facade.esgrafiado',
        'frigiliana.ingenio.facade.niches-and-sundials',
        'frigiliana.ingenio.mielcana.production-since-1725',
        'frigiliana.ingenio.mielcana.last-on-peninsula-attributed',
        'frigiliana.ingenio.ibex.cabra-montes-roofs',
        'frigiliana.ingenio.access.working-site',
        'frigiliana.heritage.ingenio.origin-and-adaptation',
        'frigiliana.history.repopulation-and-sugar-recovery',
        'frigiliana.food.ingenio.current-cane-honey-production-claim',
      ],
      status: 'covered',
      notes: 'Dating conflict reconciled by research-001 (2026-09-11): the 16th-century Manrique de Lara palace and the 1725 industrial ingenio are distinct layers of one building, both documented. Miel de caña produced since 1725 (factory Nuestra Señora del Carmen, 1950s mill train). Superlatives only attributed ("last ingenio of its kind on the peninsula", Diputación) — never "only factory in Europe". Ibex on the roof are wild cabra montés (not domestic goats/chamois); sightings not guaranteed. Working site — no promised public access.',
    },
    {
      authoringArea: 'casa-del-apero',
      purpose: 'Describe Casa del Apero: the early-17th-century ingenio annex, the fabric, and the current cultural-centre functions, keeping opening hours and admission as current checks.',
      factIds: [
        'frigiliana.casa-del-apero.origin.ingenio-annex-17c',
        'frigiliana.casa-del-apero.architecture.patio-tapial-brick',
        'frigiliana.casa-del-apero.restoration.1980s-1990s',
        'frigiliana.casa-del-apero.current-use.cultural-centre',
        'frigiliana.casa-del-apero.museum.archaeological',
      ],
      status: 'covered',
      notes: 'Covered by research-001 (2026-09-11): early-17th-century agricultural annex functionally linked to El Ingenio (granary, stables, apero store), rammed-earth-and-brick fabric around a patio, acquired early 1980s and restored through the 1990s; today the village cultural centre with library, archaeological museum, exhibition hall, historical archive and tourism office. Opening hours, admission and museum holdings stay current checks, not fixed facts. Photography for a spoke/tile is still missing.',
    },
    {
      authoringArea: 'san-antonio',
      purpose: 'Author San Antonio de Padua as its own spoke: the 1676 build on a former hermitage, the master builder and promoting bishop, the Latin-cross plan and Mudéjar armadura, and the official Baroque classification — without freezing opening or event information.',
      factIds: [
        'frigiliana.heritage.san-antonio.baroque',
        'frigiliana.san-antonio.build.1676-on-ermita',
        'frigiliana.san-antonio.builder.godoy-signed-beam',
        'frigiliana.san-antonio.promoter.bishop-santo-tomas',
        'frigiliana.san-antonio.plan.latin-cross-armadura',
        'frigiliana.san-antonio.style.baroque-classification',
      ],
      status: 'covered',
      notes: 'Authored as its own spoke by research-001 (2026-09-11): present church built 1676 on the site of an earlier hermitage beside Calle Real; master builder Bernardo de Godoy (signed roof beam quoted); promoted under Bishop Fray Alonso de Santo Tomás (coat of arms on the façade); Latin-cross plan, three naves with semi-circular arches, Mudéjar timber armadura; official Baroque classification supersedes the older Renaissance reading. The Mudéjar timber roof is a construction feature, not a competing style. Interior access, service times and any feria role stay current checks, not fixed facts. Photography for a spoke/tile is still missing.',
    },
    {
      authoringArea: 'historical-sequence',
      purpose: 'Explain the documented rupture from conquest and forced Christianization through uprising, expulsion and later repopulation.',
      factIds: [
        'frigiliana.history.forced-christianization-and-1500-revolt',
        'frigiliana.history.morisco-uprising-expulsion-depopulation',
        'frigiliana.history.castillo-lizar.destroyed-1569',
        'frigiliana.history.repopulation-and-sugar-recovery',
        'frigiliana.history.villa-status-1640',
      ],
      status: 'covered',
      notes: 'The canonical sequence is supported. Exact battle-day chronology, troop counts or contemporary-chronicle interpretations require their own normalized facts.',
    },
    {
      authoringArea: 'three-cultures-boundary',
      purpose: 'Separate the modern public-history and festival frame from claims about medieval resident communities.',
      factIds: [
        'frigiliana.history.maymon-levi.taha-property-link',
        'frigiliana.culture.three-cultures.modern-public-history',
        'frigiliana.culture.three-cultures-festival.first-edition-2006',
      ],
      status: 'covered',
      notes: 'Do not infer a synagogue, permanent Jewish community or harmonious three-faith coexistence in Frigiliana from the Taha property link or modern festival.',
    },
    {
      authoringArea: 'preserved-material-character',
      purpose: 'Show how protected coatings, joinery and settlement form produce the visible old-town character.',
      factIds: [
        'frigiliana.heritage.exterior-view.compact-white-mass',
        'frigiliana.heritage.exterior-coatings.white',
        'frigiliana.heritage.woodwork.original-colour',
        'frigiliana.atmosphere.door-colour-variety.observation',
      ],
      status: 'partial',
      notes: 'White exterior treatment and preservation boundaries are supported. A representative door-colour route and detailed roof/material rules need specific evidence before broad visual claims.',
    },
    {
      authoringArea: 'living-heritage-esparto',
      purpose: 'Present a current craftsperson, workshop, process, demonstrations and booking only from current direct and first-party evidence.',
      factIds: [],
      status: 'gap',
      notes: 'The current Lourdes Bueno, El Rincón del Esparto, material-gathering, product and demonstration narrative has no canonical fact owner.',
    },
    {
      authoringArea: 'living-heritage-miel-de-cana',
      purpose: 'Connect visible production history to current miel de caña and bounded culinary uses without inventing provenance or access.',
      factIds: [
        'frigiliana.food.ingenio.current-cane-honey-production-claim',
        'frigiliana.food.traditional-dishes.municipal-tourism-set',
      ],
      status: 'partial',
      notes: 'Production association and selected municipal food uses are supported. The molasses distinction, arropía practice, continuous operation, raw-cane origin and visitor access require additional evidence.',
    },
    {
      authoringArea: 'market-festival-and-restaurant-transitions',
      purpose: 'Continue the walk only when the target page contains the matching current situation and practical consequence.',
      factIds: [
        'frigiliana.shopping.mercadillo.thursday-reference',
        'frigiliana.culture.three-cultures-festival.current-purpose',
        'frigiliana.restaurants.the-garden.position-and-format',
        'frigiliana.restaurants.la-taperia.position-and-cuisine',
      ],
      status: 'partial',
      notes: 'The target identities exist, but the current market route, festival operations, restaurant distribution and “few minutes” continuation claims are not jointly verified.',
    },
    {
      authoringArea: 'casa-amara-start-and-return',
      purpose: 'Place Casa AMARA near San Antonio as a bounded start or return context without turning the Old Town page into a property pitch.',
      factIds: [
        'casa-amara.location.calle-chorruelo-calle-real',
        'casa-amara.access.village-core-route-after-door',
      ],
      status: 'partial',
      notes: 'The central position and step-free route after the shared front-door step toward the village core are verified. “Lower old town”, comparative stair savings, shopping/luggage advantage and an exact walk require route evidence.',
    },
    {
      authoringArea: 'source-and-live-information-boundary',
      purpose: 'Expose stable heritage sources and keep openings, programmes, workshops and access as current checks.',
      factIds: [
        'frigiliana.heritage.historic-ensemble.bic',
        'frigiliana.heritage.san-antonio.baroque',
        'frigiliana.heritage.ingenio.origin-and-adaptation',
      ],
      status: 'partial',
      notes: 'The BOJA heritage record is a stable baseline. Current monument access, office functions, programmes and commercial operation require current direct sources.',
    },
  ],
});
