#!/usr/bin/env node

const API_ORIGIN = 'https://api.lodgify.com';
const WINDOW_DAYS = 45;
const ADULTS = 2;

const status = {
  AUTH: 'FAIL',
  PROPERTY: 'FAIL',
  'ROOM TYPE': 'FAIL',
  AVAILABILITY: 'FAIL',
  RATES: 'FAIL',
  QUOTE: 'FAIL',
  OVERALL: 'FAIL',
};

function printStatus() {
  console.log('\nSTATUS');
  for (const [label, value] of Object.entries(status)) console.log(`${label}: ${value}`);
}

function fail(message, exitCode = 1) {
  console.error(`\nFAIL: ${message}`);
  printStatus();
  process.exitCode = exitCode;
}

const apiKey = process.env.LODGIFY_API_KEY;
if (!apiKey) {
  fail('LODGIFY_API_KEY is missing. Add it locally to .env; never commit it.');
} else {
  await main();
}

async function getAllowed(pathname, searchParams = {}, options = {}) {
  const url = new URL(pathname, API_ORIGIN);
  for (const [key, value] of Object.entries(searchParams)) url.searchParams.append(key, String(value));

  let response;
  try {
    response = await fetch(url, {
      method: 'GET',
      headers: { 'X-ApiKey': apiKey, Accept: 'application/json' },
      signal: AbortSignal.timeout(20_000),
    });
  } catch (error) {
    throw new Error(`Network failure while contacting Lodgify: ${error.message}`);
  }

  const safeLodgifyError = !response.ok && options.captureSafeError
    ? await readSafeLodgifyError(response)
    : undefined;
  if (response.status === 401) {
    const error = new Error('Lodgify rejected the credential (HTTP 401).');
    error.httpStatus = response.status;
    error.lodgifyError = safeLodgifyError;
    throw error;
  }
  if (response.status === 429) {
    const retryAfter = response.headers.get('retry-after');
    const error = new Error(`Lodgify rate limit reached (HTTP 429)${retryAfter ? `; retry after ${retryAfter}s` : ''}.`);
    error.httpStatus = response.status;
    error.lodgifyError = safeLodgifyError;
    throw error;
  }
  if (!response.ok) {
    const error = new Error(`Lodgify GET ${pathname} failed (HTTP ${response.status}).`);
    error.httpStatus = response.status;
    error.lodgifyError = safeLodgifyError;
    throw error;
  }

  try {
    return await response.json();
  } catch {
    throw new Error(`Lodgify GET ${pathname} returned malformed JSON.`);
  }
}

function listProperties() {
  return getAllowed('/v2/properties', { page: 1, size: 100, includeCount: false });
}

function listPropertyRooms(propertyId) {
  return getAllowed(`/v2/properties/${encodeURIComponent(propertyId)}/rooms`);
}

function getAvailability(propertyId, roomTypeId, start, end) {
  return getAllowed(
    `/v2/availability/${encodeURIComponent(propertyId)}/${encodeURIComponent(roomTypeId)}`,
    {
      start: `${start}T00:00:00.000Z`,
      end: `${end}T23:59:59.999Z`,
      includeDetails: false,
    },
  );
}

function getRates(propertyId, roomTypeId, start, end) {
  return getAllowed('/v2/rates/calendar', {
    houseId: propertyId,
    roomTypeId,
    startDate: start,
    endDate: end,
  });
}

function getQuote(propertyId, roomTypeId, arrival, departure) {
  // Follow Lodgify's explicit curl example; the autogenerated object examples are invalid.
  return getAllowed(
    `/v2/quote/${encodeURIComponent(propertyId)}`,
    {
      arrival: `${arrival}T00:00:00.000Z`,
      departure: `${departure}T00:00:00.000Z`,
      'roomTypes[0].Id': roomTypeId,
      'roomTypes[0].People': ADULTS,
      'roomTypes[0].guest_breakdown.adults': ADULTS,
      'roomTypes[0].guest_breakdown.pets': 0,
    },
    { captureSafeError: true },
  );
}

function safeErrorText(value, maximumLength) {
  if (typeof value !== 'string' && typeof value !== 'number') return undefined;
  const sanitized = String(value)
    .replace(/[\r\n\t]+/g, ' ')
    .replace(/[A-Za-z0-9_-]{32,}/g, '[redacted]')
    .trim();
  return sanitized ? sanitized.slice(0, maximumLength) : undefined;
}

async function readSafeLodgifyError(response) {
  let payload;
  try {
    payload = await response.json();
  } catch {
    return undefined;
  }
  if (!payload || typeof payload !== 'object' || Array.isArray(payload)) return undefined;
  const source = payload.error && typeof payload.error === 'object' && !Array.isArray(payload.error)
    ? payload.error
    : payload;
  const code = safeErrorText(
    source.error_code ?? source.errorCode ?? source.code,
    80,
  );
  const message = safeErrorText(
    source.error_message ?? source.errorMessage ?? source.message
      ?? (typeof payload.error === 'string' ? payload.error : undefined),
    300,
  );
  return code || message ? { code, message } : undefined;
}

function arrayFrom(payload, labels) {
  if (Array.isArray(payload)) return payload;
  if (payload && typeof payload === 'object') {
    for (const label of labels) if (Array.isArray(payload[label])) return payload[label];
  }
  throw new Error(`Unexpected Lodgify response: expected an array (${labels.join(', ')}).`);
}

function idOf(item) {
  return item?.id ?? item?.propertyId ?? item?.roomTypeId ?? item?.houseId;
}

function nameOf(item) {
  return item?.name ?? item?.title ?? item?.internalName ?? '(unnamed)';
}

function isoDate(date) {
  return date.toISOString().slice(0, 10);
}

function dateOf(item) {
  const value = item?.date ?? item?.day ?? item?.startDate ?? item?.arrival;
  return typeof value === 'string' ? value.slice(0, 10) : undefined;
}

function availabilityOf(item) {
  const value = item?.available ?? item?.isAvailable ?? item?.availability ?? item?.unitsAvailable;
  if (typeof value === 'boolean') return value;
  if (typeof value === 'number') return value > 0;
  return undefined;
}

function amountOf(item) {
  const value = item?.amount
    ?? item?.price_per_day
    ?? item?.pricePerDay
    ?? item?.rate
    ?? item?.price
    ?? item?.nightlyRate;
  return Number.isFinite(Number(value)) ? Number(value) : undefined;
}

function ratesShape(value, depth = 0) {
  if (value === null) return 'null';
  if (Array.isArray(value)) {
    if (depth >= 5) return 'array';
    return value.length ? [ratesShape(value[0], depth + 1)] : [];
  }
  if (typeof value !== 'object') return typeof value;
  if (depth >= 5) return 'object';
  return Object.fromEntries(
    Object.keys(value).sort().map((key) => [key, ratesShape(value[key], depth + 1)]),
  );
}

function failRatesShape(message, payload) {
  console.error(
    'Rates response shape (field names and types only):',
    JSON.stringify(ratesShape(payload), null, 2),
  );
  throw new Error(message);
}

function findRatesContainers(payload) {
  const queue = [payload];
  const seen = new Set();
  const containers = [];
  for (let depth = 0; depth < 3 && queue.length; depth += 1) {
    const level = queue.splice(0);
    for (const candidate of level) {
      if (!candidate || typeof candidate !== 'object' || Array.isArray(candidate) || seen.has(candidate)) continue;
      seen.add(candidate);
      if (Array.isArray(candidate.calendar_items) || Array.isArray(candidate.calendarItems)) {
        containers.push(candidate);
      }
      for (const key of ['data', 'rates', 'rate', 'calendar']) {
        const nested = candidate[key];
        if (nested && typeof nested === 'object' && !Array.isArray(nested)) queue.push(nested);
      }
    }
  }
  return containers;
}

function ratesCurrency(payload, container) {
  const settings = container.rate_settings
    ?? container.rateSettings
    ?? payload?.rate_settings
    ?? payload?.rateSettings
    ?? payload?.data?.rate_settings
    ?? payload?.data?.rateSettings;
  const value = settings?.currency_code
    ?? settings?.currencyCode
    ?? settings?.currency;
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function ratePrices(item) {
  if (Array.isArray(item?.prices)) return item.prices;
  if (Array.isArray(item?.rates)) return item.rates;
  if (item?.price && typeof item.price === 'object') return [item.price];
  if (item?.rate && typeof item.rate === 'object') return [item.rate];
  if (item?.price_per_day !== undefined || item?.pricePerDay !== undefined) return [item];
  return undefined;
}

function rateNumber(item, keys) {
  for (const key of keys) {
    if (item?.[key] === undefined || item[key] === null) continue;
    const value = Number(item[key]);
    return Number.isFinite(value) ? value : undefined;
  }
  return null;
}

function normalizeRateOption(price, payload) {
  const pricePerDay = amountOf(price);
  const minStay = rateNumber(price, ['min_stay', 'minStay', 'minimumStay']);
  const maxStay = rateNumber(price, ['max_stay', 'maxStay', 'maximumStay']);
  const pricePerAdditionalGuest = rateNumber(
    price,
    ['price_per_additional_guest', 'pricePerAdditionalGuest'],
  );
  const additionalGuestsStartsFrom = rateNumber(
    price,
    ['additional_guests_starts_from', 'additionalGuestsStartsFrom'],
  );
  const stayLimitsValid = [minStay, maxStay, additionalGuestsStartsFrom]
    .every((value) => value === null || (Number.isInteger(value) && value >= 0));
  if (
    pricePerDay === undefined
    || pricePerDay < 0
    || pricePerAdditionalGuest === undefined
    || !stayLimitsValid
  ) {
    return failRatesShape('Unexpected Lodgify rates response: malformed price option.', payload);
  }

  const option = {
    pricePerDay,
    minStay,
    maxStay,
    pricePerAdditionalGuest,
    additionalGuestsStartsFrom,
  };
  return option;
}

function effectiveMinimumStay(option) {
  return option.minStay && option.minStay > 0 ? option.minStay : 1;
}

function rateOptionMatches(option, nights) {
  return Number.isInteger(option.minStay)
    && Number.isInteger(option.maxStay)
    && option.minStay >= 0
    && option.maxStay >= 0
    && option.minStay <= option.maxStay
    && option.minStay <= nights
    && nights <= option.maxStay;
}

function normalizeRates(payload, requestedStart, requestedEnd) {
  const containers = findRatesContainers(payload);
  if (containers.length !== 1) {
    return failRatesShape(
      'Unexpected Lodgify rates response: exactly one calendar-items container was required.',
      payload,
    );
  }

  const container = containers[0];
  const calendarItems = container.calendar_items ?? container.calendarItems;
  const defaultCurrency = ratesCurrency(payload, container);
  if (!defaultCurrency) {
    return failRatesShape('Unexpected Lodgify rates response: currency was not found.', payload);
  }

  const start = validIsoDay(requestedStart);
  const end = validIsoDay(requestedEnd);
  if (!start || !end || start > end) throw new Error('Internal rates window is invalid.');

  const normalizedByDate = new Map();
  for (const item of calendarItems) {
    const date = validIsoDay(item?.date);
    if (!date) return failRatesShape('Unexpected Lodgify rates response: calendar item has no valid date.', payload);
    if (date < start || date > end) continue;

    const prices = ratePrices(item);
    if (!prices) {
      return failRatesShape('Unexpected Lodgify rates response: calendar item has no recognized price container.', payload);
    }
    if (prices.length === 0) continue;
    const priceOptions = prices.map((price) => normalizeRateOption(price, payload));
    const rate = { date, currency: defaultCurrency, priceOptions };
    if (priceOptions.length === 1) {
      const option = priceOptions[0];
      rate.amount = option.pricePerDay;
      rate.minimumStay = effectiveMinimumStay(option);
      if (option.maxStay && option.maxStay > 0) rate.maximumStay = option.maxStay;
    }
    if (normalizedByDate.has(date)) {
      return failRatesShape('Unexpected Lodgify rates response: duplicate calendar date.', payload);
    }
    normalizedByDate.set(date, rate);
  }

  const normalized = [...normalizedByDate.values()].sort((left, right) => left.date.localeCompare(right.date));
  if (!normalized.length || new Set(normalized.map((rate) => rate.currency)).size !== 1) {
    return failRatesShape('Unexpected Lodgify rates response: no single-currency nightly rates were found.', payload);
  }
  return normalized;
}

function availabilityShape(value, depth = 0) {
  if (value === null) return 'null';
  if (Array.isArray(value)) {
    if (depth >= 4) return 'array';
    return value.length ? [availabilityShape(value[0], depth + 1)] : [];
  }
  if (typeof value !== 'object') return typeof value;
  if (depth >= 4) return 'object';
  return Object.fromEntries(
    Object.keys(value).sort().map((key) => [key, availabilityShape(value[key], depth + 1)]),
  );
}

function failAvailabilityShape(message, payload) {
  console.error(
    'Availability response shape (field names and types only):',
    JSON.stringify(availabilityShape(payload), null, 2),
  );
  throw new Error(message);
}

function idsMatch(actual, expected) {
  return actual !== undefined && actual !== null && String(actual) === String(expected);
}

function validIsoDay(value) {
  if (typeof value !== 'string') return undefined;
  const day = value.slice(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(day)) return undefined;
  const parsed = new Date(`${day}T00:00:00.000Z`);
  return !Number.isNaN(parsed.valueOf()) && isoDate(parsed) === day ? day : undefined;
}

function availabilityPeriodValue(period) {
  const raw = period?.available;
  const available = typeof raw === 'boolean' ? raw : typeof raw === 'number' ? raw > 0 : undefined;
  if (available === undefined) return undefined;
  const closed = period.closed_period !== null
    && period.closed_period !== undefined
    && period.closed_period !== false;
  return available && !closed;
}

function normalizeAvailability(payload, propertyId, roomTypeId, requestedStart, requestedEnd) {
  const calendars = Array.isArray(payload)
    ? payload
    : ['items', 'availability', 'data'].map((key) => payload?.[key]).find(Array.isArray);
  if (!calendars) {
    return failAvailabilityShape('Unexpected Lodgify availability response: expected a calendar array.', payload);
  }

  const matching = calendars.filter((calendar) => {
    const responsePropertyId = calendar?.property_id ?? calendar?.propertyId;
    const responseRoomTypeId = calendar?.room_type_id ?? calendar?.roomTypeId;
    return idsMatch(responsePropertyId, propertyId) && idsMatch(responseRoomTypeId, roomTypeId);
  });
  if (matching.length !== 1 || !Array.isArray(matching[0]?.periods)) {
    return failAvailabilityShape(
      'Unexpected Lodgify availability response: exactly one matching room-type calendar with periods was required.',
      payload,
    );
  }

  const windowStart = validIsoDay(requestedStart);
  const windowEnd = validIsoDay(requestedEnd);
  if (!windowStart || !windowEnd || windowStart > windowEnd) {
    throw new Error('Internal availability window is invalid.');
  }

  const days = new Map();
  for (const period of matching[0].periods) {
    const periodStart = validIsoDay(period?.start);
    const periodEnd = validIsoDay(period?.end);
    const available = availabilityPeriodValue(period);
    if (!periodStart || !periodEnd || periodStart > periodEnd || available === undefined) {
      return failAvailabilityShape('Unexpected Lodgify availability response: malformed period.', payload);
    }

    const clippedStart = periodStart < windowStart ? windowStart : periodStart;
    const clippedEnd = periodEnd > windowEnd ? windowEnd : periodEnd;
    if (clippedStart > clippedEnd) continue;

    const cursor = new Date(`${clippedStart}T00:00:00.000Z`);
    const last = new Date(`${clippedEnd}T00:00:00.000Z`);
    while (cursor <= last) {
      const date = isoDate(cursor);
      if (days.has(date) && days.get(date).available !== available) {
        return failAvailabilityShape(
          'Unexpected Lodgify availability response: overlapping periods disagree.',
          payload,
        );
      }
      days.set(date, { date, available });
      cursor.setUTCDate(cursor.getUTCDate() + 1);
    }
  }

  const normalized = [];
  const cursor = new Date(`${windowStart}T00:00:00.000Z`);
  const last = new Date(`${windowEnd}T00:00:00.000Z`);
  while (cursor <= last) {
    const date = isoDate(cursor);
    const day = days.get(date);
    if (!day) {
      return failAvailabilityShape(
        'Unexpected Lodgify availability response: periods do not cover the requested window.',
        payload,
      );
    }
    normalized.push(day);
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  return normalized;
}

function findCandidate(availability, rates) {
  const availableByDate = new Map(availability.map((day) => [dateOf(day), day]));
  const rateByDate = new Map(rates.map((day) => [dateOf(day), day]));
  const dates = [...availableByDate.keys()].sort();
  const diagnostics = {
    availableArrivalDays: 0,
    missingArrivalRates: 0,
    nonUniqueArrivalRateRules: 0,
    unavailableStaySpans: 0,
    unpricedStaySpans: 0,
  };
  const finalCalendarDate = dates.at(-1);

  for (const arrival of dates) {
    const arrivalEntry = availableByDate.get(arrival);
    if (!availabilityOf(arrivalEntry)) continue;
    diagnostics.availableArrivalDays += 1;
    const arrivalRate = rateByDate.get(arrival);
    if (!arrivalRate?.priceOptions?.length) {
      diagnostics.missingArrivalRates += 1;
      continue;
    }
    const arrivalDate = new Date(`${arrival}T00:00:00Z`);
    const finalDate = new Date(`${finalCalendarDate}T00:00:00Z`);
    const nightsInWindow = Math.floor((finalDate - arrivalDate) / 86_400_000) + 1;
    for (let nights = 1; nights <= nightsInWindow; nights += 1) {
      const matchingRateOptions = arrivalRate.priceOptions
        .filter((option) => rateOptionMatches(option, nights));
      if (matchingRateOptions.length !== 1) {
        diagnostics.nonUniqueArrivalRateRules += 1;
        continue;
      }
      const stayDates = Array.from({ length: nights }, (_, index) => {
        const date = new Date(arrivalDate);
        date.setUTCDate(date.getUTCDate() + index);
        return isoDate(date);
      });
      if (!stayDates.every((date) => availabilityOf(availableByDate.get(date)))) {
        diagnostics.unavailableStaySpans += 1;
        continue;
      }
      if (!stayDates.every((date) => rateByDate.has(date))) {
        diagnostics.unpricedStaySpans += 1;
        continue;
      }
      const departureDate = new Date(arrivalDate);
      departureDate.setUTCDate(departureDate.getUTCDate() + nights);
      return {
        candidate: {
          arrival,
          departure: isoDate(departureDate),
          nights,
          stayDates,
          selectedRateOption: matchingRateOptions[0],
        },
        diagnostics,
      };
    }
  }
  return { candidate: undefined, diagnostics };
}

function quoteShapeKeyIsSafe(key) {
  return !/(?:^id$|id$|uid|name|description|guest|people|booking|secret|token|key|agreement|policy.*text)/i.test(key);
}

function quoteShape(value, depth = 0) {
  if (value === null) return { type: 'null' };
  if (Array.isArray(value)) {
    return {
      type: 'array',
      items: depth >= 6 || !value.length ? undefined : quoteShape(value[0], depth + 1),
    };
  }
  if (typeof value !== 'object') return { type: typeof value };
  if (depth >= 6) return { type: 'object' };
  return {
    type: 'object',
    fields: Object.fromEntries(
      Object.keys(value)
        .filter(quoteShapeKeyIsSafe)
        .sort()
        .map((key) => [key, quoteShape(value[key], depth + 1)]),
    ),
  };
}

function printQuoteShape(quote) {
  console.log(
    'Quote response shape (types only; sensitive fields omitted):',
    JSON.stringify(quoteShape(quote), null, 2),
  );
}

function quoteSource(quote) {
  if (Array.isArray(quote)) {
    return quote.length === 1 && quote[0] && typeof quote[0] === 'object' ? quote[0] : undefined;
  }
  if (!quote || typeof quote !== 'object') return undefined;
  const nested = quote.quote ?? quote.data ?? quote.result;
  if (Array.isArray(nested)) {
    return nested.length === 1 && nested[0] && typeof nested[0] === 'object' ? nested[0] : undefined;
  }
  return nested && typeof nested === 'object' ? nested : quote;
}

function quoteSummary(quote) {
  printQuoteShape(quote);
  const source = quoteSource(quote);
  if (!source) {
    throw new Error('Unexpected Lodgify quote response: quote result is ambiguous.');
  }

  const currency = source.currency_code ?? source.currencyCode;
  const totalIncludingVat = quoteAmount(source.total_including_vat ?? source.totalIncludingVat);
  const amountGross = quoteAmount(source.amount_gross ?? source.amountGross);
  const totalExcludingVat = quoteAmount(source.total_excluding_vat ?? source.totalExcludingVat);
  const vat = quoteAmount(source.total_vat ?? source.totalVat);
  const verifiedAmountGross = amountGross !== undefined
    && totalExcludingVat !== undefined
    && vat !== undefined
    && quoteAmountsApproximatelyEqual(amountGross, totalExcludingVat + vat)
    ? amountGross
    : undefined;
  const grossCandidates = [totalIncludingVat, verifiedAmountGross]
    .filter((amount) => amount !== undefined);
  if (
    typeof currency !== 'string'
    || !currency.trim()
    || !grossCandidates.length
    || grossCandidates.some((amount) => !quoteAmountsApproximatelyEqual(amount, grossCandidates[0]))
  ) {
    throw new Error('Unexpected Lodgify quote response: gross total or currency is ambiguous.');
  }

  const summary = { currency: currency.trim(), grossTotal: grossCandidates[0] };
  if (totalExcludingVat !== undefined) summary.totalExcludingVat = totalExcludingVat;
  if (vat !== undefined) summary.vat = vat;

  const roomTypes = source.room_types ?? source.roomTypes;
  const directRoomSubtotal = quoteAmount(source.room_subtotal ?? source.roomSubtotal);
  if (directRoomSubtotal !== undefined) {
    summary.roomSubtotal = directRoomSubtotal;
  } else if (Array.isArray(roomTypes) && roomTypes.length) {
    const roomSubtotals = roomTypes.map((roomType) => quoteAmount(roomType?.subtotal));
    if (roomSubtotals.every((amount) => amount !== undefined)) {
      summary.roomSubtotal = roomSubtotals.reduce((total, amount) => total + amount, 0);
    }
  }

  addQuoteAmount(summary, 'addOnsSubtotal', source.add_ons_subtotal ?? source.addOnsSubtotal);
  addQuoteAmount(
    summary,
    'totalScheduledPayments',
    source.total_scheduled_payments ?? source.totalScheduledPayments,
  );
  addQuoteAmount(
    summary,
    'totalToCollectManually',
    source.total_to_collect_manually ?? source.totalToCollectManually,
  );

  return summary;
}

function quoteAmount(value) {
  const amount = Number(value);
  return value !== null && value !== undefined && Number.isFinite(amount) ? amount : undefined;
}

function quoteAmountsApproximatelyEqual(left, right) {
  const tolerance = 0.01 + Number.EPSILON * Math.max(Math.abs(left), Math.abs(right));
  return Math.abs(left - right) <= tolerance;
}

function addQuoteAmount(summary, key, value) {
  const amount = quoteAmount(value);
  if (amount !== undefined) summary[key] = amount;
}

async function main() {
  try {
    const propertiesPayload = await listProperties();
    status.AUTH = 'PASS';
    const properties = arrayFrom(propertiesPayload, ['items', 'properties', 'data']);
    const matches = properties.filter((property) => /\bmaha\b/i.test(nameOf(property)));
    if (matches.length !== 1) {
      console.log('Sanitized properties:', properties.map((property) => ({ id: idOf(property), name: nameOf(property) })));
      status.PROPERTY = 'WARN';
      return fail(`Expected exactly one clear Maha match; found ${matches.length}.`);
    }
    const property = matches[0];
    const propertyId = idOf(property);
    if (propertyId === undefined) throw new Error('Unexpected Lodgify property response: Maha has no ID.');
    status.PROPERTY = 'PASS';
    console.log(`Property: ${nameOf(property)} (${propertyId})`);

    const rooms = arrayFrom(await listPropertyRooms(propertyId), ['items', 'rooms', 'roomTypes', 'data']);
    if (rooms.length !== 1) {
      console.log('Sanitized room types:', rooms.map((room) => ({ id: idOf(room), name: nameOf(room) })));
      status['ROOM TYPE'] = 'WARN';
      return fail(`Expected exactly one Maha room type; found ${rooms.length}.`);
    }
    const roomTypeId = idOf(rooms[0]);
    if (roomTypeId === undefined) throw new Error('Unexpected Lodgify room response: room type has no ID.');
    status['ROOM TYPE'] = 'PASS';
    console.log(`Room type: ${nameOf(rooms[0])} (${roomTypeId})`);

    const startDate = new Date();
    startDate.setUTCDate(startDate.getUTCDate() + 1);
    const endDate = new Date(startDate);
    endDate.setUTCDate(endDate.getUTCDate() + WINDOW_DAYS - 1);
    const start = isoDate(startDate);
    const end = isoDate(endDate);
    const availability = normalizeAvailability(
      await getAvailability(propertyId, roomTypeId, start, end),
      propertyId,
      roomTypeId,
      start,
      end,
    );
    status.AVAILABILITY = 'PASS';

    // Rates Calendar's end date is inclusive. Request the same final stay-night as availability,
    // then use the following day only as checkout departure; it is never summed as a charged night.
    const rates = normalizeRates(await getRates(propertyId, roomTypeId, start, end), start, end);
    status.RATES = 'PASS';
    const availableDays = availability.filter((day) => availabilityOf(day)).length;
    const pricedRates = rates.flatMap((rate) => rate.priceOptions.map((option) => option.pricePerDay));
    const multipleOptionRates = rates.filter((rate) => rate.priceOptions.length > 1);
    console.log('Calendar summary:', {
      window: `${start}..${end} (inclusive)`,
      availableDays,
      unavailableDays: availability.length - availableDays,
      pricedNights: rates.length,
      rateOptions: pricedRates.length,
      multipleOptionDays: multipleOptionRates.length,
      rateCurrency: rates[0].currency,
      rateOptionRange: pricedRates.length ? `${Math.min(...pricedRates)}..${Math.max(...pricedRates)}` : 'unavailable',
    });
    for (const rate of multipleOptionRates.slice(0, 7)) {
      console.log('Rate options:', JSON.stringify({
        date: rate.date,
        optionCount: rate.priceOptions.length,
        currency: rate.currency,
        options: rate.priceOptions.map((option) => ({
          min_stay: option.minStay,
          max_stay: option.maxStay,
          price_per_day: option.pricePerDay,
        })),
      }));
    }
    if (multipleOptionRates.length > 7) {
      console.log(`Rate options: ${multipleOptionRates.length - 7} additional multi-option days omitted.`);
    }

    const candidateSelection = findCandidate(availability, rates);
    const { candidate } = candidateSelection;
    if (!candidate) {
      status.QUOTE = 'WARN';
      status.OVERALL = 'WARN';
      console.warn(
        'No unambiguous stay satisfied contiguous availability and the arrival-date rate rules.',
        candidateSelection.diagnostics,
      );
      return printStatus();
    }
    console.log('Candidate:', {
      arrival: candidate.arrival,
      departure: candidate.departure,
      nights: candidate.nights,
      adults: ADULTS,
      min_stay: candidate.selectedRateOption.minStay,
      max_stay: candidate.selectedRateOption.maxStay,
      price_per_day: candidate.selectedRateOption.pricePerDay,
    });

    try {
      const summary = quoteSummary(await getQuote(propertyId, roomTypeId, candidate.arrival, candidate.departure));
      status.QUOTE = 'PASS';
      status.OVERALL = 'PASS';
      console.log('Quote:', summary);
    } catch (error) {
      const message = error.lodgifyError?.message ?? String(error.message);
      const stayRejected = [400, 409, 422].includes(error.httpStatus) || /minimum|stay|unavailable/i.test(message);
      status.QUOTE = stayRejected ? 'WARN' : 'FAIL';
      status.OVERALL = status.QUOTE;
      if (error.httpStatus) {
        const diagnostic = { httpStatus: error.httpStatus };
        if (error.lodgifyError?.code) diagnostic.lodgifyCode = error.lodgifyError.code;
        if (error.lodgifyError?.message) diagnostic.lodgifyMessage = error.lodgifyError.message;
        console.error(
          stayRejected
            ? 'The candidate was unavailable or rejected by stay rules; no booking was attempted.'
            : 'Quote failed; no booking was attempted.',
          diagnostic,
        );
      } else {
        console.error(stayRejected
          ? `The candidate was unavailable or rejected by stay rules; no booking was attempted. ${message}`
          : `Quote failed: ${message}`);
      }
    }
    printStatus();
  } catch (error) {
    fail(error.message);
  }
}
