import { defineKnowledgeRecommendations } from '../../schema';

export const frigilianaBreakfastRecommendations = defineKnowledgeRecommendations([
  {
    id: 'frigiliana.breakfast.caravansars-coffee',
    destination: 'frigiliana',
    topic: 'breakfast',
    place: { name: 'Caravansar\'s Coffee', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Caravansar%27s+Coffee+Frigiliana' },
    summary: 'This is the most natural pick if you feel like a slower, more modern breakfast with very good coffee and a slightly more curated atmosphere. Especially nice for avocado-based dishes, house-made touches and a peaceful start outside the busiest village flow.',
    access: [{ from: 'casa-amara', distanceMetres: 650 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.breakfast.churreria-chocolateria-alexis',
    destination: 'frigiliana',
    topic: 'breakfast',
    place: { name: 'Churreria Chocolateria Alexis', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Churreria+Chocolateria+Alexis+Frigiliana' },
    summary: 'If you want to try one truly local breakfast ritual, this is the one. Fresh churros with thick hot chocolate are the reason to come here. Great for a classic Andalusian-style morning treat, especially when you want something simple, warm and unmistakably traditional.',
    access: [{ from: 'casa-amara', distanceMetres: 500 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.breakfast.la-tahona-del-zaidin',
    destination: 'frigiliana',
    topic: 'breakfast',
    place: { name: 'La Tahona del Zaidín', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Tahona+del+Zaidin+Frigiliana' },
    summary: 'This is the practical bakery choice when you want something easy, central and uncomplicated. Very good for grabbing fresh pastries, bread or coffee before taking breakfast back home or starting a morning walk through the village.',
    access: [{ from: 'casa-amara', distanceMetres: 150 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.breakfast.cafeteria-faes',
    destination: 'frigiliana',
    topic: 'breakfast',
    place: { name: 'Cafetería Faes', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cafeteria+Faes+Frigiliana' },
    summary: 'A good option for late risers or for mornings that start more with coffee than with a full breakfast table. Best when you want a relaxed coffee-and-snack stop later in the morning rather than an early classic breakfast.',
    access: [{ from: 'casa-amara', distanceMetres: 120 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.breakfast.bar-virtudes',
    destination: 'frigiliana',
    topic: 'breakfast',
    place: { name: 'Bar Virtudes', kind: 'cafe', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bar+Virtudes+Frigiliana' },
    summary: 'This is the one for days when breakfast turns naturally into a late morning stop, almost halfway between breakfast, brunch and an early lunch. Very well placed in the village center, with lovely views and a more social, open village feeling around it.',
    access: [{ from: 'casa-amara', distanceMetres: 260 }],
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and map link only, no operating details are verified.'
  }
]);
