import { defineKnowledgeRecommendations } from '../../schema';

export const frigilianaEssentialsRecommendations = defineKnowledgeRecommendations([
  {
    id: 'frigiliana.essentials.supermarket-silvia',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'Supermarket Silvia', kind: 'shop', address: 'Calle Real 131', placeId: 'ChIJNSM8zbEkcg0RRKFBASEvIPc' },
    summary: 'Supermarket Silvia: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'split',
    basis: 'published-guide-carryover',
    factIds: [
      'frigiliana.shopping.silvia.address-and-range'
    ],
    checkedAt: '2026-08-28',
    reviewAfter: '2027-02-28',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide; the referenced facts bound the verified details, everything else is editorial selection without a dated check.'
  },
  {
    id: 'frigiliana.essentials.la-plazituela',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'La Plazituela “Saboreando la Comarca”', kind: 'shop', mapsUrl: 'https://maps.app.goo.gl/Vtimyw8gijGHRtsX7' },
    summary: 'La Plazituela “Saboreando la Comarca”: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.essentials.tienda-silveria',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'Tienda Silveria', kind: 'shop', mapsUrl: 'https://maps.app.goo.gl/SwRmk8J7nDRTGQzf6' },
    summary: 'Tienda Silveria: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.essentials.eroski-city',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'EROSKI/city Frigiliana', kind: 'shop', address: 'Plaza Doña Amparo Guerrero 10', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Eroski+City+Plaza+Do%C3%B1a+Amparo+Guerrero+10+Frigiliana' },
    summary: 'EROSKI/city Frigiliana: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'split',
    basis: 'published-guide-carryover',
    factIds: [
      'frigiliana.shopping.eroski-city.address'
    ],
    checkedAt: '2026-08-28',
    reviewAfter: '2027-02-28',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide; the referenced facts bound the verified details, everything else is editorial selection without a dated check.'
  },
  {
    id: 'frigiliana.essentials.panaderia-manolo',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'Panadería Manolo', kind: 'shop', mapsUrl: 'https://maps.app.goo.gl/hLqVUPJwWETpmaqLA' },
    summary: 'Panadería Manolo: listed in the AMARA guide as a shop used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.essentials.lavanderia-el-acebuchal',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'Lavandería El Acebuchal', kind: 'service', mapsUrl: 'https://maps.app.goo.gl/SGDiDiLSsXyMmUKY7' },
    summary: 'Lavandería El Acebuchal: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.essentials.moeve-axarquia-laundry',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'Moeve AXARQUIA self-service laundry', kind: 'service', mapsUrl: 'https://maps.app.goo.gl/MivMQoL7q7xPo2dD8' },
    summary: 'Moeve AXARQUIA self-service laundry: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.essentials.unicaja-atm',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'Unicaja ATM', kind: 'service', mapsUrl: 'https://maps.app.goo.gl/AiSbKswr1uxRHu4fA' },
    summary: 'Unicaja ATM: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.essentials.caixabank-atm',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'CaixaBank ATM', kind: 'service', mapsUrl: 'https://maps.app.goo.gl/ZSDZ7xfZCku8i4Gb8' },
    summary: 'CaixaBank ATM: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.essentials.oficina-de-turismo',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'Oficina de Turismo Frigiliana', kind: 'service', mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Oficina+de+Turismo+Frigiliana', phone: '+34952534261' },
    summary: 'Oficina de Turismo Frigiliana: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.essentials.taxi-2-frigiliana',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'Taxi 2 Frigiliana', kind: 'service', phone: '+34696969469' },
    summary: 'Taxi 2 Frigiliana: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  },
  {
    id: 'frigiliana.essentials.taxi-3-frigiliana',
    destination: 'frigiliana',
    topic: 'essentials',
    place: { name: 'Taxi 3 Frigiliana', kind: 'service', phone: '+34616388964' },
    summary: 'Taxi 3 Frigiliana: listed in the AMARA guide as a service used by guests; identity and link only.',
    provenance: 'researched',
    status: 'APPROVED',
    scope: 'amara-experience',
    basis: 'published-guide-carryover',
    checkedAt: '2026-09-05',
    reviewAfter: '2027-03-05',
    volatility: 'medium',
    claimBoundary: 'Carried over from the published guide on 2026-09-05; identity and link only, no operating details are verified.'
  }
]);
