import { defineKnowledgePageManifest } from '../../schema';

export const frigilianaFestivalsKnowledge = defineKnowledgePageManifest({
  id: 'page-frigiliana-festivals', destination: 'frigiliana', topic: 'festivals',
  createdAt: '2026-09-10T09:55:00+02:00', updatedAt: '2026-09-10T09:55:00+02:00', status: 'needs-review',
  driveFolder: { id: '1am0Oi78kux9epFClEeiOrux4krBrh6gI', url: 'https://drive.google.com/drive/folders/1am0Oi78kux9epFClEeiOrux4krBrh6gI', path: 'AMARA – Research Vault/10_LOCATIONS/frigiliana/experiences/festivals' },
  publicContentPath: 'src/content/frigilianaFestivalsContent.ts',
  researchRunIds: ['2026-09-10__085529__frigiliana-festivals-evidence-verification__research-001'],
  coverage: [
    { authoringArea: 'core-calendar-and-seasonality', purpose: 'Anchor the page on the verified recurring calendar and an honest seasonal pattern without guaranteeing quiet months.', factIds: ['frigiliana.festivals.core-calendar-list', 'frigiliana.festivals.seasonal-pattern', 'frigiliana.festivals.quiet-months-not-guaranteed'], status: 'covered' },
    { authoringArea: 'festival-3-culturas', purpose: 'Present the flagship festival: what it is, when, scale, format and the overnight trade-off, without freezing a date or edition number.', factIds: ['frigiliana.festivals.3culturas-established-2006', 'frigiliana.festivals.3culturas-late-august', 'frigiliana.festivals.3culturas-past-dates', 'frigiliana.festivals.3culturas-organiser', 'frigiliana.festivals.3culturas-format', 'frigiliana.festivals.3culturas-large-market', 'frigiliana.festivals.3culturas-uses-whole-core', 'frigiliana.festivals.3culturas-night-and-noise', 'frigiliana.festivals.3culturas-park-shuttle-2026'], status: 'covered', notes: 'Edition number and piromusical position are disputed and must be dropped from evergreen copy (see partial area).' },
    { authoringArea: '3-culturas-editorial-conflicts', purpose: 'Keep the known 3 Culturas conflicts out of evergreen copy.', factIds: ['frigiliana.festivals.3culturas-edition-number-disputed', 'frigiliana.festivals.3culturas-piromusical-position-disputed'], status: 'partial', notes: 'Drop edition number and any fixed piromusical position; name only in the live programme.' },
    { authoringArea: 'religious-and-patronal-fiestas', purpose: 'Cover San Sebastián, Carnaval, Semana Santa, Cruces de Mayo and Feria de San Antonio with fixed feast days separated from movable programmes.', factIds: ['frigiliana.festivals.san-sebastian', 'frigiliana.festivals.carnaval', 'frigiliana.festivals.semana-santa', 'frigiliana.festivals.semana-santa-soledad-and-crowds', 'frigiliana.festivals.cruces-de-mayo', 'frigiliana.festivals.feria-san-antonio'], status: 'covered' },
    { authoringArea: 'gastronomic-dia-de-la-miel', purpose: 'Cover Día de la Miel as a no-fixed-day daytime event without promising a specific edition or factory opening.', factIds: ['frigiliana.festivals.dia-miel', 'frigiliana.festivals.dia-miel-2026-disputed'], status: 'partial', notes: '2026 execution unresolved; never promise factory opening/tastings for an upcoming edition.' },
    { authoringArea: 'overnight-noise-guidance', purpose: 'Give honest quiet-stay guidance: which festivals are the red zones and what kind of disruption each brings.', factIds: ['frigiliana.festivals.3culturas-night-and-noise', 'frigiliana.festivals.feria-noise', 'frigiliana.festivals.cruces-de-mayo', 'frigiliana.festivals.carnaval', 'frigiliana.festivals.semana-santa-soledad-and-crowds'], status: 'covered', notes: 'Cross-cutting guest-impact framing; exact house exposure depends on the year layout.' },
    { authoringArea: 'candelarias-status', purpose: 'Keep Candelarias as a historic/intermittent tradition, not a travel anchor.', factIds: ['frigiliana.festivals.candelarias'], status: 'partial', notes: 'Recommend only after current municipal confirmation; absent from the official core list.' },
    { authoringArea: 'traffic-closures-and-parking', purpose: 'Guest Utility: per-festival road closures, parking bans and resident access.', factIds: ['frigiliana.festivals.3culturas-park-shuttle-2026'], status: 'gap', notes: 'Only 3 Culturas has concrete 2026 shuttle/parking evidence; other festivals need the annual Policía Local/Ayuntamiento traffic order per year.' },
  ],
});
