import { defineKnowledgePageManifest } from '../../schema';

export const frigilianaBeachesKnowledge = defineKnowledgePageManifest({
  id: 'page-frigiliana-beaches',
  destination: 'frigiliana',
  topic: 'beaches-day-connections',
  createdAt: '2026-08-28T16:30:00+02:00',
  updatedAt: '2026-08-28T16:30:00+02:00',
  status: 'needs-review',
  driveFolder: {
    id: '1FxPa56b3GnZt8XwUUcx5qEnlscUbjvA6',
    url: 'https://drive.google.com/drive/folders/1FxPa56b3GnZt8XwUUcx5qEnlscUbjvA6',
    path: 'AMARA – Research Vault/00_INBOX/2026-08-28__092356__nerja-frigiliana-beaches-connections__research-001',
  },
  publicContentPath: 'src/content/frigilianaBeachesContent.ts',
  researchRunIds: ['2026-08-28__092356__nerja-frigiliana-beaches-connections__research-001'],
  coverage: [
    {
      authoringArea: 'hero-and-coast-choice',
      purpose: 'Help guests based in Frigiliana choose a coast day by access, setting and desired rhythm rather than a generic ranking.',
      factIds: [
        'nerja.beaches.burriana.profile-and-listed-services',
        'nerja.beaches.playazo.profile-and-listed-services',
        'nerja.beaches.maro.profile-and-seasonal-access',
        'nerja.beaches.calahonda.stair-access',
        'nerja.beaches.cantarrijan.location-and-seasonal-access',
      ],
      status: 'partial',
      notes: 'Five current beach choices have a bounded official baseline. Drive time from Frigiliana, general parking, shade, sea conditions and couple suitability are not established for all six.',
    },
    {
      authoringArea: 'carabeillo',
      purpose: 'Describe Carabeíllo only if its access, setting and current facilities can be verified.',
      factIds: [],
      status: 'gap',
      notes: 'The current public card and first-person quiet-swim recommendation have no normalized fact owner.',
    },
    {
      authoringArea: 'el-playazo',
      purpose: 'Explain the official semi-urban profile and listed services without promising space or parking.',
      factIds: [
        'nerja.beaches.playazo.profile-and-listed-services',
        'nerja.beaches.accessibility-points-2026',
        'nerja.beaches.blue-flags-2026',
      ],
      status: 'partial',
      notes: 'The official profile is covered; the current first-person favourite-picnic recommendation and quieter-position advice need first-party evidence.',
    },
    {
      authoringArea: 'playa-de-maro',
      purpose: 'Present the isolated beach profile and dated seasonal access regime.',
      factIds: [
        'nerja.beaches.maro.profile-and-seasonal-access',
        'nerja.beaches.maro.shuttle-2026',
        'nerja.beaches.blue-flags-2026',
      ],
      status: 'partial',
      notes: 'Access is supported for 2026; clear-water, snorkelling, kayak and waterfall claims require their own evidence and conditions boundary.',
    },
    {
      authoringArea: 'cantarrijan',
      purpose: 'Explain that Cantarriján is a protected-area coast choice in Granada province with seasonal controlled access.',
      factIds: [
        'nerja.beaches.cantarrijan.location-and-seasonal-access',
        'nerja.beaches.cantarrijan.controlled-access-2026',
      ],
      status: 'partial',
      notes: 'Location and 2026 access are covered; clothing-optional atmosphere, restaurant operation, fresh seafood and suitability claims are not.',
    },
    {
      authoringArea: 'calahonda',
      purpose: 'Explain the central old-town relationship and the official stair-access constraint.',
      factIds: ['nerja.beaches.calahonda.stair-access'],
      status: 'partial',
      notes: 'The stair approach is supported; current public timing, calm-water, crowd and first-person recommendations are not.',
    },
    {
      authoringArea: 'burriana',
      purpose: 'Describe the urban full-service profile and its suitability for a beach-and-lunch day.',
      factIds: [
        'nerja.beaches.burriana.profile-and-listed-services',
        'nerja.beaches.accessibility-points-2026',
        'nerja.beaches.blue-flags-2026',
        'nerja.restaurants.ayo.burriana-daytime-service-2026',
      ],
      status: 'partial',
      notes: 'The official service profile and AYO daytime role are supported; availability, exact beach-day sequence and personal date-day endorsement are not.',
    },
    {
      authoringArea: 'conditions-and-timing',
      purpose: 'Separate durable beach profiles from current sea state, wind, crowding and water-activity decisions.',
      factIds: [],
      status: 'gap',
      notes: 'No normalized live sea-state method, seasonal crowd evidence or waterfall-condition evidence currently supports this section.',
    },
    {
      authoringArea: 'access-and-practical-planning',
      purpose: 'Use dated official access and accessibility information without freezing it into a future season.',
      factIds: [
        'nerja.beaches.maro.profile-and-seasonal-access',
        'nerja.beaches.maro.shuttle-2026',
        'nerja.beaches.accessibility-points-2026',
        'nerja.beaches.cantarrijan.location-and-seasonal-access',
        'nerja.beaches.cantarrijan.controlled-access-2026',
      ],
      status: 'partial',
      notes: 'The dated access regimes are covered. Parking availability, arrival-before-10 advice, equipment rental and future-year operation require live checks.',
    },
    {
      authoringArea: 'food-by-the-beach',
      purpose: 'Connect a beach to food only when the venue is actually at that beach and serves the relevant daypart.',
      factIds: [
        'nerja.beaches.burriana.profile-and-listed-services',
        'nerja.restaurants.ayo.burriana-daytime-service-2026',
      ],
      status: 'partial',
      notes: 'AYO/Burriana is supported as a dated daytime pairing. Cantarriján restaurants and central-Nerja post-beach combinations are not yet normalized.',
    },
    {
      authoringArea: 'amara-base-and-return',
      purpose: 'Explain the Frigiliana-base or Nerja-base consequence only with verified property and route evidence.',
      factIds: [],
      status: 'gap',
      notes: 'The current 200-metre AMARA Playa statement and the Frigiliana-to-coast/return sequence require property and route facts before projection.',
    },
    {
      authoringArea: 'weather-hiking-and-nerja-transitions',
      purpose: 'Create only the bounded next guest question that the target owner can answer.',
      factIds: ['frigiliana.climate.regional-proxy.seasonal-contrast'],
      status: 'partial',
      notes: 'Seasonal climate can frame the choice; current beach conditions, same-day hike pairing and Nerja evening continuation require additional evidence.',
    },
  ],
});
